= TinyMCE 6.0 Release Notes

# tag::core-changes[]
[id=core-changes]
== Core changes

{productname} 6.0 now requires a browser capable of running https://tc39.es/ecma262/2020/[ECMAScript 2020] (ES2020).

NOTE: In particular, this means {productname} 6.0 does not support Internet Explorer 11.

Also, no Premium Plugins being released with {productname} 6.0 are backwards compatible with earlier versions of {productname}.
# end::core-changes[]

# tag::things-we-renamed[]
[id=things-we-renamed]
== Things we renamed
|===
| old name                         | new name                         | element                             | notes                                                                                                                                                                                                                                                                                                         | for more information                               |

| `blockformats`                   | `blocks`                         | Menu item                           | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `formatselect`                   | `blocks`                         | Toolbar item                        | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `imagetools`                     | `editimage`                      | Plugin                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `imagetools_toolbar`             | `editimage_toolbar`              | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `imagetools_proxy`               | `editimage_proxy`                | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `imagetools_cors_hosts`          | `editimage_cors_hosts`           | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `imagetools_credentials_hosts`   | `editimage_credentials_hosts`    | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `imagetools_fetch_image`         | `editimage_fetch_iamge`          | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `imagetools_api_key`             | `editimage_api_key`              | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `images_upload_timeout`          | `editimage_upload_timeout`       | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                   | see <<new-and-improved-plugins-imagetools>>        |

| `editimage_proxy`                | `export_image_proxy_service_url` | Option                              | Renamed for easier configuration when used with https://tiny.cloud/docs/enterprise/server/[Tiny services].                                                                                                                                                                                                    |                                                    |

| `fire()`                         | `dispatch()`                     | Function                            | The `fire()` function in `tinymce.Editor`, `tinymce.dom.EventUtils`, `tinymce.dom.DOMUtils`, `tinymce.util.Observable` and `tinymce.util.EventDispatcher` has been re-named to `dispatch()`. `fire` has been aliased to `dispatch` but has also been marked as _deprecated_.                                  |                                                    |

| `font_formats`                   | `font_family_formats`            | Option                              | No behavioural changes, but there are related toolbar and menu items changes.                                                                                                                                                                                                                                 |                                                    |

| `fontselect`                     | `fontfamily`                     | Toolbar item                        | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `fontformats`                    | `fontfamily`                     | Menu item                           | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `fontsize_formats`               | `font_size_formats`              | Option                              | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `fontsizeselect`                 | `fontsize`                       | Toolbar item                        | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `fontsizes`                      | `fontsize`                       | Menu item                           | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `getWhiteSpaceElements()`        | `getWhitespaceElements()`        | Function                            | This function is part of the `Schema` API. It was renamed as part of a general renaming that treats _Whitespace_ as a single word. The behaviour of the function has not changed.                                                                                                                             |                                                    |

| `getShortEndedElements`          | `getVoidElements`                | API                                 | `special` and `void` are hard-coded elements defined by the HTML parsing specification. They can not be changed at run-time. The previous API name did not make it clear it was these, hard-coded, elements being called.                                                                                     |                                                    |

| `content`                        | `html`                           | Command                             | This `mceInsertClipboardContent` argument was re-named to better reflect what data is passed. NB: The `content` argument can no longer be used with `mceInsertClipboardContent`. If `content` is used, no data is passed.                                                                                     | see <<changed-plugins-paste>>                      |

| `linheight_formats`              | `line_height_formats`            | Option                              | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `default_link_target`            | `link_default_target`            |                                     | Changed for consistency with other `link` and `autolink` options. Their functionality, and the values they can take remain unchanged. This change applies to both `link` and `autolink` plugins.                                                                                                              |                                                    |

| `rel_list`                       | `link_rel_list`                  |                                     | Changed for consistency with other options. The functionality, and the values this option can take remain unchanged.                                                                                                                                                                                          |                                                    |

| `target_list`                    | `link_target_list`               |                                     | Changed for consistency with other options. The functionality, and the values this option can take remain unchanged.                                                                                                                                                                                          |                                                    |

| `mceInsertTable`                 | `mceInsertTableDialog`           |                                     | Use `mceInsertTableDialog` to open the _Insert Table_ dialog box. NB: `mceInsertTable` (with appropriate arguments) still works to insert a table directly into an existing document. `mceInsertTable` can no longer be used to invoke the _Table_ dialog box, however.                                       | see <<changed-plugins-table>>                      |

| `noneditable_noneditable_class`  | `noneditable_class`              |                                     | After upgrading, rename the options in your {productname} init configuration to match the new name. For example, `noneditable_noneditable_class: 'mceNonEditable'` must be renamed `noneditable_class: 'mceNonEditable'`.                                                                                     | see <<changed-plugins-noneditable>>                |

| `noneditable_editable_class`     | `editable_class`                 |                                     | After upgrading, rename the options in your {productname} init configuration to match the new name. For example, `noneditable_editable_class: 'mceEditable'` must be renamed `editable_class: 'mceEditable'`.                                                                                                 | see <<changed-plugins-noneditable>>                |

| `styleselect`                    | `styles`                         | Toolbar item                        | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `formats`                        | `styles`                         | Menu item                           | No behavioural changes.                                                                                                                                                                                                                                                                                       |                                                    |

| `textpattern_patterns`           | `text_patterns`                  | Option                              | After upgrading, rename the options in your {productname} init configuration to match the new name. Also, remove `textpattern` from your plugins list. This name-change is consequent to `textpattern` being changed from a Plugin to being part of the {productname} Core.                                   | see <<changed-plugins-textpattern>>                |

| `tinymce.Env.browser.isChrome`   | `tinymce.Env.browser.isChromium` | API                                 | Updated so the `Sand` and `Env` APIs better reflect what they are checking for. `isChrome` implies they are checking for _Google Chrome_. They are actually checking for any Chromium-based browser (eg Chromium, Google Chrome, or Chrome Edge) so `isChromium` more accurately reflects what is being done. |                                                    |

| `tinymce.Env.os.isOSX`           | `tinymce.Env.os.isMacOS`         | API                                 | Updated so the `Sand` and `Env` APIs now use the current name of Apple’s desktop operating system when checking to see if a device’s OS is, in fact, macOS.                                                                                                                                                   |                                                    |

| `toc`                            | `tableofcontents`                | Plugin, Menu item, and Toolbar item | This presents in both the menu item and the toolbar’s tooltip text. NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                       | see <<new-and-improved-plugins-table-of-contents>> |

| `tocupdate`                      | `tableofcontentsupdate`          | Toolbar item                        | This presents in the toolbar’s tooltip text. NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                              | see <<new-and-improved-plugins-table-of-contents>> |

| `toc_class`                      | `tableofcontents_class`          | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                           | see <<new-and-improved-plugins-table-of-contents>> |

| `toc_depth`                      | `tableofcontents_depth`          | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                           | see <<new-and-improved-plugins-table-of-contents>> |

| `toc_header`                     | `tableofcontents_header`         | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                                                           | see <<new-and-improved-plugins-table-of-contents>> |
|===

- *Commands* are what is passed via the `theeditor.execCommand()` API.

  Where a Command name has change, calls to `theeditor.execCommand()` API must be changed to match the new name.

- Configuration *Options* are what is passed when initialising the {productname} editor via `tinymce.init`.

  Where an Option name has changed, configurations using that option must be changed to match the new name.

- *Menu items* and *Toolbar items* are *Options* from `tinymce.init` for UI and UX features, such as the {productname} Menu, Toolbar and Contextual Menu.
# end::things-we-renamed[]

# tag::default-value-changes[]
[id=default-value-changes]
== Default value changes

|===
| element                 | old value                   | new value | notes                                                             | for more information                                               |

| `config.height`         | `200px`                     | `400px`   | Changed to improve user experience.                               | see <<ui-and-ux-elements-and-components-editor-text-entry-height>> |

| `element_format`        | _no default value assigned_ | `html`    | Changed as part of modernising {productname}’s default behaviour. |                                                                    |

| `link_default_protocol` | `http`                      | `https`   | Changed as part of modernising {productname}’s default behaviour. |                                                                    |

| {productname} `schema`  | _no default value assigned_ | `html5`   | Changed as part of modernising {productname}’s default behaviour. |                                                                    |

| `table_style_by_css`    | `false`                     | `true`    | Changed as part of modernising {productname}’s default behaviour. | see <<changed-plugins-table>>                                      |

| `table_use_colgroups`   | `false`                     | `true`    | Changed as part of modernising {productname}’s default behaviour. | see <<changed-plugins-table>>                                      |
|===
# end::default-value-changes[]

# tag::previously-deprecated-items-now-removed[]
[id=previously-deprecated-items-now-removed]
== Previously deprecated items now removed

The following elements were previously deprecated and have, with this release, been removed entirely from {productname}.

|===
| item                                  | element       | notes                                                                              |

| `$`                                   | API           | `$` was a shorthand function of `DomQuery` and `Sizzle`.                           |

| `addComponents`                       | API           | From `AddOnManager`.                                                               |

| `autoresize_on_init`                  | Option        |                                                                                    |

| `block_elements`                      | Schema option |                                                                                    |

| `boolean_attributes`                  | Schema option |                                                                                    |

| `Class`                               | API           |                                                                                    |

| `clearInterval`                       | API           | From `Delay`.                                                                      |

| `clearTimeout`                        | API           | From `Delay`.                                                                      |

| `Color`                               | API           |                                                                                    |

| `content_editable_state`              | Option        |                                                                                    |

| `debounce`                            | API           | From `Delay`.                                                                      |

| `dependencies`                        | API           | From `AddOnManager`.                                                               |

| `DomQuery`                            | API           |                                                                                    |

| `editor_deselector`                   | Option        | From `EditorManager`.                                                              |

| `editors`                             | Property      | From `EditorManager`.                                                              |

| `editor_selector`                     | Option        | From `EditorManager`.                                                              |

| `elements`                            | Option        | From `EditorManager`.                                                              |

| `execCallback`                        | API           |                                                                                    |

| `file_browser_callback_types`         | Option        |                                                                                    |

| `filepicker_validator_handler`        | Option        | Superseded by `file_picker_validator_handler`.                                     |

| `force_hex_style_colors`              | Option        |                                                                                    |

| `force_p_newlines`                    | Option        | Superseded by `forced_root_block`.                                                 |

| `forced_root_black: false`            | Option        | `forced_root_black` must be a non-empty string and cannot take a value of `false`. |

| `gecko_spellcheck`                    | Option        | Replaced by `browser_spellcheck`.                                                  |

| `images_dataimg_filter`               | Option        |                                                                                    |

| `JSON`                                | API           |                                                                                    |

| `JSONP`                               | API           |                                                                                    |

| `JSONRequest`                         | API           |                                                                                    |

| `mode`                                | Option        | From `EditorManager`.                                                              |

| `move_caret_before_on_enter_elements` | Schema option |                                                                                    |

| `non_empty_elements`                  | Schema option |                                                                                    |

| `padd_empty_with_br`                  | Option        |                                                                                    |

| `requestAnimationFrame`               | API           | From `Delay`.                                                                      |

| `self_closing_elements`               | Schema option |                                                                                    |

| `setIconStroke`                       | API           |                                                                                    |

| `setInterval`                         | API           | From `Delay`.                                                                      |

| `setMode`                             | API           |                                                                                    |

| `setTimeout`                          | API           | From `Delay`.                                                                      |

| `short_ended_elements`                | Schema option |                                                                                    |

| `Sizzle`                              | API           |                                                                                    |

| `special`                             | Schema option |                                                                                    |

| `text_block_elements`                 | Schema option |                                                                                    |

| `text_inline_elements`                | Schema option |                                                                                    |

| `throttle`                            | API           | From `Delay`.                                                                      |

| `toolbar_drawer`                      | Option        | Superseded by `toolbar_mode`.                                                      |

| `types`                               | Option        | From `EditorManager`.                                                              |

| `whitespace_elements`                 | Schema option |                                                                                    |

| `validate`                            | Schema option |                                                                                    |

| `XHR`                                 | API           | Any remaining `XHR` users have been replaced with `fetch`.                         |
|===
# end::previously-deprecated-items-now-removed[]

# tag::previously-undocumented-items-removed-without-prior-deprecation[]
[id=previously-undocumented-items-removed-without-prior-deprecation]
== Previously undocumented items removed without prior deprecation

The following elements were never documented and have never been formally supported.

Consequently, they were removed with this release without deprecation notices being provided in earlier releases.

|===
| item                                     | element       |

| `editor.editorCommands.hasCustomCommand` | API           |

| `mceResetDesignMode`                     | Command       |

| `mceRepaint`                             | Command       |

| `mceBeginUndoLevel`                      | Command       |
|===
# end::previously-undocumented-items-removed-without-prior-deprecation[]

# tag::known-issue[]
[id=known-issue]
== Known issue

=== If `nonbreaking_force_tab: true` pressing the tab key in a table cell produces an unexpected result

In {productname} 6.0, if `nonbreaking_force_tab` is set to `true`, pressing the _tab_ key when the insertion point is in a table cell produces an unexpected result.

The expected result is for the insertion point to move to the next available cell in the table.

In {productname} 6.0, three non-breaking-space entities (`&nbsp;&nbsp;&nbsp;`) are entered into the current cell.

The proximate cause of this incorrect behaviour is the move of _Tables_ from plugins to core.

As of this release, however, the specific cause is still being investigated.

And no workaround (other than keeping `nonbreaking_force_tab` set to `false`) is currently available.
# end::known-issues[]



[id=apis]
== APIs

[id=new-and-improved-apis]
=== new and improved APIs

==== `editor.annotator.removeAll`

The new `editor.annotator.removeAll` API replaces the `removeAll` function built-in to the comments plugin.


==== `editor.options` and `tinymce.activeEditor.options`

The new `editor.options` API replaces two old APIs: `editor.settings` and `editor.getParam`.

Along with this new API, the new `tinymce.activeEditor.options` registry replaces `tinymce.activeeditor.settings`.


==== `editor.uploadImages()`

The `editor.uploadImages()` API now includes a `remove` flag.

The flag returns `true` when an image being uploaded is removed after failing to upload.


==== `FakeClipboard`

The new `FakeClipboard` API provides a means for storing state that can be set and accessed by plugins and the core editor.

`FakeClipboard` is implemented on the {productname} global, allowing anything to write to it and read from it.


==== `Resource.unload`

The new `Resource.unload` API makes it possible to unload resources in the resource loader.

This allows tests, such as `ImageEmojiTest`, to remove existing databases before loading their own.


==== `setData` method in dialog API

The dialog API’s `setData` method now uses a deep merge algorithm.

Consequently, it now supports partial nested objects.


==== success or failure callbacks replaced by `Promise` in multiple APIs

* Previously, the AddOnManager, PluginManager, ScriptLoader, StyleSheetLoader, and ThemeManager APIs report resource loading status with `success` or `failure` callbacks.

  These APIs now, instead, return a `Promise`, with a value of either `resolve` or `reject`.
  
  Also, `EditorUpload`, which already returns a `Promise`, had callbacks removed.


=== Changed APIs

==== `closeButton` and `timeout`

* Previously, using `closeButton` to disable a _Notification’s_ close button required a `timeout` value to also be set.

  In {productname} 6, `closeButton` shows or hides the close button regardless of a `timeout` value being set or not set.

  Equivalently, setting a `timeout` value sets how long the notification presents before automatically closing, regardless of whether a close button is displayed or not.


==== `disabled` functions re-named in all {productname} APIs

Previously, multiple {productname} APIs and UI classes used `disable` or `disabled` in their function or property names.

In {productname} 6, these function names have been changed and configuration changes are required.

1. `isDisabled()` functions are now `isEnabled() functions.

2. The `enable()` and `disable()` functions are now the single `setEnabled(<state>)` function.

3. The `disable(<name>)` and `enable(<name>)` functions are now the single `setEnabled(<name>, <state>)` function in the Dialog APIs.

As well, the `.disabled` property is now the `.enabled` property in all {productname} UI classes.


==== `dom.DOMUtils`

The `toHex` function has been removed from `dom.DOMUtils`.


==== `DomParser`

The `filterNode` method has been removed from the `DomParser` API.

As well, the `DomParser` API no longer uses a custom parser internally and instead uses the https://developer.mozilla.org/en-US/docs/Web/API/DOMParser[native `DOMParser` API].


==== `editor.SetContent`

The `editor.SetContent` event’s `content` property has been deprecated.


==== `Env`

The following methods have been removed from the `Env` API:

* `opera`

* `webKit`

* `ie`

* `gecko`

* `mac`

* `iOS`

* `android`

* `desktop`

* `contentEditable`

* `caretAfter`

* `range`

* `ceFalse`

* `experimentalShadowDom`

* `fileApi`

Note, in particular, the removal of all legacy browser detection methods.


==== `fire` functions re-named in all {productname} APIs

The `fire()` function in `tinymce.Editor`, `tinymce.dom.EventUtils`, `tinymce.dom.DOMUtils`, `tinymce.util.Observable` and `tinymce.util.EventDispatcher` has been re-named to `dispatch()`.

`fire` has been aliased to `dispatch` but has also been marked as _deprecated_.


=== Fixed APIs

==== `editor.annotator.remove`

Previously, `editor.annotator.remove` scrolled to the removed material’s position when removing an annotation.

It did not, as expected, retain the current selection or insertion point position in the {productname} editor.

With this release, `editor.annotator.remove` does not change the change the selection or insertion point position after removing an annotation.


==== `editor.fire()`

Previously, if the {productname} editor was removed, the `editor.fire()` API returned an incorrect object.

In {productname} 6.0, `editor.fire()` returns the correct object even when the editor is removed.


==== `editor.selection.getContent()`

The `no_events` argument is Boolean. If set to `true`, events should not fire when `getContent` is called. Previously, `editor.selection.getContent()` did not respect this.

In {productname} 6.0, `editor.selection.getContent()` treats the `no_events` setting as expected: when set to `false`, events are fired; when set to `true`, events are not fired.



[id=removed-or-deprecated-apis]
=== Removed or deprecated APIs


==== `html.Styles`

The `toHex` function has been removed from `html.Styles`.


[id=removed-or-deprecated-apis-saxparser]
==== `SaxParser`

With all filtering moved to the `DomParser` API, the `SaxParser` API has been removed.


[id=removed-or-deprecated-apis-tables]
==== Table

* The `table` plugin’s functionality is, as of {productname} 6.0, entirely focussed on the user interface (UI) for creating and editing tables.

  The code that generates tables is now a Core part of {productname} 6.0.

  Since the `table` plugin API was entirely concerned with generating tables, it has been removed.


[id=removed-or-deprecated-apis-tinymce.util.promise]
==== `tinymce.util.Promise`

The `tinymce.util.Promise` API has been removed.


== Commands and queries

=== New and improved commands and queries

==== `mceAutocompleterClose` and `mceAutocompleterReload`

As part of moving `autocompleter` from the default `silver` theme to the {productname} core, two new commands are now available: `mceAutocompleterClose` and `mceAutocompleterReload`.


==== mceInsertTableDialog

* `mceInsertTableDialog` is the new command for invoking an _Insert Table_ dialog box.

   The previous command, `mceInsertTable`, no longer works to invoke an _Insert Table_ dialog box: use the `mceInsertTableDialog` command instead.

   The `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user input.


=== Changed commands and queries

==== `element_format`

Previously, `element_format` had no explicit default value. It’s implicit value, however, was `xhtml`.

In {productname} 6.0, `element_format` now has an explicit default value: `html`.

==== `mceAddEditor` and `mceToggleEditor`

Previously, `mceAddEditor` and `mceToggleEditor` used the `editorManager.settings` values to set the `id` and UI and UX options for a new {productname} editor instance.

`editorManager.settings` is not used at all in {productname} 6.

Instead, the `mceAddEditor` and `mceToggleEditor` commands use `id` and `options` values from an object passed when the command is run.

=== Fixed commands and queries

=== Removed or deprecated commands and queries

==== `execCommand`

The `execCommand` handler function has been removed from the `plugin` and `theme` interfaces.


==== `mceInsertRawHTML`

The `mceInsertRawHTML` command has been removed.



== Events

=== New and improved events

==== `AutocompleterStart`, `AutocompleterUpdate` and `AutocompleterEnd`

As part of moving `autocompleter` from the default `silver` theme to the {productname} core, three new events are now available: `AutocompleterStart`, `AutocompleterUpdate` and `AutocompleterEnd`.

Themes can act on the `AutocompleterStart` and `AutocompleterUpdate` events and can call `AutocompleterEnd` to cancel the auto completer.


==== `BeforeSetContent`

The `BeforeSetContent` event now includes the actual serialized content when passing in an `AstNode` to the `editor.setContent`.


==== `ThemeLoadError`

A `ThemeLoadError` event is now fired if the theme fails to load.

// === Changed events

=== Fixed events

==== `beforeinput`

The `beforeinput` event is expected to fire whenever material is added to or removed from a {productname} instance. 

Previously, however, because of overrides in the `DeleteBackspaceKeys.ts` module, the `beforeinput` event did not always fire when expected.

With this release, these over-rides no longer prevent `beforeinput` events firing when expected.


==== `GetContent`

Previously the `GetContent` event did not fire when the `editor.selection.setContent()` API attempted to get `tree` or `text` formatted data.

With this release, the `GetContent` event fires as expected when `editor.selection.setContent()` attempts this.

NOTE: The `editor.selection.setContent()` API only supports the `html` and `raw` formats. It does not support `tree` or `text` formats. To create a tree to pass in to `editor.selection.setContent()`, use the `new tinymce.html.Node()` API, or parse to a tree using `editor.parser.parse(html)`.


==== `input`

The `input` event is expected to fire whenever material is deleted from a {productname} instance. 

Previously, however, because of over-rides in the `DeleteBackspaceKeys.ts` module, when more than one line was deleted, the `input` event did not fire.

With this release, these over-rides no longer prevent an `input` event firing when multiple lines are deleted, as expected.


// === Removed or deprecated events


== Formatting

// === New and improved formatting


// === Changed formatting


// === Fixed formatting


// === Removed or deprecated formatting


== Functions

// new and improved

// changed

// fixed

=== Removed or deprecated functions

==== `execCommand`




== Options

//=== New and improved options

=== Changed options

==== `image_upload_handler

Previously the `images_upload_handler` option passed `success` or `failure` callbacks to report the status of an image upload.

In {productname} 6, `images_upload_handler` reports upload results by returning a `Promise`, with a value of either `resolve` or `reject`.


==== link_default_protocol

The `link_default_protocol` option sets the link protocol used by links added or edited using the _link_ dialog.

It now defaults to `https`. Previously it defaulted to `http`.

NOTE: the `link_default_protocol` value is only applied to an edited or inserted link if the protocol is not explicitly specified.

==== tinymce.activeEditor.options.get

Previously `tinymce.activeEditor.options.get('plugins')` returned the configured plugins as a string.

As of {productname} 6, `tinymce.activeEditor.options.get('plugins')` now returns the configured plugins as an array.



=== Fixed options

=== Added options

=== Removed or deprecated options

[id=removed-or-deprecated-options-textpattern]
==== TextPattern

* the `textpattern_patterns` option is no longer an option. It is has been re-named, to `text_patterns` and is now a Core part of {productname} 6.0.

   All references to `textpattern_patterns` (and `text_patterns`) should be removed from your configurations.

*  Also, the API called `textpattern` has been removed.

*  Finally, text patterns are now on by default. `text_patterns: false` turns the functionality off.







== Parsing and serialisation

=== changed parsing and serialisation

==== RGB colors no longer converted to hex values

With the removal of the, now deprecated, `toHex` APIs, RGB colors are no longer converted to hex values when parsing or serializing content.

[id=plugins]
== Plugins

=== Plugin loading format change

{productname} 6.0 allows plugin loading in any of three formats:

1. An array of strings:

   `plugins: [ 'advlist', 'list', 'image', 'help', 'wordcount' ]`

2. A space-separated string:

   `plugins: 'advlist list image help wordcount'`
   
3. A comma-separated string:

   `plugins: 'advlist,list,image,help,wordcount'`

Previously, two other formats were allowed: comma-separated strings with spaces and arrays of space-separated strings.

Neither of these formats are allowed in {productname} 6.0.


[id=new-and-improved-plugins]
=== New and improved plugins

[id=new-and-improved-plugins-imagetools]
==== EditImage

_EditImage_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin], replaces the now-deprecated and removed _ImageTools_ plugin. The `imagetools` plugin is no longer part of the Core open source editor.

An `editimage` options were also re-named: `editimage_proxy` is now `editimage_proxy_service_url`, making it easier to configure when accessing https://tiny.cloud/docs/enterprise/server/[Tiny-specific services].

`editimage` also offers a new export plugin option: `export_image_proxy_service_url`.

NOTE: `editimage_proxy` (the re-named equivalent to the previous `imagetools_proxy`) is still available as an alternative configuration option for setting up image proxy functionality without using Tiny services.


[id=new-and-improved-plugins-emoticons]
==== Emoticons

* The `emoticon` plugin now uses the more accurate word, _Emoji_, in its tool bar, menu item and dialog box.

   In previous versions, the word presented in these parts of the plugin’s user-interface was _Emoticon_.

   NOTE: The plugin, itself, is still called Emoticons. And the plugin description and the plugin’s configuration and Help dialogs still reflect this.


[id=new-and-improved-plugins-table-of-contents]
==== Table of contents

* There are no end-user facing changes between the previous `toc` plugin and the `tableofcontents` plugin. However, the `tableofcontents` plugin now uses https://terser.org[terser] to improve performance.

  NOTE: the `tableofcontents` plugin is no longer part of the Core open source editor. Table of Contents is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].


[id=changed-plugins]
=== Changed plugins

[id=changed-plugins-autoresize]
==== Autoresize

* Previously, the `autoresize` plugin offered an `autoresize_on_init` option.

  This setting does not do anything meaningful, and had been previously deprecated.

  As of {productname} 6.0, it has been removed from the `autoresize` plugin.

[id=changed-plugins-media]
==== Media

* In {productname} 5.x, the `media` plugin used https://tiny.cloud/docs/api/tinymce.html/tinymce.html.saxparser/[SaxParser] to validate elements for parsing.

  As of {productname} 6.0, SaxParser is no longer used. Another {productname} public API — DomParser — is used instead.

  As a consequence the `iframe`, `video`, `audio`, and `object` elements are no longer marked as _special_. Instead their contents are simply validated against the {productname} schema.

NOTE: The {productname} public API, DomParser uses, in turn, the same-named browser parsing API: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser[DomParser].

* The `media` plugin’s `media_scripts` option was deprecated in {productname} 5.10.

// Based on the code it looks like `media_scripts` was meant to be a way to provide an allowed list of <script>s that could be used to embed media. However, somewhere along the lines it broke and no longer works.

  As of the release of {productname} 6.0, this option has been removed completely.

[id=changed-plugins-noneditable]
==== Noneditable

* The `noneditable` plugin is no longer a plugin. It is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `noneditable` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=changed-plugins-paste]
==== Paste

* The `paste` plugin’s functionality is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `paste` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

* The `paste_data_images` option now defaults to `true`. When `paste` was a plugin, this option was, by default, set to `false`, which prevented images being pasted from the local machine.

* The `mceInsertClipboardContent` argument, `content`, has been re-named. It is now `html`.

  The new name is a more accurate reflection of what sort of data the argument passes.

  NOTE: `PastePreProcess` also takes an argument, `content`. This argument, for this command, has not changed.


[id=changed-plugins-print]
==== Print

* `print` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

   In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

   All references to `print` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=changed-plugins-table]
==== Table

* The `table` plugin’s functionality is, as of {productname} 6.0, entirely focussed on the user interface (UI) for creating and editing tables.

  The code that generates tables is now a Core part of {productname} 6.0.

* If the selected cells in the `tfoot` section of a table were header elements (ie were `th` elements), pressing the `table` row header toolbar button (which invokes the `mceTableRowType` command) returned the row as a header row.

  This was incorrect: the section takes precedence and cells in the `tfoot` section of a table should be declared as a footer row.

  In {productname} 6.0, selecting cells in the `tfoot` section of a table and pressing the row header toolbar button returns the row as a footer row, as expected.

* `mceInsertTableDialog` is the new command for invoking an *Insert Table* dialog box.

   The previous command, `mceInsertTable`, no longer works to invoke an *Insert Table* dialog box: use the `mceInsertTableDialog` command instead.

   The `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user-input.

* The default values for the `table_style_by_css` and the `table_use_colgroups` options have both been changed.

  Previously, these options defaulted to `false`. As of {productname} 6.0, both options now default to `true`.

  This is in line with modern web practice.

* the `table_responsive_width` option was previously deprecated and superseded by `table_sizing_mode`.

  In {productname} 6.0, the `table_responsive_width` option has been removed.




[id=fixed-plugins]
=== Fixed plugins

[id-added-plugins]
=== Added plugins

[id=removed-or-deprecated-plugins]
=== Removed or deprecated plugins

[id=removed-or-deprecated-plugins-bbcode]
==== BBCode

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `bbcode` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[id=removed-or-deprecated-plugins-color-picker]
==== Color Picker

* Color Picker’s functionality has been a built in part of {productname} since version 5.

  Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the empty `colorpicker` plugin has now been removed.

[id=removed-or-deprecated-plugins-context-menu]
==== Context Menu

* Context Menu’s functionality has been a built in part of {productname} since version 5.

  Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the empty `contextmenu` plugin has now been removed.

[id=removed-or-deprecated-plugins-full-page]
==== Full Page

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `fullpage` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[id=removed-or-deprecated-plugins-hr]
==== HR

* The `hr` (horizontal rule) functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `hr` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=removed-or-deprecated-plugins-imagetools]
==== ImageTools

* The `imagetools` plugin is no longer part of the Free {productname} editor. _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

[id=removed-or-deprecated-plugins-legacy-output]
==== Legacy Output

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `legacyoutput` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[id=removed-or-deprecated-plugins-paste]
==== Paste

* The `paste` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

* Because the functionality was unmaintained, `paste` no longer supports input from Microsoft Word.

  There is an open https://github.com/tinymce/tinymce/discussions/7487[request for maintainers] should someone in the community be interested in taking over maintainance of this particular functionality as a separate plugin.

  If a community-maintained version of the `paste` plugin becomes available, we will link to it from the xref:6.0-migration-guide.adoc#plugins-paste[_{productname} 6.0 Migration Guide_].

  NOTE: the Premium plugin, https://tiny.cloud/docs/plugins/premium/powerpaste/[`PowerPaste`], is available. It provides the capability to accept data from Microsoft Word and Microsoft Excel, and clean-up the received data before pasting it into place.

[id=removed-or-deprecated-plugins-print]
==== Print

* `print` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

   In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

   All references to `print` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=removed-or-deprecated-plugins-spellchecker]
==== Spellchecker

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `spellchecker` plugin has been removed. It is no longer part of {productname} 6.0.

  The https://tiny.cloud/tinymce/features/#productivity[Premium plugin], https://tiny.cloud/docs/plugins/premium/tinymcespellchecker/[Spellchecker Pro], which offers equivalent functionality and more, is available.

[id=removed-or-deprecated-plugins-tabfocus]
==== TabFocus

* The `tabfocus` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

  The `tabfocus_elements` option, which relied on the `tabfocus` plugin, no longer functions.

  As well, the `tab_focus` option was previously deprecated by `tabfocus_elements`. With this release, the `tab_focus` option has been removed completely.

  As per standard web practice, the `tabindex` attribute should be used instead of the `tabfocus` plugin or any of the `tabfocus` plugin’s options.

  As per that standard web practice, the `tabindex` attribute is copied from the target element to the iframe.

[id=removed-or-deprecated-plugins-table-of-contents]
==== Table of contents

* The `toc` plugin is no longer part of the Core open source editor. _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

   NOTE: although there are no end-user facing changes, as part of the general architectural change, the `tableofcontents` Premium plugin has modernised its output. It uses the ES2020 library and targets ES2018. It also uses https://terser.org[terser] to improve performance.

[id=removed-or-deprecated-plugins-text-color]
==== Text color

* Text color’s functionality has been a built in part of {productname} since version 5.

  Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the empty `textcolor` plugin has now been removed.

[id=removed-or-deprecated-plugins-text-pattern]
==== TextPattern

* The `textpattern` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `textpattern` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

* Also, the API that called `textpattern` has been removed.





== Properties

// new and improved
// changed
// fixed
// added

=== Removed or deprecated properties

==== `editor.settings`

The `editor.settings` property has been replaced by the `Options` API.

It has, consequently, been removed from {productname} 6.0.

==== `fixed`

the `fixed` property has been removed from the `tinymce.html.Node` class.

==== `shortEnded`

the `shortEnded` property has been removed from the `tinymce.html.Node` class.


== Schema

=== New and improved schema

* {productname} 6.0 instances now use HTML 5 as the default schema.

  The previous default was, for practical purposes, also HTML 5 but no specific schema was set. This change formalises and makes explicit what was, previously, only implicit.

  NOTE: `html5-strict` is still an available schema option and is unchanged from {productname} 5.x.

* The assignment operator character — `:` — has been changed to `~` for the `valid_elements` and `extended_valid_elements` schemata.

  The `:` is also used to assign an [xlink:href] rule and this was not possible in these schemata because the colon character was acting as an assignment operator.

  This change allows both schemata to set attribute values for the `valid_elements` and `extended_valid_elements` options using the `~` character and assign [xlink:href] rules as expected.



//=== Changed schema

//=== Fixed schema

//=== Added schema

//=== Removed or deprecated schema


== Strings and Internationalisation

=== Fixed strings

==== color picker dialog

The {productname} color picker presents tool tip labels (also known as aria labels) showing the name of the color the pointer is hovering over.

These labels presented these names in English in multiple instances when they should have presented the names in other languages (eg German).

With this update, these tool tip labels now present in the expected language.


== UI and UX elements and components

=== new and improved UI and UX elements and components

==== `buttonType`

`buttonType` is a new property available as a basic panel component of `dialogs`.

It replaces the, now deprecated property, `primary`.

The `primary` property was boolean, allowing for only two states: `true` and `false`.

The new `buttonType` property can take any of three states: `'primary'`, `'secondary'`, and `'toolbar'`.

Setting `buttonType: 'primary'` is the same as setting `primary: true`.

Setting `buttonType: 'secondary'` is the same as setting `primary: false`.


[id=new-and-improved-ui-and-ux-elements-and-components-buttontype]
==== dialog box re-rendering

Previously, when a component in a {productname} dialog box changed — for example, when a _next_ or _previous_ button was clicked — the entire dialog box was re-rendered.

In {productname} 6.0, the `initialData` type is now `Partial<T>`, which matches the underlying implementation.

And, relatedly, the `redial` API now re-renders only the portions of a dialog that have changed.


==== `setData` method in dialog API

The dialog API’s `setData` method now uses a deep merge algorithm.

Consequently, it now supports partial nested objects.


[id=new-and-improved-ui-and-ux-elements-and-components-editor-text-entry-height]
==== Editor text entry height

In {productname} 5.x, editors without a specified `config.height` value defaulted to a 200px high text entry area.

In {productname} 6.0, editors without a specified `config.height` value default to a 400px high text entry area.


==== editor theme now fetched in parallel with icons, plugins, and language packs

Previously, when a theme was requested, {productname} downloaded it completely before fetching accompanying components, such as icons, plugins, and language packs.

With this release, when a theme is called, related components are downloaded in parallel with the theme.


==== `imagepreview`

The new `imagepreview` dialog component allows for previewing and zooming of any image URL.


==== Insertion point placement improved when clicking on noneditable elements

Clicking on or near the boundaries between editable and noneditable elements (eg in the `padding` of a noneditable element containing an editable element), there are established and expected norms as to where the insertion point should present after the click.

With this release, {productname} has improved the placing of the insertion point on either side of a noneditable element when clicking on or near these boundaries.


==== `slider`

{productname} 6.0 includes a new `slider` dialog component.


=== Changed UI and UX elements and components

==== buttonType

`buttonType` is a new property available as a basic panel component of `dialogs`.

It replaces the, now deprecated property, `primary`.


==== `disabled` properties re-named to `.enabled` in {productname} UI classes

Previously, {productname} UI classes provided a `.disabled` property.

In {productname} 6, this property has been re-named to `.enabled`.

Also, the Dialog API, which previously offered the `disable(<name>)` and `enable(<name>)` functions, now offers a single `setEnabled(<name>, <state>)` function.


==== Editor text entry height

In {productname} 5.x, editors without a `height` value specified in the {productname} configuration defaulted to a 200px high text entry area.

In {productname} 6.0, editors without a `height` value specified in the {productname} configuration default to a 400px high text entry area.

As was the case in {productname} 5.x, this new default only applies to editors in `iframe` mode, not `inline` mode.


==== status bar company ID changed from text string to logo mark

The _Powered by Tiny_ text string set in the {productname} status bar is now the {productname} logo.

NOTE: the logo still responds appropriately when {productname} is used with a screen reader.


==== status bar path delimiter character changed.

The default status bar path delimiter character (also known as a breadcrumb separator) has been changed.

It was `»` (the double, right-pointing, angled quotation mark).

It is now `›` (the single, right-pointing, angled quotation mark).



=== Fixed UI and UX elements and components

==== Anchor elements now rendering correctly when `allow_html_in_named_anchor: true`

When `allow_html_in_named_anchor` was set to `true`, content inside the anchor element was wrapped such that each character was set on a new line.

With this release, setting `allow_html_in_named_anchor: true` sets characters inside the anchor element as entered, with no wrapping of each character to a new line.


==== Default UI theme, silver, no longer renders incorrectly as plugins load

Previously, {productname}’s default UI theme, `silver`, was initialised such that it rendered some UI components before plugins that, potentially, would over-ride or adjust the defaults presented by `silver`.

This resulted in these UI elements rendering incorrectly.

With this release, `silver` no longer renders these UI elements before plugins get to over-ride or adjust, and these components no longer render incorrectly.


==== dialog labels now rendering correctly

Previously, {productname} dialog labels and other UI elements were rendered with HTML markup.

With this release, the `text` and `label` properties of these elements are now rendered as plain text, as expected.


==== `editor.selection.setRng`

Calls to `editor.selection.setRng` now update the insertion point bookmark when focus is returned to the editor.

For the end-user, this change means content dragged from outside the {productname} editor into the editable area will be placed into the {productname} document where the insertion point appears as the drag is completed.

This is the expected behaviour.


==== sub-menu items now read by screen readers

Previously, navigating through {productname} menus using the keyboard did not cause screen readers to read out menu items.

This has been corrected with this release.

Screen readers now read menu items as the {productname} menus are traversed, as expected.

NOTE: this patch was contributed by community member, https://github.com/westonkd[Weston Dransfield].


==== Tables are now positioned using `margins`, not `float`

{productname} previously used `float` to position tables to the left or right of the viewport (the working area available to the {productname} editor). This caused multiple layout and UX problems.

As of {productname} 6.0, tables are positioned using `margins` rather than `float`. This prevents these layout and UX problems occuring.

However, when upgrading to {productname} 6.0, there are two things to be aware of:

First, {productname} 6.0 does not alter existing documents. Extant {productname} documents with tables that were aligned to either _left_ or _right_ will still have the `float` property assigned when opened and edited unless and until their *alignment* is altered.

If an extant {productname} document with an aligned table is opened using {productname} 6.0 and the *alignment* of the table is re-set, {productname} 6.0 will remove the `float` property and use the `margin` property to set the *alignment*.

Second, if the previous behaviour is required, a custom `format` will need to be created.


=== Removed or deprecated UI and UX elements and components

==== `mobile` theme

The `mobile` theme was deprecated when integrated support for mobile devices was  added to {productname}.

The theme has now been removed.


==== primary

the `primary` property was a boolean property available as a basic panel component of `dialogs`.

It has been deprecated and replaced by the new `buttonType` property.


==== style field in the Advanced tab of the Insert/Edit Image dialog box

The _Style_ field, previously presented in the _Advanced_ tab of the _Insert/Edit Image_ dialog box has been removed.

When the _Advanced_ tab in the _Insert/Edit Image_ dialog box was selected, a _Style_ text-entry field (auto-populated with the selected image’s properties and associated values) was one of the fields presented.

A bug in {productname} prevented the field from being edited, however.

Separate from the text-entry bug, supporting edits in this field properly is out-of-scope for this release of {productname}.

An internal feature request to re-implement this feature when it can be done so safely has been logged.


==== Typing the End key no longer causes the insertion point to leave an editable element

Pressing the _End_ key when the insertion point is somewhere in a line of editable text should move the insertion point to the end of that line.

In the previous release of {productname}, pressing this key moved the insertion point outside the element containing the editable text entirely.

As of this {productname} release, pressing the _End_ key when the insertion point is in a line of editable text moves the insertion point to the end of that line, as expected.

