= TinyMCE 6.0 UI and UX elements and components changes
:navtitle: TinyMCE 6.0 UI and UX elements and components changes
:description: TinyMCE 6.0 UI and UX elements and components changes
:keywords: releasenotes, ui, ux

This section documents the improvements, changes, fixes and removals made to {productname} 6.0 UI and UX elements and components.

* xref:ui-and-ux-elements-and-components[UI and UX elements and components]
* xref:new-and-improved-ui-and-ux-elements-and-components][New and improved UI and UX elements and components]
* xref:changed-ui-and-ux-elements-and-components[Changed UI and UX elements and componen]
* xref:fixed-ui-and-ux-elements-and-components[Fixed UI and UX elements and components]
* xref:removed-or-deprecated-ui-and-ux-elements-and-components[Removed or deprecated UI and UX elements and components]

// tag::ui-and-ux-elements-and-components[]
[[ui-and-ux-elements-and-components]]
== UI and UX elements and components

[[new-and-improved-ui-and-ux-elements-and-components]]
=== New and improved UI and UX elements and components

[[buttontype]]
==== `buttonType`

`buttonType` is a new property available for button components used in dialogs.

It replaces the, now deprecated property, `primary`.

The `primary` property was boolean, allowing for only two states: `true` and `false`.

The new `buttonType` property can take any of three states: `'primary'`, `'secondary'`, and `'toolbar'`.

Setting `buttonType: 'primary'` is the same as setting `primary: true`.

Setting `buttonType: 'secondary'` is the same as setting `primary: false`.


[[dialog-box-re-rendering]]
==== dialog box re-rendering

Previously, when a component in a {productname} dialog box changed — for example, when a _next_ or _previous_ button was clicked — the entire dialog box was re-rendered.

In {productname} 6.0, the `initialData` type is now `Partial<T>`, which matches the underlying implementation.

And, relatedly, the `redial` API now re-renders only the portions of a dialog that have changed.

[[format-painter]]
==== Format Painter

The *Format Painter* toolbar item now has a matching menu item: *Format › Format Painter*.


[[setdata]]
==== `setData` method in dialog API

The dialog API’s `setData` method now uses a deep merge algorithm.

Consequently, it now supports partial nested objects.


[[editor-text-entry-height]]
==== Editor text entry height

In {productname} 5.x, editors without a specified `config.height` value defaulted to a 200px high text entry area.

In {productname} 6.0, editors without a specified `config.height` value default to a 400px high text entry area.


[[editor-theme-parallel-fetched]]
==== editor theme now fetched in parallel with icons, plugins, and language packs

Previously, when a theme was requested, {productname} downloaded it completely before fetching accompanying components, such as icons, plugins, and language packs.

With this release, when a theme is called, related components are downloaded in parallel with the theme.


[[imagepreview]]
==== `imagepreview`

The new `imagepreview` dialog component allows for previewing and zooming of any image URL.


[[insertion-point-placement-improvement]]
==== Insertion point placement improved when clicking on noneditable elements

Clicking on or near the boundaries between editable and noneditable elements (eg in the `padding` of a noneditable element containing an editable element), there are established and expected norms as to where the insertion point should present after the click.

With this release, {productname} has improved the placing of the insertion point on either side of a noneditable element when clicking on or near these boundaries.


[[slider]]
==== `slider`

{productname} 6.0 includes a new `slider` dialog component.


[[changed-ui-and-ux-elements-and-components]]
=== Changed UI and UX elements and components

[[buttontype]]
==== buttonType

`buttonType` is a new property available as a basic panel component of `dialogs`.

It replaces the, now deprecated property, `primary`.


[[disabled-properties-renamed-to-enabled]]
==== `disabled` properties renamed to `.enabled` in {productname} UI classes

Previously, {productname} UI classes provided a `.disabled` property.

In {productname} 6, this property has been renamed to `.enabled`.

Also, the Dialog API, which previously offered the `disable(<name>)` and `enable(<name>)` functions, now offers a single `setEnabled(<name>, <state>)` function.


[[editor-text-entry-height]]
==== Editor text entry height

In {productname} 5.x, editors without a `height` value specified in the {productname} configuration defaulted to a 200px high text entry area.

In {productname} 6.0, editors without a `height` value specified in the {productname} configuration default to a 400px high text entry area.

As was the case in {productname} 5.x, this new default only applies to editors in `iframe` mode, not `inline` mode.


[[status-bar-compeny-id-changed-from-text-to-logo]]
==== status bar company ID changed from text string to logo mark

The _Powered by Tiny_ text string set in the {productname} status bar is now the {productname} logo.

NOTE: The logo still responds appropriately when {productname} is used with a screen reader.


[[status-bar-path-delimiter-character-changed]]
==== status bar path delimiter character changed.

The default status bar path delimiter character (also known as a breadcrumb separator) has been changed.

It was `»` (the double, right-pointing, angled quotation mark).

It is now `›` (the single, right-pointing, angled quotation mark).


[[fixed-ui-and-ux-elements-and-components]]
=== Fixed UI and UX elements and components


[[anchor-elements-render-correctly]]
==== Anchor elements now render correctly when `allow_html_in_named_anchor: true`

When `allow_html_in_named_anchor` was set to `true`, content inside the anchor element was wrapped such that each character was set on a new line.

With this release, setting `allow_html_in_named_anchor: true` sets characters inside the anchor element as entered, with no wrapping of each character to a new line.


[[default-ui-theme-silver-renders-correctly]]
==== Default UI theme, silver, no longer renders incorrectly as plugins load

Previously, {productname}’s default UI theme, `silver`, was initialised such that it rendered some UI components before plugins that, potentially, would over-ride or adjust the defaults presented by `silver`.

This resulted in these UI elements rendering incorrectly.

With this release, `silver` no longer renders these UI elements before plugins get to override or adjust, and these components no longer render incorrectly.


[[dialog-labels-render-correcttly]]
==== dialog labels now rendering correctly

Previously, {productname} dialog labels and other UI elements were rendered with HTML markup.

With this release, the `text` and `label` properties of these elements are now rendered as plain text, as expected.


[[editor-selection-setring]]
==== `editor.selection.setRng`

Calls to `editor.selection.setRng` now update the insertion point bookmark when focus is returned to the editor.

For the end-user, this change means content dragged from outside the {productname} editor into the editable area will be placed into the {productname} document where the insertion point appears as the drag is completed.

This is the expected behavior.


[[sub-menu-items-now-read-by-screen-readers]]
==== sub-menu items now read by screen readers when using Google Chrome 93 or later

Previously, in Google Chrome 93 and later, navigating through {productname} menus using the keyboard did not cause screen readers to read out menu items.

This has been corrected with this release.

Screen readers now read menu items as the {productname} menus are traversed, as expected.

NOTE: This patch was contributed by community member, https://github.com/westonkd[Weston Dransfield].


[[tables-now-positioned-using-margins-not-float]]
==== Tables are now positioned using `margin`, not `float`

{productname} previously used `float` to position tables to the left or right of the viewport (the working area available to the {productname} editor). This caused multiple layout and UX problems.

As of {productname} 6.0, tables are positioned using `margin` rather than `float`. This prevents these layout and UX problems occurring.

However, when upgrading to {productname} 6.0, there are two things to be aware of:

First, {productname} 6.0 does not alter existing documents. Extant {productname} documents with tables that were aligned to either _left_ or _right_ will still have the `float` property assigned when opened and edited unless and until their *alignment* is altered.

If an extant {productname} document with an aligned table is opened using {productname} 6.0 and the *alignment* of the table is re-set, {productname} 6.0 will remove the `float` property and use the `margin` property to set the *alignment*.

Second, if the previous behavior is required, a custom `format` will need to be created.


[[text-presentation-corrections-on-some-UI-elements]]
==== Text presentation corrections on some UI elements

The text on some buttons and menu items incorrectly presented in Title Case.

The underlying strings have been corrected and these items now present in sentence case, as expected.


[[removed-or-deprecated-ui-and-ux-elements-and-components]]
=== Removed or deprecated UI and UX elements and components

[[mobile-theme]]
==== `mobile` theme

The `mobile` theme was deprecated when integrated support for mobile devices was added to the `silver` theme.

The `mobile` theme has been removed.


[[primary]]
==== primary

The `primary` property was a boolean property available for button components used in dialogs

It has been deprecated and replaced by the new `buttonType` property.


[[style-field]]
==== style field in the Advanced tab of the Insert/Edit Image dialog box

The _Style_ field, previously presented in the _Advanced_ tab of the _Insert/Edit Image_ dialog box has been removed.

When the _Advanced_ tab in the _Insert/Edit Image_ dialog box was selected, a _Style_ text-entry field (auto-populated with the selected image’s properties and associated values) was one of the fields presented.

A bug in {productname} prevented the field from being edited, however.

Separate from the text-entry bug, supporting edits in this field properly is out-of-scope for this release of {productname}.

An internal feature request to re-implement this feature when it can be done so safely has been logged.


[[typing-end-key]]
==== Typing the End key no longer causes the insertion point to leave an editable element

Pressing the _End_ key when the insertion point is somewhere in a line of editable text should move the insertion point to the end of that line.

In the previous release of {productname}, pressing this key moved the insertion point outside the element containing the editable text entirely.

As of this {productname} release, pressing the _End_ key when the insertion point is in a line of editable text moves the insertion point to the end of that line, as expected.

// end::ui-and-ux-elements-and-components[]
