= TinyMCE 6.0: Premium changes
:navtitle: Premium changes
:description: Premium feature changes accompanying TinyMCE 6.0
:keywords: releasenotes, premium, bugfixes

* xref:premium-plugin-components-we-renamed[Premium Plugin components we renamed]
* xref:title-case-corrected-in-premium-plugin-ui-elements[Title case corrected in Premium Plugin UI elements]
* xref:hindi-malay-and-vietnamese-translations-added-to-premium-plugins[Hindi, Malay, and Vietnamese translations added to Premium Plugins]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:accompanying-premium-self-hosted-server-side-component-changes[Accompanying Premium self-hosted server-side component changes]

== {productname} 6.0 Premium Plugins are not backwards compatible

No Premium Plugins released with {productname} 6.0 are backwards compatible with earlier versions of {productname}.


[[premium-plugin-components-we-renamed]]
== Premium Plugin components we renamed

[cols="1,1,1,1"]
|===
| Old name                            | New name                         | Element                             | Notes

| `formatpainter_blacklisted_formats` | `formatpainter_ignored_formats`  | Option                              | 

| `imagetools`                        | `editimage`                      | Plugin                              | NB: _Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `imagetools_toolbar`                | `editimage_toolbar`              | Option                              | NB: _Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `imagetools_proxy`                  | `editimage_proxy`                | Option                              | NB: _Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `imagetools_cors_hosts`             | `editimage_cors_hosts`           | Option                              | NB: _Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `imagetools_credentials_hosts`      | `editimage_credentials_hosts`    | Option                              | NB: _Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `imagetools_fetch_image`            | `editimage_fetch_image`          | Option                              | NB: _Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `images_upload_timeout`             | `editimage_upload_timeout`       | Option                              | NB: _Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `toc`                               | `tableofcontents`                | Plugin, Menu item, and Toolbar item | This presents in both the menu item and the toolbar’s tooltip text. NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `tocupdate`                         | `tableofcontentsupdate`          | Toolbar item                        | This presents in the toolbar’s tooltip text. NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `toc_class`                         | `tableofcontents_class`          | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `toc_depth`                         | `tableofcontents_depth`          | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

| `toc_header`                        | `tableofcontents_header`         | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].
|===

[[hindi-malay-and-vietnamese-translations-added-to-premium-plugins]]
== Hindi, Malay, and Vietnamese translations added to Premium Plugins

The following Premium Plugins now present in Hindi, Malay, and Vietnamese:

* xref:a11ychecker.adoc[Accessibility Checker]
* xref:advtable.adoc[Advanced Tables]
* xref:introduction-to-tiny-comments.adoc[Comments]
* xref:editimage.adoc[Enhanced Image Editing]
* xref:export.adoc[Export]
* xref:introduction-to-powerpaste.adoc[PowerPaste]
* xref:rtc-introduction.adoc[Real-time Collaboration (RTC)]
* xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro]
* xref:tableofcontents.adoc[Table of Contents]

[[title-case-corrected-in-premium-plugin-ui-elements]]
== Title case corrected in Premium Plugin UI elements

Previously, buttons, dialog fields, and menu items in the following Premium Plugins were presented in title case:

* xref:a11ychecker.adoc[Accessibility Checker]
* xref:formatpainter.adoc[Format Painter]
* xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro]

As of this update, these UI elements in these Plugins present in standard sentence case.


// tag::accompanying-premium-plugin-changes[]
[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.0.

=== Accessibility Checker

The following change was made to the xref:a11ychecker.adoc[Accessibility Checker] plugin:

The default value for `a11ychecker_html_version` was `html4`.

It is now `html5`.


=== Advanced Tables

The following changes and fixes were made to the xref:advtable.adoc[Advanced Tables] plugin:

With all table logic, except table UI components, now part of xref:6.0-release-notes-core-changes.adoc#changed-plugins-table[core {productname} editor], the `advtable` plugin now only requires the `table` plugin be enabled to use the Advanced Table-specific toolbar buttons and menu items.

Previously, the `getRowType()` method of the series generator info argument incorrectly returned `header` when a `tfoot` row contained only header cells.

With this update, `getRowType()` correctly returns `footer` when a `tfoot` row contains only header cells.

Previously tables containing a `colgroup` did not sort correctly. As of this release, this error has been corrected: tables with a `colgroup` now sort correctly, as expected.


=== Comments

The following changes and fixes were applied to the xref:introduction-to-tiny-comments.adoc[Comments] plugin:

Because of how a comment’s active state was captured when the comment was made active, this active state was not excluded when capturing editor content from a comment.

With this release, a comment’s active state is captured differently and, consequently, this state is excluded when comment content is captured.

Previously, every time the insertion point was placed within an extant comment and then placed anywhere outside of the comment body, an undo level was added. That is, every time focus was switched either to or from a content, an undo level was added.

With this update, shifting focus to or from a comment no longer adds undo levels, as expected.

Previously, the Comments plugin’s scroll position logic lead to, in some edge cases, the last comment not scrolling into view correctly.

The logic has been corrected and, with this update, all comments scroll into view as expected.

Previously, when a Comment was added to a {productname} instance, the data in `tinycomments` was automatically, and incorrectly, added to `editor.selection.getContent()`.

This caused that same data to appear in dialogs such as the *Find and Replace* Find text-entry input field and the *Insert Link* text-entry input field.

Typically, the added data was the content selected before adding the comment. Selecting any or all the contents of a {productname} instance was not, however, necessary for this bug to present. Adding a comment to a {productname} instance automatically adds data to `tinycomments` regardless of whether there is selected content in the {productname} instance.

With this update, adding a comment still adds data to `tinycomments` but that data is no longer passed to `editor.selection.getContent()`, which prevents it being automatically added to dialogs such as the *Find and Replace* Find text-entry input field.


=== Enhanced Image Editing (was Image Tools)

The following changes were made to the xref:editimage.adoc[Enhanced Image Editing] plugin:

As noted in the xref:6.0-release-notes-core-changes.adoc#removed-or-deprecated-plugins-imagetools[_{productname} 6.0 Release Notes_], the `imagetools` plugin is no longer included as part of the Free editor.

_Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

The `imagetools_proxy` option has been renamed to `editimage_proxy`. However, when setting up xref:introduction-to-premium-selfhosted-services.adoc[Tiny services] the recommended configuration is now `editimage_proxy_service_url` and will be used in favour of `editimage_proxy` if both are set.

Users of the Free version of {productname} 5.x who rely on the removed `imagetools` plugin should not upgrade to {productname} 6.0 without a https://tiny.cloud/pricing/[subscription plan] that provides access to https://tiny.cloud/tinymce/features/#productivity[_Enhanced Image Editing_].


=== Enhanced Media Embed

The following change was made to the xref:introduction-to-mediaembed.adoc[Enhanced Media Embed] plugin:

In earlier versions of the {productname}, the `forced_root_block` option took the value `false`.

This value was previously deprecated and, with this release, support for `false` as a `forced_root_block` value has been removed from the Enhanced Media Embed plugin.

=== Export

The following improvement was made to the xref:export.adoc[Export] plugin:

A new `export_image_proxy_service_url` option is available for use with the proxy service provided by https://tiny.cloud/docs/enterprise/server/[Tiny services].


=== Format Painter

The following improvement and following change were made to the xref:formatpainter.adoc[Format Painter] plugin:

A `formatpainter` menu item was added to match the toolbar button.

The `formatpainter_blacklisted_formats` option was re-named to `formatpainter_ignored_formats`.


=== Mentions

The following change was made to the xref:mentions.adoc[Mentions] plugin:

The `getUsers` API was removed.

View the following demo for an alternative to the `getUsers` API:

liveDemo::getusers-api-alternative[height="400"]
        
=== PowerPaste

As noted in the xref:6.0-release-notes-core-changes.adoc#removed-or-deprecated-plugins-paste[_{productname} 6.0 Release Notes_], the `paste` plugin’s functionality is no longer provided as a plugin. It is now a core part of {productname} 6.0.

Because the functionality was unmaintainable, however, `paste` no longer supports input from Microsoft Word.

The Premium plugin, xref:introduction-to-powerpaste.adoc[`PowerPaste`] provides the capability to accept data from Microsoft Word and Microsoft Excel, and clean-up the received data before pasting it into place.

For this release, the following fixes and changes were also incorporated into the xref:introduction-to-powerpaste.adoc[PowerPaste] plugin:

Previously, when dragging content from outside the editor to inside the editor the pointer did not move with the dragged content as expected.

With this update, dragging content behaves correctly: the {productname} editor takes focus when the drag enters a the pointer follows the dragged content.

As well, content dragged and dropped into the {productname} editor is now cleaned or merged using the same logic as when content is pasted in.

Finally, pasting content from Microsoft Word that included a style block ≥ 1.4 Mb previously triggered a stack overflow.

With this release, such content can be pasted in to a {productname} editor with PowerPaste enabled without issue.

In conjunction with these PowerPaste changes, three changes were made to `paste`:

. A `paste` default has changed. The `paste_data_images` option now defaults to `true`.
+
When `paste` was a plugin, this option was, by default, set to `false`, which prevented images being pasted from the local machine.
+
. The `mceInsertClipboardContent` argument, `content`, has been renamed to `html`.
+
The new name is a more accurate reflection of what sort of data the argument passes.
+
The `content` argument can no longer be used with `mceInsertClipboardContent`. If `content` is used, no data is passed. `mceInsertClipboardContent` only attempts to pass data if the `html` or `text` property is used.
+
. The, now built-in, `paste` functionality no longer supports pasting from Microsoft Word.
+
NOTE: There is an open https://github.com/tinymce/tinymce/discussions/7487[request for maintainers] should someone in the community be interested in taking over maintenance of this particular functionality as a separate plugin. +
If a community-maintained version of the `paste` plugin becomes available, we will link to it from the xref:migration-from-5x.adoc#plugins-paste[_Migration Guide_].


=== Real-time Collaboration

The following improvements, changes, and fixes were made to the xref:rtc-introduction.adoc[Real-time Collaboration] plugin:

Three additional options are now supported when Real-time Collaboration is active:

* `valid_elements`
* `valid_children`
* `extended_valid_elements`

Real-time Collaboration now supports xref:autocompleter.adoc[the `autocompleter` API].

Real-time Collaboration now supports xref:content-behavior-options.adoc#inline_boundaries[the `inline_boundaries` option].

When provided values are incorrect, the returned error messages are now less opaque.

For example, the error message `'key' was not a string` is now the error message `Expected field 'key'`.

Previously, if a {productname} editor instance with Real-time Collaboration loaded also contained a Horizontal Rule (ie an `+<hr>+` element), attempting to move the insertion point over the Horizontal Rule using arrow keys threw an exception: `Uncaught Error: Unsupported node type: [object DocumentType]`.

With this update, moving the insertion point through a Horizontal Rule using arrow keys works as expected: the insertion point moves and no exception is thrown.

Previously, attempting to remove failed image uploads with the `images_upload_handler` API failed if Real-time Collaboration was loaded.

With this update, `images_upload_handler` removes failed image uploads and presents the correct alert message.

Keyboard events can now be prevented before the Real-time Collaboration plugin intercepts them.

Previously, selecting linked images when the `link_context_toolbar` option was enabled, caused the Real-time Collaboration editor to enter an endless loop. This loop caused the selected images to flicker.

With this update, the Real-time Collaboration editor no longer enters an endless loop when linked images are selected. Consequenlty, the selected images no longer flicker.


=== Spell Checker Pro

The following fixes were made to the xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro] plugin:

Previously, Spell Checker Pro treated soft hyphens (ie the `+&shy;+` html entity) as a word boundary. As a consequence words containing soft hyphens were not correctly spellchecked as whole words.

With this update, the `+&shy;+` entity is correctly recognised as part of a word, not a word boundary. And words containing soft hyphens are, consequently, spell checked correctly.

As well, one command and one option have been replaced and a, previously deprecated, fallback option has been removed.

[cols="1,1,1"]
|===
| Removed item                    | Replacement                | Element type

| `mceSpellcheckDocument`         | `mceSpellcheckDialog`      | Command

| `spellchecker_select_languages` | `content_langs`            | Option

| `spellchecker_whitelist`        | `spellchecker_ignore_list` | Option
|===


=== Table of Contents

The following changes were made to the xref:tableofcontents.adoc[Table of Contents] plugin:

As noted in the xref:6.0-release-notes-core-changes.adoc#new-and-improved-plugins-table-of-contents[_{productname} 6.0 Release Notes_], the `toc` plugin is no longer part of the Core editor.

Table of Contents has been updated and is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

Users of the Free version of {productname} 5.x who rely on the, now deprecated and removed, `toc` plugin, should not upgrade to {productname} 6.0 without a https://tiny.cloud/pricing/[subscription plan] that provides access to Premium plugins such as https://tiny.cloud/tinymce/features/#productivity[_Table of Contents_].

The new Premium `tableofcontents` plugin also changes the names of several elements.

[cols="1,1"]
|===
| Old name     | New name                 | Element type

| `toc`        | `tableofcontents`        | Plugin, Menu item, and Toolbar item

| `tocupdate`  | `tableofcontentsupdate`  | Toolbar item

| `toc_class`  | `tableofcontents_class`  | Option

| `toc_depth`  | `tableofcontents_depth`  | Option

| `toc_header` | `tableofcontents_header` | Option
|===

Any configurations or logic that use the old element names must be updated to the new names after upgrading to {productname} 6.0 and installing the new `tableofcontents` plugin.


=== Tiny Drive

The following improvements, changes, and fixes were made to the xref:tinydrive-introduction.adoc[Tiny Drive] plugin:

Tiny Drive supports several new file formats:

* https://developers.google.com/speed/webp[WebP] images (`.webp`).
* https://aomediacodec.github.io/av1-avif/[AV1 Image File Format] (AVIF) files (`.avif`).
* https://wiki.mozilla.org/APNG_Specification[Animated Portable Network Graphic] files (`.apng`).

Tiny Drive now recognises files using the following filename extensions as JPEG files:

* `+.jpe+`
* `+.jfi+`
* `+.jif+`,
* `+.jfif+`,
* `+.pjpeg+`,
* `+.pjp+`

When the *Starred* filter is used, _move_ and _copy_ are now removed from the actions menu.

They are not needed and removing them from the menu obviates a file-moving error.

The third-party PDF renderer used by Tiny Drive, https://mozilla.github.io/pdf.js/[PDFjs] has been updated to the most recent version.

When Tiny Drive cannot preview a file, it displays a generic file-type icon.

With this release, a text message — _No preview available_ — is also displayed.

Previously, everytime Tiny Drive was opened, the CSS used to present the Tiny Drive instance was re-loaded.

With this release, a check has been added. Tiny Drive’s CSS is now loaded once, when it is first opened, and uses the already loaded CSS on subsequent openings.

Icons presented in the _Upload file_ and _Upload/Create_ menus were inconsistent: some presenting as black and some presenting as white.

This has been corrected: these icons now all present as black or white as expected.

When the {productname} toolbar is visible but the viewport is narrow, the toolbar, or parts of the toolbar, are collapsed into an overflow menu (denoted with a mid-line horizontal ellipsis: `+⋯+`).

In some circumstances, when Tiny Drive was loaded and the overflow menu was opened, clicking outside the resulting displayed menu did not close the menu.

With this update, clicking outside this menu closes it, as expected.

When a file available in Tiny Drive both had an attached Star and was presented in the Preview view, choosing *Unstar* from the Preview view’s overflow menu did not change the file’s Star state.

With this update, files with Stars that are Unstarred from the Preview view have the star removed, as expected.

Similarly, when a file available in Tiny Drive was presented in the Preview view, choosing *Rename* from the overflow menu, entering a new name, and clicking *Submit*, did not change the file’s name.  

With this update, files with Stars that are re-named from the Preview view update the filename, as expected.



[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.0 release includes an accompanying release of the *Premium Skins and Icon Packs*.

//=== Premium Skins and Icon Packs new features
//
// Add description here.

For information on using premium skins and icon packs, see: xref:enhanced-skins-and-icon-packs.adoc[Premium Skins and Icon Packs].

//=== Premium Skins and Icon Packs Bug fixes
//
//The *Premium Skins and Icon Packs* release includes the following bug fixes:
//
// Add description here.
//
//For information on using premium skins and icon packs, see: xref:enhanced-skins-and-icon-packs.adoc[Premium Skins and Icon Packs].

[[accompanying-premium-self-hosted-server-side-component-changes]]
== Accompanying Premium self-hosted server-side component changes

The {productname} 6.0 release includes accompanying changes affecting the {productname} *self-hosted* services for the following plugins:

* Enhanced Media Embed plugin (`+mediaembed+`)
* Export plugin (`+export+`)
* Enhanced Image Editing plugin (`+editimage+`)
* Link Checker plugin (`+linkchecker+`)
* Spell Checker Pro plugin (`+tinymcespellchecker+`)

The Java server-side components have been updated to the following versions:

* `+ephox-hyperlinking.war+`: 2.105.9
* `+ephox-image-proxy.war+`: 2.106.1
* `+ephox-spelling.war+`: 2.118.4

For information on:

* The Enhanced Media Embed plugin, see: xref:introduction-to-mediaembed.adoc[Enhanced Media Embed plugin].
* The Export plugin, see: xref:export.adoc[Export plugin].
* The Enhanced Image Editing plugin, see: xref:editimage.adoc[Enhanced Image Editing plugin].
* The Link Checker plugin, see: xref:linkchecker.adoc[Link Checker plugin].
* The Spell Checker Pro plugin, see: xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro plugin].
* Deploying the server-side components, see: xref:introduction-to-premium-selfhosted-services.adoc[Server-side component installation].

=== Updating the self-hosted server-side components

The new versions of the server-side services provide updates for the Java-based server-side components. To deploy the updated version of the server-side components:

. Update your Java Application Server to the minimum required version:

include::partial$misc/supported-application-servers.adoc[]

[arabic, start=2]
. Replace the existing server-side `+.war+` files with the `+.war+` files bundled with {productname} 6.0 or later.

For information on:

* Deploying the server-side components, see: xref:introduction-to-premium-selfhosted-services.adoc[Server-side component installation].
* Deploying the server-side components using Docker, see: xref:bundle-intro-setup.adoc[Containerized service deployments].

// tag::accompanying-premium-plugin-changes[]


// [[premium-plugin-name-xyz]]
// === Premium Plugin Name X.Y.Z
//
// The {productname} 6.0 release includes an accompanying release of the *<>* premium plugin.
//
// *<>* X.Y.Z adds the following new features:
//
// * {blank}
// +
//
// *<>* X.Y.Z introduces the following enhancements:
//
// * {blank}
// +
//
// *<>* X.Y.Z provides the following bug fixes:
//
// * {blank}
// +
//
// For information on the <> plugin, see: xref:<>.adoc[<> plugin].

