= TinyMCE 6.0 API changes
:navtitle: TinyMCE 6.0 API changes
:description: TinyMCE 6.0 API changes
:keywords: releasenotes, apis

This section documents the improvements, changes and fixes made to {productname} 6.0 APIs.

It also documents the {productname} 6.0 APIs that have been removed.


* xref:apis[APIs]
* xref:new-and-improved-apis][New and improved APIs]
* xref:changed-apis[Changed APIs] 
* xref:fixed-apis[Fixed APIs]
* xref:removed-or-deprecated-apis[Removed or deprecated APIs]


[[apis]]
== APIs

[[id=new-and-improved-apis]]
=== New and improved APIs

[[editor-annotator-removeall]]
==== `editor.annotator.removeAll`

The new `editor.annotator.removeAll` API replaces the `removeAll` function built-in to the comments plugin.

[[editor-options]]
==== `editor.options` and `tinymce.activeEditor.options`

The new `editor.options` API replaces two old APIs: `editor.settings` and `editor.getParam`.

Along with this new API, the new `tinymce.activeEditor.options` registry replaces `tinymce.activeeditor.settings`.

[[editor-uploadImages]]
==== `editor.uploadImages()`

The `editor.uploadImages()` API now includes a `remove` flag.

The flag returns `true` when an image being uploaded is removed after failing to upload.

[[fakeclipboard]]
==== `FakeClipboard`

The new `FakeClipboard` API provides a means for storing state that can be set and accessed by plugins and the core editor.

`FakeClipboard` is implemented on the {productname} global, allowing anything to write to it and read from it.

[[resource-unload]]
==== `Resource.unload`

The new `Resource.unload` API makes it possible to unload resources in the resource loader.

This allows tests, such as `ImageEmojiTest`, to remove existing databases before loading their own.

[[setdata]]
==== `setData` method in dialog API

The dialog API’s `setData` method now uses a deep merge algorithm.

Consequently, it now supports partial nested objects.

[[promise]]
==== success or failure callbacks replaced by `Promise` in multiple APIs

* Previously, the AddOnManager, PluginManager, ScriptLoader, StyleSheetLoader, and ThemeManager APIs report resource loading status with `success` or `failure` callbacks.

  These APIs now, instead, return a `Promise`, with a value of either `resolve` or `reject`.
  
  Also, `EditorUpload`, which already returns a `Promise`, had callbacks removed.

[[changed-apis]]
=== Changed APIs

[[closebutton]]
==== `closeButton` and `timeout`

* Previously, using `closeButton` to disable a _Notification’s_ close button required a `timeout` value to also be set.

  In {productname} 6, `closeButton` shows or hides the close button regardless of a `timeout` value being set or not set.

  Equivalently, setting a `timeout` value sets how long the notification presents before automatically closing, regardless of whether a close button is displayed or not.

[[disabled]]
==== `disabled` functions re-named in all {productname} APIs

Previously, multiple {productname} APIs and UI classes used `disable` or `disabled` in their function or property names.

In {productname} 6, these function names have been changed and configuration changes are required.

1. `isDisabled()` functions are now `isEnabled() functions.

2. The `enable()` and `disable()` functions are now the single `setEnabled(<state>)` function.

3. The `disable(<name>)` and `enable(<name>)` functions are now the single `setEnabled(<name>, <state>)` function in the Dialog APIs.

As well, the `.disabled` property is now the `.enabled` property in all {productname} UI classes.

[[dom-domutils]]
==== `dom.DOMUtils`

The `toHex` function has been removed from `dom.DOMUtils`.

[[domparser]]
==== `DomParser`

The `filterNode` method has been removed from the `DomParser` API.

As well, the `DomParser` API no longer uses a custom parser internally and instead uses the https://developer.mozilla.org/en-US/docs/Web/API/DOMParser[native `DOMParser` API].

[[editor-setcontent]]
==== `editor.SetContent`

The `editor.SetContent` event’s `content` property has been deprecated.

[[env]]
==== `Env`

The following methods have been removed from the `Env` API:

* `opera`

* `webKit`

* `ie`

* `gecko`

* `mac`

* `iOS`

* `android`

* `desktop`

* `contentEditable`

* `caretAfter`

* `range`

* `ceFalse`

* `experimentalShadowDom`

* `fileApi`

Note, in particular, the removal of all legacy browser detection methods.

[[fire]]
==== `fire` functions re-named in all {productname} APIs

The `fire()` function in `tinymce.Editor`, `tinymce.dom.EventUtils`, `tinymce.dom.DOMUtils`, `tinymce.util.Observable` and `tinymce.util.EventDispatcher` has been re-named to `dispatch()`.

`fire` has been aliased to `dispatch` but has also been marked as _deprecated_.

[[fixed-apis]]
=== Fixed APIs

[[editor-annotator-remove]]
==== `editor.annotator.remove`

Previously, `editor.annotator.remove` scrolled to the removed material’s position when removing an annotation.

It did not, as expected, retain the current selection or insertion point position in the {productname} editor.

With this release, `editor.annotator.remove` does not change the change the selection or insertion point position after removing an annotation.

[[editor-fire]]
==== `editor.fire()`

Previously, if the {productname} editor was removed, the `editor.fire()` API returned an incorrect object.

In {productname} 6.0, `editor.fire()` returns the correct object even when the editor is removed.

[[editor-getcontent]]
==== `editor.getContent()`

The `editor.getContent()` API can now provide custom content by preventing and overriding `content` in the `BeforeGetContent` event.

This makes it consistent with the `editor.selection.getContent()` API.

The `editor.setContent()` API can also now be prevented from using the `BeforeSetContent` event.

This, too, makes it consistent with the `editor.selection.setContent()` API.

[[editor-selection-getcontent]]
==== `editor.selection.getContent()`

The `no_events` argument is Boolean. If set to `true`, events should not fire when `getContent` is called. Previously, `editor.selection.getContent()` did not respect this.

In {productname} 6.0, `editor.selection.getContent()` treats the `no_events` setting as expected: when set to `false`, events are fired; when set to `true`, events are not fired.



[[removed-or-deprecated-apis]]
=== Removed or deprecated APIs

[[html-styles]]
==== `html.Styles`

The `toHex` function has been removed from `html.Styles`.


[[removed-or-deprecated-apis-saxparser]]
==== `SaxParser`

With all filtering moved to the `DomParser` API, the `SaxParser` API has been removed.


[[removed-or-deprecated-apis-tables]]
==== Table

The `table` plugin’s functionality is, as of {productname} 6.0, entirely focussed on the user interface (UI) for creating and editing tables.

The code that generates tables is now a Core part of {productname} 6.0.

Since the `table` plugin API was entirely concerned with generating tables, it has been removed.


[[removed-or-deprecated-apis-tinymce-util-promise]]
==== `tinymce.util.Promise`

The `tinymce.util.Promise` API has been removed.
