= TinyMCE 6.0 Release Notes

== Core architectural change

{productname} 6.0 now requires a browser capable of running https://tc39.es/ecma262/2020/[ECMAScript 2020] (ES2020).

NOTE: In particular, this means {productname} 6.0 does not support Internet Explorer 11.

[id=things-we-renamed]
== Things we renamed

| old name                         | new name                         | element                             | notes                                                                                                                                                                                                                                                                         | for more information                               |
| -------------------------------- | -------------------------------- | ----------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| `imagetools`                     | `editimage`                      | Plugin                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `imagetools_toolbar`             | `editimage_toolbar`              | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `imagetools_proxy`               | `editimage_proxy`                | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `imagetools_cors_hosts`          | `editimage_cors_hosts`           | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `imagetools_credentials_hosts`   | `editimage_credentials_hosts`    | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `imagetools_fetch_image`         | `editimage_fetch_iamge`          | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `imagetools_api_key`             | `editimage_api_key`              | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `images_upload_timeout`          | `editimage_upload_timeout`       | Option                              | NB: _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                     | see <<new-and-improved-plugins-imagetools>>        |
| `editimage_proxy`                | `export_image_proxy_service_url` | Option                              | Renamed for easier configuration when used with https://tiny.cloud/docs/enterprise/server/[Tiny services].                                                                                                                                                                    |                                                    |
| `default_link_target`            | `link_default_target`            |                                     | Changed for consistency with other `link` and `autolink` options. Their functionality, and the values they can take remain unchanged. This change applies to both `link` and `autolink` plugins.                                                                              |                                                    |
| `rel_list`                       | `link_rel_list`                  |                                     | Changed for consistency with other options. The functionality, and the values this option can take remain unchanged.                                                                                                                                                          |                                                    |
| `target_list`                    | `link_target_list`               |                                     | Changed for consistency with other options. The functionality, and the values this option can take remain unchanged.                                                                                                                                                          |                                                    |
| `mceInsertTable`                 | `mceInsertTableDialog`           |                                     | Use `mceInsertTableDialog` to open the _Insert Table_ dialog box. NB: `mceInsertTable` (with appropriate arguments) still works to insert a table directly into an existing document. `mceInsertTable` can no longer be used to invoke the _Table_ dialog box, however.       | see <<changed-plugins-table>>                      |
| `noneditable_noneditable_class`  | `noneditable_class`              |                                     | After upgrading, rename the options in your {productname} init configuration to match the new name. For example, `noneditable_noneditable_class: 'mceNonEditable'` must be renamed `noneditable_class: 'mceNonEditable'`.                                                     | see <<changed-plugins-noneditable>>                |
| `noneditable_editable_class`     | `editable_class`                 |                                     | After upgrading, rename the options in your {productname} init configuration to match the new name. For example, `noneditable_editable_class: 'mceEditable'` must be renamed `editable_class: 'mceEditable'`.                                                                 | see <<changed-plugins-noneditable>>                |
| `textpattern_patterns`           | `text_patterns`                  | Option                              | After upgrading, rename the options in your {productname} init configuration to match the new name. Also, remove `textpattern` from your plugins list. This name-change is consequent to `textpattern` being changed from a Plugin to being part of the {productname} Core.   | see <<changed-plugins-textpattern>>                |
| `toc`                            | `tableofcontents`                | Plugin, Menu item, and Toolbar item | This presents in both the menu item and the toolbar’s tooltip text. NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                       | see <<new-and-improved-plugins-table-of-contents>> |
| `tocupdate`                      | `tableofcontentsupdate`          | Toolbar item                        | This presents in the toolbar’s tooltip text. NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                              | see <<new-and-improved-plugins-table-of-contents>> |
| `toc_class`                      | `tableofcontents_class`          | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                           | see <<new-and-improved-plugins-table-of-contents>> |
| `toc_depth`                      | `tableofcontents_depth`          | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                           | see <<new-and-improved-plugins-table-of-contents>> |
| `toc_header`                     | `tableofcontents_header`         | Option                              | NB: _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].                                                                                                                                                                           | see <<new-and-improved-plugins-table-of-contents>> |

- *Commands* are what is passed via the `theeditor.execCommand()` API.

  Where a Command name has change, calls to `theeditor.execCommand()` API must be changed to match the new name.

- Configuration *Options* are what is passed when initialising the {productname} editor via `tinymce.init`.

  Where an Option name has changed, configurations using that option must be changed to match the new name.

- *Menu items* and *Toolbar items* are *Options* from `tinymce.init` for UI and UX features, such as the {productname} Menu, Toolbar and Contextual Menu.


[id=default-value-changes]
== Default value changes

| element                 | old value | new value | notes                                                             | for more information                                               |
| ----------------------- | --------- | --------- | ----------------------------------------------------------------- | ------------------------------------------------------------------ |
| `table_style_by_css`    | `false`   | `true`    | Changed as part of modernising {productname}’s default behaviour. | see <<changed-plugins-table>>                                      |
| `table_use_colgroups`   | `false`   | `true`    | Changed as part of modernising {productname}’s default behaviour. | see <<changed-plugins-table>>                                      |
| `config.height`         | `200px`   | `400px`   | Changed to improve user experience.                               | see <<ui-and-ux-elements-and-components-editor-text-entry-height>> |
| `link_default_protocol` | `http`    | `https`   | Changed as part of modernising {productname}’s default behaviour. |                                                                    |


[id=known-issues]
== Known issues

=== Pressing the tab key in tables does not always produce the expected result

In {productname}, three settings control what happens when the _tab_ key is pressed:

| setting                 | default value | other possible value |
| ----------------------- | ------------- | -------------------- |
| `nonbreaking_force_tab` | `false`       | `true`               |
| `lists_indent_on_tab`   | `true`        | `false`              |
| `table_tab_navigation`  | `true`        | `false`              |

Previously, the setting which took precedence at any given instance of the _tab_ key being pressed was determined by the plugin load order.

As of {productname} 6.0, however, _Tables_  are not provided as a plugin. They are part of the core {productname} editor.

In {productname} 6.0, when the above settings are set to their default values (and when `nonbreaking_force_tab`, in particular, is set to its default value, `false`), and the insertion point is placed in a table cell and the tab key is pressed, the expected result is one of two things.

1. If the insertion point is within anything other than a list item, the insertion point moves to the next cell.

2. If the insertion point is within a list item, the specific list item containing the insertion point ‘indents’ presenting said item as one step ‘lower’ in the list’s visual outline.

This is the expected behaviour.

However, in {productname} 6.0, when `nonbreaking_force_tab` is set to `true`, the first behaviour above does not present. Instead, when the setting is `nonbreaking_force_tab: true` and the insertion point is within a table cell, pressing the tab key causes the string `&nbsp;&nbsp;&nbsp;` to be entered into the cell. `&nbsp;&nbsp;&nbsp;` is three non-breaking space HTML entities, the closest equivalent to a `tab` character supported in HTML.

The proximate cause of this incorrect behaviour is the move of _Tables_ from plugins to core. As of this release, however, the specific cause is still being investigated. And no workaround (other than keeping `nonbreaking_force_tab` set to `false`) is currently available.




[id=apis]
== APIs

[id=new-and-improved-apis]
=== new and improved APIs

==== `Editor.options`

* The new `editor.options` API replaces both `editor.settings` and `editor.getParam`.

=== Changed APIs

==== `closeButton` and `timeout`

* Previously, using `closeButton` to disable a _Notification’s_ close button required a `timeout` value to also be set.

  In {productname} 6, `closeButton` shows or hides the close button regardless of a `timeout` value being set or not set.

  Equivalently, setting a `timeout` value sets how long the notification presents before automatically closing, regardless of whether a close button is displayed or not.


==== `disabled` functions re-named in all {productname} APIs

Previously, multiple {productname} APIs and UI classes used `disable` or `disabled` in their function or property names.

In {productname} 6, these function names have been changed and configuration changes are required.

1. `isDisabled()` functions are now `isEnabled() functions.

2. The `enable()` and `disable()` functions are now the single `setEnabled(<state>)` function.

3. The `disable(<name>)` and `enable(<name>)` functions are now the single `setEnabled(<name>, <state>)` function in the Dialog APIs.

As well, the `.disabled` property is now the `.enabled` property in all {productname} UI classes.


==== success or failure callbacks replaced by `Promise` in multiple APIs

* Previously, the AddOnManager, PluginManager, ScriptLoader, StyleSheetLoader, and ThemeManager APIs report resource loading status with `success` or `failure` callbacks.

  These APIs now, instead, return a `Promise`, with a value of either `resolve` or `reject`.



- fixed
- added

[id=removed-or-deprecated-apis]
=== Removed or deprecated APIs

[id=removed-or-deprecated-apis-tables]
==== Table

* The `table` plugin’s functionality is, as of {productname} 6.0, entirely focussed on the user interface (UI) for creating and editing tables.

  The code that generates tables is now a Core part of {productname} 6.0.

  Since the `table` plugin API was entirely concerned with generating tables, it has been removed.

// Don’t forget to set a visual check mark of some sort to denote the removal or deprecation of any previously undocumented things.


== Commands and queries

=== New and improved commands and queries

==== mceInsertTableDialog

* `mceInsertTableDialog` is the new command for invoking an _Insert Table_ dialog box.

   The previous command, `mceInsertTable`, no longer works to invoke an _Insert Table_ dialog box: use the `mceInsertTableDialog` command instead.

   The `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user input.


=== Changed commands and queries

==== `mceAddEditor` and `mceToggleEditor`

Previously, `mceAddEditor` and `mceToggleEditor` used the `editorManager.settings` values to set the `id` and UI and UX options for a new {productname} editor instance.

`editorManager.settings` is not used at all in {productname} 6.

Instead, the `mceAddEditor` and `mceToggleEditor` commands use `id` and `options` values from an object passed when the command is run.

=== Fixed commands and queries

=== Femoved or deprecated commands and queries

// Don’t forget to set a visual check mark of some sort to denote the removal or deprecation of any previously undocumented things.


== Events

- new and improved
- changed
- fixed
- removed or deprecated
    - visual check mark of some sort to denote the removal or deprecation of previously undocumented things

== Formatting

- new and improved
- changed
- fixed
- removed or deprecated
    - visual check mark of some sort to denote the removal or deprecation of previously undocumented things

== Functions

- new and improved
- changed
- fixed
- removed or deprecated
    - visual check mark of some sort to denote the removal or deprecation of previously undocumented things

== Options

=== New and improved options

=== Changed options

==== link_default_protocol

The `link_default_protocol` option sets the link protocol used by links added or edited using the _link_ dialog.

It now defaults to `https`. Previously it defaulted to `http`.

NOTE: the `link_default_protocol` value is only applied to an edited or inserted link if the protocol is not explicitly specified.

==== tinymce.activeEditor.options.get

Previously `tinymce.activeEditor.options.get('plugins')` returned the configured plugins as a string.

As of {productname} 6, `tinymce.activeEditor.options.get('plugins')` now returns the configured plugins as an array.



=== Fixed options

=== Added options

=== Removed or deprecated options

[id=removed-or-deprecated-options-textpattern]
==== TextPattern

* the `textpattern_patterns` option is no longer an option. It is has been re-named, to `text_patterns` and is now a Core part of {productname} 6.0.

   All references to `textpattern_patterns` (and `text_patterns`) should be removed from your configurations.

*  Also, the API called `textpattern` has been removed.

*  Finally, text patterns are now on by default. `text_patterns: false` turns the functionality off.




// Don’t forget to set a visual check mark of some sort to denote the removal or deprecation of any previously undocumented things.


== Parsing and serialisation

- new and improved
- changed
- fixed
- added
- removed or deprecated
    - visual check mark of some sort to denote the removal or deprecation of previously undocumented things

[id=plugins]
== Plugins

[id=new-and-improved-plugins]
=== New and improved plugins

[id=new-and-improved-plugins-imagetools]
==== EditImage

_EditImage_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin], replaces the now-deprecated and removed _ImageTools_ plugin. The `imagetools` plugin is no longer part of the Core open source editor.

An `editimage` options were also re-named: `editimage_proxy` is now `editimage_proxy_service_url`, making it easier to configure when accessing https://tiny.cloud/docs/enterprise/server/[Tiny-specific services].

`editimage` also offers a new export plugin option: `export_image_proxy_service_url`.

NOTE: `editimage_proxy` (the re-named equivalent to the previous `imagetools_proxy`) is still available as an alternative configuration option for setting up image proxy functionality without using Tiny services.


[id=new-and-improved-plugins-emoticons]
==== Emoticons

* The `emoticon` plugin now uses the more accurate word, _Emoji_, in its tool bar, menu item and dialog box.

   In previous versions, the word presented in these parts of the plugin’s user-interface was _Emoticon_.

   NOTE: The plugin, itself, is still called Emoticons. And the plugin description and the plugin’s configuration and Help dialogs still reflect this.


[id=new-and-improved-plugins-table-of-contents]
==== Table of contents

* There are no end-user facing changes between the previous `toc` plugin and the `tableofcontents` plugin. However, the `tableofcontents` plugin now uses https://terser.org[terser] to improve performance.

  NOTE: the `tableofcontents` plugin is no longer part of the Core open source editor. Table of Contents is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].


[id=changed-plugins]
=== Changed plugins

[id=changed-plugins-autoresize]
==== Autoresize

* Previously, the `autoresize` plugin offered an `autoresize_on_init` option.

  This setting does not do anything meaningful, and had been previously deprecated.

  As of {productname} 6.0, it has been removed from the `autoresize` plugin.

[id=changed-plugins-media]
==== Media

* In {productname} 5.x, the `media` plugin used https://tiny.cloud/docs/api/tinymce.html/tinymce.html.saxparser/[SaxParser] to validate elements for parsing.

  As of {productname} 6.0, SaxParser is no longer used. Another {productname} public API — DomParser — is used instead.

  As a consequence the `iframe`, `video`, `audio`, and `object` elements are no longer marked as _special_. Instead their contents are simply validated against the {productname} schema.

NOTE: The {productname} public API, DomParser uses, in turn, the same-named browser parsing API: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser[DomParser].

* The `media` plugin’s `media_scripts` option was deprecated in {productname} 5.10.

// Based on the code it looks like `media_scripts` was meant to be a way to provide an allowed list of <script>s that could be used to embed media. However, somewhere along the lines it broke and no longer works.

  As of the release of {productname} 6.0, this option has been removed completely.

[id=changed-plugins-noneditable]
==== Noneditable

* The `noneditable` plugin is no longer a plugin. It is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `noneditable` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=changed-plugins-paste]
==== Paste

* The `paste` plugin’s functionality is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `paste` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

* The `paste_data_images` option now defaults to `true`. When `paste` was a plugin, this option was, by default, set to `false`, which prevented images being pasted from the local machine.

* The `mceInsertClipboardContent` argument, `content`, has been re-named. It is now `html`.

  The new name is a more accurate reflection of what sort of data the argument passes.

  NOTE: `PastePreProcess` also takes an argument, `content`. This argument, for this command, has not changed.


[id=changed-plugins-print]
==== Print

* `print` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

   In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

   All references to `print` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=changed-plugins-table]
==== Table

* The `table` plugin’s functionality is, as of {productname} 6.0, entirely focussed on the user interface (UI) for creating and editing tables.

  The code that generates tables is now a Core part of {productname} 6.0.

* If the selected cells in the `tfoot` section of a table were header elements (ie were `th` elements), pressing the `table` row header toolbar button (which invokes the `mceTableRowType` command) returned the row as a header row.

  This was incorrect: the section takes precedence and cells in the `tfoot` section of a table should be declared as a footer row.

  In {productname} 6.0, selecting cells in the `tfoot` section of a table and pressing the row header toolbar button returns the row as a footer row, as expected.

* `mceInsertTableDialog` is the new command for invoking an *Insert Table* dialog box.

   The previous command, `mceInsertTable`, no longer works to invoke an *Insert Table* dialog box: use the `mceInsertTableDialog` command instead.

   The `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user-input.

* The default values for the `table_style_by_css` and the `table_use_colgroups` options have both been changed.

  Previously, these options defaulted to `false`. As of {productname} 6.0, both options now default to `true`.

  This is in line with modern web practice.

* the `table_responsive_width` option was previously deprecated and superseded by `table_sizing_mode`.

  In {productname} 6.0, the `table_responsive_width` option has been removed.




[id=fixed-plugins]
=== Fixed plugins

[id-added-plugins]
=== Added plugins

[id=removed-or-deprecated-plugins]
=== Removed or deprecated plugins

[id=removed-or-deprecated-plugins-bbcode]
==== BBCode

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `bbcode` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[id=removed-or-deprecated-plugins-color-picker]
==== Color Picker

* Color Picker’s functionality has been a built in part of {productname} since version 5.

  Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the empty `colorpicker` plugin has now been removed.

[id=removed-or-deprecated-plugins-context-menu]
==== Context Menu

* Context Menu’s functionality has been a built in part of {productname} since version 5.

  Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the empty `contextmenu` plugin has now been removed.

[id=removed-or-deprecated-plugins-full-page]
==== Full Page

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `fullpage` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[id=removed-or-deprecated-plugins-hr]
==== HR

* The `hr` (horizontal rule) functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `hr` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=removed-or-deprecated-plugins-imagetools]
==== ImageTools

* The `imagetools` plugin is no longer part of the Free {productname} editor. _Image Tools_ is now _Edit Image_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

[id=removed-or-deprecated-plugins-legacy-output]
==== Legacy Output

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `legacyoutput` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[id=removed-or-deprecated-plugins-paste]
==== Paste

* The `paste` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

* Because the functionality was unmaintained, `paste` no longer supports input from Microsoft Word.

  There is an open https://github.com/tinymce/tinymce/discussions/7487[request for maintainers] should someone in the community be interested in taking over maintainance of this particular functionality as a separate plugin.

  If a community-maintained version of the `paste` plugin becomes available, we will link to it from the xref:6.0-migration-guide.adoc#plugins-paste[_{productname} 6.0 Migration Guide_].

  NOTE: the Premium plugin, https://tiny.cloud/docs/plugins/premium/powerpaste/[`PowerPaste`], is available. It provides the capability to accept data from Microsoft Word and Microsoft Excel, and clean-up the received data before pasting it into place.

[id=removed-or-deprecated-plugins-print]
==== Print

* `print` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

   In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

   All references to `print` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[id=removed-or-deprecated-plugins-spellchecker]
==== Spellchecker

* As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the `spellchecker` plugin has been removed. It is no longer part of {productname} 6.0.

  The https://tiny.cloud/tinymce/features/#productivity[Premium plugin], https://tiny.cloud/docs/plugins/premium/tinymcespellchecker/[Spellchecker Pro], which offers equivalent functionality and more, is available.

[id=removed-or-deprecated-plugins-tabfocus]
==== TabFocus

* The `tabfocus` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

  The `tabfocus_elements` option, which relied on the `tabfocus` plugin, no longer functions.

  As well, the `tab_focus` option was previously deprecated by `tabfocus_elements`. With this release, the `tab_focus` option has been removed completely.

  As per standard web practice, the `tabindex` attribute should be used instead of the `tabfocus` plugin or any of the `tabfocus` plugin’s options.

  As per that standard web practice, the `tabindex` attribute is copied from the target element to the iframe.

[id=removed-or-deprecated-plugins-table-of-contents]
==== Table of contents

* The `toc` plugin is no longer part of the Core open source editor. _Table of Contents_ is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

   NOTE: although there are no end-user facing changes, as part of the general architectural change, the `tableofcontents` Premium plugin has modernised its output. It uses the ES2020 library and targets ES2018. It also uses https://terser.org[terser] to improve performance.

[id=removed-or-deprecated-plugins-text-color]
==== Text color

* Text color’s functionality has been a built in part of {productname} since version 5.

  Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement], the empty `textcolor` plugin has now been removed.

[id=removed-or-deprecated-plugins-text-pattern]
==== TextPattern

* The `textpattern` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

  In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

  All references to `textpattern` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

* Also, the API that called `textpattern` has been removed.



// Don’t forget to set a visual check mark of some sort to denote the removal or deprecation of any previously undocumented things.

== Properties

- new and improved
- changed
- fixed
- added
- removed or deprecated
    - visual check mark of some sort to denote the removal or deprecation of previously undocumented things

== Schema

=== New and improved schema

* {productname} 6.0 instances now use HTML 5 as the default schema.

  The previous default was, for practical purposes, also HTML 5 but no specific schema was set. This change formalises and makes explicit what was, previously, only implicit.

  NOTE: `html5-strict` is still an available schema option and is unchanged from {productname} 5.x.

* The assignment operator character — `:` — has been changed to `~` for the `valid_elements` and `extended_valid_elements` schemata.

  The `:` is also used to assign an [xlink:href] rule and this was not possible in these schemata because the colon character was acting as an assignment operator.

  This change allows both schemata to set attribute values for the `valid_elements` and `extended_valid_elements` options using the `~` character and assign [xlink:href] rules as expected.



=== Changed schema



=== Fixed schema

=== Added schema

=== Removed or deprecated schema

// Don’t forget to set a visual check mark of some sort to denote the removal or deprecation of any previously undocumented things.

== UI and UX elements and components

=== new and improved UI and UX elements and components

[id=new-and-improved-ui-and-ux-elements-and-components-editor-text-entry-height]
==== Editor text entry height

* In {productname} 5.x, editors without a specified `config.height` value defaulted to a 200px high text entry area.

  In {productname} 6.0, editors without a specified `config.height` value default to a 400px high text entry area.

[id=new-and-improved-ui-and-ux-elements-and-components-buttontype]
=== dialog box re-rendering

Previously, when a component in a {productname} dialog box changed — for example, when a _next_ or _previous_ button was clicked — the entire dialog box was re-rendered.

In {productname} 6.0, the `redial` API now only re-renders the portions of a dialog that have changed.

==== new property, `buttonType`

`buttonType` is a new property available as a basic panel component of `dialogs`. It replaces the, now deprecated property, `primary`.

The `primary` property was boolean, allowing for only two states: `true` and `false`.

The new `buttonType` property can take any of three states: `'primary'`, `'secondary'`, and `'toolbar'`.

Setting `buttonType: 'primary'` is the same as setting `primary: true`.

Setting `buttonType: 'secondary'` is the same as setting `primary: false`.


=== Changed UI and UX elements and components

==== buttonType

`buttonType` is a new property available as a basic panel component of `dialogs`. It replaces the, now deprecated property, `primary`.

==== `disabled` properties re-named to `.enabled` in {productname} UI classes

Previously, {productname} UI classes provided a `.disabled` property.

In {productname} 6, this property has been re-named to `.enabled`.

Also, the Dialog API, which previously offered the `disable(<name>)` and `enable(<name>)` functions, now offers a single `setEnabled(<name>, <state>)` function.

==== Editor text entry height

In {productname} 5.x, editors without a `height` value specified in the {productname} configuration defaulted to a 200px high text entry area.

In {productname} 6.0, editors without a `height` value specified in the {productname} configuration default to a 400px high text entry area.

As was the case in {productname} 5.x, this new default only applies to editors in `iframe` mode, not `inline` mode.


=== Fixed UI and UX elements and components

==== Tables are now positioned using `margins`, not `float`

{productname} previously used `float` to position tables to the left or right of the viewport (the working area available to the {productname} editor). This caused multiple layout and UX problems.

As of {productname} 6.0, tables are positioned using `margins` rather than `float`. This prevents these layout and UX problems occuring.

However, when upgrading to {productname} 6.0, there are two things to be aware of:

First, {productname} 6.0 does not alter existing documents. Extant {productname} documents with tables that were aligned to either _left_ or _right_ will still have the `float` property assigned when opened and edited unless and until their *alignment* is altered.

If an extant {productname} document with an aligned table is opened using {productname} 6.0 and the *alignment* of the table is re-set, {productname} 6.0 will remove the `float` property and use the `margin` property to set the *alignment*.

Second, if the previous behaviour is required, a custom `format` will need to be created.

=== Added UI and UX elements and components

=== Removed or deprecated UI and UX elements and components

==== primary

the `primary` property was a boolean property available as a basic panel component of `dialogs`.

It has been deprecated and replaced by the new `buttonType` property.

// Don’t forget to set a visual check mark of some sort to denote the removal or deprecation of any previously undocumented things.
