= TinyMCE 5.x -> 6.0 Migration Guide

include::6.0-release-notes.adoc#things-we-renamed

include::6.0-release-notes.adoc#default-value-changes


== APIs

=== Changed APIs

==== `closeButton` and `timeout`

* Previously, using `closeButton` to disable the close button presented as part of a _Notification_ required a `timeout` value to also be set.

  In {productname} 6, `closeButton` shows or hides the close button regardless of a `timeout` value being set or not set.

  Equivalently, setting a `timeout` value sets how long the notification presents before automatically closing, regardless of whether a close button is displayed or not.

NOTE: this does not change the behaviour of existing _Notifications_. An `editor.notificationManager` with both `timeout: 5000` and `closeButton: false` set will still present a notification without a close button that automatically closes after displaying for 5 seconds.



== Commands and queries

=== New and improved commands and queries

==== `mceInsertTableDialog`

Previously, the `mceInsertTable` command worked in two modes.

If invoked without arguments —

`tinymce.activeEditor.execCommand('mceInsertTable');`

— the command opened the *Insert Table* dialogue box.

If invoked with arguments — 

`tinymce.activeEditor.execCommand('mceInsertTable', false, { rows: 2, columns: 2 });`

— the command inserted a table, with the specified properties, directly into the document without opening the *Insert Table* dialog box.

In {productname} 6.0, the `mceInsertTableDialog` command must be used to invoke the *Insert Table* dialog box.

NOTE: the `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user-input. However, using the `mceInsertTable` command without arguments now throws a console error: `model.min.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'rows')`.

=== Changed commands and queries

==== `mceAddEditor` and `mceToggleEditor`

Previously, `mceAddEditor` and `mceToggleEditor` used the `editorManager.settings` values to set the `id` and UI and UX options for a new {productname} editor instance.

`editorManager.settings` is not used at all in {productname} 6.

Instead, the `mceAddEditor` and `mceToggleEditor` commands use `id` and `options` values from an object created when the command is run.

For example —

`tinyMCE.execCommand('mceAddEdit', false, { id: 'ed-1', options: { readonly: false, toolbar: 'bold italic strikethrough' } })`

— finds a `textarea` with id `ed-1` and turns it into a working {productname} editor that displays the _bold_, _italic_, and _strikethrough_ options in the editor toolbar.




== Options

=== Changed options

==== link_default_protocol

The `link_default_protocol` option sets the link protocol used by links added or edited using the _link_ dialog.

It now defaults to `https`. Previously it defaulted to `http`.
  
NOTE: the `link_default_protocol` value is only applied to an edited or inserted link if the protocol is not explicitly specified.


== Plugins

=== Removed plugins

All references to any of these plugins should be removed from plugin configurations.

See below for specific documentation of potential migration issues, if any, regarding these removed plugins.

Eight `plugins` were removed because their functionality is now a Core part of {productname} 6.0:

1. `colorpicker`
  
2. `contextmenu`

3. `hr`
  
4. `noneditable`

5. `paste`

6. `print`

7. `textcolor`

8. `textpattern_patterns`

These plugins were already empty. As of {productname} 6.0, however, they are gone entirely.

Three plugins were removed as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[announcement]:

1. `fullpage`

2. `bbcode`
  
3. `legacyoutput`

One plugin was removed as no longer supported:

1. `spellchecker`

NOTE: The https://tiny.cloud/tinymce/features/#productivity[Premium plugin], https://tiny.cloud/docs/plugins/premium/tinymcespellchecker/[Spellchecker Pro], which offers equivalent functionality and more, is available.

=== ImageTools                        

As noted in the xref:6.0-release-notes.adoc#removed-or-deprecated-plugins-imagetools[_{productname} 6.0 Release Notes_], the `imagetools` plugin is no longer included as part of the Core open source editor.

_ImageTools_ is now _EditImage_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin] that offers real-time updates of image as they are edited.

`editimage` also offers two new options:

1. `editimage_proxy_service_url` and

2. `export_image_proxy_service_url`.

These new options provide access to Tiny-specific services.
  
NOTE: `editimage_proxy` (the re-named equivalent to the previous `imagetools_proxy`) still works. It is the fallback option should the Tiny-specific services not be available.

Users of the Free version of {productname} 5.x who rely on the, now deprecated and removed, `imagetools` plugin, should not upgrade to {productname} 6.0 without also installing https://tiny.cloud/tinymce/features/#productivity[_EditImage_].

=== Media

As noted in the xref:6.0-release-notes.adoc#changed-plugins-media[_{productname} 6.0 Release Notes_], the `media` plugin no longer uses the SaxParser.

As a consequence the `iframe`, `video`, `audio`, and `object` elements are no longer marked as _special_, and cannot be marked as such. Put another way, the DomParser does not preserve embedded content.

Instead these elements, and their contents, are validated against the {productname} schema.

This validation is generally done by the `valid_elements`, `valid_children` or `extended_valid_elements` config.

The schema must, therefore, be configured to allow usage of the media elements, and the media element attributes.

NOTE: as of this release, there are no known cases of this change causing media objects to not work as expected. But, also as of this release, not every potential or possible use-case has been tested.

[id=plugins-paste]
=== Paste

As noted in the xref:6.0-release-notes.adoc#removed-or-deprecated-plugins-paste[_{productname} 6.0 Release Notes_], the `paste` plugin’s functionality is no longer provided as a plugin. It is now a core part of {productname} 6.0.

In conjunction with this change, three changes have been made:

1. A `paste` default has changed. The `paste_data_images` option now defaults to `true`.

   When `paste` was a plugin, this option was, by default, set to `false`, which prevented images being pasted from the local machine.

2. The `mceInsertClipboardContent` argument, `content`, has been re-named. It is now `html`.

   The new name is a more accurate reflection of what sort of data the argument passes.
   
   The `content` argument can no longer be used with `mceInsertClipboardContent`. If it is used [what happens?]
  
NOTE: `PastePreProcess` also takes an argument, `content`. This argument, for this command, has not been changed.


3. The, now built-in, `paste` functionality no longer supports pasting from Microsoft Word.

   There is an open https://github.com/tinymce/tinymce/discussions/7487[request for maintainers] should someone in the community be interested in taking over maintainance of this particular functionality as a separate plugin.

   If a community-maintained version of the `paste` plugin becomes available, we will link to it from here.

NOTE: the Premium plugin, https://tiny.cloud/tinymce/features/powerpaste[`PowerPaste`], is available. It provides the capability to accept data from Microsoft Word and Microsoft Excel, and clean-up the received data before pasting it into place.

=== Table of Contents

As noted in the xref:6.0-release-notes.adoc#new-and-improved-plugins-table-of-contents[_{productname} 6.0 Release Notes_], the `toc` plugin is no longer part of the Core open source editor.

Table of Contents has been updated and is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

Users of the Free version of {productname} 5.x who rely on the, now deprecated and removed, `toc` plugin, should not upgrade to {productname} 6.0 without also installing https://tiny.cloud/tinymce/features/#productivity[_Table of Contents_].


=== Text Patterns

As noted in the xref:6.0-release-notes.adoc#removed-or-deprecated-plugins-text-pattern[_{productname} 6.0 Release Notes_], the `textpattern_patterns` plugin:

* was renamed to `text_patterns`;

* and had its functionality moved to the Core of {productname} 6.0.

As well, the `textpattern` API has been removed.

Finally, and unlike in previous versions of {productname}, text patterns are now on by default. `text_patterns: false` or `text_patterns: []` turns the functionality off.

After upgrading:

* rename any options in your {productname} init configuration to match the new name. 

* remove `textpattern` from your plugins list.


== Schema

=== New and improved schema

* {productname} 6.0 instances now use HTML 5 as the default schema.

  The previous default was, for practical purposes, also HTML 5, but no specific schema was set. This change formalises and makes explicit what was, previously, only implicit.
  
  NOTE: `html5-strict` is still an available schema option and is unchanged from {productname} 5.x.

* The assignment operator character — `:` — has been changed to `~` for the `valid_elements` and `extended_valid_elements` schemata.

  The `:` is also used to assign an [xlink:href] rule and this was not possible in these schemata because the colon character was acting as an assignment operator.
  
  This change allows both schemata to set attribute values for the `valid_elements` and `extended_valid_elements` options using the `~` character and assign [xlink:href] rules as expected.
  
  Existing configurations using either of these schemata must be edited so the `~` character is used for `valid_elements` and `extended_valid_elements` options configurations. The `:` character should no longer be used to set attribute values in these configurations.
  
  Also, when assigning `[xlink:href]` rules, the colon character is no longer escaped. `[xlink\\:href]` can now be written plainly, as `[xlink:href]`.
  
  NOTE: existing configurations that included escaped colons will continue to work as expected. Editing such configs to remove the escape characters will improve readability but is not necessary for functionality.


  


== UI elements and components

[id=ui-elements-and-components-editor-text-entry-height]
=== Editor text entry height

In {productname} 5.x, editors without a specified `config.height` value defaulted to a 200px high text entry area. In {productname} 6.0, editors without a specified `config.height` value default to a 400px high text entry area.

The new default can be over-ridden by setting the element’s `height` to a value larger than 400px using CSS. Setting the elmement’s `height` to a value less than 400px using CSS will *not* reduce the height of the text entry area, however.

NOTE: {productname} 6.0 honours the `config.height` setting. To prevent text entry areas from disappearing during re-sizing, however, the `min-height` option of 100px cannot be over-ridden

//    Need to preserve the 200px height? _[here’s how?]_

=== buttonType

// The primary property on dialog buttons has been deprecated. Use the
// new buttonType property instead #TINY-8304
//  
//    Also add this to release notes as
//  
//  1. Changed UI element or component



// where does the change in how tables are positioned fit in the above structure?

== Tables

=== Tables are now positioned using `margins`, not `float`

{productname} previously used `float` to position tables to the left or right of the viewport (the working area available to the {productname} editor). This caused multiple layout and UX problems.

For example, consider a {productname} document that included a table that took up less than 100% of the viewport and a paragraph of text below that table. If both the table and the paragraph were selected and their *alignment* was changed to _left_ or _right_, the paragraph of text moved up beside the table.

As another example, consider a {productname} document containing a table that is wider than the viewport. If you selected this table’s contents and set the *alignment* to _right_, the portion of the table that was outside the viewport disappeared to the left, and no scrollbar presented allowing you to bring that portion back into view.

As of {productname} 6.0, tables are positioned using `margins` rather than `float`. This prevents these layout and UX problems occuring.

However, when upgrading to {productname} 6.0, there are two things to be aware of:

1. {productname} 6.0 does not alter existing documents. Extant
   {productname} documents with tables that were aligned to either
   _left_ or _right_ will still have the `float` property assigned
   when opened and edited unless and until their *alignment* is
   altered.

   If an extant {productname} document with an aligned table is opened
   using {productname} 6.0 and the *alignment* of the table is re-set,
   {productname} 6.0 will remove the `float` property and use the
   `margin` property to set the *alignment*.

2. If the old behaviour is required, a custom format will need to be
   created.

