= TinyMCE 6.2
:navtitle: TinyMCE 6.2
:description: Release notes for TinyMCE 6.2
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.2 was released for {enterpriseversion} and {cloudname} on Monday, September 26^th^, 2022. It includes {productname} 6.2, additional changes to Premium plugins, and several new Premium plugins. These release notes provide an overview of the changes for {productname} 6.2:

* xref:new-premium-plugins[New Premium plugins]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]

[[new-premium-plugins]]
== New Premium plugins

=== Spelling Autocorrect 1.0.0

The {productname} 6.2 release includes the new **Autocorrect** premium plugin.

The Spelling Autocorrect plugin allows {productname} to autocorrect a specified set of spelling errors, common typos, and capitalization errors, as they are being typed.

For information on the **Spelling Autocorrect** plugin, see: xref:autocorrect.adoc[Spelling Autocorrect].

=== Footnotes 1.0.0

The {productname} 6.2 release includes the new **Footnotes** premium plugin.

The Footnotes plugin allows the user to add footnotes to {productname} documents.

For information on the **Footnotes** plugin, see: xref:footnotes.adoc[Footnotes].

=== Merge Tags 1.0.0

The {productname} 6.2 release includes the new **Merge Tags** premium plugin.

The Merge Tags plugin allows the user to insert merge tags (also known as a personalization tokens, or a mail merge fields) into {productname} documents.

For information on the **Merge Tags** plugin, see: xref:mergetags.adoc[Merge Tags].


[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.2.

=== Enhanced Media Embed 3.0.4

The {productname} 6.2 release includes an accompanying release of the **Enhanced Media Embed** premium plugin.

**Enhanced Media Embed** 3.0.4 fixes the following bug:

Previously, embedded audio objects became invisible when a left or right alignment was applied.

With this update all audio objects are set to `min-width: 100px` and now continue to show in {productname} documents when aligned left or right.

For information on the **Enhanced Media Embed** plugin, see: xref:introduction-to-mediaembed.adoc[Enhanced Media Embed].

=== Permanent Pen 2.0.2

The {productname} 6.2 release includes an accompanying release of the **Permanent Pen** premium plugin.

Permanent Pen 2.0.2 fixes the following bug:

Previously, if Permanent Pen was switched off (by, for example, clicking the Permanent Pen button in the toolbar so the button toggles from highlighted to not-highlighed) and the next user-action was to press the *Enter* or *Return* key, Permanent Pen did not turn off as expected.

This update improves Permanent Pen’s activate and deactivate mechanism. When the plugin is switched off and the next user-action is to press either *Enter* or *Return*, Permanent Pen stays switched off.

For information on the **Permanent Pen** plugin, see: xref:permanentpen.adoc[Permanent Pen].

=== PowerPaste 6.1.1

The {productname} 6.2 release includes an accompanying release of the **PowerPaste** premium plugin.

PowerPaste 6.1.1 fixes the following bug:

The `wordimport.js` resource file was difficult to bundle when using Webpack 5.

// #TINY-8791

// Bumped internal dependency of wimp to fix webpack 5 bundling issues

For information on the **PowerPaste** plugin, see: xref:introduction-to-powerpaste.adoc[PowerPaste].

=== Real-Time Collaboration 2.1.1

The {productname} 6.2 release includes an accompanying release of the **Real-Time Collaboration** premium plugin.

Real-Time Collaboration 2.1.1 fixes the following bug:

The Real_Time Collaboration plugin validates `that` parameters, used to set the token provider among other settings, as valid Promises.

However, Angular code wraps promises into ZoneAwarePromises. These fail said validation, throwing an `expected it to return a promise` error.

With this update, providers now accept any object that has `then` and `catch` functions as compatible with promise-like objects.

For information on the **Real-Time Collaboration** plugin, see: xref:rtc-introduction.adoc[Real-Time Collaboration].

=== Spell Checker Pro 3.1.0

The {productname} 6.2 release includes an accompanying release of the **Spell Checker Pro** premium plugin.

Spell Checker Pro 3.1.0 adds one change and fixes two bugs:

==== The `SpellcheckerLanguageChanged` event is now dispatched at plugin initialization

Spell Checker Pro now fires the `SpellcheckerLanguageChanged` event when it is initialized, making the language Spell Checker Pro has been configured to use available for querying.

This enables other plugins to check for the currently configured language.

==== Ins some specific cases, copying and pasting in tables did not work as expected due to Spell Checker Pro incorrectly moving the selection

In some circumstances, Spell Checker Pro would silently, and incorrectly, extend a selection. When the extended selection was then copied-and-pasted, unexpected results occurred.

For example, in some circumstances the selection appeared to be the contents of a single table cell, but Spell Checker Pro incorrectly extended the selection to include an HTML markup element outside the table. When this wa pasted, the incorrectly added element made the paste behave incorrectly.

With this update, the way elements are traversed when selections are being made has been changed. Consequently, incorrect selection extension no longer occurs, and copying-and-pasting content from tables works as expected.

==== Spellchecking incorrectly triggered on all `change` events

Spell Checker Pro should trigger on any `paste` event, whether the event comes from a plugin (such as Paste or PowerPaste) or a native browser action. Previously, however, Spell Checker Pro was listening to the wrong event — the `change` event — to cover this case.

As a consequence, Spell Checker Pro triggered on all `change` events.

With this update, Spell Checker Pro now listens for input events and only triggers when content is inserted into a {productname} document.

For information on the **Spell Checker Pro** plugin, see: xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro].

[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.2 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following update:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.2 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[additions]]
== Additions

{productname} 6.2 also includes the following additions:

=== A new `text_patterns_lookup` option to provide additional text patterns dynamically.

// #TINY-8778

=== A new promotion element has been added to the default UI.

{productname} 6.2 includes an *Upgrade* promotion button. It appears in the unused corner of the {productname} menu bar.

It can be disabled using the new `promotion` option.

For more information see xref:content-appearance.adoc#premium-upgrade-promotion-option[Premium upgrade promotion option].

=== New `format_noneditable_selector` option to specify the `contenteditable="false"` elements that can be wrapped in a format.

// #TINY-8905

=== Added `allow` as a valid attribute for the iframe element in the editor schema.

// #TINY-8939

=== New search field in the MenuButton that shows a search field at the top of the menu, and refetches items when the search field updates.

// #TINY-8952


[[improvements]]
== Improvements

{productname} 6.2 also includes the following improvements:

=== The formatter can now apply a format to a `contenteditable="false"` element by wrapping it.

Configurable using the `format_noneditable_selector` option.

// #TINY-8905

=== The autocompleter now supports a multiple character trigger using the new trigger configuration.

// #TINY-8887

=== Some inline formatting, such as color and font size, can now be applied to list item elements

In {productname} 6.2 list bullets and list numbers can be inline-formatted.

If the contents of a list item are selected and inline formatting is applied — such as a change of color or change of font-size — this spot-formatting is also applied to the list item’s associated bullet or number.

For more information see the xref:advlist.adoc#inline-formatting[Inline formatting of list elements documentation].

=== The installed and available plugin lists in the Help dialog are now sorted alphabetically.

Previously, when the *Help > Help* dialog was invoked, and the _Plugins_ list was selected, available Premium plugins were supposed to be presented in alphabetical order by name.

This was done manually, however, and the manual presentation was not entirely alphabetical.

Also, this manual sort did not take account of the selected UI language and the Premium plugin names were not, in the main, translated.

With this update Premium plugin names are explicitly not translated. But they are, now, correctly sorted in alphabetical order by name.

=== Alignment can now be applied to more embedded media element types.

Embedded media elements could not, previously, be set to left, right, or center alignment.

With this update they can. Selecting an embedded media element and clicking the left, right, or center alignment toolbar buttons, or selecting the appropriate option from the *Format > Align* sub-menu, sets the element to the chosen alignment.


[[changes]]
== Changes

{productname} 6.2 also incorporates the following changes:

=== The `@menubar-row-separator-color` oxide variable no longer affects the divider between the Menubar and Toolbar.

Testing revealed circumstances in which an unnecessary border was added under the {productname} Menu bar.

This update includes changes to the `@menubar-row-separator-color` oxide variable. It now only controls the color of the separator lines drawn in multiline Menubars.

Consequently, unnecessary borders are no longer added under the {productname} menu bar.

=== The `@toolbar-separator-color` oxide variable now affects the color of the separator between the Menu bar and Toolbar only.

In concert with the testing above that discovered an unnecessary border occasionally being added under the {productname} Menu bar, the `@toolbar-separator-color` oxide variable was also changed.

This variable now only affects the color of the separator between the {productname} Menu bar and the {productname} Toolbar.

=== Available Premium plugins, which are listed by name in the Help dialog, are no longer translated.

Previously, when the *Help > Help* dialog was invoked, and the _Plugins_ list was selected, available Premium plugins were supposed to be presented in alphabetical order by name.

This was done manually, however, and the manual presentation was not entirely alphabetical.

Also, this manual sort did not take account of the selected UI language and the Premium plugin names were not, in the main, translated.

With this update Premium plugin names are explicitly not translated. But they are, now, correctly sorted in alphabetical order by name.

[[bug-fixes]]
== Bug fixes

=== The Autolink plugin did not work when text nodes in the content were fragmented.
//

// #TINY-3723

=== Fixed multiple incorrect types on public APIs found while enabling TypeScript strict mode.

// #TINY-8806

=== The number of blank lines returned from `editor.getContent({format: 'text'})` differed between browsers.

// #TINY-8579

=== The editor focused via the `auto_focus` option was not scrolled into the viewport.

// #TINY-8785

=== Adding spaces immediately after a `contenteditable="false"` block did not work properly in some circumstances.

// #TINY-8814

=== Elements with only `data-*` custom attributes were sometimes removed when they should not be removed.

// #TINY-8755

=== Selecting a figure with `class="image"` incorrectly highlighted the link toolbar button.

// #TINY-8832

=== Specifying a single, non-default list style for the `advlist_bullet_styles` and `advlist_number_styles` options was not respected.

// #TINY-8721

=== Fixed multiple issues that occurred when formatting `contenteditable` elements.

// #TINY-8905

=== Spaces could be incorrectly added to `urlinput` dialog components in certain cases.

`urlinput` dialog components are commonly but not exclusively presented in the **Insert/Edit Link** dialog.

// #TINY-8775

=== The text patterns logic threw an error when there were fragmented text nodes in a paragraph.

// #TINY-8779

=== Dragging a `contentEditable=false` element towards a document’s edge did not cause scrolling.

// #TINY-8874

=== Parsing large documents no longer throws a Maximum call stack size exceeded exception.

// #TINY-6945

=== DomParser filter matching was not checked between filters, which could lead to an exception in the parser.

// #TINY-8888

=== Fixed `contenteditable="false"` lists and `contenteditable="true"` list elements issues

`contenteditable="false"` lists can no longer be toggled; and contenteditable="true" list elements within these lists can no longer be indented, split into another list element, or appended to the previous list element by deletion.

// #TINY-8920

=== Removed extra bottom padding in the context toolbar of the TinyMCE 5 skin.

// #TINY-8980

=== Fixed a regression where pressing Enter added or deleted content outside the selection.

// #TINY-9101

=== Fixed a bug where pressing Enter deleted selected `contenteditable="false" <pre>` elements.

// #TINY-9101

=== The `editor.insertContent()` API did not respect the `no_events` argument.

If, for example, `editor.insertContent('<p>test</p>', { no_events: true });` was run, `BeforeGetContent` and `SetContent` events were still fired, despite `no_events` being set to `true`.

With this update, the API respects the `no_events: true` setting. Adding content to a {productname} document with `no_events` set to true now adds the content without firing events, as expected.

[[deprecated]
== Deprecated

=== The `autocompleter` configuration property, `ch`, has been deprecated.

`ch` will be removed in the next major release. Use the `trigger` property instead.

[source,js]
----
trigger: '<string>',
----


[[known-issues]]
== Known issues

This section describes issues that users of {productname} 6.2 may encounter and possible workarounds for these issues.

There is one known issue in {productname} 6.2 affecting the new premium plugin, xref:mergetags.adoc[Merge Tags].

=== Merge Tags cannot be manually added to a {productname} document in some circumstances

There are several circumstances where typing the Merge tags prefix (by default, `+{{+`) does not activate the `autocompleter`. Consequently, choosing a Merge tag from the expected pop-up menu is not possible because the pop-up menu does not present.

Moreover, in the circumstances where the `autocompleter` does not activate, even typing the entire Merge tag does not result in the string being turned in to a Merge tag.

There is a workaround, however.

If typing the Merge tags prefix does not work as expected, clicking the Merge tags toolbar button and selecting the desired Merge tag from the resultant menu inserts a functioning Merge tag.
