= TinyMCE 6.3
:navtitle: TinyMCE 6.3
:description: Release notes for TinyMCE 6.3
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.3 was released for {enterpriseversion} and {cloudname} on Wednesday, December 7^th^, 2022. It includes {productname} 6.3, additional changes to Premium plugins, and several new Premium plugins. These release notes provide an overview of the changes for {productname} 6.3:

* xref:new-premium-plugins[New Premium plugins]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:known-issues[Known issues]

[[new-premium-plugins]]
== New Premium plugins

=== Inline CSS 1.0.0

The {productname} 6.3 release includes the new **Inline CSS** premium plugin.

The Inline CSS plugin allows the user to <notes here>.

For information on the **Inline CSS** plugin, see: xref:inline-css.adoc[Inline CSS].

=== Advanced Typography 1.0.0

The {productname} 6.3 release includes the new **Advanced typography** premium plugin.

The **Advanced Typography** plugin, depending on its setting, can automatically or interactively replace common typewriter-style characters with their professional typesetter’s equivalents.

For information on the **Advanced typography** plugin, see: xref:advanced-typography.adoc[Advanced typography].

There are several known issues in **Advanced Typography** 1.0.0:

==== Switching the Advanced Typography target language does not always work as expected

Selecting a language from the *Advanced Typography* toolbar button’s menu, runs the rules for the newly selected over the current {productname} document.

In some circumstances, switching the target language in this fashion does not result in typesetting changes as expected. This is most visibly apparent with quotation marks.

The British English typesetting norm is to use opening and closing single-quote marks to denote direct quotation: *‘* and *’*.

The American English typesetting norm is to use opening and closing double-quote marks to denote direct quotation: *“* and *”*.

And one Spanish typesetting norm is to use guillemets, also known as comillas angulares, comillas franceses or chevrons, to denote direct quotation: *«* and *»*.

So, for example, if a {productname} document included a string thus:

[source,text]
----
"They went that way," he said, pointing.
----

Selecting _English (US)_ from the *Advanced Typography* toolbar icon’s pop-up menu transforms the text, as expected, into

[source,text]
----
“They went that way,” he said, pointing.
----

Following this action by, then, selecting _Spanish_ from the *Advanced Typography* toolbar icon’s pop-up menu, however, can result in the following incomplete typesetting change:

[source,text]
----
«They went that way, ” he said, pointing.
----

As of this release the only workaround is to not change *Advanced Typography* target languages.

==== The Advanced Typography plugin erroneously honors the current SpellChecker Pro language selection

There is currently a conflict between the selected **SpellChecker Pro** language and the selected **Advanced Typography** language.

When a **SpellChecker Pro** language is specified, **SpellChecker Pro** adds a `lang=<language-value>` attribute to the `<body>` tag and the **Advanced Typography** plugin erroneously honours this attribute when applying Typography rules.

Consequently, if, for example, the **Advanced Typography** plugin is set to Danish but the **SpellChecker Pro** language is set to English, when **Advanced Typography** rules are applied, it is English-language rules that are applied to the text, not Danish language rules.

As of this release, the only workaround is to either not specify a **SpellChecker Pro** language or to make certain the currently specified **SpellChecker Pro** language is the same as the desired **Advanced Typography** language.


[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.3.

=== Accessibility Checker 3.1.0

The {productname} 6.3 release includes an accompanying release of the **Accessibility Checker** premium plugin.

**Accessibility Checker** 3.1.0 includes the following fixes, additions, and improvements.

==== Merge tags prefix and suffix elements were not ignored

Previously, **Accessibility Checker** incorrectly flagged xref:mergetags.adoc[Merge Tags] prefixes and suffixes as presenting a contrast issue.

With this update, the **Accessibility Checker** plugin ignores Merge Tag prefixes and suffixes, as expected.

==== Added a new rule to show a warning when the alternative text of an image exceeds 100 characters
// @bforte review required
In {productname} 6.3, a new function was introduced that added a new rule to show a warning to the user when the alternative text of an image either exceeds 100 characters or when alternative text is not present for an image.

Warning prompts will be displayed as below examples.

When the alternative text exceeds the rule (>100) message will display `Image alternative text should be less than 100 characters`
Secondary message will display if this rule is triggered reading `Alternative text is (number) characters`, which provides the user with a `num_value` in which the alternative text count currently is.

If alternative text cannot be found, the message will display `Images must have an alternative text description.  Decorative images are not allowed`

Worth noting, if the user attempts to replace the alternative text with the same content as the `file_name` and click `repair`, the dialog will now display an error with the message `Alternative text must not be the same as the image filename`.


**Accessibility Checker** 3.1.0 now includes a rule that, when applied, shows a warning dialog when an image’s alternative (`+alt+`) text attribute exceeds 100 characters. This dialog also presents the alternative text in an editable field, for immediate repair.

==== Replaces the single warning icon presented in dialogs with icons specific to each alert level;

Previously, all **Accessibility Checker** warning dialogs presented with a triangle warning icon, regardless of whether the alert was informational, a warning, or an error.

With this update, **Accessibility Checker** shows a level-specific icon with each alert.

==== Improves the discoverability of the question mark button in warning dialogs
// @bforte review required
In {productname} 6.3 improvements were made to the `Help` icon in the accessibility checker dialog.

The changes made to the icon involved re-adjusting the icon’s text alignment to `centered`, and decreasing the font size for the subheadings under the label of  `issue, warning and error`.  

Additional changes were made to remove borders from the exterior of the description field while adjusting the contrast colors to ensure they matched the `background-color` for the icon changes that were added in {productname}’s 6.3 release also.

Many **Accessibility Checker** dialogs include a question mark icon. This icon is also a link to further information about the discovered issue.

This update includes changes to the presentation of this icon to make it's visability of being a `clickable button` more apparent to the user.

==== Improves the legibility of warning dialogs

In concert with the changes noted above to the question mark icon in **Accessibility Checker** dialogs, legibility improvements were made to the presentation and typography of these dialogs.

==== Added correct icons in dialog alert panel for each severity level

In {productname} 6.3, improvements for the accessibility checker were added to provide additional support for users when trying to identify different alerts such as _info_, _warning_ or _error_ icons.

In previous versions of {productname} the accessibility checker used the same triangle warning icon for all alerts when displayed. In {productname} 6.3, each alert type now displays a unique icon.

* Warning alerts now display as an exclamation mark nested inside a yellow circle.
* Error alerts now display as an exclamation mark nested inside a red triangle.
* Success alerts now display as a green tick.

For information on the **Accessibility Checker** plugin, see: xref:a11ychecker.adoc[Accessibility Checker].

=== Checklist 2.0.2

The {productname} 6.3 release includes an accompanying release of the **Checklist** premium plugin.

**Checklist** 2.0.2 includes one fix:

==== Checklist toggling did not preserve selection when used on an existing list.

In previous {productname} versions, when selecting content over either an ordered or unordered list, then switching the list to a checklist, the user’s content selection was not preserved.

In {productname} 6.3, the user selection is now preserved when toggling a list to a checklist.

For information on the **Checklist** plugin, see xref:checklist.adoc[Checklist].

=== Comments 3.2.0

The {productname} 6.3 release includes an accompanying release of the **Comments** premium plugin.

**Comments** 3.2.0 includes one fix and one change:

==== A comment could be inserted when in an empty editor or block

In previous {productname} versions a bug existed that allowed comments to be placed into an empty editor or block.

With this update, the comments button, menu-item, comment sidebar and shortcut keys are now disabled when the editor contains no content.

==== The selection now expands to encompass the word containing the insertion point when a comment is added

{productname} 6.3 adds xref:additions[two new API functions] — `tinymce.selection` and `tinymce.dom.RangeUtils`.

With these two functions available, if there is no selected text when a new comment is added, {productname} automatically extends the selection to encompass the word containing the insertion point and links the newly added comment to this automatically selected word.

For information on the **Comments** plugin, see: xref:introduction-to-tiny-comments.adoc[Introduction to Tiny Comments].


=== Merge tags 1.1.0

The {productname} 6.3 release includes an accompanying release of the **Merge tags** premium plugin.

**Merge Tags** 1.1.0 includes one addition, one fix, and one change:

==== New mceMergeTag command to wrap selected content in a merge tag

A new command, `mceMergeTag`, is now available as a Text Patterns option.

When this command is added as a `text_pattern`, manually typing a complete Merge Tag, including the prefix and suffix strings, into a {productname} document will result in the entered string being turned into an active merge tag when the string is completed by having a word boundary character added immediately after it.

In the following example, the Merge Tag prefix and suffix are the default, `{{` and `}}`

[source,js]
----
tinymce.init({
  selector: "textarea", // change this value according to your HTML
  plugins: "mergetags",
  text_patterns: [
    { start: '{{', end: '}}', cmd: 'mceMergeTag' }
  ],
  mergetags_list: [
  {
    value: 'merge.tag',
    title: 'A merge tag.'
  },
	],
  toolbar: "mergetags",
});
----

In this example, typing `{{string}}` followed by a word boundary character (such as a space, full-stop, question mark or comma) will result in the _string_ being turned into an active merge tag.

==== The autocompleter was triggered without being preceded by a merge tag prefix.

Previously, the Merge Tags autocompleter would remain after being triggered, in the case where a merge tag was inserted by the `mceMergeTag` command and not the autocompleter. 

In {productname} 6.3, the autocompleter now closes after the `mceMergeTag` command is executed.

==== Merge tags cannot exceed 255 characters in length

In {productname} 6.3 a new character limit range of 0-255 was introduced.

With this change, all Merge Tag items are now subject to this limit including `mergetags_lists`.

In {productname} 6.3, to support this feature, the editor will check all `mergeTag` lengths to ensure they do not exceed 255 characters. 

In the event the `mergeTag` length exceeds this, the item will not be accepted by the editor.

NOTE: some non-ASCII characters or Unicode codepoints count as more than one character.

For information on the **Merge tags** plugin, see: xref:mergetags.adoc[Merge Tags].


=== Spellchecker Pro 3.1.1

The {productname} 6.3 release includes an accompanying release of the **Spellchecker Pro** premium plugin.

**Spellchecker Pro** 3.1.1 includes one fix:

==== Spellchecker Pro could search outside of the {productname} editor for a language match.

For spelling, a word’s language was identified by finding the nearest `lang` attribute anywhere in an ancestor HTML element to the word (ie, any elements that contain the word). 

When {productname} was running in Inline mode, that included HTML ancestors that were provided by the host Browser, which are outside the {productname} editor instance.

If a `lang` attribute existed anywhere in this ancestry that `lang` attribute value overrode all attempts by the user to set the spell checking language for the document.

As of {productname} 6.3, the `lang` attribute inherits the default settings for the {productname} editor body. As a consequence, the editor no longer searches elements external to the editor body when searching for `lang` attributes.

For information on the **Spellchecker Pro** plugin, see: xref:introduction-to-tiny-spellchecker.adoc[Spellchecker Pro].

=== Spelling Autocorrect 1.0.1

The {productname} 6.3 release includes an accompanying release of the **Spelling Autocorrect** premium plugin.

**Spelling Autocorrect** 1.0.1 includes one fix:

==== Fixed format changes at the start of sentences when auto-capitalization was on

When **Spelling Autocorrect** was active and had Capitalization enabled (ie had `autocorrect_capitalize: true` set), any inline formatting applied at the beginning of a new sentence, after a full stop (period) but before the start of the word, would be lost when the word was auto-capitalized. Instead the format at the end of the previous sentence was incorrectly applied. 

This update to the **Spelling Autocorrect** premium plugin removed redundant ‘pre-text’ punctuation, before the word at the start of the sentence being capitalized, from start and replacement of text-pattern.

As a consequence, formatting is now retained when the word is capitalized, as expected.

[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.3 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.3 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].

[[improvements]]
== Improvements

{productname} 6.3 also includes the following improvements

=== The Text color and Background color menus now display a checkmark denoting the currently selected color.

Previously, the color swatches displayed when the Text color and Background color menus were opened gave no indication as to whether or not the Text color or Background color of the current selection was one of the colors displayed in these menus.

With this update, when the selected text’s current Text color or Background color matches one of the colors available from the appropriate color swatch menu, a check mark (the ✔️ character, also known as a tick) displays over that color.

=== Text color and Background color toolbar menus now pre-select the color for the selected text or insertion point position.

{productname} 6.3 included an improvement to the Text color or Background color menus that allows the user to identify the pre-populated color for the selected-text: a ✔️ character displayed over the color that matches the currently selected Text color or Background color.

In addition to this, in {productname} 6.3, `getCurrentColor` checks for the first found `backcolor` and `forecolor` color before the parent color, based on the current selection or insertion point position.

As a consequence, when either the Text color or Background color toolbar menus are opened, if the selected Text color or Background color matches one of the colors available from the appropriate color swatch menu, that color is pre-selected.


[[additions]]
== Additions

{productname} 6.3 also includes the following additions:

=== New expand functions added to tinymce.selection and tinymce.dom.RangeUtils which expand the selection around the nearest word.

{productname} 6.3 introduced two new API functions that allow a user to select a word from the insertion point location which applies a new expand feature.

This new `tinymce.selection` API function allows {productname} users and developers to expand the selection range to contain the entire word when the selection is collapsed within the word.

To support this new API function, {productname} 6.3 also introduced `tinymce.dom.RangeUtils`, which focuses on a new `expand` method range that expands around the entire word that the user selection was collapsed within by the `tinymce.selection` API function.

If, in the following example, a user places the insertion point between the first and second `m` in the word, `comment`, then clicks the _Add comment_ toolbar button, or selects _Insert > Add comment_ from the TinyMCE menu, or presses the _Add comment_ keyboard shortcut  (eg ⌘+⌥+M) — 

[source,html]
----
<p>
  <span class="mce-annotation tox-comment" 
  	data-mce-annotation-uid="mce-conversation_58585987121669010253247" 
	data-mce-annotation="tinycomments">Comment</span>
</p>
----

— {productname} 6.3 will automatically expand the selection to include the whole word, ‘Comment’.

=== New `color_map_foreground` and `color_map_background` options store custom colors selected using the Text color and Background color menus.

{productname} 6.3 has two new and separate color palettes — `color_map_foreground` and `color_map_background` — for custom Text colors and custom Background colors.

When custom colors are selected from the Text color or Background color menus, these colors are now stored in these separate color palettes, `color_map_foreground` and `color_map_background`, respectively.

When chosen, these custom colors are still added to the Text color and Background color menus. But they are now stored separately from the default color sets used by both menus.

NOTE: When a user adds a custom color to the `color_map_background` pallete, the editor does not replicate the new color in the `color_map_foreground` pallete.

=== Added optional storageKey property to `colorinput` component

{productname} 6.3 introduced two new color palettes for `color_map_background` and `color_map_foreground`.

This addition introduced changes to the `colorcache`: it is no longer considered a singleton. The `colorcache` can now be accessed with the help of a custom ID, which can now create custom `color_map` colors, selected by the user to be assigned to either the `backcolor` or `forecolor` pallets separately.

To accompany this, {productname} 6.3 now allows for the creation of a separate `storageKey` property for the pre-provided colors in `color_map_forground` and `color_map_background` respectively. `storageKey` properties can also be set fo `color_cols`, the `colorinput` component, and `colorswatch`.

NOTE: If no separate values are set for `color_map_forground` and `color_map_background`, they still default to the shared or previous values as before.


=== New addView function added to editor.ui.registry which makes it possible to register custom editor views.
=== New ToggleView command which makes it possible to hide or show registered custom views.

// https://ephocks.atlassian.net/browse/TINY-9210
// @bforte review required -- Feedback provided is to keep this minimal.
{productname} 6.3 now gives users the ability to register `custom` editor views with use of the new  `addView` API.



=== New color_default_foreground and color_default_background options to set the initial default color for the forecolor and backcolor toolbar buttons and menu items.

{productname} 6.3 adds a new feature that allows the default color for the `color_default_foreground` and `color_default_background` in the toolbar button menu to be pre-defined.

The `color_default_foreground` and `color_default_background` colors are pre-defined by including them in `tinymce.init`

In the example below, the foreground color is set to red and the background color is set to a shade of cyan.

As the example shows, these colors can be defined by either name or hex #.

[source,js]
----
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
	color_default_background: 'red',
	color_default_foreground: '#0DEDFF',
	toolbar: 'forecolor backcolor fontsize'
});
</script>
----


=== New getTransparentElements function added to tinymce.html.Schema to return a map object of transparent HTML elements.
=== Transparent elements, like anchors, are now allowed in the root of the editor body if they contain blocks.
=== Transparent elements, like anchors, can now contain block elements.
// https://ephocks.atlassian.net/browse/TINY-9172
// @bforte review required
In {productname} 6.3 block level links are now supported.


=== Added `ToggleToolbarDrawer` event to subscribe to toolbar’s opening and closing. 

{productname} 6.3 includes a new event, `ToggleToolbarDrawer`, to subscribe to the toolbar's opening and closing actions.

In previous versions of {productname}, when the `ToggleToolbarDrawer` command was set to `toolbar_mode: "sliding"` or `toolbar_mode: “floating”,` the `ToggleToolbarDrawer` did not create an opening or closing event.

With {productname} 6.3, the new `ToggleToolbarDrawer` event has been introduced. When the `ToggleToolbarDrawer` command is triggered, the new event initializes an `onToggle` callback that propagates the `OuterContainer` component for `SplitSlidingToolbar` and `SplitFloatingToolbar`.

Once the `OuterContainer` component event is triggered, the console records either a `true` or `false` action that calls on the `onToggled` callback which supports the `FloatingToolbarButton` and `SplitFloatingToolbar` components.


[[changes]]
== Changes

{productname} 6.3 also incorporates the following changes:

=== Keyboard navigation in the Text color and Background color  menus now starts on the currently selected color if that color is present.

In {productname} 6.3, `getCurrentColor` now checks for the first found `backcolor` and `forecolor` color before the parent color, based on the current selection or insertion point position.

As a consequence, when either the Text color or Background color toolbar menus are opened, if the selected Text color or Background color matches one of the colors available from the appropriate color swatch menu, that color is pre-selected and navigating through the available colors using arrow keys on the keyboard starts from this pre-selected color.

=== `setContent` is now allowed to accept any custom keys and values as a second options argument.

In {productname} 6.3, changes have been made to the `setContent` feature that now allows the editor to accept any custom `[key: string]: (value) any;` as a second option argument when the user inserts content.

The provides more flexibility with the `getContent` and `setContent` features.

New tests have been added to the `setContent` feature in {productname} 6.3 that now check if content manipulation in `BeforeSetContent` callback is possible so it can pass the custom data object to the `getContent` feature, allowing it to set both the content and action events.


[[bug-fixes]]
== Bug fixes

{productname} 6.3 also includes the following bug fixes:

=== Parsing media content would cause a memory leak, which for example occurred when using the getContent API.

A memory leak occurred in Chrome, Edge and Firefox browsers when media content was parsed into the editor using the `tinymce.activeEditor.getContent()` method API.

The memory leak caused an abnormal behavior that increased the memory requirements of the editor until the active tab in the browser crashed.

This memory leak has been reported as https://bugs.chromium.org/p/chromium/issues/detail?id=1374180[Memory leak with DOMParser parseFromString method] in the Chromium bug tracker.

A fix that prevents {productname} being effected by the leak has been included in {productname} 6.3.

=== Dragging a noneditable element toward the bottom edge would cause the page to scroll up.

A regression was found in {productname} 6.2 where dragging an element containing a `contentEditable=false` attribute towards a document’s edge did not cause scrolling.

It was also found that dragging elements containing a `contentEditable=false` attribute toward the bottom edge causes similar behaviour. In this instance, however, when the elements containing a `contentEditable=false` attribute was dragged to the bottom of the page the editor would sometimes scroll up.

This regression has been addressed in {productname} 6.3. Dragging elements containing a `contentEditable=false` attribute towards a document’s edge causes the viewport to scroll as expected. And dragging elements containing a `contentEditable=false` attribute toward the bottom edge of the editor no longer causes the page to scroll up.

=== Range expanding capabilities behaved inconsistently depending on where the insertion point was placed.

When the `ExpandRange.ts:expandRng()` function is given a range, it is expected to select a the next word whether the range begins before or after the word. Previously, however, this was discovered to not be the case.

As a result of the discovery, it was further discovered that the string `ExpandRange.ts:expandRng()` function, that checks the location of the user’s insertion point before and after, was affecting the for-loop in `walkText-implementation`.

Fixes were applied to the `tinymce.activeEditor.selection.expand()` function which is responsible for directly affecting the white space next to a word that accompanies a space-separated instance. 

In {productname} 6.3, the `ExpandRange.ts:expandRng()` function now behaves as intended with any element such as text, special character, styles or elements with `contenteditable="false”` attributes. Regardless of where the insertion point is placed, the function, when given a range, now selects the word as expected.

=== Compilation errors were thrown when using TypeScript 4.8.

{productname} 6.3 includes updates to the latest `rollup-plugin-dts` version to pull in a fix that was generating invalid generics. The update also allowed for a transition from typescript 4.7.4 to typescript 4.8.3, which, further, fixed compilation errors that were occurring.

=== Line separator scrolling in floating toolbars.

In {productname} 6.0.3 the background images in the floating toolbar followed the scroll position of any nested scrolling containers when the editor width was reduced by the browser. By default, however, the background images should scroll with the main scrollable element, `+<body>+`.

As a consequence, the divider lines that act as background image to improve the UI would not follow the scroll position of any nested containers inside the floating toolbar.

In {productname} 6.3 background images now scroll with the toolbar’s content as expected.

=== A double bottom border appeared on inline mode editor for the tinymce-5 skin.

The `inline-mode` toolbar showed an additional border line with {productname} 6.x premium skins that used {productname} 5.x skin packages.

With {productname} 6.3, all {productname} premium skins were updated and the additional border line no longer presents.


=== The editor header showed up even with no menubar and toolbar configured.

In classic mode, when both the {productname} toolbar and menubar were disabled, a header was still visible at the top of the editor. 

In {productname} 6.3 this header no longer presents when the {productname} toolbar and menubar are disabled, giving the editor a cleaner appearance with only the content editor visible.


=== Inline text pattern no longer triggers if it matches only the end but not the start.
=== Matches of inline text patterns that are similar are now managed correctly.

// https://ephocks.atlassian.net/browse/TINY-8947
// https://ephocks.atlassian.net/browse/TINY-8949
// @bforte review required 2x versions for suggestions (MERGED 8949 into this!)
Previously, to check if something matched a pattern, {productname} would first search for the end pattern and then check if the offset was long enough to be the start pattern.

For example, consider a pattern that has a start = `+**+` and an end = `+**+`. And a document that consists of the following string: `a *test**`.

{productname} would find the end — `**` — and would then look for the the offset between the two elements as length 2(` *`).

In this circumstance, {productname} returned a match because the search mechanism searched within the nodes. Using the previous mechanism a start pattern like `**` would match, for example, `*<span class="not-visible"></span>*`.

Example of what would happen when the issue would occur.

`a *test**` became `a<em>test</em>`

In {productname} 6.3 the mechanism now directly checks the text, and the text only, avoiding the errors caused by the previous mechanism.


Notes

The above edit still leaves me cold.

What does start = `**` mean?

Is `**` a string an end-user would enter, or a string an integrator would add to a configuration or other setup?

If we have examples, are they in a particular syntax? Should they be presented as AsciiDoc code-blocks for syntax highlighting and, consequently, easier parsing? For example (and making a blind guess as to the underlying syntax):

For example:

[source,grep]
----
a *test**
----

would become

[source,grep]
----
a<em>test</em>
----

Also, even re-presented like this, I’m unsure what _this_ becoming _that_ means?

// @bforte version 2 for the above.
Previously, to check if something matched a pattern, {productname} would first search for the end pattern and then check if the offset was long enough to be the start pattern.

For example, consider you want to wrap a specific `text-selection` with a font-style `bold`. In previous versions of {productname}, when applying a pattern to apply font-styling `bold` you would add text pattern `**` before_the_word and `**` after_the_word, such as this `example *bold*`.

{productname} would find the end `**` after_the_word and would then look for text pattern `**` before_the_word , but specifically for any offsets in between the two elements as length 2 (`**` equivilant to ` *` or `11` == `node_1,node2`).

In this circumstance, `example bold*` would return a match because the search mechanism would check for the available node spaces before_the_word and `**` after_the_word.

For example:

[source,grep]
----
example bold* // renders `examplebold `
----

[source,grep]
----
<p>example<strong>bold</strong>&nbsp;</p>
----
The example above detected `1` missing text pattern, but also `1` available node space which triggered the mechanism to remove the node space _after_the_last_word, while replacing the missing text pattern `⤴*` _before_the_word.

In {productname} 6.3 the mechanism now directly checks the text pattern before_the_word and _after_the_word only and apply the closest match based on the text patterns entered. Noted: If the user enter’s an incorrect text pattern that does not match both _before_the_word and after_the_word, the trailing text pattern will remain.

For example:

[source,grep]
----
example bold* // renders `example bold* 
----

[source,grep]
----
<p>example <em>bold</em>*&nbsp;</p>
----
// end



=== The context toolbar prevented the user from placing the cursor at the edges of the editor.

When scrolled past the top row of a table, the table _context toolbar_ overlapped any rows at the top of the editor to display below the toolbar.

In {productname} 5.x, the _context toolbar_ switched from being at the top of the editor, to the bottom of the table or editor when a user attempted to select cells close to the top row of the table. And vice versa when the _context toolbar_ was docked to the bottom of the editor.

In {productname} 6.x, the height of the _context toolbar_ was increased, while the distance from which it needed to be selected in order to switch locations was not.

With {productname} 6.3 this distance has been increased. This allows the _context toolbar_ to correctly switch locations when a user selects cells close to the toolbar, allowing the top or bottom visible rows of a table to be selected without issue when the _context toolbar_ is visible.


=== The Quick Insert context toolbar provided by the quickbars plugin showed when the cursor was in a fake block caret.

The Quick Insert context toolbar, provided by the xref:quickbars.adoc[Quick Toolbars] plugin, was displayed when the cursor was moved to the left of an element with a `contenteditable="false"` attribute.

This behavior was unexpected because the Quick Insert context toolbar should not present when the insertion point is placed on a line with content.

The root cause was the insertion point being placed into a fake block caret, which was not considered by the logic for toggling the Quick Insert context toolbar.

A fix was applied to the logic to ensure it could handle such cases, and prevent it from showing in this circumstance.


=== When running on Firefox, the editor.selection.getRng() API was not returning expected values on hidden editors

In contrast to other supported browsers, Firefox did not return the selected object or the selection range from iframes that are hidden by the `display: none` attribute.

As a consequence, when a {productname} instance was running on Firefox, the `window.getSelection()` API for an iframe returned `null` if the iframe was hidden. This, further, resulted in the `editor.selection.getRng()` and `editor.selection.getBookmark()` APIs returning incorrect data from hidden editors when Firefox was the host browser.

This has been fixed in {productname} 6.3. All browsers, including Firefox, now return the correct values even when the iframe is hidden.


=== Dragging a noneditable element before or after another noneditable element now works correctly.

Elements that had the `contenteditable="false"` attribute set could not be dragged to the left of an ancestor element.

For example in the following

[source,html]
----
<p>Text in a paragraph tag with a span of <span contenteditable="false">non-editable text</span> inside.</p>
----

the string _non-editable text_ could not be dragged to before the opening `+<p>+` tag.

{productname} 6.3 can place a fake insertion point next to elements with a `contenteditable="false"` attribute when another element with a `contenteditable="false"` attribute is dragged, allowing the object to be moved before and after other such elements.


=== The restored selection or location after a redo or undo action was not scrolled into view.

Prior to the {productname} 6.3 release, executing an undo or redo function in the editor did not scroll the editor to the new insertion point or selection, should the undo or redo result in the insertion point or selection being out of the current viewport.

Instead, users had to manually scroll to the insertion point or selection after issuing an undo or redo command that resulted in the insertion point or selection being out of view.

As of the {productname} 6.3 release, the scroll function now repositions the insertion point to the last known undo or redo location.


=== A newline could not be inserted after an inline element with a contenteditable="false" attribute was created.

In previous versions of {productname}, a newline could not be inserted when the selection was restored from a ‘bookmark’ positioning after adding an inline element with a `contenteditable="false"` attribute.

This was most commonly seen by pressing the *Return* (or *Enter*) key not moving the insertion point to a new line after a merge tag was created in the editor.

For {productname} 6.3, a fix was applied to the core `SelectionOverrides` settings to ensure the user selection restores from the ‘bookmark’ positioning before and after an inline element with a `contenteditable="false"` attribute is created.

Hitting the *Return* (or *Enter*) after creating a merge tag now moves the insertion point to a new line, as expected.


=== Inline mode did not respect the `content_css_cors` option.

In previous versions of {productname}, the `tinymce.styleSheetLoader` global was not configured by the `content_css_cors` option, when specified.

Consequently, stylesheets loaded by {productname} onto the outer document page did not have the `crossOrigin="anonymous"` attribute. This particularly effected {productname} instances running in inline mode, because the `tinymce.styleSheetLoader` global is used to load stylesheets used by inline editors. (Stylesheets for {productname} editors running in iframe mode are specific to the editor.)

Without the `crossOrigins="anonymous"` attribute being set, no external stylesheets were loaded. And inline editors with the `pageembed` plugin loaded and the `tiny_pageembed_inline_styles` option set to `true` would, as a result, return an error when attempting to insert any iframse through the dialog.

As of {productname} 6.3, the `content_css_cors` option now configures the `tinymce.dom.styleSheetLoader` global when specified. This allows the `crossOrigin="anonymous"` attribute to be added to all stylesheets loaded by the editor — including editors running in inline mode — when the attribute is set to true.

=== The insertion point moved to the previous line when a text pattern executed a `mceInsertContent` command on Firefox

In previous versions of {productname}, when running on Firefox and after pressing Enter or Return to execute an `mceInsertContent` command (to, for example, add a merge tag to a {productname} document), xref:content-behavior-options.adoc#text_patterns[text_patterns] moved the insertion point to the previous line.

This error has been corrected in {productname} 6.3. When running {productname} 6.3 on Firefox and creating a merge tag using `mceInsertContent`, pressing the Enter or Return to generate the desired merge tag moves the insertion point to the end of said newly-created merge tag, as expected.


[[security-fixes]]
== Security fixes

{productname} 6.3 includes fixes for the following security issues:

=== HTML in messages for the `WindowManager.alert` and `WindowManager.confirm` APIs was not properly sanitized.

Some calls to `DomFactory.fromHtml` were escaping the text being substituted into the HTML `string`, resulting in an isolated alert being displayed within the {productname} editor viewport. 

{productname} 6.3 introduced `dompurify` into the core dependencies to reduce the risks associated with XSS attacks.

In messages for the `WindowManager.alert` and `WindowManager.confirm` APIs now sanitise properly.


=== Cross-site scripting vulnerability in TinyMCE alerts

A cross-site scripting (XSS) vulnerability was discovered in the alert and confirm dialogs when these dialogs were provided with malicious HTML content. This can occur in plugins that use the alert or confirm dialogs, such as in the image plugin, which presents these dialogs when certain errors occur. The vulnerability allowed arbitrary JavaScript execution when an alert presented in the TinyMCE UI for the current user.

This vulnerability has been patched in this release by ensuring HTML sanitization is still performed after unwrapping invalid elements.

[[known-issues]]
== Known issues

This section describes issues that users of {productname} 6.3 may encounter and possible workarounds for these issues.

There are several known issues in {productname} 6.3.

=== The More button can disappear from the {productname} toolbar when exiting the inline code editor

When the More button in the {productname} toolbar is open (ie, is set to display all of a multi-line toolbar), opening and closing the xref:advcode.adoc[Advanced Code Editor] in inline mode can cause the More button to disappear.

Specifically, when {productname} 6.3 is running `advcode_inline: true` and `toolbar_mode: sliding` specifically the More button disappears after clicking on the _Cancel_ button in the xref:advcode.adoc[Advanced Code Editor] viewport.

This only occurs when the toolbar is forced into a viewport small enough to render the _More_ toolbar button inside the editor. As in the example below, which sets the viewport width to be less than the toolbar width.

[source,js]
----
tinymce.init({
    selector: "textarea", // change this value according to your HTML
	width: 400,
    plugins: [
        "advcode",
    ],
	advcode_inline: true,
	toolbar_mode: 'sliding',
    toolbar: " undo redo | styles | bold italic underline strikethrough | code "
});
----

A workaround does exist to resolve this issue: if the More button disappears, re-sizing the editor viewport forces it to re-display. Switching to Full Screen mode and back counts as re-sizing for this workaround’s purposes.


=== In Safari 16.1, the ‘Click for more info’ button in Accessibility Checker dialogs is not outlined when made active

*Accessibility Checker* dialogs for accessibility Errors and Warnings include a _Click for more info_ button: a coloured square containing a circled question mark.

When this button is navigated to using keyboard navigation, the button is highlighted and a blue outline appears around the highlighted button.

When Safari 16.1 is the host browser for a {productname} instance, the _Click for more info_ button highlights, but the blue outline does not present when this button is navigated to using keyboard navigation.

This is a presentation issue only. The _Click for more info_ button still works as a button in Safari 16.1, responding as expected when it is clicked or pressed, or when the Return key is pressed after navigating to the button using the Tab key.

There is, as of this release, no specific workaround.

NOTE: if the _Click for more info_ button is navigated to using the Tab key, and then the Return key is pressed to activate the button and load the more information page, the blue outline does appear in Safari 16.1 after the Return key is pressed.


=== Checkmark over the current color is not displayed when ‘Text color’ or ‘Background color’ is accessed from the {productname} menu

The *Text color* and *Background color* commands set the color of the selected text and the background behind the selected text respectively.

Depending on the {productname} configuration, these commands can be accessed from the *Format* menu or from the {productname} toolbar, or both.

And, when selected text or the background behind selected text is set to one of the colors available from the swatch presented by both commands, a checkbox appears over that color when these commands are selected and the swatch is opened.

As of {productname} 6.3, however, this checkmark does not appear if the *Text color* or *Background color* commands are opened via the *Format* menu. The checkmark does, however, appear when the equivalent toolbar button menus are opened.

This presentation issue does not affect functionality. Selecting a new *Text color* or *Background color*, either via the *Format* menu or the toolbar, changes the selected text color or the selected text’s background color, as expected.

A workaround is to display the {productname} toolbar with the *Text color* and *Background color* options and access these commands from the toolbar. The checkmark appears in the 


=== Checkmark over the current Background color is not displayed when inline formatting is applied in a certain order

If text in a {productname} document is formatted in the following order, the checkmark over the currently active background color does not display in the Background color swatch menu:

. Apply inline formatting, such as *Bold* or _Italic_.
. Apply a Text color
. Apply a Background color

This presentation issue does not affect functionality. Selecting an new *Background color*, either via the *Format* menu or the toolbar, changes the selected text’s background color, as expected.

A workaround is to apply inline formatting after applying the Text and Background color. When the inline formatting is applied after the Text and Background colors are applied, the presentation error does not occur.

NOTE: this checkmark presentation issue occurs in conjunction with the similar checkmark presentation issue documented above. When this presentation issue occurs, the checkmark does denote the current background color in either the *Background color* menu or toolbar item.

