= TinyMCE 6.4
:navtitle: TinyMCE 6.4
:description: Release notes for TinyMCE 6.4
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.4 was released for {enterpriseversion} and {cloudname} on Wednesday, March 15^th^, 2023. It includes {productname} 6.4, additional changes to Premium plugins, and a new Premium plugin, Advanced Template. These release notes provide an overview of the changes for {productname} 6.4:

* xref:new-premium-plugin[New Premium plugin]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvement[Improvement]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
// * xref:security-fixes[Security fixes] -- leave until closer to 2023-03-15 and remove or make visible as appropriate.
// * xref:known-issues[Known issues] -- leave until closer to 2023-03-15 and remove or make visible as appropriate.
// NB: edit the equivalent section of nav.adoc when the remove or make visible decision is made.

[[new-premium-plugin]]
== New Premium plugin

=== Advanced Template 1.0.0



[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.4.

=== Advanced Typography 1.0.1

The {productname} 6.4 release includes an accompanying release of the **Advanced Typography** premium plugin.

**Advanced Typography** 1.0.1 includes the following fixes, additions, and improvements.

=== Spaces after opening and before closing quotes are not added anymore in French

// https://ephocks.atlassian.net/browse/TINY-9434
// 1. Cause - What actions or circumstances cause this bug to present.
// 2. Consequence - What happens when the bug presents
// 3. Fix - What was done to fix the bug.
// 4. Result - What now happens when the actions or circumstances above occur.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== Fixed adding redundant space between a comma and a quote by switching the sequence of executing safe and unsafe rules

// https://ephocks.atlassian.net/browse/TINY-9442
// 1. Cause - What actions or circumstances cause this bug to present.
// 2. Consequence - What happens when the bug presents
// 3. Fix - What was done to fix the bug.
// 4. Result - What now happens when the actions or circumstances above occur.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== Added common/space/delBetweenExclamationMarks to remove spaces between exclamation marks

// https://ephocks.atlassian.net/browse/TINY-9398
// 1. Cause - What actions or circumstances cause this bug to present.
// 2. Consequence - What happens when the bug presents
// 3. Fix - What was done to fix the bug.
// 4. Result - What now happens when the actions or circumstances above occur.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== Added typography plugin to the default menubar

// https://ephocks.atlassian.net/browse/TINY-9450
// 1. Cause - What actions or circumstances cause this bug to present.
// 2. Consequence - What happens when the bug presents
// 3. Fix - What was done to fix the bug.
// 4. Result - What now happens when the actions or circumstances above occur.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== Typography button and menu item will be disabled if editor has no content

// https://ephocks.atlassian.net/browse/TINY-9441
// 1. Cause - What actions or circumstances cause this bug to present.
// 2. Consequence - What happens when the bug presents
// 3. Fix - What was done to fix the bug.
// 4. Result - What now happens when the actions or circumstances above occur.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

For information on the **Advanced Typography** plugin, see: xref:advanced-typography.adoc[Advanced Typography].

////
Be wary of the version number listed above.

To quote my [comment, left on the TinyMCE 6.4 BoM][0] in Notion:

> Given the five changes in the Unreleased section of the Advanced
> Typography plugin’s [changelog][1], is it sensible to assume this plugin
> is getting a version bump?

[0]: <https://notion.so/TinyMCE-6-4-Bill-of-materials-BOM-885a34e3b9884be0b69cd30eba7c618b?d=5267c02d507140c2882a18c2a9c7c753#0067a51f89bc45f1a99cc1b80a6e7a39>

[1]: <https://github.com/tinymce/typography/blob/main/CHANGELOG.md>
////



=== Checklist 2.0.3

The {productname} 6.4 release includes an accompanying release of the **Checklist** premium plugin.

**Checklist** 2.0.3 includes the following fix

////
To quote my [comment, left on the TinyMCE 6.4 BoM][2] in Notion

> What changes were made to the Checklist plugin? The [changelog][3]
> contains no entries beyond 2022-11-23 and the only [commits this
> year][4] have been dependabot bumps or back-end changes.

[2]: <https://notion.so/TinyMCE-6-4-Bill-of-materials-BOM-885a34e3b9884be0b69cd30eba7c618b?d=a1149ea94c2e459b80773fa2e59a6cc6#e826f887f0654bafb3ec0fdcb1659385>

[3]: <https://github.com/tinymce/santa/blob/main/CHANGELOG.md>

[4]: <https://github.com/tinymce/santa/commits/main>
////

For information on the **Checklist** plugin, see: xref:checklist.adoc[Checklist].



=== Merge Tags 1.2.0

The {productname} 6.4 release includes an accompanying release of the **Merge Tags** premium plugin.

**Merge Tags** 1.2.0 includes the following change.

==== The mceMergeTag command now preserves the selected content as a plain text and wraps it in a merge tag prefix and suffix if the content length exceeds the limit.

// https://ephocks.atlassian.net/browse/TINY-9444
// 1. Cause - What actions or circumstances cause this bug to present.
// 2. Consequence - What happens when the bug presents
// 3. Fix - What was done to fix the bug.
// 4. Result - What now happens when the actions or circumstances above occur.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

For information on the **Merge Tags** plugin, see: xref:mergetags.adoc[Merge Tags].


=== PowerPaste 6.1.3

The {productname} 6.4 release includes an accompanying release of the **PowerPaste** premium plugin.

**PowerPaste** 6.1.3 includes the following fixes, additions, and improvements.

////
To quote my [comment, left on the TinyMCE 6.4 BoM][5] in Notion

> What changes were made to the Checklist plugin? The [changelog][6]
> contains no entries beyond 2022-11-23 and the only [commits this
> year][7] have been dependabot bumps or back-end changes.

[5]: <https://www.notion.so/TinyMCE-6-4-Bill-of-materials-BOM-885a34e3b9884be0b69cd30eba7c618b?d=32ea41e705fb460c99f63ad7c1ef6043#3531017a765f43868ca2cadf7133ef1b>

[6]: <https://github.com/tinymce/powerpaste2/blob/main/CHANGELOG.md>

[7]: <https://github.com/tinymce/powerpaste2/commits/main>
////


For information on the **PowerPaste** plugin, see: xref:introduction-to-powerpaste.adoc[PowerPaste].


=== Comments 3.3.0

The {productname} 6.4 release includes an accompanying release of the **Comments** premium plugin.

**Comments** 3.3.0 includes the following fix.

==== The comment input box now has a max height to prevent long comments from expanding the box indefinitely

// https://ephocks.atlassian.net/browse/TINY-8894
// 1. Cause - What actions or circumstances cause this bug to present.
// 2. Consequence - What happens when the bug presents
// 3. Fix - What was done to fix the bug.
// 4. Result - What now happens when the actions or circumstances above occur.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

For information on the **Comments** plugin, see: xref:introduction-to-tiny-comments.adoc[Introduction to Tiny Comments].


=== Enhanced Media Embed 3.0.5

The {productname} 6.4 release includes an accompanying release of the **Enhanced Media Embed** premium plugin.

**Enhanced Media Embed** 3.0.5 includes the following fixes, additions, and improvements.

////
To quote my [comment, left on the TinyMCE 6.4 BoM][8] in Notion

> What changes were made to the Enhanced Media Embed plugin? The
> [changelog][9] contains no entries beyond 2022-09-08 and the only [commits
> this year][10] have been dependabot bumps or back-end changes.

[8]: <https://notion.so/TinyMCE-6-4-Bill-of-materials-BOM-885a34e3b9884be0b69cd30eba7c618b?d=1c6d570eebbf4a8697d959425fa02808#476b7ddffb464f6c8ffbe9e98db4af84>

[9]: <https://github.com/tinymce/pillow/blob/main/CHANGELOG.md>

[10]: <https://github.com/tinymce/pillow/commits/main>
////


For information on the **Enhanced Media Embed** plugin, see: xref:introduction-to-mediaembed.adoc[Introduction to Enhanced Media Embed].


=== Spell Checker Pro 3.2.0

The {productname} 6.4 release includes an accompanying release of the **Spell Checker Pro** premium plugin.

**Spell Checker Pro** 3.2.0 includes the following fixes, additions, and improvements.

////
To quote my [comment, left on the TinyMCE 6.4 BoM][11] in Notion

> What changes were made to the Enhanced Media Embed plugin? The
> [changelog][12] contains no entries beyond 2022-09-08 and the only [commits
> this year][13] have been dependabot bumps or back-end changes.

[11]: <https://notion.so/TinyMCE-6-4-Bill-of-materials-BOM-885a34e3b9884be0b69cd30eba7c618b?d=40e8ab59323f4319bfbb83898a3fe18c#0c32239916564963850ca08c2ab4f112>

[12]: <https://github.com/tinymce/powerspell/blob/main/CHANGELOG.md>

[13]: <https://github.com/tinymce/powerspell/commits/main>
////


For information on the **Spell Checker Pro** plugin, see: xref:introduction-to-tiny-spellchecker.adoc[INtroduction to Spell Checker Pro].



[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.4 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.4 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvement]]
== Improvement

{productname} 6.4 also includes the following improvement:

=== Direct invalid child text nodes of list elements will be wrapped in list item elements.
// @bforte @KKS waiting on TINY-9589 to be merged for confirmation of adding this.
// https://ephocks.atlassian.net/browse/TINY-4818

Invalid child nodes were throwing a `Uncaught TypeError:` when `<ol>` tags directly included a text node. This `TypeError` would not allow the user to `Tab` a text node while nested within `<ol>/<li>` HTML tags.

Improvements were made to add a content filter for lists within {productname} 6.4. This improvement meant that any _invalid child nodes_ nested within `<li>` elements would be wrapped with this filter to avoid the `Uncaught TypeError:`.

In {productname} 6.4, direct _invalid child text nodes_ of list elements are now wrapped in list item elements, which allow the user to now `Tab` nested text nodes that are within `<ol>/<li>` tags.
// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== Opening the toolbar drawer steals focus even if skip_focus is set.
// @bforte @KKS waiting on TINY-9589 to be merged for confirmation of adding this.
//https://ephocks.atlassian.net/browse/TINY-9337		

A focusing event that was in the initial *FloatingToolbarButton* config, in previous versions of {productname} in (2019) was causing `focus` issues with the *ToggleToolbarDrawer*. As a consequence, this meant that while the editor was been scrolled into `focus`(viewport position), and the *ToggleToolbarDrawer* command `skipFocus: boolean` was set, the toolbar draw could still take `focus` when It was not meant to.

In {productname} 6.4, a improvement was made to the focusing `event` which is now removed after toggling the toolbar.

As a result to the fix, while the *FloatingToolbarButton* `focus` is initiated, the toolbar now focuses correctly without stealing `focus` when `skipFocus: 'boolean' is set.

=== Add Typography to the default menubar config
// @bforte @KKS waiting on TINY-9589 to be merged for confirmation of adding this.
//https://ephocks.atlassian.net/browse/TINY-9450		

In previous versions of {productname}, the typography button would *not* appear in the `menubar` by default. As a consequence, the user could only `find` the typography button in the `toolbar` due to it not appearing in the `menubar` dropdown.

To correct this bug, the typography plugin was added to the default `menubar` config.

{productname} 6.4, by default, will now display the typography button in both the `toolbar` and below the “Source code" button in the `menubar`.

=== Fix removing spaces between exclamation marks ! !
// @bforte @KKS waiting on TINY-9589 to be merged for confirmation of adding this.
//https://ephocks.atlassian.net/browse/TINY-9398		

A issue was discovered that affected the typography plugin in previous versions of {productname} that was associated with inserting content into the editor, but specifically *exclamation marks* and the spaces between them. Such as: `“Hello! !“`. This issue meant that the editor would not remove the spaces between the double *exclamation marks* `! <space>!` after the typography plugin `toolbar` or `menubar` button was executed.

The fix for this involved adding a new rule which removes the spaces between exclamation marks when the typography button is pressed.

In {productname} 6.4, spaces are now removed between exclamation marks `!!` for formatted HTML documents when the typography plugin is used. Read more about xref:advanced-typography.adoc[Advanced Typography] and how you can add this new premium plugin to your project.

[[additions]]
== Additions

{productname} 6.4 also includes the following additions:

=== renderUI property in the Theme type can now return a Promise <RenderResult> instead of RenderResult

// https://ephocks.atlassian.net/browse/TINY-9556
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== New isEditable API to editor.selection that returns true or false if the current selection is editable

// https://ephocks.atlassian.net/browse/TINY-9462
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== New isEditable API to editor.dom that returns true or false if the specified node is editable

// https://ephocks.atlassian.net/browse/TINY-9462
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== New setText and setIcon methods added to menu button and toolbar button apis

// https://ephocks.atlassian.net/browse/TINY-9268
Previous versions of {productname}, the menu button APIs did not behave as expected with the parent `icon` or `text` selection. As a consequence, the menu button API, would not extend or update the parent `icon` or `text` directly, based upon what `icon` or `text` the user had selected within the menubar.

In {productname} 6.4, two new additions were added to the menu button API.

. Added `setText` and `setIcon` properties to both the toolbar button `api`, and menu button `api`.
. Provided the menu button `api` property as an *argument* which will fetch a function that will allow menu items to change the `icon` or `text` of the parent menu button.

As a result, in {productname} 6.4, menu items can chance based on the parent menu button `api` properties.

=== New highlight_on_focus option which enables highlighting the content area on focus

// https://ephocks.atlassian.net/browse/TINY-9277
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== New fontsizeinput toolbar item which allows the user to set the size via input and also increase and decrease it with + and - buttons

// https://ephocks.atlassian.net/browse/TINY-9429
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480


[[changes]]
== Changes

{productname} 6.4 also incorporates the following changes:

=== The link plugins context menu items will no longer appear for noneditable links

// https://ephocks.atlassian.net/browse/TINY-9491
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== The formatting of contenteditable="false" elements are no longer cloned to new cells while creating new table rows

// https://ephocks.atlassian.net/browse/TINY-9449
Previous versions of {productname}, contenteditable="false" elements such as a *merge tags* could clone the styling to a new table row. In some situations, this cloning would happen during the creation of new table row, where the merge tag prefix would unexpectedly clone the formatting from the previous cell to the new cell.

To correct this issue, {productname} added changes to the *clone logic*, and the cursor position API, which will now return `true`, for any passed `contenteditable=false` elements.

In {productname} 6.4, the formatting of `contenteditable="false"` elements are no longer cloned to new cells while creating new table rows.

=== Changed the color of @dialog-table-border-color, and added right padding to the first cell of dialog table

// https://ephocks.atlassian.net/browse/TINY-9380
An area for improvement was identified during an accessibility audit for the *help menu* within {productname}, which focuses on users that rely on `zoom` orient to help with visibility.

The consequence of the previous UX, meant that adjustments needed to be made to the horizontal lines within the *help menu* table, that seperate each `row`.

To fix this accessibility issue, {productname} 6.4, increased the contrast ratio to `3:1` to each line divider, and changed the `line` color to `#646D78` to further help define were the separations occur in the table.

As a result, the `help menu` is now styled to support a wider range of users, by these new changes implemented.


[[bug-fixes]]
== Bug fixes

{productname} 6.4 also includes the following bug fixes:

=== Sometimes the editor would finish initializing before the silver theme would have finished loading
// Waiting for QA_Verified
// https://ephocks.atlassian.net/browse/TINY-9556
In earlier versions of {productname}, the properties set for the `renderUI`, caused conflicting issues with the theme rendering load times. As a consequence, the `renderUI` would finish rendering before the {productname} theme `silver` would finish load.

To fix this bug, {productname}, made changes to the `renderUI` properties that allowed the theme type the to return a `Promise<RenderResult>` instead of `RenderResult`, which corrects the issues found previously. 

In {productname} 6.4, all `renderUI` property loading issues have been resolved.

=== The searchreplace modal would close incorrectly when clicking outside of the alert that pops up when no match is found

// https://ephocks.atlassian.net/browse/TINY-9443
In previous versions of {productname}, the searchreplace modal would close incorrectly when clicking outside of the alert dialog. The expexted behaviour in previous versions was that an error dialog would open when **no <string> match** was found within the {productname} editor viewport. The identifying issue found was when the user would `click` outside of the error dialog, resulting in the `Find and Replace` modal to closes incorrectly.

In {productname} 6.4, when a **no <string> match** occurs within the {productname} editor viewport, an error banner will render in the `Find and Replace` modal beneith the (Replace with) field.

As a result the when the instance occurs where **no <string> match** is triggered, the user will be prompted with the following warning: *`Could not find the specified string`*.

=== Color picker on toolbar would not update when changing forecolor or backcolor from menu

// https://ephocks.atlassian.net/browse/TINY-9439
In {productname} 6.3, when the https://www.tiny.cloud/docs/tinymce/6/6.3-release-notes/#new-color_map_foreground-and-color_map_background-options-store-custom-colors-selected-using-the-text-color-and-background-color-menus[new color map] was introduced, a regression was found that affected the UI for *Color Swatch*.

A regression was found, that meant the colors would not render inside the color palette to reflect the selected `color_map_foreground` and `color_map_background` stored. To correct this {productname}, added a register that would store the `last color` for each  specific `node | cell` that will hold this `value` for the color picker pallette.

In {productname} 6.4, when the color picker in the `toolbar` is updated when changing either the `forecolor` or `backcolor` from the `menubar`.

=== The onSetup api function would not run when defining custom group toolbar button

// https://ephocks.atlassian.net/browse/TINY-9496
A bug was discovered that affected the custom group toolbar button `config` in {productname}, due to a missing `Event Behaviour`. As a consequence, the `onSetup` api function would not run as intended when defining a custom group toolbar `button`, resulting in the `console` returning `blank`.

In {productname} 6.4, this bug was fixed by adding a `Event Behaviour` to the toolbar group button that now calls the `api` as intended.

As a result, the `onSetup` function for custom group toolbar buttons now runs correctly in {productname} 6.4.

// https://ephocks.atlassian.net/browse/TINY-9364
In {productname} 6.0, the drag and drop `config` did not check some conditions surrounding element placements using either a grag or drop action.  This affected users running {productname} 6.0, which would affectivly allow decendants of *noneditable elements* to be dropped into another *noneditable element*.

Fixes were made to ensure that `dragging | dropping` onto *noneditable element* targets on all browsers is `disabled`. This also includes when the drop target cursor is inside the contenteditable element, or just before it.

In {productname} 6.4, now prevents the user from having the ability to drag and drop any descendants of a `contenteditable=false element` within another *noneditable element*.

=== Checkmark did not show in menu colorswatches

// https://ephocks.atlassian.net/browse/TINY-9395
Previous versions of {productname} the known issue, (_https://www.tiny.cloud/docs/tinymce/6/6.3-release-notes/#checkmark-over-the-current-background-color-is-not-displayed-when-inline-formatting-is-applied-in-a-certain-order[checkmark-over-the-current-background-color-is-not-displayed-when-inline-formatting-is-applied-in-a-certain-order]_) was identifed. As a consequence, when text was formatted in the following order, the *checkmark* over the currently active background color would not display in the Background color swatch menu:

. When the user appled inline formatting, such as *bold* or _Italic_.
. After applying a forground(text) color.
. After applying a background color.

To fix this bug, {productname} introduced a new variable to store the node `selection` and `color` format value, which then renders a checkmark to appear in both the toolbar and menubar for both the `forecolor` and `background` color.

As a result, in {productname} 6.4, checkmarks now work as expected when using the color swatch in both the toolbar and menubar.

=== Toolbar split buttons in advlist plugin to show the correct state when the cursor is in a checklist

// https://ephocks.atlassian.net/browse/TINY-5167
In previous versions of {productname}, when a cursor was placed within a checklist item, the icon for both the checklist and the bullet list would show as `active`. This created UX issues, as having both buttons showing a `active` state was confusing for the user, specifically for navigation purposes when using checklists from the `advlist` plugin.

To fix this issue, {productname} added improvements to the list configuration to checks a new set of conditionals which would determine if the `node` selected matched the parent `node` within the checklist. If the match returns as `true`, the (api) will set only the checklist icon to a `active` state.

As a result, the checklist `icon` in {productname} 6.4, related to the `advlist` plugin will only appear in a `active` state, when the `node` checklist meets the new conditions implemented.

=== Dragging transparent elements into transparent blocks elements could produce invalid nesting of transparents

// https://ephocks.atlassian.net/browse/TINY-9231
Dragging or dropping block `links` into other `links` was producing invalid nesting of other transparents such as `anchors`. As a result, these transparent elements would produce `anchor` tags within other `anchor` tags, which is not a general practice. As an example `links` and `anchors` that are defined to an element, must not be nested within or contain any other element and vice versa.

Changes were implemented in {productname} 6.4 to fix this issue to ensure that any invalid child anchor elements that try to reproduce this action are unwrapped when the editor verifies another transparent has been dropped into another transparent (anchor) element.

In {productname} 6.4, dragging content such as `links` into other `links` will now produce *valid* HTML `output` after a drag operation occurs which will be consistent across all browsers.

=== The editor.insertContent API would insert contents inside noneditable elements if the selection was inside the element

// https://ephocks.atlassian.net/browse/TINY-9462
In previous versions of {productname}, the settings for the `contentEditable` property in the editor root was set to `false`. As a consequence, the user could insert content using `api` commands to edit a `noneditable` root element.

To fix this bug, in {productname} 6.4, a blocker was added to the `editor.insertContent` api and `mceInsertContent` command, which stops `noneditable` root element from being edited.

In {productname} 6.4, inserting contents inside a `noneditable` element while the selection is inside another element, is no longer possible.

=== Closing a dialog would scroll down the document in Safari

// https://ephocks.atlassian.net/browse/TINY-9148
While using previous versions of {productname}, `clicking` away to dismiss the *Search* and *Replace* dialog within Safari would scroll the page to the bottom of the editor. As a result the user would have to manually scroll back to the original `focus` area each time the steps above were executed.

To correct this issue, a new Css.set was implemented to keep the `focus` on the DOM container in the initial scroll document position. 

In {productname} 6.4, when the user `clicks` away to dismiss the *Search* and *Replace* dialog within Safari, the focus now returns to the editor and the scroll does not change position within the editor.

=== Quick toolbars were incorrectly rendered during the dragging of contenteditable="false" elements

// https://ephocks.atlassian.net/browse/TINY-9305
The quickbar was displaying incorrectly during a drag and drop `action` for contenteditable="false" elements. As a consequence, during the movement of contenteditable="false" element, the selection was updated, which triggered a *NodeChange*. This selection update would cause an absence of the caret location during a dragging or dropping event.

To fix this bug, {productname} 6.4 added a new check to identify when the user is dragging a contenteditable="false" element, which blocks the quickbar from rendering.

As a result, the quickbar no longer opens in {productname} 6.4, when the user is dragging a contenteditable="false" element.

=== Selection of images, hrs, tables or noneditable elements was possible if they were within a noneditable element

// https://ephocks.atlassian.net/browse/TINY-9473
In previous versions of {productname}, elements that were nested within another `noneditable` element such as a element set with a `contenteditable="false"` attribute, was avoiding the `noneditables` guidelines set. As a consequence, selection of images, hrs, tables or noneditable elements was possible if they were nested within a noneditable element.

Improvements were made to the `SelectionOverride` to now check if the DOM parent node is either set as an `editable` or `noneditable` element.

In {productname} 6.4, elements with contenteditable="false" attributes can no longer be selected when they are children of another contenteditable="false" attribute, such as:

.Example of `noneditables`
[source,HTML]
----
<div contenteditable="false">noneditables div text</div>
<div>editable div text</div>
----

=== Ranged deletion of formatted text using selection or keyboard shortcut would sometimes cause Blink and Webkit browsers to insert interpreted tags upon typing, which may result in inconsistent tags

// https://ephocks.atlassian.net/browse/TINY-9302
Blink & Webkit browsers (Chrome & Safari) were deleting the contents of inline formats which would cause the format to be lost and not retained. As a consequence, this issue would impact the semantics and visuals for the *HTML* document, which is not be visible to the user.

A override fix already exists for _character-by-character_ deletion using backspace/delete keys with a collapsed selection. However, this particular bug persists when the format is deleted when there is a ranged selection that starts at the beginning of the inline format(s) and encompasses at least the entirety of the inline format(s). The bug also occurs when deletion is done using common keyboard shortcuts including `Ctrl/Alt + Backspace`, `Ctrl/Alt + Delete`, and `Cmd + Backspace`.

In {productname} 6.4, two new key overrides have been added to:

. Check that a `non-collapsed` selection satisfies the conditions set (specifically for a ranged selection using `backspace/delete`).
. Check a range of conditions *before* continuing (for keyboard shortcut `backspace/delete`).

As a result, the ranged selection for backspace/delete now check that all of the original formats at the cursor selection *start*, before deletion, are retained with either the native browser behaviour or a caret. For keyboard shortcuts that are using backspace/delete, will create a new unformatted caret which prevents browsers from inserting interpolated formats.

=== Visual characters were rendered inside noneditable elements

// https://ephocks.atlassian.net/browse/TINY-9474
In previous versions of {productname}, a bug was found that affected the `visual characters` plugin. As a consequence, the visual characters selecter would render inside `noneditable` elements after the plugin was applied to the editor.

To fix this issue, a conditional filter was added which identifies, if an element is either `editable` or `noneditable` to its decendants.  If the element matches `noneditable` to itself or decendants, the `visual character` plugin will remove the highlighted selecter from within the `dom` viewport.

As a result, in {productname} 6.4, visual characters no longer render inside `noneditable` elements.

=== Lists in a noneditable root were incorrectly editable using list API commands, toolbar buttons and menu items

// https://ephocks.atlassian.net/browse/TINY-9458
In previous versions of {productname}, a bug was found that affected the `lists` and `advlist` plugins when the {productname} editor body was set to `contentEditable = 'false'`. The consequence meant that `lists` that were *noneditable* could be *edited* using list API commands, toolbar buttons and menu items.

The fix involved implementing a new process to  check the element conditions.  The check now looks to  identify if the `lists` or `advlists` in the DOM are set to be either `contentEditable = 'false'` or `contentEditable = 'true'.

As a result, in {productname} 6.4, `lists` and `advlist` plugins that are set as `contentEditable = 'false'` elements will no longer be *editable* using list API commands, toolbar buttons and menu items.

=== Color picker dialog would not update the preview color if the hex input value was prefixed with # symbol

// https://ephocks.atlassian.net/browse/TINY-9457
In previous versions of {productname}, the preview sample box within the color picker dialod would not render. This issue could be replicated when a hex `value` was prefixed with a `#` symbol before the hex `value`.

Example of a `incorrect` vs `correct` value input:

* *`#BDE123`*: Incorrect hex value input.
* *`BDE123`*: Correct hex value input.

In order to fix this bug, {productname} 6.4, not detects if the user inserts a `#` symbol before the hex `value`, which removes the leading `#` prefix before rendering to the color picker component.

In {productname} 6.4, the color picker works as expected when using hex `values`.

=== Table cell selection was possible even if the element was in a noneditable root element

// https://ephocks.atlassian.net/browse/TINY-9459
Previous versions of {productname}, table cells set with the `noneditable` properties could still be modified. This was because the `contentEditable` property settings were set to `false` in the root. This meant that any table UI actions, commands or table selections could still affect any tables that were within that specific `noneditable` root.

{productname} 6.4, introduced a blocker that is executed when tables are inside a `noneditable` root.

In {productname} 6.4, all table UI actions, commands and selections have been `disabled` for tables when either the table or the editor body have been set as `noneditable` elements.

=== Table commands were modifying tables in a noneditable root element
// ONHOLD waiting for final implementation
// https://ephocks.atlassian.net/browse/TINY-9459
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== Fake carets were rendered for noneditable elements and tables in a noneditable root element
// ONHOLD waiting for final implementation
// https://ephocks.atlassian.net/browse/TINY-9459
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== Textareas with scrollbars in dialogs would not render rounded corners correctly on some browsers

// https://ephocks.atlassian.net/browse/TINY-9331
//1. Cause - What actions or circumstances cause this bug to present.

//2. Consequence - What happens when the bug presents.

//3. Fix - What was done to fix the bug.

//4. Result - What now happens when the actions or circumstances above occur.

// https://notion.so/tinycloud/Four-words-to-live-by-96e307110aaa4137b94f9ba12874d480

=== It was possible to open links inside the editor if the editor root was noneditable

// https://ephocks.atlassian.net/browse/TINY-9470
Setting the `contentEditable` property to the editor root to `false` such as the below example, would result in `noneditable` elements like `links` could be navigable.

[source, js]
----
setup: (editor) => {
    editor.on('preinit', () => {
        editor.getBody().contentEditable = false;
    })
}
----

As a result, links could be opened within the `iframe` element.

In {productname} 6.4, links can no longer be navigable by clicking on them while they are inside a `noneditable` root, after a blocker was implemented to avoid this event `action`.

{productname} 6.4, all links in a `noneditable` behave as expected.

=== Inline boundary was rendered for noneditable inline boundary elements

// https://ephocks.atlassian.net/browse/TINY-9471
Inline boundaries for noneditable elements were rendering styling in previous versions of {productname} 6.4 after the user `selected` before and after the noneditable elements node. The expected behaviour is that noneditable elements should *not* have inline boundaries when a caret is inside an noneditable anchor or root.

Added a predicate check for inline boundaries before they render, and additional tests for `selections` for some special cases surrounding particular noneditable elements.

In {productname} 6.4, it is now not possible to highlight inline boundary elements that are classified as a `noneditable` content element.

=== Clicking on a disabled split button will no longer call the onAction callback

// https://ephocks.atlassian.net/browse/TINY-9504
A bug was found in versions of {productname} prior to the 6.4 release, that would call the `onAction` callback for *split buttons* regardless of the action being `disabled`. This meant it was possible for the user to emit the `onAction` call wether or not the `disable` function was enabled or not.

As a fix to the issue, {productname} 6.4 introduced a new conditional check to identify *if* the button is `enabled` or `disabled`. If the button is set to `enabled` then {productname} executes the secondary check, which will identify wether or not the button is a *split button*.  Split buttons are classified as “special buttons”,  as they are unique and require both `advlists` and `dropdowns` to function, this makes them more complex than traditional buttons.

In {productname} 6.4, clicking on a disabled split button won't call the `onAction` callback anymore.

=== The "Edit Link" dialog incorrectly retrieved the URL value when opened immediately after the link insertion

// https://ephocks.atlassian.net/browse/TINY-7993
A bug was found within the context menu and dialog when inserting `links` in previous versions of {productname}. The issue resulted in the `open link` being deactivated within the context menu and dialog when the user would execute a specific chain of clicks. Such as:

.Example
====
. Opening the editor
. Type “test1 test2 test3” into the editor
. Double click to select “test2”
. Use the context menu to insert a new link over the text “test2”
. Add a valid URL
. Press `Enter`
. Without taking any other action, right click on “test2”

In this example the bug would deactivate the `open link` button within the context menu and dialog, which removes the users ability to reopen the “open link” dialog.
====

The fix now allows all 3 link-plugins to work within the context menu items.

In {productname} 6.4, when the user executes right `mouse click` on the link selection immediately after attaching a link to a `<string>`, the link-plugins now work as expected.

=== Creating a list in a table cell when the caret is in front of an anchor element would not properly include the anchor in the list.
// @bforte @KKS waiting on TINY-9589 to be merged for confirmation of adding this.	
//https://ephocks.atlassian.net/browse/TINY-6853
In previous versions of {productname}, a bug was causing issues with `links` while they were nested within table-cells. As a consequence, it was found that when creating a `num-list` or `bullet-list` to the left (node) of a `link` that was nested within a table cell the `list` would *not* include the created `link` within the `num or bullet-list` as expected. 

To fix this bug, the table cell now checks *If* the caret position is in front of an *anchor element*, `if` (true), then the table cell will include the anchor in the `list`.

In {productname} 6.4, anchor elements are included inside `lists` while nested within table cells.

=== Fixed the space between a comma and a quote in typography.
// @bforte @KKS waiting on TINY-9589 to be merged for confirmation of adding this.
//https://ephocks.atlassian.net/browse/TINY-9442
After {productname} introduced the `Smart Typography` plugin, a bug was discovered that was causing a `space` to be introduced between a `comma` and a closing `double-quote` mark. Such as in the below example.

.Example
> “They went that way,[space introduced here] ” he said as he pointed.

As displayed in the above example, a unintentional/redundant `space` was inserted into a seperate node position without intention.

{productname} fixed the issue by switching the sequence of executing `safe` and `unsafe` rules surrounding *Typography*.

In {productname} 6.4, the `Smart Typography` plugin, no longer creates a `space` between a `comma` and a closing `double-quote` mark.

////

// No security issues as of 2023-02-09
//
// Leave this comment block in place until closer to 2023-03-15 and remove or make visible as appropriate.

[[security-fixes]]
== Security fixes

{productname} 6.4 includes a fix for the following security issue:

No security issues as of 2023-02-09

Leave this comment block in place until closer to 2023-03-15 and remove or make visible as appropriate.

////


////

// No known issues as of 2023-02-09
//
// Leave this comment block in place until closer to 2023-03-15 and remove or make visible as appropriate.

[[known-issues]]
== Known issues

This section describes issues that users of {productname} 6.4 may encounter and possible workarounds for these issues.

There are several known issues in {productname} 6.4.

=== known issue 1



=== known issue 2



=== known issue 3



=== known issue 4



=== known issue 5



////