= TinyMCE 6.4.2
:navtitle: TinyMCE 6.4.2
:description: Release notes for TinyMCE 6.4.2
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} 6.4.2 was released for {enterpriseversion} and {cloudname} on Wednesday, May 3^rd^, 2023. These release notes provide an overview of the changes for {productname} 6.4.2:

* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:bug-fixes[Bug fixes]


[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.4.2 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.4.2 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.4.2.

=== TinyMCE Comments 3.3.2

The {productname} 6.4.2 release includes an accompanying release of the **TinyMCE Comments** premium plugin.

**TinyMCE Comments** 3.3.2 includes the following bug fix:

==== The ‘Comments > Delete all conversations’ menu item was enabled even when no comments were added

In previous versions of {productname}, when the Premium plugin, xref:introduction-to-tiny-comments.adoc[Tiny Comments] was also running, {productname} did not check the state of the comments section.

Consequently, the _Comments > Delete all conversations_ menu item was not disabled even when the comments section was empty.

With this update, when xref:introduction-to-tiny-comments.adoc[Tiny Comments] is running, {productname} checks the comments section state and this menu item is, as expected, disabled when the {productname} comments section contains no comments.

For information on the **Comments** plugin, see: xref:introduction-to-tiny-comments.adoc[Comments plugin].

[[bug-fixes]]
== Bug fixes

{productname} 6.4.2 includes the following bug fixes:

=== The `quickimage` toolbar button failed to insert images selected from the local computer when running on Google Chrome for macOS

A regression was discovered in {productname} 6.4.0 when the macOS version of Google Chrome was the host browser: the `focusin` editor event occurred before the `change` event for a file input.

As a consequence, although selecting the `quickimage` toolbar button presented the macOS-native *NSOpenPanel* dialogue box as expected, images selected from this dialogue box were not inserted into the {productname} document.

For this update, the regression has been corrected. In {productname} 6.4.2, local images selected after the `quickimage` button is selected are added to the {productname} document, as expected.

=== When hovering over tree dialog components the mouse pointer rendered incorrectly

In previous versions of {productname}, when hovering over tree dialog component items, the mouse pointer style rendered incorrectly.

Specifically, the mouse pointer rendered as an I-beam pointer rather than the default arrow pointer.

In {productname} 6.4.2, the styles for tree component items have been updated to correct this issue.

NOTE: as of {productname} 6.4.2, tree components are only used as part of the xref:advanced-templates.adoc[Advanced Templates] Premium plugin.

=== The editor displayed a notification error when it failed to retrieve a blob image uri

In previous versions of {productname}, when the editor contained an image with an invalid or unreachable blob url, it displayed an error notification banner within the editor viewport which impacted the user experience.

For {productname} 6.4.2 the error notification banner has been removed: the visible broken image icon is notification enough for the end-user.

=== Setting an invalid unit in the `fontsizeinput` changed it to the default value instead of reverting it to the previous, and valid value

In previous versions of {productname}, when an invalid value was entered into the `fontsizeinput` toolbar component, the value was not parsed and both the value and unit were set to their default values: _0_ and _pt_ respectively. 

As a consequence, entering an invalid value set selected text, or the insertion point, to _0pt_.

In {productname} 6.4.2, if an invalid string is entered in the `fontsizeinput` entry field, the `fontsizeinput` value reverts to the previous, valid, value.

=== The `tox-button` and `tox-button-secondary` buttons now support the `hover`, `active`, `focus`, and `disabled` states

In previous versions of {productname}, the `--enabled` css class for `tox-button` and `tox-button-secondary` was not defined.

As a consequence, some {productname} toolbar buttons did not render all their possible states as expected when they were selected so as to enable UI option the button represents.

With this update, the `--enabled` css class has been defined. And {productname} toolbar buttons render all their  possible states as expected when the UI option a button represents is activated.

=== The `urlinput` dialog component would not open the type-ahead dropdown when the input value was reset to an empty string

In previous versions of {productname}, a console error was thrown when the _Source_ field of the *Insert Media* dialog was reset.

As a consequence, the dropdown list of suggested URLs did not expand.

To fix this issue, the code for the `urlinput` component that is responsible for gathering the correct dropdown items was updated.

As a result, the URL suggestions dropdown list now expands even on the empty _Source_ field. As well, the host browser’s console no longer returns errors.

=== Selection was not correctly scrolled horizontally into view when using the `selection.scrollIntoView` API

In previous versions of {productname}, the `scrollToMarker` function manually calculated how much should be scrolled vertically. The horizontal scroll amount, however, was set to a specific value: left of the marker.

As a consequence, in some circumstances {productname} editor instances did not scroll to the correct horizontal position.

To fix this, instead of manually calculating the vertical and horizontal marker position, {productname} 6.4.2 now uses a native `scrollIntoView` function to keep the marker in the viewport.

=== Tab navigation no longer incorrectly stops at menu buttons within toolbar groups

In previous versions of {productname}, menu buttons were assigned an internal attribute.

When the More toolbar button — *…* — was opened, and the, now-visible, floating toolbar contained a menu button, using the Tab key to navigate through the floating toolbar icons would, because of this attribute and in some circumstances, stop progressing through the toolbar and, sometimes, enter a selection loop.

For this update this internal attribute has been removed and using the Tab key to activate floating toolbar icons progresses through these icons as expected.

=== Redial would, in some circumstances, cause elements to not have an initial value selected when they should have

In previous versions of {productname}, the host browser did not properly manage switching child elements when the Accessibility Checker dialog was visible.

As a consequence, the dropdown menu in this dialog would, in some circumstances, present without one of the dropdown menu’s options being selected by default.

To fix this issue {productname} now populates the element with a default value, unless this menu is explicitly configured as empty by the particular {productname} instance’s configuration.

NOTE: this change also addresses xref:6.4.1-release-notes.adoc#known-issues[a known issue] in the xref:a11ychecker.adoc[Accessibility Checker Premium plugin].

=== The contextual toolbar displayed the status of Advanced List Premium plugin icons incorrectly

In previous versions of {productname}, the quickbar button handler setup for the Open Source plugin, xref:lists.adoc[Lists], was different to the quickbar button handler setup for the Premium plugin, xref:advlist.adoc[Advanced Lists].

As a consequence, when a {productname} instance included the Advanced Lists Premium plugin, the contextual toolbar did not display button status on the toolbar correctly.

With this update, the setup handler for the Advanced Lists Premium plugin now matches the setup handler settings for the Open Source Lists plugin. And toolbar icon state is now correctly rendered on the contextual toolbar.
