= TinyMCE 6.5
:navtitle: TinyMCE 6.5
:description: Release notes for TinyMCE 6.5
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

//include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.5 was released for {enterpriseversion} and {cloudname} on Wednesday, June 14^th^, 2023. These release notes provide an overview of the changes for {productname} 6.5:

* xref:new-premium-plugin[New Premium Plugin]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium Plugin end-of-life announcement]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:known-issues[Known issues]

[[new-premium-plugin]]
== New Premium Plugin

[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.5.

=== Merge Tags 1.3.0

The {productname} 6.5 release includes an accompanying release of the **Merge Tags** premium plugin.

**Merge Tags** 1.3.0 includes one fix:

=== The plugin now correctly manages prefixes and suffixes when they are the same.
//#TINY-9566

In previous versions of {productname}, a bug was discovered with the merge tags plugin. The issue arose when the plugin mishandled the prefix and suffix for merge tags in situations where the user placed multiple merge tags within either an inline or block element, which resulted in incorrect management of the prefixes and suffixes during the `setContent` operation.

As a consequence, an unintended repetition of the prefix or suffix occurred, which lead to an undesired output.

For instance, if the input was: 

[souce, html]
----
<div>%Tag1% this is a bug %Tag1%</div>
----

the output would be:

[source, html]
----
%Tag1%%% this is a bug %%%Tag1%
----

However, in the current version of {productname}, this issue has been addressed, which now properly handles this problem by splitting the array of any matching merge tags that are identified as `odd` prefixes or suffixes.


[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium Plugin end-of-life announcement

The following premium plugin has been announced as reaching its end-of-life:

[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.5 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.5 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvements]]
== Improvements

{productname} 6.5 also includes the following improvements:


[[additions]]
== Additions
{productname} 6.5 also includes the following additions:


[[changes]]
== Changes

{productname} 6.5 also incorporates the following changes:


[[bug-fixes]]
== Bug fixes

{productname} 6.5 also includes the following bug fixes:


[[security-fixes]]
== Security fixes

{productname} 6.5 includes a fix for the following security issue:


[[known-issues]]
== Known issues

This section describes issues that users of {productname} 6.5 may encounter and possible workarounds for these issues.

There are several known issues in {productname} 6.5.