= TinyMCE 6.5
:navtitle: TinyMCE 6.5
:description: Release notes for TinyMCE 6.5
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

//include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.5 was released for {enterpriseversion} and {cloudname} on Wednesday, June 14^th^, 2023. These release notes provide an overview of the changes for {productname} 6.5:

* xref:new-premium-plugin[New Premium Plugin]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium Plugin end-of-life announcement]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:known-issues[Known issues]

[[new-premium-plugin]]
== New Premium Plugin

[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.5.

=== Enhanced Media Embed 3.1.2

The {productname} 6.5 release includes an accompanying release of the **Enhanced Media Embed** premium plugin.

**Enhanced Media Embed** 3.1.2 includes the following fix.

=== Allow a media embed element to be correctly resized when using the media plugin dialog by converting the responsive media embed to a standalone iframe.
//#TINY-8714

Previously, the Enhanced Media Embed plugin and the Media plugin encountered issues when used together.

The Enhanced Media Embed plugin wraps `iframe` in a responsive wrapper that relies on large padding for the height.

The Media plugin dialog, however, targets the `"ephox-embed-iri"` div, and the width and height are mapped to the wrapper’s `max-width` and `max-height` properties.

When content created with the Enhanced Media Embed plugin is inserted using the Media plugin dialog, the height is primarily determined by padding, rendering the `max-height` property ineffective.

(For additional detail, see https://benmarshall.me/responsive-iframes[benmarshall.me/responsive-iframes].)

As well, when inserting embedded content via the Enhanced Media Embed plugin, the element may be dis-proportionally sized. This occurred because height was not explicitly set, leaving it to be determined by the content within the `iframe`.

In Enhanced Media Embed 3.1.2 the responsive embedded content is wrapped in a div with the wrapper’s `max-width` set. This ensures that the embedded content maintains proportional sizing when resizing the viewport.

As well, when opening the media plugin dialog for content created using the Enhanced Media Embed plugin and identified with the `"ephox-embed-iri"` attribute, the width and height are now calculated and displayed in the editor. If any changes to the height or width are made within the dialog, the responsive media embed is converted into a standalone `iframe` with a fixed width and height to reflect the modifications.

For information on the **Enhanced Media Embed** plugin, see: xref:introduction-to-mediaembed.adoc[Introduction to Enhanced Media Embed].

[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium Plugin end-of-life announcement

The following premium plugin has been announced as reaching its end-of-life:

[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.5 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.5 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvements]]
== Improvements

{productname} 6.5 also includes the following improvements:


[[additions]]
== Additions
{productname} 6.5 also includes the following additions:


[[changes]]
== Changes

{productname} 6.5 also incorporates the following changes:


[[bug-fixes]]
== Bug fixes

{productname} 6.5 also includes the following bug fixes:


[[security-fixes]]
== Security fixes

{productname} 6.5 includes a fix for the following security issue:


[[known-issues]]
== Known issues

This section describes issues that users of {productname} 6.5 may encounter and possible workarounds for these issues.

There are several known issues in {productname} 6.5.