= TinyMCE 6.5
:navtitle: TinyMCE 6.5
:description: Release notes for TinyMCE 6.5
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

//include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.5 was released for {enterpriseversion} and {cloudname} on Wednesday, June 14^th^, 2023. These release notes provide an overview of the changes for {productname} 6.5:

* xref:new-premium-plugin[New Premium Plugin]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium Plugin end-of-life announcement]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:known-issues[Known issues]

[[new-premium-plugin]]
== New Premium Plugin

[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.5.

=== Merge Tags 1.3.0

The {productname} 6.5 release includes an accompanying release of the **Merge Tags** premium plugin.

**Merge Tags** 1.3.0 includes one fix:

=== Right clicking on a merge tag instance presented different highlighting depending on the host browser.
//#TINY-9848

In previous versions of {productname}, when users right-clicked on a merge tag, the highlighting within the merge tag selection varied, depending on the host browser.

This resulted in an inconsistent end-user experience.

{productname} 6.5 no longer uses a browser’s default highlighting of the merge tag. Instead, {productname} 6.5 introduces {productname}-specific styles. These styles highlight the merge tag consistently across different browsers.

{productname} now presents end-users with uniform merge tag highlighting across all supported browsers.

For information on the **Merge Tags** plugin, see: xref:mergetags.adoc[Merge Tags].

=== Advanced Templates 1.2.0

The {productname} 6.5 release includes an accompanying release of the **Advanced Templates** premium plugin.

**Advanced Templates** 1.2.0 includes one fix:

=== The insert template button and menu item was not disabled when the selection was in a non-editable context.
//#TINY-9892

In previous versions of {productname}, the insert template button and menu item remained enabled even in `contenteditable="false"` contexts.

As a consequence, no action occured when attempting to insert a template into a `contenteditable="false"` root.

In {productname} 6.5, the button and toolbar item will now be disabled when the selection is in a `contenteditable="false"` context.

[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium Plugin end-of-life announcement

The following premium plugin has been announced as reaching its end-of-life:

[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.5 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.5 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvements]]
== Improvements

{productname} 6.5 also includes the following improvements:


[[additions]]
== Additions
{productname} 6.5 also includes the following additions:


[[changes]]
== Changes

{productname} 6.5 also incorporates the following changes:


[[bug-fixes]]
== Bug fixes

{productname} 6.5 also includes the following bug fixes:

=== Text within anchor tags, <a>, presented with the Times New Roman font-family, ignoring the font family used in the original document.
//#TINY-9812

In previous versions of {productname}, an issue related to the `a:link` selector in the CSS received from Microsoft Word was identified.

When content containing links was pasted from a Microsoft Word file into a {productname} instance running the xref:introduction-to-powerpaste.adoc[PowerPaste] plugin, the pasted-in link text rendered using the Times New Roman font family. And it presented thus no matter the typeface set for this text in the original Microsoft Word document.

To work around this, {productname} 6.5 removes the default CSS styling applied by Microsoft Word during the paste operation.

With this change, link text copied from Microsoft Word using the PowerPaste plugin now uses the font-family matching that used in the source document.

=== Invalid markup in Notification and Dialog close buttons.
//#TINY-9849

In previous versions of {productname}, an issue was identified in the close buttons: invalid markup was present. Specifically, a div element was being used within the buttons. This violates HTML standards and caused problems when running {productname} HTML through markup checkers: the checker, correctly, threw errors.

In {productname} 6.5, the markup was fixed by replacing the div element with a `<span>` element, aligning it with HTML guidelines. As a result, the updated close buttons now pass HTML markup checkers without throwing errors.

[[security-fixes]]
== Security fixes

{productname} 6.5 includes a fix for the following security issue:


[[known-issues]]
== Known issues

This section describes issues that users of {productname} 6.5 may encounter and possible workarounds for these issues.

There are several known issues in {productname} 6.5.