= TinyMCE 6.5
:navtitle: TinyMCE 6.5
:description: Release notes for TinyMCE 6.5
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

//include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.5 was released for {enterpriseversion} and {cloudname} on Wednesday, June 14^th^, 2023. These release notes provide an overview of the changes for {productname} 6.5:

* xref:new-premium-plugin[New Premium Plugin]
* xref:accompanying-premium-plugin-changes[Accompanying Premium Plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium Plugin end-of-life announcement]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:known-issues[Known issues]

[[new-premium-plugin]]
== New Premium Plugin

[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 6.5.

=== Checklist 2.0.5

The {productname} 6.5 release includes an accompanying release of the **Checklist** premium plugin.

**Checklist** 2.0.5 includes one fix:

=== Checklist toggling was possible on elements with a `contenteditable="false"` attribute set
//#TINY-9469

In previous versions of {productname}, the Checklist plugin could toggle elements with a `contenteditable = "false"` attribute set.

As a consequence, lists nested within an element with a `contenteditable="false"` attribute set could be converted into checklists.

To address this, as of {productname} 6.5, the Checklist button is disabled when the selection is within an element with a `contenteditable="false"` attribute set.

It is no longer possible to apply Checklist functionality to elements with a `contenteditable="false"` attribute set.

For information on the **Checklist** plugin, see: xref:checklist.adoc[Checklist].
[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium Plugin end-of-life announcement

The following premium plugin has been announced as reaching its end-of-life:

[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.5 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.5 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvements]]
== Improvements

{productname} 6.5 also includes the following improvements:


[[additions]]
== Additions
{productname} 6.5 also includes the following additions:


[[changes]]
== Changes

{productname} 6.5 also incorporates the following changes:


[[bug-fixes]]
== Bug fixes

{productname} 6.5 also includes the following bug fixes:


[[security-fixes]]
== Security fixes

{productname} 6.5 includes a fix for the following security issue:


[[known-issues]]
== Known issues

This section describes issues that users of {productname} 6.5 may encounter and possible workarounds for these issues.

There are several known issues in {productname} 6.5.