= TinyMCE 6.6
:navtitle: TinyMCE 6.6
:description: Release notes for TinyMCE 6.6
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.6 was released for {enterpriseversion} and {cloudname} on Wednesday, July 19^th^, 2023. These release notes provide an overview of the changes for {productname} 6.6, including:

* xref:new-premium-plugin[New Premium plugin]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvement[Improvement]
* xref:additions[Additions]
* xref:change[Change]
* xref:bug-fix[Bug fix]


[[new-premium-plugin]]
New Premium plugin

The following new Premium plugin was released alongside {productname} 6.6.

=== AI 1.0.0

The new Premium plugin, **AI** // description here.

For information on the **<Premium plugin name>** see xref:ai.adoc[AI].


[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.6 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.6 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvement]]
== Improvement

{productname} 6.6 also includes the following improvement:

=== Displaying the footer section of a modal or inline dialog is now optional
//#TINY-9996

A {productname} dialog’s UI consist of three main sections: the title, body, and footer.

Previously, it was a requirement that any {productname} dialog — built-in or custom — displayed all three parts.

As of {productname} 6.6, it is possible to configure a custom dialog to not render the footer section.

When defining a modal or inline dialog, set the `buttons` property to `undefined` or to `[]` (an empty array). The result is a dialog that displays without rendering the footer section.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.


[[additions]]
== Additions

{productname} 6.6 also includes the following additions:

=== Added a new property — `bottom` — to inline dialog configurations
//#TINY-9888

We have added a new option that opens an inline dialog. This inline dialog will be positioned at the bottom of the editor, if the `toolbar_location` option is set to top. This option doesn’t have any impact on the modal dialog, only inline dialog are positioned at the bottom of the editor, if this setting was set to inline: 'bottom' 

This new inline dialog option allows the inline dialog to be positioned at the bottom of the editor

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.


=== Added a new property — `persistent` to inline dialog configurations.
//#TINY-9991

This new option allows the inline dialog to be persistent, meaning that it will not be closed when the user clicks outside of the dialog

// more CCFR here.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new `streamContent` property for the `iframe` dialog component which controls dialog `setData()` behavior. 
//#TINY-10032

With the property set to `true`, frame content will update with `document.write()` to avoid reloading the frame, and end scroll positions will be maintained as new content streams in.

// more CCFR here.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new `border` property for the `iframe` dialog component which controls the visibility of its border.
//#TINY-10049

// CCFR here

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `align` — for the label dialog component that controls text alignment.
//#TINY-10058

A new, and optional, property — `+align+` — is available for the dialog component, `+label+`.

This property allows text in this component be set left-, centre-, or right-aligned.

If the property is not explicitly set, it uses a default value which sets label text to present as it has always been presented: left-aligned for LTR languages; and right-aligned for RTL languages.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== - New `ai`, `ai-prompt` and `send` icons.
//#TINY-9942

// CCFR here.

// link out to ai premium plugin page here?

=== Add `ai` buttons to the default toolbar and menubar.
//#TINY-9939

// CCFR here

// link out to ai premium plugin page here?


[[change]]
== Change

=== The icon in `alertbanner` dialog component is not clickable if the _URL_ field is not specified.
//#TINY-10013

// CCFR here


[[bug-fix]]
== Bug fix

{productname} 6.6 also includes the following bug fix:

=== Fixed an issue that prevented setting the inline dialog `size` to _medium_ or _normal_.
//#TINY-10015

Previously, although the inline dialog specification included a `size` option, the function was not implemented. As a consequence, no matter what value `size` was set to, an inline dialog’s size defaulted to `normal`.

For this update the missing functionality, which applies the necessary CSS when a `size` value is set for an inline dialog, was added.

Setting an inline dialog to any of the supported sizes — 

[source,js]
----
size: 'normal', // or
size: 'medium', // or
size: 'large',
----

— now changes the dialog’s width, as expected.
