= TinyMCE 6.6
:navtitle: TinyMCE 6.6
:description: Release notes for TinyMCE 6.6
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.6 was released for {enterpriseversion} and {cloudname} on Wednesday, July 19^th^, 2023. These release notes provide an overview of the changes for {productname} 6.6, including:

* xref:new-premium-plugin[New Premium plugin]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvement[Improvement]
* xref:additions[Additions]
* xref:change[Change]
* xref:bug-fix[Bug fix]


[[new-premium-plugin]]
New Premium plugin

The following new Premium plugin was released alongside {productname} 6.6.

=== AI Assistant 1.0.0

The new Premium plugin, **AI Assistant** // description here.

For information on **AI Assistant**, see xref:ai.adoc[AI Assistant].


[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.6 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.6 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[additions]]
== Additions

{productname} 6.6 also includes the following additions:

=== Added a new property — `bottom` — to inline dialog configurations
//#TINY-9888

We have added a new option that opens an inline dialog. This inline dialog will be positioned at the bottom of the editor, if the `toolbar_location` option is set to top. This option doesn’t have any impact on the modal dialog, only inline dialog are positioned at the bottom of the editor, if this setting was set to inline: 'bottom' 

This new inline dialog option allows the inline dialog to be positioned at the bottom of the editor

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `persistent` — for inline dialog configurations that controls dialog persistence when not in focus
//#TINY-9991

A new, and optional, property, — `+persistent+` — is available for inline dialog configuration.

When this property is set to `true`, an inline dialog will stay open when focus is switched away from the dialog and towards other parts of the {productname} editor (for example, the document editor, or a menu).

If the property is not explicitly set, it is set to `+false+`, matching inline dialog behavior prior to this property being added to {productname}.

Also, setting the property to `+true+` does not over-ride normal mechanisms for closing a dialog, such as clicking the _Close_ button or pressing the *Esc* key.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `streamContent` — for the `iframe` dialog component which controls dialog `setData()` behavior
//#TINY-10032

A new, and optional, property, — `+streamContent+` — is avalable for `iframe` dialog components.

When this property is set to `true`, content within the `iframe` component is updated using `document.write()` rather than `srcdoc`.

As a consequence, the component’s contents update without flickering. As well, if the `iframe` component is currently scrolled to the end of the extant content, this position will be maintained as new content is added.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `border` — for the `iframe` dialog component that controls border visibility
//#TINY-10049

A new, and optional, property — `+border+` — is available for the dialog component, `+iframe+`.

When this property is set to `true`, a border displays around the `+iframe+` component. As well, when the `+border+` property is set to `true`, the iframe component is highlighted when it is given focus.

If the property is not explicitly set, it is set to `+false+`, matching the presentation norm prior to it being added to {productname}.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `align` — for the label dialog component that controls text alignment
//#TINY-10058

A new, and optional, property — `+align+` — is available for the dialog component, `+label+`.

This property allows text in this component be set left-, centre-, or right-aligned.

If the property is not explicitly set, it uses a default value which sets label text to present as it has always been presented: left-aligned for LTR languages; and right-aligned for RTL languages.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== - New `ai`, `ai-prompt` and `send` icons.
//#TINY-9942

// CCFR here.

For more information on **AI Assistant**, see xref:ai.adoc[AI Assistant].

=== AI Assistant plugin toolbar items added to the default toolbar and AI Assistant plugin menu items added to the default menu bar
//#TINY-9939

With the release of the new xref:new-premium-plugin[AI Premium plugin], {productname} defaults have been updated.

If the AI Assistant plugin is added to a {productname} configuration, by default:

. the _AI dialog_ and _AI shortcuts_ menu items will appear in the {productname} *Tools* menu; and

. the _AI dialog_ and _AI shortcuts_ toolbar items will appear in the {productname} toolbar.

NOTE: further **AI Assistant**-specific menu items are generated based on the setting of the _quick prompts_ option. These will appear as sub-menus items of the _AI shortcuts_ menu and toolbar items.

For more information on **AI Assistant**, see xref:ai.adoc[AI Assistant].


[[improvement]]
== Improvement

{productname} 6.6 also includes the following improvement:

=== Displaying the footer section of a modal or inline dialog is now optional
//#TINY-9996

A {productname} dialog’s UI consist of three main sections: the title, body, and footer.

Previously, it was a requirement that any {productname} dialog — built-in or custom — displayed all three parts.

As of {productname} 6.6, it is possible to configure a custom dialog to not render the footer section.

When defining a modal or inline dialog, set the `buttons` property to `undefined` or to `[]` (an empty array). The result is a dialog that displays without rendering the footer section.

For details see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.


[[change]]
== Change

=== The icon in `alertbanner` dialog component is not clickable if the _URL_ field is not specified
//#TINY-10013

// CCFR here


[[bug-fix]]
== Bug fix

{productname} 6.6 also includes the following bug fix:

=== Fixed an issue that prevented setting the inline dialog `size` to _medium_ or _normal_
//#TINY-10015

Previously, although the inline dialog specification included a `size` option, the function was not implemented. As a consequence, no matter what value `size` was set to, an inline dialog’s size defaulted to `normal`.

For this update the missing functionality, which applies the necessary CSS when a `size` value is set for an inline dialog, was added.

Setting an inline dialog to any of the supported sizes — 

[source,js]
----
size: 'normal', // or
size: 'medium', // or
size: 'large',
----

— now changes the dialog’s width, as expected.
