= TinyMCE 6.6
:navtitle: TinyMCE 6.6
:description: Release notes for TinyMCE 6.6
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.6 was released for {enterpriseversion} and {cloudname} on Wednesday, July 19^th^, 2023. These release notes provide an overview of the changes for {productname} 6.6, including:

* xref:new-premium-plugin[New Premium plugin]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]

[[new-premium-plugin]]
New Premium plugin

The following new Premium plugin was released alongside {productname} 6.6.

=== AI 1.0.0

The new Premium plugin, **AI** // description here.

For information on the **<Premium plugin name>** see xref:ai.adoc[AI].


[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.6 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.6 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].
