= TinyMCE 6.6
:navtitle: TinyMCE 6.6
:description: Release notes for TinyMCE 6.6
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.6 was released for {enterpriseversion} and {cloudname} on Wednesday, July 19^th^, 2023. These release notes provide an overview of the changes for {productname} 6.6, including:

* xref:new-premium-plugin[New Premium plugin]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:known-issue[Known issue]

[[new-premium-plugin]]
New Premium plugin

The following new Premium plugin was released alongside {productname} 6.6.

=== AI Assistant 1.0.0

The new Premium plugin, **AI Assistant**, allows a {productname} document to send queries to registered AI APIs and either:

. immediately add the returned results to a document; or
. temporarily store the returned results for later use in the currently active {productname} instance.

For information on **AI Assistant**, see xref:ai.adoc[AI Assistant].


[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.6 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.6 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[additions]]
== Additions

{productname} 6.6 also includes the following additions:

=== Added a new property value — `bottom` — for inline dialog configurations that anchors the dialog to the bottom of the editor
//#TINY-9888

A new property value — `+bottom+` — is available for inline dialog configuration.

By default, {productname} dialogs present as modal and in the center of the editor viewport.

Previously, adding a second argument — `{ inline: 'toolbar' }` to `editor.windowManager.open`, set the dialog to appear adjacent to the {productname} toolbar.

With this update, a new value can be passed with this second argument: `{ inline: 'bottom' }`.

This new inline dialog option sets the inline dialog to appear at the bottom of the editor viewport.

For details, see the xref:dialog-configuration.adoc#dialog-position[Dialog position section] of the Dialog configuration documentation.

=== Added a new property — `persistent` — for inline dialog configurations that will stop the dialog closing when clicking away from it
//#TINY-9991

A new, and optional, property, — `+persistent+` — is available for inline dialog configuration.

When this property is set to `true`, an inline dialog will stay open when focus is switched away from the dialog and towards other parts of the {productname} editor (for example, the document editor, or a menu).

If the property is not explicitly set, it is set to `+false+`, matching inline dialog behavior prior to this property being added to {productname}.

Also, setting the property to `+true+` does not over-ride normal mechanisms for closing a dialog, such as clicking the _Close_ button or pressing the *Esc* key.

For details, see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `streamContent` — for the `iframe` dialog component
//#TINY-10032

A new, and optional, property, — `+streamContent+` — is available for `iframe` dialog components.

When this property is set to `true`, `setData()` updates content within the `iframe` component using `document.write()` rather than `srcdoc`. 

As a consequence, the component’s contents update without reloading the frame and without flickering. As well, if the `iframe` component is currently scrolled to the end of the extant content, this position is maintained as new content is added.

For details, see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `border` — for the `iframe` dialog component that allows a border to be added
//#TINY-10049

Previously, {productname} provided no option to set a border around the `iframe` dialog component. This caused UX and accessibility issues since the `iframe` bounds were not visible and the iframe showed no highlight when it was made the current focus.

With {productname} 6.6, a new, and optional, property — `+border+` — is now available for the dialog component, `+iframe+`.

When this property is set to `true`, a border displays around the `+iframe+` component. As well, when the `+border+` property is set to `true`, the iframe component is highlighted when it is given focus.

If the property is not explicitly set, it is set to `+false+`, matching the presentation norm prior to it being added to {productname}.

For details, see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== Added a new property — `align` — for the label dialog component that controls text alignment
//#TINY-10058

A new, and optional, property — `+align+` — is available for the dialog component, `+label+`.

This property allows text in this component be set left-, centre-, or right-aligned.

If the property is not explicitly set, it uses a default value which sets label text to present as it has always been presented: left-aligned for LTR languages; and right-aligned for RTL languages.

For details, see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== New `ai`, `ai-prompt` and `send` icons
//#TINY-9942

With the release of the new xref:new-premium-plugin[AI Assistant Premium plugin], {productname}’s default available icon set has been updated.

This update includes three new icons.

[cols="^,^,^",options="header"]
|===
|Identifier |Preview |Filename
|`+ai+` |image:icons/ai.svg[ai.svg] |`+ai.svg+`
|`+ai-prompt+` |image:icons/ai-prompt.svg[ai-prompt.svg] |`+ai-prompt.svg+`
|`+send+` |image:icons/send.svg[send.svg] |`+send.svg+`
|===

For the full list of icons available with {productname} by default, see xref:editor-icon-identifiers.adoc[Icons available for {productname}].

For more information on **AI Assistant**, see xref:ai.adoc[AI Assistant].

=== AI Assistant plugin toolbar items added to the default toolbar and AI Assistant plugin menu items added to the default menu bar
//#TINY-9939

With the release of the new xref:new-premium-plugin[AI Assistant Premium plugin], {productname}’s default menus and toolbars have been updated.

If the AI Assistant plugin is added to a {productname} configuration, by default:

. the _AI dialog_ and _AI shortcuts_ menu items will appear in the {productname} *Tools* menu; and

. the _AI dialog_ and _AI shortcuts_ toolbar items will appear in the {productname} toolbar.

NOTE: further **AI Assistant**-specific menu items are generated based on the setting of the _quick prompts_ option. These will appear as sub-menus items of the _AI shortcuts_ menu and toolbar items.

For more information on **AI Assistant**, see xref:ai.adoc[AI Assistant].


[[improvements]]
== Improvements

{productname} 6.6 also includes the following improvement:

=== When defining a modal or inline dialog, if the buttons property is an empty array, or is not defined at all, the footer will now no longer be rendered
//#TINY-9996

A {productname} dialog’s UI consist of three main sections: the title, body, and footer.

Previously, it was a requirement that any {productname} dialog — built-in or custom — displayed all three parts.

As of {productname} 6.6, it is possible to configure a custom dialog to not render the footer section.

When defining a modal or inline dialog, set the `buttons` property to `[]` (an empty array) or do not define the property at all. The result is a dialog that displays without rendering the footer section.

For details, see the xref:dialog-configuration.adoc#configuration-parameters[Configuration parameters section] of the Dialog configuration documentation.

=== The `iframe` dialog component now has a minimum height of 200px
//#TINY-10059

The `iframe` dialog component takes in html as a string and displays it within the dialog.

And, previously, the component’s height adjusted dynamically to take up the space remaining in a dialog once other components were rendered.

Large dialogs have a purposefully large fixed height, creating substantial empty space for the `iframe` component to dynamically fill.

Examples of large dialogs include the dialogs presented by choosing *View → Preview* or *View → Source code* from a default {productname} instance menu bar.

Medium dialogs, however, do not have a static height. Instead, they render with the height needed to fit its components.

As a consequence, `iframe` dialog components placed within medium dialogs acquired their height value from the host browser, taking said host browser’s minimum iframe height.

In many circumstances, this produced a display area to small to usefully display the content added to the `iframe` component.

As of the {productname} 6.6 update, the component has a minimum height of 200px, improving its out-of-the-box utility as a display component, particularly in medium dialogs.

For more information about this component, see the xref:dialog-components.adoc#iframe[`iframe` section] of the Dialog components documentation.

For more information about dialogs, see the xref:dialog-configuration.adoc[Dialog configuration] documentation.


[[change]]
== Change

{productname} 6.6 also includes the following change:

=== The icon in an `alertbanner` dialog component is no longer clickable if the _URL_ field is not specified
//#TINY-10013

The `url` argument in an `alertbanner` dialog component is optional. When it is specified, the value of the argument is passed to the `onAction` function when the dialog’s icon is activated by clicking or pressing.

Previously, however, when the `url` argument was not specified, the dialog icon remained clickable or pressable, even though nothing happened on this user action.

With this update, this has been changed.

The icon in an `alertbanner` dialog remains visible, but it is no longer clickable if the `url` argument is not specified.

For more information on `alertbanner` dialog components, see the xref:dialog-components.adoc#alertbanner[Alert banner section] of the Dialog components documentation.


[[bug-fixes]]
== Bug fixes

{productname} 6.6 also includes the following bug fixes:

=== Fixed an issue that caused the inline dialog `size` setting to have no effect
//#TINY-10015

Previously, although the inline dialog specification included a `size` option, the function was not implemented. As a consequence, no matter what value `size` was set to, an inline dialog’s size defaulted to `normal`.

For this update the missing functionality, which applies the necessary CSS when a `size` value is set for an inline dialog, was added.

Setting an inline dialog to any of the supported sizes — 

[source,js]
----
size: 'normal', // or
size: 'medium', // or
----

— now changes the dialog’s width, as expected.

For more information see the xref:dialog-configuration.adoc#options[Options] table in the xref:dialog-configuration.adoc[Dialog configuration documentation].

NOTE: `inline` dialogs do not support `size: 'large'`.

=== Fixed an issue that prevented the close button from being clicked when the dialog was blocked
//#TINY-10056

Previously, when a dialog was blocking, the close button — *X* — became inactive. Pressing the *Esc* key still closed the dialog, but the close button was not available to a mouse pointer and could not be navigated to using keyboard navigation.

As of {productname} 6.6 this has been corrected. A dialog’s close button now remains active and available as a tool for closing a dialog, even when the dialog is blocking.


[[known-issue]]
== Known issue

When Safari is the host browser for a {productname} 6.6 instance running with the xref:ai.adoc[*AI Assistant*] plugin loaded, flickering of the returned text preview in the AI Assistant dialog may occasionally occur.

This is a visual affect only. It does not effect *AI Assistant* functionality, nor the material being returned from the API query.

