= TinyMCE 6.6.1
:navtitle: TinyMCE 6.6.1
:description: Release notes for TinyMCE 6.6.1
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 6.6.1 was released for {enterpriseversion} and {cloudname} on Wednesday, August 9^th^, 2023. These release notes provide an overview of the changes for {productname} 6.6.1, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvement[Improvement]
* xref:addition[Addition]
* xref:change[Change]
* xref:bug-fixes[Bug fixes]
//* xref:security-fixes[Security fixes]
//* xref:known-issues[Known issues]



[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} 6.6.1.

=== AI Assistant 1.0.1

The {productname} 6.6.1 release includes an accompanying release of the **AI Assistant** premium plugin.

**AI Assistant** 1.0.1 includes the following fixes:

==== Toolbar buttons and menu items were enabled while the dialog was waiting for a final response
//#TINY-10077 #1

The **AI Assistant** toolbar buttons and menu items provide no functionality while a response is being generated in the AI Assistant dialog. Previously, however, these buttons and items continued to present as enabled during response generation.

With the release of **AI Assistant** 1.0.1, this has been corrected. The plugin’s toolbar buttons and menu items are now disabled while a response is being generated.

==== Error events from streaming requests were included in separate threads to the corresponding response event
//#TINY-10077 #2

Previously, when an error occurred while a streaming response was in progress, both an error and response event were added to the current thread.

**AI Assistant 1.0.1** corrects this. Now, when an error occurs during an in-progress streaming response, a single event — containing both the error and the response — is added to the current thread.

==== Preview content was removed when an error is encountered part way through a streaming response
//#TINY-10096

Previously, when an error was encountered while a streaming response was in progress, the **AI Assistant** dialog removed the partial response when displaying the error.

With the release of **AI Assistant 1.0.1**, the partial response is left in place, displayed as a finished response.

And the error message is displayed below this, left-in-place, response.

==== When a response from the AI Assistant dialog was inserted into a selection not in view, the content did not scroll into view
//#TINY-10102

Previously when inserting a response from the AI Assistant dialog at a selection which is above the current view, the inserted content would not be scrolled into view.

In **AI Assistant** 1.0.1, the response is now inserted after the dialog is closed, allowing the content to be scrolled into view correctly.

For information on the **AI Assistant** plugin, see: xref:ai.adoc[AI Assistant].


=== Enhanced Image Editing

The {productname} 6.6.1 release includes an accompanying release of the **Enhanced Image Editing** premium plugin.

**Enhanced Image Editing** 1.1.1 includes the following fix:

==== Context menu and context toolbar no longer show when the selected image is in a non-editable context
//#TINY-10016

// CCFR here.

For information on the **Enhanced Image Editing** plugin, see: xref:editimage.adoc[Enhanced Image Editing].



[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} 6.6.1 release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 6.6.1 skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvement]]
== Improvement

{productname} 6.6.1 also includes the following improvement:

=== When Safari is the host browser, content updates for iframe dialog components with `streamContent: true` set are now throttled to 500ms intervals
//#TINY-10097

When `iframe` dialog components have xref:dialog-configuration.adoc#dialog_streamContent[`streamContent: true`] set, content is updated using the `document.write()` method rather than by setting the `srcdoc` attribute to prevent the `iframe` from reloading.

This setting stops the iframe from flickering as it updates its contents when the host browser is Google Chrome or Mozilla Firefox.

The flickering still occurred when the host browser was Apple Safari, however.

In {productname} 6.6.1, content updates for `iframe` dialog components with `streamContent: true` set are throttled to 500ms intervals when Safari is the host browser. This significantly reduces the apparent flickering.

NOTE: This 500ms throttling is specific to Safari. It is not applied when any browser other than Safari is the host browser.


[[addition]]
== Addition

{productname} 6.6.1 also includes the following addition:

=== New `pad_empty_with_br` option that can be set to `true` to pad empty block elements with `<br>` tag instead of nbsp character
//#TINY-9861

[[change]]
== Change

{productname} 6.6.1 also includes the following change:

=== API comments/documentation: a markup typo and run-on sentences both corrected
//#TINY-10073

A markup typo in `/tinymce/modules/tinymce/src/core/main/ts/api/WindowManager.ts` resulted in an extraneous html markup tag displaying in the xref:/apis/tinymce.windowmanager.adoc[tinymce.WindowManager()] documentation.

As well, two run-on sentences in the same file were corrected.

[[bug-fixes]]
== Bug fixes

{productname} 6.6.1 also includes the following bug fixes:

=== On Safari and Firefox, scroll positions were not always maintained when updating the content of a `streamContent: true` iframe dialog component
//#TINY-10078

On each content update for iframe dialog components with `streamContent: true` set, the iframe is expected to automatically scroll to the bottom if the pre-update scrolled position is already at the end of the scrollable area. It is also expected, however, that the end-user can freely scroll through the iframe as content updates occur.

When Chrome is the host browser, scroll positions are natively maintained after content updates via `document.write()`, but this is not the case when either Safari or Firefox are the host browsers. Both these browsers reset the scroll positions to the top.

As a consequence, once the user scrolls up in the iframe as content updates occur and the programmatic scrolling to the bottom no longer occurs, the native behavior takes over. On Safari and Firefox, this results in the scroll being kept at the top even as the user attempts to scroll, which is both against expected behavior and poor UX.


As of {productname} 6.6.1, after a content update to a `streamContent: true` iframe dialog component, if the host browser is Firefox or Safari and the previous scroll position was not at the end of the scrollable area, {productname} now programmatically restores the previous scroll position.

=== On Safari, iframe dialog components did not consistently autoscroll to the end of the scrollable area when `streamContent: true` was set
//#TINY-10109

{productname} 6.6.0 added support for a `streamContent` setting for iframe dialog components. One of the features of this setting allows the iframe to automatically scroll to the end of the scrollable area on each content update if the scrolled position is already at the end of this area before content updates begin.

However, when Safari was the host browser, when attempting to scroll an iframe component with `streamContent: true` set before its `load` event has fired, the scroll unexpectedly jumped back to the top after the iframe loaded.

This made the autoscrolling feature inconsistent on Safari, as it depended on how quickly the iframe loaded after the content update.

In {productname} 6.6.1, when Safari is the host browser, the autoscrolling behavior is attached to a one-time event listener that responds to the iframe’s `load` event on each content update.

This allows iframe dialog components with `streamContent: true` set to consistently autoscroll to the end of the scrollable area when Safari is the host browser.


=== Scrolling behavior was inconsistent when updating a `streamContent: true` iframe dialog component with content lacking an HTML document type declaration
//#TINY-10110

When an iframe dialog has `streamContent: true` set and the scrolled position is already at the end of the scrollable area, the expected behavior is to maintain this end-of-scrollable-area position by automatically scrolling to the end of the area as content in the scrollable area updates

However, it was found that, when setting content without an HTML document type declaration using `document.write()`, the scrolling element used to determine scrolling conditions is the iframe’s body, not its document element. And, previously, only the latter was handled. As a consequence, updating the iframe with content without an HTML doctype declaration did not always maintain scroll positions as expected.

{productname} 6.6.1 now checks whether the content contains an HTML doctype declaration and, if so, it chooses the iframe’s body as the scrolling element to determine scrolling conditions. This allows content updates for `streamContent: true` iframe dialog components to behave as expected for both content with and without an HTML doctype declaration.

=== A warning message was sometimes printed to the browser console when closing a dialog that contains an iframe component
//#TINY-10070

// CCFR here.

=== When an editable area was nested inside a non-editable area, creating lists was not possible
//#TINY-10000

// CCFR here.

=== Safari and Firefox `focus` border missing from `iframe`
//TINY-10101
//2023-06-26: sub-head is ticket summary, not changelog entry.

//CCFR here.
