= New features, enhancements, and changes for TinyMCE 6.0 core and core plugins

:title_nav: Core improvements

:description: New features, enhancements, and functionality changes for TinyMCE 6.0
:keywords: releasenotes bugfixes

* xref:newfeatures[New features]
* xref:enhancements[Enhancements]
* xref:functionalitychanges[Functionality changes]
* xref:removedfunctionality[Removed functionality]

[[newfeatures]]
== New features

The following new features were added for the {productname} 6.0 release.

=== Feature name

=== Additional new features

{productname} 6.0 introduces the following minor new features:

* changelog

[[enhancements]]
== Enhancements

The following enhancements were made for the {productname} 6.0 release.

=== `+tabindex+` improvement

In iframe (classic editor) mode, {productname} now copies the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex[`+tabindex+` attribute] from the target element to the editor's iframe. This accessibility improvement allows integrators to rely on the browser behavior for specifying tab order, instead of specially configuring {productname}. It also replaces the <<tabfocusplugin, Tabfocus plugin>>.

=== Enhancement name

=== Additional enhancements

{productname} 6.0 introduces the following minor enhancements:

* changelog

[[functionalitychanges]]
== Functionality changes

The following changes were made for the {productname} 6.0 release.

=== Horizontal rule plugin moved to TinyMCE Core

The Horizontal rule (`+hr+`) plugin has been moved to Core in {productname} 6.0.

The `+hr+` toolbar button and menu item will now work by default, without needing to specify `+hr+` as a plugin.

Integrators can remove `+hr+` from the `+plugins+` section of their {productname} configuration.

For information about horizontal rule-related functionality, see:

* link:available-toolbar-buttons.html#thecoretoolbarbuttons[Core toolbar buttons]
* link:available-menu-items.html#thecoremenuitems[Core menu items]
* link:editor-command-identifiers.html#coreeditorcommands[Core commands]

=== Noneditable plugin moved to TinyMCE Core

The Noneditable (`+noneditable+`) plugin has been moved to Core in {productname} 6.0.

Integrators can remove `+noneditable+` from the `+plugins+` section of their {productname} configuration.

For information about noneditable-related functionality, see:

* link:content-filtering.html#editable_class[Content filtering options - editable_class]
* link:content-filtering.html#noneditable_class[Content filtering options - noneditable_class]
* link:content-filtering.html#noneditable_regexp[Content filtering options - noneditable_regexp]

=== Print plugin moved to TinyMCE Core

The Print plugin has been moved to Core in {productname} 6.0.

The toolbar button, menu item, shortcut, and command for printing content are now available by default, without needing to specify `+print+` as a plugin.

Integrators can remove `+print+` from the `+plugins+` section of their {productname} configuration.

For information about print-related functionality, see:

* link:available-toolbar-buttons.html#thecoretoolbarbuttons[Core toolbar buttons]
* link:available-menu-items.html#thecoremenuitems[Core menu items]
* link:editor-command-identifiers.html#coreeditorcommands[Core commands]
* link:keyboard-shortcuts.html#editorkeyboardshortcuts[Shortcuts]

=== Renamed Options

The following options have been renamed in {productname} 6.0:

* The `+default_link_target+` option has been renamed to `+link_default_target+` for both `+link+` and `+autolink+` plugins.
* The `+rel_list+` option has been renamed to `+link_rel_list+` for the `+link+` plugin.
* The `+target_list+` option has been renamed to `+link_target_list+` for the `+link+` plugin.
* The `+noneditable_editable_class+` option has been renamed to `+editable_class+`.
* The `+noneditable_noneditable_class+` option has been renamed to `+noneditable_class+`.

[[removedfunctionality]]
== Removed functionality

=== Tabfocus plugin

The `+tabfocus+` plugin has been removed in {productname} 6.0. The tab order of the elements in a page, including {productname}, should now be specified using the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex[`+tabindex+` attribute]. For information about configuring tab order, see: link:accessibility.html#taborder[Tab order].
