= TinyMCE 7.0
:navtitle: TinyMCE 7.0
:description: Release notes for TinyMCE 7.0
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} 7.0 was released for {enterpriseversion} and {cloudname} on Wednesday, March 20^th^, 2024. These release notes provide an overview of the changes for {productname} 7.0, including:

// Remove sections and section boilerplates as necessary.
// Pluralise as necessary or remove the placeholder plural marker.
* xref:new-premium-plugin<s>[New Premium plugin<s>]
* xref:new-open-source-plugin<s>[New Open Source plugin<s>]
* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium plugin end-of-life announcement]
* xref:accompanying-open-source-plugin-end-of-life-announcement[Accompanying open source plugin end-of-life-announcement]
* xref:accompanying-premium-skins-and-icon-packs-changes[Accompanying Premium Skins and Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[new-premium-plugin<s>]]
New Premium plugin<s>

The following new Premium plugin was released alongside {productname} <x.y[.z]>.

=== <Premium plugin name> 1.0.0

The new Premium plugin, **<Premium plugin name>** // description here.

For information on the **<Premium plugin name>** see xref:<plugincode>.adoc[<Premium plugin name>].


[[new-open-source-plugin]]
== New Open Source plugin

The following new Open Source plugin was released alongside {productname} <x.y[.z]>.

=== <Open source plugin name> 1.0.0

The new open source plugin, **<Open source plugin name>** // description here.

For information on the **<Open source plugin name>** plugin see xref:<plugincode>.adoc[<Open source plugin name>].


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} <x.y[.z]>.

=== <Premium plugin name 1> <Premium plugin name 1 version>

The {productname} <x.y[.z]> release includes an accompanying release of the **<Premium plugin name 1>** premium plugin.

**<Premium plugin name 1>** <Premium plugin name 1 version> includes the following <fixes, changes, improvements>.

==== <Premium plugin name 1 change 1>

// CCFR here.

For information on the **<Premium plugin name 1>** plugin, see: xref:<plugincode>.adoc[<Premium plugin name 1>].


[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium plugin end-of-life announcement

The following Premium plugin has been announced as reaching its end-of-life:

=== <Premium plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Premium plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-premium-skins-and-icon-packs-changes]]
== Accompanying Premium Skins and Icon Packs changes

The {productname} <x.y[.z]> release includes an accompanying release of the **Premium Skins and Icon Packs**.

=== Premium Skins and Icon Packs

The **Premium Skins and Icon Packs** release includes the following updates:

The **Premium Skins and Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} <x.y[.z]> skin, Oxide.

For information on using premium skins and icon packs, see: xref:premium-skins-and-icons.adoc[Premium Skins and Icon Packs].


[[improvements]]
== Improvements

{productname} <x.y[.z]> also includes the following improvement<s>:

[[a-new-trigger-property-for-block-text-pattern-configurations-allowing-pattern-activation-with-either-space-or-enter-keys]]
=== A new `trigger` property for block text pattern configurations, allowing pattern activation with either Space or Enter keys
//#TINY-10324

This release introduces a new `trigger` property for block text pattern configurations, allowing pattern activation with either `Space` or `Enter` keys.

In {productname} 7.0 the default preconfigured text patterns **was changed from**:

[[example-preconfigured-text-patterns-prior-to-TinyMCE-7.0]]
.Example preconfigured text_patterns prior to {productname} 7.0
[source, js]
----
[
  { start: '*', end: '*', format: 'italic' },
  { start: '**', end: '**', format: 'bold' },
  { start: '#', format: 'h1' },
  { start: '##', format: 'h2' },
  { start: '###', format: 'h3' },
  { start: '####', format: 'h4' },
  { start: '#####', format: 'h5' },
  { start: '######', format: 'h6' },
  // The following text patterns require the `lists` plugin
  { start: '1. ', cmd: 'InsertOrderedList' },
  { start: '* ', cmd: 'InsertUnorderedList' },
  { start: '- ', cmd: 'InsertUnorderedList' }
]
----

to the following new preconfigured defaults:

.Example preconfigured text_patterns for {productname} 7.0+
[source, js]
----
[     
  { start: '*', end: '*', format: 'italic' },
  { start: '**', end: '**', format: 'bold' },
  { start: '#', format: 'h1', trigger: 'space' },
  { start: '##', format: 'h2', trigger: 'space' },
  { start: '###', format: 'h3', trigger: 'space' },
  { start: '####', format: 'h4', trigger: 'space' },
  { start: '#####', format: 'h5', trigger: 'space' },
  { start: '######', format: 'h6', trigger: 'space' },
  { start: '1.', cmd: 'InsertOrderedList', trigger: 'space' },
  { start: '*', cmd: 'InsertUnorderedList', trigger: 'space' },
  { start: '-', cmd: 'InsertUnorderedList', trigger: 'space' },
  { start: '>', cmd: 'mceBlockQuote', trigger: 'space' },
  { start: '---', cmd: 'InsertHorizontalRule', trigger: 'space' },
]
----

[IMPORTANT]
Customers that wish to revert back to the previous default block `text_patterns` execution on `Enter` key pressing will be required to replace the preconfigured text_patterns with following array:

[source, js]
----
[     
    { start: '*', end: '*', format: 'italic' },
    { start: '**', end: '**', format: 'bold' },
    { start: '#', format: 'h1', trigger: 'enter' },
    { start: '##', format: 'h2', trigger: 'enter' },
    { start: '###', format: 'h3', trigger: 'enter' },
    { start: '####', format: 'h4', trigger: 'enter' },
    { start: '#####', format: 'h5', trigger: 'enter' },
    { start: '######', format: 'h6', trigger: 'enter' },
    { start: '1. ', cmd: 'InsertOrderedList', trigger: 'enter' },
    { start: '* ', cmd: 'InsertUnorderedList', trigger: 'enter' },
    { start: '- ', cmd: 'InsertUnorderedList', trigger: 'enter' },
]
----

[TIP]
The trigger property is exclusively applicable to the configuration of block text patterns. It is not recognized in the configurations for inline and replacement text patterns.

For information on the **text_patterns**, see xref:content-behavior-options.adoc#text_patterns[Text Patterns]


[[additions]]
== Additions

{productname} <x.y[.z]> also includes the following additions:

=== <TINY-vwxyz 1 changelog entry>
//#TINY-vwxyz1

// CCFR here.

[[changes]]
== Changes

=== <TINY-vwxyz 1 changelog entry>
//#TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} <x.y[.z]> also includes the following bug fix<es>:

=== <TINY-vwxyz 1 changelog entry>
//#TINY-vwxyz1

// CCFR here.

[[security-fixes]]
== Security fixes

{productname} <x.y[.z]> includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
//#TINY-vwxyz1

// CCFR here.

[[deprecated]]
== Deprecated

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} <x.y[.z]> may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} <x.y[.z]>.

=== <TINY-vwxyz 1 changelog entry>
//#TINY-vwxyz1

// CCFR here.