= {productname} {release-version}
:release-version: 7.0.1
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, April 10^th^, 2024. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:improvements[Improvements]
* xref:changes[Changes]
* xref:removed[Removed]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== Enhanced Code Editor

The {productname} {release-version} release includes an accompanying release of the **Enhanced Code Editor** premium plugin.

This **Enhanced Code Editor** release includes the following fixes.

==== Light mode background with `advcode_inline: true` had the wrong color when {productname} was used with a dark skin.
// #TINY-10760

Previously in the **Enhanced Code Editor**, the `advcode` background color depended on the skin of the {productname} editor when `advcode_inline` was set to `true`. As a result, when {productname} was used with a dark skin, the `advcode` light mode would display dark text on a dark background.

In {productname} {release-version}, this issue has been fixed. Now, when `advcode_inline` is set to `true`, the background for `advcode` light mode is set to white. As a result, the `advcode` light mode correctly displays dark text on a light background when {productname} is used with a dark skin.

For information on the **Enhanced Code Editor** plugin, see: xref:advcode.adoc[Enhanced Code Editor].

=== <Premium plugin name 1> <Premium plugin name 1 version>

The {productname} {release-version} release includes an accompanying release of the **<Premium plugin name 1>** premium plugin.

**<Premium plugin name 1>** <Premium plugin name 1 version> includes the following <fixes, changes, improvements>.

==== <Premium plugin name 1 change 1>

// CCFR here.

For information on the **<Premium plugin name 1>** plugin, see: xref:<plugincode>.adoc[<Premium plugin name 1>].

=== Table of Contents

The {productname} {release-version} release includes an accompanying release of the **Table of Contents** premium plugin.

This **Table of Contents** release includes the following fixes.

==== Encoding header of Table of Contents causing HTML source to be revealed on refresh.
// #TINY-10682

Previously in {productname}, the **Table of Contents** (ToC) header encoding caused special characters to be incorrectly displayed as code instead of their HTML representation.

To address this issue, the HTML encoding has been removed. As a result, the ToC header now renders correctly as HTML even after refreshing, displaying as intended.

For example, if the **Table of Contents** (ToC) header contained the following content with "_Contents_" emphasized as follows:

liveDemo::tiny-10682-initial[]

Upon refreshing the ToC, the header would change to display the HTML tags literally, exposing the underlying HTML:

liveDemo::tiny-10682-before[]

Now, the header maintains the intended HTML rendering even after refreshing:

liveDemo::tiny-10682-after[]

==== Encode header title for literal display in Table of Contents.
// #TINY-10789

Previously in {productname}, during Table of Contents (ToC) generation, heading elements containing HTML tags such as `<em>` for italics were incorrectly rendered within the ToC itself.

{productname} {release-version} addresses this issue by encoding the heading element during ToC generation. This ensures that any HTML tags present within the heading element are treated as plain text and displayed literally.

For example, if your document contained a heading element with HTML tags as string in the heading content, the ToC would previously render the heading element as follows:

liveDemo::tiny-10789-before[]

Now, the ToC maintains the HTML tags within the heading element as plain text, matching the heading element itself:

liveDemo::tiny-10789-after[]

For information on the **Table of Contents** plugin, see: xref:tableofcontents.adoc[Table of Contents].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvement<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[changes]]
== Changes

{productname} {release-version} also includes the following change<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} {release-version} also includes the following removal<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fix<es>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} {release-version} includes the following deprecation<s>:

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} {release-version} may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} {release-version}.

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.