= TinyMCE {release-version}
:release-version: 7.2
:navtitle: TinyMCE {release-version}
:description: Release notes for TinyMCE {release-version}
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, June 19^th^, 2024. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:new-premium-plugin<s>[New Premium plugin<s>]
* xref:new-open-source-plugin<s>[New Open Source plugin<s>]
* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium plugin end-of-life announcement]
* xref:accompanying-open-source-plugin-end-of-life-announcement[Accompanying open source plugin end-of-life-announcement]
* xref:accompanying-enhanced-skins-and-icon-packs-changes[Accompanying Enhanced Skins & Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[new-premium-plugin<s>]]
New Premium plugin<s>

The following new Premium plugin was released alongside {productname} {release-version}.

=== <Premium plugin name>

The new Premium plugin, **<Premium plugin name>** // description here.

For information on the **<Premium plugin name>** plugin, see xref:<plugincode>.adoc[<Premium plugin name>].


[[new-open-source-plugin]]
== New Open Source plugin

The following new Open Source plugin was released alongside {productname} {release-version}.

=== <Open source plugin name>

The new open source plugin, **<Open source plugin name>** // description here.

For information on the **<Open source plugin name>** plugin, see xref:<plugincode>.adoc[<Open source plugin name>].

[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== Image Editing

The {productname} {release-version} release includes an accompanying release of the **Image Editing** premium plugin.

**Image Editing** includes the following improvement.

==== Dialog slider components now emit an onChange event when using arrow keys.
// #TINY-10428

Previously in the Edit Image dialog, when using the left/right arrow keys to adjust settings with sliders, the slider component did not properly update the image preview. As a consequence, users were unable to use the keyboard to update image properties controlled by sliders such as Brightness, Contrast, Color Levels, and Gamma settings.

In {productname} {release-version}, this issue has been resolved. Now, the slider component emits an `onChange` event when the slider value is adjusted using the left/right arrow keys. As a result, users can now update the Edit Image dialog sliders using the keyboard.

For information on the **Image Editing** plugin, see: xref:editimage.adoc[Image Editing].

=== Revision History

The {productname} {release-version} release includes an accompanying release of the **Revision History** premium plugin.

This release of **Revision History** introduces the following addition.

==== New `revisionhistory_fetch_revision` option to support updating a revision.
// #TINY-10362

In {productname} {release-version}, a new `revisionhistory_fetch_revision` option has been added to enable updating a revision after the initial fetch. If configured, when a revision is selected, the plugin uses this option to update the selected or closest revision that has no content.

NOTE: As part of this addition, the `content` property is now optional. For the fetched revisions, an empty string is considered as valid content.

IMPORTANT: The `revisionhistory_fetch` option must be configured when using the new `revisionhistory_fetch_revision` option, as it is required to provide the initial revisions.

For more information on the `revisionhistory_fetch_revision` option, see: xref:revisionhistory.adoc#revisionhistory_fetch_revision[Revision History - revisionhistory_fetch_revision].

This option is useful for handling revisions with large content or for loading content only when needed.

For information on the **Revision History** premium plugin, see: xref:revisionhistory.adoc[Revision History].


[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium plugin end-of-life announcement

The following Premium plugin has been announced as reaching its end-of-life:

=== <Premium plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Premium plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-open-source-plugin-end-of-life-announcement]]
== Accompanying open source plugin end-of-life announcement

The following open source plugin has been announced as reaching its end-of-life:

=== <Open source plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Open source plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-enhanced-skins-and-icon-packs-changes]]
== Accompanying Enhanced Skins & Icon Packs changes

The {productname} {release-version} release includes an accompanying release of the **Enhanced Skins & Icon Packs**.

=== Enhanced Skins & Icon Packs

The **Enhanced Skins & Icon Packs** release includes the following updates:

The **Enhanced Skins & Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} {release-version} skin, Oxide.

For information on using Enhanced Skins & Icon Packs, see: xref:enhanced-skins-and-icon-packs.adoc[Enhanced Skins & Icon Packs].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvements:

=== Added `referrerpolicy` as a valid attribute for an iframe element.
// #TINY-10374

Previously in {productname}, the `referrerpolicy` attribute was not considered as valid for iframe elements. In {productname} {release-version}, this attribute has been added to the schema, allowing users to include the `referrerpolicy` attribute in iframes.


[[additions]]
== Additions

{productname} {release-version} also includes the following addition:

=== Added `options.debug` API that logs the initial raw editor options to console.
// #TINY-10605

This release introduces a new `options.debug` API that logs the initial raw editor options passed to `tinymce.init` to the console. This API is useful for debugging and troubleshooting issues with the editor, especially when dynamically composing many editor options from different sources.

Usage:

[source,js]
----
tinymce.activeEditor.options.debug();
----

The following data types are logged exactly as they are passed to `tinymce.init`:

* `string`
* `number`
* `boolean`
* `object`
* `array`
* `null`

All other data types not mentioned above are logged as `[object X]` where "X" is the type of the object, such as:

* `Function`
* `Undefined`
* `RegExp`
* `Promise`
* and more

==== Example: using the `options.debug` API:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  height: 500,
  paste_as_text: true,
  context_menu: [ 'image', 'lists' ],
  menu: { insert: { title: 'Insert', items: 'table | image | accordion' }},
  inline: null,
  myUndefined: undefined,
  init_instance_callback: (editor) => editor.options.debug(),
});
----

The above code will log the following to the console:

[source,js]
----
{
  selector: 'textarea',
  height: 500,
  paste_as_text: true,
  context_menu: [ 'image', 'lists' ],
  menu: { insert: { title: 'Insert', items: 'table | image | accordion' }},
  inline: null,
  myUndefined: [object Undefined],
  init_instance_callback: [object Function],
}
----


[[changes]]
== Changes

{productname} {release-version} also includes the following change<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} {release-version} also includes the following removal<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fix<es>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} {release-version} includes the following deprecation<s>:

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} {release-version} may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} {release-version}.

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.