= TinyMCE {release-version}
:release-version: 7.2
:navtitle: TinyMCE {release-version}
:description: Release notes for TinyMCE {release-version}
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]

[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, June 19^th^, 2024. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:new-premium-plugin<s>[New Premium plugin<s>]
* xref:new-open-source-plugin<s>[New Open Source plugin<s>]
* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium plugin end-of-life announcement]
* xref:accompanying-open-source-plugin-end-of-life-announcement[Accompanying open source plugin end-of-life-announcement]
* xref:accompanying-enhanced-skins-and-icon-packs-changes[Accompanying Enhanced Skins & Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[new-premium-plugin<s>]]
New Premium plugin<s>

The following new Premium plugin was released alongside {productname} {release-version}.

=== <Premium plugin name>

The new Premium plugin, **<Premium plugin name>** // description here.

For information on the **<Premium plugin name>** plugin, see xref:<plugincode>.adoc[<Premium plugin name>].


[[new-open-source-plugin]]
== New Open Source plugin

The following new Open Source plugin was released alongside {productname} {release-version}.

=== <Open source plugin name>

The new open source plugin, **<Open source plugin name>** // description here.

For information on the **<Open source plugin name>** plugin, see xref:<plugincode>.adoc[<Open source plugin name>].

[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== <Premium plugin name 1> <Premium plugin name 1 version>

The {productname} {release-version} release includes an accompanying release of the **<Premium plugin name 1>** premium plugin.

**<Premium plugin name 1>** <Premium plugin name 1 version> includes the following <fixes, changes, improvements>.

==== <Premium plugin name 1 change 1>

// CCFR here.

For information on the **<Premium plugin name 1>** plugin, see: xref:<plugincode>.adoc[<Premium plugin name 1>].

=== Math

The {productname} {release-version} release includes an accompanying release of the **Math** premium plugin.

This **Math** plugin release includes the following fix:

==== Math preview was not rendered with the colors from the current skin.
// #TINY-10900

Previously, the **Math** preview did not follow the editor skin UI colors. As a consequence, the equation preview dialog was always rendered with black text on white background even if the UI skin was a dark skin.

This has been addressed in {productname} {release-version}. Now, the editor renders the equation preview inline with the **Math** dialog, and not using an iframe, so that the preview container's colors are inherited from the dialog. As a result, the text color and background color of the equation preview container now follows the editor skin UI colors.

For information on the **Math** plugin, see: xref:math.adoc[Math].


[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium plugin end-of-life announcement

The following Premium plugin has been announced as reaching its end-of-life:

=== <Premium plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Premium plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-open-source-plugin-end-of-life-announcement]]
== Accompanying open source plugin end-of-life announcement

The following open source plugin has been announced as reaching its end-of-life:

=== <Open source plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Open source plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-enhanced-skins-and-icon-packs-changes]]
== Accompanying Enhanced Skins & Icon Packs changes

The {productname} {release-version} release includes an accompanying release of the **Enhanced Skins & Icon Packs**.

=== Enhanced Skins & Icon Packs

The **Enhanced Skins & Icon Packs** release includes the following updates:

The **Enhanced Skins & Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} {release-version} skin, Oxide.

For information on using Enhanced Skins & Icon Packs, see: xref:enhanced-skins-and-icon-packs.adoc[Enhanced Skins & Icon Packs].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvement<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[additions]]
== Additions

{productname} {release-version} also includes the following addition<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[changes]]
== Changes

{productname} {release-version} also includes the following change<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} {release-version} also includes the following removal<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fix<es>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} {release-version} includes the following deprecation<s>:

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} {release-version} may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} {release-version}.

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.