= {productname} {release-version}
:release-version: 7.2.1
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, July 3^rd^, 2024. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:bug-fixes[Bug fixes]


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fix<es>:

=== Open Link button was disabled when selection partially covered a link or when multiple links were selected.
// #TINY-11009

Previously, the “Open link” toolbar button and menu item were disabled when a link was partially selected or when the selection included multiple links.

{productname} {release-version} addresses this issue. Now, the "Open link" toolbar button and menu item are enabled when any part of a link or multiple links are within the selection, even when the selection is not perfectly confined to a single link.