= {productname} {release-version}
:release-version: 7.6.1
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on <weekday>, <month> <DD>^<st|nd|rd|th>^, <YYYY>. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:improvements[Improvements]
* xref:bug-fixes[Bug fixes]


[[new-premium-plugin<s>]]
New Premium plugin<s>

The following new Premium plugin was released alongside {productname} {release-version}.

=== <Premium plugin name>

The new Premium plugin, **<Premium plugin name>** // description here.

For information on the **<Premium plugin name>** plugin, see xref:<plugincode>.adoc[<Premium plugin name>].


[[new-open-source-plugin]]
== New Open Source plugin

The following new Open Source plugin was released alongside {productname} {release-version}.

=== <Open source plugin name>

The new open source plugin, **<Open source plugin name>** // description here.

For information on the **<Open source plugin name>** plugin, see xref:<plugincode>.adoc[<Open source plugin name>].


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== Comments

The {productname} {release-version} release includes an accompanying release of the **Comments** premium plugin.

**Comments** includes the following fixes.

==== The mentions dropdown remained visible even after the mention text was deleted in quick succession.
// #TINY-11673

In previous versions of the **Comments** plugin, an issue was identified where the mentions in comments dropdown was still visible after the `@` mentioned text was removed in quick succession. 

This behavior occurred when the users list was updated following a successful API fetch request, even when the mentioned text was completely deleted.

As a result, users were unable to interact with or close the `@` mentions dropdown.

In {productname} {release-version}, the logic has been updated to ensure the users list is only refreshed if the mentioned text is not entirely removed. This change ensures that the mentions dropdown automatically closes when the `@` mentioned text is deleted.

==== The mentions menu without items was not closed when pressing Space or Enter key.
// #TINY-11454

Previously, an issue was identified where pressing the `Space` or `Enter` key when the mentions dropdown displayed the message "no users found" did not close the dropdown unlike in the editor.

This issue also caused the `Space` and `Enter` keys to be non-functional, resulting in a poor user experience.

{productname} {release-version} resolves this issue by ensuring that pressing the `Space` or `Enter` key closes the dropdown, maintaining consistent functionality between the comment text area and the editor.

==== Toggle sidebar shortcut remained active when the editor was disabled.
// #TINY-11646

Previously, an issue was identified where the comment sidebar would close when using the keyboard shortcut `Cmd + Opt + M` on Mac and `Ctrl + Alt + M` on Windows while the editor was in a disabled state.

This led to inconsistent behavior, as keyboard shortcuts remained functional despite the editor being disabled.

{productname} {release version} addresses this issue. The behavior of keyboard shortcuts has been updated to ensure that the comment sidebar shortcut is disabled when the editor is in a disabled state.

For information on the **Comments** plugin, see: xref:introduction-to-tiny-comments.adoc[Introduction to {companyname} Comments].

=== Enhanced Tables

The {productname} {release-version} release includes an accompanying release of the **Enhanced Tables** premium plugin.

**Enhanced Tables** includes the following fixes.

==== Table resize bars was not properly aligned for inline editors inside scrollable containers.
// #TINY-11215

In earlier versions of {productname}, an issue was identified in the inline mode editor where table resize bars were improperly positioned when placed within a scrollable container. When the container was scrolled, the resize bars became misaligned with the corresponding table rows and columns.

This misalignment caused a disconnect between the table rows and their associated resize handles, leading to usability challenges as the handles appeared in the incorrect location.

In {productname} {release-version}, this issue has been resolved by ensuring the table resize bars are properly attached to the respective table rows and columns when the container is scrolled, enhancing usability and functionality.

For information on the **Enhanced Table** plugin, see: xref:advtable.adoc[Enhanced Tables].

=== Image Optimizer

The {productname} {release-version} release includes an accompanying release of the **Image Optimizer** premium plugin.

**Image Optimizer** includes the following fixes.

==== Resizing images by typing into the input didn't update the `style` attribute correctly.
// TINY-11669

An issue was identified where the `data-mce-style` attribute of an image was not updated correctly when its width and height were modified via user input.

This was caused by triggering the resize function when the selection was somewhere else due to a debounce between the input and the resize, but the resize operation would be performed on the current selection.

This resulted in other editor components that contain the `data-mce-style` attribute accidentally reading outdated values, and the resize not being applied as the selection would not be on the image.

{productname} {release-version} addresses this by updating the `data-mce-style` attribute accordingly when a resize operation is performed and the resize function takes the image as a parameter. 
This ensures that all editor components that reference the `data-mce-style` attribute read the most recent value entered, and the resize operation is applied to the correct image even before the debounce time has elapsed.

For information on the **Image Optimizer** plugin, see: xref:uploadcare.adoc[Image Optimizer].

[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium plugin end-of-life announcement

The following Premium plugin has been announced as reaching its end-of-life:

=== <Premium plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Premium plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-open-source-plugin-end-of-life-announcement]]
== Accompanying open source plugin end-of-life announcement

The following open source plugin has been announced as reaching its end-of-life:

=== <Open source plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Open source plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, dand is no longer available for purchase.


[[accompanying-enhanced-skins-and-icon-packs-changes]]
== Accompanying Enhanced Skins & Icon Packs changes

The {productname} {release-version} release includes an accompanying release of the **Enhanced Skins & Icon Packs**.

=== Enhanced Skins & Icon Packs

The **Enhanced Skins & Icon Packs** release includes the following updates:

The **Enhanced Skins & Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} {release-version} skin, Oxide.

For information on using Enhanced Skins & Icon Packs, see: xref:enhanced-skins-and-icon-packs.adoc[Enhanced Skins & Icon Packs].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvement<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[additions]]
== Additions

{productname} {release-version} also includes the following addition<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[changes]]
== Changes

{productname} {release-version} also includes the following change<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} {release-version} also includes the following removal<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fix<es>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} {release-version} includes the following deprecation<s>:

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} {release-version} may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} {release-version}.

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.
