= {productname} {release-version}
:release-version: 7.7.2
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, March 19^th^, 2025. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:bug-fixes[Bug fixes]

[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fixes:

=== Error was thrown when pressing `Tab` in the last cell of a non-editable table.
// #TINY-11797

Previously in {productname}, an issue was identified where pressing `Tab` in the last cell of a non-editable table attempted to insert a new row and move the selection to it. This behavior resulted in an infinite loop. Additionally, if `Tab` was pressed in an editable cell and the next cell was a `contenteditable="false"` (`CEF`) cell, with a `contenteditable="true"` element inside, the focus would skip the `CEF` cell.

This issue also triggered error messages when pressing `Tab` in the last cell of a non-editable table, negatively impacting page performance.

{productname} {release-version} resolves this issue by refining the tab navigation behavior:

* Pressing `Tab` in the last cell of a non-editable table now has no effect.
* When `Tab` is pressed in an editable cell, and the next cell is a `CEF` cell with an editable element inside, the cursor is moved to an editable element within the `CEF` cell.

These improvements enhance table navigation, prevent unnecessary error messages, and optimize performance when working with non-editable tables.

=== Error was thrown when trying to use the context form API after a component was detached.
// #TINY-11781

Previously, an error occurred when the `setValue` function from the xref:contextform.adoc#formapi[Context Form API] was called after the toolbar had been detached from the DOM. As a result, developers were unable to retrieve the value of the Context Form when using the API after the form had been closed.

{productname} {release-version} resolves this issue by ensuring that developers can now reliably get and set the value of the Context Form even after it has been detached.

=== Deleting an empty block within an `<li>` element would move cursor to the end of the `<li>`.
// #TINY-11763

In previous versions of {productname}, an issue was identified where deleting an empty block within an `<li>` element would unexpectedly reposition the cursor at the end of the `<li>` element. Additionally, deleting an empty block located between two lists could trigger an error if all elements were nested within the same `<li>` element.

These issues led to confusing behavior, as users experienced unintended cursor movement and encountered error messages.

{productname} {release-version} resolves these issues by improving the list behavior. As a result, the cursor remains stable, and users no longer experience unexpected movements or error messages.