= {productname} {release-version}
:release-version: 7.7.2
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, bugfixes, security
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on <weekday>, <month> <DD>^<st|nd|rd|th>^, <YYYY>. These release notes provide an overview of the changes for {productname} {release-version}, including:

// Remove sections and section boilerplates as necessary.
// Pluralise as necessary or remove the placeholder plural marker.
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]

[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fixes:

=== Exception was thrown when trying to use the context form API after the toolbar was detached.
// #TINY-11781

Previously, an error occurred when the `setValue` function from the Context Form API was called after the toolbar had been detached from the DOM. As a result, developers were unable to retrieve the value of the Context Form when using the API after the form had been closed.

{productname} {release-version} resolves this issue by ensuring that developers can now reliably get and set the value of the Context Form even after it has been detached.

For more information on the Context Form API, see: xref:contextform.adoc[Context Forms]


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.