= {productname} {release-version}
:release-version: 7.8.0
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, April 02^nd^, 2025. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:new-premium-plugin<s>[New Premium plugin<s>]
* xref:new-open-source-plugin<s>[New Open Source plugin<s>]
* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:accompanying-premium-plugin-end-of-life-announcement[Accompanying Premium plugin end-of-life announcement]
* xref:accompanying-open-source-plugin-end-of-life-announcement[Accompanying open source plugin end-of-life-announcement]
* xref:accompanying-enhanced-skins-and-icon-packs-changes[Accompanying Enhanced Skins & Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[new-premium-plugin<s>]]
New Premium plugin<s>

The following new Premium plugin was released alongside {productname} {release-version}.

=== <Premium plugin name>

The new Premium plugin, **<Premium plugin name>** // description here.

For information on the **<Premium plugin name>** plugin, see xref:<plugincode>.adoc[<Premium plugin name>].


[[new-open-source-plugin]]
== New Open Source plugin

The following new Open Source plugin was released alongside {productname} {release-version}.

=== <Open source plugin name>

The new open source plugin, **<Open source plugin name>** // description here.

For information on the **<Open source plugin name>** plugin, see xref:<plugincode>.adoc[<Open source plugin name>].


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== <Premium plugin name 1> <Premium plugin name 1 version>

The {productname} {release-version} release includes an accompanying release of the **<Premium plugin name 1>** premium plugin.

**<Premium plugin name 1>** <Premium plugin name 1 version> includes the following <fixes, changes, improvements>.

==== <Premium plugin name 1 change 1>

// CCFR here.

For information on the **<Premium plugin name 1>** plugin, see: xref:<plugincode>.adoc[<Premium plugin name 1>].

=== Export to Word

The {productname} {release-version} release includes an accompanying update to the **Export to Word** premium plugin.

==== Improved handling of relative URLs using `base_url` configuration for Export to Word
// #TINY-11923

Previously, the `exportword` plugin converted relative URLs (e.g., `+/relative/url+`) into incorrect absolute URLs during export, causing hyperlinks in Word documents to direct users to unintended or non-existent destinations. This issue has been resolved. The plugin now correctly resolves relative URLs using the `base_url` configuration option, ensuring exported Word documents contain valid and functional hyperlinks.

For more information, see: xref:exportword.adoc[Export to Word].

=== Export to PDF

The {productname} {release-version} release includes an accompanying update to the **Export to PDF** premium plugin.

==== Improved handling of relative URLs using `base_url` configuration for Export to PDF
// #TINY-11923

The `exportpdf` plugin previously transformed relative URLs (e.g., `+/relative/url+`) into incorrect absolute URLs, resulting in broken or misdirected links in exported PDF documents. This issue has been addressed. The plugin now uses the `base_url` configuration option to correctly resolve relative URLs, ensuring that links in exported PDFs lead to the correct destinations.

For more information, see: xref:exportpdf.adoc[Export to PDF].

[[accompanying-premium-plugin-end-of-life-announcement]]
== Accompanying Premium plugin end-of-life announcement

The following Premium plugin has been announced as reaching its end-of-life:

=== <Premium plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Premium plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-open-source-plugin-end-of-life-announcement]]
== Accompanying open source plugin end-of-life announcement

The following open source plugin has been announced as reaching its end-of-life:

=== <Open source plugin name eol>

{productname}’s xref:<plugincode>.adoc[<Open source plugin name eol>] plugin will be deactivated on <month> <DD>, <YYYY>, and is no longer available for purchase.


[[accompanying-enhanced-skins-and-icon-packs-changes]]
== Accompanying Enhanced Skins & Icon Packs changes

The {productname} {release-version} release includes an accompanying release of the **Enhanced Skins & Icon Packs**.

=== Enhanced Skins & Icon Packs

The **Enhanced Skins & Icon Packs** release includes the following updates:

The **Enhanced Skins & Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} {release-version} skin, Oxide.

For information on using Enhanced Skins & Icon Packs, see: xref:enhanced-skins-and-icon-packs.adoc[Enhanced Skins & Icon Packs].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvement<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[additions]]
== Additions

{productname} {release-version} also includes the following addition<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[changes]]
== Changes

{productname} {release-version} also includes the following change<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} {release-version} also includes the following removal<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fix<es>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} {release-version} includes the following deprecation<s>:

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} {release-version} may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} {release-version}.

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.