= {productname} {release-version}
:release-version: 8.2.1
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Thursday, November 6^th^, 2025. These release notes provide an overview of the changes for {productname} {release-version}, including:

// Remove sections and section boilerplates as necessary.
* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:bug-fixes[Bug fixes]

== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== PowerPaste

The {productname} {release-version} release includes an accompanying release of the **PowerPaste** premium plugin.

**The PowerPaste plugin** includes the following fix.

==== Dragging an element over the editor would cause it to jump unexpectedly on some versions of Chrome with the PowerPaste plugin.
// #TINY-13196

In {productname} xref:8.2.0-release-notes.adoc#the-editor-would-upon-gaining-focus-scroll-to-the-center-of-the-editor-on-some-browsers-if-the-top-of-the-editor-was-out-of-frame[8.2.0], an issue was resolved where the editor would unexpectedly scroll in certain situations. This behavior originated from a workaround for a Chromium bug, which caused the editor to scroll when the top of the editor was out of frame.

While this issue was addressed for the core editor behavior in that release, the same problem persisted in the xref:introduction-to-powerpaste.adoc[PowerPaste] plugin, resulting in similar unexpected scrolling.

In {productname} {release-version}, this issue has now been fully resolved for PowerPaste as well. The editor no longer scrolls unexpectedly when using the PowerPaste plugin.

For information on the **PowerPaste** plugin, see: xref:introduction-to-powerpaste.adoc[PowerPaste plugin].

[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fixes:

=== Resizing the editor's height would add a fixed width value.
// #TINY-13138

Previously, an issue was identified where the editor’s width styles were overwritten when resizing the editor. This caused the width styles to break, resulting in the editor having a fixed width value instead of adapting to the container’s width.

In {productname} {release-version}, this issue has been resolved. The editor's width is no longer overwritten after resizing when the xref:editor-size-options.adoc#resize[resize option] is set to `true`. Now, resizing only affects the width when the resize option is set to `both`. This ensures that only the necessary styles are applied during editor resizing, preserving other styles and allowing the resize behavior to function as expected.

=== The Help Plugin did not contain an entry for the Full Page HTML plugin.
// #TINY-13183

Prior to the {release-version} release, the xref:fullpagehtml.adoc[Full Page HTML] plugin was not included in the plugin list displayed in the xref:help.adoc[Help plugin] dialog. This has now been corrected, and the Help plugin dialog properly lists the plugin.
