= {productname} 8.2.0
:release-version: 8.2.0
:navtitle: {productname} 8.2.0
:description: Release notes for {productname} 8.2.0
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} 8.2.0 was released for {enterpriseversion} and {cloudname} on Wednesday, October 22^nd^, 2025. These release notes provide an overview of the changes for {productname} 8.2.0, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:accompanying-enhanced-skins-and-icon-packs-changes[Accompanying Enhanced Skins & Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} 8.2.0.

=== Media Optimizer

The {productname} 8.2.0 release includes an accompanying release of the **Media Optimizer** premium plugin.

**Media Optimizer** now includes comprehensive video handling capabilities.

==== Video Upload Support

The **Media Optimizer** plugin now supports video upload and processing, extending beyond its previous image-only functionality. Users can now upload videos directly within the editor through drag-and-drop, file selection, or URL input.

The plugin now supports commonly available video formats including MP4, WebM, 3GPP, MPEG variants, QuickTime, Matroska, AVI, Flash Video, RealMedia, and other standard video formats.

This new functionality is supported with the following configuration options:

* **`uploadcare_video_properties`**: Comprehensive video player configuration including autoplay, controls, loop and more.
* **`uploadcare_video_resize`**: Option to control whether videos can be resized directly within the editor.

For information on the **Media Optimizer** plugin, see: xref:uploadcare-video.adoc[Media Optimizer: Video].

// === <Premium plugin name 1> <Premium plugin name 1 version>

// The {productname} 8.2.0 release includes an accompanying release of the **<Premium plugin name 1>** premium plugin.

// **<Premium plugin name 1>** <Premium plugin name 1 version> includes the following <fixes, changes, improvements>.

// ==== <Premium plugin name 1 change 1>
// #TINY-vwxyz1

// CCFR here.

// For information on the **<Premium plugin name 1>** plugin, see: xref:<plugincode>.adoc[<Premium plugin name 1>].


[[accompanying-enhanced-skins-and-icon-packs-changes]]
== Accompanying Enhanced Skins & Icon Packs changes

The {productname} 8.2.0 release includes an accompanying release of the **Enhanced Skins & Icon Packs**.

=== Enhanced Skins & Icon Packs

The **Enhanced Skins & Icon Packs** release includes the following updates:

The **Enhanced Skins & Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} 8.2.0 skin, Oxide.

For information on using Enhanced Skins & Icon Packs, see: xref:enhanced-skins-and-icon-packs.adoc[Enhanced Skins & Icon Packs].


[[improvements]]
== Improvements

{productname} 8.2.0 also includes the following improvement<s>:

// === <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[additions]]
== Additions

{productname} 8.2.0 also includes the following addition<s>:

// === <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[changes]]
== Changes

{productname} 8.2.0 also includes the following change<s>:

// === <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} 8.2.0 also includes the following removal<s>:

// === <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} 8.2.0 also includes the following bug fix<es>:

// === <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} 8.2.0 includes <a fix | fixes for the following security issue<s>:

// === <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} 8.2.0 includes the following deprecation<s>:

// === The `<plugin>` configuration property, `<name>`, has been deprecated
// #TINY-vwxyz1

// CCFR here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} 8.2.0 may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} 8.2.0.

// === <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.
