= {productname} {release-version}
:release-version: 8.2.1
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on <weekday>, <month> <DD>^<st|nd|rd|th>^, <YYYY>. These release notes provide an overview of the changes for {productname} {release-version}, including:

// Remove sections and section boilerplates as necessary.
* xref:bug-fixes[Bug fixes]


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fixes:

=== Resizing the editor's height would add a fixed width value.
// #TINY-13138

Previously, an issue was identified where the editor’s width styles were overwritten when resizing the editor. This caused the width styles to break, resulting in the editor having a fixed width value instead of adapting to the container’s width.

In {productname} {release-version}, this issue has been resolved. The editor's width is no longer overwritten after resizing when the xref:editor-size-options.adoc#resize[resize option] is set to `true`. Now, resizing only affects the width when the resize option is set to `both`. This ensures that only the necessary styles are applied during editor resizing, preserving other styles and allowing the resize behavior to function as expected.