= {productname} {release-version}
:release-version: 8.3.0
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, new, changes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, December 10^th^, 2025. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== Media Optimizer

The {productname} {release-version} release includes an accompanying release of the **Media Optimizer** premium plugin.

**Media Optimizer** includes the following improvements.

==== Support for uploading additional file types
// #TINY-13270

The Media Optimizer plugin now supports uploading many additional file types through the link dialog, including documents (PDF, Word, Excel, PowerPoint, RTF, plain text), iWork files (Keynote, Pages, Numbers), audio files (WAV, MP3, OGG), and archive files (ZIP, GZIP, TAR, 7Z, RAR). A full list of supported file types is available in the documentation.

The default list of supported file types can be customized using the xref:uploadcare-documents.adoc#documents-file-types[`+documents_file_types+`] option.

For information on the **Media Optimizer** plugin, see: xref:uploadcare-documents.adoc[Media Optimizer: Documents].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvements:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[additions]]
== Additions

{productname} {release-version} also includes the following additions:

=== New options `files_upload_handler`, `documents_file_types`, and `link_uploadtab`
// #TINY-13278

Added new configuration options to the Link plugin to support file uploads through the link dialog:

* xref:link.adoc#files_upload_handler[`+files_upload_handler+`] - Specifies a function that handles file uploads in the link dialog's upload tab
* xref:link.adoc#documents_file_types[`+documents_file_types+`] - Specifies which file types (MIME types and extensions) are supported for file uploads
* xref:link.adoc#link_uploadtab[`+link_uploadtab+`] - Controls whether the "Upload" tab is displayed in the link dialog

For more information, see xref:link.adoc#files_upload_handler[`+files_upload_handler+`], xref:link.adoc#documents_file_types[`+documents_file_types+`], and xref:link.adoc#link_uploadtab[`+link_uploadtab+`].

=== New options for `dropzone` dialog components
// #TINY-13278

Added new configuration options to the `dropzone` dialog component to customize the dropzone UI and file type restrictions:

* xref:dialog-components.adoc#dropzone[`+dropAreaLabel+`] - Specifies the text label for the drop area where files can be dragged (default: `+'Drop an image here'+`)
* xref:dialog-components.adoc#dropzone[`+buttonLabel+`] - Specifies the text label for the browse button (default: `+'Browse for an image'+`)
* xref:dialog-components.adoc#dropzone[`+allowedFileTypes+`] - Specifies a MIME type pattern for allowed file types (default: `+'image/*'+`, e.g., `+'image/*'+`, `+'application/pdf'+`)
* xref:dialog-components.adoc#dropzone[`+allowedFileExtensions+`] - Specifies an array of allowed file extensions (default: xref:file-image-upload.adoc#images_file_types[`+images_file_types+`], e.g., `+['.jpg', '.png', '.pdf']+`)

For more information, see xref:dialog-components.adoc#dropzone[dropzone component].


[[changes]]
== Changes

{productname} {release-version} also includes the following changes:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} {release-version} also includes the following removals:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fixes:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} {release-version} includes the following deprecation<s>:

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} {release-version} may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} {release-version}.

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.

