= {productname} {release-version}
:release-version: 8.3.2
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, January 14^th^, 2026. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:bug-fixes[Bug fix]


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== <Premium plugin name 1> <Premium plugin name 1 version>

The {productname} {release-version} release includes an accompanying release of the **<Premium plugin name 1>** premium plugin.

**<Premium plugin name 1>** <Premium plugin name 1 version> includes the following <fixes, changes, improvements>.

==== <Premium plugin name 1 change 1>

// CCFR here.

For information on the **<Premium plugin name 1>** plugin, see: xref:<plugincode>.adoc[<Premium plugin name 1>].


[[bug-fixes]]
== Bug fix

{productname} {release-version} also includes the following bug fix:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.
