= {productname} {release-version}
:release-version: 8.3.2
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, bugfixes
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, January 14^th^, 2026. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:improvements[Improvements]


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== Media Optimizer

The {productname} {release-version} release includes an accompanying release of the **Media Optimizer** premium plugin.

**Media Optimizer** includes the following improvement.

=== Placeholder loading had two progress indicators
// #TINY-13163

Uploading a video in {productname} could display two progress indicators at the same time (a spinner and a progress bar), which unnecessarily cluttered the UI and made upload status harder to interpret. In {release-version}, the upload experience was updated to display only a single progress indicator: a progress bar when the upload duration can be estimated, or a spinner when the remaining time is unknown, resulting in a cleaner and clearer interface during video uploads.

For information on the **Media Optimizer** plugin, see: xref:uploadcare.adoc[Media Optimizer].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvement:

=== Placeholder loading had two progress indicators

// TODO: add documentation
