= {productname} {release-version}
:release-version: 8.5.0
:navtitle: {productname} {release-version}
:description: Release notes for {productname} {release-version}
:keywords: releasenotes, new, changes, bugfixes, new features, improvements, changes, removals, deprecated, known issues
:page-toclevels: 1

include::partial$misc/admon-releasenotes-for-stable.adoc[]


[[overview]]
== Overview

{productname} {release-version} was released for {enterpriseversion} and {cloudname} on Wednesday, April 29^th^, 2026. These release notes provide an overview of the changes for {productname} {release-version}, including:

* xref:accompanying-premium-plugin-changes[Accompanying Premium plugin changes]
* xref:accompanying-enhanced-skins-and-icon-packs-changes[Accompanying Enhanced Skins & Icon Packs changes]
* xref:improvements[Improvements]
* xref:additions[Additions]
* xref:changes[Changes]
* xref:bug-fixes[Bug fixes]
* xref:security-fixes[Security fixes]
* xref:deprecated[Deprecated]
* xref:known-issues[Known issues]


[[accompanying-premium-plugin-changes]]
== Accompanying Premium plugin changes

The following premium plugin updates were released alongside {productname} {release-version}.

=== <Premium plugin name 1> <Premium plugin name 1 version>

The {productname} {release-version} release includes an accompanying release of the **<Premium plugin name 1>** premium plugin.

**<Premium plugin name 1>** <Premium plugin name 1 version> includes the following <fixes, changes, improvements>.

==== <Premium plugin name 1 change 1>

// CCFR here.

For information on the **<Premium plugin name 1>** plugin, see: xref:<plugincode>.adoc[<Premium plugin name 1>].

=== TinyMCE AI

The {productname} {release-version} release includes an accompanying release of the **TinyMCE AI** premium plugin.

**TinyMCE AI** includes the following fix.

==== Tab could be used to move focus between segmented button options in the preview footer
// #TINY-14161

Previously, the Tab key could be used to move focus between individual options within the segmented button in the TinyMCE AI preview mode footer. This was inconsistent with standard keyboard navigation behavior, where arrow keys should navigate between options in a segmented control and Tab should move focus to the next interactive element outside the group.

In {productname} {release-version}, the focus order in the TinyMCE AI preview footer has been corrected. The Tab key now moves focus to the next interactive element outside the segmented button, and arrow keys navigate between options within the group. This provides a more predictable and accessible keyboard navigation experience.

For information on the **TinyMCE AI** plugin, see: xref:tinymceai.adoc[TinyMCE AI].


[[accompanying-enhanced-skins-and-icon-packs-changes]]
== Accompanying Enhanced Skins & Icon Packs changes

The {productname} {release-version} release includes an accompanying release of the **Enhanced Skins & Icon Packs**.

=== Enhanced Skins & Icon Packs

The **Enhanced Skins & Icon Packs** release includes the following updates:

The **Enhanced Skins & Icon Packs** were rebuilt to pull in the changes also incorporated into the default {productname} {release-version} skin, Oxide.

For information on using Enhanced Skins & Icon Packs, see: xref:enhanced-skins-and-icon-packs.adoc[Enhanced Skins & Icon Packs].


[[improvements]]
== Improvements

{productname} {release-version} also includes the following improvement<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[additions]]
== Additions

{productname} {release-version} also includes the following addition<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[changes]]
== Changes

{productname} {release-version} also includes the following change<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[removed]]
== Removed

{productname} {release-version} also includes the following removal<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[bug-fixes]]
== Bug fixes

{productname} {release-version} also includes the following bug fix<es>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[security-fixes]]
== Security fixes

{productname} {release-version} includes <a fix | fixes for the following security issue<s>:

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.


[[deprecated]]
== Deprecated

{productname} {release-version} includes the following deprecation<s>:

=== The `<plugin>` configuration property, `<name>`, has been deprecated

// placeholder here.


[[known-issues]]
== Known issues

This section describes issues that users of {productname} {release-version} may encounter and possible workarounds for these issues.

There <is one | are <number> known issue<s> in {productname} {release-version}.

=== <TINY-vwxyz 1 changelog entry>
// #TINY-vwxyz1

// CCFR here.
