= Accessibility Checker plugin
:navtitle: Accessibility Checker
:description: Checks the contents of the editor for WCAG & Section 508 accessibility problems.
:keywords: a11y, accessibility, WCAG
:pluginname: Accessibility Checker
:plugincode: a11ychecker
:pluginminimumplan: tierthree
:includedSection: a11yPlugin


include::partial$misc/admon-premium-plugin.adoc[]

The `+a11ychecker+` premium plugin allows you to check the HTML in the editor for various WCAG & Section 508 accessibility problems. It has an auto-repair feature that lets the user fix identified problems.

== Interactive example

liveDemo::a11ychecker[]

// include::partial$misc/purchase-premium-plugins.adoc[]

== Basic setup

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `+plugins+` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'a11ychecker',
  toolbar: 'a11ycheck',
});
----

[[accessibility-rules]]
== Accessibility Rules

The following checks are available for the {pluginname} plugin. The rules checked depends on:

* The level of compliance (A, AA, or AAA), set using the `+a11ychecker_level+` option.
* The HTML version of the content, set using the `+a11ychecker_html_version+` option.

Each rule has a severity level, which will be one of the following, listed in order of increasing severity:

* Warning
* Error

[[D1]]
=== D1 - Usage of paragraphs as headings

*Rule description:* this rule checks that `+h1+`-`+h6+` tags are used for heading content, not `+p+` tags. Not using correct heading markup will make it difficult for assistive technologies to represent and navigate through your content.

==== {pluginname} rule details - D1

Notification level (severity):: Warning

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specifications::

* https://www.w3.org/WAI/WCAG21/Techniques/html/H42.html[H42 - Using h1-h6 to identify headings].
* https://www.w3.org/WAI/WCAG21/Techniques/html/H69.html[H69 - Providing heading elements at the beginning of each section of content].

[[D2]]
=== D2 - Sequential headings

*Rule description:* this rule checks that headings tags are used sequentially.

For example: A `+h1+` heading should be followed by a `+h2+` heading, not a `+h3+` heading. Using sequential headings will make it easier for assistive technology to parse your content.

==== {pluginname} rule details - D2

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/general/G141.html[G141 - Organizing a page using headings].

[[D3]]
=== D3 - Adjacent links

*Rule description:* this rule checks that links next to other links do not have the same `+href+` attribute.

For example: If an image link and a text link have the same `+href+` attribute, both elements should be in the same `+a+` element. If an image link and a text link point to the same URL but are two separate elements, it can be confusing for users of screen readers and other assistive technologies.

==== {pluginname} rule details - D3

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H2.html[H2 - Combining adjacent image and text links for the same resource].

[[D4O]]
=== D4O - Ordered list structure

*Rule description:* this rule checks that an `+ol+` element is used for ordered lists. Do not use paragraphs beginning with numbers or roman numerals instead of an `+ol+` element containing `+li+` items. This is to simplify navigation and parsing of the content for users of assistive technologies.

==== {pluginname} rule details - D4O

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H48.html[H48 - Using ol, ul and dl for lists or groups of links].

[[D4U]]
=== D4U - Unordered list structure

*Rule description:* this rule checks that a `+ul+` element is used for unordered lists. Do not use paragraphs beginning with `+*+` or `+-+` or some similar character instead of an `+ol+` element containing `+li+` items. This is to simplify navigation and parsing of the content for users of assistive technologies.

==== {pluginname} rule details - D4U

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H48.html[H48 - Using ol, ul and dl for lists or groups of links].

[[D5]]
=== D5 - Contrast ratio of the text (D5A, D5B, and D5C)

*Rule description:* this rule checks that the contrast ratio of the text is above the following values:

* When the compliance level is set to AA,
** 4.5:1 for normal text
** 3:1 for large text
* When the compliance level is set to AAA,
** 7:1 for any text

Text with a low contrast ratio is hard to read for users with impaired vision.

[[D5A]]
==== {pluginname} rule details - D5A

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level AA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/general/G145.html[G145 - Ensuring that a contrast ratio of at least 3:1 exists between text (and images of text) and background behind the text].

[[D5B]]
==== {pluginname} rule details - D5B

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level AA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/general/G18.html[G18 - Ensuring that a contrast ratio of at least 4.5:1 exists between text (and images of text) and background behind the text].

[[D5C]]
==== {pluginname} rule details - D5C

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/general/G17.html[G17 - Ensuring that a contrast ratio of at least 7:1 exists between text (and images of text) and background behind the text].

[[H93]]
=== H93 - IDs must be unique

*Rule description:* this rule checks that all `+id+` attributes are unique in the editor. Duplicate `+id+` attributes are known to cause problems for assistive technologies when parsing the content.

==== {pluginname} rule details - H93

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H93.html[H93 - Ensuring that id attributes are unique on a Web page].

[[I1]]
=== I1 - Image `+alt+` text

*Rule description:* this rule checks that all images have alternative (`+alt+`) text for screen readers and other assistive technologies.

==== {pluginname} rule details - I1

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/general/G95.html[G95 - Providing short text alternatives that provide a brief description of the non-text content].

include::partial$misc/admon-accessibility-rule-i3-can-also-be-applied.adoc[]

[[I2]]
=== I2 - Image `+alt+` text is not the image filename

*Rule description:* this rule checks that the `+alt+` attribute text of the image is not the same as the filename of the image.

==== {pluginname} rule details - I2

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/general/G95.html[G95 - Providing short text alternatives that provide a brief description of the non-text content].

include::partial$misc/admon-accessibility-rule-i3-can-also-be-applied.adoc[]

[[I3]]
=== I3 - Image `+alt+` text is not greater than 100 characters

*Rule description:* this rule checks that the `+alt+` attribute text of the image is not more than 100 characters.

An _Image alternative text should be less than 100 characters_ warning dialog presents if the alternative (`+alt+`) text is longer than 100 characters. This dialog also presents the alternative text in an editable field, for immediate repair.

==== {pluginname} rule details - I3

Notification level (severity):: Warning

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: n/a.

include::partial$misc/admon-requires-6.3v.adoc[]


[[T1]]
=== T1 - Table caption

*Rule description:* this rule checks that all `+table+` elements have a `+caption+` element describing the data inside the table to simplify parsing and navigation of the content for users of assistive technologies.

==== {pluginname} rule details - T1

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H39.html[H39 - Using caption elements to associate data table captions with data tables].

[[T2]]
=== T2 - Complex table summary

*Rule description:* this rule checks that all complex tables must have a `+summary+` attribute explaining to users of assistive technologies how to navigate through the data inside of the table.

[NOTE]
====
This rule only applies to HTML 4 content and is not checked when `+a11ychecker_html_version+` is set to `+html5+`.
====

==== {pluginname} rule details - T2

Notification level (severity):: Warning

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H73.html[H73 - Using the summary attribute of the table element to give an overview of data tables].

[[T3]]
=== T3 - Table caption and summary

*Rule description:* this rule checks that the table caption and summary does not have the same text content. The caption should explain *what* the table is about while the summary should explain *how* to navigate the data inside of the table.

[NOTE]
====
The table `+summary+` attribute was deprecated in HTML 5, both the *what* and *how* information should be moved to the table caption.
====

==== {pluginname} rule details - T3

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H73.html[H73 - Using the summary attribute of the table element to give an overview of data tables].

[[T4A]]
=== T4A - Table markup

*Rule description:* this rule checks that all `+tables+` contain both `+tr+` and `+td+` elements.

==== {pluginname} rule details - T4A

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H51.html[H51 - Using table markup to present tabular information].

[[T4B]]
=== T4B - Table headers

*Rule description:* this rule checks that all `+table+` elements contain at least one table header (`+th+`) element.

==== {pluginname} rule details - T4B

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H51.html[H51 - Using table markup to present tabular information].

[[T4C]]
=== T4C - Table heading scope

*Rule description:* this rule checks that all table header (`+th+`) elements have a `+scope+` attribute clarifying what scope the heading has inside of the `+table+`. The allowed values are `+row+`, `+col+`, `+rowgroup+`, and `+colgroup+`. This is important for users of assistive technologies to be able to parse table data.

==== {pluginname} rule details - T4C

Notification level (severity):: Error

https://www.w3.org/TR/WCAG21/#conformance[WCAG level]:: Level A ; Level AA ; Level AAA

xref:a11ychecker_html_version[HTML version]:: HTML4 and HTML5

WCAG 2.1 specification:: https://www.w3.org/WAI/WCAG21/Techniques/html/H63.html[H63 - Using the scope attribute to associate header cells and data cells in data tables].

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/a11y_advanced_options.adoc[leveloffset=+1]

include::partial$configuration/a11ychecker_allow_decorative_images.adoc[leveloffset=+1]

include::partial$configuration/a11ychecker_filter_issue.adoc[leveloffset=+1]

include::partial$configuration/a11ychecker_html_version.adoc[leveloffset=+1]

include::partial$configuration/a11ychecker_ignored_rules.adoc[leveloffset=+1]

include::partial$configuration/a11ychecker_issue_url_callback.adoc[leveloffset=+1]

include::partial$configuration/a11ychecker_level.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

[[events]]
== Events

The {pluginname} plugin provides the following events.

include::partial$events/a11ychecker-events.adoc[]

== APIs

The {pluginname} plugin provides the following APIs.

[[toggleaudit]]
=== `+toggleaudit()+`

Opens and closes the accessibility checker dialog with the results of the audit and options to correct the problems, if any.

==== Example: using `+toggleaudit()+`

[source,js]
----
tinymce.activeEditor.plugins.a11ychecker.toggleaudit();
----

[[getreport]]
=== `+getReport()+`

Conducts an accessibility audit and reports the results without opening the dialog. The report produced is an array of objects, where each object represents an xref:a11ychecker.adoc#issue[issue].

==== Example: using `+getReport()+`

[source,js]
----
const issues = tinymce.activeEditor.plugins.a11ychecker.getReport();

console.log(issues);

// example result
[
  {
    "contentID": "<div id=\"accessibility-issue__contentID\"><span>Text:&nbsp;</span><span>\"H5\"</span></div>",
    "description": "Headings must be applied in sequential order. For example: Heading 1 should be followed by Heading 2, not Heading 3.",
    "element": [object],  // The element value contains the DOM element (such as <h4>).
    "id": "D2",
    "severity": "error",
    "url": "https://www.w3.org/WAI/WCAG21/Techniques/general/G141.html",
  },
  {
    "contentID": "<div id=\"accessibility-issue__contentID\"><span>Table:&nbsp;</span><span>\"2x2\"</span></div>",
    "description": "Tables must have captions",
    "element": [object],  // The element value contains the DOM element (such as <table>).
    "id": "T1",
    "severity": "error",
    "url": "https://www.w3.org/WAI/WCAG21/Techniques/html/H39.html",
  }
]
----

[[issue]]
=== The `+issue+` object

In a11ychecker, when the content within the editor is `audited`, each element is checked to ensure that no xref:a11ychecker.adoc#accessibility-rules[Accessibility rules] are violated. Any element which doesn't adhere to a rule will generate an `issue` within the audit; the details of which are to be displayed in the a11ychecker dialog.

The `+'issue'+` object provides relevant data pertaining to any issue generated by an element which violates an xref:a11ychecker.adoc#accessibility-rules[Accessibility rule]:

* `+id+` : `+String+` A11ychecker issue identifier used by {productname}, such as D1, T4A. For a description and other details about the issue, see xref:accessibility-rules[Accessibility Rules].

* `+description+` : `+String+` description of the issue; as will be displayed in the dialog.

* `+severity+` : `+String+` severity level of the issue; either `+warning+` or `+error+`.

* `+url+` : `+String+` URL reference for the issue. By default, this will be a link to the W3 website, containing the W3 WCAG technique that needs to be addressed to clear the issue.

* `+element+` : `+Object+` DOM element where the issue was found.

* `+contentID+` : `+String+` A short snippet of the content (such as text, image, or table) where the issue was found.
