= Accordion plugin
:navtitle: Accordion
:description: <What does this plugin do? What is the benefit? (One sentence description)>.
:description_short: <Like description, but shorter (if possible)>.
:keywords: plugin, accordion, etc.
:pluginname: Accordion
:plugincode: accordion
:plugincategory: opensource

The Accordion plugin allows for the creation of collapsible sections in a document that can be expanded or collapsed to show or hide additional content.

== Interactive example

liveDemo::{plugincode}[]

== Basic setup

To add the {pluginname} plugin to the editor, add `+{plugincode}+` to the `+plugins+` option in the editor configuration.

To add the {pluginname} toolbar icon to the {productname} toolbar, add `+{plugincode}+` to the `+toolbar+` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: '{plugincode}',
  toolbar: '{plugincode}',
});
----

////

Delete everything not require/relevant from this point on.

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

There should be a template to help you create these configuration option/settings "chunks".
Just include as per the below example.
include::partial$configuration/<setting-name-in-hyphen-case>.adoc[]

Toolbar buttons content, uses the pluginname and plugincode variables.
The toolbar buttons are the same as another plugin, assign the other plugin's identifier to `altplugincode`
Don’t forget to add this to available-toolbar-buttons.adoc
include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

Menu items content, uses the pluginname and plugincode variables.
The menu items are the same as another plugin, assign the other plugin's identifier to `altplugincode`
Don’t forget to add this to available-menu-items.adoc
include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {{pluginname}} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]

== APIs

The {{pluginname}} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]

////
