= Advanced Template plugin
:navtitle: Advanced Template
:description: <What does this plugin do? What is the benefit? (One sentence description)>.
:description_short: <Like description, but shorter (if possible)>.
:keywords: plugin, advanced template, templates, advtemplate.
:pluginname: Advanced Template
:plugincode: advtemplate
:plugincategory: premium

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-requires-6.4v.adoc[]

// Add an introduction. What does the plugin do? Why would I use this plugin? Keep it concise.

== Interactive example

liveDemo::{plugincode}[]

== Basic setup

To setup the {pluginname} plugin in the editor

* add `{plugincode}` to the `plugins` option in the editor configuration;

* add `inserttemplate` and `addtemplate` to the `toolbar` option in the editor configuration;

* add the templates to use in the editor instance as a `const` declaration; and

* add the `const` name to the initialisation script.

For example:

[source,js]
----
const advtemplate_templates = [
  {
    id: '1',
    title: 'Numbered templates',
    items: [
      {
        id: '2',
        title: 'Template 01',
        content: '<p><strong>Template 01</strong> contents.</p>'
      },
      {
        id: '3',
        title: 'Template 02',
        content: '<p><strong>Template 02</strong> contents.</p>'
      },
      {
        id: '6',
        title: 'Template 03',
        content: '<p><strong>Template 03</strong> contents.</p>'
      }
    ]
  },
  {
    id: '4',
    title: 'Lettered templates',
    items: [
      {
        id: '7',
        title: 'Template A',
        content: '<p><strong>Template A</strong> contents.</p>'
      },
      {
        id: '8',
        title: 'Template B',
        content: '<p><strong>Template B</strong> contents.</p>'
      },
      {
        id: '9',
        title: 'Template C',
        content: '<p><strong>Template C</strong> contents.</p>'
      },
    ]
  },
];

tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'advtemplate',
  toolbar: 'inserttemplate addtemplate',
	advtemplate_templates,
});
----








// Delete everything not require/relevant from this point on.

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

////
  There should be a template to help you create these configuration option/settings "chunks".
  Just include as per the below example.
////
include::partial$configuration/<setting-name-in-hyphen-case>.adoc[]

////
  Toolbar buttons content, uses the pluginname and plugincode variables.
  The toolbar buttons are the same as another plugin, assign the other plugin's identifier to `altplugincode`
  Don't forget to add this to available-toolbar-buttons.md
////
include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]
////
  Menu items content, uses the pluginname and plugincode variables.
  The menu items are the same as another plugin, assign the other plugin's identifier to `altplugincode`
  Don't forget to add this to available-menu-items.md
////
include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {{pluginname}} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]

== APIs

The {{pluginname}} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]
