= Advanced Template plugin
:navtitle: Advanced Template
:description: Create and edit complex templates in {productname} for use with {productname}.
:description_short: Create templates.
:keywords: plugin, advanced template, templates, advtemplate.
:pluginname: Advanced Template
:plugincode: advtemplate
:plugincategory: premium

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-requires-6.4v.adoc[]

The {pluginname} Premium plugin enables the creation of complex, interactive templates using {productname}.

They can also be added to a {productname} instance by end-users selecting content in a {productname} document and saving the selection as a template via the {productname} user-interface.

IMPORTANT: This initial {pluginname} release does not support template editing. To update a particular template; insert the template into an editor; make edits; select the, now edited, content; and then create a new template (using, for example, the *Tools > Save as Template…* menu item).

There are two approaches to using the Advanced Template Premium plugin:

. _Fixed Template List._
For users who work with a fixed template list that does not require modification, you can provide the list directly through the editor init configuration using the xref:advtemplate_templates[`+advtemplate_templates+` option]. Please refer to this interactive xref:#predifined-list-config-example[example] for guidance on this approach.

. _User-Modifiable Template List._
If the template list is intended to be modified by the user, the plugin should be configured with functional options to enable communication with a remote template storage service. Please refer to this interactive xref:#remote-config-example[example] for guidance on configuring the plugin to support user-modifiable template lists.

== Interactive examples
[[remote-config-example]]
=== Configuring the Advanced Template plugin to interact with a remote backend service via REST API.
liveDemo::{plugincode}[]

[[predifined-list-config-example]]
=== Configuring the Advanced Template plugin to use a static list of predefined templates.
liveDemo::{plugincode}-predefined[]

== Basic setup

To setup the {pluginname} plugin user-interface in the editor

* add `{plugincode}` to the `plugins` option in the editor configuration;

* add `inserttemplate` and `addtemplate` to the `toolbar` option in the editor configuration;

* add each {pluginname} option to the editor configuration;

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  plugins: "advtemplate",
  toolbar: "inserttemplate addtemplate",
  contextmenu: "advtemplate",
  // Each of the following options should be defined as
  // a function that returns a Promise.
  // Please find the specific details for each option below.
  advtemplate_list,
  advtemplate_get_template,
  advtemplate_create_category,
  advtemplate_create_template,
  advtemplate_rename_category,
  advtemplate_rename_template,
  advtemplate_delete_template,
  advtemplate_delete_category,
  advtemplate_move_template,
  advtemplate_move_category_items
});
----

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/advtemplate_templates.adoc[]

include::partial$configuration/advtemplate_list.adoc[]

include::partial$configuration/advtemplate_get_template.adoc[]

include::partial$configuration/advtemplate_create_category.adoc[]

include::partial$configuration/advtemplate_create_template.adoc[]

include::partial$configuration/advtemplate_rename_category.adoc[]

include::partial$configuration/advtemplate_rename_template.adoc[]

include::partial$configuration/advtemplate_delete_template.adoc[]

include::partial$configuration/advtemplate_delete_category.adoc[]

include::partial$configuration/advtemplate_move_template.adoc[]

include::partial$configuration/advtemplate_move_category_items.adoc[]


include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]
