= Enhanced Code Editor plugin
:navtitle: Enhanced Code Editor
:description: How to setup TinyMCE's Enhanced Code Editor plugin.
:keywords: code, advcode, codemirror
:pluginname: Enhanced Code Editor
:plugincode: advcode
:altplugincode: code
:pluginminimumplan: tiertwo

include::partial$misc/admon-premium-plugin.adoc[]

[TIP]
As of {productname} 7.0, the Advanced Code Editor plugin has been renamed to {pluginname}. When adding {pluginname} in your editor, continue to use {plugincode}.

The xref:advcode.adoc[Enhanced Code Editor] plugin (`+advcode+`) brings a more Enhanced Code Editor to {productname}. This code editor makes it easier to modify the HTML, and is a useful add-on for power users. It comes with features often found in IDEs, all enabled by default:

* Syntax color highlighting.
* Bracket matching.
* Code folding.
* Multiple selections/carets.
* Search and Replace.
* Dark or light mode button for code display.
* Increase and decrease display font size buttons.
* Full-screen mode button.

NOTE: For the {pluginname} to offer a full-screen mode requires the xref:fullscreen.adoc[Full screen] plugin and requires {pluginname} to be running in xref:advcode.adoc#advcode_inline[inline mode].

== The difference between the Code and Enhanced Code Editor plugins

liveDemo::advcode[]

// include::partial$misc/purchase-premium-plugins.adoc[]

== Example: basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'advcode',
  toolbar: 'code'
});
----

== Example: enable the {pluginname} full-screen mode button

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  advcode_inline: true,
  plugins: [
    "fullscreen", "advcode",
  ],
  toolbar: "code"
});
----

include::partial$misc/code-dialog-and-selection-state.adoc[]

include::partial$configuration/advcode.adoc[]

include::partial$misc/advcode-shortcuts.adoc[]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} command.

include::partial$commands/code-cmds.adoc[]
