= Installing {productname} with Bower
:navtitle: Bower projects
:description: Learn how to install {productname} using Bower.
:keywords: bower, javascript, install

IMPORTANT: Bower has been deprecated. The Bower team recommends migrating toNPMor Yarn for new projects. For more information, see the link:https://bower.io/blog/2017/how-to-migrate-away-from-bower/[official Bower migration guide].

== Install {productname} using Bower

{productname} {productmajorversion} is a powerful and flexible rich text editor that can be embedded in web applications. This quick start covers how to add a {productname} editor to a web page using Bower.

To add {productname} to a Bower project, run the following on a command line:

[source,sh,subs="attributes+"]
----
bower install tinymce#^{productmajorversion}
----

The location of the main {productname} script will be: `+bower_components/tinymce/tinymce.min.js+`. Ensure the `+tinymce+` directory containing the `+tinymce.min.js+` file is accessible for the target page or application by either:

* Using a webserver route, or
* Copying the `+tinymce+` directory to a public folder using a build tool such as Gulp or Webpack.

== Include the {productname} script

Include the following line of code in the `+<head>+` of an HTML page:

[source,html,subs="attributes+"]
----
<script src="/path/or/uri/to/tinymce.min.js" referrerpolicy="origin" crossorigin="anonymous"></script>
----

== Initialize {productname} as part of a web form

include::partial$install/initialize-editor-self-hosted.adoc[]

Adding this content to an HTML file and opening it in a web browser will load a {productname} editor, such as:

liveDemo::default[]

include::partial$install/save-content.adoc[]

include::partial$misc/quickstart-next-steps.adoc[]
