= Bundling the User Interface localizations for {productname}
:navtitle: UI localizations
:description_short: Information on bundling User Interface localizations
:description: Information on bundling User Interface localizations

== Overview

* xref:using-community-localizations[Using community localizations]
* xref:using-premium-self-hosted-localizations[Using premium self-hosted localizations]

[[using-community-localizations]]
== Using community localizations

:forModuleLoaders: true
include::partial$misc/using-community-lang-packs.adoc[leveloffset=+1]
:forModuleLoaders: false

[[using-premium-self-hosted-localizations]]
== Using premium self-hosted localizations

:editorcomponent: localization
include::partial$module-loading/bundling-ref-example.adoc[leveloffset=+1]
:!editorcomponent:

Premium language packs are available from ZIP downloads or the `+tinymce-premium+` NPM package. When using the NPM package, import language packs from `+tinymce-premium/langs/+` instead of `+tinymce/langs/+`.

The following table shows examples of the syntax used to bundle the following example localization file:

....
./langs/sv_SE.js
....

[cols='1,1,4']
|===
|Module Syntax |Source |Example

.2+|ES6+
|npm (community)
a|
[source, js]
----
import 'tinymce/langs/sv_SE';
----

|npm (premium)
a|
[source, js]
----
import 'tinymce-premium/langs/sv_SE';
----

|`.zip`
a|
[source, js]
----
import '../tinymce/langs/sv_SE';
----

.2+|Common JS
|npm (community)
a|
[source, js]
----
require('tinymce/langs/sv_SE');
----

|npm (premium)
a|
[source, js]
----
require('tinymce-premium/langs/sv_SE');
----

|`.zip`
a|
[source, js]
----
require('../tinymce/langs/sv_SE.js');
----
|===

[NOTE]
====
For complete information on using premium language packs from the NPM package, including non-bundling approaches, see: xref:ui-localization.adoc#premium-language-packs-npm[Providing premium language packs from `+tinymce-premium+`].
====

:forModuleLoaders: true
include::partial$misc/ui-languages.adoc[leveloffset=+1]
:forModuleLoaders: false
