= Changelog
:description: The history of {productname} releases.
:keywords: changelog

NOTE: This is the {productname} Community version changelog. For information about the latest {cloudname} or {enterpriseversion} Release, see: xref:release-notes.adoc[{productname} Release Notes].

== xref:8.2.0-release-notes.adoc[8.2.0 - 2025-10-23]

### Improved
* Some elements would be given an extra newline by the serializer when indented.
// #TINY-12857

### Fixed
* UI elements like focus outlines and placeholders would be visible after printing.
// #TINY-12584
* The `open` attribute on `<details>` elements is now normalized to `open="open"` when the accordion plugin is enabled. 
//#TINY-12862
* Tooltips on toolbar buttons sometimes remained visible if the button icon was updated while hovered.
// #TINY-12289
* The editor would upon gaining focus scroll to the center of the editor on some browsers if the top of the editor was out of frame.
// #TINY-12626
* Some UI elements related to dragging elements were not properly filtered out when fetching content.
// #TINY-12384
* The cursor could get stuck around an absolute CEF element when navigating using arrow keys.
// #TINY-10526
* The schema will now allow the `property` RDFa attribute on `meta` elements.
// #TINY-12858
* Corrected type of `undoManager.add` method. The `event` parameter is type `EditorEvent` not `Event`.
// #TINY-12936
* Chromium browsers would in certain situations scroll the editor unexpectedly when dragging content over the editor.
// #INT-3373
* Support for setting component urls for custom elements.
// #TINY-13006
* Reverted toolbar button width to `auto`.
// #TINY-13097
* Addressed split buttons rendering narrower than in {productname} 7, ensuring consistent sizing across the toolbar.
// #TINY-13111

== xref:8.1.2-release-notes.adoc[8.1.2 - 2025-09-18]

### Fixed
* Sidebar UI for comments was not rendering correctly.
// #TINY-12925

== xref:8.1.1-release-notes.adoc[8.1.1 - 2025-09-17]

### Fixed
* Reset rules for CSS were not applying correctly.
// #TINY-12920

== xref:8.1.0-release-notes.adoc[8.1.0 - 2025-09-17]

### Improved
* The editor `DomParser` API can now parse full documents when the API's `root_name` option is set to `#document`.
// #TINY-12589
* Tooltips can be hovered over to keep open.
// #TINY-12053
* Default avatars are now generated with a consistent color based on the user id.
// #TINY-12532
* Reverted split button design change.
// #TINY-12593
* `editor.getContent()` now includes `indent` and `entity_encoding` properties to control HTML formatting.
// #TINY-12786

### Deprecated
* Deprecated `content_css_cors` config option.
// #TINY-12578

### Fixed
* Clicking on a non selectable element when the selection is off screen no longer scrolls to the selection.
// #TINY-12245
* Using CMD+backspace would not preserve inline formatting.
// #TINY-12071
* Navigating between elements with `contenteditable="true"` was not possible on Firefox using the keyboard.
// #TINY-12459
* NVDA would announce `iframe_aria_text` multiple times.
// #TINY-11296
* Cursor movement did not operate correctly after a `figure` was selected.
// #TINY-12458
* Links inserted with `+&amp;+` encoding are now decoded to `&` before inserting.
// #TINY-12504
* Attribute `aria-errormessage` was incorrectly added to url input fields by default.
// #TINY-12037
* Splitting list items by pressing enter did not move the cursor due to an error in the browser console.
// #TINY-12830

== xref:8.0.2-release-notes.adoc[8.0.2 - 2025-08-14]

[NOTE]
====
In {productname} 8.0.1, the `licensekeymanager` plugin was missing from some available bundles. {productname} 8.0.2 corrects this by including the `licensekeymanager` plugin in all available bundles.

**Workaround for 8.0.1 users:** If you are using a bundle that is missing the `licensekeymanager` plugin, you can download the plugin separately and manually add it to your plugins folder. Contact your account manager or support for assistance in obtaining the separate `licensekeymanager` plugin download.
====

### Fixed
* Reverted split button design change.
// #TINY-12593

== xref:8.0.1-release-notes.adoc[8.0.1 - 2025-07-28]

[NOTE]
No new features or changes were introduced in this patch release. It contains missing changelogs from the link:https://download.tiny.cloud/tinymce/community/tinymce_8.0.0.zip[community/tinymce_8.0.0.zip] file only.

### Fixed
*  Updated missing changelogs.
// #TINY-12581

== xref:8.0-release-notes.adoc[8.0.0 - 2025-07-23]

[NOTE]
====
*Breaking Change in {productname} 8.0.0*: Users upgrading to {productname} {productmajorversion} with self-hosted commercial deployments must contact their account manager **to obtain new `T8LK:` prefixed license keys**. {productname} 7 license keys are not compatible with {productname} {productmajorversion} and cannot be modified to work by adding the `T8LK:` prefix. Cloud users ({cloudname}) are **not affected** as the commercial license is automatically applied. For complete details on the new license system and upgrade process, see: xref:license-key.adoc[License key configuration].
====

### Added
* Support for TinyMCE 8 xref:license-key.adoc[license keys] and license key manager.
// #TINY-12001
* New `pageUid` property on the `tinymce` global instance.
// #TINY-12021
* New `editorUid` property on editor instances.
// #TINY-12021
* New `UserLookup` API to provide consistent user management and fetching/caching user information across TinyMCE plugins.
// #TINY-11974
* New toolbar icons for suggested edits plugin.
// #TINY-12070
* New `crossorigin` option that sets the `crossorigin` attribute on scripts loaded by the editor.
// #TINY-12228
* New `allow_html_in_comments` option to allow HTML like contents inside comment data.
// #TINY-12220
* New `list_max_depth` option that limits the maximum list indent depth.
// #TINY-11937

### Improved
* Focus is now restored to a dialog after closing an alert, confirmation or another dialog.
// #TINY-12038
* Resize handles are more accessible with `role` and `aria-valuetext` attributes.
// #TINY-11421
* Toolbar drawer now closes when the editor loses focus.
// #TINY-12125
* The `translate` API now automatically replaces three dots in a row with an ellipsis character.
// #TINY-12155
* Tooltips can now be closed by pressing the escape key.
// #TINY-12054
* Instructions on how to navigate the color swatch, image select and insert table widget are now announced by the screen readers.
// #TINY-12189
* When `editor.resetContent()` is used, the resulting `SetContent` event now has the `initial` flag set in the event arguments.
// #TINY-12146
* Updated Image plugin decorative image check to align with accessibility standard.
// #TINY-12545

### Changed
* DomParser no longer tries to fix some nodes when parsed with a context.
// #TINY-11927
* Split buttons are now rendered as separate action and chevron buttons.
// #TINY-8665
* Moved essential parts of the `lists` plugin into core.
// #TINY-12121
* Cut action now uses the editor delete implementation instead of the native `execCommand('Delete')` function.
// #TINY-12171
* Comments with HTML like content, attributes with HTML like values, elements with HTML Comment like textContent are no longer retained while content sanitization is active.
// #TINY-12056
* Added space to promotion message for ease of reading.
// #TINY-12271
* Added deprecation console warning to `fire()` method.
// #TINY-12012

### Deprecated
* Deprecated `skipFocus` option for ToggleToolbarDrawer command. To skip focus use `skip_focus` option.
// #TINY-12044
* Deprecated 'editor.selection.setContent' method.
// #TINY-11692
* Deprecated `fire()` method for event handling. Use `dispatch()` instead. The `fire()` method will be removed in TinyMCE 9.
// #TINY-12012

### Removed
* Removed undocumented `documentBaseUrl` property from `Editor` instances. `documentBaseURI` is the supported property.
// #TINY-12182

### Fixed
* Long tooltips could overflow narrow browser windows.
// #TINY-11884
* Pressing Tab to create a new row in tables with a non-editable final row would freeze the editor.
// #TINY-12018
* Fixed an issue where the context form API `onSetup` was referencing the incorrect element.
// #TINY-11912
* Attempting to add a newline directly after a block element such as an image would cause an error.
// #TINY-12045
* It wasn't possible to navigate out of a `figcaption` using the left and right arrow keys in Firefox.
// #TINY-11982
* Nested font sizes were causing too much spacing between lines.
// #TINY-12073
* New list item was not inserted correctly when existing list item had a block element inside.
// #TINY-12102
* Deleting a whole element would sometimes replace the tag name of adjacent content.
// #TINY-11868
* HTML schema did not treat `colgroup` or `col` elements as block elements.
// #TINY-12092
* Inserting HTML fragments with invalid contents now retains more of the structure.
// #TINY-11927
* The `contextform` subtoolbar is no longer dismissed when using the toolbar back button in inline editors.
// #TINY-12118
* Tabbing when a `figure` was selected didn't move the selection on the `figcaption` correctly.
// #TINY-11753
* Strikethrough format could be added outside font size format, which renders incorrectly in some browsers.
// #TINY-12004
* Using arrow navigation between buttons when a button had the mouse over could stop the navigation.
// #TINY-12163
* Codesample dialog would not disable spellcheck as expected.
// #TINY-12120
* Cutting a whole HTML element would add an empty paragraph.
// #TINY-12171
* Added better support for template elements.
// #TINY-12157
* Tooltips no longer show above editor views.
// #TINY-12289
* `onboarding` plugin overlay now shows above popups.
// #TINY-12522