= Quick start: {productname} from {cloudname}
:navtitle: Quick start: Cloud
:description_short: Setup a basic {productname} {productmajorversion} editor using the {cloudname}.
:description: Get an instance of {productname} {productmajorversion} up and running using the {cloudname}. Initialize the editor on a textarea element using its ID with tinymce.init and the selector option.
:keywords: tinymce, script, textarea, selector, id, #mytextarea, tinymce.init, initialize, quick start
:productSource: cloud


{productname} {productmajorversion} is a powerful and flexible rich text editor that can be embedded in web applications. This quick start covers how to add a {productname} editor to a web page using the {cloudname}.

include::partial$misc/admon-account-creation-and-social-option.adoc[]

== Include the {productname} script

Include the following script tag in the `+<head>+` of a HTML file:

[source,html,subs="attributes+"]
----
<script src="{cdnurl}" referrerpolicy="origin" crossorigin="anonymous"></script>
----

== Initialize {productname}

include::partial$install/initialize-editor-cloud.adoc[]

Adding this content to the HTML file and opening it in a web browser will load a {productname} editor, such as:

liveDemo::default[]

== Update the "no-api-key" placeholder

Update the `+no-api-key+` placeholder in the source script URL (`+<script src=https://.../no-api-key/tinymce/{productmajorversion}/tinymce.min.js+/>`) with your {cloudname} API key, which is created when signing up to the link:{accountsignup}/[{cloudname}].

Providing a valid API key also removes the notice:

[WARNING]
====
**This domain is not registered with {cloudname}. Please see the quick start guide or create an account.**
====

Signing up for a {cloudname} API key will also provide a trial of the xref:plugins.adoc#premium-plugins[Premium Plugins].

include::partial$install/save-content.adoc[]

include::partial$misc/quickstart-next-steps.adoc[]
