= Spelling service settings

:description: Configuration options for the Spelling premium server-side component.

The following settings for the Spelling premium server-side component are optional. These settings should be added to the `+application.conf+` file described in xref:configure-required-services.adoc[Required configuration for the server-side components].

[[spelling]]
== `+spelling+` (optional)

The Spelling service has these configurable settings:

* `+hunspell-dictionaries-path+`
* `+custom-dictionaries-path+`
* `+dynamic-custom-dictionaries+`

[[hunspell-dictionaries-path]]
=== `+hunspell-dictionaries-path+` (optional)

include::partial$misc/hunspell-dictionaries-path.adoc[]

=== `+custom-dictionaries-path+` (optional)

For information on creating custom dictionaries, see: xref:custom-dictionaries-for-tiny-spellchecker.adoc#creatingcustomdictionaryfiles[Adding custom dictionaries - Creating custom dictionary files].

include::partial$misc/custom-dictionaries-path.adoc[]

[[dynamic-custom-dictionaries]]
=== `+dynamic-custom-dictionaries+` (optional)

include::partial$misc/dynamic-custom-dictionaries.adoc[]
