= Content localization options
:navtitle: Localization
:description_short: Localize TinyMCE for your language, including directionality.
:description: These settings configure TinyMCE's language capabilities, including right-to-left support.

== Setting the language on content

include::partial$configuration/content_langs.adoc[leveloffset=+1]

== Setting the language options for Spell Checker

To set the default language for Spell Checker plugin, see: xref:introduction-to-tiny-spellchecker.adoc#spellchecker_language[The Spell Checker plugin - `+spellchecker_language+`].

To customize the list of spell checking languages available to your users through the Spell Checker plugin, see: xref:introduction-to-tiny-spellchecker.adoc#spellchecker_languages[The Spell Checker plugin - `+spellchecker_languages+`].

== Changing the default text direction of content

include::partial$configuration/directionality.adoc[leveloffset=+1]

== Allow users to change the text direction of content

To allow your users to change the text direction of content as needed, add the toolbar buttons provided by xref:directionality.adoc[The Directionality plugin].
