= Content localization options

:title_nav: Localization :description_short: Localize TinyMCE for your language, including directionality. :description: These settings configure TinyMCE's language capabilities, including right-to-left support.

== Setting the language on content

#\{% include configuration/content_langs.md %}

== Setting the language options for Spell Checker Pro

To set the default language for Spell Checker Pro plugin, see: link:{{site.baseurl}}/plugins-ref/premium/tinymcespellchecker/#spellchecker_language[The Spell Checker Pro plugin - `+spellchecker_language+`].

To customize the list of spell checking languages available to your users through the Spell Checker Pro plugin, see: link:{{site.baseurl}}/plugins-ref/premium/tinymcespellchecker/#spellchecker_languages[The Spell Checker Pro plugin - `+spellchecker_languages+`].

== Changing the default text direction of content

#\{% include configuration/directionality.md %}

== Allow users to change the text direction of content

To allow your users to change the text direction of content as needed, add the toolbar buttons provided by link:{{site.baseurl}}/plugins-ref/opensource/directionality/[The Directionality plugin].
