= Copy & paste options

:title_nav: Copy and paste options
:description: TinyMCE copy and paste

== {productname} PowerPaste plugin

{productname} has built-in paste functionality, however PowerPaste is a premium plugin that provides improved paste support, including support for Microsoft Word, Microsoft Excel and Google Docs content. It also includes the option to clean or merge the styles when pasting content into the editor.

For information, see the xref:introduction-to-powerpaste.adoc[PowerPaste plugin].

IMPORTANT: The core paste functionality and PowerPaste share many options, although some have minor differences. The following options apply specifically to the core paste functionality. For example, the `paste_block_drop`, `paste_data_images`, `paste_remove_styles_if_webkit`, and `paste_webkit_styles` options are specific to the core functionality and do not apply to the PowerPaste plugin.

== Controlling how content is pasted

These options affect the way HTML content is processed when pasted in to the editor.

include::partial$configuration/paste_as_text.adoc[leveloffset=+1]

include::partial$configuration/paste_block_drop.adoc[leveloffset=+1]

include::partial$configuration/paste_merge_formats.adoc[leveloffset=+1]

include::partial$configuration/paste_tab_spaces.adoc[leveloffset=+1]

include::partial$configuration/smart_paste.adoc[leveloffset=+1]

== Filtering pasted content

These options control how the HTML content is filtered such that the content is eliminated or preserved when pasted into the editor.

include::partial$configuration/paste_data_images.adoc[leveloffset=+1]

include::partial$configuration/paste_preprocess.adoc[leveloffset=+1]

include::partial$configuration/paste_postprocess.adoc[leveloffset=+1]

include::partial$configuration/paste_remove_styles_if_webkit.adoc[leveloffset=+1]

include::partial$configuration/paste_webkit_styles.adoc[leveloffset=+1]