= Create an icon pack for {productname}
:navtitle: Create an icon pack
:description_short: Introducing icon pack creation.
:description: How to create a custom icon pack.
:keywords: create, creator, icon

== Overview

This guide provides comprehensive coverage of creating, building, and deploying custom icon packs, including solutions to common issues. It details two approaches:

* The inline approach, for adding a small number of custom icons
* The icon file approach, using the Icon Pack Template project to easily generate the required output file from a folder of SVGs.

== How Icons Work in {productname}

A {productname} icon pack is a JavaScript construct containing strings of link:https://developer.mozilla.org/en-US/docs/Web/SVG[SVG's]. Icon packs are often kept in separate files, but can be inlined if needed. An icon pack can be used to add one or more custom icons or to replace some or all of the default {productname} icons.

An icon pack only **requires** the custom icons to be included; the default {productname} icons are used as a fallback for icons missing from the custom icon pack.

== Registering an icon pack

Icon packs are registered with {productname} using the IconManager. Whether creating the icon pack manually or using the Icon Pack Template tool, the JavaScript required to setup an icon pack looks like:

[source,javascript]
----
tinymce.IconManager.add('custom-pack-name', {
  icons: {
    'bold': '<svg width="24" height="24">...</svg>', 
    'italic': '<svg width="24" height="24">...</svg>',
    'custom-icon': '<svg width="24" height="24">...</svg>',
    // ... more icons
  }
});
----

== Creating an icon pack manually

When adding only a few icons, it may be easier to manually configure the new icon pack than to use the Icon Pack Template tool. To do this:

. Gather the SVG files for the new icons. Extract their content string, e.g. `+<svg width="24" height="24">...</svg>+`
. Call `+tinymce.IconManager.add()+`
. Specify the icon pack name as the first argument
. The second argument is an object, with key `+icons+` and a nested object containing the new icons with their names and SVG strings as their keys and values.

The new icons can then be used by name within {productname}.

[IMPORTANT]
====
*Icon Override:* If custom icons have the same name as a default {productname} icon, they will override the default icon.
====

This JavaScript can be included as a separate icon file or inlined beside the application's `+tinymce.init()+` call. Configure {productname} to load the icon pack and possibly where from.

[NOTE]
====
*Naming Icon Pack Files:* When loading icon packs from a separate file, it is safest to name the file `+icons.js+`. This ensures that, if placed in the default location, {productname} will recognize the file as an icon pack.
====

=== Example: using a custom icon pack inline

[source,js]
----
tinymce.IconManager.add('customIcons', { // icon pack name
  icons: { // list icons as name-SVG pairs
    'my-custom-icon': '<svg width="24" height="24">...</svg>',
  }
});

tinymce.init({
  selector: '#editor',
  icons: 'customIcons', // tell {productname} to load the custom icon pack
  toolbar: 'myCustomButton',
  setup: function(editor) {
    editor.ui.registry.addToolbarButton('myCustomButton', {
      icon: 'my-custom-icon' // use the custom icon for a custom toolbar button
    });
  }
});
----

== Using the Icon Pack Template tool

For large custom icon packs, use the xref:using-the-icon-pack-template.adoc[Icon Pack Template tool], which can take a folder of SVGs and generate the required output file. This approach is ideal when creating icon packs with many icons or when automating the build process.

For step-by-step instructions, see: xref:using-the-icon-pack-template.adoc[Using the Icon Pack Template tool].

== Deploying an Icon Pack file

An icon pack file can be served either:

* With {productname}
* Separate from {productname}

Use the xref:editor-icons.adoc#icons[`+icons+`] and xref:editor-icons.adoc#icons_url[`+icons_url+`] options to configure {productname} appropriately.

[NOTE]
====
*Default Icon Pack Location:*

The `+icons+` option will only recognize icon files located at `+TINYMCE_BASE/icons/${iconPackName}/icons.js+`; where:

* `+TINYMCE_BASE+` is the {productname} root directory (the directory containing `+tinymce.min.js+`).
====

[[deploy-the-icon-pack-with-tinymce]]
=== Deploy the Icon Pack with {productname}

:customIconPack: true
include::partial$configuration/icons.adoc[]

[[deploy-the-icon-pack-and-tinymce-separately]]
=== Deploy the Icon Pack and {productname} Separately

include::partial$configuration/icons_url.adoc[]
:customIconPack: false

== Interactive Demo

See the custom icon pack in action with the interactive demo:

liveDemo::custom-icon-pack[]
