= Creating custom Menu toolbar buttons
:navtitle: Menu toolbar button
:description: Creating custom Menu toolbar buttons for TinyMCE
:keywords: toolbar, toolbarbuttons, buttons, toolbarbuttonsapi

A toolbar menu button is a toolbar button that opens a menu when clicked. This menu can also contain submenus. This is useful for grouping together actions that would otherwise be several buttons on the toolbar. It can also be used to reduce visual clutter and save UI space, as menubar menu items and some toolbar buttons could be moved into a toolbar menu button. Potentially, all menubar menu items could be moved into toolbar menu buttons, allowing for the editor to be used without a menubar at all.

For example: The table plugin's `+table+` toolbar button opens a menu similar to the menubar Table menu.

== Options

[cols="1,2,1,4",options="header"]
|===
|Name |Value |Requirement |Description
|fetch |`+(success: (menu) => void, fetchContext) => void+` |required |Function that takes a callback and a `+fetchContext+` object. The callback function must be passed the list of options for the button's dropdown. The `+fetchContext+` object provides information which is useful for choosing which items should be passed to the callback. For more details on `fetchContext`, see xref:searchable-menu-buttons[Searchable Menu Buttons]
|text |string |optional |Text to display if no icon is found.
|icon |string |optional |
include::partial$misc/admon-predefined-icons-only.adoc[]
|search|boolean or object|optional |If not false, adds a search field to the menu. For more details, see xref:searchable-menu-buttons[Searchable Menu Buttons]
|tooltip |string |optional |Text for button tooltip.
|onSetup |`+(api) => (api) => void+` |optional |default: `+() => () => {}+` - Function that's invoked when the button is rendered. For details, see: xref:using-onsetup[Using `+onSetup+`].
4+|
include::partial$misc/admon-requires-7.4v.adoc[]
|context |string |optional |default: `mode:design` - The context property dynamically enables or disables the button based on the editor's current state. For details, see: xref:context.adoc[Context].
|===

== API

[cols="1,3,4",options="header"]
|===
|Name |Value |Description
|isEnabled |`+() => boolean+` |Checks if the button is enabled.
|setEnabled |`+(state: boolean) => void+` |Sets the button's enabled state.
3+|
include::partial$misc/admon-requires-6.4v.adoc[]
|setText |`+(text: string) => void+` |Sets the text label to display.
|setIcon |`+(icon: string) => void+` |Sets the icon of the button.
|===

== Menu button example and explanation without search enabled

The following is a simple toolbar menu button example:

liveDemo::custom-toolbar-menu-button[tab="js"]

This example configures a toolbar menu button labeled `+My Button+` that opens a menu when clicked. The menu contains two items: one that inserts content and another that opens a submenu with two additional items to be inserted when clicked.

The `+fetch+` function retrieves an array of menu items and passes it to the callback, which renders them in the dropdown menu. This enables asynchronous menu generation. 

[[searchable-menu-buttons]]
== Fetch with Searchable menu buttons 

include::partial$misc/admon-requires-6.2v.adoc[]

The button's menu can include a search input field alongside it's items, controlled by the `+search+` option. The  `+search+` option can be either:

* A `+boolean+` value: When `true`, it enables the search field. The text inside the field is empty.

* An `+object+`: Allows customization with a placeholder to set placeholder text for the input field. 

By default, `+search+` is false, meaning no search field is displayed. When enabled, the search field allows for dynamic updating of the menu content based on their input. The `+fetchContext+` object provides additional information to the `+fetch+` function which can be used to determine the menu's behaviour or content.

When `+search+` is enabled, depending on the `+pattern+` property of `+fetchContext+` different menu buttons options will be shown. This is because when a new keypress is added to the `+search+`, `+fetch+` is called to update the possible options from the search.
== Searchable menu button example and explanation

include::partial$misc/admon-requires-6.2v.adoc[]

The following is a simple toolbar menu button example, where searching has been configured:

liveDemo::custom-toolbar-menu-button-search[tab="js"]

This example configures a toolbar menu button with the label `+Searchable Menu+` that opens the specified menu when clicked. The menu will contain a search input field because `+search+` is not `+false+`. The `+fetch+` function is called with a `+pattern+` being "Search items...". The `+fetchContext+` is set to the `+pattern+` and as `+pattern+` is updated the menu will update. When searching the `+pattern+` is filtered and when the pattern doesn't meet the menuitems the search closes.

The input field's https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder[placeholder attribute] will be `+Type...+`.

include::partial$misc/onSetup.adoc[]
