= Creating custom Menu toolbar buttons
:navtitle: Menu toolbar button
:description: Creating custom Menu toolbar buttons for TinyMCE
:keywords: toolbar, toolbarbuttons, buttons, toolbarbuttonsapi

A toolbar menu button is a toolbar button that opens a menu when clicked. This menu can also contain submenus. This is useful for grouping together actions that would otherwise be several buttons on the toolbar. It can also be used to reduce visual clutter and save UI space, as menubar menu items and some toolbar buttons could be moved into a toolbar menu button. Potentially, all menubar menu items could be moved into toolbar menu buttons, allowing for the editor to be used without a menubar at all.

For example: The table plugin's `+table+` toolbar button opens a menu similar to the menubar Table menu.

== Options

[cols="1,2,1,4",options="header"]
|===
|Name |Value |Requirement |Description
|fetch |`+(success: (menu) => void, fetchContext) => void+` |required |Function that takes a callback and a `+fetchContext+` object. The callback function must be passed the list of options for the button's dropdown. The `+fetchContext+` object provides information which is useful for choosing which items should be passed to the callback. For more details on `fetchContext`, see xref:searchable-menu-buttons[Searchable Menu Buttons]
|text |string |optional |Text to display if no icon is found.
|icon |string |optional |
include::partial$misc/admon-predefined-icons-only.adoc[]
|search|boolean or object|optional |If not false, adds a search field to the menu. For more details, see xref:searchable-menu-buttons[Searchable Menu Buttons]
|tooltip |string |optional |Text for button tooltip.
|onSetup |`+(api) => (api) => void+` |optional |default: `+() => () => {}+` - Function that's invoked when the button is rendered. For details, see: xref:using-onsetup[Using `+onSetup+`].
4+|
include::partial$misc/admon-requires-7.4v.adoc[]
|context |string |optional |default: `mode:design` - The context property dynamically enables or disables the button based on the editor's current state. For details, see: xref:context.adoc[Context].
|===

== API

[cols="1,3,4",options="header"]
|===
|Name |Value |Description
|isEnabled |`+() => boolean+` |Checks if the button is enabled.
|setEnabled |`+(state: boolean) => void+` |Sets the button's enabled state.
3+|
include::partial$misc/admon-requires-6.4v.adoc[]
|setText |`+(text: string) => void+` |Sets the text label to display.
|setIcon |`+(icon: string) => void+` |Sets the icon of the button.
|===

== Menu button example and explanation

The following is a simple toolbar menu button example:

liveDemo::custom-toolbar-menu-button[tab="js"]

This example configures a toolbar menu button with the label `+My Button+` that opens the specified menu when clicked. The top-level menu contains two items. The first menu item inserts content when clicked and the second menu item opens a submenu containing two menu items which insert content when clicked.

The `+fetch+` function is called when the toolbar menu button's menu is opened. It is a function that takes a callback and passes it an array of menu items to be rendered in the drop-down menu. This allows for asynchronous fetching of the menu items.

[[searchable-menu-buttons]]
== Searchable menu buttons

include::partial$misc/admon-requires-6.2v.adoc[]

The button's menu can be configured to have an input field for searching, as well as its usual items. The presence of the input field is controlled by the `+search+` field in the xref:options[options]. The `+search+` field can be a `+boolean+` or an `+object+` containing a single optional string `placeholder`. By default, `+search+` is false. If `+search+` is not false, the button's menu will contain an input field with any specified placeholder text. As the user types into this field, the `+fetch+` function will be called with the text in the input field passed back as part of `+fetchContext+`. The `+fetch+` function is responsible for using this `+fetchContext+` to determine which items to pass to its `+success+` callback.

The `+fetchContext+` is an object containing a single string property: `+pattern+`. If the toolbar menu button has not configured `search` to be active, then the `+pattern+` string will be empty.

== Searchable menu button example and explanation

include::partial$misc/admon-requires-6.2v.adoc[]

The following is a simple toolbar menu button example, where searching has been configured:

liveDemo::custom-toolbar-menu-button-search[tab="js"]

This example configures a toolbar menu button with the label `+My searchable button+` that opens the specified menu when clicked. The menu will contain a search input field because `+search+` is not `+false+`. The input field's https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder[placeholder attribute] will be `+Type...+`.

Initially, when the menu opens, the search input field will be empty, and the `+fetch+` function is called with an empty `+pattern+` for its `+fetchContext+`. In that situation, `+fetch+` passes back an array of two items to be rendered in the drop-down menu. When the user types in the input field, `+fetch+` will be called again, except this time, the `+pattern+` property in `+fetchContext+` will reflect the value typed in the input field. For illustration purposes, this example then passes back an item that contains this pattern inside the item's text. In a more real-life example, the `+pattern+` could be used to filter which of the items are passed to the callback.

include::partial$misc/onSetup.adoc[]
