= Creating custom Group toolbar buttons
:navtitle: Group toolbar button
:description: Creating custom Group toolbar buttons for TinyMCE
:keywords: toolbar, toolbarbuttons, buttons, toolbarbuttonsapi

A group toolbar button is a toolbar button that contains a collection of other toolbar buttons that are displayed in a pop-up when clicked. The style of toolbar shown is based on the current xref:toolbar-configuration-options.adoc#toolbar_mode[toolbar mode]. For example, if `+toolbar_mode+` is set to `+floating+`, the toolbar group pop-up will appear in a floating shelf.

NOTE: The group toolbar button is _only_ supported when using the `+floating+` toolbar mode. If the `+toolbar_groups+` option is used with other toolbar modes, the toolbar group button will not be displayed and a warning message will be printed in the console.

== Config options

[cols="1,2,1,4",options="header"]
|===
|Name |Value |Requirement |Description
|text |string |optional |Text to display if no icon is found.
|icon |string |optional |
include::partial$misc/admon_predefined_icons_only.adoc[]
|tooltip |string |optional |Text for button tooltip.
|items |string or `+LabelledToolbar[]+` |required |A string of space separated toolbar button names, or an array of xref:toolbar-configuration-options.adoc#addingtoolbargrouplabels[labelled toolbar buttons].
|onSetup |`+(api) => (api) => void+` |optional |default: `+() => () => {}+` - Function that's invoked when the button is rendered. For details, see: xref:usingonsetup[Using `+onSetup+`].
|===

== API

[cols="1,3,4",options="header"]
|===
|Name |Value |Description
|isEnabled |`+() => boolean+` |Checks if the button is enabled.
|setEnabled |`+(state: boolean) => void+` |Sets the button's enabled state.
|===

== Group toolbar button example and explanation

The following is a simple group toolbar button example:

liveDemo::custom-toolbar-group-button[tab="js"]

The example above configures a custom *alignment* group toolbar button. When clicked the button will show a floating shelf containing the align left, center, right and justify toolbar buttons.

include::partial$misc/onSetup.adoc[]
