= Creating custom Toggle toolbar buttons
:navtitle: Toggle toolbar button
:description: Creating custom Toggle toolbar buttons for TinyMCE
:keywords: toolbar, toolbarbuttons, buttons, toolbarbuttonsapi

A toggle button triggers an action when clicked but also has a concept of state. This means it can be toggled `+on+` and `+off+`. A toggle button gives the user visual feedback for its state through CSS styling. An example of this behavior is the *Bold* button that is highlighted when the cursor is in a word with bold formatting.

== Options

[cols="1,2,1,4",options="header"]
|===
|Name |Value |Requirement |Description
|text |string |optional |Text to display if no icon is found.
|icon |string |optional |
include::partial$misc/admon-predefined-icons-only.adoc[]
|tooltip |string |optional |Text for button tooltip.
|enabled |boolean |optional |default: `true` - Represents the button's state. When `false`, the button is unclickable. Toggled by the button's API.
|active |boolean |optional |default: `false` - Represents the button's state. When `true`, the button is highlighted. Toggled by the button's API.
|onSetup |`+(api) => (api) => void+` |optional |default: `+() => () => {}+` - Function invoked when the button is rendered. For details, see: xref:using-onsetup[Using `+onSetup+`].
|onAction |`+(api) => void+` |required |Function invoked when the button is clicked.
4+|
include::partial$misc/admon-requires-7.0v.adoc[]
|shortcut |string |optional |Shortcut to display in the tooltip. To register a shortcut, see: xref:shortcuts.adoc[Add custom shortcuts to TinyMCE].
4+|
include::partial$misc/admon-requires-7.4v.adoc[]
|context |string |optional |default: `mode:design` - The context property dynamically enables or disables the button based on the editor's current state. For details, see: xref:context.adoc[Context].
|===

== API

[cols="1,3,4",options="header"]
|===
|Name |Value |Description
|isEnabled |`+() => boolean+` |Checks if the button is enabled.
|setEnabled |`+(state: boolean) => void+` |Sets the button's enabled state.
|isActive |`+() => boolean+` |Checks if the button is `+on+`.
|setActive |`+(state: boolean) => void+` |Sets the button's toggle state.
3+|
include::partial$misc/admon-requires-6.4v.adoc[]
|setText |`+(text: string) => void+` |Sets the text label to display.
|setIcon |`+(icon: string) => void+` |Sets the icon of the button.
|===

== Toggle button example and explanation

liveDemo::custom-toolbar-toggle-button[tab="js"]

The example above adds two custom *strikethrough* buttons with the same `+onAction+` configuration. The configuration uses `+editor.execCommand(command, ui, args)+` to execute `+mceToggleFormat+`. This editor method toggles the specified format on and off, but only works for xref:content-formatting.adoc#formats[formats] that are already registered with the editor. In this example, `+strikethrough+` is the registered format.

The first button applies and removes strikethrough formatting, and its state toggles on click using `+api.setActive(!api.isActive())+`. However, the expected behavior is that the button's state will reflect whether the selected content has strikethrough formatting. For example, if the cursor is moved into editor content that has strikethrough formatting the button will become *active* and if it is moved into content that does not have strikethrough formatting the button will become *inactive*. The first button in the example does not do this, since its state only toggles when the button is clicked.

To achieve this, the second button uses `+onSetup+` to register a callback for strikethrough content using `+editor.formatter.formatChanged(formatName, callback)+`. This method executes the specified callback function when the selected content has the specified formatting.

NOTE: The format name given to `+mceToggleFormat+` via `+editor.execCommand(command, ui, args)+` and to `+editor.formatter.formatChanged(formatName, callback)+` is the same.

The callback given to `+editor.formatter.formatChanged+` is a function that takes a `+state+` boolean representing whether the currently selected content contains the applied format. This `+state+` boolean is used to set the button's active state to match if the selected content has the specified formatting by using `+api.setActive(state)+` from the button's API. This ensures the `+customToggleStrikethrough+` button is only *active* when the selected content contains the strikethrough formatting.

For formats that require variables, the `+editor.formatter.formatChanged+` function takes two extra arguments: `+similar+` and `+vars+`.

When the `+similar+` argument is `+true+`, similar formats will all be treated as the same by `+formatChanged+`. Similar formats are those with the same `+formatName+` but different variables. This argument will default to `+false+`.

The `+vars+` argument controls which variables are used to match the content when determining whether to run the callback. This argument is only used when `+similar+` is `+false+`.

include::partial$misc/onSetup.adoc[]
