= Image Editing
:navtitle: Image Editing
:description: Image Editing features for TinyMCE.
:keywords: edit, image, rotate, rotateleft, rotateright, flip, flipv, fliph, editimage, imageoption, imageediting
:pluginname: Image Editing
:plugincode: editimage
:pluginminimumplan: tiertwo

include::partial$misc/admon-premium-plugin.adoc[]

The {pluginname} (`{plugincode}`) plugin adds a contextual editing toolbar to images in the editor.

If the toolbar does not appear after clicking on an image, you may need to enable `+editimage_cors_hosts+` or `+editimage_proxy_service_url+` (see below).

NOTE: In previous versions of {productname}, the {pluginname} plugin was provided as an open source plugin known as the Image Tools plugin.

== Interactive example

liveDemo::edit-image[]

include::partial$misc/admon-svg-not-supported.adoc[]

// include::partial$misc/purchase-premium-plugins.adoc[]

== Cloud Installation

The Image Editing plugin is provided with all subscriptions to xref:editor-and-features.adoc[{cloudname}], including an automatically configured image proxy. Simply add `+image+` to the `+toolbar+` list and `+image editimage+` to the `+plugins+` list.

=== Basic setup using Tiny Cloud

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'image',
  plugins: 'image editimage'
});
----

== Self-hosted Installation

To enable the {productname} Image Editing plugin:

. Add `image` to the `toolbar` list and `image editimage` to the `plugins` list.
. Enable xref:editimage_cors_hosts[`+editimage_cors_hosts+`] and xref:editimage_proxy_service_url[`+editimage_proxy_service_url+`] options as required.

=== Basic self-hosted setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'image',
  plugins: 'image editimage',
  editimage_cors_hosts: [ 'example.com', 'example.net' ],
  editimage_proxy_service_url: 'http://example.com/ephox-image-proxy/'
});
----

== Options

include::partial$configuration/image_cors_hosts.adoc[leveloffset=+1]

include::partial$configuration/editimage_credentials_hosts.adoc[leveloffset=+1]

include::partial$configuration/editimage_fetch_image.adoc[leveloffset=+1]

include::partial$configuration/image_proxy.adoc[leveloffset=+1]

include::partial$configuration/image_proxy_service_url.adoc[leveloffset=+1]

include::partial$configuration/editimage_toolbar.adoc[leveloffset=+1]

include::partial$configuration/editimage_upload_timeout.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[leveloffset=+1]

== Commands

The Image Editing plugin provides the following {productname} commands.

include::partial$commands/editimage-cmds.adoc[]
