= Enhanced Image Editing (formerly Image Tools)
:navtitle: Enhanced Image Editing
:description: Enhanced image editing features for TinyMCE.
:keywords: edit, image, rotate, rotateleft, rotateright, flip, flipv, fliph, editimage, imageoptions
:pluginname: Enhanced Image Editing
:plugincode: editimage
:pluginminimumplan: tierone

NOTE: In previous versions of {productname}, the {pluginname} plugin was provided as an open source plugin known as the Image Tools plugin.

Enhanced Image Editing (`+editimage+`) plugin adds a contextual editing toolbar to the images in the editor. If toolbar is not appearing on image click, it might be that you need to enable `+editimage_cors_hosts+` or `+editimage_proxy_service_url+` (see below).

== Interactive example

liveDemo::edit-image[]

include::partial$misc/admon-svg-not-supported.adoc[]

include::partial$misc/purchase-premium-plugins.adoc[]

== Cloud Installation

The Enhanced Image Editing plugin is provided with all subscriptions to xref:editor-and-features.adoc[{cloudname}], including an automatically configured image proxy. Simply add `+image+` to the `+toolbar+` list and `+image editimage+` to the `+plugins+` list.

=== Basic setup using Tiny Cloud

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'image',
  plugins: 'image editimage'
});
----

== Self-hosted Installation

To enable the {productname} Enhanced Image Editing plugin:

. Add `image` to the `toolbar` list and `image editimage` to the `plugins` list.
. Enable xref:editimage_cors_hosts[`+editimage_cors_hosts+`] and xref:editimage_proxy_service_url[`+editimage_proxy_service_url+`] options as required.

=== Basic self-hosted setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'image',
  plugins: 'image editimage',
  editimage_cors_hosts: [ 'mydomain.com', 'otherdomain.com' ],
  editimage_proxy_service_url: 'http://mydomain.com/ephox-image-proxy/'
});
----

== Options

include::partial$configuration/image_cors_hosts.adoc[leveloffset=+1]

include::partial$configuration/editimage_credentials_hosts.adoc[leveloffset=+1]

include::partial$configuration/editimage_fetch_image.adoc[leveloffset=+1]

include::partial$configuration/image_proxy.adoc[leveloffset=+1]

include::partial$configuration/image_proxy_service_url.adoc[leveloffset=+1]

include::partial$configuration/editimage_toolbar.adoc[leveloffset=+1]

include::partial$configuration/editimage_upload_timeout.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[leveloffset=+1]

== Commands

The Enhanced Image Editing plugin provides the following {productname} commands.

include::partial$commands/editimage-cmds.adoc[]
