= Commands Available for TinyMCE

:title_nav: Available Commands

:description_short: Complete list of editor commands.
:description: The complete list of exposed editor commands.
:keywords: editorcommands editorcommand execcommand Bold Italic Underline Strikethrough Superscript Subscript Cut Copy Paste Unlink JustifyLeft JustifyCenter JustifyRight JustifyFull JustifyNone InsertUnorderedList InsertOrderedList ForeColor HiliteColor FontName FontSize RemoveFormat mceBlockQuote FormatBlock mceInsertContent mceToggleFormat mceSetContent Indent Outdent InsertHorizontalRule mceToggleVisualAid mceInsertLink selectAll delete mceNewDocument Undo Redo mceAutoResize mceShowCharmap mceCodeEditor mceDirectionLTR mceDirectionRTL mceFullPageProperties mceFullscreen mceImage mceInsertDate mceInsertTime mceInsertDefinitionList mceNonBreaking mcePageBreak mcePreview mcePrint mceSave SearchReplace mceSpellcheck mceInsertTemplate mceVisualBlocks mceVisualChars mceMedia mceAnchor mceTableSplitCells mceTableMergeCells mceTableInsertRowBefore mceTableInsertRowAfter mceTableInsertColBefore mceTableInsertColAfter mceTableDeleteCol mceTableDeleteRow mceTableCutRow mceTableCopyRow mceTablePasteRowBefore mceTablePasteRowAfter mceTableDelete mceInsertTable mceTableRowProps mceTableCellProps mceEditImage mceAddEditor mceRemoveEditor mceToggleEditor

== Overview

* <<executablecommands, Executable commands>>
** <<listingcoreandplugineditorcommands, Listing core and plugin editor commands>>
** <<coreeditorcommands, Core Editor commands>>
** <<plugincommands, Plugin Commands>>
** <<editormanagementcommands, Editor Management Commands>>
* <<querycommandstates, Query command states>>
** <<listingcoreandpluginquerycommandstates, Listing core and plugin query command states>>
** <<availablequerycommandstates, Available query command states>>
* <<querycommandvalues, Query command values>>
** <<listingcoreandpluginquerycommandvalues, Listing core and plugin Query command values>>
** <<availablequerycommandvalues, Available Query command values>>
** <<querycommandvaluestableplugin, Query command values: Table plugin>>

== Executable commands

The following tables show the existing editor commands. These commands are provided by `+tinymce+` and not by the browser's internal commands. These commands can be executed using the [execCommand](\{\{ site.baseurl }}/apis/tinymce/tinymce.editorcommands/#execcommand) function.

=== Listing core and plugin editor commands

To retrieve a list of avaliable commands from the active editor, run the following command from the browser console:

[source,js]
----
tinymce.activeEditor.editorCommands.commands.exec;
----

=== Core Editor commands

The commands on the following table are provided by the \{\{site.productname}} editor and do not require any plugins to be enabled.

[cols=",",options="header",]
|===
|Command |Description
|Bold |Toggles bold formatting to selection.
|Italic |Toggles italic formatting to selection.
|Underline |Toggles underline formatting to selection.
|Strikethrough |Toggles strikethough formatting to selection.
|Superscript |Toggles superscript formatting to selection.
|Subscript |Toggles subscript formatting to selection.
|Cut |Cuts the selected contents and puts in into users clipboard.
|Copy |Copies the selected contents and puts in into users clipboard.
|Lang |Sets the language of the current selection. The value passed in should be a language spec described in link:{baseurl}/content/content-localization/#content_langs[Content appearance options - `+content_langs+`].
|Paste |Pastes the current clipboard contents into the editor.
|mceInsertLink |Inserts a link at the current selection. The value is the URL to add to the link(s).
|Unlink |Removes any links from the current selection.
|JustifyLeft |Left aligns the current text block/image.
|JustifyCenter |Center aligns the current text block/image.
|JustifyRight |Right aligns the current text block/image.
|JustifyFull |Full aligns the current text block/image.
|JustifyNone |Removes any alignment to the selected text.
|ForeColor |Changes the text color of the text. The value passed in should be the color.
|HiliteColor |Changes the background color of the text. The value passed in should be the color.
|FontName |Font name to apply to the text. The value passed in should be the font family name.
|FontSize |Font size of the text. The value passed in should be a valid CSS font size.
|LineHeight |Sets the line height of the text. The value passed in should be a valid CSS line height.
|mceApplyTextcolor |Applies text color or background color to the current selection. Requires an argument of either `+'hilitecolor'+` or `+'forecolor'+`, and the value of the color.
|mceRemoveTextcolor |Removes the text color or background color from the current selection. Requires an argument of either `+'hilitecolor'+` or `+'forecolor'+`.
|RemoveFormat |Removes any formats from the current selection.
|mceBlockQuote |Wraps the selected text blocks into a block quote.
|FormatBlock |Toggles the format of the current selection. The value passed in should be the format name. If no format is specified, the paragraph (<`+p+`>) format will be toggled. For a list of options, see: [Content formatting options - Built-in formats](\{\{ site.baseurl }}/content/content-formatting/#built-informats).
|mceInsertContent |Inserts contents at the current selection. The value passed in should be the contents to be inserted.
|mceReplaceContent |Replaces the current selection. The value passed in should be the new content.
|mceSetContent |Sets the contents of the editor. The value is the contents to set as the editor contents.
|mceToggleFormat |Toggles a specified format by name. The value is the name of the format to toggle. For a list of options, see: [Content formatting options - Built-in formats](\{\{ site.baseurl }}/content/content-formatting/#built-informats).
|ToggleSidebar |Closes the currrent sidebar, or toogles the sidebar if the sidebar name is provided as a value (_`+<sidebar-name>+`_).
|ToggleToolbarDrawer |Toggles the Toolbar Drawer. For information on toolbars, see: link:{baseurl}/interface/toolbars/toolbar-configuration-options/#toolbar[User interface options - Toolbar].
|Indent |Indents the current selection.
|Outdent |Outdents the current selection.
|InsertHorizontalRule |Inserts a horizontal rule at the cursor location or inplace of the current selection.
|InsertLineBreak |Adds a line break `+<br/>+` at the current cursor or selection.
|mceInsertNewLine |Adds a new line at the current cursor or selection, such as splitting the current paragraph element.
|mceInsertRawHTML |Inserts the RAW HTML passed as a value, overwriting the current selection or at the cursor position. *Warning*: This command allows dangerous `+<script>+` elements to be added to and executed in the editor.
|mceToggleVisualAid |Toggles the visual aids for: tables without borders and anchors.
|SelectAll |Selects all content in the editor.
|Delete |Deletes the current selection from the editor.
|ForwardDelete |Deletes the current selection or the character to the right of the cursor for a collapsed selection.
|mceNewDocument |Removes all contents of the editor.
|Redo |Redoes the last change to the editor.
|Undo |Undoes the last change to the editor.
|mceAddUndoLevel |Adds an undo level.
|mceEndUndoLevel |Adds an undo level.
|mceCleanup |Copies the current editor content and sets the content using the copy.
|mceSelectNode |Selects a node in the editor. The target node is passed as the value (_`+<DOM_node>+`_).
|mceSelectNodeDepth |Selects the parent DOM node 'n' levels above the current node.
|mceRemoveNode |Removes the current node or the target node passed as the value (_`+<DOM_node>+`_).
|mceFocus |Focuses and activates the editor. Places DOM focus inside the editor and also sets the editor as the active editor instance on the page.
|mcePrint |Opens the browser's print dialog for the current page.
|===

*Examples*

[source,js]
----
tinymce.activeEditor.execCommand('Bold');
tinymce.activeEditor.execCommand('Italic');
tinymce.activeEditor.execCommand('Underline');
tinymce.activeEditor.execCommand('Strikethrough');
tinymce.activeEditor.execCommand('Superscript');
tinymce.activeEditor.execCommand('Subscript');
tinymce.activeEditor.execCommand('Cut');
tinymce.activeEditor.execCommand('Copy');
tinymce.activeEditor.execCommand('Paste');
tinymce.activeEditor.execCommand('mceInsertLink', false, 'https://www.tiny.cloud');
tinymce.activeEditor.execCommand('Unlink');
tinymce.activeEditor.execCommand('JustifyLeft');
tinymce.activeEditor.execCommand('JustifyCenter');
tinymce.activeEditor.execCommand('JustifyRight');
tinymce.activeEditor.execCommand('JustifyFull');
tinymce.activeEditor.execCommand('JustifyNone');
tinymce.activeEditor.execCommand('ForeColor', false, '#FF0000');
tinymce.activeEditor.execCommand('HiliteColor', false, '#FF0000');
tinymce.activeEditor.execCommand('FontName', false, 'courier new');
tinymce.activeEditor.execCommand('FontSize', false, '30px');
tinymce.activeEditor.execCommand('LineHeight', false, '1.4');
tinymce.activeEditor.execCommand('mceApplyTextcolor', 'hilitecolor', '#FF0000');
tinymce.activeEditor.execCommand('mceRemoveTextcolor', 'hilitecolor');
tinymce.activeEditor.execCommand('RemoveFormat');
tinymce.activeEditor.execCommand('mceBlockQuote');
tinymce.activeEditor.execCommand('FormatBlock', false, 'bold');
tinymce.activeEditor.execCommand('mceInsertContent', false, 'My new content');
tinymce.activeEditor.execCommand('mceReplaceContent', false, 'My replacement content');
tinymce.activeEditor.execCommand('mceSetContent', false, 'My content');
tinymce.activeEditor.execCommand('mceToggleFormat', false, 'bold');
tinymce.activeEditor.execCommand('ToggleSidebar');  /* OR */
tinymce.activeEditor.execCommand('ToggleSidebar', false, '<sidebar-name>');
tinymce.activeEditor.execCommand('ToggleToolbarDrawer');
tinymce.activeEditor.execCommand('Indent');
tinymce.activeEditor.execCommand('Outdent');
tinymce.activeEditor.execCommand('InsertHorizontalRule');
tinymce.activeEditor.execCommand('InsertLineBreak');
tinymce.activeEditor.execCommand('mceInsertNewLine');
tinymce.activeEditor.execCommand('mceInsertRawHTML', false, '<p>Hello, World!</p>');
tinymce.activeEditor.execCommand('mceToggleVisualAid');
tinymce.activeEditor.execCommand('SelectAll');
tinymce.activeEditor.execCommand('Delete');
tinymce.activeEditor.execCommand('ForwardDelete');
tinymce.activeEditor.execCommand('mceNewDocument');
tinymce.activeEditor.execCommand('Redo');
tinymce.activeEditor.execCommand('Undo');
tinymce.activeEditor.execCommand('mceAddUndoLevel');
tinymce.activeEditor.execCommand('mceEndUndoLevel');
tinymce.activeEditor.execCommand('mceCleanup');
tinymce.activeEditor.execCommand('mceSelectNode', false, '<DOM_node>');
tinymce.activeEditor.execCommand('mceSelectNodeDepth', false, 2); // For two nodes up.
tinymce.activeEditor.execCommand('mceRemoveNode'); /* OR */
tinymce.activeEditor.execCommand('mceRemoveNode', false, '<DOM_node>');
tinymce.activeEditor.execCommand('mceFocus');
tinymce.activeEditor.execCommand('mcePrint');
----

=== Plugin Commands

Commands are available for the following plugins:

* <<advancedcode, Advanced Code>>
* <<advancedlists, Advanced Lists>>
* <<advancedtables, Advanced Tables>>
* <<anchor, Anchor>>
* <<autoresize, Autoresize>>
* <<casechange, Case Change>>
* <<charactermap, Character Map>>
* <<code, Code>>
* <<codesample, Code Sample>>
* <<comments, Comments>>
* <<directionality, Directionality>>
* <<emoticons, Emoticons>>
* <<export, Export>>
* <<formatpainter, Format Painter>>
* <<fullscreen, Full Screen>>
* <<help, Help>>
* <<image, Image>>
* <<imagetools, Image Tools>>
* <<insertdatetime, Insert Date/Time>>
* <<link, Link>>
* <<lists, Lists>>
* <<media, Media>>
* <<nonbreakingspace, Nonbreaking Space>>
* <<pagebreak, Page Break>>
* <<paste, Paste>>
* <<permanentpen, Permanent Pen>>
* <<powerpaste, PowerPaste>>
* <<preview, Preview>>
* <<save, Save>>
* <<searchandreplace, Search and Replace>>
* <<spellcheckerpro, Spell Checker Pro>>
* <<table, Table>>
* <<template, Template>>
* <<tableofcontents, Table of Contents>>
* <<visualblocks, Visual Blocks>>
* <<visualcharacters, Visual Characters>>
* <<wordcount, Word Count>>

==== Advanced Code

The following command requires the link:{baseurl}/plugins-ref/premium/advcode/[Advanced Code (`+advcode+`)] plugin.

include::partial$commands/code-cmds.adoc[]

==== Advanced Lists

The following commands require the link:{baseurl}/plugins-ref/opensource/advlist/[Advanced Lists (`+advlist+`)] plugin.

include::partial$commands/advlist-cmds.adoc[]

==== Advanced Tables

The following commands require the link:{baseurl}/plugins-ref/premium/advtable/[Advanced Tables (`+advtable+`)] plugin.

include::partial$commands/advtable-cmds.adoc[]

==== Anchor

The following command requires the link:{baseurl}/plugins-ref/opensource/anchor/[Anchor (`+anchor+`)] plugin.

include::partial$commands/anchor-cmds.adoc[]

==== Autoresize

The following command requires the link:{baseurl}/plugins-ref/opensource/autoresize/[Autoresize (`+autoresize+`)] plugin.

include::partial$commands/autoresize-cmds.adoc[]

==== Case Change

The following commands require the link:{baseurl}/plugins-ref/premium/casechange/[Case Change (`+casechange+`)] plugin.

include::partial$commands/casechange-cmds.adoc[]

==== Character Map

The following command requires the link:{baseurl}/plugins-ref/opensource/charmap/[Character Map (`+charmap+`)] plugin.

include::partial$commands/charmap-cmds.adoc[]

==== Code

The following command requires the link:{baseurl}/plugins-ref/opensource/code/[Code (`+code+`)] plugin.

include::partial$commands/code-cmds.adoc[]

==== Code Sample

The following command requires the link:{baseurl}/plugins-ref/opensource/codesample/[Code Sample (`+codesample+`)] plugin.

include::partial$commands/codesample-cmds.adoc[]

==== Comments

The following commands require the link:{baseurl}/plugins-ref/premium/comments/[Comments (`+tinycomments+`)] plugin.

include::partial$commands/comments-cmds.adoc[]

==== Directionality

The following commands require the link:{baseurl}/plugins-ref/opensource/directionality/[Directionality (`+directionality+`)] plugin.

include::partial$commands/directionality-cmds.adoc[]

==== Emoticons

The following commands require the link:{baseurl}/plugins-ref/opensource/emoticons/[Emoticons (`+emoticons+`)] plugin.

include::partial$commands/emoticons-cmds.adoc[]

==== Export

The following commands require the link:{baseurl}/plugins-ref/premium/export/[Export (`+export+`)] plugin.

include::partial$commands/export-cmds.adoc[]

==== Format Painter

The following commands require the link:{baseurl}/plugins-ref/premium/formatpainter/[Format Painter (`+formatpainter+`)] plugin.

include::partial$commands/formatpainter-cmds.adoc[]

==== Full Screen

The following command requires the link:{baseurl}/plugins-ref/opensource/fullscreen/[Full Screen (`+fullscreen+`)] plugin.

include::partial$commands/fullscreen-cmds.adoc[]

==== Help

The following command requires the link:{baseurl}/plugins-ref/opensource/help/[Help (`+help+`)] plugin.

include::partial$commands/help-cmds.adoc[]

==== Image

The following command requires the link:{baseurl}/plugins-ref/opensource/image/[Image (`+image+`)] plugin.

include::partial$commands/image-cmds.adoc[]

==== Image Tools

The following commands require the link:{baseurl}/plugins-ref/opensource/imagetools/[Image Tools (`+imagetools+`)] plugin.

include::partial$commands/imagetools-cmds.adoc[]

==== Insert Date/Time

The following commands require the link:{baseurl}/plugins-ref/opensource/insertdatetime/[Insert Date/Time (`+insertdatetime+`)] plugin.

include::partial$commands/insertdatetime-cmds.adoc[]

==== Link

The following command requires the link:{baseurl}/plugins-ref/opensource/link/[Link (`+link+`)] plugin.

include::partial$commands/link-cmds.adoc[]

==== Lists

The following commands require the link:{baseurl}/plugins-ref/opensource/lists/[Lists (`+lists+`)] plugin.

include::partial$commands/lists-cmds.adoc[]

==== Media

The following command requires the link:{baseurl}/plugins-ref/opensource/media/[Media (`+media+`)] plugin.

include::partial$commands/media-cmds.adoc[]

==== Nonbreaking Space

The following command requires the link:{baseurl}/plugins-ref/opensource/nonbreaking/[Nonbreaking Space (`+nonbreaking+`)] plugin.

include::partial$commands/nbsp-cmds.adoc[]

==== Page Break

The following command requires the link:{baseurl}/plugins-ref/opensource/pagebreak/[Page Break (`+pagebreak+`)] plugin.

include::partial$commands/pagebreak-cmds.adoc[]

==== Paste

The following commands require the link:{baseurl}/plugins-ref/opensource/paste/[Paste (`+paste+`)] plugin.

include::partial$commands/paste-cmds.adoc[]

==== Permanent Pen

The following commands require the link:{baseurl}/plugins-ref/premium/permanentpen/[Permanent Pen (`+permanentpen+`)] plugin.

include::partial$commands/permanentpen-cmds.adoc[]

==== PowerPaste

The following command requires the link:{baseurl}/plugins-ref/premium/powerpaste/[PowerPaste (`+powerpaste+`)] plugin.

include::partial$commands/powerpaste-cmds.adoc[]

==== Preview

The following command requires the link:{baseurl}/plugins-ref/opensource/preview/[Preview (`+preview+`)] plugin.

include::partial$commands/preview-cmds.adoc[]

==== Save

The following commands require the link:{baseurl}/plugins-ref/opensource/save/[Save (`+save+`)] plugin.

include::partial$commands/save-cmds.adoc[]

==== Search and Replace

The following command requires the link:{baseurl}/plugins-ref/opensource/searchreplace/[Search and Replace (`+searchreplace+`)] plugin.

include::partial$commands/searchreplace-cmds.adoc[]

==== Spell Checker Pro

The following commands require the link:{baseurl}/plugins-ref/premium/tinymcespellchecker/[Spell Checker Pro (`+tinymcespellchecker+`)] plugin.

include::partial$commands/tinymcespellchecker-cmds.adoc[]

==== Table

The following commands require the link:{baseurl}/plugins-ref/opensource/table/[Table (`+table+`)] plugin.

include::partial$commands/table-cmds.adoc[]

==== Template

The following command requires the link:{baseurl}/plugins-ref/opensource/template/[Template (`+template+`)] plugin.

include::partial$commands/template-cmds.adoc[]

==== Table of Contents

The following commands require the link:{baseurl}/plugins-ref/opensource/toc/[Table of Contents (`+toc+`)] plugin.

include::partial$commands/toc-cmds.adoc[]

==== Visual Blocks

The following command requires the link:{baseurl}/plugins-ref/opensource/visualblocks/[Visual Blocks (`+visualblocks+`)] plugin.

include::partial$commands/visualblocks-cmds.adoc[]

==== Visual Characters

The following command requires the link:{baseurl}/plugins-ref/opensource/visualchars/[Visual Characters (`+visualchars+`)] plugin.

include::partial$commands/visualchars-cmds.adoc[]

==== Word Count

The following command requires the link:{baseurl}/plugins-ref/opensource/visualchars/[Word Count (`+wordcount+`)] plugin.

include::partial$commands/wordcount-cmds.adoc[]

=== Editor Management Commands

The following commands are used to manage editor instances.

For example:

[source,js]
----
tinymce.execCommand('mceAddEditor', false, '<editor_id>');
tinymce.execCommand('mceRemoveEditor', false, '<editor_id>');
tinymce.execCommand('mceToggleEditor', false, '<editor_id>');
----

[cols=",",options="header",]
|===
|Command |Description
|mceAddEditor |Converts the specified HTML or DOM element into an editor instance with the specified ID.
|mceRemoveEditor |Removes an editor instance with the specified ID.
|mceToggleEditor |Runs mceAddEditor if an editor is not detected for the specified ID, otherwise it runs either [hide](\{\{ site.baseurl }}/apis/tinymce/tinymce.editor/#hide) if the editor is visible or [show](\{\{ site.baseurl }}/apis/tinymce/tinymce.editor/#show) if it is not visible.
|===

== Query command states

\{\{site.productname}} provides the `+queryCommandState+` API to allow developers to determine the current state of selected content. The query will return `+true+` if the content is formatted using the same CSS styles and elements used by the corresponding command.

=== Listing core and plugin query command states

To retrieve a list of avaliable queryable states from the active editor, run the following command from the browser console:

[source,js]
----
tinymce.activeEditor.editorCommands.commands.state;
----

=== Available query command states

The following command states can be queried using the [queryCommandState](\{\{ site.baseurl }}/apis/tinymce/tinymce.editorcommands/#querycommandstate) API.

[cols=",",options="header",]
|===
|Command |Description
|Bold |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+Bold+` command.
|InsertDefinitionList |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+InsertDefinitionList+` command.
|InsertOrderedList |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+InsertOrderedList+` command.
|InsertUnorderedList |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+InsertUnorderedList+` command.
|Italic |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+Italic+` command.
|JustifyCenter |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+JustifyCenter+` command.
|JustifyFull |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+JustifyFull+` command.
|JustifyLeft |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+JustifyLeft+` command.
|JustifyRight |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+JustifyRight+` command.
|mceBlockQuote |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+mceBlockQuote+` command.
|Outdent |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+Outdent+` command.
|Strikethrough |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+Strikethrough+` command.
|Subscript |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+Subscript+` command.
|Superscript |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+Superscript+` command.
|ToggleToolbarDrawer |Returns `+true+` if the Toolbar Drawer is open. The state can be controlled by the \{\{site.productname}} `+ToggleToolbarDrawer+` command.
|Underline |Returns `+true+` if the content is formatted using the same markup as the \{\{site.productname}} `+Underline+` command.
|===

*Examples*

[source,js]
----
tinymce.activeEditor.queryCommandState('Bold');
tinymce.activeEditor.queryCommandState('InsertDefinitionList');
tinymce.activeEditor.queryCommandState('InsertOrderedList');
tinymce.activeEditor.queryCommandState('InsertUnorderedList');
tinymce.activeEditor.queryCommandState('Italic');
tinymce.activeEditor.queryCommandState('JustifyCenter');
tinymce.activeEditor.queryCommandState('JustifyFull');
tinymce.activeEditor.queryCommandState('JustifyLeft');
tinymce.activeEditor.queryCommandState('JustifyRight');
tinymce.activeEditor.queryCommandState('mceBlockQuote');
tinymce.activeEditor.queryCommandState('Outdent');
tinymce.activeEditor.queryCommandState('Strikethrough');
tinymce.activeEditor.queryCommandState('Subscript');
tinymce.activeEditor.queryCommandState('Superscript');
tinymce.activeEditor.queryCommandState('ToggleToolbarDrawer');
tinymce.activeEditor.queryCommandState('Underline');
----

== Query command values

\{\{site.productname}} provides the `+queryCommandValue+` API to allow developers to determine the current state of selected content. The query will return an object containing the relevant value.

=== Listing core and plugin query command values

To retrieve a list of avaliable queryable command values from the active editor, run the following command from the browser console:

[source,js]
----
tinymce.activeEditor.editorCommands.commands.value;
----

=== Available query command values

The following command values can be queried using the [queryCommandValue](\{\{ site.baseurl }}/apis/tinymce/tinymce.editorcommands/#querycommandvalue) API.

[cols=",",options="header",]
|===
|Command |Description
|FontName |Returns the font name of the current selection.
|FontSize |Returns the font size of the current selection.
|LineHeight |Returns the line height of the current selection.
|ToggleSidebar |Returns the current state of sidebar (open or closed).
|===

*Examples*

[source,js]
----
tinymce.activeEditor.queryCommandValue('FontName');
tinymce.activeEditor.queryCommandValue('FontSize');
tinymce.activeEditor.queryCommandValue('LineHeight');
tinymce.activeEditor.queryCommandValue('ToggleSidebar');
----

=== Query command values: Table plugin

include::partial$commands/table-query-cmd-values.adoc[]
