= Export to Word
:navtitle: exportword
:description: The export to Word feature lets you generate a .docx file directly from the editor.
:description_short: Generate a .docx file directly from the editor.
:keywords: plugin, exportword.
:pluginname: Export to Word
:plugincode: exportword
:plugincategory: premium

include::partial$misc/admon-paid-addon-pricing.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]

The export to Microsoft Word feature collects the HTML generated with the `tinymce.editor.getContent()` method and combines it with the default editor content styles along with the styles provided in the configuration. The combined content and styles are then transmitted to the {productname} Cloud Services HTML to DOCX converter service. Following this, the service generates a Word file, which is subsequently returned to the user’s browser, enabling them to save it in the Word format onto their disk.

== Interactive example

[NOTE]
.{pluginname} demo
====
Demos containing the {pluginname} plugin are currently only available on our main website. Check out https://www.tiny.cloud/tinymce/features/export-word/[the {pluginname} demo], or the https://www.tiny.cloud/[demo on our home page], to try it out today.
====

[NOTE]
The generated `.docx` file may not be fully compatible with older versions of Word.

[NOTE]
xref:introduction-to-mediaembed.adoc[Enhanced Media Embed] will not be included in the exported document.
== Basic setup

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `plugins` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'exportword',
  toolbar: 'exportword',
  exportword_service_url: '<service_URL>'
});
----

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/{plugincode}.adoc[][leveloffset=+1]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[][leveloffset=+1]

== API Reference

> Explore the comprehensive API documentation for the {pluginname} Premium plugin at https://exportdocx.converter.tiny.cloud/docs#section/Export-to-Word[Export to Word.^]