= {pluginname} plugin
:plugincode: exportword
:pluginname: Export to Word
:navtitle: {pluginname}
:description: The {pluginname} feature lets you generate a .docx (Microsoft Word document) file directly from the editor.
:description_short: Generate a .docx file directly from the editor.
:keywords: plugin, {plugincode}, {pluginname}
:plugincategory: premium

include::partial$misc/admon-export-word-paid-addon-pricing.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]

The export to Microsoft Word feature collects the HTML generated with the `tinymce.editor.getContent()` method and combines it with the default editor content styles along with the styles provided in the plugin configuration. The combined content and styles are then processed by the included server-side converter service, which can be either self-hosted or cloud-based. Following this processing, a Word file is generated, which is subsequently returned to the user's browser, enabling them to save it in the Word format onto their disk or drive.

== Interactive example

liveDemo::exportword[]

[NOTE]
.{pluginname} known issues
====
* The generated `.docx` file may not be fully compatible with older versions of Word.
* xref:introduction-to-mediaembed.adoc[Enhanced Media Embed] will not be included in the exported document, resulting in a console.error _"The Export to Word plugin requires the `exportword_service_url` to be configured"_.
====

== Basic setup using the {companyname} Cloud service

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `plugins` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'exportword',
  toolbar: 'exportword',
  exportword_token_provider: () => { // required when using the Export to Word plugin with Tiny Cloud.
    return fetch('http://localhost:3000/jwt', { // specify your token endpoint
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
    }).then(response => response.json());
  },
});
----

[NOTE]
For more infomation on the exportword_token_provider option, see xref:exportword.adoc#exportword-token-provider[exportword_token_provider]

[IMPORTANT]
====
The {pluginname} plugin **requires** JWT authentication when using the {companyname} Cloud service.

* Configure the `{plugincode}_token_provider` option to specify the endpoint for retrieving a valid JWT token.
* If hosting locally, use the format `+http://localhost:[port]/jwt+`, ensuring the endpoint returns a JSON object containing the token.

For more information on how to set up JWT authentication with {pluginname}, see examples:

* xref:export-to-word-with-jwt-authentication-nodejs.adoc[{pluginname} with JWT authentication (Node.js)]
* xref:export-to-word-with-jwt-authentication-php.adoc[{pluginname} with JWT authentication (PHP)]

**Trial period behavior:**

* The {pluginname} plugin runs in evaluation mode and adds a watermark to exported content.
* The `{plugincode}_token_provider` option is "not required" during the trial period.
* If the trial period "expires" or the plugin lacks the necessary entitlement, it becomes _non-functional_.
* Attempting to use JWT authentication during the trial will result in an _error_.
====






== Basic setup using the self-hosted service

To use the self-hosted version of the {pluginname} plugin, you need to set the `exportword_service_url` option to the URL of the service.

For example:
[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'exportword',
  toolbar: 'exportword',
  exportword_service_url: 'http://localhost:8080/' // Update with the URL of the service you are using such  as 'http://myserver.com/'
});
----

[IMPORTANT]
====
The `exportword_service_url` option automatically appends `/v2/convert/html-docx` to the URL provided, so only the base URL is required. For example, if the service is hosted at `http://localhost:8080/v2/convert/html-docx`, the `exportword_service_url` option should be set to `http://localhost:8080/`. When using in production, ensure that `exportword_service_url` is updated to the production URL such as `https://myserver.com/`.
====

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/exportword_service_url.adoc[leveloffset=+1]

include::partial$configuration/exportword_token_provider.adoc[leveloffset=+1]

include::partial$configuration/exportword_converter_options.adoc[leveloffset=+1]

include::partial$configuration/exportword_converter_style.adoc[leveloffset=+1]

include::partial$configuration/exportword_watermark.adoc[leveloffset=+1]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/exportword-cmds.adoc[][leveloffset=+1]

== API Reference

> Explore the comprehensive API documentation for the {pluginname} Premium plugin at link:https://exportdocx.api.tiny.cloud/v2/convert/docs#section/Export-to-Word[{pluginname} API Reference Documentation.^]
