= Export to PDF plugin
:navtitle: Export to PDF
:description: The Export to PDF feature provides the ability to generate a PDF file directly from the editor.
:description_short: Generate a PDF file directly from the editor.
:keywords: plugin, exportpdf, export to pdf
:pluginname: Export to PDF
:plugincode: exportpdf
:plugincategory: premium


include::partial$misc/admon-export-pdf-paid-addon-pricing.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]

The {pluginname} feature collects the HTML generated with the `tinymce.editor.getContent()` method and combines it with the default editor content styles along with the styles provided in the plugin configuration. The combined content and styles are then processed by the included server-side converter service, which can be either self-hosted or cloud-based. Following this processing, a PDF file is generated, which is subsequently returned to the user’s browser, enabling them to save it onto their disk or drive.

== Interactive example

[NOTE]
.{pluginname} demo
====
Demos containing the {pluginname} plugin are currently only available on our main website. Check out https://www.tiny.cloud/tinymce/features/export-pdf[the {pluginname} demo], or the https://www.tiny.cloud/[demo on our home page], to try it out today.
====

== Basic setup

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `plugins` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'exportpdf',
  toolbar: 'exportpdf',
  exportpdf_service_url: '<service url>'
});
----

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/{plugincode}.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== API Reference

> Explore the comprehensive API documentation for the {pluginname} Premium plugin at https://exportpdf.converter.tiny.cloud/docs[Export to PDF.^]