= Cloud deployment of plugins Only
:description_short: Learn how to setup TinyMCE Plugins via the Tiny Cloud.
:description: Connect to Tiny Cloud within a hybrid deployment.
:keywords: tinymce, cloud, script, textarea, apiKey, hybrid
:productSource: cloud

A hybrid deployment of {cloudname} allows the loading of premium plugins in a self-hosted environment. Download and install the link:{gettiny}/[{productname} Community edition] to get started.

Signing up for a free API key provides entitlements to the premium xref:editimage.adoc[Image Editing] plugin. A {cloudname} image proxy server must already be configured. Premium plugins can be purchased at any time once the API key has been set up.

== Step 1: Insert the custom script tag into the webpage

Add the following script in the webpage once the script tag to load {productname} has been specified. Be sure to substitute 'no-api-key' with your api key.

[source,js,subs="attributes+"]
----
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/{productmajorversion}/plugins.min.js" referrerpolicy="origin"></script>
----

== Step 2: Specify purchased TinyMCE plugins and toolbar buttons

NOTE: It may take up to 30 minutes for the purchased plugin to be available to {productname}. Clear the browser's cache.

Extend the xref:basic-setup.adoc[{productname} configuration] to include any additional purchased plugins and associated toolbar and menu items. Refer to the following enablement guides for more information:

include::partial$misc/premium-plugin-list.adoc[]

include::partial$misc/admon-cloud-configured-options.adoc[]

The following is a complete example, where:

* The {cloudname} `+API key+` has the value `+no-api-key+`.
* The {cloudname} has the xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro] plugin enabled.

[source,js,subs="attributes+"]
----
<html>
   <head>
      <script src="https://your_server/tinymce.min.js"></script>
      <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/{productmajorversion}/plugins.min.js" referrerpolicy="origin"></script>
   </head>
   <body>
      <textarea><p>test textarea</p></textarea>
      <script>
         tinymce.init({
            selector: 'textarea',
            height: 500,
            plugins: [
               'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview', 'anchor',
               'pagebreak', 'tinymcespellchecker'
            ]
         });
      </script>
   </body>
<html>
----

== Step 3: Forward proxy configuration

Ensure that the following URLs are accessible via this proxy if the network has a forward proxy that controls access to the internet.

* All URLs where the editor is deployed.
* All URLs where the plugins are deployed.
* +https://imageproxy.tiny.cloud+
* +https://hyperlinking.tiny.cloud+
* +https://spelling.tiny.cloud+

Ensure the `+tiny-api-key+` and `+tinymce-api-key+` headers are retained while requesting the list of above URLs.
