= Footnotes plugin
:navtitle: Footnotes
:description: Insert footnotes into the {productname} editor
:keywords: footnotes, footnote, insertfootnotes, insert, footnotesupdate, mceInsertFootnote, mceUpdateFootnotes
:pluginname: Footnotes
:plugincode: footnotes
:pluginminimumplan: tierthree

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-requires-6.2v.adoc[]

The {pluginname} plugin allows the user to insert a footnote into the {productname} editor.

Each time a footnote is added, a superscripted footnote number is placed at the current insertion point, or at the end of the current selection.

The plugin then adds a new line to the footnotes section located at the bottom of the editor and moves the insertion point to this new line. This allows for the immediate creation of the contents of the footnote entry related to the newly-created footnote

== Interactive Example

liveDemo::footnotes[]

include::partial$misc/purchase-premium-plugins.adoc[]

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'footnotes',
  toolbar: 'footnotes',
});
----

The footnotes section, which is placed at the bottom of the {productname} editor, is created when the first footnote is added.

Footnotes can be inserted using the _Insert footnote_ button on the toolbar, or the _Insert footnote_ command in the _Insert_ menu.

The footnotes section is automatically updated whenever a footnote is inserted, reordered, or removed within the {productname} editor. (And the footnotes section is automatically removed if all footnotes are removed.)

For example, adding a new footnote between already extant footnotes ~*1*~ and ~*2*~ results in the new footnote becoming footnote ~*2*~ and the previous footnote ~*2*~ automatically becoming footnote ~*3*~.

Superscripted footnote numbers can also be dragged to a different position in the document. Footnote numbers and their relationship with the respective footnote entry are automatically updated when they are dragged to a different position.

Each superscripted footnote number links to its respective footnote entry, and each footnote entry is prefixed with a caret — ~*^*~ — that links back to its respective superscripted footnote number. This allows for navigation between the editor content and the footnotes section.

If the TinyMCE document is large enough to produce a scroll bar, clicking the caret prefixing a footnote entry scrolls the document back to the line containing said entry’s superscripted footnote number.

NOTE: Although the viewport scrolls back to the line containing the footnote number, the insertion point is not changed. Users must move the insertion point by, for example, clicking the I-beam pointer somewhere in the now-scrolled document.

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/footnotes-cmds.adoc[]