= Footnotes plugin
:navtitle: Footnotes
:description: Insert footnotes into the {productname} editor
:keywords: footnotes, footnote, insertfootnotes, insert, footnotesupdate, mceInsertFootnote, mceUpdateFootnotes
:pluginname: Footnotes
:plugincode: footnotes
:pluginminimumplan: tierthree

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-requires-6.2v.adoc[]

The {pluginname} plugin allows the user to insert a footnote into the {productname} editor.

Each time a footnote is added, a superscripted footnote number is placed at the current insertion point, or at the end of the current selection.

The plugin then adds a new line to the footnotes section located at the bottom of the editor and moves the insertion point to this new line. This allows for the immediate creation of the contents of the footnote entry related to the newly-created footnote.

== Interactive Example

liveDemo::footnotes[]

// include::partial$misc/purchase-premium-plugins.adoc[]

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'footnotes',
  toolbar: 'footnotes',
});
----

The footnotes section, which is placed at the bottom of the {productname} editor, is created when the first footnote is added.

Footnotes can be inserted with

* the _Insert footnote_ button, located on the toolbar;
* the _Insert > Insert Footnote_ command from the menu bar;
* or the `+mceInsertFootnote+` command.

The footnotes section is automatically updated whenever a footnote is inserted, reordered, or removed within the {productname} editor. The footnotes section is automatically removed if all footnotes are removed.

For example, adding a new footnote between already extant footnotes ^*1*^ and ^*2*^ results in the new footnote becoming footnote ^*2*^ and the previous footnote ^*2*^ automatically becoming footnote ^*3*^.

Superscripted footnote numbers can also be dragged to a different position in the document. Footnote numbers and their relationship with the respective footnote entry are automatically updated when they are dragged to a different position.

Each superscripted footnote number links to its respective footnote entry, and each footnote entry is prefixed with a caret — *^* — that links back to its respective superscripted footnote number. This allows for navigation between the editor content and the footnotes section.

If the {productname} document is large enough to produce a scroll bar, clicking the caret prefixing a footnote entry scrolls the document back to the line containing said entry’s superscripted footnote number.

NOTE: Although the viewport scrolls back to the line containing the footnote number, the insertion point is not changed. Users must move the insertion point by, for example, clicking the I-beam pointer somewhere in the now-scrolled document.


== CSS

The following CSS is used in the internal `+content.css+` within {productname}. It can be overridden with a custom xref:add-css-options.adoc#content_css[`+content_css+`] stylesheet.

To make footnotes display correctly outside of {productname}, add this CSS to the published webpage.

[source,css]
----
include::example$css-codeblock/footnotes-plugin.css[]
----


== Usage notes

=== The update footnotes button

The update footnotes button, as its name implies, updates the state of all footnotes in a {productname} document.

To add the update footnote button to the {productname} toolbar, add `footnotesupdate` to the `toolbar`.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'footnotes',
  toolbar: 'footnotes footnotesupdate',
});
----

In the main, footnotes update automatically as they are added, removed, or edited. However, there are some circumstances where user-edits change footnote state but the footnotes themselves do not update.

For example, when an image caption with an attached footnote is removed (by unchecking the _Show caption_ checkbox in the *Insert/Edit Image* dialog), the associated footnote text is not automatically removed.

In similar fashion, if a table row or column that contains a footnote is removed, the associated footnote text is not automatically removed.

These orphan footnote texts can be deleted manually. They can also be removed by clicking the `footnotesupdate` button in the toolbar.


=== Formatting superscripted footnote numbers

. Superscripted footnote numbers cannot be inline-formatted
+
If a selected string includes a superscripted footnote number and inline-formatting is applied to that string, the superscripted footnote number does not take on the applied formatting.
+
Inline-formatting includes setting a string to *Bold* or _Italic_ or `monospaced`.

. Superscripted footnote numbers can be block-formatted
+
If a selected string includes a superscripted footnote number and block-formatting is applied to that string, the superscripted footnote number takes on the applied formatting.
+
Block-formatting includes making a selection a Heading of any level or setting the selection to `Preformatted`.

=== Formatting footnote text

. Footnote text can be inline-formatted
+
Footnote text can be formatted using inline-formatting options such as *Bold*, _Italic_, or `monospaced`.

. Footnote text cannot be block-formatted
+
Footnote text cannot, for example, be made into a Heading, or set as `Preformatted`.

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/footnotes-cmds.adoc[]
