= Footnotes plugin
:navtitle: Footnotes
:description: Insert footnotes into the {productname} editor
:keywords: footnotes, footnote, insertfootnotes, insert, footnotesupdate, mceInsertFootnote, mceUpdateFootnotes
:pluginname: Footnotes
:plugincode: footnotes
:pluginminimumplan: tiertwo

include::partial$misc/admon-premium-plugin.adoc[]

The {pluginname} plugin allows the user to insert a footnote into the {productname} editor.

Invoking the plugin adds a superscripted footnote number at the current insertion point, or at the end of the current selection.

The plugin then places the insertion point in a new line in the footnotes section located at the bottom of the editor, allowing the user to add the footnote entry related to the newly-created footnote.

== Interactive Example

liveDemo::footnotes[]

include::partial$misc/purchase-premium-plugins.adoc[]

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'footnotes',
  toolbar: 'footnotes footnotesupdate',
});
----

A footnotes section is automatically created and updated whenever a footnote is inserted into the {productname} editor.

This footnotes section is placed at the bottom of the {productname} editor.

Footnotes can be inserted using the _Insert footnote_ button on the toolbar, or the _Insert footnote_ command in the _Insert_ menu. 

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/footnotes-cmds.adoc[]