= Full Page HTML Plugin
:navtitle: Full Page HTML
:description: Edit metadata and document properties including title, keywords, and description via a dialog box, with HTML structure exposure in source code view.
:description_short: Edit document metadata and properties with dialog interface and source code exposure.
:keywords: full page html, metadata, document properties, title, keywords, description, HTML structure, source code
:pluginname: Full Page HTML
:plugincode: fullpagehtml
:plugincategory: premium

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-inline-not-supported.adoc[]

The {pluginname} plugin provides comprehensive control over document metadata and properties. It enables users to edit HTML document metadata such as title, keywords, and description through an intuitive dialog interface. When combined with the code plugin, it also exposes the complete HTML structure including `<head>`, `<body>`, and various meta tags in the source code view.


== Interactive example


liveDemo::{plugincode}[]

== Basic setup

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `plugins` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'fullpagehtml',
  toolbar: 'fullpagehtml',
  fullpagehtml_default_doctype: '<!DOCTYPE html>'
});
----

[WARNING]
====
**Meta tags may be removed by XSS sanitization**

By default, {productname} sanitizes HTML content to protect against XSS attacks, which may remove certain meta tags from the full page HTML. If integrators experience issues with meta tags being removed, the following configuration options are available, though not advisable:

* `xss_sanitization: false` - Disables DOMPurify.
* `+valid_elements: '*[*]'+` - Allows all elements and attributes.

See xref:security.adoc#xss_sanitization-option[xss_sanitization option] and xref:content-filtering.adoc#valid_elements[valid_elements option] for more information.

**Preserving meta tags (advanced configuration)**

If meta tags are being removed by XSS sanitization, the editor can be configured to preserve them using one of the following approaches, though these options are **not recommended**:

.Example: using `+xss_sanitization+` to disable DOMPurify
[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'fullpagehtml',
  toolbar: 'fullpagehtml',
  xss_sanitization: false  // Disables DOMPurify, TinyMCE's built-in XSS sanitization which allows potentially unsafe HTML content to be inserted
});
----

.Example: using `+valid_elements+` to allow all elements and attributes
[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'fullpagehtml',
  toolbar: 'fullpagehtml',
  valid_elements: '*[*]'  // Allows all elements and attributes - use with caution
});
----
====

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/fullpagehtml-default-doctype.adoc[leveloffset=+1]

include::partial$configuration/fullpagehtml-default-title.adoc[leveloffset=+1]

include::partial$configuration/fullpagehtml-default-encoding.adoc[leveloffset=+1]

include::partial$configuration/fullpagehtml-default-body-style.adoc[leveloffset=+1]

include::partial$configuration/fullpagehtml-hide-in-source-view.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$toolbar-button-ids/{plugincode}-toolbar-buttons.adoc[leveloffset=+1]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

include::partial$menu-item-ids/{plugincode}-menu-items.adoc[leveloffset=+1]

== Commands

The {pluginname} plugin provides the following {productname} command.

include::partial$commands/fullpagehtml-cmds.adoc[leveloffset=+1]