= Get help
:description: Details on how to get help if you get stuck in getting Tiny Drive up and running
:keywords: help
:title_nav: Get help

== Get help with Tiny Drive

To implement {cloudfilemanager}, you need prior knowledge of JWT in detail, including how they can be used for user authentication and session management in a web application. There will be some coding involved on both the client-side and the server-side to configure JWT as per the instructions in this section.

Getting started with {cloudfilemanager} can be tricky if you are new to JWT. We recommend reading up and trying to understand how xref:tinydrive-jwt-authentication.adoc[JWT authentication] works.

If you haven't tried any of the xref:tinydrive-getting-started.adoc#starterprojects[Starter projects], we recommend you try them before trying to implement your own solution. The source is also available on Github to study.

For support related issues such as problems with JWT authentication and implementing {cloudfilemanager} link:{supporturl}[submit a support request].
