= Get Support &amp; FAQ
:description: Community and pro-grade support options.
:keywords: forum forums url absolute relative security xss
:title_nav: Support &amp; FAQ

== Premium support

Paid premium support is available as part of link:{pricingpage}[{enterpriseversion} and {cloudname} subscriptions]. {productname} Enterprise customers can xref:support.adoc[submit a case support request].

== Community support

Open Source Community Edition users can get free help from Stack Overflow using the link:{communitysupporturl}[`{prodnamecode}` tag].

== FAQ & troubleshooting

=== Q: The icons are missing when installing on my server?

Some web servers do not support the mime types needed for the font file extensions. Below are the mime types required - the first part is the mime type the second part is the file extension that needs to be mapped. It's in apache mime type format. Other servers might need a different format.

|===
| MIME type | File Extension

| image/svg+xml
| svg
|===

=== Q: Why do buttons/select boxes have the incorrect size?

You are probably using an old `DOCTYPE`. As of {productname} 4, a proper HTML5 doctype is required. All web developers should use a standard rendering mode on their web pages. Use a HTML5 doctype like `<!DOCTYPE html>` to properly render the page and the {productname} UI.

=== Q: Is TinyMCE protected against XSS vulnerabilities?

The server should have protection against XSS attacks implemented. Since if you can submit contents in a form using {productname} one could as easily disable all JavaScript and therefore bypass {productname} filtering and still submit HTML code with insecure content. You need to properly filter the HTML input on the server using things like http://htmlpurifier.org/[HTML Purifier].

=== Q: How do I convert my URLs to relative, absolute, or absolute with the domain?

==== Relative URLs

The *Relative URLs* converts all URLs within the same domain to relative URLs. The URLs are relative from the `document_base_url`.

[source, js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : true,
  document_base_url : 'http://www.site.com/path1/'
});
----

===== Example: Relative URLs

`+http://www.site.com/path1/path2/file.htm >> path2/file.htm+`

===== Example: Relative URLs on links and images

liveDemo::url-conversion-relative-1[]

===== Example: Relative URLs on links and images to a specific page

liveDemo::url-conversion-relative-2[]

==== Absolute URLs

The *Absolute URLs* converts all relative URLs to absolute URLs. The URLs are `absolute` based on the `document_base_url`.

[source, js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : false,
  remove_script_host : true,
  document_base_url : 'http://www.site.com/path1/'
});
----

===== Example: Absolute URLs

`path2/file.htm >> /path1/path2/file.htm`

===== Example: Absolute URLs on links and images

liveDemo::url-conversion-absolute-1[]

===== Example: Absolute URLs and including domain on links and images

liveDemo::url-conversion-absolute-2[]

==== Domain absolute URLs

The *Domain absolute URLs* converts all relative URLs to absolute URLs. The URLs are `absolute` based on the `document_base_url` with the domain.

[source, js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : false,
  remove_script_host : false,
  document_base_url : 'http://www.site.com/path1/'
});
----

===== Example: Domain absolute URLs

`+path2/file.htm >> http://www.site.com/path1/path2/file.htm+`
