= Help plugin
:controls: toolbar button, menu item
:description: Shows the help dialog.
:keywords: help
:title_nav: Help

:pluginname: Help
:plugincode: help

The help plugin adds a button and/or menu item that opens a dialog showing two tabs:

* Handy shortcuts that explain some nice-to-know keyboard shortcuts
* Plugin list that shows which plugins that have been installed, with links to the relevant documentation pages if available, and a list of available premium plugins.

In the footer of the dialog you can also see which version of {productname} you are using.

The help dialog can also be shown by pressing the keyboard shortcut `Alt + 0`.

== Basic setup

[source, js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'help',
  toolbar: 'help'
});
----

== Config Options

include::partial$configuration/help_tabs.adoc[]

[[api]]
== API

|===
| Name | Arguments | Description

| addTab
| tabSpec: xref:dialog-components.adoc#tabpanel[TabPanel]
| Register a tab for the Help dialog
|===

=== Example: Using the `addTab` API

[source, js]
----
tinymce.activeEditor.plugins.help.addTab({
  name: 'custom',
  title: 'My Custom Tab',
  items: [
    {
      type: 'htmlpanel',
      html: '<p>This is a custom tab</p>',
    }
  ]
});
----

== Exposing metadata for the help plugin

For information on how to expose metadata from you custom plugin to add it to the Installed plugins list in the Help plugin, see the  xref:creating-a-plugin.adoc[Creating a Plugin page].

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The Help plugin provides the following JavaScript command.

include::partial$commands/help-cmds.adoc[]
