= Help plugin

:title_nav: Help :description: Shows the help dialog. :keywords: help :controls: toolbar button, menu item

\{% assign pluginname = "Help" %} \{% assign plugincode = "help" %}

The help plugin adds a button and/or menu item that opens a dialog showing two tabs:

* Handy shortcuts that explains some nice-to-know keyboard shortcuts
* Plugin list that shows which plugins that have been installed, with links to the relevant documentation pages if available, and a list of available premium plugins.

In the footer of the dialog you can also see which version of \{\{site.productname}} you are using.

The help dialog can also be shown by pressing the keyboard shortcut `+Alt + 0+`.

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'help',
  toolbar: 'help'
});
----

== Config Options

\{% include configuration/help_tabs.md %}

== API

[cols=",,",options="header",]
|===
|Name |Arguments |Description
|addTab |tabSpec: link:{{site.baseurl}}/how-to-guides/creating-custom-ui-components/dialogs/dialog-components/#tabpanel[TabPanel] |Register a tab for the Help dialog
|===

=== Example: Using the `+addTab+` API

[source,js]
----
tinymce.activeEditor.plugins.help.addTab({
  name: 'custom',
  title: 'My Custom Tab',
  items: [
    {
      type: 'htmlpanel',
      html: '<p>This is a custom tab</p>',
    }
  ]
});
----

== Exposing metadata for the help plugin

For information on how to expose metadata from you custom plugin to add it to the Installed plugins list in the Help plugin, see the [Creating a Plugin page](\{\{ site.baseurl }}/how-to-guides/creating-custom-ui-components/making-plugins/creating-a-plugin/#exposingmetadata).

\{% include misc/plugin-toolbar-button-id-boilerplate.md %}

\{% include misc/plugin-menu-item-id-boilerplate.md %}

== Commands

The Help plugin provides the following \{\{site.productname}} command.

\{% include commands/help-cmds.md %}
