= Image plugin
:navtitle: Image
:description: Insert an image into TinyMCE.
:keywords: photo, insert, edit, style, format, image_caption, image_list, image_advtab, image_title, image_class_list, image_prepend_url, image_description, image_dimensions, image_title, image_prepend_url
:pluginname: Image
:plugincode: image

This plugin enables the user to insert an image into {productname}'s editable area. The plugin also adds a toolbar button and an `+Insert/edit image+` menu item under the `+Insert+` menu.

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'image',
  toolbar: 'image',
  image_list: [
    { title: 'My image 1', value: 'https://www.example.com/my1.gif' },
    { title: 'My image 2', value: 'http://www.moxiecode.com/my2.gif' }
  ]
});
----

NOTE: This is not drag-drop functionality and the user is required to enter the path to the image. Optionally the user can also enter the image description, dimensions, and whether image proportions should be constrained (selected via a checkbox). Some of these settings can be preset using the plugin's configuration options.

include::partial$misc/admon-svg-not-supported.adoc[]

== Options

These configuration options affect the execution of the `+image+` plugin. Many of the settings here will disable dialog box features used to insert or edit images. A predefined list of images can also be provided to enable quick insertion of those images.

If you wish to align the image, you can also use the text align buttons while images are selected.

:includedSection: imagePlugin
include::partial$configuration/a11y_advanced_options.adoc[leveloffset=+1]
:!includedSection:

include::partial$configuration/file_picker_callback.adoc[leveloffset=+1]

include::partial$configuration/file_picker_types.adoc[leveloffset=+1]

include::partial$configuration/image_caption.adoc[leveloffset=+1]

include::partial$configuration/image_list.adoc[leveloffset=+1]

include::partial$configuration/image_advtab.adoc[leveloffset=+1]

include::partial$configuration/image_class_list.adoc[leveloffset=+1]

include::partial$configuration/image_description.adoc[leveloffset=+1]

include::partial$configuration/image_dimensions.adoc[leveloffset=+1]

include::partial$configuration/image_prepend_url.adoc[leveloffset=+1]

include::partial$configuration/image_title.adoc[leveloffset=+1]

include::partial$configuration/image_uploadtab.adoc[leveloffset=+1]

include::partial$configuration/images_file_types.adoc[leveloffset=+1]

include::partial$configuration/images_upload_base_path.adoc[leveloffset=+1]

include::partial$configuration/images_upload_credentials.adoc[leveloffset=+1]

include::partial$configuration/images_upload_handler.adoc[leveloffset=+1]

include::partial$configuration/images_upload_url.adoc[leveloffset=+1]

include::partial$configuration/object_resizing.adoc[leveloffset=+1]

include::partial$configuration/resize_img_proportional.adoc[leveloffset=+1]

include::partial$configuration/type_ahead_urls.adoc[leveloffset=+1]

== Q: Where are the advanced image options?

Use the `+Style Formats+` option instead, which is much more powerful.

[source,js]
----
style_formats: [
  {
    title: 'Image Left',
    selector: 'img',
    styles: {
      float: 'left',
      margin: '0 10px 0 10px'
    }
  },
  {
    title: 'Image Right',
    selector: 'img',
    styles: {
      float: 'right',
      margin: '0 10px 0 10px'
    }
  }
]
----

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The Image plugin provides the following {productname} command.

include::partial$commands/image-cmds.adoc[]
