
= {pluginname} plugin
:plugincode: importword
:pluginname: Import from Word
:pluginfilename: import-from-word
:navtitle: {pluginname}
:description: Provides a way to import .docx (Microsoft Word documents) or .dotx (Microsoft Word templates) files into the editor.
:description_short: Import .docx or .dotx files into the editor.
:keywords: plugin, {plugincode}, {pluginname}
:plugincategory: premium

include::partial$misc/admon-import-word-paid-addon-pricing.adoc[]


The {pluginname} plugin lets you import `.docx` (Word document) or `.dotx` (Word template) files into the editor. The process preserves formatting and rich media.

== Interactive example

liveDemo::importword[]

== Basic setup using the {companyname} Cloud service

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `plugins` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'importword',
  toolbar: 'importword',
// Below option is only required when using the cloud-based Import from Word plugin from Tiny.Cloud.
// Avoid setting it up during the trial period.
  importword_token_provider: () => { // required when using the Import from Word plugin with Tiny Cloud.
    return fetch('http://localhost:3000/jwt', { // specify your token endpoint
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
    }).then(response => response.json());
  },
});
----

For more infomation on the importword_token_provider option, see xref:importword.adoc#importword-token-provider[importword_token_provider].

include::partial$misc/admon-jwt-authentication-requirements.adoc[]


== Basic setup using the self-hosted service

To use the self-hosted version of the {pluginname} plugin, you need to set the `importword_service_url` option to the URL of the service.

.Example:
[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'importword',
  toolbar: 'importword',
  importword_service_url: 'http://localhost:8080/' // Update with the URL of the service you are using such  as 'http://myserver.com/'
});
----

[IMPORTANT]
====
The `importword_service_url` option automatically appends `/v2/convert/docx-html` to the URL provided, so only the base URL is required. For example, if the service is hosted at `http://localhost:8080/v2/convert/docx-html`, the `importword_service_url` option should be set to `http://localhost:8080/`. When using in production, ensure that the `importword_service_url` is updated to the production URL such as `https://myserver.com/`.
====

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/importword_service_url.adoc[leveloffset=+1]

include::partial$configuration/importword_token_provider.adoc[leveloffset=+1]

include::partial$configuration/importword_converter_options.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/importword-cmds.adoc[]

== API Reference

> Explore the comprehensive API documentation for the {pluginname} Premium plugin at link:https://importdocx.api.tiny.cloud/v2/convert/docs#section/Import-from-Word[{pluginname} API Reference Documentation.^]
