
= Import from Word plugin
:navtitle: Import from Word
:description: Provides a way to import .docx (Word documents) or .dotx (Word templates) files into the editor.
:description_short: Import .docx or .dotx files into the editor.
:keywords: plugin, importword, import from word
:pluginname: Import from Word
:plugincode: importword
:plugincategory: premium

include::partial$misc/admon-import-word-paid-addon-pricing.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]


The {pluginname} plugin lets you import `.docx` (Word document) or `.dotx` (Word template) files into the editor. The process preserves formatting and rich media.

== Interactive example

[NOTE]
.{pluginname} demo
====
Demos containing the {pluginname} plugin are currently only available on our main website. Check out https://www.tiny.cloud/tinymce/features/import-from-word[the {pluginname} demo], or the https://www.tiny.cloud/[demo on our home page], to try it out today.
====

== Basic setup

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `plugins` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'code importword',
  toolbar: 'importword code',
  importword_service_url: '<service_URL>'
});
----

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/{plugincode}.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== API Reference

> Explore the comprehensive API documentation for the {pluginname} Premium plugin at link:https://importdocx.converter.tiny.cloud/v2/convert/docs#section/Import-from-Word[Import from Word.^]