= Installing {productname}
:navtitle: Installation
:description: Learn how to install {productname} via {cloudname}, package managers, self-hosted zips for various integration options.
:page-aliases: integrations.adoc


== Quick start guides

[cols=2*a]
|===

|
[.lead]
xref:cloud-quick-start.adoc[Cloud quick start]

Get started with {productname} using the {cloudname} in minutes.
|
|===

== Integrations

Get started with {productname} in your preferred integration:

=== Supported Integrations

The following packages are thin wrappers around {productname} to make it easier to integrate into your project:

[cols=2*a]
|===

|
[.lead]
xref:react-cloud.adoc[React]

Integrate {productname} into your React application using the {cloudname}.

|
[.lead]
xref:angular-cloud.adoc[Angular]

Integrate {productname} into your Angular application using the {cloudname}.

|
[.lead]
xref:vue-cloud.adoc[Vue.js]

Integrate {productname} into your Vue.js application using the {cloudname}.

|
[.lead]
xref:blazor-cloud.adoc[Blazor]

Integrate {productname} into your Blazor application using the {cloudname}.

|
[.lead]
xref:svelte-cloud.adoc[Svelte]

Integrate {productname} into your Svelte application using the {cloudname}.

|
[.lead]
xref:webcomponent-cloud.adoc[Web Component]

Integrate {productname} as a web component using the {cloudname}.

|
[.lead]
xref:jquery-cloud.adoc[jQuery]

Integrate {productname} with the jQuery JavaScript library using the {cloudname}.

// Empty cell to even out rows
|
|===

=== Backend Integrations

[cols=2*a]
|===

|
[.lead]
xref:django-cloud.adoc[Django]

Integrate {productname} into your Django application using the {cloudname}.

|
[.lead]
xref:laravel-tiny-cloud.adoc[Laravel]

Integrate {productname} into your Laravel application using the {cloudname}.

|
[.lead]
xref:rails-cloud.adoc[Ruby on Rails]

Integrate {productname} into your Ruby on Rails application using the {cloudname}.

// Empty cell to even out rows
|

|===

=== Other Integrations

[cols=2*a]
|===


|
[.lead]
xref:bootstrap-cloud.adoc[Bootstrap]

Integrate {productname} with the Bootstrap CSS framework using the {cloudname}.
|
|===
