= Enhanced Media Embed plugin

:title_nav: Enhanced Media Embed
:description: Add rich media previews inside TinyMCE.
:keywords: video youtube vimeo mp3 mp4 mov movie clip film spotify
:pluginname: Enhanced Media Embed
:plugincode: mediaembed
:altplugincode: nil
:pluginminimumplan: tiertwo


include::partial$misc/admon_premium_plugin.adoc[]

The *Enhanced Media Embed* plugin is a link:{pricingpage}/[premium {productname} plugin] that will take a URL, send it to a backend service that returns an embeddable snippet of code, and add that code to the editor. That typically takes the form of rich media such as audio, video and social media cards.

== Interactive example

liveDemo::mediaembed[ ]

include::partial$misc/purchase-premium-plugins.adoc[]

== Installation

For the moment the *Enhanced Media Embed* plugin has to be used in conjunction with the xref:media.adoc[media] plugin, so:

. Make sure you have the `+media+` plugin added to the `+plugins+` list.
. Add the `+mediaembed+` plugin to the `+plugins+` list.

=== Example Cloud Configuration

The service URL is already configured with xref:editor-and-features.adoc[{cloudname}]. Simply specify the `+media+` and `+mediaembed+` plugins, and optionally a `+mediaembed_max_width+`

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'media mediaembed',
  mediaembed_max_width: 450
});
----

=== Example Self-hosted Configuration

In a Self-hosted installation, please ensure you configure the URL to the service with the `+mediaembed_service_url+` parameter.

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'media mediaembed',
  mediaembed_service_url: 'SERVICE_URL',
  mediaembed_max_width: 450
});
----

=== CSS

To make the embeddable snippets display correctly on your site, be sure to add the required summary card CSS.

[source,css]
----
include::partial$css-codeblock/mediaembed-plugin-css.adoc[]
----

== Usage

The plugin can be used in two ways, either by simply entering a URL on an empty line and pressing the enter key - or by entering the URL into the media plugin's dialog window. Either way the URL will be handled by the service backend and the returned code will be embedded into the editor.

== Configuration Options

include::partial$configuration/mediaembed_inline_styles.adoc[leveloffset=+1]

include::partial$configuration/mediaembed_service_url.adoc[leveloffset=+1]

include::partial$configuration/mediaembed_max_width.adoc[leveloffset=+1]

== Downloading Enhanced Media Embed plugin

A link:{pricingpage}/[{enterpriseversion} subscription] includes the ability to download and install the *Media Embed* plugin and a *WAR* file to access the service backend. Please follow these xref:introduction-to-premium-selfhosted-services.adoc#set-up-editor-client-instances-to-use-the-server-side-functionality[instructions] to configure the *WAR* file.
