= Commenting &amp; collaboration
:description: The Comments plugin provides the ability to add comments to the content and collaborate with other users for content editing.
:keywords: enterprise pricing comment commenting
:title_nav: Commenting &amp; collaboration

The Comments plugin provides an ability to start or join a conversation by adding comments to the content within the {productname} editor.

Users can now add comments to their text from within their {productname} editor for collaboration, review, and providing feedback.

== Collaborate on your projects within your content

The Comments plugin offers the following primary functionality:

* A *user interface* to collaborate on content by creating and replying to comments.
* A way to control the delete operation on a comment/comment thread if you want to remove it from your content.

== Primary Comments Functions

The Comments plugin allows the user to perform the following functions:

* Create a comment
* Reply to a comment
* Delete a comment/comment thread
* Lookup a comment
* Edit a comment

== Try our Comments plugin demo

liveDemo::comments-embedded[]

:pluginname: Comments
:pluginminimumplan: enterprise
:plugindocspage: introduction_to_tiny_comments.adoc
include::partial$misc/purchase-premium-plugins.adoc[]
