= Server-side component installation
:description: Server-side components for premium plugins like spelling as-you-type.
:keywords: enterprise, tinymcespellchecker, spell check, Spell Checker, editimage, server

Some {productname} Enterprise features require server-side components. If you're using the {cloudname} solution, we've done all the hard work for you and you can skip this page. Alternatively, if you've purchased our Self-hosted solution then please read on.

IMPORTANT: As of {productname} 8.0, server-side components are only supported using Docker containers. The older Java application server-based deployment (.war files) has been deprecated.

The following server-side components are included in the {productname} Self-hosted package:

[cols="<,<",options="header"]
|===
|Component |Description  
|xref:introduction-to-tiny-spellchecker.adoc[Spellchecking], xref:autocorrect.adoc[Spelling Autocorrect] |Spell checking and Autocorrect service for {productname} Enterprise
|xref:editimage.adoc[Image Editing] |Image proxy service for the Export and Image Editing plugins
|xref:introduction-to-mediaembed.adoc[Enhanced Media Embed], xref:linkchecker.adoc[Link Checker] |Link Checker and Enhanced Media Embed service for {productname} Enterprise
|===

NOTE: The configuration of xref:configure-required-services.adoc#allowed-origins[allowed origins] should be specified directly in the Docker container configuration file.

[[deploy-server-side-components]]
== Deploying server-side components using Docker

[IMPORTANT]
====
A valid access token is required to access the {companyname} Cloud Docker registry and pull the Docker images. Contact link:https://www.tiny.cloud/contact/[{companyname} Support^] to request the access token.
====

=== Requirements

* The link:https://docs.docker.com/engine/docker-overview/[Docker Engine^] is installed and running
* Administrative or Root user access to run Docker commands
* Either:
** A Unix-like operating system (Linux or macOS)
** Windows with Unix command line tools via link:https://gitforwindows.org/[Git for Windows^], link:https://www.cygwin.com/[Cygwin^], or link:https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux^]

For detailed requirements and setup instructions for each service, refer to:

* For Spellchecking and Autocorrect services, see: xref:individual-spelling-container.adoc[Deploy the Spelling server-side component using Docker]
* For Image Editing service, see: xref:individual-image-proxy-container.adoc[Deploy the Image Proxy server-side component using Docker]
* For Enhanced Media Embed and Link Checker services, see: xref:individual-hyperlinking-container.adoc[Deploy the Hyperlinking server-side component using Docker]

=== Configuration

Each service requires configuration to function properly. For details on configuring each service, refer to:

* For Spellchecking and Autocorrect services, see the Configuration section in xref:individual-spelling-container.adoc[Deploy the Spelling server-side component using Docker]
* For Image Editing service, see the Configuration section in xref:individual-image-proxy-container.adoc[Deploy the Image Proxy server-side component using Docker]
* For Enhanced Media Embed and Link Checker services, see the Configuration section in xref:individual-hyperlinking-container.adoc[Deploy the Hyperlinking server-side component using Docker]

[IMPORTANT]
.HTTP proxy
====
If you are relying on an HTTP proxy for outgoing HTTP/HTTPS connections to the Internet, the proxy configuration can be set directly in the Docker container configuration as discussed in the documentation for each service.
====

[[set-up-editor-client-instances-to-use-the-server-side-functionality]]
== Set up editor client instances to use the server-side functionality

Once you have the Docker containers deployed and running, you'll need to tell your {productname} instances where to find them:

* Set the {productname} `+spellchecker_rpc_url+` and `+autocorrect_service_url+` configuration properties to the URL where the spelling service is running
* Set the {productname} `+editimage_proxy_service_url+` and `+export_image_proxy_service_url+` configuration properties to the URL where the image proxy service is running
* Set the {productname} `+mediaembed_service_url+` and `+linkchecker_service_url+` configuration properties to the URL where the hyperlinking service is running

For example, if your services are exposed as follows:
- Spelling service on port 18080
- Image proxy service on port 19040
- Hyperlinking service on port 19100 

Example of {productname} client configuration:

[source,js]
----
tinymce.init({
  selector: 'textarea', // change this value according to your HTML
  toolbar: 'image',
  plugins: 'tinymcespellchecker image editimage media mediaembed',
  spellchecker_rpc_url: 'http://yourserver.example.com:18080',
  autocorrect_service_url: 'http://yourserver.example.com:18080',
  editimage_proxy_service_url: 'http://yourserver.example.com:19040',
  export_image_proxy_service_url: 'http://yourserver.example.com:19040',
  mediaembed_service_url: 'http://yourserver.example.com:19100',
  linkchecker_service_url: 'http://yourserver.example.com:19100'
});
----
