= Spell Checker plugin
:navtitle: Spell Checker
:description: Check spelling as-you-type in TinyMCE.
:keywords: tinymcespellchecker, spellchecker_language, spellchecker_languages, spellchecker_rpc_url, spellchecker_dialog, ephox
:pluginname: Spell Checker
:plugincode: tinymcespellchecker
:pluginminimumplan: tierthree

include::partial$misc/admon-premium-plugin.adoc[]

*Spell Checker* adds spell checking as-you-type capabilities to {productname}. For information on the supported languages, refer to xref:spellchecker_language[this] section.

== Interactive example

liveDemo::spellchecker[]

// include::partial$misc/purchase-premium-plugins.adoc[]

== Cloud Installation

To enable the {productname} Enterprise Spellchecking plugin with xref:editor-and-features.adoc[{cloudname}], add `+tinymcespellchecker+` to the `+plugins+` list.

With {cloudname} the server-side spellchecking component is automatically configured, so the `+spellchecker_rpc_url+` parameter does not need to be set.

=== Example: TinyMCE Cloud Installation

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  spellchecker_language: 'en'
});
----

== Self-hosted Installation

To enable the {productname} Enterprise Spellchecking plugin, add `+tinymcespellchecker+` to the `+plugins+` list.

For information on installing the server-side component for spell checking, please see the xref:introduction-to-premium-selfhosted-services.adoc[server-side component installation guide].

=== Example: TinyMCE Self-hosted Installation

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  spellchecker_rpc_url: 'localhost/ephox-spelling',
  spellchecker_language: 'en'
});
----

== Usage

The {productname} Enterprise Spellchecking plugin activates automatically when users type content into the editor. To select a spelling suggestion for a misspelled word, right-click the misspelled word to open the contextual menu.

== Options

include::partial$configuration/spellchecker_active.adoc[leveloffset=+1]

include::partial$configuration/spellchecker_dialog.adoc[leveloffset=+1]

include::partial$configuration/spellchecker_ignore_list.adoc[leveloffset=+1]

include::partial$configuration/spellchecker_language.adoc[leveloffset=+1]

include::partial$misc/spellchecker-languages.adoc[leveloffset=+2]

include::partial$configuration/spellchecker_languages.adoc[leveloffset=+1]

ifeval::[{productmajorversion} < 6]
include::partial$configuration/spellchecker_on_load.adoc[leveloffset=+1]
endif::[]

include::partial$configuration/spellchecker_rpc_url.adoc[leveloffset=+1]

include::partial$plugins/spellchecker-content_langs.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The Spell Checker plugin provides the following commands.

include::partial$commands/tinymcespellchecker-cmds.adoc[]

== Events

include::partial$events/tinymcespellchecker-events.adoc[]

=== SpellcheckerIgnore event

This event triggers when the user selects *Ignore* on a misspelled word.

==== Example: the SpellcheckerIgnore event

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  toolbar: 'spellchecker',
  init_instance_callback: (editor) => {
    editor.on('SpellcheckerIgnore', (e) => {
      console.log('Ignore word', e.word);
    });
  }
});
----

=== SpellcheckerIgnoreAll event

This event triggers when the user selects *Ignore All* on a misspelled word.

==== Example: the SpellcheckerIgnoreAll event

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  toolbar: 'spellchecker',
  init_instance_callback: (editor) => {
    editor.on('SpellcheckerIgnoreAll', (e) => {
      console.log('Ignore word (all)', e.word, e.language);
    });
  }
});
----

=== SpellcheckStart event

This event triggers when the user *enables* the `+spellchecker+`.

==== Example: the SpellcheckStart event

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  toolbar: 'spellchecker',
  init_instance_callback: (editor) => {
    editor.on('SpellcheckStart', (e) => {
      console.log('Started spellchecking');
    });
  }
});
----

=== SpellcheckEnd event

This event triggers when the user *disables* the `+spellchecker+`.

==== Example: the SpellcheckEnd event

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  toolbar: 'spellchecker',
  init_instance_callback: (editor) => {
    editor.on('SpellcheckEnd', (e) => {
      console.log('Stopped spellchecking');
    });
  }
});
----

=== SpellcheckError event

This event triggers when a spellchecker error occurs, such as the Spell Checker service can’t be reached.

==== Example: the SpellcheckError event

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  toolbar: 'spellchecker',
  init_instance_callback: (editor) => {
    editor.on('SpellcheckError', (e) => {
      console.log('Spelling service error: ' + e.message);
    });
  }
});
----

=== SpellcheckerLanguageChanged event

This event fires when the spellchecking language is changed.

==== Example: the SpellcheckerLanguageChanged event

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  toolbar: 'spellchecker',
  init_instance_callback: (editor) => {
    editor.on('SpellcheckerLanguageChanged', (e) => {
      console.log(`Spelling language changed: ${e.language}. Previous language: ${e.prevLanguage}`);
    });
  }
});
----

=== SpellcheckerUpdated Event

include::partial$misc/admon-requires-6.5v.adoc[]

This event is fired when the editor content is checked for misspellings and suggestions, either by opening the Spell Checker dialog, or by executing the `+mceSpellcheckUpdate+` command.

NOTE: This event is not fired when Spell Checker is operating in As-You-Type mode.

==== Example: the SpellcheckerLanguageChanged event

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'tinymcespellchecker',
  toolbar: 'spellchecker',
  init_instance_callback: (editor) => {
    editor.on('SpellcheckerUpdated', (e) => {
      const spelling = e.spelling;
      for (const [ language, words ] of Object.entries(spelling)) {
        for (const [ word, suggestions ] of Object.entries(words)) {
          console.log(`${language} suggestions for ${word}:`, suggestions);
        }
      }
    });
  }
});
----

[[spelling-object]]
==== The `spelling` object

The `+spelling+` object, which is provided by the `+SpellcheckerUpdated+` event, contains the result of the spelling service spellcheck.

The keys of the outermost object are the language code for each checked language.

Under each returned language code is an object with

* keys representing misspelled words; and
* arrays of values that are possible correct spellings.

===== Example: the `spelling` object

[source, json]
----
spelling: {
  en: {
    riddiculed: [ 'ridiculed', 'ridicule' ],
    impossable: [ 'impossible', 'impassable', 'impassible' ]
  },
  es: {
    impossible: [ 'impasible', 'imposible', 'imposibles', 'imposibilite' ],
    designate: [ 'desnate', 'designativo', 'designa-te', 'designare' ],
    moment: [ 'momento', 'momentito', 'omento', 'memento' ]
  }
}
----

== APIs

The {pluginname} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]
