= Lists plugin
:navtitle: Lists
:description: Normalizes list behavior between browsers.
:keywords: list, lists, browser, normalize
:pluginname: Lists
:plugincode: lists

The `+lists+` plugin allows you to add numbered and bulleted lists to {productname}. To enable advanced lists (e.g. alpha numbered lists, square bullets) you should also enable the xref:advlist.adoc[Advanced List] (`+advlist+`) plugin.

The plugin also normalizes list behavior between browsers. Enable it if you have problems with consistency making lists.

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'lists',
  toolbar: 'numlist bullist'
});
----

== Example adding the `listprops` menu item to the Tools menu

The `listprops` xref:#menu-items[menu item] opens the List Properties dialog.

This dialog only works with numbered lists. The menu item is inactive unless the selection or insertion point is within a numbered list.

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "lists",
  toolbar: "bullist numlist",
  menu: { tools: { title: 'Tools', items: 'listprops' }},
});
----

== Options

These settings affect the execution of the `+lists+` plugin.

include::partial$configuration/lists_indent_on_tab.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The Lists plugin provides the following {productname} commands.

include::partial$commands/lists-cmds.adoc[]

include::partial$misc/inline-formatting-of-list-bullets.adoc[]
