= Markdown plugin
:navtitle: Markdown
:description: The Markdown Premium plugin detects pure markdown from a paste event within a TinyMCE editor instance.
:description_short: Convert pure markdown on paste.
:keywords: plugin, Markdown.
:pluginname: Markdown
:plugincode: markdown
:plugincategory: premium

include::partial$misc/admon-premium-plugin.adoc[]

The {pluginname} Premium plugin detects pure markdown from a paste event within a {productname} editor instance.

== Using the {pluginname} plugin

=== How it works

The **{pluginname}** Premium Plugin detects if pure markdown is pasted into the {productname} editor instance.

If markdown content is detected during a paste event, the editor will:

* attempt to convert the markdown into HTML
* add an undo level before the conversion, allowing the original plain text to be restored

[TIP]
====
Below are useful keyboard shortcuts for pasting in `plain-text` format when using the {pluginname} plugin within {productname}.

To paste text without formatting use:

* *Windows*: `Ctrl+Shift+V`.
* *Mac*: `Cmd+Shift+V`.

These shortcuts allow pasting of `plain-text` which removes existing formatting (such as bold, italics, or different fonts). This is particularly useful when copying {pluginname} syntax (text) from websites or documents as it ensures the text is pasted into the new location without the original HTML formatting.
====

== Basic setup

To setup the {pluginname} plugin user-interface in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  plugins: 'markdown',
});
----

include::partial$misc/bundling-guide-link.adoc[]


== Interactive examples

liveDemo::{plugincode}[]

[[options]]
== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/markdown.adoc[][leveloffset=+1]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== APIs

The {pluginname} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]