= Markdown plugin
:navtitle: Markdown
:description: The Markdown Premium plugin detects pure markdown from a paste event within a TinyMCE editor instance.
:description_short: Convert pure markdown on paste.
:keywords: plugin, Markdown.
:pluginname: Markdown
:plugincode: markdown
:plugincategory: premium

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]

The {pluginname} Premium plugin detects pure markdown from a paste event within a {productname} editor instance.

== Using the {pluginname} plugin

=== How it works

The **Markdown** Premium Plugin allows the editor to detect if pure markdown is pasted into the {productname} editor instance.

During this paste event, If the editor detects markdown has been pasted it will:

* attempt to convert the markdown to HTML, while
* add a undo level before the conversion to allow for undo of plain-text.


[TIP]
Below is a list of handy shortcuts for copying and pasting in `plain-text` format when using the {pluginname} plugin within {productname}.

[cols="1,3",options="header"]
|===
| Description | Windows | MacOS
| example | `placeholder` | `placeholder` 
|===

== Basic setup

To setup the {pluginname} plugin user-interface in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  plugins: 'markdown',
});
----

== Interactive examples

liveDemo::{plugincode}[]

[[options]]
== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/markdown.adoc[][leveloffset=+1]


== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

// Note to remove if not required.
////
== Events

The {pluginname} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]

== APIs

The {pluginname} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]

////