= Migrating from {productname} 6 to {productname} 7
:navtitle: Migrating from TinyMCE 6
:description: Guidance for migrating from TinyMCE 6 to TinyMCE 7
:keywords: migration, considerations, premigration, pre-migration
:release-version: 7.0

The process for setting up a basic {productname} {release-version} instance is the same as {productname} 6.

Most configuration changes in {productname} {release-version} only affect complex use cases, such as custom plugins and customized user interface components.

This documentation details the changes in {productname} {release-version} that integrators using {productname} 6 should consider when upgrading.

NOTE: For support related to migration, please contact https://support.tiny.cloud/hc/en-us/requests/new[Tiny Support].  +
Open Source users: please report issues in the https://github.com/tinymce/tinymce/[TinyMCE GitHub Repository].

[[overview]]
== Overview

* xref:commands-and-apis[Commands and APIs]
* xref:options[Options]
* xref:plugins[Plugins]
* xref:ui-and-ux[UI and UX]
* xref:security[Security]

[[tinymce-70-core-changes]]
== {productname} {productmajorversion} core changes.

For additional details on {productname} {release-version} changes, see xref:7.0-release-notes.adoc[{productname} {release-version} release notes].


[[commands-and-apis]]
== Commands and APIs 

This section documents the core changes made to {productname} 7.0.

=== Changed

==== Removed `InsertOrderedList` and `InsertUnorderedList` commands from {productname} core.

Previously, native list commands were executable through various text patterns, leading to undefined browser behavior due to the embedded list code.

In {productname} 7.0, these commands are only available in the xref:lists.adoc[*Lists plugin*].

.Example adding list plugin
[source, js]
----
tinymce.init({
  selector: "textarea",
  plugins: [
    "lists"
  ],
  toolbar: "bullist numlist",
});
----

[[remove-trailing-brs-property-removal-from-domparser]]
==== `remove_trailing_brs` property removal from DomParser

The `remove_trailing_brs` setting was removed from the xref:apis/tinymce.html.domparser.adoc[`DomParser` API], after being deprecated in link:https://www.tiny.cloud/docs/tinymce/6/6.5.1-release-notes/#inserting-two-tables-consecutively-without-focus-in-the-editor-resulted-in-the-second-table-being-inserted-at-the-wrong-position[{productname} 6.5]. 

[[changes-to-text-pattern-defaults-to-trigger-on-space-key-press]]
==== Changes to `text-pattern` defaults to trigger on `Space` key press.

Applying basic formats such as headings, lists, bold and italic from typing them out in Markdown syntax is considered a must-have for WYSIWYG Editor's. In previous versions, {productname} would only apply these formats once the user presses the `Enter` key.

{productname} {release-version} updates the default behavior of the `text-patterns` option to apply these formats when the user presses the `Space` key.

[NOTE]
The previous default `text_patterns` behavior, applying the format on an `Enter` key press, can be configured by replacing the `trigger` property with the value `'space'`. Learn more about how you can configure `text_patterns` in the xref:7.0-release-notes.adoc#a-new-trigger-property-for-block-text-pattern-configurations-allowing-pattern-activation-with-either-space-or-enter-keys[{release-version} Release notes]

.Updated default text patterns
[source, ts]
----
default: [
  { start: '#', format: 'h1', trigger: 'space' },
  { start: '##', format: 'h2', trigger: 'space' },
  { start: '###', format: 'h3', trigger: 'space' },
  { start: '####', format: 'h4', trigger: 'space' },
  { start: '#####', format: 'h5', trigger: 'space' },
  { start: '######', format: 'h6', trigger: 'space' },
  { start: '1.', cmd: 'InsertOrderedList', trigger: 'space' },
  { start: '*', cmd: 'InsertUnorderedList', trigger: 'space' },
  { start: '-', cmd: 'InsertUnorderedList', trigger: 'space' },
  { start: '>', cmd: 'mceBlockQuote', trigger: 'space' },
  { start: '---', cmd: 'InsertHorizontalRule', trigger: 'space' },
]
----

For information on the **text_patterns**, see xref:content-behavior-options.adoc#text_patterns[Text Patterns].

=== Removed

==== The autocompleter `ch` configuration property has been removed. Use the `trigger` property instead.
// #TINY-8929

Previously, the `ch` configuration property was used to specify the character that would trigger the autocompleter.

This property was deprecated in link:https://www.tiny.cloud/docs/tinymce/6/6.2-release-notes/#deprecated[{productname} 6.2] and has been removed in {productname} 7.0. Instead, use the `trigger` property to specify the `string` that will trigger the autocompleter.

If `+editor.ui.registry.addAutocompleter(name, options)+` was used in your configuration, updating your configuration from `ch: '<string>',` to `trigger: '<string>',` is required.

NOTE: The new `trigger` option can handle multiple character strings as the trigger.

For more information, visit the updated xref:autocompleter.adoc[Autocompleter] documentation.

[[options]]
== Options

=== Changed

[[highlight-on-focus]]
==== `highlight_on_focus`

Previously, the default value for the editor configuration option `highlight_on_focus` was set to `false` by default. In {productname} {release-version} this option is now by default set to `true`.

As a result, the focus outline for the editor will by default be displayed when the focus is on the editor.

Customers who have created their own custom skins, or have implemented their own outline and do not intend to use the default will need to add `highlight_on_focus: false` to their {productname} configuration.

[NOTE]
This change does not impact editors using inline mode.

=== Removed

[[force-hex-color]]
==== `force_hex_color`

Previously in {productname} 6, all colors in the content HTML were set to use `rgb` values by default. As the common practice is using `hex` values this change has been reverted.

.Example
[source, html]
----
<!-- example using RGB values -->
<p>Hello <span style="color: rgb(255, 0, 0);">red</span> color</p>

<!-- example using HEX values -->
<p>Hello <span style="color: #ff0000">red</span> color</p>
----

In {productname} 7.0, all colors (excluding `rgba` values) are converted to use `hex` values and the `forced_hex_color` option has been removed.

[[plugins]]
== Plugins

=== Changed

==== Changed the `media_url_resolver` option to use promises.
// #TINY-9154

In {productname} 6 and earlier, the `media_url_resolver` option provided `resolve` and `reject` callbacks, rather than a Promise. In certain circumstances this implementation resulted in unexpected behavior.

In {productname} 7, the `media_url_resolver` option now requires a Promise to be returned.

.Old expected value implementing callbacks
[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'media',
  toolbar: 'media',
  media_url_resolver: (data, resolve, reject) => {
    if (data.url.indexOf('YOUR_SPECIAL_VIDEO_URL') !== -1) {
      const embedHtml = `<iframe src="${data.url}" width="400" height="400" ></iframe>`;
      resolve({ html: embedHtml });
    } else {
      resolve({ html: '' });
    }
  }
});
----

.New expected value returning a Promise
[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'media',
  toolbar: 'media',
  media_url_resolver: (data) => {
    return new Promise((resolve) => {
      if (data.url.indexOf('YOUR_SPECIAL_VIDEO_URL') !== -1) {
        const embedHtml = `<iframe src="${data.url}" width="400" height="400" ></iframe>`;
        resolve({ html: embedHtml });
      } else {
        resolve({ html: '' });
      }
    });
  }
});
----

[NOTE]
Integrators will be required to update there configuration to the reflect the new `media_url_resolver` changes.

For more information on using `+media_url_resolver+`, see xref:media.adoc#media_url_resolver[media_url_resolver]


[[removed-plugins]]
=== Removed Plugins

In {productname} {release-version} the below plugin has been removed.

[[removed-plugins-template-plugin]]
==== Removed open-source `Template` plugin

The open-source `Template` plugin and associated config options have been removed in {productname} 7.0.

Customers using the `template` plugin are recommended to upgrade to the premium **Templates** plugin which provides enhanced template functionality. For more information on the **Templates** plugin, see: xref:advanced-templates.adoc[Templates] for more details.

Removed **Template** options:
    
* `template_cdate_classes`
* `template_cdate_format`
* `template_mdate_classes`
* `template_mdate_format`
* `template_replace_values`
* `template_preview_replace_values`
* `template_selected_content_classes`


[[ui-and-ux]]
== UI and UX

=== Changed

[[ui-and-ux-improved-how-styles-are-applied-when-resizing-rows-and-columns-for-tables]]
==== Changed how cell and row heights are applied to tables.

Previously, {productname} added numerous `height` styles when resizing table rows such as on the `table` element, `tr` elements, and `td` elements. This resulted in unnecessarily verbose HTML output.

{productname} {release-version} addresses this by making a couple of changes:

* The height input field has been removed from the "Cell Properties" dialog. Now, the "Row Properties" dialog is the only way to update row heights. 
* When a table is resized using the resize handles or the "Row properties" dialog, existing `height` styles will be stripped from `td/th` elements where applicable and only applied to the `table` element and `tr` elements.

[NOTE]
{productname} {release-version} does not provide any fallback to revert to the old behavior.

=== Removed

[[ui-and-ux-force-notifications-to-have-a-close-button]]
==== Force notifications to have a close button

In previous versions of {productname}, xref:creating-custom-notifications.adoc[notifications] were able to be displayed without a close button (`X`). Accessibility is an important component of the editor, and when this button is not in a notification, that notification cannot be closed via keyboard navigation.

As of {productname} 7.0, the `closeButton` property has been removed from the xref:creating-custom-notifications.adoc[notification API], with all notifications now displaying a visible `closeButton`. This is to allow notifications to be closed using the `Tab` key. 

[[security]]
== Security

=== Changed

[[sandbox-iframes-option]]
==== `sandbox_iframes`

In {productname} 6.8.1, the xref:content-filtering.adoc#sandbox-iframes[sandbox iframes] editor option was introduced to allow iframes to be sandboxed by default when inserted into the editor.

In {productname} 7.0, the default for `+sandbox_iframes+` will change from `false` to `true`, meaning that all `+iframe+` elements inserted into the editor will be given the `sandbox=""` attribute by default, preventing most actions, including scripting and same-origin access, which may break existing editor content or produce undesirable effects.

To prevent any expected iframes from being sandboxed, we recommend adding the source domains of such iframes to the new xref:content-filtering.adoc#sandbox-iframes-exclusions[`+sandbox_iframes_exclusions+`] option list, and including the domains in the default list where necessary. To prevent all iframes from being sandboxed, set the option `+sandbox_iframes+` to `+false+` in your editor configuration.

For further details on the `+sandbox_iframes+` option, see the xref:content-filtering.adoc#sandbox-iframes[the content filtering options], or refer to the xref:security.adoc#sandbox-iframes[security guide], or the link:https://www.tiny.cloud/docs/tinymce/6/6.8.1-release-notes/#new-sandbox_iframes-option-that-controls-whether-iframe-elements-will-be-added-a-sandbox-attribute-to-mitigate-malicious-intent[{productname} 6.8.1 release notes].


[[convert-unsafe-embeds-option]]
==== `convert_unsafe_embeds`

In {productname} 6.8.1, xref:content-filtering.adoc#convert-unsafe-embeds[convert_unsafe_embeds] editor option was introduced to allow `+object+` and `+embed+` elements to be converted by default to the correct element, respective of the MIME type, automatically when inserted into the editor.

In {productname} 7.0, the default value for `+convert_unsafe_embeds+` will change from `false` to `true`, meaning that all `+object+` and `+embed+` tags will automatically be converted to different elements when inserted to the editor.

{productname} has a configuration option that converts object tags to modern equivalents such as `<img>, <video>` and `<audio>` tags, such as;

.Example of before/after conversion.
[source, html]
----
<!-- Before Conversion -->
<object type="video/mp4" data="https://sneak-preview.tiny.cloud/3adc27b5-bb2f-49f0-9ccc-72b7c48313b0/bad.mov"></object>

<!-- After Conversion -->
<video src="https://sneak-preview.tiny.cloud/3adc27b5-bb2f-49f0-9ccc-72b7c48313b0/bad.mov" controls="controls"></video>
----
[NOTE]
If this behaviour is undesirable, set `+convert_unsafe_embeds+` to `+false+` in your editor configuration.

For further details on the `+convert_unsafe_embeds+` option, see the xref:content-filtering.adoc#convert-unsafe-embeds[content filtering options], or refer to the xref:security.adoc#convert-unsafe-embeds[security guide], or the link:https://www.tiny.cloud/docs/tinymce/6/6.8.1-release-notes/#new-convert_unsafe_embeds-option-that-controls-whether-object-and-embed-elements-will-be-converted-to-more-restrictive-alternatives-namely-img-for-image-mime-types-video-for-video-mime-types-audio-audio-mime-types-or-iframe-for-other-or-unspecified-mime-types[{productname} 6.8.1 release notes].
