= Migrating from TinyMCE 5 to TinyMCE 6
:navtitle: Migrating from TinyMCE 5
:description: Guidance for migrating from TinyMCE 5 to TinyMCE 6
:keywords: migration, considerations, premigration, pre-migration

The process for setting up a basic TinyMCE 6 instance is the same as TinyMCE 5.

Most configuration changes in {productname} 6.0 only affect complex use cases, such as custom plugins and customized user interface components.

This chapter describes the settings that require updating prior to migration; and workaround procedures for deprecated, deleted, and updated features.

It set outs the {productname} 6.0 changes that customers using TinyMCE 5 should be aware of as part of upgrading.

NOTE: For support related to migration, please contact https://support.tiny.cloud/hc/en-us/requests/new[Tiny support].  +
Open Source users: please report issues in the https://github.com/tinymce/tinymce/[TinyMCE GitHub Repository].

== Contents

* xref:apis[APIs]
* xref:commands-and-queries[Commands and queries]
* xref:options[Options]
* xref:text-patterns[Text patterns]
* xref:plugins[Plugins]
* xref:schema[Schema]
* xref:ui-and-ux-elements-and-components[UI and UX elements and components]
* xref:security[Security]

== {productname} {productmajorversion} core changes

include::partial$release-notes/6.0-release-notes-summary.adoc[leveloffset=+2]

For additional details on {productname} 6.0 changes, see xref:6.0-release-notes-overview.adoc[{productname} 6.0 release notes overview].

[[apis]]
== APIs

=== AddOnManager

Previously, when loading a requested resource, the `AddOnManager` passed a `success` or `failure` callback to report the status of the request. In {productname} 6, `AddOnManager` reports this status by returning a `Promise`.

=== `change` editor event

Previously, the `change` event was triggered by the first modification made to a {productname} editor instance. However, subsequent changes did not cause the event to fire until focus was switched away from the editor.

For example, typing a single character into the {productname} editor text-entry area triggered the `change` event. Subsequent typing, or selecting of the entered character and modifying it by setting it to *bold* or _italic_, did not trigger further `change` events. Making further modifications and then switching focus away from the editor did trigger this event, however.

As of {productname} 6, the `change` event is not fired unless and until

. focus is switched away from the editor; and
. changes have been made in the editor since focus was switched to it.

NOTE: It is still possible to listen for modification to a {productname} editor instance before focus is changed. To do this, listen for the `dirty` event, rather than the `change` event.

=== Dialog `redial` API

Previously, when a component in a {productname} dialog box changed — for example, when a _next_ or _previous_ button was clicked — the entire dialog box was re-rendered.

In {productname} 6.0, the `initialData` type in the dialog `redial` API uses object diffing for the passed spec. As a consequence, the API now only re-renders the portions of a dialog that have changed.

=== `disabled` renamed in all {productname} APIs

Previously, multiple {productname} APIs used `disable` or `disabled` in their function or property names.

In {productname} 6, these function names have been changed and configuration changes are required.

. `isDisabled()` functions are now `isEnabled()` functions.
+
Configurations that called `isDisabled()` must now call `isEnabled()`. Also, the returned or set value must be interpreted in terms of the new function name. For example, if `isDisabled(false)` was previously called, the equivalent new call is `isEnabled(true)`.
+
. The `enable()` and `disable()` functions are now the single `setEnabled(<state>)` function.
+
Rather than calling the function to set the desired state, call `setEnabled()` with the `true` or `false` value to set the desired state.
+
. The `disable(<name>)` and `enable(<name>)` functions are now the single `setEnabled(<name>, <state>)` function in the Dialog APIs.
+
As well, the `.disabled` property is now the `.enabled` property in all {productname} dialog APIs.
+
. All defaults have been swapped to retain the same logical API defaults.

=== `fire` method renamed in all {productname} APIs

The `fire()` method in

* `tinymce.Editor`;
* `tinymce.dom.EventUtils`;
* `tinymce.dom.DOMUtils`;
* `tinymce.util.Observable`; and
* `tinymce.util.EventDispatcher`

has been renamed to `dispatch()`.

`fire` has been aliased to `dispatch`, so existing integrations should still work as expected.

`fire` has also, however, been marked as _deprecated_. Using `dispatch()` in place of `fire()` is recommended.


=== `new` keyword no longer used to instantiate plugins

In {productname} 6.0, plugins (and other addons) are no longer initialized with the `new` keyword.

As a consequence, the plugin initializer value passed to `PluginManager.add` must be a function. It cannot be a class. (The plugin initializer value is the second argument passed to `PluginManager.add()`.)

This change makes it safe to use both older functions and newer arrow functions when instantiating add-ons.

=== NotificationManager `closeButton` and `timeout`

Previously, using `closeButton` to disable the close button on a xref:apis/tinymce.notificationmanager.adoc[_Notification_] required a `timeout` value to also be set.

In {productname} 6 this requirement was removed; `closeButton` now shows or hides the close button regardless of whether a `timeout` value is set or not set. An `editor.notificationManager` with both `timeout: 5000` and `closeButton: false` set will still present a notification that automatically closes after displaying for 5 seconds.

NOTE: This does not change the behaviour of existing _Notifications_.

=== PluginManager

Previously, when loading a requested resource, the `PluginManager` passed a `success` or `failure` callback to report the status of the request. In {productname} 6, `PluginManager` reports this status by returning a `Promise`.

=== ScriptLoader

Previously, when loading a requested resource, `ScriptLoader` passed a `success` or `failure` callback to report the status of the request. In {productname} 6, `ScriptLoader` reports this status by returning a `Promise`.

=== `SetContent` editor event

The `SetContent` event's `content` property has been deprecated.

When the `SetContent` event fires, any data in `content` has already been added to the {productname} editor instance and cannot be altered, making `content` essentially moot as an `SetContent` property.

To alter such data before it is added to the {productname} editor, use the `content` property available in the `BeforeSetContent` event.

NOTE: The `SetContent` `content` property now returns an empty string in some cases.

=== StyleSheetLoader

Previously, when loading a requested resource, `StyleSheetLoader` passed a `success` or `failure` callback to report the status of the request. In {productname} 6, `StyleSheetLoader` reports this status by returning a `Promise`.

=== ThemeManager

Previously, when loading a requested resource, the `ThemeManager` passed a `success` or `failure` callback to report the status of the request. In {productname} 6, `ThemeManager` reports this status by returning a `Promise`.


[[commands-and-queries]]
== Commands and queries

=== `mceInsertTableDialog`

Previously, the `mceInsertTable` command worked in two modes.

If invoked without arguments —

`tinymce.activeEditor.execCommand('mceInsertTable');`

— the command opened the *Insert Table* dialog box.

If invoked with arguments —

`tinymce.activeEditor.execCommand('mceInsertTable', false, { rows: 2, columns: 2 });`

— the command inserted a table, with the specified properties, directly into the document without opening the *Insert Table* dialog box.

In {productname} 6.0, the `mceInsertTableDialog` command must be used to invoke the *Insert Table* dialog box.

NOTE: The `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user-input. However, using the `mceInsertTable` command without arguments now throws a console error: `model.min.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'rows')`.

=== `mceAddEditor` and `mceToggleEditor`

Previously, `mceAddEditor` and `mceToggleEditor` used the `editorManager.settings` values to set the `id` and UI and UX options for a new {productname} editor instance.

`editorManager.settings` is not used at all in {productname} 6 and has been removed.

Instead, the `mceAddEditor` and `mceToggleEditor` commands use `id` and `options` values from an object passed in when the command is run.

For example —

`tinyMCE.execCommand('mceAddEdit', false, { id: 'ed-1', options: { readonly: false, toolbar: 'bold italic strikethrough' } })`

— finds a `textarea` with id `ed-1` and turns it into a working {productname} editor that displays the _bold_, _italic_, and _strikethrough_ buttons in the editor toolbar.


[[options]]
== Options

=== `element_format`

Previously, `element_format` had no explicit default value. It's implicit value, however, was `xhtml`.

In {productname} 6.0, `element_format` now has an explicit default value: `html`.

This new, and explicit default changes how entered material is serialised. In particular, self-closing elements, such as `<hr>`, `<br>`, and `<img>` no longer present in the `xhtml` standard fashion, as `<hr />`, `<br />`, and `</img />` respectively.

NOTE: If `xhtml` standard representation is required, explicitly setting `element_format` to `xhtml` works as before.

=== `images_upload_handler`

Previously the `images_upload_handler` option passed `success` or `failure` callbacks to report the status of an image upload. In {productname} 6, `images_upload_handler` reports upload results by returning a `Promise`.

=== `link_default_protocol`

The `link_default_protocol` option sets the link protocol used by links added or edited using the _link_ dialog.

It now defaults to `'https'`. Previously it defaulted to `'http'`.

NOTE: The `link_default_protocol` value is only applied to an edited or inserted link if the protocol is not explicitly specified.

[[text-patterns]]
== Text Patterns

As noted in the xref:6.0-release-notes-core-changes.adoc#removed-or-deprecated-options-textpattern[_{productname} 6.0 Release Notes_], the `textpattern_patterns` option:

* Was renamed to `text_patterns`; and
* Had its functionality moved to the core of {productname} 6.0.

As well, the `textpattern` API has been removed.

Finally, and unlike in previous versions of {productname}, text patterns are now on by default. `text_patterns: false` turns the functionality off.

include:partial$misc/admon-turning-text_patterns-off.adoc[]

After upgrading:

* Rename any options in your {productname} init configuration to match the new name.
* Remove `textpattern` from your plugins list.

include::partial$configuration/text_patterns-and-lists.adoc[]


[[plugins]]
== Plugins

=== `plugins` option

Previously, the list of configured plugins could be retrieved by calling `editor.getParam('plugins')` and returned the configured plugins as a string.

As of {productname} 6, the list of configured plugins is retrieved by calling `editor.options.get('plugins')` and now returns the configured plugins as an array.


=== Plugin loading format change

{productname} 6.0 allows plugin loading in any of three formats:

. An array of strings:
+
`plugins: [ 'advlist', 'lists', 'image', 'help', 'wordcount' ]`
+
. A space-separated string:
+
`plugins: 'advlist lists image help wordcount'`
+
. A comma-separated string, with or without spaces:
+
`plugins: 'advlist,lists,image,help,wordcount'` +
`plugins: 'advlist, lists, image, help, wordcount'`

Previously, one other format was allowed: arrays of space-separated strings. This format is no longer accepted in {productname} 6.0.

=== Removed plugins

All references to any of these plugins should be removed from plugin configurations.

NOTE: Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load. {productname} 6.0 should, otherwise, work without error. If, however, {productname} 6.0 is ‘installed' incorrectly — by being unZipped onto an existing {productname} 5.0 instance for example — the old plugin will not be removed, it will load and, since a {productname} 5.x plugin is attempting to work with a {productname} 6.0 instance, error notifications will almost certainly present to the end-user.

See below for specific documentation of potential migration issues, if any, regarding these removed plugins.

Five plugins were removed as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"]:

. `fullpage`
. `bbcode`
. `legacyoutput`
. `tabfocus`
. `spellchecker`

Four plugins were removed because their functionality is now a Core part of {productname} 6.0:

. `hr`
. `noneditable`
. `paste`
. `print`

The functionality from these plugins is now enabled automatically, except for `paste` which as previously announced no longer supports cleaning Microsoft Word content.

Three plugins have been empty stub plugins since {productname} 5.0, and were removed in {productname} 6.0:

. `colorpicker`
. `contextmenu`
. `textcolor`

NOTE: The https://tiny.cloud/tinymce/features/#productivity[Premium plugin], xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro], which offers equivalent functionality and more, is available.

NOTE: No Premium Plugins released with {productname} 6.0 are backwards compatible with earlier versions of {productname}.

=== Enhanced Image Editing (was Image Tools)

As noted in the xref:6.0-release-notes-core-changes.adoc#removed-or-deprecated-plugins-imagetools[_{productname} 6.0 Release Notes_], the `imagetools` plugin is no longer included as part of the Free editor.

_Image Tools_ is now _Enhanced Image Editing_, a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

The `imagetools_proxy` option has been renamed to `editimage_proxy`. However, when setting up xref:introduction-to-premium-selfhosted-services.adoc[Tiny services] the recommended configuration is now `editimage_proxy_service_url` and will be used in favour of `editimage_proxy` if both are set.

Users of the Free version of {productname} 5.x who rely on the removed `imagetools` plugin should not upgrade to {productname} 6.0 without a https://tiny.cloud/pricing/[subscription plan] that provides access to xref:editimage.adoc[Enhanced Image Editing].

NOTE: No Premium Plugins released with {productname} 6.0 are backwards compatible with earlier versions of {productname}.

=== Media

As noted in the xref:6.0-release-notes-core-changes.adoc#changed-plugins-media[_{productname} 6.0 Release Notes_], the `media` plugin no longer uses the SaxParser.

As a consequence the `iframe`, `video`, `audio`, and `object` elements are no longer marked as _special_, and cannot be marked as such. Put another way, the DOM parser does not preserve embedded content.

Instead these elements, and their contents, are validated against the {productname} schema.

This validation is generally done by the `valid_elements`, `valid_children` or `extended_valid_elements` config.

The schema must, therefore, be configured to allow usage of the media elements, and the media element attributes.

NOTE: As of this release, there are no known cases of this change causing media objects to not work as expected. But, also as of this release, not every potential or possible use-case has been tested.

[[plugins-paste]]
=== Paste

As noted in the xref:6.0-release-notes-core-changes.adoc#removed-or-deprecated-plugins-paste[_{productname} 6.0 Release Notes_], the `paste` plugin's functionality is no longer provided as a plugin. It is now a core part of {productname} 6.0.

In conjunction with this change, three changes have been made:

. A `paste` default has changed. The `paste_data_images` option now defaults to `true`.
+
When `paste` was a plugin, this option was, by default, set to `false`, which prevented images being pasted from the local machine.
+
. The `mceInsertClipboardContent` argument, `content`, has been renamed. It is now `html`.
+
The new name is a more accurate reflection of what sort of data the argument passes.
+
The `content` argument can no longer be used with `mceInsertClipboardContent`. If `content` is used, no data is passed. `mceInsertClipboardContent` only attempts to pass data if the `html` or `text` property is used.
+
. The, now built-in, `paste` functionality no longer supports pasting from Microsoft Word.
+
There is an open https://github.com/tinymce/tinymce/discussions/7487[request for maintainers] should someone in the community be interested in taking over maintainance of this particular functionality as a separate plugin.
+
If a community-maintained version of the `paste` plugin becomes available, we will link to it from here.

NOTE: The Premium plugin, xref:introduction-to-powerpaste.adoc[PowerPaste], is available. It provides the capability to accept data from Microsoft Word and Microsoft Excel, and clean-up the received data before pasting it into place.

NOTE: No Premium Plugins released with {productname} 6.0 are backwards compatible with earlier versions of {productname}.

=== Tabfocus

The `tabfocus` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

The `tabfocus_elements` option, which relied on the `tabfocus` plugin, no longer functions.

As per standard web practice, the `tabindex` attribute should be used instead of the `tabfocus` plugin or any of the `tabfocus` plugin's options.

The tab order of a page’s elements, including {productname}, is configured by setting the https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex[`tabindex` attribute] on the relevant HTML elements. The browser then natively handles the tab order.

To configure `tabindex` for the {productname} editor, set the attribute on the target element for the editor. For example:

[source, html]
----
 tinymce.init({
   selector: 'textarea'
 });
 ...
 <input tabindex="1">
 <textarea tabindex="2"></textarea>
 <input tabindex="3">
----

In iframe (classic editor) mode, {productname} copies the `tabindex` attribute from the target element to the editor's iframe, to allow this to work correctly.


=== Table of Contents

As noted in the xref:6.0-release-notes-core-changes.adoc#new-and-improved-plugins-table-of-contents[_{productname} 6.0 Release Notes_], the `toc` plugin is no longer part of the Free editor.

Table of Contents has been updated and is now a https://tiny.cloud/tinymce/features/#productivity[Premium plugin].

Users of the Free version of {productname} 5.x who rely on the, now deprecated and removed, `toc` plugin, should not upgrade to {productname} 6.0 without a https://tiny.cloud/pricing/[subscription plan] that provides access to Premium plugins such as xref:tableofcontents.adoc[Table of Contents].

The new Premium `tableofcontents` plugin also changes the names of several elements.

[cols="1,1"]
|===
| Old name     | New name

| `toc`        | `tableofcontents`

| `tocupdate`  | `tableofcontentsupdate`

| `toc_class`  | `tableofcontents_class`

| `toc_depth`  | `tableofcontents_depth`

| `toc_header` | `tableofcontents_header`
|===

Any configurations or logic that use the old element names must be updated to the new names after upgrading to {productname} 6.0 and installing the new `tableofcontents` plugin.

NOTE: No Premium Plugins released with {productname} 6.0 are backwards compatible with earlier versions of {productname}.


[[schema]]
== Schema

=== Default schema is HTML 5

* {productname} 6.0 instances now explicitly use HTML 5 as the default schema.
+
The previous default was, for practical purposes, also HTML 5, but no specific schema was set. This change formalises and makes explicit what was, previously, only implicit.
+
There is only one functional change consequent to this explicit setting of a default schema.
+
Previously, if you did not explicitly set the schema to anything, `b` and `i` elements were automaticlly transformed into `strong` and `em` elements respectively.
+
If, however, you explicitly set the schema to `html5`, `b` and `i` elements were preserved.
+
With this release, `html5` is explicitly set as the schema by default, _and_ `b` and `i` elements are automatically transformed into `strong` and `em` elements.
+
That is, the element transformation persists even though the `html5` schema is now explicitly set.
+
NOTE: `html5-strict` is still an available schema option and is unchanged from {productname} 5.x.
+
* The assignment operator character — `:` — has been changed to `~` for the `valid_elements` and `extended_valid_elements` schemata.
+
The `:` is also used to assign an `[xlink:href]` rule and this was not possible in these schemata because the colon character was acting as an assignment operator.
+
This change allows both schemata to set attribute values for the `valid_elements` and `extended_valid_elements` options using the `~` character and assign [xlink:href] rules as expected.
+
Existing configurations using either of these schemata must be edited so the `~` character is used for `valid_elements` and `extended_valid_elements` options configurations. The `:` character should no longer be used to set attribute values in these configurations.
+
Also, when assigning `[xlink:href]` rules, the colon character is no longer escaped. `[xlink\\:href]` can now be written plainly, as `[xlink:href]`.
+
NOTE: Existing configurations that included escaped colons will continue to work as expected. Editing such configs to remove the escape characters will improve readability but is not necessary for functionality.


[[ui-and-ux-elements-and-components]]
== UI and UX elements and components

=== `buttonType`

`buttonType` is a new property available for button components used in dialogs. It replaces the, now deprecated property, `primary`.

The `primary` property was boolean, allowing for only two states: `true` and `false`.

The new `buttonType` property can take any of three states: `'primary'`, `'secondary'`, and `'toolbar'`.

Setting `buttonType: 'primary'` is the same as setting `primary: true`.

Setting `buttonType: 'secondary'` is the same as setting `primary: false`.

[[editor-height]]
=== Editor height

In {productname} 5.x, editors without a `height` value specified in the {productname} configuration defaulted to a height of `200px` In {productname} 6.0, editors without a `height` value specified in the {productname} configuration default to `400px`.

As was the case in {productname} 5.x, this new default only applies to editors in `iframe` mode, not `inline` mode.

The new default can be overridden by explicitly setting a `height` value in the {productname} configuration. So setting this to `200px` will recreate the previous default presentation.

Also, setting the CSS `height` of the element replaced by {productname} to a value larger than `400px` will increase the editor height. Setting the element's CSS `height` to a value less than `400px` will *not* reduce the height of the editor, however.

NOTE: To prevent the editor UI from disappearing during manual, end-user re-sizing, `min_height` now has a default value: `100px`.

This default can be overridden as part of an initialization configuration. Setting `min_height` to `> 400` will increase the height of the initial {productname} editor.

But setting a value below `100` makes it possible for manual, end-user re-sizing to reduce the {productname} editor to a horizontal sliver (or, potentially, make it disappear entirely). Setting `min_height` to `< 100` is not recommended


=== formatting user interface name changes

The names of the following user-interface and user experience elements were changed.

[cols="1,1,1"]
|===
| UI or UX element | Old name              | New name

| Option           | `font_formats`       | `font_family_formats`

| Toolbar item     | `fontselect`         | `fontfamily`

| Menu item        | `fontformats`        | `fontfamily`

| Option           | `fontsize_formats`   | `font_size_formats`

| Toolbar item     | `fontsizeselect`     | `fontsize`

| Menu item        | `fontsizes`          | `fontsize`

| Toolbar item     | `formatselect`       | `blocks`

| Menu item        | `blockformats`       | `blocks`

| Toolbar item     | `styleselect`        | `styles`

| Menu item        | `formats`            | `styles`

| Option           | `lineheight_formats` | `line_height_formats`
|===

NOTE: The behaviour of these elements is unchanged.

=== `primary`

The `primary` property was a boolean property available as a basic panel component of `dialogs`.

It has been deprecated and replaced by the new `buttonType` property.


[[ui-elements-and-components-tables-positioned-using-margins-not-float]]
=== Tables are now positioned using `margin`, not `float`

{productname} previously used `float` to position tables to the left or right of the viewport (the working area available to the {productname} editor). This caused multiple layout and UX problems.

For example, consider a {productname} document that included a table that took up less than 100% of the viewport and a paragraph of text below that table. If both the table and the paragraph were selected and their *alignment* was changed to _left_ or _right_, the paragraph of text moved up beside the table.

As another example, consider a {productname} document containing a table that is wider than the viewport. If you selected this table's contents and set the *alignment* to _right_, the portion of the table that was outside the viewport disappeared to the left, and no scrollbar presented allowing you to bring that portion back into view.

As of {productname} 6.0, tables are positioned using `margin` rather than `float`. This prevents these layout and UX problems occurring.

However, when upgrading to {productname} 6.0, there are two things to be aware of:

First, {productname} 6.0 does not alter existing documents. Extant {productname} documents with tables that were aligned to either _left_ or _right_ will still have the `float` property assigned when opened and edited unless and until their *alignment* is altered.

If an extant {productname} document with an aligned table is opened using {productname} 6.0 and the *alignment* of the table is re-set, {productname} 6.0 will remove the `float` property and use the `margin` property to set the *alignment*.

Second, if the previous behavior is required, a custom `format` will need to be created. Specifically, the following format (the https://github.com/tinymce/tinymce/blob/release/5.10/modules/tinymce/src/core/main/ts/fmt/DefaultFormats.ts#L27-L117[table-specific code] from {productname} 5.x's `DefaultFormats.ts`) must be added to the `format` configuration:

[source,js]
----
alignleft: [
  {
    selector: 'figure.image',
    collapsed: false,
    classes: 'align-left',
    ceFalseOverride: true,
    preview: 'font-family font-size'
  },
  {
    selector: 'figure,p,h1,h2,h3,h4,h5,h6,td,th,tr,div,ul,ol,li',
    styles: {
      textAlign: 'left'
    },
    inherit: false,
    preview: false,
    defaultBlock: 'div'
  },
  {
    selector: 'img,table,audio,video',
    collapsed: false,
    styles: {
      float: 'left'
    },
    preview: 'font-family font-size'
  }
],


aligncenter: [
  {
    selector: 'figure,p,h1,h2,h3,h4,h5,h6,td,th,tr,div,ul,ol,li',
    styles: {
      textAlign: 'center'
    },
    inherit: false,
    preview: 'font-family font-size',
    defaultBlock: 'div'
  },
  {
    selector: 'figure.image',
    collapsed: false,
    classes: 'align-center',
    ceFalseOverride: true,
    preview: 'font-family font-size'
  },
  {
    selector: 'img,audio,video',
    collapsed: false,
    styles: {
      display: 'block',
      marginLeft: 'auto',
      marginRight: 'auto'
    },
    preview: false
  },
  {
    selector: 'table',
    collapsed: false,
    styles: {
      marginLeft: 'auto',
      marginRight: 'auto'
    },
    preview: 'font-family font-size'
  }
],


alignright: [
  {
    selector: 'figure.image',
    collapsed: false,
    classes: 'align-right',
    ceFalseOverride: true,
    preview: 'font-family font-size'
  },
  {
    selector: 'figure,p,h1,h2,h3,h4,h5,h6,td,th,tr,div,ul,ol,li',
    styles: {
      textAlign: 'right'
    },
    inherit: false,
    preview: 'font-family font-size',
    defaultBlock: 'div'
  },
  {
    selector: 'img,table,audio,video',
    collapsed: false,
    styles: {
      float: 'right'
    },
    preview: 'font-family font-size'
  }
],
----

Alternatively, the xref:apis/tinymce.formatter.adoc#register[Formatter API] can be used to register a custom format using `editor.formatter.register(<name>, <format>)`.

[[security]]
== Security

include::partial$security/sanitizing-html-input-and-protecting-against-xss-attacks-dom-parser-and-dom-purify.adoc[]
