= TinyMCE Mobile
:description: The TinyMCE rich text editing experience for mobile devices.
:keywords: mobile tablet
:title_nav: Mobile

{% include DEPRECATED/legacy-mobile-removal.md %}

{{site.productname}} 5.1 introduced an improved mobile editor, replacing the existing mobile editor with a touch friendly version of the silver theme.

The mobile experience comes with a number of user interface changes in addition to the {{site.productname}} "desktop" experience:

* Mobile devices now use the `silver` theme.
* Horizontal contextual menus on mobile.
* Side-scrolling toolbars  and contextual menus on mobile.
* Contextual keyboard settings for dialogs using link:{{site.baseurl}}/ui-components/dialogcomponents/#inputmode[`inputMode`].
* <<mobiledefaultsforselectedsettings,Mobile defaults for selected settings>>.
* Table cell selection on mobile.

The mobile experience allows most of the {{site.productname}} plugins to work on mobile devices, except for:

* link:{{site.baseurl}}/plugins/premium/comments/[Comments].
* link:{{site.baseurl}}/plugins/opensource/imagetools/[Image tools].
* link:{{site.baseurl}}/plugins/premium/moxiemanager/[MoxieManager].
* link:{{site.baseurl}}/plugins/premium/permanentpen/[Permanent Pen].

{{site.productname}} will detect the platform and show an optimal UI experience based on the device type and screen size.

NOTE: iPads do not use the `mobile` part of the {{site.productname}} init configuration. This is due to a constraint added by Apple to return the environment as a "desktop environment" for iPads. iPad users will receive the other changes to touch functionality, such as context toolbars and context menus.

{% include misc/mobile_platform_compatibility.md %}

== Configuring mobile

Add the following `meta` tag to the `head` of pages using {{site.productname}} to ensure the mobile user interface functions as intended.

```html+++<meta name="viewport" content="width=device-width, initial-scale=1">++++++</meta>+++

```

To set mobile specific settings, add the setting to the link:{{site.baseurl}}/configure/editor-appearance/#mobile[`mobile`] configuration, such as:

`js
tinymce.init({
  selector: 'textarea',
  mobile: {
    menubar: true
  }
});
`

=== Mobile defaults for selected settings

These mobile-specific default values have been set to disable unsupported settings for mobile devices or to provide the best experience without configuration from developers.

The following settings have mobile-specific default values:

* link:{{site.baseurl}}/configure/editor-appearance/#menubar[`menubar`] - defaults to `false` on mobile phones.
* link:{{site.baseurl}}/configure/editor-appearance/#toolbar_mode[`toolbar_mode`] - defaults to `scrolling` on mobile devices. The toolbar will <<sidescrollingtoolbarsonmobile,side-scroll by default>>.
* link:{{site.baseurl}}/configure/editor-appearance/#toolbar_sticky[`toolbar_sticky`] - Sticky Toolbar is not supported on mobile devices and defaults to `false`.
* link:{{site.baseurl}}/plugins/opensource/table/#table_grid[`table_grid`] - Table grid is not supported on mobile devices and defaults to `false`. When creating tables on mobile, a dialog is shown instead of the table grid.
* link:{{site.baseurl}}/configure/editor-appearance/#resize[`resize`] - Resizing is not supported on mobile devices and defaults to `false`.
* link:{{site.baseurl}}/configure/advanced-editing-behavior/#object_resizing[`object_resizing`] - Object resizing is not supported on mobile devices and defaults to `false`.

=== Unsupported settings for mobile

The following settings are not supported on mobile devices:

* link:{{site.baseurl}}/general-configuration-guide/use-tinymce-inline/[Inline editing mode].
* link:{{site.baseurl}}/general-configuration-guide/use-tinymce-distraction-free/[Distraction-free editing mode].
* link:{{site.baseurl}}/configure/editor-appearance/#inline[`inline`].
* link:{{site.baseurl}}/configure/editor-appearance/#toolbar_sticky[`toolbar_sticky`].
* link:{{site.baseurl}}/plugins/opensource/table/#table_grid[`table_grid`].
* link:{{site.baseurl}}/configure/editor-appearance/#resize[`resize`].
* link:{{site.baseurl}}/configure/advanced-editing-behavior/#object_resizing[`object_resizing`].

== The legacy mobile theme

{% include DEPRECATED/legacy-mobile-removal.md %}

The mobile experience provided for {{site.productname}} 4.7 through {{site.productname}} 5.0 has been deprecated as of {{site.productname}} 5.1.

To revert to the legacy mobile theme, add the mobile theme to the {{site.productname}} configuration, such as:

`js
tinymce.init({
  mobile: {
    theme: 'mobile'
  }
});
`

=== Legacy mobile theme - configuring the plugins

The plugins supported by legacy mobile theme are limited to the link:{{site.baseurl}}/plugins/opensource/autosave/[autosave], link:{{site.baseurl}}/plugins/opensource/autolink/[autolink], and link:{{site.baseurl}}/plugins/opensource/lists/[lists] plugins.

To add these plugins to the legacy mobile theme, add a plugin entry to the mobile section. For example:

`js
tinymce.init({
  selector: 'textarea',
  theme: 'silver',
  mobile: {
    theme: 'mobile',
    plugins: 'autosave lists autolink'
  }
});
`

=== Legacy mobile theme - configuring the Toolbar

The legacy TinyMCE theme mobile supports a subset of the toolbar items, which can configured using the `mobile: toolbar` setting, such as:

`js
tinymce.init({
  selector: 'textarea',
  theme: 'silver',
  mobile: {
    theme: 'mobile',
    plugins: 'autosave lists autolink',
    toolbar: 'undo bold italic styleselect'
  }
});
`

Below are the toolbar items supported for the legacy mobile theme, and the plugins/configuration required.

NOTE: The `list` functions require the link:{{site.baseurl}}/plugins/opensource/lists/[lists] plugin and `styleselect` requires configuring link:{{site.baseurl}}/configure/editor-appearance/#style_formats[style_formats].

|===
| Name | Function | Plugins Required | Configuration

| undo
| Undo operation
|
|

| redo
| Redo operation
|
|

| bold
| Bold formatting operation
|
|

| italic
| Italic formatting operation
|
|

| underline
| Underline formatting operation
|
|

| link
| Insert / Edit a hyperlink
|
|

| unlink
| Remove an existing hyperlink
|
|

| image
| Insert an image
|
|

| bullist
| Insert an unordered list
| link:{{site.baseurl}}/plugins/opensource/lists[lists]
|

| numlist
| Insert an ordered list
| link:{{site.baseurl}}/plugins/opensource/lists[lists]
|

| fontsizeselect
| Change the font size
|
|

| forecolor
| Apply a foreground color
|
|

| styleselect
| Apply a custom style
|
| link:{{ site.baseurl }}/configure/editor-appearance/#style_formats[style_formats]

| removeformat
| Removes any inline formatting
|
|
|===
