= TinyMCE Mobile
:description: The TinyMCE rich text editing experience for mobile devices.
:keywords: mobile tablet
:title_nav: Mobile

include::partial$DEPRECATED/legacy-mobile-removal.adoc[]

{productname} 5.1 introduced an improved mobile editor, replacing the existing mobile editor with a touch friendly version of the silver theme.

The mobile experience comes with a number of user interface changes in addition to the {productname} "desktop" experience:

* Mobile devices now use the `silver` theme.
* Horizontal contextual menus on mobile.
* Side-scrolling toolbars  and contextual menus on mobile.
* Contextual keyboard settings for dialogs using xref:ui-components/dialogcomponents.adoc#inputmode[`inputMode`].
* xref:mobiledefaultsforselectedsettings[Mobile defaults for selected settings].
* Table cell selection on mobile.

The mobile experience allows most of the {productname} plugins to work on mobile devices, except for:

* xref:plugins/premium/comments/index.adoc[Comments].
* xref:plugins/opensource/imagetools.adoc[Image tools].
* xref:plugins/premium/moxiemanager.adoc[MoxieManager].
* xref:plugins/premium/permanentpen.adoc[Permanent Pen].

{productname} will detect the platform and show an optimal UI experience based on the device type and screen size.

NOTE: iPads do not use the `mobile` part of the {productname} init configuration. This is due to a constraint added by Apple to return the environment as a "desktop environment" for iPads. iPad users will receive the other changes to touch functionality, such as context toolbars and context menus.

include::partial$misc/mobile_platform_compatibility.adoc[]

== Configuring mobile

Add the following `meta` tag to the `head` of pages using {productname} to ensure the mobile user interface functions as intended.

[source, html]
----
<meta name="viewport" content="width=device-width, initial-scale=1"></meta>
----

To set mobile specific settings, add the setting to the xref:configure/editor-appearance.adoc#mobile[`mobile`] configuration, such as:

[source, js]
----
tinymce.init({
  selector: 'textarea',
  mobile: {
    menubar: true
  }
});
----

[[mobiledefaultsforselectedsettings]]
=== Mobile defaults for selected settings

These mobile-specific default values have been set to disable unsupported settings for mobile devices or to provide the best experience without configuration from developers.

The following settings have mobile-specific default values:

* xref:configure/editor-appearance.adoc#menubar[`menubar`] - defaults to `false` on mobile phones.
* xref:configure/editor-appearance.adoc#toolbar_mode[`toolbar_mode`] - defaults to `scrolling` on mobile devices. The toolbar will xref:configure/editor-appearance.adoc#scrolling[side-scroll by default].
* xref:configure/editor-appearance.adoc#toolbar_sticky[`toolbar_sticky`] - Sticky Toolbar is not supported on mobile devices and defaults to `false`.
* xref:plugins/opensource/table.adoc#table_grid[`table_grid`] - Table grid is not supported on mobile devices and defaults to `false`. When creating tables on mobile, a dialog is shown instead of the table grid.
* xref:configure/editor-appearance.adoc#resize[`resize`] - Resizing is not supported on mobile devices and defaults to `false`.
* xref:configure/advanced-editing-behavior.adoc#object_resizing[`object_resizing`] - Object resizing is not supported on mobile devices and defaults to `false`.

=== Unsupported settings for mobile

The following settings are not supported on mobile devices:

* xref:general-configuration-guide/use-tinymce-inline.adoc[Inline editing mode].
* xref:general-configuration-guide/use-tinymce-distraction-free.adoc[Distraction-free editing mode].
* xref:configure/editor-appearance.adoc#inline[`inline`].
* xref:configure/editor-appearance.adoc#toolbar_sticky[`toolbar_sticky`].
* xref:plugins/opensource/table.adoc#table_grid[`table_grid`].
* xref:configure/editor-appearance.adoc#resize[`resize`].
* xref:configure/advanced-editing-behavior.adoc#object_resizing[`object_resizing`].

[[thelegacymobiletheme]]
== The legacy mobile theme

include::partial$DEPRECATED/legacy-mobile-removal.adoc[]

The mobile experience provided for {productname} 4.7 through {productname} 5.0 has been deprecated as of {productname} 5.1.

To revert to the legacy mobile theme, add the mobile theme to the {productname} configuration, such as:

[source, js]
----
tinymce.init({
  mobile: {
    theme: 'mobile'
  }
});
----

=== Legacy mobile theme - configuring the plugins

The plugins supported by legacy mobile theme are limited to the xref:plugins/opensource/autosave.adoc[autosave], xref:plugins/opensource/autolink.adoc[autolink], and xref:plugins/opensource/lists.adoc[lists] plugins.

To add these plugins to the legacy mobile theme, add a plugin entry to the mobile section. For example:

[source, js]
----
tinymce.init({
  selector: 'textarea',
  theme: 'silver',
  mobile: {
    theme: 'mobile',
    plugins: 'autosave lists autolink'
  }
});
----

=== Legacy mobile theme - configuring the Toolbar

The legacy TinyMCE theme mobile supports a subset of the toolbar items, which can configured using the `mobile: toolbar` setting, such as:

[source, js]
----
tinymce.init({
  selector: 'textarea',
  theme: 'silver',
  mobile: {
    theme: 'mobile',
    plugins: 'autosave lists autolink',
    toolbar: 'undo bold italic styleselect'
  }
});
----

Below are the toolbar items supported for the legacy mobile theme, and the plugins/configuration required.

NOTE: The `list` functions require the xref:plugins/opensource/lists.adoc[lists] plugin and `styleselect` requires configuring xref:configure/editor-appearance.adoc#style_formats[style_formats].

|===
| Name | Function | Plugins Required | Configuration

| undo
| Undo operation
|
|

| redo
| Redo operation
|
|

| bold
| Bold formatting operation
|
|

| italic
| Italic formatting operation
|
|

| underline
| Underline formatting operation
|
|

| link
| Insert / Edit a hyperlink
|
|

| unlink
| Remove an existing hyperlink
|
|

| image
| Insert an image
|
|

| bullist
| Insert an unordered list
| xref:plugins/opensource/lists.adoc[lists]
|

| numlist
| Insert an ordered list
| xref:plugins/opensource/lists.adoc[lists]
|

| fontsizeselect
| Change the font size
|
|

| forecolor
| Apply a foreground color
|
|

| styleselect
| Apply a custom style
|
| xref:configure/editor-appearance.adoc#style_formats[style_formats]

| removeformat
| Removes any inline formatting
|
|
|===
