= Noneditable plugin
:description: Prevent users from changing content within elements. Ideal for templates.
:keywords: noneditable contenteditable editable mceNonEditable noneditable_editable_class noneditable_noneditable_class noneditable_regexp
:title_nav: Noneditable

NOTE: The `noneditable` plugin has been rewritten from scratch to use stability improvements to the {productname} core. It is now more reliable and has fewer browser-specific quirks.

This plugin enables you to prevent users from being able to edit content within elements assigned the `mceNonEditable` class.

== Basic setup

[source, js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'noneditable'
});
----

When you have existing classes that cannot be removed, you may combine MCE classes with the existing class in the following manner:

=== Non-editable div example

[source, html]
----
<div class="myclass mceNonEditable">Contents</div>
----

=== Editable div example

[source, html]
----
<div class="myclass mceEditable">Contents</div>
----

== Options

These settings affect the execution of the `noneditable` plugin. These settings help determine which areas of the editor's editable area will remain editable and which will be converted to non-editable status.

include::partial$configuration/noneditable_editable_class.adoc[]

include::partial$configuration/noneditable_noneditable_class.adoc[]

include::partial$configuration/noneditable_regexp.adoc[]

== Making Content Non-editable

=== Procedure

. Add `noneditable` to `plugins`. For example:
+
[source, js]
----
 tinymce.init({
   selector: 'textarea',  // change this value according to your HTML
   plugins: 'code noneditable'
 });
----

. Configure the `noneditable_noneditable_class` option, or the others as necessary in your `tinymce.init`. For example:
+
[source, js]
----
 tinymce.init({
   selector: 'textarea',  // change this value according to your HTML
   plugins: 'noneditable',
   noneditable_noneditable_class: 'mceNonEditable'
 });
----
+
NOTE: Replace `mceNonEditable` with the class name you want for your non-editable elements.

. Select the desired editor content.
. From the menu bar, select `View` > `Source code`.
. Add the non-editable class to the desired editor content. For example:
+
[source, html]
----
<div class="myclass mceNonEditable">Contents</div>
----