= Quick start: {productname} from NPM or Yarn
:navtitle: Quick start: NPM/Yarn
:description: Learn how to install {productname} from NPM using NPM and Yarn, including premium plugins for commercial customers.
:keywords: yarn, npm, javascript, install, premium plugins, tinymce-premium, selector, textarea, id, tinymce.init

== Install {productname} using NPM or Yarn

{productname} {productmajorversion} is a powerful and flexible rich text editor that can be embedded in web applications. This quick start covers how to add a {productname} editor to a web page using NPM or Yarn.

== Prerequisites

This procedure requires https://nodejs.org/[Node.js (and npm)] to be installed. Ensure you have a project directory with a `+package.json+` file. If you don't have a project yet, initialize one by running `+npm init+` or `+yarn init+` in your project directory.

== Install {productname}

To add {productname} to your project, navigate to your project directory and run one of the following commands:

* *NPM:*
+
[source,sh,subs="attributes+"]
----
npm install tinymce@^{productmajorversion}
----
* *Yarn:*
+
[source,sh,subs="attributes+"]
----
yarn add tinymce@^{productmajorversion}
----

The location of the main {productname} script will be: `+node_modules/tinymce/tinymce.min.js+`. Ensure the `+tinymce+` directory containing the `+tinymce.min.js+` file is accessible for the target page or application by either:

* Using a webserver route, or
* Copying the `+tinymce+` directory to a public folder using a build tool such as Gulp or Webpack.

[[install-premium-plugins]]
== Install premium plugins

The `+tinymce-premium+` NPM package provides all premium plugins, skins, themes, icons, and language packs for commercial TinyMCE customers.

[IMPORTANT]
====
The `+tinymce-premium+` package requires a commercial license. Ensure you have a valid license key before using premium plugins. For information on obtaining a license key, see: xref:license-key.adoc[License Key].
====

=== Prerequisites

Before installing premium plugins, ensure you have:

* The core `+tinymce+` package installed (see above)
* A valid license key
* Node.js and npm installed

=== Install the premium plugins package

Install the `+tinymce-premium+` package using npm:

[source,sh]
----
npm install tinymce-premium@^8.3
----

[NOTE]
====
The `+tinymce-premium+` package is available for {productname} 8.3 onwards and is currently only published to the NPM registry. The package version must align with the `+tinymce+` package version—always use compatible versions of both packages (e.g., both at 8.3.0 or later).
====

=== Package contents

The `+tinymce-premium+` package includes:

* All premium plugins
* License key manager plugin
* Premium skins, icons and language packs

[NOTE]
====
Dictionaries are **not** included in the `+tinymce-premium+` package and remain a separate download.
====

=== Using premium plugins

After installing the `+tinymce-premium+` package, configure the plugins in your editor. For complete instructions on bundling premium plugins or using the `+external_plugins+` option, see: xref:bundling-plugins.adoc#using-premium-plugins[Using premium plugins].

=== Framework integration

For framework-specific integration guides, see:

* xref:react-pm-bundle.adoc[React (Bundling)]
* xref:react-pm-host.adoc[React (Hosting)]
* xref:angular-pm.adoc[Angular]
* xref:vue-pm.adoc[Vue.js]
* xref:blazor-pm.adoc[Blazor]
* xref:svelte-pm.adoc[Svelte]
* xref:webcomponent-pm.adoc[Web Component]


== Include the {productname} script

Include the following line of code in the `+<head>+` of a HTML page:

[source,html,subs="attributes+"]
----
<script src="/path/or/uri/to/tinymce.min.js" referrerpolicy="origin" crossorigin="anonymous"></script>
----

== Initialize {productname} as part of a web form

include::partial$install/initialize-editor-self-hosted.adoc[]

Adding this content to an HTML file and opening it in a web browser will load a {productname} editor, such as:

liveDemo::default[]

include::partial$install/save-content.adoc[]

include::partial$misc/quickstart-next-steps.adoc[]
