= Open source plugins for TinyMCE
:description: This section lists the open source plugins provided with TinyMCE.
:description_short: TinyMCE open source plugins
:title_nav: Open source plugins
:type: folder



// 2 Columns, both asciidoc
[cols=2*a]
|===

|
[.lead]
xref:advlist.adoc[Advanced List]

Create styled number and bulleted lists.

|
[.lead]
xref:anchor.adoc[Anchor]

Insert anchors (sometimes referred to as a bookmarks).

|
[.lead]
xref:autolink.adoc[Autolink]

Automatically create hyperlinks.

|
[.lead]
xref:autoresize.adoc[Autoresize]

Automatically resize TinyMCE to fit content.

|
[.lead]
xref:autosave.adoc[Autosave]

Automatically save content in your local browser.

|
[.lead]
xref:bbcode.adoc[BBCode]

Add basic BBCode input/output to TinyMCE.

|
[.lead]
xref:charmap.adoc[Character Map]

Insert special characters into TinyMCE.

|
[.lead]
xref:code.adoc[Code]

Edit your content's HTML source.

|
[.lead]
xref:codesample.adoc[Code Sample]

Insert and embed syntax highlighted code snippets.

|
[.lead]
xref:directionality.adoc[Directionality]

Toolbar buttons for setting the left-to-right or right-to-left direction of content.

|
[.lead]
xref:emoticons.adoc[Emoticons]

Bring a smiley to your content.

|
[.lead]
xref:fullpage.adoc[Full Page]

Edit all metadata and document properties such as title, keywords and description.

|
[.lead]
xref:fullscreen.adoc[Full Screen]

Zoom TinyMCE up to the whole screen.

|
[.lead]
xref:help.adoc[Help]

Shows the help dialog.

|
[.lead]
xref:hr.adoc[Horizontal Rule]

Insert a horizontal line.

|
[.lead]
xref:image.adoc[Image]

Insert an image into TinyMCE.

|
[.lead]
xref:editimage.adoc[Image Tools]

Image editing features for TinyMCE.

|
[.lead]
xref:importcss.adoc[Import CSS]

Automatically populate CSS class names into the Format dropdown.

|
[.lead]
xref:insertdatetime.adoc[Insert Date/Time]

Insert the current date and/or time into TinyMCE.

|
[.lead]
xref:legacyoutput.adoc[Legacy Output]

Changes HTML output to old HTML syntax such as font, b and i

|
[.lead]
xref:link.adoc[Link]

Add hyperlinks to content.

|
[.lead]
xref:lists.adoc[Lists]

Normalizes list behavior between browsers.

|
[.lead]
xref:media.adoc[Media]

Add HTML5 video and audio elements.

|
[.lead]
xref:nonbreaking.adoc[Nonbreaking Space]

Insert a nonbreaking space.

|
[.lead]
xref:noneditable.adoc[Noneditable]

Prevent users from changing content within elements. Ideal for templates.

|
[.lead]
xref:pagebreak.adoc[Page Break]

Add a page break.

|
[.lead]
xref:paste.adoc[Paste]

Standard version of features for copying-and-pasting content from Microsoft Word.

|
[.lead]
xref:preview.adoc[Preview]

Shows a popup of the current content in read-only format.

|
[.lead]
xref:print.adoc[Print]

Print the content in TinyMCE.

|
[.lead]
xref:quickbars.adoc[Quick Toolbars]

User interface controls to create content faster.

|
[.lead]
xref:save.adoc[Save]

Adds a save button to the TinyMCE toolbar.

|
[.lead]
xref:searchreplace.adoc[Search and Replace]

Find and replace content in TinyMCE.

|
[.lead]
xref:spellchecker.adoc[Spell Checker]

Enables TinyMCE's spellcheck functionality.

|
[.lead]
xref:tabfocus.adoc[Tab Focus]

Tab into and out of the TinyMCE control in your web form.

|
[.lead]
xref:table.adoc[Table]

Table editing features.

|
[.lead]
xref:template.adoc[Template]

Custom templates for your content.

|
[.lead]
xref:textpattern.adoc[Text Pattern]

Matches special patterns in the text and applies formats or executed commands on these patterns.

|
[.lead]
xref:tableofcontents.adoc[Table of Contents]

Insert a simple Table of Contents into TinyMCE editor

|
[.lead]
xref:visualblocks.adoc[Visual Blocks]

Allows a user to see block level elements such as paragraphs.

|
[.lead]
xref:visualchars.adoc[Visual Characters]

See invisible characters like non-breaking spaces.

|
[.lead]
xref:wordcount.adoc[Word Count]

Show a word count in the TinyMCE status bar.

// Empty cell to even out rows
| 

|===