= Troubleshooting the PowerPaste plugin

:navtitle: Troubleshooting
:description: Information on troubleshooting PowerPaste behavior.
:keywords: enterprise powerpaste power paste microsoft word excel google docs

== What happens when copy and pasting from Microsoft Word?

When content is copied from an application (such as Microsoft Word), the application places an HTML representation of the copied content onto the computer's clipboard. PowerPaste uses the HTML from the clipboard and cannot access the file directly.

NOTE: Web browsers and the applications running in them cannot directly access files on the device for security reasons.

Microsoft Word or Microsoft Excel can create content that does not have an equivalent in HTML. The HTML provided to the clipboard by the application is the application's "best effort" at representing the content as HTML. Depending on the complexity of the source document, the content pasted into {productname} using PowerPaste may not be an exact representation of what the content looked like in the original application.

== Why are some images or elements from Microsoft Word not appearing?

Some "images" in Microsoft Word cannot be represented as image files in an HTML document, such as: charts, drawings, and "Word Art". PowerPaste may not be able to paste these items into the {productname} editor, because they were not represented as HTML-compatible images on the clipboard. Microsoft Word also allows some formats on images that cannot be represented in HTML, such as wrap and inline.

Microsoft Word can also create content that cannot be accurately recreated in HTML, such as columns, page headers and page footers. Some of these elements may not be copied to the clipboard by Microsoft Word, such as page headers and footers.

== How can I see what is on the clipboard?

To view the HTML of content on the clipboard, paste into the red box on the http://static.ephox.com/clipboard/clipboardtest.html[{companyname} Clipboard Viewer].
