= Revision History Plugin
:navtitle: Revision History
:description: A view that allows {productname} users to see historical snapshots of a document and an ability to restore from a snapshot
:description_short: View containing historical snapshots of a document.
:keywords: plugin, Revision History, history, version, snapshots, restore, changes
:pluginname: Revision History
:plugincode: revisionhistory
:plugincategory: premium

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]

include::partial$misc/admon-iframe-only.adoc[]

The {pluginname} plugin provides users an ability to see how a document has changed over time and to restore from a saved version.

== Interactive example

liveDemo::{plugincode}[]

[NOTE]
The {pluginname} plugin treats commented HTML as actual content in the {productname} editor. This means that if the initial content is in the form of commented HTML and no revisions are fetched, the commented HTML automatically becomes the latest revision. However, if some revisions are present, the commented HTML will be compared to the first configured revision.

=== How it works
// TODO: Attach image of revision history

The {pluginname} view is opened when clicking on the `revisionhistory` toolbar or menu button which locates under `View` menu.

The view consists of these main UI components:

* In the toolbar header, there are `Restore this version` and `Close` buttons. Clicking `Restore this version` will set the editor's content to the selected version and close the view. Pressing `Close` button will exit the view.

* The readonly diff content UI shows the changes between the selected version and the closest one, which is below the selected version. The changes are highlighted for easy recognition of the types of change being applied:

** Red: Removed content
** Green: New content
** Yellow: Content being modified. Modifications to HTML content implies attribute or format changes (bold, italic, etc)

* The revisions sidebar renders the versions of a document. When a new version is selected, the diff content UI is updated accordingly.

=== Basic setup

To setup the {pluginname} plugin user-interface in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;

* add `{plugincode}` to the `toolbar` option in the editor configuration;

* add `{plugincode}_fetch` option to the editor configuration;

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'revisionhistory',
  toolbar: 'revisionhistory',
  // Required
  revisionhistory_fetch: () => new Promise((resolve) => {
    const revisions = [];  // Replace this with an API request to get saved versions
    resolve(revisions);
  })
});
----

== Understanding initial and current versions

A new document, that has no saved versions, always has at max two versions: the initial version and current version. 

* Initial version is created on {productname} `Loaded` event with the content initialized with the editor.
* Current version is added on opening the {pluginname} with the editor's current content. If included, it is always be the latest version and placed at the top.

If both versions are the same, only the current version is kept.

When a document has saved versions, its initial version is discarded as the {pluginname} assumes it already a part of versions. The current version is only discarded if it matches to the closest version.

The below table summaries how the initial and current versions are handled in the {pluginname}:
[cols=",,,1",options="header"]
|===
|Initial version | Different current version | Has saved versions | Expect
|No |No |No |No revisions is shown
|Yes |No |No |Only shows the current version
|Yes |Yes |No |Both initial and current version are shown
|Yes |Yes |Yes |Shows the saved versions including the current version
|Yes |No |Yes |Only shows the saved versions
|No |Yes |Yes |Shows the saved versions including the current version
|No |No |Yes |Only shows the saved versions
|===

[NOTE]
`Different current version` implies whether the current version is different than the initial version. When the editor is loaded with content, the two versions are the same.

== Limitations

1. There are several known limitations when it comes to the plugin's content diffing capability.

* For the listed content below, the {pluginname} might not be able to render them as how they are rendered in the editor and the diffing might not correctly reflects the changes on them:
** Content that is annotated or its visual representation provided by a plugin: ie: comments, pagebreak, etc.
** Custom content. Note: If its visual representation can be addressed by CSS then it is up the integrators to provide the styling via xref:revisionhistory_css_url.adoc[`+revisionhistory_css_url+`] option.
* Code inside `code` block except for the newlines.

2. There is no integration for saving a version yet. For now, the integrators can make a custom `Save current content` button by following the below example:

[source,js]
----
const revisions = [];

tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'revisionhistory',
  toolbar: 'revisionhistory saveversion',
  setup: (editor) => {
    editor.ui.registry.addButton('saveversion', {
      text: 'Save a version',
      onAction: () => {
        // Change this according to your setup
        const revision = {
          content: editor.getContent({ format: 'raw' }),
          revisionId: (revisions.length + 1).toString(),
          createdAt: new Date().toISOString()
        };
        revisions.unshift(revision);
      }
    });
  },
  revisionhistory_fetch: () => Promise.resolve(revisions)
});
----


== Known issues
This section describes issues that users of {productname} may encounter:

* `table` elements with `colgroup` are highlighted as new even though there is no change.


== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/revisionhistory_fetch.adoc[leveloffset=+1]

include::partial$configuration/revisionhistory_css_url.adoc[leveloffset=+1]

include::partial$configuration/revisionhistory_diff_classes.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {pluginname} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]