= Revision History Plugin
:navtitle: Revision History
:description: A view that allows {productname} users to see historical snapshots of a document and an ability to restore from a snapshot
:description_short: View containing historical snapshots of a document.
:keywords: plugin, Revision History, history, version, snapshots, restore, changes
:pluginname: Revision History
:plugincode: revisionhistory
:plugincategory: premium

include::partial$misc/admon-revisionhistory-paid-addon-pricing.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]

The {pluginname} plugin offers users the ability to view document changes over time and restore previous versions effortlessly.

== Interactive example

liveDemo::{plugincode}[]

include::partial$misc/admon-iframe-only.adoc[]

== How it works

The {pluginname} view is accessible via either the `revisionhistory` toolbar button or menu button within the `View` menu.

The key components are:

1. In the {pluginname} view header, there are two buttons.
* `Restore this version`: Set the selected version's content to the editor and close the view.
* `Close`: Close the view.

2. The readonly diff view presents the changes between the selected version and its immediate predecessor, clearly highlighting for easy recognition. The changes are also color-coded for clarity:
* Red: Removed content.
* Green: New content.
* Yellow: Content being modified. Modifications to HTML content implies attributes or formatting (e.g. bold, italic, etc.).
3. The revisions sidebar displays all available document versions. When a new version is selected, the diff view is updated accordingly.

[NOTE]
The default highlighting colors can be customized using the xref:revisionhistory_css_url[`+revisionhistory_css_url+`] option.

[NOTE]
The {pluginname} plugin interprets commented HTML as valid content, yet it disregards this content during the version comparison process. Consequently, a version containing solely commented content appears as empty in the user interface displaying the differential content.

== Basic setup

To setup the {pluginname} plugin user-interface in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;
* add `{plugincode}` to the `toolbar` option in the editor configuration;
* add `{plugincode}_fetch` option to the editor configuration;

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'revisionhistory',
  toolbar: 'revisionhistory',
  // Required
  revisionhistory_fetch: () => new Promise((resolve) => {
    const revisions = [];  // Replace this with an API request to get saved versions
    resolve(revisions);
  })
});
----

== Understanding initial and current versions

When dealing with a new document, that has no saved versions, {pluginname} plugin will always typically maintain two versions: the `initial` and `current` versions.

* Initial Version: this version is generated during the {productname} `Loaded` event, with the editor's content initialized.
* Current Version: is created on opening the {pluginname} with the editor's current content. If included, it will become the `latest version` and placed at the top of the revisions list.

[TIP]
When the editor is initialized with content, both versions' content are the same. In that case, the {pluginname} only keeps the `current version`.

For documents with saved versions, the `initial version` is disregarded by the {pluginname} assuming it's already part of the version history. The current version is discarded if its content matches the closest saved version.

The below table summaries how versions are handled in {pluginname}:

[cols="1,1,1,3", options="header"]
|===
|Has Initial Version |Current Version |Has Saved Versions |Expectation
|No |N/A |No |No versions are shown
|No |N/A |Yes |Only the saved versions are shown
|Yes |Same |No |Only the current version is shown
|Yes |Different |No |Both the initial and current versions are shown
|Yes |Either |Yes |The saved versions and the current version are shown
|===

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/revisionhistory_fetch.adoc[leveloffset=+1]

include::partial$configuration/revisionhistory_css_url.adoc[leveloffset=+1]

include::partial$configuration/revisionhistory_diff_classes.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {pluginname} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]