= Revision History Plugin
:navtitle: Revision History
:description: A view that allows {productname} users to see historical snapshots of a document and an ability to restore from a snapshot
:description_short: View containing historical snapshots of a document.
:keywords: plugin, Revision History, history, version, snapshots, restore, changes
:pluginname: Revision History
:plugincode: revisionhistory
:plugincategory: premium

include::partial$misc/admon-premium-plugin.adoc[]

include::partial$misc/admon-requires-7.0v.adoc[]

The {pluginname} plugin offers users the ability to view document changes over time and restore previous versions effortlessly.

== Interactive example

liveDemo::{plugincode}[]

include::partial$misc/admon-iframe-only.adoc[]

=== How it works

The {pluginname} view is opened when clicking on the `revisionhistory` toolbar or menu button which locates under `View` menu.

The view consists of these main UI components:

* In the toolbar header, there are `Restore this version` and `Close` buttons.
** Clicking `Restore this version` will set the editor's content to the selected version and close the view. ** Pressing `Close` button will exit the view.
* The readonly diff content UI shows the changes between the selected version and the closest one, which is below the selected version. The changes are highlighted for easy recognition of the types of change being applied:
** Red: Removed content
** Green: New content
** Yellow: Content being modified. Modifications to HTML content implies attribute or format changes (bold, italic, etc)
* The revisions sidebar renders the available versions for a document. When a new version is selected, the diff content UI is updated accordingly.

[NOTE]
The {pluginname} plugin treats commented HTML as actual content but the content is ignored in the diffing process. This means that a version with all its content commented appears empty in the diff content UI.

=== Basic setup

To setup the {pluginname} plugin user-interface in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;
* add `{plugincode}` to the `toolbar` option in the editor configuration;
* add `{plugincode}_fetch` option to the editor configuration;

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'revisionhistory',
  toolbar: 'revisionhistory',
  // Required
  revisionhistory_fetch: () => new Promise((resolve) => {
    const revisions = [];  // Replace this with an API request to get saved versions
    resolve(revisions);
  })
});
----

== Understanding initial and current versions

When dealing with a new document, that has no saved versions, {pluginname} plugin will always typically maintain two versions: the `initial` and `current` version.

* Initial Version: this version is generated during the {productname} `Loaded` event, with the editor's content initialized.
* Current Version: is added on opening the {pluginname} with the editor's current content. If included, it will become the `latest version` and placed at the top of the revisions list.

[TIP]
If both versions are the same, only the `current version` is kept.

For documents with saved versions, the `initial version` is disregarded by the {pluginname} assuming it's already part of the version history. The current version is only discarded if it matches the closest saved version.

The below table summaries how the initial and current versions are handled in the {pluginname}:

[cols="1,1,1,3", options="header"]
|===
|Initial Version |Different Current Version |Has Saved Versions |Expect
|No |No |No |No versions are shown
|Yes |No |No |Only the `current` version is shown
|Yes |Yes |No |Both the `initial` and `current` versions are shown
|Yes |Yes |Yes |Shows the `saved` versions, including the `current` version
|Yes |No |Yes |Only the `saved` versions are shown
|No |Yes |Yes |Shows the `saved` versions, including the `current` version
|No |No |Yes |Only the `saved` versions are shown
|===

[NOTE]
`Different current version` implies whether the current version is different than the initial version. When the editor is loaded with content, the two versions are the same.

== Limitations

1. There are several known limitations when it comes to the plugin's content diffing capability.

* For the listed content below, the {pluginname} might not be able to render them as how they are rendered in the editor and the diffing might not correctly reflects the changes on them:
** Annotated content or content whose visual representation is provided by a plugin, such as comments or page breaks.
** Custom content if its visual representation can be adjusted using CSS, integrators can address this by providing styling via the xref:revisionhistory_css_url.adoc[`+revisionhistory_css_url+`] option.
* Code within code blocks may not be accurately differentiated, excluding changes in newlines.

2. There is no integration for saving a version yet. For now, a workaround is to add a custom toolbar button. For example:

[source,js]
----
const revisions = [];

tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'revisionhistory',
  toolbar: 'revisionhistory saveversion',
  setup: (editor) => {
    // Save the current content of the editor as a new version
    editor.ui.registry.addButton('saveversion', {
      text: 'Save a version',
      onAction: () => {
        // Change this according to your setup
        const revision = {
          content: editor.getContent({ format: 'raw' }),
          revisionId: (revisions.length + 1).toString(),
          createdAt: new Date().toISOString()
        };
        revisions.unshift(revision);
      }
    });
  },
  revisionhistory_fetch: () => Promise.resolve(revisions)
});
----


== Known issues

This section describes issues that users of {productname} may encounter:

* `table` elements with `colgroup` are highlighted as new even though there is no change.

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/revisionhistory_fetch.adoc[leveloffset=+1]

include::partial$configuration/revisionhistory_css_url.adoc[leveloffset=+1]

include::partial$configuration/revisionhistory_diff_classes.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {pluginname} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]