= Getting started with Real-Time Collaboration (RTC)

:title_nav: Getting started with RTC
:description: Getting started with RTC
:keywords: rtc
:pluginname: Real-Time Collaboration (RTC)
:plugincode: rtc
:jwturl: {accountpageurl}/jwt/
:numberedHeading: true

This procedure will assist with setting up {productname} with real-time collaboration.

[IMPORTANT]
--
include::partial$misc/secure-context.adoc[]
--

The steps required for setting up Real-Time Collaboration for {productname} are:

. Register for a {cloudname} API key.
. Add a public key to the {cloudname} API key.
. Set up an Encryption Provider endpoint (or server).
. Set up a JSON Web Token (JWT) Provider endpoint (or server).
. Configure the required {productname} options.

[[register-for-a-tiny-cloud-api-key]]
== 1. Register for a Tiny Cloud API key

If you do not have a {cloudname} API key, you can sign up for a trial or purchase a subscription on the link:{pricingpage}/[{companyname} pricing page].

include::partial$auth/private-public-key-pairs-for-tiny-cloud-services.adoc[leveloffset=+1]

[[set-up-an-encryption-endpoint]]
== 3. Set up an Encryption endpoint

{productname} Real-Time Collaboration (RTC) uses encryption keys to encrypt content before sending it to collaborators through the RTC server to provide end-to-end encryption.

For information on setting up an Encryption Provider endpoint, see: xref:rtc-encryption.adoc[Real-Time Collaboration (RTC) Encryption Setup].

[[set-up-a-json-web-token-jwt-provider-endpoint]]
== 4. Set up a JSON Web Token (JWT) Provider endpoint

Real-Time Collaboration (RTC) requires setting up JSON Web Token (JWT) authentication. This is to ensure that only authenticated users will be able to access and collaborate on documents.

For information on setting up a JSON Web Token Provider endpoint, see: xref:rtc-jwt-authentication.adoc[Real-Time Collaboration (RTC) JWT Authentication Setup].

[[configure-the-required-tinymce-rtc-options]]
== 5. Configure the required TinyMCE RTC options

=== Basic static Real-Time Collaboration (RTC) setup

This example shows how to add the Real-Time Collaboration (RTC) plugin and configure the required options using static values. This configuration may be useful for setting up an RTC-enabled editor for initial testing, but not for production environments as it exposes your sensitive and private data.

include::partial$rtc/rtc-min-configuration-example.adoc[]

=== Basic Dynamic configuration that fetches encryption keys and tokens from a server

This example is a minimal production setup, where the document ID, encryption secret, and JSON Web Token are dynamically retrieved from a server.

[source,js]
----
tinymce.init({
  selector: 'textarea#rtc-example',
  plugins: 'rtc',
  /* Set the document ID as a string. */
  rtc_document_id: 'unique-document-id',
  /*
   * Provide a promise that retrieves an encryption key for the document
   * from a remote endpoint or server.
   */
  rtc_encryption_provider: ({documentId, keyHint}) =>
    fetch('/getKey', {
      method: 'POST',
      credentials: 'include',
      body: JSON.stringify({ documentId, keyId: keyHint })
    })
    .then((response) => response.json())
    .then(({ keyId, secret }) => ({ key: secret, keyHint: keyId }))
    .catch((error) => console.log('Failed to return encryption key\n' + error)),
  /*
   * Provide a promise that retrieves a JSON Web Token for the user
   * from a remote endpoint or server.
   */
  rtc_token_provider: ({ documentId }) =>
    fetch('/getJwtToken', {
      method: 'POST',
      credentials: 'include',
      body: JSON.stringify({ documentId }),
    })
    .then((response) => response.json())
    .then(({ jwt }) => ({ token: jwt }))
    .catch((error) => console.log('Failed to return a JWT\n' + error))
});
----

For details on the available configuration options, see: xref:rtc-options-overview.adoc[Configuration Options].
