= Save plugin
:navtitle: Save
:description: Adds a save button to the TinyMCE toolbar.
:keywords: submit, save_enablewhendirty, save_oncancelcallback, save_onsavecallback
:pluginname: Save
:plugincode: save

This plugin adds a save button to the {productname} toolbar, which will submit the form that the editor is within.

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'save',
  toolbar: 'save'
});
----

== Save error messages

The `+"Error: Form submit field collision."+` error message will appear if you call the submit button of your form "submit", which causes a collision with the JS form `+submit+` function and makes it impossible to submit the form using code. This can easily be avoided by naming the submit button `+"submitbtn"+` or similar.

So replace this:

[source,html]
----
<form><button name="submit"></button></form>
----

With this:

[source,html]
----
<form><button name="submitbtn"></button></form>
----

== Options

These settings affect the execution of the `+save+` plugin. Callbacks that will execute after saving the content or canceling saving the content are included in this section. In addition, a setting that will disable the save button when no modifications have been made to the content is available here.

include::partial$configuration/save_enablewhendirty.adoc[leveloffset=+1]

include::partial$configuration/save_oncancelcallback.adoc[leveloffset=+1]

include::partial$configuration/save_onsavecallback.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

== Commands

The Save plugin provides the following {productname} commands.

include::partial$commands/save-cmds.adoc[]
