= Security guide
:navtitle: Security guide
:description_short: Security information for TinyMCE.
:description: Information on reporting security issues, what TinyMCE does to protect users, and what you can do to protect your users.
:keywords: security, xss, scripting, vulnerability, hack, hacker, csp, mitigation, protection, protect

NOTE: The following is _general_ security advice that may be relevant to a website or application using {productname}.

== Overview

* xref:reporting-tinymce-security-issues[Reporting TinyMCE security issues]
* xref:what-we-do-to-maintain-security-for-tinymce[What we do to maintain security for TinyMCE]
** xref:scripts-and-xss-vulnerabilities[Scripts and XSS vulnerabilities]
** xref:keeping-dependencies-up-to-date[Keeping dependencies up-to-date]
* xref:configuring-content-security-policy-csp-for-tinymce[Configuring Content Security Policy (CSP) for TinyMCE]
* xref:general-security-risks-for-user-input-elements[General security risks for user input elements]
** xref:cross-site-scripting-xss[Cross-Site Scripting (XSS)]
** xref:injection[Injection]
** xref:sanitizing-html-input-to-protect-against-xss-attacks[Sanitizing HTML input to protect against XSS attacks]
** xref:insecure-transmission-and-storage-of-data[Insecure Transmission and Storage of data]
** xref:broken-authentication-and-session-management[Broken Authentication and Session Management]
** xref:using-components-with-known-vulnerabilities[Using Components with Known Vulnerabilities]
** xref:further-security-information[Further security information]

// Note: The reportingtinymcesecurityissues anchor is needed for older external links
[[reporting-tinymce-security-issues]]
== [[reportingtinymcesecurityissues]] Reporting TinyMCE security issues

{companyname} values the work of security researchers in improving the security of technology products worldwide. We welcome researchers who wish to responsibly disclose vulnerabilities in our products or systems.

Note that we do not offer any “bug bounty” program or any form of payment for disclosed vulnerabilities.

To report a potential security vulnerability, contact our Security team at mailto:infosec@tiny.cloud[infosec@tiny.cloud,Potential vulnerability report].

In line with the United States National Infrastructure Advisory Council (NIAC) https://dhs.gov/xlibrary/assets/vdwgreport.pdf[Vulnerability Disclosure Framework] (PDF link), Tiny requests community members reporting potential security vulnerabilities maintain the confidentiality of their report and discovery until Tiny has investigated the issue and taken action to fix it.

Tiny will communicate with you regarding the status of your report and will, with your permission, publicly attribute the security issue’s discovery to you after the issue has been fixed and disclosed.

[[what-we-do-to-maintain-security-for-tinymce]]
== What we do to maintain security for TinyMCE

To protect {productname} users, {companyname}:

* Patches Cross-Site Scripting (XSS) vulnerabilities,
* Keeps {productname} dependencies up to date, and
* Provides information about how to configure a Content Security Policy that works with {productname}.

[[scripts-and-xss-vulnerabilities]]
=== Scripts and XSS vulnerabilities

{productname} filters content such as scripts from the editor content, however, client-side applications can be by-passed by attackers. {companyname} recommends processing received editor content through server-side filters.

SVGs (Scalable Vector Graphics) are not supported in {productname} to protect our users and their end-users. SVGs can be used to perform both client-side and server-side attacks.

From the 1st of January 2020, Security Advisories for patched XSS vulnerabilities will be published on the https://github.com/tinymce/tinymce/security/advisories?state=published[{productname} GitHub repository Security page].

[[keeping-dependencies-up-to-date]]
=== Keeping dependencies up-to-date

To protect our users, {companyname} ensures that the TinyMCE dependencies are updated before the next version (major or minor) is released.

include::partial$misc/general-csp.adoc[]

[[general-security-risks-for-user-input-elements]]
== General security risks for user input elements

The following security risks are not {productname} specific, but are the main security risks associated with websites or applications which allow user inputs. Protecting your services and users from these risks requires server-side handling. Note that attackers will likely bypass any editor and attack the server directly, rather than use the text editor as a vector.

For information on mitigating these risks, see the provided links in each section.

[[cross-site-scripting-xss]]
=== Cross-Site Scripting (XSS)

Cross-Site Scripting (XSS) involves using website or application inputs to inject malicious, client-side code. This code can then be used to attack your users.

Although {productname} filters content such as scripts from the editor content, precautions should be taken to protect your users, such as enabling a Content Security Policy (CSP) and server-side filtering.

For information on Cross-Site Scripting and how to reduce the risk of an attack, see: https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A7-Cross-Site_Scripting_(XSS)[OWASP Top Ten 2017 -- Cross-Site Scripting (XSS)].

[[injection]]
=== Injection

Injection attacks involve attackers using website or application inputs to run server-side code, such as SQL, NoSQL, or LDAP scripts.

If user inputs are not properly sanitized server-side, host devices and user data can be compromised.

For information on Injection-related security issues and how to reduce the risk of an attack, see: https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A1-Injection[OWASP Top Ten 2017 -- Injection].

include::partial$security/sanitizing-html-input-and-protecting-against-xss-attacks-dom-parser-and-dom-purify.adoc[]

[[insecure-transmission-and-storage-of-data]]
=== Insecure Transmission and Storage of data

The transmission or storage of data without strong cryptographic protection leaves this content exposed to attackers.

Loading insecure content into the editor, or submitting content from the editor over an insecure connection exposes the user and the host server to attack.

For information on Sensitive Data Exposure issues and how to reduce the risk of an attack, see: https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A3-Sensitive_Data_Exposure[OWASP Top Ten 2017 -- Sensitive Data Exposure].

[[broken-authentication-and-session-management]]
=== Broken Authentication and Session Management

Broken or incorrectly implemented authentication and session management exposes both user data and the server to attackers, allowing them to impersonate users, including administrators.

Broken Authentication or session management may allow attackers to change or submit data through the editor, or any input field, as the compromised user account.

For information on Broken Authentication issues and how to reduce the risk of an attack, see: https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A2-Broken_Authentication[OWASP Top Ten 2017 -- Broken Authentication].

[[using-components-with-known-vulnerabilities]]
=== Using Components with Known Vulnerabilities

Using outdated components on your website or application allows attackers to exploit known vulnerabilities.

{productname} is patched when vulnerabilities are discovered. Keeping {productname} and your other dependencies up to date will protect you and your users from known vulnerabilities.

For information on issues related to using components with known issues and how to reduce the risk of an attack, see: https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A9-Using_Components_with_Known_Vulnerabilities.html[OWASP Top Ten 2017 -- Using Components with Known Vulnerabilities].

[[further-security-information]]
=== Further security information

For general security advice about securing your website or application, visit the https://owasp.org/[Open Web Application Security Project (OWASP)].
