= Custom Keyboard Shortcuts
:navtitle: Keyboard Shortcuts
:description: How-to add custom keyboard shortcuts to TinyMCE 6.
:keywords: shortcuts, shortcut, custom, keyboard

IMPORTANT: Adding a custom shortcut with a keyboard combination that conflicts with an existing {productname} or browser shortcut will override the existing shortcut.

To add a custom keyboard shortcut to {productname}, use either:

* xref:apis/tinymce.editor.adoc#addShortcut[The `+tinymce.Editor.addShortcut+` API].
* xref:apis/tinymce.shortcuts.adoc[The `+tinymce.Shortcuts.add+` API].

include::partial$misc/shortcut-os-mappings.adoc[]

== Example: custom keyboard shortcut

liveDemo::custom-shortcut[tab="js"]

== Example: adding a custom shortcut for a menu item

When adding a shortcut for a custom menu item, add both a custom shortcut and a custom menu item. To display the shortcut on a custom menu item, add the `+shortcut+` configuration option when creating the menu item.

liveDemo::custom-shortcut-2[tab="js"]

== Example: adding a custom shortcut for a toolbar button

When adding a shortcut for a custom basic toolbar or toggle button, add both a custom shortcut and a custom toolbar button. To include the keyboard shortcut information in the tooltip for a custom toolbar button, add the `+shortcut+` configuration option when creating the toolbar button.

liveDemo::custom-shortcut-3[tab="js"]
