= Suggested Edits Plugin
:navtitle: Suggested Edits 
:description: Suggested Edits keeps track of changes and review edits made by multiple authors in a document.
:description_short: A view of tracked changes made by multiple authors
:keywords: plugin, Suggested Edits, changes, diff, track changes, review changes, collaboration, multiple authors
:pluginname: Suggested Edits
:plugincode: suggestededits
:plugincategory: premium

include::partial$misc/admon-paid-addon-pricing.adoc[]

The {pluginname} plugin allows multiple users to collaborate on a document. The plugin shows which user suggested which edits, whether they added, removed, modified, or replaced any content, and allows users to provide feedback on those suggestions or give a final review by approving or rejecting them.

== Interactive example

liveDemo::{plugincode}[]

include::partial$misc/admon-iframe-only.adoc[]

== How it works

The {pluginname} plugin keeps track of every suggested edit made to the document by the current user, as the edits are made, and stores this metadata in an internal model of the document. These suggestions can then be reviewed in the `'suggestededits'` xref:custom-view.adoc[editor view], where each edit is highlighted in the document, and where you can accept, reject, or provide feedback. The `'suggestededits'` view is accessible via either the `suggestededits` toolbar button or menu button within the `View` menu. These edits, and any feedback provided, are stored in the model provided by the plugin xref:#get_model[`+get_model()+` API].

[IMPORTANT]
This model should be saved externally alongside the document, and loaded into the editor with the xref:#suggestededits_model[`+suggestededits_model+` option]. This will ensure that both the document and the model are in sync, and that every user's contributions are tracked correctly.

== Reviewing edits

The {pluginname} plugin provides a dedicated `'suggestededits'` xref:custom-view.adoc[editor view] for viewing and reviewing edits made by multiple authors. Which actions you can take in this view depends on the xref:#suggestededits_access[`+suggestededits_access+` option].

=== Header

The view contains a few controls to manage the review process: 

* Show edits: A toggle button which hides/unhides the highlighted annotations. 
* Complete review: Ends the review, applying the resolved changes to the document.
* Cancel: Exits the review with no change to the document.

=== Document

The current editor document is displayed in a sandboxed iframe, with each suggested edit highlighted as they appear in the document. The following color coding is used to indicate the type of change:  

* Green: Added content. 
* Blue: Modified attributes or formatting (e.g. bold, italic, etc.).
* Red: Removed content.

Replaced content is represented as both added and removed content, and indicates that some content was removed and replaced with new content in a single edit. When a suggestion is selected, whether in the document or in the sidebar, the corresponding highlighted suggestion in the document will be outlined in blue and scrolled into view.

=== Sidebar

Each suggested edit is listed as a card in the sidebar and color coded by the type of change, along with the user who made the suggestion, when the edit was made, and any feedback provided on that suggestion. When selected, each suggestion can be handled in the following ways:

* Accept: Resolves the edit and will be applied to the document when .
* Reject: Removes the change from the document.
* Revert: Undoes a previously accepted or rejected change.
* Provide feedback: Opens a text area for you to provide feedback on the suggestion.

Any feedback will be stored in the model and displayed underneath the card details and in chronological order. This feedback thread can be used to discuss the suggestion with the author or other reviewers. The feedback author can edit or delete their own feedback.

At the top of the sidebar, there is also a dropdown menu to apply review actions in bulk to all suggested edits:

* Accept all.
* Reject all.
* Revert all.

=== Finishing a review

When you complete a review, any resolved suggestions will be applied to the document and will no longer be tracked in the model as suggestions, including any feedback on resolved suggestions. This means that any accepted edits will remain in the docuemnt, and any rejected edits will be reverted to the state before the suggestion was made. More specifically, review actions will apply the following to the document:

* When added content is -
** Accepted: The content will remain in the document.
** Rejected: The content will be removed from the document.

* When modified content is -
** Accepted: The content will keep the current formats and attributes.
** Rejected: The content will revert to the formats and attributes it had before the edit was made.

* When removed content is -
** Accepted: The content will be remain removed from the document.
** Rejected: The content will be restored to the document.

If you cancel your review, no resolved suggestions will be applied to the document and all suggestions will remain in the model, including any feedback provided during that review session.

== Initial setup

To setup the {pluginname} plugin in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;
* add `{plugincode}` to the `toolbar` option in the editor configuration;

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea#suggestededits',  // change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
});
----

This configuration will add {pluginname} to the editor toolbar, allowing users to access the plugin features. However, to fully utilize the plugin, you will need to provide additional configuration options.

The {pluginname} plugin requires a model to store. If the model is not provided in the editor configuration, or is `+undefined+`, the plugin will generate a new model. The model contains all the current suggested edits, so unless you are starting a new document, the current model for the document should always be provided. This model can be retrieved from the editor at any time using the xref:#get_model[`getModel` API], and should be saved externally alongside the document.

The {pluginname} plugin also requires a unique user identifier to attribute suggestions made by each user, including edits and feedback. The current user should be set with the xref:#user_id[`+user_id+` option]. The user ID should be a unique string that identifies the user, such as a username or an email address. Each suggestion in the model will have a uid, allowing other users to see who made which suggestion.

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/user_id.adoc[leveloffset=+1]

include::partial$configuration/fetch_users.adoc[leveloffset=+1]

include::partial$configuration/suggestededits_model.adoc[leveloffset=+1]

include::partial$configuration/suggestededits_content.adoc[leveloffset=+1]

include::partial$configuration/suggestededits_access.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {pluginname} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]

== APIs

The {pluginname} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]

////
== Known Limitations 

[NOTE]
Since the comparison is made against the original version of the document, if there are unresolved changes by multiple authors affecting the same part, the most recent change will be used for comparison. The `hasChanges` API can be used to implement a safeguard that prevents further edits on a document with unresolved changes.

////