= Suggested Edits Plugin
:navtitle: Suggested Edits 
:description: A view that allows users to review document changes made by multiple authors
:description_short: A view of tracked changes made by multiple authors
:keywords: plugin, Suggested Edits, changes, diff
:pluginname: Suggested Edits
:plugincode: suggestededits
:plugincategory: premium

include::partial$misc/admon-revisionhistory-paid-addon-pricing.adoc[]

include::partial$misc/admon-requires-8.0v.adoc[]

The Suggested Edits plugin allows users to easily review and manage changes made to a document by multiple authors. 

== Interactive example

liveDemo::{plugincode}[]

include::partial$misc/admon-iframe-only.adoc[]

== How it works

The Suggested Edits plugin monitors edits made to a document by comparing its current state to the original version. Each change is attributed to its respective author and can be approved or rejected before being applied to the document.

The plugin includes a dedicated view for reviewing current changes, accessible via the `{plugincode}` toolbar button or the menu option under the `View` menu. The key components are:

. **Read-only Diff View**:
+
Highlights the current changes made to the document, using the following color codes:  
+
* Green: New content. 
* Blue: Modified content. Modifications to HTML content implies attributes or formatting (e.g. bold, italic, etc.).
* Red: Removed content.

. **Sidebar**:
+
Contains a header with the following buttons: 
+
* Show Changes: A toggle button which hides/unhides the change annotations. 
* Complete: Ends the review and applies the resolved changes. 
* Cancel: Ends the review without any further action.

+
The sidebar also displays all tracked changes that need to be resolved. Each change can be handled in the following ways:
* Accept: Applies the change to the document. 
* Reject: Removes the change from the document. 
* Revert: Undoes a previously accepted or rejected change. 

== Basic setup

To setup the {pluginname} plugin in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;
* add `{plugincode}` to the `toolbar` option in the editor configuration;
* add `{plugincode}_model` to the editor configuration. 
* add `{plugincode}_uid` to the editor configuration. 

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_model: {
    version: 1, 
    maxId: 0, 
    contents: [
      {
        type: 'p',
        children: [
          { text: 'Hello, World!' }
        ]
      }
    ]
  },
  suggestededits_uid: 'unique-identifier' // replace this with a unique string to identify the user 
});
----

== Suggestions

The plugin also enables users to provide suggestions or feedback to edits before they are resolved. This feature is only available if xref:{plugincode}_access[`+suggestededits_access+`] is set to `admin` or `suggest`. 

Example: Using Suggestions 

liveDemo::suggestededits-suggestions[]

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/suggestededits-options.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {pluginname} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]

== APIs

The {pluginname} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]

////
== Known Limitations 

[NOTE]
Since the comparison is made against the original version of the document, if there are unresolved changes by multiple authors affecting the same part, the most recent change will be used for comparison. The `hasChanges` API can be used to implement a safeguard that prevents further edits on a document with unresolved changes.

////