= Suggested Edits Plugin
:navtitle: Suggested Edits 
:description: A view that allows users to review document changes made by multiple authors
:description_short: A view of tracked changes made by multiple authors
:keywords: plugin, Suggested Edits, changes, diff
:pluginname: Suggested Edits
:plugincode: suggestededits
:plugincategory: premium

include::partial$misc/admon-revisionhistory-paid-addon-pricing.adoc[]

include::partial$misc/admon-requires-8.0v.adoc[]

The Suggested Edits plugin allows users to easily review and manage changes made to a document by multiple authors. 

== Interactive example

liveDemo::{plugincode}[]

include::partial$misc/admon-iframe-only.adoc[]

== How it works

The Suggested Edits plugin builds a document model of the editor content to track edits made by multiple authors. This model is used to compare the current content of the editor with the original version, highlighting changes such as insertions, modifications, and deletions. 

This allows users to review the changes made to the document, provide feedback on them, and accept or reject them as needed. See xref:#suggestededits_access[`suggestededits_access`] option for more information on how to configure user permissions for editing and reviewing content. 

[NOTE]
The model's content should be considered as metadata of the editor's HTML content, and both should be saved together to ensure correctness. See xref:#suggestededits_content[`suggestededits_content`] for more information on how to configure the source of content loaded into the editor. 

A dedicated read-only view is provided for reviewing current changes, accessible via the `{plugincode}` toolbar button or the menu option under the `View` menu. The key components are:

. **Read-only Diff View**:
+
Highlights the current changes made to the document, using the following color codes:  
+
* Green: New content. 
* Blue: Modified content. Modifications to HTML content implies attributes or formatting (e.g. bold, italic, etc.).
* Red: Removed content.

. **Sidebar**:
+
Contains a header with the following buttons: 
+
* Show Changes: A toggle button which hides/unhides the change annotations. 
* Complete: Ends the review and applies the resolved changes. 
* Cancel: Ends the review without any further action.

+
The sidebar also displays all tracked changes that need to be resolved. Each change can be handled in the following ways:
* Accept: Applies the change to the document. 
* Reject: Removes the change from the document. 
* Revert: Undoes a previously accepted or rejected change. 

== Types of suggestions 

There are four basic types of suggestions that are tracked by the Suggested Edits plugin:

==== Insert
Tracks the addition of new content to the document. 

==== Modify
Tracks HTML attribute changes or formatting changes to existing content, such as bold or italic text. Note that if multiple users modify the same content, the original author will still be attributed with the change. 

==== Delete
Tracks the removal of content from the document.

==== Replace
Tracks the replacement of existing content with new content. This is treated as a combination of a delete and an insert, where the original content is selected and replaced by new content. Note that if multiple users replace the same content, the most recent author will be attributed with the change.

== Initial setup

The Suggested Edits plugin uses a document model to track changes. If the model is not provided in the editor configuration, the plugin will create a new model from the current content of the editor. This model can be retrieved from the editor at any time using the xref:#get_model[`getModel` API], and should be saved externally

To setup the {pluginname} plugin in the editor:

* add `{plugincode}` to the `plugins` option in the editor configuration;
* add `{plugincode}` to the `toolbar` option in the editor configuration;
* add `{plugincode}_model` to the editor configuration, if a document is already being tracked.

For example:

[source,js]
----
const suggestededits_model = `<YOUR_DOCUMENT_MODEL>` // model provided by the getModel API

tinymce.init({
  selector: 'textarea#suggestededits',  // change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_model,
});
----

== Options

The following configuration options affect the behavior of the {pluginname} plugin.

include::partial$configuration/suggestededits-options.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {pluginname} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]

== APIs

The {pluginname} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]

////
== Known Limitations 

[NOTE]
Since the comparison is made against the original version of the document, if there are unresolved changes by multiple authors affecting the same part, the most recent change will be used for comparison. The `hasChanges` API can be used to implement a safeguard that prevents further edits on a document with unresolved changes.

////