= Support
:navtitle: Support
:description: Getting support and supported platforms
:description_short: Getting support and supported platforms
:keywords: browser, compatibility, safari, firefox, chrome, edge, mobile, support, supported, browsers, windows, osx, linux, premium, self-hosted, selfhosted

== Getting support

=== Premium support

Paid premium support is available as part of link:{pricingpage}/[{enterpriseversion} and {cloudname} subscriptions]. {productname} Enterprise customers can link:{supporturl}/[submit a case support request].

=== Community support

Open Source Community Edition users can get free help from Stack Overflow using the link:{communitysupporturl}[`{prodnamecode}` tag].

// Note: The supportedversionsandplatforms anchor is needed for older external links
[[supported-versions-and-platforms]]
== [[supportedversionsandplatforms]] Supported Versions and Platforms

include::partial$misc/supported-versions.adoc[leveloffset=+1]

include::partial$misc/browser-compatibility.adoc[leveloffset=+1]

include::partial$misc/mobile-platform-compatibility.adoc[leveloffset=+1]

Visit xref:tinymce-for-mobile.adoc[{productname} mobile documentation] for information on {productname} mobile setup and configuration.

== Premium plugin support information

include::partial$misc/plugin-support-table.adoc[leveloffset=+1]

include::partial$misc/support-powerpaste.adoc[leveloffset=+1]

=== System Requirements: Self-hosted Enterprise

The {productname} server-side components are delivered as Docker/OCI container images. The following requirements must be met:


Host System Requirements::
* Operating System:
** Linux
** macOS
** Windows with WSL 2
* CPU: Dual Core Processor ~ 2Ghz. For higher loads, a quad core or higher is recommended
* RAM: 4 Gigabytes of RAM available for services
* Storage: At least 10GB of free disk space for container images and data

Container Platform Support::
* Docker standalone
* Container orchestration platforms (such as Kubernetes)
* Cloud container services

[NOTE]
For production deployments, we recommend using container orchestration platforms or cloud container services that provide built-in scaling and monitoring capabilities.
