= Support
:navtitle: Support
:description: Getting support and supported platforms
:description_short: Getting support and supported platforms
:keywords: browser, compatibility, safari, firefox, chrome, edge, mobile, support, supported, browsers, windows, osx, linux, premium, self-hosted, selfhosted

[[tinymce-version-support-timeframes]]
== {productname} Version Support Timeframes

=== Premium Support

Paid premium support is available as part of link:{pricingpage}/[{enterpriseversion} and {cloudname} subscriptions]. {productname} Enterprise customers can link:{supporturl}/[submit a case support request].

=== End of Premium Support

Support for the enterprise version of {productname} ends **18 months** from the date of release.

For detailed release dates and additional release information, please visit the xref:release-notes.adoc[Release Information] page on the xref:introduction-to-tinymce.adoc[{productname} documentation].

=== Community Support

Open Source Community Edition users can get free help from Stack Overflow using the link:{communitysupporturl}[`{prodnamecode}` tag].

==== End of Community Support

Support for the current community version ends with the **next** release of the community version, regardless of whether it is a minor or major release.

// Note: The supportedversionsandplatforms anchor is needed for older external links
[[supported-versions-and-platforms]]
== [[supportedversionsandplatforms]] Supported Versions and Platforms

include::partial$misc/software-licence-agreement.adoc[leveloffset=+1]

include::partial$misc/browser-compatibility.adoc[leveloffset=+1]

include::partial$misc/mobile-platform-compatibility.adoc[leveloffset=+1]

Visit xref:tinymce-for-mobile.adoc[{productname} mobile documentation] for information on {productname} mobile setup and configuration.

== Premium plugin support information

include::partial$misc/plugin-support-table.adoc[leveloffset=+1]

include::partial$misc/support-powerpaste.adoc[leveloffset=+1]

=== Supported Application Servers: Self-hosted Enterprise

The {productname} spell checking server-side component requires a Java Web Application Server that supports Servlet Implementation API 3.0.

Java Development Kit::
* JDK 8

Java (J2EE) Application Servers::
include::partial$misc/supported-application-servers.adoc[]

Operating Systems::
* Windows Server 2008 SP2
* Red Hat Enterprise Linux v6
* Red Hat Enterprise Linux v5

Minimum Hardware Requirements::
* CPU: Dual Core Processor ~ 2Ghz. For higher loads, a quad core or higher is recommended.
* RAM: 4 Gigabytes of RAM available for services