= Table of Contents plugin
:navtitle: Table of Contents
:description: Insert a simple Table of Contents into the {productname} editor
:keywords: tableofcontents, tableofcontents_depth, tableofcontents_class, tableofcontents_header, toc
:pluginname: Table of Contents
:plugincode: tableofcontents
:pluginminimumplan: tiertwo

include::partial$misc/admon-premium-plugin.adoc[]

The {pluginname} plugin generates a basic _table of contents_ (ToC) and inserts it into the editor at the current cursor position. ToC entries are generated from header elements (`h1 – h6` elements) in the content.

NOTE: In previous versions of {productname} the {pluginname} plugin was provided as an open source plugin also called {pluginname}.

== Interactive Example

liveDemo::tableofcontents[]

// include::partial$misc/purchase-premium-plugins.adoc[]

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'tableofcontents',
  toolbar: 'tableofcontents',
});
----

The _Table of Contents_ will have a simple HTML structure - a wrapper `+div+` element, a header with _editable_ title and unordered nested list with navigation links. Nesting depth is customizable.

Internally plugin doesn't apply any inline styles. Basic formatting can be added via xref:editor-content-css.adoc[Boilerplate Content CSS], that can be customized to your needs.

[source,css]
----
include::example$css-codeblock/tableofcontents-plugin.css[]
----

== Options

include::partial$configuration/tableofcontents_depth.adoc[leveloffset=+1]

include::partial$configuration/tableofcontents_header.adoc[leveloffset=+1]

include::partial$configuration/tableofcontents_class.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The Table of Contents plugin provides the following {productname} commands.

include::partial$commands/tableofcontents-cmds.adoc[]
