= Template plugin
:navtitle: Template
:description: Custom templates for your content.
:keywords: insert, template_cdate_classes, template_cdate_format, template_mdate_classes, template_mdate_format, template_replace_values, template_selected_content_classes, template_preview_replace_values
:pluginname: Template
:plugincode: template


IMPORTANT: The Template plugin, has been marked as *deprecated*. As a result, it will be completely removed from the upcoming TinyMCE 7.0 release. As an alternative solution, we highly recommend utilizing the xref:advanced-templates.adoc[Advanced Template] Premium plugin. 

The `+template+` plugin adds support for custom templates. It also adds a menu item `+Insert template+` under the `+Insert+` menu and a toolbar button.

== Basic setup

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'template',
  toolbar: 'template'
});
----

== Interactive example

This example shows how the template plugin can be used to insert custom templates with pre-defined markup and values.

liveDemo::template[tab="js"]

== Options

These settings affect the execution of the `+template+` plugin. Predefined templates for items such as created dates and modified dates can be set here.

include::partial$configuration/templates.adoc[leveloffset=+1]

include::partial$configuration/template_cdate_classes.adoc[leveloffset=+1]

include::partial$configuration/template_cdate_format.adoc[leveloffset=+1]

include::partial$configuration/template_mdate_classes.adoc[leveloffset=+1]

include::partial$configuration/template_mdate_format.adoc[leveloffset=+1]

include::partial$configuration/template_replace_values.adoc[leveloffset=+1]

include::partial$configuration/template_preview_replace_values.adoc[leveloffset=+1]

include::partial$configuration/template_selected_content_classes.adoc[leveloffset=+1]

== Template Plugin Examples

=== Example: using the `+template+` plugin

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'template',
  toolbar: 'template',
  template_cdate_classes: 'cdate creationdate',
  template_mdate_classes: 'mdate modifieddate',
  template_selected_content_classes: 'selcontent',
  template_cdate_format: '%m/%d/%Y : %H:%M:%S',
  template_mdate_format: '%m/%d/%Y : %H:%M:%S',
  template_replace_values: {
    username: 'Jack Black',
    staffid: '991234'
  },
  templates: [
    {
      title: 'Editor Details',
      url: 'editor_details.html',
      description: 'Adds Editor Name and Staff ID'
    },
    {
      title: 'Timestamp',
      url: 'time.html',
      description: 'Adds an editing timestamp.'
    }
  ]
});
----

=== Example of an external template list

This is the contents your backend page should return if you specify a URL in the templates option. A simple array containing each template to present. This URL can be a backend page, for example a PHP file.

[source,json]
----
[
  {"title": "Some title 1", "description": "Some desc 1", "content": "My content"},
  {"title": "Some title 2", "description": "Some desc 2", "url": "development.html"}
]
----

== Making Templates

A template is a file with a `+div+` containing the template data. All `+html+` outside the `+div+` will simply be presented to the user in the preview frame.

A template has more capabilities than a simple snippet, for example, a template can have dynamic content/smart content that gets updated by functions located in the `+template_replace_values+` key. These functions will continue to be executed each time a cleanup procedure is performed.

Each template needs to be inside of a div with the `+mceTmpl+` class, like this example:

[source,html]
----
<!-- This will not be inserted -->
<div class="mceTmpl">
  <table width="98%%"  border="0" cellspacing="0" cellpadding="0">
    <tr>
      <th scope="col">&nbsp;</th>
      <th scope="col">&nbsp;</th>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</div>
----

== Making Snippets

Snippets are `+html+` code chunks that can be inserted. Replace variables will only be executed upon insert, without being wrapped in a template `+div+` element. So if you define `+somevar1+` in `+template_replace_values+` array it will be replaced on insert. If you wish to preview the replacements before inserting, use `+template_preview_replace_values+`.

[source,html]
----
This is a simple <strong>snippet</strong>. Will be replaced: {$somevar1}.
----

include::partial$configuration/ref_time_date_formats.adoc[leveloffset=+1]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The Template plugin provides the following {productname} command.

include::partial$commands/template-cmds.adoc[]
