= Understanding editor loads
:navtitle: Understanding editor loads
:description: Relevant information for Tiny Cloud users to help understand editor loads for {productname}.
:keywords: invalid-api-key, API, {productname}, cloud, frequently asked questions

== Understanding editor loads for {productname}

[IMPORTANT]
This information is only relevant to Tiny Cloud users. Users who self-host the open source version of {productname} are not subject to editor load restrictions, but must comply with the https://github.com/tinymce/tinymce/blob/master/LICENSE.TXT[open source license]. 

An editor load is the event that occurs each time {productname} is initialized in your application. The editor dispatches the 'init' event to indicate a successful load. For example, if 100 users load {productname} 10 times each, the result would be 1,000 editor loads. 

The process of initializing an editor involves several steps.

. The integrator initializes one or more editors on the webpage, commonly accomplished through the `tinymce.init({ ... })` method. 
+
. The `selector` property of the `init` method determines which elements should be replaced with editor instances. For example: if the selector is `textarea` and there are 5 textarea elements on the page, 5 editor instances will be created.
+
Each editor instance performs the same initialization sequence and then dispatches an `init` event. This event is dispatched even if the the editor is not visible.
+
. **The 'init' event serves as the conclusive indicator that the editor has completed its loading process**. At this point, the editor has been successfully initialized and is ready for user interaction. 

== How are editor loads counted?

An editor load is counted each time a new {productname} editor instance completes the initialization sequence and dispatches an `init` event.

== What happens if I have multiple editors on a page?

Each individual editor instance on a page is counted as one editor load. For example, if a page has ten editors, a single refresh of that page results in ten editor loads.

== What can contribute to a high number of editor loads?

The most obvious scenario is using multiple editors on a single page (see above). For example:

* An email building app that has a {productname} editor embedded in multiple sections
* A publicly available page on a high traffic website with multiple editor instances

== How can I get unlimited editor loads?

You can get unlimited editors loads one of three ways:

* The open-source version of {productname} can be self hosted, and is not subject to editor load restrictions.
* The open-source version of {productname} is also available via third party-hosted CDNs and is not subject to editor load restrictions.
* For the Enterprise version of Tiny MCE with Premium features, https://www.tiny.cloud/contact/[get in touch with our Sales team] for a custom quote.

== I have an annual plan. Are my editor loads calculated monthly or over the entire year?

If you have an annual plan, your editor loads are calculated on a monthly basis within the structure of your annual plan. Similar to our monthly plans, you have a set monthly editor load limit and are automatically charged $40 USD per every block of 1,000 editor loads over the plan limit. Learn more about ////<Insert link>[Tiny Cloud’s Usage-Based Billing model]////.
