= Bundling TinyMCE in Vue.js
:navtitle: Using a package manager with bundling
:description: A guide on bundling TinyMCE with a Vue.js application using a module loader.
:keywords: integration, integrate, vue, vuejs, bundle, webpack, vite
:productSource: package-manager
:packageName: @tinymce/tinymce-vue

This guide shows how to bundle {productname} into a Vue.js application using the link:https://github.com/tinymce/tinymce-vue[{productname} Vue.js component^].

== Prerequisites

This procedure requires:

* link:https://nodejs.org/en/download/[Node.js LTS] (recommended).
* link:https://cli.vuejs.org/[Vue CLI] (optional).

== Procedure

. Create a new Vue project named `tinymce-vue-demo` using the link:https://github.com/vuejs/create-vue[Create Vue Tool].
* From a command line or command prompt create a Vue.js 3.x project: `+tinymce-vue-demo+`.
+
[source,sh]
----
npm create vue@3
----

* If a Vue.js 2.x project is required, instead use:
+
[source,sh]
----
npm create vue@2
----
+
[NOTE]
====
As per the link:https://vuejs.org/about/faq.html#what-s-the-difference-between-vue-2-and-vue-3[Vue FAQ], _Vue 2 will reach End of Life by the end of 2023_.
====

* Follow the prompts and type `+tinymce-vue-demo+` as the project name.
. Navigate into the newly created directory.
+
[source,sh]
----
cd tinymce-vue-demo
----

. Install the `+tinymce+` and `+tinymce-vue+` packages.
* For Vue.js 3.x users:
+
[source,sh]
----
npm install tinymce "@tinymce/tinymce-vue"
----

* For Vue.js 2.x users:
+
[source,sh]
----
npm install tinymce "@tinymce/tinymce-vue@^3"
----

. Create `+src/editor.js+` and set the contents to:
+
[source,js]
----
// Add the @tinymce/tinymce-vue wrapper to the bundle
import Editor from '@tinymce/tinymce-vue';

// Ensure TinyMCE is imported to register the global variable required by other components
import 'tinymce/tinymce';
// DOM model
import 'tinymce/models/dom/model';
// Theme
import 'tinymce/themes/silver';
// Toolbar icons
import 'tinymce/icons/default';
// Editor styles
import 'tinymce/skins/ui/oxide/skin.min.css';

// Import plugins
import 'tinymce/plugins/advlist';
import 'tinymce/plugins/autolink';
import 'tinymce/plugins/link';
import 'tinymce/plugins/image';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/table';
import 'tinymce/plugins/code';
import 'tinymce/plugins/help';
// Include resources that a plugin lazy-loads at the run-time
import 'tinymce/plugins/help/js/i18n/keynav/en.js';
import 'tinymce/plugins/wordcount';

// Content styles, including inline UI like fake cursors
import 'tinymce/skins/content/default/content.js';
import 'tinymce/skins/ui/oxide/content.js';

// Export Editor component for use in Vue components
export default Editor;
----
+
. Update `+src/App.vue+` to import and configure `+Editor+`.
+
[source,jsx]
----
<template>
  <div>
    <h1>TinyMCE Vue Demo</h1>
    <Editor
      v-model="content"
      :init="editorConfig"
      licenseKey="gpl"
    />
  </div>
</template>

<script>
import Editor from './editor.js';

export default {
  name: 'App',
  components: {
    Editor
  },
  data() {
    return {
      content: '<p>This is the initial content of the editor.</p>',
      editorConfig: {
        height: 500,
        plugins: 'advlist autolink lists link image table code help wordcount',
        toolbar: 'undo redo | blocks | bold italic | alignleft aligncenter alignright | bullist numlist | help'
      }
    };
  }
};
</script>
----

. To start the development server, run:
+
[source,sh]
----
npm run dev
----

== Other resources

* For reporting issues, go to: link:https://github.com/tinymce/tinymce-vue/issues[{productname} Vue.js issues^].
* For more examples of `tinymce-vue` wrapper, see: link:https://tinymce.github.io/tinymce-vue/[the tinymce-vue storybook^].
* For information on bundling, see: xref:introduction-to-bundling-tinymce.adoc[]
* For guides on integrating {productname} premium plugins, see: xref:bundling-plugins.adoc#using-premium-plugins[Using premium plugins].
* For information on customizing:
** {productname} integration, see: xref:vue-ref.adoc[Vue.js framework Technical Reference].
** {productname}, see: xref:basic-setup.adoc[Basic setup].
** The Vue.js application, see: https://vuejs.org[the Vue.js documentation].
