ifeval::["{extensionType}" != "Packs"]
:extensionType: plugin
endif::[]
ifeval::[{pluralExtensionType} == true]
:isAre: are
endif::[]
ifeval::[{pluralExtensionType} != true]
:isAre: is
endif::[]

ifeval::["{pluginname}" != "Tiny Drive"]
== Getting started with {productname} {pluginname}
endif::[]
ifeval::["{pluginname}" == "Tiny Drive"]
== Getting started with {pluginname}
endif::[]

[[creating-an-account]]
=== Creating an account

Try the *{pluginname} {extensionType}* and the {cloudname} with a free link:{accountsignup}[{accountpage}]. New accounts receive a 30-day trial of the {companyname} link:{plugindirectory}[premium plugins], skins, and icon packs; with no credit card information or commitment required.

ifeval::["{pluginname}" != "Tiny Drive"]
=== Get {productname} {pluginname}
endif::[]
ifeval::["{pluginname}" == "Tiny Drive"]
=== Get {pluginname}
endif::[]

ifeval::["{pluginminimumplan}" != "enterprise"]
The *{pluginname} {extensionType}* {isAre} included in the following {cloudname} plans:
endif::[]
ifeval::["{pluginminimumplan}" == "enterprise"]
The *{pluginname} {extensionType}* {isAre} included in link:{pricingpage}[{enterpriseplan}].
endif::[]

ifeval::["{pluginminimumplan}" == "tierone"]
* The link:{pricingpage}[{tieroneplan}].
* The link:{pricingpage}[{tiertwoplan}].
* The link:{pricingpage}[{tierthreeplan}].
* link:{pricingpage}[{enterpriseplan}].
endif::[]
ifeval::["{pluginminimumplan}" == "tiertwo"]
* The link:{pricingpage}[{tiertwoplan}].
* The link:{pricingpage}[{tierthreeplan}].
* link:{pricingpage}[{enterpriseplan}].
endif::[]
ifeval::["{pluginminimumplan}" == "tierthree"]
* The link:{pricingpage}[{tierthreeplan}].
* link:{pricingpage}[{enterpriseplan}].
endif::[]


ifeval::["{pluginminimumplan}" == "tiertwo"]
A 14-day free trial is also available for the {tiertwoplan} and the {tierthreeplan}.
endif::[]
ifeval::["{pluginminimumplan}" == "tierthree"]
A 14-day free trial is also available for the {tiertwoplan} and the {tierthreeplan}.
endif::[]

[[further-information]]
== Further information

For information on:

* {cloudname} plans, see: link:{pricingpage}[{companyname} Pricing Plans].
ifeval::["{extensionType}" == "Packs"]
* Enabling premium skins, see: link:{rootDir}configure/editor-appearance.html#skin[The `skin` setting].
* Enabling premium icon packs, see: link:{rootDir}configure/editor-appearance.html#icons[The `icons` setting].
endif::[]
ifeval::["{extensionType}" != "Packs"]
* Configuring the *{pluginname} {extensionType}*, see: link:{rootDir}plugins/{plugindocspage}.html[The {pluginname} {extensionType} documentation].
endif::[]
