{% if extensionType != 'Packs' %}
:extensionType: plugin
{% endif %}
{% if pluralExtensionType == true %}
:isAre: are
{% else %}
:isAre: is
{% endif %}
## Getting started with {% if pluginname != 'Tiny Drive' %}{productname}{% endif %} {\{pluginname}}

[[creating-an-account]]
=== Creating an account

Try the *{\{pluginname}} {\{extensionType}}* and the {cloudname} with a free link:{accountsignup}[{accountpage}]. New accounts receive a 30-day trial of the {companyname} link:{plugindirectory}[premium plugins], skins, and icon packs; with no credit card information or commitment required.

[[get-if-pluginname-tiny-drive-site-productname-endif-pluginname]]
=== Get {% if pluginname != 'Tiny Drive' %}{productname}{% endif %} {\{pluginname}}

{% if pluginminimumplan != 'enterprise' %}
The *{\{pluginname}} {\{extensionType}}* {\{isAre}} included in the following {cloudname} plans:
{% else %}
The *{\{pluginname}} {\{extensionType}}* {\{isAre}} included in link:{pricingpage}[{enterpriseplan}].
{% endif %}

{% case pluginminimumplan %}
{% when 'tierone' %}- The link:{pricingpage}[{tieroneplan}].
{% when 'tierone' or 'tiertwo' %}- The link:{pricingpage}[{tiertwoplan}].
{% when 'tierone' or 'tiertwo' or 'tierthree' %}- The link:{pricingpage}[{tierthreeplan}].
- link:{pricingpage}[{enterpriseplan}].
{% endcase %}

{% if pluginminimumplan == 'tiertwo' or pluginminimumplan == 'tierthree' %}
A 14-day free trial is also available for the {tiertwoplan} and the {tierthreeplan}.
{% elsif pluginminimumplan == 'tierthree' %}
A 14-day free trial is available for the {tierthreeplan}.
{% endif %}

[[further-information]]
== Further information

For information on:

* {cloudname} plans, see: link:{pricingpage}[{companyname} Pricing Plans].{% if extensionType == 'Packs' %}
* Enabling premium skins, see: link:{rootDir}configure/editor-appearance.html#skin[The `skin` setting].
* Enabling premium icon packs, see: link:{rootDir}configure/editor-appearance.html#icons[The `icons` setting].{% else %}
* Configuring the *{\{pluginname}} {\{extensionType}}*, see: link:{rootDir}plugins/{plugindocspage}.html[The {\{pluginname}} {\{extensionType}} documentation].
{% endif %}
