=== Configuring the Service

Running this command will generate a log warning about `allowed-origins` not being configured. This is expected, as it will be set up in the next step.

The {productname} server-side components require a configuration file to function correctly. By convention, this file is named `application.conf`. For more information, refer to link:https://www.tiny.cloud/docs/tinymce/latest/configure-required-services/[Required configuration for the server-side components]. 

This configuration file requires at least the following information:

* `allowed-origins`: Specifies the domains allowed to communicate with server-side editor features. This is **mandatory** for all server-side components.

=== Run with Docker Compose

The Docker container can be run with `docker compose`. Here's an example directory structure:

[source,sh]
----
{service-type}-service/
└── resources/
└── application.conf
└── docker-compose.yaml
----

Here is an example `application.conf` file with basic configurations:

[source, conf]
----
ephox {
  allowed-origins {
    origins = [
      "<http://example.com>",
      "<http://good.com> ",
      "*.my.company.org"
    ]
  }
}
----

. Create the `docker-compose.yaml` file:

+
[source, yaml]
----
services:
  {service-name}:
    image: registry.containers.tiny.cloud/{service-name}:<VERSION>
    ports:
      - "{service-port}:{service-port}"
    restart: always
    init: true
    volumes:
      - type: bind
        source: ./application.conf
        target: /ephox-{service-type}/ephox-{service-type}-docker-env.conf
        read_only: true
----

. Run the service (within the same directory where `docker-compose.yaml` was placed):

+
[source, sh]
----
docker compose up
----

=== Test the Service

. Test via cURL command:

+
[source, sh]
----
curl http://localhost:{service-port}/version
----

. Test the service with an allowed origin:

+
[source, sh]
----
curl http://localhost:{service-port}/check -H "Origin: http://good.com"
----

. Test with an unauthorized origin:

+
[source, sh]
----
curl http://localhost:{service-port}/check -H "Origin: http://bad.com"
----

If unauthorized, you should see: `{ "message": "The supplied authentication is not authorized to access this resource" }`

=== Next Steps

For detailed configuration options and integration with {productname}, refer to:

* link:https://www.tiny.cloud/docs/tinymce/latest/configure-required-services/[Required configuration for the server-side components]
* The specific documentation for this service's {productname} plugin
