:rootDir: ./../../
:partialsDir: {rootDir}partials/
= Embed Rich Media
:description: Add rich media previews inside TinyMCE.
:keywords: enterprise pricing video youtube vimeo mp3 mp4 mov movie clip film link linkchecking linkchecker mediaembed media

The link:{rootDir}plugins/mediaembed.html[Enhanced Media Embed plugin] makes it easy to add an enhanced content creation experience in your website or app with enriched media previews from the most popular web sources. Facebook, YouTube, Flickr, NY Times, Vimeo, Hulu, Tumblr, CodePen, SlideShare, TechCrunch, WordPress, Twitch, Spotify ... and many more!

By easy, we mean easy. The service automatically "`looks behind the link`" to see whether a URL in the TinyMCE editor points to a rich media source. That URL will resolve into an enhanced media thumbnail whenever possible.

It is now as simple as adding a plugin to deliver a modern, content creation experience that everyone takes for granted.

Your have two deployment options. One is super easy with TinyMCE Cloud, the other is to go the more traditional Self-hosted route, requiring an additional link:{rootDir}enterprise/server/index.html[server-side component] to be installed and configured.

[[enhanced-media-embed-cloud-quick-setup]]
== Enhanced Media Embed Cloud Quick Setup
anchor:enhancedmediaembedcloudquicksetup[historical anchor]

link:{rootDir}cloud-deployment-guide/editor-and-features.html[TinyMCE Cloud] makes setting up Enhanced Media Embed a breeze. Simply include the `mediaembed` parameter in your `tinymce.init` and have our Cloud services do the work for you.

[[enhanced-media-embed-self-hosted-quick-setup]]
== Enhanced Media Embed Self-hosted Quick Setup
anchor:enhancedmediaembedself-hostedquicksetup[historical anchor]

If you'd rather deploy Enhanced Media Embed via the Self-hosted package, you have a little more work to do. Once you've got the link:{rootDir}enterprise/server/index.html[server-side component] installed, additional configuration to your `application.conf` file is required. (Don't forget to restart the Java application server after updating the configuration.)

You also need to link:{rootDir}enterprise/embed-media/mediaembed-server-integration.html[integrate] and link:{rootDir}enterprise/embed-media/mediaembed-server-config.html[configure] the Enhanced Media Embed server.

[NOTE]
====
*Important note:* The Enhanced Media Embed server currently does not support integration with IBM WebSphere Application Server.
====
