[[installation]]
== Installation

[NOTE]
A valid service license key is required to run the {pluginname} on-premises service. This is separate from the {productname} editor license key. See xref:service-license-keys.adoc[Service license keys] for details.
link:https://www.tiny.cloud/contact/[Contact us] for a trial service license key.

=== Supported technologies

The application is provided as a docker image by default.

It can be run with any Open Container runtime tool e.g. link:https://kubernetes.io/[Kubernetes], link:https://www.redhat.com/en/technologies/cloud-computing/openshift[OpenShift], link:https://podman.io/[Podman], link:https://docs.docker.com/[Docker] and many others.

Refer to the xref:individual-import-from-word-and-export-to-word-on-premises.adoc#requirements[Requirements guide] for more information about the hardware and software requirements to run the {pluginname} On-Premises.

=== Setting up the application using a Docker container

. The username and password credentials supplied by Tiny are utilized for logging into the Docker registry and retrieving the Docker image.
. Containerize the application using `docker` or `docker-compose`.
. Use a demo page to verify if the application works properly.

==== Containerize example using docker

Login to Docker registry:

[source, sh, subs="attributes+"]
----
docker login -u tiny -p [access-token] registry.containers.tiny.cloud
----

Pull the Docker image: 

[source, sh, subs="attributes+"]
----
docker pull {dockerimageimportfromwordexporttoword}:[version]
----

[TIP]
====
To view all available Docker image versions, refer to the changelog at link:https://registry.containers.tiny.cloud/api/changelogs/docx-converter-tiny[docx-converter-tiny].

To ensure access to the most recent version of the service, {companyname} recommends using the `latest` tag when pulling the image.
====

Launch the Docker container:

[source, sh, subs="attributes+"]
----
docker run --init -p 8080:8080 -e LICENSE_KEY="$DOCX_LICENSE_KEY" {dockerimageimportfromwordexporttoword}:[version]
----

Replace `+$DOCX_LICENSE_KEY+` with the service license key, or set `+DOCX_LICENSE_KEY+` as an environment variable. See xref:service-license-keys.adoc#using-service-specific-environment-variables[Using service-specific environment variables] for details.

If using authorization provide the SECRET_KEY:

[source, sh, subs="attributes+"]
----
docker run --init -p 8080:8080 -e LICENSE_KEY="$DOCX_LICENSE_KEY" -e SECRET_KEY=[your_secret_key] {dockerimageimportfromwordexporttoword}:[version]
----

Read more about using authorization in the xref:individual-import-from-word-and-export-to-word-on-premises.adoc#authorization[authorization] section.

==== Containerize example using docker-compose

. Create the docker-compose.yml file:
+
[source, yml, subs="attributes+"]
----
version: "3.8"
services:
  doc-converter:
    image: {dockerimageimportfromwordexporttoword}:[version]
    ports:
      - "8080:8080"
    restart: always
    init: true
    environment:
      LICENSE_KEY: "$\{DOCX_LICENSE_KEY}"
      # Secret Key is optional
      SECRET_KEY: "secret_key"
----
+
For details on `SECRET_KEY` usage check the xref:individual-import-from-word-and-export-to-word-on-premises.adoc#authorization[authorization] section.
+
. Run:

[source, bash]
----
docker compose up
----

[NOTE]
====
* Without a correct `+LICENSE_KEY+` the application will not start. Set `+DOCX_LICENSE_KEY+` in the `+.env+` file or shell environment with a valid service license key.
** If the license is invalid, a wrong license key error will display in the logs and the application will not run.
* It is advisable to override the `+SECRET_KEY+` variable using a unique and hard to guess string for security reasons.
====

=== Next steps

Use the link:http://localhost:8080/v2/convert/html-docx[http://localhost:8080/v2/convert/html-docx] endpoint to export DOCX files. Check out the xref:individual-import-from-word-and-export-to-word-on-premises.adoc#authorization[authorization] section to learn more about tokens and token endpoints.

Use the demo page available on link:http://localhost:8080/demo[http://localhost:8080/demo] to generate an example DOCX file.

Refer to the {pluginname} REST API documentation on link:http://localhost:8080/docs[http://localhost:8080/docs] for more details.