= Bootstrap integration
:description: How to override the built-in block on `focusin` in Bootstrap dialogs when using TinyMCE.
:keywords: integration integrate bootstrap
:title_nav: Bootstrap

[#tinymce-bootstrap-integration-quick-start-guide]
== TinyMCE Bootstrap integration quick start guide

Using {{site.productname}} with bootstrap does not require any special configuration.

The {{site.productname}} jQuery integration can be used with bootstrap. For information on using the jQuery integration, see: link:{{site.baseurl}}/integrations/jquery/[jQuery integration]

This procedure creates a basic Bootstrap integration containing a {{site.productname}} editor based on our link:{{site.baseurl}}/demo/basic-example/[Basic example].

[#procedure]
=== Procedure

. In a HTML file, add a source script for Bootstrap JS.
+
If the project loads Bootstrap from \https://www.bootstrapcdn.com/, use the script provided by the https://www.bootstrapcdn.com/[Bootstrap CDN], which includes the `integrity` and `crossorigin` attributes.

. Source {{site.productname}} from the {{site.cloudname}} or from a self-hosted location.
 ** *{{site.cloudname}}*
+
To source {{site.productname}} from the {{site.cloudname}}, add the following `script` element to the `<head>` of the document:
  `html
  <script src="{{site.cdnurl}}" referrerpolicy="origin"></script>
 `
  Replace `no-api-key` in the source script (`+<script src=...+`) with a {{site.cloudname}} API key, which is created when signing up to the link:{{site.accountsignup}}[{{site.cloudname}}].
+
Signing up for a {{site.cloudname}} API key will also provide a trial of the link:{{site.baseurl}}/enterprise/[Premium Plugins].

 ** *{{site.productname}} self-hosted*
+
To use an independent deployment of {{site.productname}}, add the following source script to either the `<head>` or the end of the `<body>` of the HTML file, such as:
  `html
  <script src="/path/to/tinymce.min.js"></script>
 `
+
For information on self-hosting {{site.productname}}, see: link:{{site.baseurl}}/general-configuration-guide/advanced-install/[Installing {{ site.productname }}].
. Add an initialization point for {{site.productname}}, such as:
+
```html+++<div>++++++<textarea id="tiny">++++++</textarea>++++++</div>+++
+
```

. Add the {{site.productname}} init script.
+
`html
 <script>
   tinymce.init({
     selector: 'textarea#tiny'
   });
 </script>
`

[#using-tinymce-in-a-bootstrap-dialog]
== Using TinyMCE in a Bootstrap dialog

To render {{site.productname}} instances inside Bootstrap UI dialogs, add the following code:

`js
// Prevent Bootstrap dialog from blocking focusin
$(document).on('focusin', function(e) {
  if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    e.stopImmediatePropagation();
  }
});
`

This code is required because Bootstrap blocks all `focusin` calls from elements outside the dialog. For a working example, http://fiddle.tinymce.com/gRgaab[try this {{site.productname}} fiddle].

[discrete#a-note-about-integrations]
==== A note about integrations

NOTE: We are pleased to provide integrations/code guidance to help you build great products with {{site.productname}}. If you have queries about this integration, please join the https://community.tiny.cloud/[{{site.productname}} Community].
