:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Basic setup
:title_nav: Basic setup
:description_short: The three most important configuration settings, with examples.
:description: TinyMCE provides a range of configuration options that allow you to integrate it into your application.
:keywords: selector plugin toolbar configuration configure

This introduction to {productname} details the options used in traditional form-based layouts, useful information for creating streamlined user experiences, and examples of using {productname} as an inline editor.

The four most common configuration options for {productname} are:

. link:#selectorconfiguration[_(Required)_ The Selector configuration]
. link:#pluginconfiguration[The Plugin configuration]
. link:#toolbarconfiguration[The Toolbar configuration]
. link:#menuandmenubarconfiguration[The Menu and Menu Bar configuration]

== A note about code snippet examples

Code snippets are provided as example implementations throughout the {productname} documentation.

Example code snippet:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugin: 'a_tinymce_plugin',
  a_plugin_option: true,
  a_configuration_option: 400
});
----

Snippets include the `+selector+` option, which is described below. Change the value of the working code block according to the HTML.

Insert the snippet into a HTML document between the `+<script>+` tags and update the selector as described below.

== Selector configuration

Selector configuration is required for {productname} integration. Selector configuration uses https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors[CSS `+selector+` syntax] to determine which elements on the page are editable through {productname}.

{productname} visually replaces the selected element with an `+iframe+` (the editable content area) and the UI elements (such as toolbar, menu bar, and status bar).

The following example replaces all `+textarea+` elements on the page with {productname} instances:

[source,js]
----
tinymce.init({
  selector: 'textarea'
});
----

{productname} can also match an `+id+` attribute.

The following example replaces a `+textarea+` element with the `+id+` `+"default"+` on the page:

[source,js]
----
tinymce.init({
  selector: 'textarea#default'
});
----

Providing a {productname} editor with the default configuration, such as:

codepen::default[]

The selector can target most block elements when the editor is used in link:../use-tinymce-inline/[inline editing mode]. Inline mode edits the content in place, instead of replacing the element with an `+iframe+`.

The following example uses the `+selector+` in inline editing mode on a `+div+` element with `+id+` `+'editable'+`:

[source,js]
----
tinymce.init({
  selector: 'div#editable',
  inline: true
});
----

For information on the differences between the classic and inline editing modes, see: link:../use-tinymce-inline/[Setup inline editing mode].

== Plugin configuration

The functionality of {productname} is extended by using plugins, which are enabled using the `+plugins+` option.

The following example enables the lists (`+lists+`), Advanced Lists (`+advlist+`), Link (`+link+`), and Image (`+image+`) plugins.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'advlist link image lists'
});
----

For a full list of plugins and their options, see: link:{rootDir}plugins.html[Add plugins to TinyMCE].

== Toolbar configuration

{productname} provides a default set of toolbar controls, which can be overridden using the `+toolbar+` option.

=== Default toolbar controls

The {productname} default toolbar contains the following buttons:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to the HTML
  toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | outdent indent'
});
----

Hello, World!

The `+toolbar+` option defines the presence, order, and grouping of toolbar buttons.

Use a space-separated list to specify the toolbar buttons for {productname}. Create toolbar groups by using the "`+|+`" pipe character between button names.

==== Additional information

* For additional toolbar options, including disabling the toolbar and adding multiple toolbars, see: link:{rootDir}configure/editor-appearance.html#toolbar[User interface options - toolbar].
* For a list of all available toolbar items, see: https://www.tiny.cloud/docs/advanced/editor-control-identifiers/#toolbarcontrols[Editor control identifiers - Toolbar controls].

== Menu and Menu bar configuration

There are two menu options: `+menubar+` and `+menu+`. `+menubar+` is used to define the presence and order of _menus_, such as *File*, *Edit*, and *View*. `+menu+` is used to define the presence and order of _menu items_, such as *New Document*, *Select all*, and *Source code*.

=== Menu and Menu bar configuration examples

To display the _File_, _Edit_, and _View_ menus:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  menubar: 'file edit view'
});
----

codepen::menubar[]

To create an `+Edit+` menu that only contains the _Undo_, _Redo_, and _Select all_ items.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  menu: {
    edit: {title: 'Edit', items: 'undo, redo, selectall'}
  }
});
----

codepen::menu1[]

To create a menu titled "Happy", provide an identifier for the menu and an object with the `+title+` and `+items+` for the menu.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  menu: {
    happy: {title: 'Happy', items: 'code'}
  },
  plugins: 'code',  // required by the code menu item
  menubar: 'happy'  // adds happy to the menu bar
});
----

codepen::menu2[]

=== Default menu controls

The default menus are as follows:

include::{partialsDir}configuration/defaultmenuitems.adoc[]

[NOTE]
====
Some menu items require a plugin, such as the `+table+` menu and items requires the `+table+` plugin.
====

==== Additional information

* For information on the `+menu+` setting, see: link:{rootDir}configure/editor-appearance.html#menu[User interface options - menu].
* For information on the `+menubar+` setting, see: link:{rootDir}configure/editor-appearance.html#menubar[User interface options - menubar].
* For a list of all available menu items, see: link:{rootDir}advanced/editor-control-identifiers.html#menucontrols[Editor control identifiers - Menu controls].

== Basic configuration example

The following example is a basic {productname} configuration.

[source,html,subs="+attributes"]
----
<!DOCTYPE html>
<html>
<head>
  <script
    type="text/javascript"
    src="{cdnurl}"
    referrerpolicy="origin">
  </script>
  <script type="text/javascript">
  tinymce.init({
    selector: '#myTextarea',
    width: 600,
    height: 300,
    plugins: [
      'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
      'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
      'table emoticons template paste help'
    ],
    toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
      'bullist numlist outdent indent | link image | print preview media fullpage | ' +
      'forecolor backcolor emoticons | help',
    menu: {
      favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | spellchecker | emoticons'}
    },
    menubar: 'favs file edit view insert format tools table help',
    content_css: 'css/content.css'
  });
  </script>
</head>

<body>
  <textarea id="myTextarea"></textarea>
</body>
</html>
----

=== Break-down of the basic configuration example

The following section is a break-down of the options used in the basic configuration example.

Selects the `+textarea+` with the id `+myTextarea+` to be replaced by the editor.

[source,js]
----
selector: '#myTextarea',
----

Sets the width and height of the editable area in pixels as numeric values.

[source,js]
----
width: 600,
height: 300,
----

Selects the plugins to be included on load.

[source,js]
----
plugins: [
  'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
  'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
  'table emoticons template paste help'
],
----

Selects the toolbar buttons displayed to the user. Use a comma or space as a separator.

[source,js]
----
toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons',
----

Adds an additional menu named "My Favorites" with `+menu+`, then adds it to the menu bar using `+menubar+`.

[source,js]
----
menu: {
  favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | spellchecker | emoticons'}
},
menubar: 'favs file edit view insert format tools table help',
----

Sets the styling of the editable area using `+content_css+`.

[source,js]
----
content_css: 'css/content.css',
----

codepen::basic-conf[]

=== Additional information

* For a full list of configuration options, see: the link:{rootDir}configure.html[Configuration options reference].
* For a full list of Plugins and their options, see: link:{rootDir}plugins.html[Add plugins to TinyMCE].
* For information on the UI elements, see: link:{rootDir}ui-components.html[User interface components].
