:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Get Support &amp; FAQ
:description: Community and pro-grade support options.
:keywords: forum forums url absolute relative security xss
:title_nav: Support &amp; FAQ

[[premium-support]]
== Premium support

Paid premium support is available as part of link:{pricingpage}[{enterpriseversion} and {cloudname} subscriptions]. {productname} Enterprise customers can link:{rootDir}enterprise/support.html[submit a case support request].

[[forums]]
== Forums

Open Source Community Edition users can get free access to the https://community.tiny.cloud/[{productname} Forum]. Sign up https://community.tiny.cloud/[here].

[[faq-troubleshooting]]
== FAQ & troubleshooting

[[q-the-icons-are-missing-when-installing-on-my-server]]
=== Q: The icons are missing when installing on my server?

Some web servers do not support the mime types needed for the font file extensions. Below are the mime types required - the first part is the mime type the second part is the file extension that needs to be mapped. It's in apache mime type format. Other servers might need a different format.

|===
| MIME type | File Extension

| image/svg+xml
| svg
|===

[[q-why-do-buttonsselect-boxes-have-the-incorrect-size]]
=== Q: Why do buttons/select boxes have the incorrect size?

You are probably using an old `DOCTYPE`. As of {productname} 4, a proper HTML5 doctype is required. All web developers should use a standard rendering mode on their web pages. Use a HTML5 doctype like `<!DOCTYPE html>` to properly render the page and the {productname} UI.

[[q-is-tinymce-protected-against-xss-vulnerabilities]]
=== Q: Is TinyMCE protected against XSS vulnerabilities?

The server should have protection against XSS attacks implemented. Since if you can submit contents in a form using {productname} one could as easily disable all JavaScript and therefore bypass {productname} filtering and still submit HTML code with insecure content. You need to properly filter the HTML input on the server using things like http://htmlpurifier.org/[HTML Purifier].

[[q-how-do-i-convert-my-urls-to-relative-absolute-or-absolute-with-the-domain]]
=== Q: How do I convert my URLs to relative, absolute, or absolute with the domain?

[[relative-urls]]
==== Relative URLs

The *Relative URLs* converts all URLs within the same domain to relative URLs. The URLs are relative from the `document_base_url`.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : true,
  document_base_url : 'http://www.site.com/path1/'
});
----

[[example]]
===== Example

`+http://www.site.com/path1/path2/file.htm >> path2/file.htm+`

[[absolute-urls]]
==== Absolute URLs

The *Absolute URLs* converts all relative URLs to absolute URLs. The URLs are `absolute` based on the `document_base_url`.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : false,
  remove_script_host : true,
  document_base_url : 'http://www.site.com/path1/'
});
----

[[example-2]]
===== Example

`path2/file.htm >> /path1/path2/file.htm`

[[domain-absolute-urls]]
==== Domain absolute URLs

The *Domain absolute URLs* converts all relative URLs to absolute URLs. The URLs are `absolute` based on the `document_base_url` with the domain.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : false,
  remove_script_host : false,
  document_base_url : 'http://www.site.com/path1/'
});
----

[[example-2]]
===== Example

`+path2/file.htm >> http://www.site.com/path1/path2/file.htm+`
