:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Check spelling in TinyMCE
:keywords: spell checker spelling browser_spellcheck gecko_spellcheck
:title_nav: Spell checking

{productname} provides several options to bring spell checking capabilities to your users.

[[browser-based-spell-checking]]
== Browser-based spell checking

Assign the link:{rootDir}configure/spelling.html#browser_spellcheck[`browser_spellcheck`] configuration option the value of `true` to utilize the browser's native spell check functionality. Enabling the link:{rootDir}configure/editor-appearance.html#contextmenu[`contextmenu`] option _may_ be required depending on the right-click or context usability requirement.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  browser_spellcheck: true,
  contextmenu: false
});
----

[[php-spellchecker-component]]
== PHP Spellchecker component

You can also use {productname}'s PHP _Spellchecker_ component, that you can http://download.moxiecode.com/spellcheckers/tinymce_spellchecker_php_4.0.zip[download here]. To view the complete changelog history, view this http://archive.tinymce.com/develop/changelog/?type=phpspell[`txt`] file. The {productname}'s PHP Spellchecker component requires a little more work than the browser-based option, being a server-side script.

This plugin enables *Enchant* or *PSpell* on the server to spell check content within the {productname} editor.

[discrete#installation-steps-for-the-default-enchant-engine]
===== Installation steps for the default Enchant engine

. Enable *Enchant* in PHP.
. Download the *{productname} Spellchecker* for PHP package. http://download.moxiecode.com/spellcheckers/tinymce_spellchecker_php_4.0.zip[(Direct download)].
. Unpack the package in the `/path/to/tinymce/plugins/spellchecker` directory.
. Configure {productname} to use the spell checker by enabling the `spellchecker` plugin.
. Configure the `spellchecker_rpc_url` to `'spellchecker.php'`.
. Download word lists and place them in the `/dicts` directory for example "es_ES.dic, es_ES.aff".

[discrete#example]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'spellchecker',
  toolbar: 'spellchecker',
  spellchecker_rpc_url: 'spellchecker.php'
});
----

Review the link:{rootDir}plugins/spellchecker.html[Spell Checker plugin] for advanced configuration options.

[[tinymce-spell-checker-pro-plugin]]
== TinyMCE Spell Checker Pro plugin

Use the link:{rootDir}plugins/tinymcespellchecker.html[Spell Checker Pro plugin] for scalable enterprise-grade spell check as-you-type functionality. *Spell Checker Pro* requires both a client-side plugin to be configured and a server-side component to be installed and configured.

Review the {productname} Premium Features link:{rootDir}enterprise/check-spelling.html[documentation for Spelling]. Learn more about link:{pricingpage}[{productname} Premium Products here].
