site:
  title: TinyMCE 5 Documentation (Staging)
  url: https://staging.tiny.cloud/docs
  start_page: tinymce::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: ./
urls:
  html_extension_style: indexify
ui:
  bundle:
    url: https://tiny-cloud-docs-antora-themes-staging.s3.amazonaws.com/ui-bundle.zip
asciidoc:
  attributes:
    tinymce_live_demo_url: https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/5/tinymce.min.js
  extensions:
    - '@tinymce/antora-extension-livedemos'
