[[tinymce-3-documentation]]
= TinyMCE 3 documentation
:pp: {plus}{plus}

This project maintains the documentation for TinyMCE 3 at
https://www.tiny.cloud/docs[\https://www.tiny.cloud/docs]. If you have any
modifications you wish to contribute, fork this project, make the changes
and submit a pull request. You will need to sign the contributors license
agreement, which will be emailed to you upon creating the pull request.

[[contributing-to-the-tinymce-3-documentation]]
== Contributing to the TinyMCE 3 Documentation

If you would like to contribute to the TinyMCE 3 project please read the TinyMCE 3 Documentation Contributor's Guide at either:

* https://www.tiny.cloud/docs/configure/contributing-docs/[TinyMCE 3 Documentation - Contributor's Guide].
* https://github.com/tinymce-3/tinymce-3-docs/blob/develop/CONTRIBUTING.md#contributing-to-the-tinymce-3-developer-documentation[GitHub - Contributing to the TinyMCE 3 developer documentation].

[[working-on-tinymce-3-documentation]]
== Working on TinyMCE 3 documentation

[[compiling-or-building-the-documentation]]
=== Compiling or building the documentation

The following procedure assists with building (or compiling) the documentation locally. Tiny recommends testing and reviewing changes locally prior to submitting a pull request.
