= 08. Check Spelling
:description: Take spell checking to your users.
:keywords: spell checker spelling browser_spellcheck gecko_spellcheck

Nobody likes content with spelling errors. Our team at TinyMCE is motivated to help your users create error-free content. Which is why we have several options to help you bring spell checking capabilities to your users.

== Browser-based spell checking

The first and easiest to implement option is to utilize the browser's native spell check functionality by assigning the link:{baseurl}/configure/spelling/#browser_spellcheck[`browser_spellcheck`] configuration option the value of `true`. Depending on the right click / context behavior you want, you _may_ need to enable the link:{baseurl}/plugins/contextmenu/[`contextmenu`] plugin.

`js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  browser_spellcheck: true,
  contextmenu: false
});
`

== PHP Spellchecker component

You can also use TinyMCE's PHP Spellchecker component, which you can http://download.moxiecode.com/spellcheckers/tinymce_spellchecker_php_4.0.zip[download here]. To view the complete changelog history, view this http://archive.tinymce.com/develop/changelog/?type=phpspell[txt] file. The TinyMCE's PHP Spellchecker component requires a little more work than the browser-based option, being a server-side script.

This plugin enables you to use *Enchant* or *PSpell* on the backend of your server to spell check contents within the TinyMCE editor.

[discrete]
===== Installation steps for the default Enchant engine

. Make sure you enable *Enchant* in your PHP.
. Download the *TinyMCE Spellchecker* for PHP package. http://download.moxiecode.com/spellcheckers/tinymce_spellchecker_php_4.0.zip[(Direct download)].
. Unpack the package in the your``/path/to/tinymce/plugins/spellchecker`` directory.
. Configure TinyMCE to use the spell checker by enabling the `spellchecker` plugin.
. Configure the `spellchecker_rpc_url` to `'spellchecker.php'`.
. Download word lists and place them in the `/dicts` directory for example "sv_SE.dic, sv_SE.aff".

[discrete]
===== Example

`js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'spellchecker',
  toolbar: 'spellchecker',
  spellchecker_rpc_url: 'spellchecker.php'
});
`

Please see the link:{baseurl}/plugins/spellchecker/[Spell Checker Plugin] for advanced configuration options.

== TinyMCE Spellchecker Pro plugin

For developers requiring a robust enterprise-grade spell check as-you-type functionality, you need the link:{baseurl}/plugins/tinymcespellchecker/[Spell Checker Pro plugin]. Spell Checker Pro requires both a client-side plugin to be configured and a server-side component to be installed and configured.

Full documentation can be found in the TinyMCE Enterprise link:{baseurl}/enterprise/check-spelling/[documentation for Spelling]. Learn more about https://www.tinymce.com/pricing/[TinyMCE Enterprise here].

{% assign_page next_page = "/general-configuration-guide/filter-content/index.html" %}
{% include next-step.html next=next_page %}
