[[deploy-the-tinymce-image-proxy-server-side-component-using-docker-self-hosted-enterprise-bundles]]
=== Deploy the TinyMCE image proxy server-side component using Docker (self-hosted enterprise bundles)

The TinyMCE image proxy server-side component can be deployed using Docker or a container orchestration application such as Kubernetes. {companyname} provides a pre-configured package for creating a Image Proxy Docker image.

WARNING: Do not push this docker image to a publicly accessible container registry. Doing so will constitute a breach of the https://about.tiny.cloud/legal/tiny-self-hosted-software-license-agreement-enterprise/[{companyname} Self-Hosted Software License Agreement].

[[procedure]]
==== Procedure

The following procedure covers downloading, configuring, building and testing the {productname} Image Proxy Docker image.

NOTE: This procedure assumes that a {productname} self-hosted enterprise bundle has been extracted as described in <<downloadandextractthetinymceself-hostedbundle,Download and extract the TinyMCE Self-hosted Bundle>>.

. Navigate into the `tinymce-services` folder.
+
[source,sh]
----
cd tinymce-selfhosted/tinymce-services/
----

. Extract the contents of `ephox-image-proxy-docker-starter-kit.zip`, such as:
+
[source,sh]
----
unzip ephox-image-proxy-docker-starter-kit.zip -d image-proxy-service-dockerfile
----

. Copy `ephox-image-proxy.war` into the directory containing the extracted files, such as:
+
[source,sh]
----
cp ephox-image-proxy.war image-proxy-service-dockerfile/
----

. Navigate into the `image-proxy-service-dockerfile` folder.
+
[source,sh]
----
cd image-proxy-service-dockerfile
----

. Set the permissions on the extracted files to executable.
+
[source,sh]
----
chmod +x *.sh
----

. _Optional_: Edit the `image-proxy` configuration setting in `config/ephox-image-proxy-docker-env.conf`. The configurable setting is in the `image-proxy` section of the file. For example:
+
[source]
----
 image-proxy {
   image-size = 10000000 // 10MB in bytes
}
----
+
For information on the `image-proxy` configuration setting, see: link:{rootDir}enterprise/server/configure/#image-proxyoptional[Configure server-side components - `image-proxy`].

. _Optional_: Edit the `http` configuration settings in `config/ephox-image-proxy-docker-env.conf`. The configurable settings are in the `http` section of the file. For example:
+
[source]
----
 http {
   max-connections = 100
   max-connections-per-host = 10
   max-redirects = 10
   max-retries = 3
   request-timeout-seconds = 10
   trust-all-cert = false
   websphere = {
     use-ssl-config = true
   }
}
----
+
For information on the `http` configuration setting, see: link:{rootDir}enterprise/server/configure.html#httpoptional[Configure server-side components - `http`].

. _Optional_: Configure the service to use a HTTP proxy by updating `config/ephox-image-proxy-docker-env.conf`. See:
link:{rootDir}enterprise/server/configure.html[Configure server-side components].
. Create an `origins.env` file in the same directory as the `Dockerfile`, and specify the Hypertext Transfer Protocol (HTTP) and domain name of sites hosting the TinyMCE editor (`allowed-origins`). Up to 99 origins can be added without editing `config/ephox-image-proxy-docker-env.conf`.
+
For example:
+
[source,conf]
----
ORIGIN0=example.net
ORIGIN1=example
ORIGIN2=http://example.org
----
+
For information on `allowed-origins`, see: link:{rootDir}enterprise/server/configure/#allowed-originsrequired[Configure server-side components - allowed-origins].

. As the root user or Administrator, build the {productname} Image Proxy Docker image using the following command:
+
[source,sh]
----
docker build -t tinymce-image-proxy-service .
----

. As the root user or Administrator, deploy the service using the following command:
+
[source,sh]
----
docker run -d -p 8081:8080 --env-file origins.env tinymce-image-proxy-service
----
+
Where:

 * `-p 8081:8080` maps the container port `8080` to local port `8081`.
 * `--env-file origins.env` adds the allowed origins to the container.

. To verify that the Docker container is deployed and the image proxy is running, execute:
+
[source,sh]
----
curl http://localhost:8081/ephox-image-proxy/
----
The response from the `curl` command should be:
+
[source]
----
Image proxy service is running.
----

The {productname} Image Proxy Docker image can now be pushed to a private container registry for deployment on https://kubernetes.io/[Kubernetes], https://docs.docker.com/engine/swarm/[Docker Swarm] or https://www.openshift.com/[OpenShift].
