:experimental:

ifeval::[{shbundledockerfiles} == false]
[[deploy-the-tinymce-spelling-service-server-side-component-using-docker-individually-licensed]]
=== Deploy the TinyMCE spelling service server-side component using Docker (individually licensed)
endif::[]

ifeval::[{shbundledockerfiles} == true]
[[deploy-the-tinymce-spelling-service-server-side-component-using-docker-self-hosted-enterprise-bundles]]
=== Deploy the TinyMCE spelling service server-side component using Docker (self-hosted enterprise bundles)
endif::[]

The TinyMCE spelling service server-side component can be deployed using Docker or a container orchestration application such as Kubernetes. {companyname} provides a pre-configured package for creating a Spelling Service Docker image.

WARNING: Do not push this docker image to a publicly accessible container registry. Doing so will constitute a breach of the https://about.tiny.cloud/legal/tiny-self-hosted-software-license-agreement-enterprise/[{companyname} Self-Hosted Software License Agreement].

ifeval::[{shbundledockerfiles} == false]

[[prerequisites]]
==== Prerequisites

* The https://docs.docker.com/engine/docker-overview/[Docker Engine] is installed and running.
* The user has Administrative or Root user access.
* The user is either:
 ** Using a Linux, Unix or macOS operating system.
 ** Using Windows and has access to unix command line tools using https://gitforwindows.org/[Git for Windows], https://www.cygwin.com/[Cygwin], or the https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux].

endif::[]

[[procedure]]
==== Procedure

The following procedure covers downloading, configuring, building and testing the {productname} Spelling Service Docker image.
ifeval::[{shbundledockerfiles} == true]

NOTE: This procedure assumes that a {productname} self-hosted enterprise bundle has been extracted as described in <<downloadandextractthetinymceself-hostedbundle,Download and extract the TinyMCE Self-hosted Bundle>>.

. Navigate into the `tinymce-services` folder.
+
[source,sh]
----
cd tinymce-selfhosted/tinymce-services/
----

. Extract the contents of `ephox-spelling-docker-starter-kit.zip`, such as:
+
[source,sh]
----
unzip ephox-spelling-docker-starter-kit.zip -d spelling-service-dockerfile
----
+
The structure of the extracted files will be:
+
[source,sh]
----
spelling-service-dockerfile/
├── config
│   └── ephox-spelling-docker-env.conf
├── docker-entrypoint.sh
├── Dockerfile
└── generate-jetty-start.sh
----

. Copy `ephox-spelling.war` into the directory containing the extracted files, such as:
+
[source,sh]
----
cp ephox-spelling.war spelling-service-dockerfile/
----

. Navigate into the `spelling-service-dockerfile` folder.
+
[source,sh]
----
cd spelling-service-dockerfile
----

endif::[]
ifeval::[{shbundledockerfiles} == false]

. Go to menu:link:{accountpageurl}[{accountpage}][My Downloads] and download _Tiny Spell Checker Pro_.
. Open a command line and navigate to the directory containing `ephox-spelling_<version>.zip`. Windows Users should open a Bash command line as the Administrator User.
. Extract the contents of `ephox-spelling_<version>.zip`, such as:
+
[source,sh]
----
unzip ephox-spelling_<version>.zip -d tinymce-spelling-service
----

. Navigate into the extracted folder.
+
[source,sh]
----
cd tinymce-spelling-service
----

. Extract the contents of `ephox-spelling-docker-starter-kit.zip`, such as:
+
[source,sh]
----
unzip ephox-spelling-docker-starter-kit.zip
----
+
The structure of the current directory (`tinymce-spelling-service/`) will be:
+
[source,sh]
----
tinymce-spelling-service/
├── config
│   └── ephox-spelling-docker-env.conf
├── docker-entrypoint.sh
├── Dockerfile
├── ephox-spelling-docker-starter-kit.zip
├── ephox-spelling.war
├── generate-jetty-start.sh
├── license.txt
├── readme.txt
└── version.txt
----
+
endif::[]

. Set the permissions on the extracted files to executable.
+
[source,sh]
----
chmod +x *.sh
----

. _Optional_: Edit the `http` configuration settings in `config/ephox-spelling-docker-env.conf`. The configurable settings are in the `http` section of the file. For example:
+
[source]
----
http {
  max-connections = 100
  max-connections-per-host = 10
  max-redirects = 10
  max-retries = 3
  request-timeout-seconds = 10
  trust-all-cert = false
  websphere = {
    use-ssl-config = true
  }
}
----
+
For information on the `http` configuration setting, see: link:{rootDir}enterprise/server/configure.html#httpoptional[Configure server-side components - `http`].

. _Optional_: Configure the service to use a HTTP proxy by updating `config/ephox-spelling-docker-env.conf`. See:
link:{rootDir}enterprise/server/configure.html[Configure server-side components].
. _Optional_: Add a custom dictionary, as described in link:{rootDir}enterprise/check-spelling/custom.html[Adding custom dictionaries].
. Create an `origins.env` file in the same directory as the `Dockerfile`, and specify the Hypertext Transfer Protocol (HTTP) and domain name of sites hosting the TinyMCE editor (`allowed-origins`). Up to 99 origins can be added without editing `config/ephox-spelling-docker-env.conf`.
+
For example:
+
[source,conf]
----
ORIGIN0=example.net
ORIGIN1=example
ORIGIN2=http://example.org
----
+
For information on `allowed-origins`, see: link:{rootDir}enterprise/server/configure/#allowed-originsrequired[Configure server-side components - allowed-origins].

. As the root user or Administrator, build the {productname} Spelling Service Docker image using the following command:
+
[source,sh]
----
docker build -t tinymce-spelling-service .
----

. As the root user or Administrator, deploy the service using the following command:
+
[source,sh]
----
docker run -d -p 8082:8080 --env-file origins.env tinymce-spelling-service
----
+
Where:

 ** `-p 8082:8080` maps the container port `8080` to local port `8082`.
 ** `--env-file origins.env` adds the allowed origins to the container.

. To verify that the Docker container is deployed and the spelling service is running, execute:
+
[source,sh]
----
curl http://localhost:8082/ephox-spelling/
----
+
The response from the `curl` command should be:
+
[source]
----
Spelling service is running.
----

The {productname} Spelling Service Docker image can now be pushed to a private container registry for deployment on https://kubernetes.io/[Kubernetes], https://docs.docker.com/engine/swarm/[Docker Swarm] or https://www.openshift.com/[OpenShift].
