[[creating-a-privatepublic-key-pair-for-tiny-drive]]
== Creating a private/public key pair for Tiny Drive

The procedure for creating a key pair depends on the operating system of the host machine.

* <<linux,Linux procedure>>.
* <<applemacos,Apple macOS procedure>>.
* <<microsoftwindows,Microsoft Windows procedure>>.

[[linux]]
=== Linux

To create a private/public key pair on a Linux operating system:

. <<installingopensslonlinux,Install OpenSSL>>.
. <<createaprivatepublickeypaironlinux,Create a private/public key pair>>.
. <<retrievethepublickeyonlinux,Retrieve the public key>>.

[[installing-openssl-on-linux]]
==== Installing OpenSSL on Linux

The procedure for installing OpenSSL on Linux distributions varies. The installation commands for common Linux distributions have been provided here.

[[red-hat-enterprise-linux-7-or-centos-7]]
===== Red Hat Enterprise Linux 7 or CentOS 7

On a command line, run the following commands to install OpenSSL on:

* Red Hat Enterprise Linux 6 or 7.
* CentOS 6 or 7.

[source,sh]
----
sudo yum check-update
sudo yum install openssl
----

[[red-hat-enterprise-linux-8-fedora-or-centos-8]]
===== Red Hat Enterprise Linux 8+, Fedora, or CentOS 8+

On a command line, run the following commands to install OpenSSL on:

* Red Hat Enterprise Linux 8 or later.
* CentOS 8 or later.
* Fedora 18 or later.

[source,sh]
----
sudo dnf check-update
sudo dnf install openssl
----

[[debian-ubuntu-linux-mint-or-other-debian-based-distributions]]
===== Debian, Ubuntu, Linux Mint, or other Debian-based distributions

On a command line, run the following commands to install OpenSSL on Debian-based operating systems (such as: Debian, Ubuntu, and Linux Mint).

[source,sh]
----
sudo apt update
sudo apt install openssl
----

[[suse-linux-enterprise-server-or-opensuse]]
===== SUSE Linux Enterprise Server or openSUSE

On a command line, run the following commands to install OpenSSL on openSUSE-based operating systems (such as: openSUSE and SUSE Linux Enterprise Server).

[source,sh]
----
sudo zypper refresh
sudo zypper install openssl
----

[[create-a-privatepublic-key-pair-on-linux]]
==== Create a private/public key pair on Linux

To create a private/public key pair:

. On a command line, run:
+
[source,sh]
----
ssh-keygen -m PEM -t rsa -b 2048 -f <MY_TINY_DRIVE_KEY>
----
+
Where `_<MY_TINY_DRIVE_KEY>_` should be replaced with a name for the key pair.

. Enter a passphrase for accessing the key.

Two files will be created in the current directory:

* `<MY_TINY_DRIVE_KEY>` - The private key.
* `<MY_TINY_DRIVE_KEY>.pub` - The public key.

[[retrieve-the-public-key-on-linux]]
==== Retrieve the public key on Linux

To retrieve the public key, on a command line, run:

[source,sh]
----
openssl rsa -in <MY_TINY_DRIVE_KEY> -outform DER -pubout | base64 -w0
----

The public key for the `<MY_TINY_DRIVE_KEY>` key pair will be printed on the command line with base64 encoding.

[[apple-macos]]
=== Apple macOS

To create a private/public key pair on a macOS operating system:

. <<createaprivatepublickeypaironmacos,Create a private/public key pair>>.
. <<retrievethepublickeyonmacos,Retrieve the public key>>.

[[create-a-privatepublic-key-pair-on-macos]]
==== Create a private/public key pair on macOS

To create a private/public key pair:

. Using *Finder*, open a *Terminal*.
. On a terminal, run:
+
[source,sh]
----
ssh-keygen -m PEM -t rsa -b 2048 -f <MY_TINY_DRIVE_KEY>
----
+
Where `_<MY_TINY_DRIVE_KEY>_` should be replaced with a name for the key pair.

. Enter a passphrase for accessing the key.

Two files will be created in the current directory:

* `<MY_TINY_DRIVE_KEY>` - The private key.
* `<MY_TINY_DRIVE_KEY>.pub` - The public key.

[[retrieve-the-public-key-on-macos]]
==== Retrieve the public key on macOS

To retrieve the public key, on a terminal, run:

[source,sh]
----
openssl rsa -in <MY_TINY_DRIVE_KEY> -outform DER -pubout | base64 -
----

The public key for the `<MY_TINY_DRIVE_KEY>` key pair will be printed on the terminal with base64 encoding.

[[microsoft-windows]]
=== Microsoft Windows

To create a private/public key pair on a Microsoft Windows operating system:

. <<installingopensslonmicrosoftwindows,Install OpenSSL>>.
. <<createaprivatepublickeypaironwindows,Create a private/public key pair>>.
. <<retrievethepublickeyonwindows,Retrieve the public key>>.

[[installing-openssl-on-microsoft-windows]]
==== Installing OpenSSL on Microsoft Windows

To install OpenSSL with _Git for Windows_:

. Download the _Windows_ package from https://git-scm.com/downloads[the Git Downloads page].
. Open the downloaded file `Git-<VERSION>-<ARCH>-bit.exe`, where _`<VERSION>`_ is the latest version of _Git for Windows_ and _`<ARCH>`_ is the architecture, such as _32-bit_ or _64-bit_.
. Click *Next* on the _Information_ and _Select Destination Location_ screens.
. Select *Check daily for Git for Windows updates* on the _Select Components_ screen, then click *Next*.
. Click *Next* on the remaining screens to accept the default settings.
. Once the installation is complete, click *Finish*.

[[create-a-privatepublic-key-pair-on-windows]]
==== Create a private/public key pair on Windows

To create a private/public key pair:

. Open the *Start* menu (or _Windows_ menu) and open *Git Bash*.
. On the _Git bash_ command line, run:
+
[source,sh]
----
ssh-keygen -m PEM -t rsa -b 2048 -f <MY_TINY_DRIVE_KEY>
----
+
Where `_<MY_TINY_DRIVE_KEY>_` should be replaced with a name for the key pair.

. Enter a passphrase for accessing the key.

Two files will be created in the current directory:

* `<MY_TINY_DRIVE_KEY>` - The private key.
* `<MY_TINY_DRIVE_KEY>.pub` - The public key.

[[retrieve-the-public-key-on-windows]]
==== Retrieve the public key on Windows

To retrieve the public key, on a _Git bash_ command line, run:

[source,sh]
----
openssl rsa -in <MY_TINY_DRIVE_KEY> -outform DER -pubout | base64 -w0
----

The public key for the `<MY_TINY_DRIVE_KEY>` key pair will be printed on the command line with base64 encoding.
