ifeval::[{customIconPack} != true]
[[icons_url]]
== icons_url

The *icons_url* option allows the editor icons to be extended or replaced using an icon pack. For information on creating icon packs, see: link:{rootDir}advanced/creating-an-icon-pack.html[Create an icon pack for {productname}].
endif::[]

On initialization, {productname} will try to load any icon pack specified by the *icons_url* option. The icons in the icon pack will be merged with link:{rootDir}advanced/editor-icon-identifiers.html[{productname}'s default icons] and icons in the icon pack will overwrite the default icons with the same identifier.

`icons_url` is used to specify the location of an icon pack when {productname} and the icon pack are loaded from different locations. For example: When loading {productname} from {cloudname}, the icon pack can be loaded from a different web server.

ifeval::[{customIconPack} == true]
Such as:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  icons_url: 'https://www.example.com/icons/my_icon_pack/icons.js', // load icon pack
  icons: 'my_icon_pack'      // use icon pack
});
----
endif::[]

ifeval::[{customIconPack} != true]
*Type:*  `String`

[[example]]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  icons_url: 'https://www.example.com/icons/material/icons.js', // load icon pack
  icons: 'material'      // use icon pack
});
----
endif::[]
