[[images_dataimg_filter]]
== images_dataimg_filter

IMPORTANT: This option was deprecated with the release of {productname} 5.3. `images_dataimg_filter` may be removed in a future release of {productname}.

The *images_dataimg_filter* option is used to filter `<img>` elements before they are passed to link:{rootDir}configure/file-image-upload.html#images_upload_handler[`image_upload_handler`] or link:{rootDir}configure/file-image-upload.html#images_upload_url[`images_upload_url`]. If the callback function provided returns `false` for an image, the image will not be uploaded.

*Type:* `JavaScript Function`

[discrete#example]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  images_upload_url: 'postAcceptor.php',
  images_dataimg_filter: function(img) {
    return !img.hasAttribute('internal-blob');  // blocks the upload of <img> elements with the attribute "internal-blob".
  }
});
----

NOTE: The `images_dataimg_filter` option can also be used to specify a filter predicate function for disabling the logic that converts base64 images into blobs while within the editor. {companyname} discourages using `images_dataimg_filter` for this purpose.
