[[images_reuse_filename]]
== images_reuse_filename

By default {productname} will generate unique filename for each uploaded file (for details refer to link:{rootDir}general-configuration-guide/upload-images.html#imageuploaderrequirements[Upload Images]). Sometimes this might have undesirable side-effects. For example, ,when `automatic_uploads` is enabled, every manipulation on the image done with link:{rootDir}plugins/imagetools[Image Tools] plugin, results in file upload and each time under a different filename, despite the fact that the image stays the same.

Setting `images_reuse_filename` to _true_ tells {productname} to use the actual filename of the image, instead of generating a new one each time. Take into account that `src` attribute of the corresponding `<img>` tag gets replaced with whatever filename you send back from the server (see <<images_upload_url,images_upload_url>>). It can be the same filename or something else, but the next time that filename is used for the upload.

*Type:* `Boolean`

*Default Value:* `false`

*Possible Values:* `true`, `false`

[discrete#example]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  automatic_uploads: true,
  images_upload_url: 'postAcceptor.php',
  images_reuse_filename: true
});
----
