[[quickbars_insert_toolbar]]
=== quickbars_insert_toolbar

The *quickbars_insert_toolbar* option configures the Quick Insert toolbar provided by the link:{rootDir}plugins/quickbars[quickbars plugin]. To change the buttons on the Quick Insert toolbar, provide a space-separated string of link:{rootDir}advanced/editor-control-identifiers.html#toolbarcontrols[toolbar button names]. The Quick Insert toolbar is intended for buttons related to inserting content, but any link:{rootDir}advanced/editor-control-identifiers.html#toolbarcontrols[{productname} toolbar buttons] or link:{rootDir}ui-components/toolbarbuttons[custom toolbar buttons] are allowed.

To disable the Quick Insert toolbar, set `quickbars_insert_toolbar` to `false`.

*Type:* `String`

*Defaults:* `quickimage quicktable`

[[example-customizing-the-quick-insert-toolbar]]
==== Example: Customizing the Quick Insert toolbar

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars hr pagebreak',
  inline: true,
  quickbars_insert_toolbar: 'quickimage quicktable | hr pagebreak'
});
----

[[example-disabling-the-quick-insert-toolbar]]
==== Example: Disabling the Quick Insert toolbar

To disable the Quick Insert toolbar, set `quickbars_insert_toolbar` to `false`.

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars',
  inline: true,
  quickbars_insert_toolbar: false
});
----
