[[selector]]
== selector

This option allows you to specify a CSS selector for the areas that {productname} should make editable.

When using this option in {productname}'s regular editing mode, the element will be replaced with an `iframe` that {productname} will perform all operations within.

[[replace-all-textarea-elements-on-the-page]]
=== Replace all textarea elements on the page

*Type:* `String`

[discrete#example]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea'  // change this value according to your HTML
});
----

[[replace-a-textarea-element-with-id-editable]]
=== Replace a textarea element with id 'editable'

*Type:* `String`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
    selector: 'textarea#editable'
});
----

When using this option in {productname}'s inline editing mode, the selector can be used on any block element and will edit the content in place instead of replacing the element with an `iframe`.

[[inline-editing-mode-on-a-div-element-with-id-editable]]
=== Inline editing mode on a div element with id 'editable'

*Type:* `String`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
    selector: 'div#editable',
    inline: true
});
----

For more information on the differences between regular and inline editing modes please see this page link:{rootDir}general-configuration-guide/use-tinymce-inline.html[here].
