[[toolbar]]
== toolbar

This option allows you to specify the link:{rootDir}advanced/editor-control-identifiers.html#toolbarcontrols[buttons] and the order that they will appear on {productname}'s toolbar.

[[grouping-toolbar-controls]]
=== Grouping toolbar controls

To specify the controls that should appear on {productname}'s toolbar, the `toolbar` option should be provided with a space separated list of link:{rootDir}advanced/editor-control-identifiers.html#toolbarcontrols[toolbar controls]. To create groups within this list, please add `|` pipe characters between the groups of controls that you would like to create.

*Type:* `String`

[discrete#example-grouped-toolbar]
===== Example grouped toolbar

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'undo redo | styleselect | bold italic | link image'
});
----

[[adding-toolbar-group-labels]]
=== Adding toolbar group labels

To specify labels to the grouped controls that appear on {productname}'s toolbar, the `toolbar` option should be provided with an array of objects with `name` and `items` as object properties. The `name` should be a string value that will be set as the `title` attribute on the `div` containing the toolbar group. The `items` should be an array of strings that indicate the controls that should appear within the particular toolbar group.

*Type:* `Array`

[discrete#example]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: [
    {
      name: 'history', items: [ 'undo', 'redo' ]
    },
    {
      name: 'styles', items: [ 'styleselect' ]
    },
    {
      name: 'formatting', items: [ 'bold', 'italic']
    },
    {
      name: 'alignment', items: [ 'alignleft', 'aligncenter', 'alignright', 'alignjustify' ]
    },
    {
      name: 'indentation', items: [ 'outdent', 'indent' ]
    }
  ];
});
----

[[disabling-the-toolbar]]
=== Disabling the toolbar

To disable the toolbar, the toolbar option should be provided a boolean value of `false`.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:* `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
    toolbar: false
});
----

[[using-multiple-toolbars]]
=== Using multiple toolbars

To specify multiple toolbars, the toolbar option should be provided with an array of space separated strings.

*Type:* `Array`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: [
    'undo redo | styleselect | bold italic | link image',
    'alignleft aligncenter alignright'
  ]
});
----

Alternatively, you may specify multiple toolbars through the use of the <<toolbarn,toolbar(n)>> option.
