:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= jQuery integration
:description: Documentation for the official TinyMCE jQuery integration.
:keywords: integration integrate jquery javascript
:title_nav: jQuery

[[tinymce-jquery-integration-quick-start-guide]]
== TinyMCE jQuery integration quick start guide

The https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/js/JqueryIntegration.js[Official {productname} jQuery component] integrates TinyMCE into jQuery projects.
This procedure creates a basic jQuery integration containing a {productname} editor based on our link:{rootDir}demo/basic-example.html[Basic example].

[[procedure]]
=== Procedure

. In a HTML file, add a source script for source jQuery.
+
If the project loads jQuery from \https://code.jquery.com/, use the script provided by the https://code.jquery.com/[jQuery CDN], which includes the `integrity` and `crossorigin` attributes.

. Source {productname} and the {productname} jQuery integration from the {cloudname} or from a self-hosted location.
 ** *{cloudname}*
+
To source {productname} and the {productname} jQuery integration from the {cloudname}, add the following `script` elements:
+
[source,html,subs="+attributes"]
----
<script src="{cdnurl}" referrerpolicy="origin"></script>
<script src="{basecdnurl}jquery.tinymce.min.js" referrerpolicy="origin"></script>
----
+
Replace `no-api-key` in the source script (`+<script src=...+`) with a {cloudname} API key, which is created when signing up to the link:{accountsignup}[{cloudname}].
+
Signing up for a {cloudname} API key will also provide a trial of the link:{rootDir}enterprise.html[Premium Plugins].

 ** *{productname} self-hosted*
+
To use an independent deployment of {productname}, add source scripts to either the `<head>` or the end of the `<body>` of the HTML file, such as:
+
[source,html]
----
<script src="/path/to/tinymce.min.js"></script>
<script src="/path/to/jquery.tinymce.min.js"></script>
----
+
For information on self-hosting {productname}, see: link:{rootDir}general-configuration-guide/advanced-install.html[Installing {productname}].
. Add an initialization point for {productname}, such as:
+
[source,html]
----
 <div>
   <textarea id="tiny"></textarea>
 </div>
----

. Add the {productname} jQuery init script. The {productname} selector is defined in the jQuery prefix, and any other settings are defined within the `tinymce` object.
+
[source,html]
----
<script>
   $('textarea#tiny').tinymce({    });
 </script>
----

[[example-jquery-integration]]
=== Example jQuery integration

To load a TinyMCE editor similar to the link:{rootDir}demo/basic-example.html[Basic example], add the following code to an empty HTML file.

[source,html,subs="+attributes"]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{cdnurl}" referrerpolicy="origin"></script>
    <script src="{basecdnurl}jquery.tinymce.min.js" referrerpolicy="origin"></script>
  </head>
  <body>
    <div>
      <textarea id="tiny"></textarea>
    </div>
    <script>
      $('textarea#tiny').tinymce({
        height: 500,
        menubar: false,
        plugins: [
          'advlist autolink lists link image charmap print preview anchor',
          'searchreplace visualblocks code fullscreen',
          'insertdatetime media table paste code help wordcount'
        ],
        toolbar: 'undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help'
      });
    </script>
  </body>
</html>
----

[[tinymce-in-a-jquery-ui-dialog]]
== TinyMCE in a jQuery UI Dialog

To render {productname} instances inside jQuery UI dialogs, add the following code:

[source,js]
----
// Prevent jQuery UI dialog from blocking focusin
$(document).on('focusin', function(e) {
  if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    e.stopImmediatePropagation();
  }
});
----

This code is required because jQuery blocks all `focusin` calls from elements outside the dialog. For a working example, http://fiddle.tinymce.com/rsdaab/840[try this {productname} fiddle].

[discrete#a-note-about-integrations]
==== A note about integrations

NOTE: We are pleased to provide integrations/code guidance to help you build great products with {productname}. If you have queries about this integration, please join the https://community.tiny.cloud/[{productname} Community].
