:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Rails integration
:description: Seamlessly integrates TinyMCE into the Rails asset pipeline.
:keywords: integration integrate rails
:title_nav: Rails

{productname} can be added to a Ruby on Rails project using either:

* <<tinymce-in-ruby-on-rails-using-the-tiny-cloud,TinyMCE in Ruby on Rails using the Tiny Cloud>>
* <<tinymce-in-ruby-on-rails-using-tinymce-self-hosted,TinyMCE in Ruby on Rails using TinyMCE self-hosted>>
* <<the-third-party-tinymce-ruby-on-rails-gem,The third-party TinyMCE Ruby on Rails gem>>

[[tinymce-in-ruby-on-rails-using-the-tiny-cloud]]
=== TinyMCE in Ruby on Rails using the Tiny Cloud

The {cloudname} can be used to integrate {productname} into Ruby on Rails projects.
This procedure creates a https://guides.rubyonrails.org/getting_started.html[basic Ruby on Rails application] containing a {productname} editor based on our link:{rootDir}demo/basic-example.html[Basic example].

include::{partialsDir}integrations/rails-basic-proj.adoc[]

. Add the following lines within the `<head>` element of `app/views/layouts/application.html.erb` to automatically include {productname} on pages using the `application` layout:
+
[source,html,subs="+attributes"]
----
 <script src="{cdnurl}" referrerpolicy="origin"></script>
 <script>
   tinymce.init({
     selector: '.tinymce',
     height: 500,
     menubar: false,
     plugins: [
       'advlist autolink lists link image charmap print preview anchor',
       'searchreplace visualblocks code fullscreen',
       'insertdatetime media table paste code help wordcount'
     ],
       toolbar: 'undo redo | formatselect | ' +
       ' bold italic backcolor | alignleft aligncenter ' +
       ' alignright alignjustify | bullist numlist outdent indent | ' +
       ' removeformat | help'
   });
</script>
----

. Create a `<textarea>` with the initial content `Hello, World!` for {productname} by adding the following lines to `app/views/welcome/index.html.erb`:
+
[source,html]
----
<%= text_area_tag :content, "Hello, World!", :class => "tinymce" %>
----

. On a command line, from the project's root directory, start the Ruby on Rails server.
+
[source,sh]
----
 rails server
----

The page containing the {productname} will be accessible at `+http://localhost:<port>/+` (default: http://localhost:3000/[http://localhost:3000/]).

[[tinymce-in-ruby-on-rails-using-tinymce-self-hosted]]
=== TinyMCE in Ruby on Rails using TinyMCE self-hosted

Self-hosted instances of {productname} can be integrated into Ruby on Rails projects.
This procedure creates a https://guides.rubyonrails.org/getting_started.html[basic Ruby on Rails application] containing a {productname} editor based on our link:{rootDir}demo/basic-example.html[Basic example].

include::{partialsDir}integrations/rails-basic-proj.adoc[]

. Add the following lines within the `<head>` element of `app/views/layouts/application.html.erb` to automatically include {productname} on pages using the `application` layout:
+
[source,html]
----
 <script src="/path/to/tinymce.min.js"></script>
 <script>
   tinymce.init({
     selector: '.tinymce',
     height: 500,
     menubar: false,
     plugins: [
       'advlist autolink lists link image charmap print preview anchor',
       'searchreplace visualblocks code fullscreen',
       'insertdatetime media table paste code help wordcount'
     ],
       toolbar: 'undo redo | formatselect | ' +
       'bold italic backcolor | alignleft aligncenter ' +
       'alignright alignjustify | bullist numlist outdent indent | ' +
       ' removeformat | help'
   });
</script>
----

. Create a `<textarea>` with the initial content `Hello, World!` for {productname} by adding the following lines to `app/views/welcome/index.html.erb`:
+
[source,html]
----
<%= text_area_tag :content, "Hello, World!", :class => "tinymce" %>
----

. On a command line, from the project's root directory, start the Ruby on Rails server.
+
[source,sh]
----
 rails server
----

The page containing the {productname} will be accessible at `+http://localhost:<port>/+` (default: http://localhost:3000/[http://localhost:3000/]).

For information on self-hosting {productname}, see: link:{rootDir}general-configuration-guide/advanced-install.html[Installing {productname}].

[[the-third-party-tinymce-ruby-on-rails-gem]]
=== The third-party TinyMCE Ruby on Rails gem

{thirdPartyInteg}

Sam Pohlenz maintains the https://github.com/spohlenz/tinymce-rails[{productname} Ruby on Rails gem] for integrating {productname} into the Ruby on Rails asset pipeline.
This procedure creates a https://guides.rubyonrails.org/getting_started.html[basic Ruby on Rails application] containing a {productname} editor based on our link:{rootDir}demo/basic-example.html[Basic example].

include::{partialsDir}integrations/rails-basic-proj.adoc[]

. Using a text editor, open the project `Gemfile` and add the line:
+
[source,sh]
----
gem 'tinymce-rails'
----
 Do not add this line within a `group` - `end` element.

. Install the `tinymce-rails` gem using `bundle`:
+
[source,sh]
----
bundle install
----

. Create a {productname} configuration file.
 .. Create the `config/tinymce.yml` file:
+
[source,sh]
----
touch config/tinymce.yml
----

 .. Add a {productname} configuration. The configuration must be in the https://yaml.org/spec/1.2/spec.html[YAML format], such as:
+
[source,yml]
----
height: 500
menubar: false
toolbar:
  - undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help
plugins:
  - advlist autolink lists link image charmap print preview anchor
  - searchreplace visualblocks code fullscreen
- insertdatetime media table paste code help wordcount
----
. Add the following lines within the `<head>` element of `app/views/layouts/application.html.erb` to automatically include {productname} on pages using the `application` layout:
+
[source,html]
----
 <%= tinymce_assets %>
<script type="text/javascript" src="/assets/tinymce.js"></script>
----

. Create a `<textarea>` with the initial content `Hello, World!` for {productname} by adding the following lines to `app/views/welcome/index.html.erb`:
+
[source,html]
----
 <%= text_area_tag :content, "Hello, World!", :class => "tinymce" %>
 <%= tinymce %>
----

. On a command line, from the project's root directory, start the Ruby on Rails server.
+
[source,sh]
----
 rails server
----

The page containing the {productname} will be accessible at `+http://localhost:<port>/+` (default: http://localhost:3000/[http://localhost:3000/]).

For information on creating advanced configurations for the third-party TinyMCE Ruby on Rails integration, visit the project on GitHub: https://github.com/spohlenz/tinymce-rails[Rails Integration for TinyMCE].
