:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= WordPress integration
:keywords: integration integrate wordpress advanced
:title_nav: WordPress

[[default-visual-editor-in-wordpress]]
== Default Visual Editor in Wordpress

To use {productname} in WordPress, TinyMCE Advanced is a great option.

[[powerpaste-for-wordpress]]
== PowerPaste for WordPress

link:{productpages}/powerpaste/[{productname} PowerPaste for WordPress] is a premium plugin from the makers of {productname} that brings the PowerPaste features to WordPress. It automatically fixes Word formatting, creates tables from Excel, and links & embed images with content pasted from the web.

[[tinymce-advanced]]
== TinyMCE Advanced

https://wordpress.org/plugins/tinymce-advanced/[TinyMCE Advanced] is a WordPress plugin built by https://profiles.wordpress.org/azaozz/[Andrew Ozz] that will let you add, remove, and arrange the buttons that are shown on the Visual Editor toolbar. It includes 15 plugins for {productname} that are automatically enabled or disabled depending on what buttons are chosen.

*Some of the features added by this plugin*

* Support for creating and editing tables
* More options when inserting lists
* Search and Replace in the editor
* Ability to set Font Family and Font Size

With this plugin, you will also be able to enable the {productname} menu. It is a convenient way to access a lot of features that are not used frequently.

[discrete#a-note-about-integrations]
==== A note about integrations

NOTE:  We are pleased to reference third-party integrations/code to help you build great products with {productname}. If you have queries about this integration, please contact the developer directly.
