= Bundling an npm version of TinyMCE with ES6 and Webpack
:description: Bundling an npm version of TinyMCE in a project using ES6 and Webpack
:description_short: Bundling an npm version of TinyMCE in a project using ES6 and Webpack
:keywords: webpack es6 es2015 npm modules tinymce
:title_nav: ES6 and npm

{% assign installtype = "an npm" %}
{% assign bundler = "https://webpack.js.org/[Webpack]" %}
{% assign syntax = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules[ES6+ syntax]" %}
{% include module-loading/bundling-procedure-intro.md %}

== Requirements

This guide requires the following:

* Node.js and npm
* Basic knowledge of how to use https://webpack.js.org/[Webpack]
* (Optional: For premium features) The latest premium `.zip` bundle of TinyMCE for including premium plugins

== Procedure

{% assign is_zip_install = false %}
{% include module-loading/webpack-dev-dependencies.md %}

{% include module-loading/bundling-webpack-es6-npm_editor.md %}

{% include module-loading/bundling-webpack-es6-npm_webpack.config.md %}

{% include module-loading/bundling-webpack-es6_index.md %}

. Run Webpack to test the bundle, such as:
+
`sh
 webpack --config webpack.config.js
`
+
If Webpack runs successfully, check that the editor loads in the application.
 If Webpack fails, review any errors and review the configuration changes in this procedure; you may need to adjust for conflicts or other issues when bundling {{site.productname}} into an existing project.

{% assign is_zip_install = nil %}

{% include module-loading/bundling-next-steps.md %}
