:rootDir: ../
:partialsDir: {rootDir}partials/
:imagesDir: {rootDir}images/
include::{rootDir}_attributes.adoc[]
= Contribute to TinyMCE
:description: Contribute to the open source project. Help build the core, plugins or even write the documentation.
:description_short: Contribute to the open source project.
:keywords: opensource oss contributors lgpl
:title_nav: Contribute to TinyMCE

TinyMCE is an open source software project, and we encourage developers to contribute patches and code for us to include in the main package of TinyMCE. However, there are a few rules and limitations when doing so, and this page lists them.

== Basic rules

* Contributed code will be licensed under the LGPL license, but not limited to LGPL.
* Copyright notices will be changed to Tiny Technologies but contributors will get credit for their work.
* All third party code will be reviewed, tested and possibly modified before being released.
* For contributions to be accepted, a Contributors License Agreement must be completed.

These basic rules make it possible for us to properly manage the TinyMCE project and to ensure that the code remains open source and under the LGPL license.

== How to contribute

The TinyMCE source code is https://github.com/tinymce/tinymce[hosted on Github]. Through Github, you can submit _pull requests_ and log new bugs and feature requests.

== Contributing to the documentation

If you would like to contribute to TinyMCE's documentation, please see our link:../contributing-docs/[contrib page and style guide].
