= tinymce.util.JSONRequest

This class enables you to use JSON-RPC to call backend methods.

[[examples]]
== Examples

[source,js]
----
var json = new tinymce.util.JSONRequest({
    url: 'somebackend.php'
});

// Send RPC call 1
json.send({
    method: 'someMethod1',
    params: ['a', 'b'],
    success: function(result) {
        console.dir(result);
    }
});

// Send RPC call 2
json.send({
    method: 'someMethod2',
    params: ['a', 'b'],
    success: function(result) {
        console.dir(result);
    }
});
----

[[methods]]
== Methods

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#send[send()] |Sends a JSON-RPC call. Consult the Wiki API documentation for more details on what you can pass to this function. |link:{baseurl}/api/tinymce.util/tinymce.util.jsonrequest.html[tinymce.util.JSONRequest]
|link:#sendrpc[sendRPC()] |Simple helper function to send a JSON-RPC request without the need to initialize an object. Consult the Wiki API documentation for more details on what you can pass to this function. |link:{baseurl}/api/tinymce.util/tinymce.util.jsonrequest.html[tinymce.util.JSONRequest]
|===

== Methods

[[send]]
=== send

send(args:Object)

Sends a JSON-RPC call. Consult the Wiki API documentation for more details on what you can pass to this function.

[[parameters]]
==== Parameters

* `+args+` `+(Object)+` - Call object where there are three field id, method and params this object should also contain callbacks etc.

[[sendrpc]]
=== sendRPC

sendRPC(o:Object)

Simple helper function to send a JSON-RPC request without the need to initialize an object. Consult the Wiki API documentation for more details on what you can pass to this function.

==== Parameters

* `+o+` `+(Object)+` - Call object where there are three field id, method and params this object should also contain callbacks etc.
