[[nightly-releases]]
== Nightly Releases

This article describes the purpose and usage of nightly releases of {pluginname} On-Premises images.

Nightly images are released every day. During the automatic release, we run our tests to make sure that these images are working correctly, but unlike stable releases, nightly builds do not go through our full release process and are not tested and approved by our Quality Assurance.

Nightly images include all of the changes that are merged on our development branches. This allows you to access new features or receive fixes faster than with stable on-premises images.

> Nightly builds are intended only for advanced usage where your use case requires having the new changes as soon as possible. We highly recommend using stable versions of our images.
+
**Before you use nightly images please get familiar with the “Dangers of using nightly builds” section.**

=== Dangers of using nightly builds

Nightly builds are released automatically. By the nature of these images, they should be treated as unstable. Running an On-Premises application using these images may result in some unexpected behaviors, undocumented features or known and unknown defects.

You need to ensure that the versions that you are willing to run are working correctly and will not impact your application negatively. We highly recommend using DEV/UAT environments first and going through the process of quality acceptance on your side, before you use nightly images in production.

By using the nightly builds you accept the risks mentioned in the documentation.

=== Nightly images usage

There is a difference between the usage of nightly and stable releases of {pluginname} On-Premises. Instead of the pdf-converter or `pdf-converter-windows` images, you should use the `pdf-converter-nightly` or `pdf-converter-windows-nightly` images.

[NOTE]
Notice that the version of nightly images also includes a date and a hash. This date part can help you find the latest version of the nightly build. Example usage:

[source, yaml, subs="attributes+"]
----
version: "2.2"
services:
  pdf-converter-nightly:
    image: {exportpdf_nightly_nightly} # change the version
    ports:
      - "8080:8080"
      # environment variables and other configuration
----

Nightly builds are available only as docker images.

=== List of available nightly versions

This list shows available versions for `pdf-converter-nightly` images, but the same versions are also available for `pdf-conveter-windows-nightly` images.

////
Example of images placeholder
////

=== Fetching the latest nightly version

If you want to automate the process of updating your application and automatically use the latest versions of nightly builds you can make a GET request at {exportpdf_nightly_nightly}. This will fetch the JSON with all available versions. Use the date in the version to find the latest image that can be used in your application.