The procedure for creating a key pair depends on the operating system of the host machine.

* xref:linux[Linux procedure].
* xref:applemacos[Apple macOS procedure].
* xref:microsoftwindows[Microsoft Windows procedure].

[[linux]]
== Linux

To create a private/public key pair on a Linux operating system:

. xref:installingopensslonlinux[Install OpenSSL].
. xref:createaprivatepublickeypaironlinux[Create a private/public key pair].
. xref:retrievethepublickeyonlinux[Retrieve the public key].

[[installingopensslonlinux]]
=== Installing OpenSSL on Linux

The procedure for installing OpenSSL on Linux distributions varies. The installation commands for common Linux distributions have been provided here.

==== Red Hat Enterprise Linux 7 or CentOS 7

On a command line, run the following commands to install OpenSSL on:

* Red Hat Enterprise Linux 6 or 7.
* CentOS 6 or 7.

[source,sh]
----
sudo yum check-update
sudo yum install openssl
----

==== Red Hat Enterprise Linux 8+, Fedora, or CentOS 8+

On a command line, run the following commands to install OpenSSL on:

* Red Hat Enterprise Linux 8 or later.
* CentOS 8 or later.
* Fedora 18 or later.

[source,sh]
----
sudo dnf check-update
sudo dnf install openssl
----

==== Debian, Ubuntu, Linux Mint, or other Debian-based distributions

On a command line, run the following commands to install OpenSSL on Debian-based operating systems (such as: Debian, Ubuntu, and Linux Mint).

[source,sh]
----
sudo apt update
sudo apt install openssl
----

==== SUSE Linux Enterprise Server or openSUSE

On a command line, run the following commands to install OpenSSL on openSUSE-based operating systems (such as: openSUSE and SUSE Linux Enterprise Server).

[source,sh]
----
sudo zypper refresh
sudo zypper install openssl
----

[[createaprivatepublickeypaironlinux]]
=== Create a private/public key pair on Linux

To create a private/public key pair:

. On a command line, run:
+
[source,sh]
----
ssh-keygen -m PEM -t rsa -b 2048 -f <MY_KEY_PAIR_NAME>
----
+
Where _`+<MY_KEY_PAIR_NAME>+`_ should be replaced with a name for the key pair.

include::partial$auth/passphrase-step-jwt.adoc[]

Two files will be created in the current directory:

* `+<MY_KEY_PAIR_NAME>+` - The private key.
* `+<MY_KEY_PAIR_NAME>.pub+` - The public key.

[[retrievethepublickeyonlinux]]
=== Retrieve the public key on Linux

To retrieve the public key, on a command line, run:

[source,sh]
----
openssl rsa -in <MY_KEY_PAIR_NAME> -outform DER -pubout | base64 -w0
----

The public key for the `+<MY_KEY_PAIR_NAME>+` key pair will be printed on the command line with base64 encoding.

[[applemacos]]
== Apple macOS

To create a private/public key pair on a macOS operating system:

. xref:createaprivatepublickeypaironmacos[Create a private/public key pair].
. xref:retrievethepublickeyonmacos[Retrieve the public key].

[[createaprivatepublickeypaironmacos]]
=== Create a private/public key pair on macOS

To create a private/public key pair:

. Using *Finder*, open a *Terminal*.
. On a terminal, run:
+
[source,sh]
----
ssh-keygen -m PEM -t rsa -b 2048 -f <MY_KEY_PAIR_NAME>
----
+
Where _`+<MY_KEY_PAIR_NAME>+`_ should be replaced with a name for the key pair.

include::partial$auth/passphrase-step-jwt.adoc[]

Two files will be created in the current directory:

* `+<MY_KEY_PAIR_NAME>+` - The private key.
* `+<MY_KEY_PAIR_NAME>.pub+` - The public key.

[[retrievethepublickeyonmacos]]
=== Retrieve the public key on macOS

To retrieve the public key, on a terminal, run:

[source,sh]
----
openssl rsa -in <MY_KEY_PAIR_NAME> -outform DER -pubout | base64 -
----

The public key for the `+<MY_KEY_PAIR_NAME>+` key pair will be printed on the terminal with base64 encoding.

[[microsoftwindows]]
== Microsoft Windows

To create a private/public key pair on a Microsoft Windows operating system:

. xref:installingopensslonmicrosoftwindows[Install OpenSSL].
. xref:createaprivatepublickeypaironwindows[Create a private/public key pair].
. xref:retrievethepublickeyonwindows[Retrieve the public key].

[[installingopensslonmicrosoftwindows]]
=== Installing OpenSSL on Microsoft Windows

To install OpenSSL with _Git for Windows_:

. Download the _Windows_ package from https://git-scm.com/downloads[the Git Downloads page].
. Open the downloaded file `+Git-<VERSION>-<ARCH>-bit.exe+`, where _`+<VERSION>+`_ is the latest version of _Git for Windows_ and _`+<ARCH>+`_ is the architecture, such as _32-bit_ or _64-bit_.
. Click *Next* on the _Information_ and _Select Destination Location_ screens.
. Select *Check daily for Git for Windows updates* on the _Select Components_ screen, then click *Next*.
. Click *Next* on the remaining screens to accept the default settings.
. Once the installation is complete, click *Finish*.

[[createaprivatepublickeypaironwindows]]
=== Create a private/public key pair on Windows

To create a private/public key pair:

. Open the *Start* menu (or _Windows_ menu) and open *Git Bash*.
. On the _Git bash_ command line, run:
+
[source,sh]
----
ssh-keygen -m PEM -t rsa -b 2048 -f <MY_KEY_PAIR_NAME>
----
+
Where _`+<MY_KEY_PAIR_NAME>+`_ should be replaced with a name for the key pair.

include::partial$auth/passphrase-step-jwt.adoc[]

Two files will be created in the current directory:

* `+<MY_KEY_PAIR_NAME>+` - The private key.
* `+<MY_KEY_PAIR_NAME>.pub+` - The public key.

[[retrievethepublickeyonwindows]]
=== Retrieve the public key on Windows

To retrieve the public key, on a _Git bash_ command line, run:

[source,sh]
----
openssl rsa -in <MY_KEY_PAIR_NAME> -outform DER -pubout | base64 -w0
----

The public key for the `+<MY_KEY_PAIR_NAME>+` key pair will be printed on the command line with base64 encoding.
