The \{\{pluginname}} Server requires a _public_ key generated from the same _private_ key that will be used on your JSON Web Token (JWT) provider endpoint. The public key(s) stored on the \{\{pluginname}} Server are used to ensure that content is sent by authorized users.

There are two methods for generating and adding a public key to your API key:

[arabic]
. The secure key pair generator at link:{accountpageurl}/jwt/[\{\{site.accountpage}} - JWT Keys] (recommended).
. Generate a key pair locally and add the _public_ key to link:{accountpageurl}/jwt/[\{\{site.accountpage}} - JWT Keys].

[[generate-a-key-pair-using-the-siteaccountpage-jwt-keys-page]]
== Generate a key pair using the \{\{site.accountpage}} JWT Keys page

The link:{accountpageurl}/jwt/[\{\{site.accountpage}} - JWT Keys] page provides a private/public key generator, providing a quick and secure way of generating the required keys. This generator will store a copy of the _public_ key, and provide a downloadable file for both the public and private keys. \{\{site.companyname}} does not store the _private_ key and the key pair cannot be retrieved later.

== Generate a key pair locally

When generating a key pair locally, use one of the supported algorithms.
include::partial$auth/jwt-supported-algorithms.adoc[]

For instructions on generating a key pair locally, see: link:{baseurl}/how-to-guides/generate-rsa-key-pairs/[Creating a private/public key pair for Tiny Cloud].

\{% if include.numberedHeading == true %}

[[2-add-a-public-key-to-the-sitecloudname-api-key]]
== 2. Add a public key to the \{\{site.cloudname}} API key

\{% else %}

[[add-a-public-key-to-the-sitecloudname-api-key]]
== Add a public key to the \{\{site.cloudname}} API key

\{% endif %} Once a public key has been generated, add the public key to the \{\{site.cloudname}} API key at: link:{accountpageurl}/jwt/[\{\{site.accountpage}} - JWT Keys].
