:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Contribute to TinyMCE development
:description: Contribute to the open source project. Help build the core, plugins or even write the documentation.
:description_short: Contribute to the open source project.
:keywords: opensource oss contributors lgpl
:title_nav: Contribute to TinyMCE

{productname} is an open source software project. We encourage developers to contribute patches and code to include in {productname}. However, there are a few rules and limitations:

[[basic-rules]]
== Basic rules

* Contributed code will be licensed under the LGPL license, but not limited to LGPL.
* Copyright notices will be changed to {companynameformal} but contributors will get credit for their work.
* All third party code will be reviewed, tested and possibly modified before being released.
* For contributions to be accepted, a Contributors License Agreement must be completed.

These basic rules make it possible for us to manage the {productname} project and to ensure that the code remains open source and under the LGPL license.

[[how-to-contribute]]
== How to contribute

The {productname} source code is https://github.com/tinymce/tinymce[hosted on Github]. Through Github, you can submit _pull requests_ and log new bugs and feature requests.

[[contributing-to-the-documentation]]
== Contributing to the documentation

If you would like to contribute to {productname}'s documentation, please see our link:../contributing-docs/[contribute to documentation page and style guide].
