= tinymce.ui.Selector

Selector engine, enables you to select controls by using CSS like expressions. We currently only support basic CSS expressions to reduce the size of the core and the ones we support should be enough for most cases.

[[examples]]
== Examples

[source,prettyprint]
----
Supported expressions:
 element
 element#name
 element.class
 element[attr]
 element[attr*=value]
 element[attr~=value]
 element[attr!=value]
 element[attr^=value]
 element[attr$=value]
 element:<state>
 element:not(<expression>)
 element:first
 element:last
 element:odd
 element:even
 element element
 element > element
----

[[constructors]]
== Constructors

[cols=",,",options="header",]
|===
|name |summary |defined by
|link:#selector[Selector()] |Constructs a new Selector instance. |link:{baseurl}/api/tinymce.ui/tinymce.ui.selector.html[tinymce.ui.Selector]
|===

[[methods]]
== Methods

[cols=",,",options="header",]
|===
|name |summary |defined by
|link:#find[find()] |Returns a tinymce.ui.Collection with matches of the specified selector inside the specified container. |link:{baseurl}/api/tinymce.ui/tinymce.ui.selector.html[tinymce.ui.Selector]
|link:#match[match()] |Returns true/false if the selector matches the specified control. |link:{baseurl}/api/tinymce.ui/tinymce.ui.selector.html[tinymce.ui.Selector]
|===

== Constructors

[[selector]]
=== Selector

public constructor function Selector(selector:String)

Constructs a new Selector instance.

[[parameters]]
==== Parameters

* [.param-name]#selector# [.param-type]#(String)# - CSS like selector expression.

== Methods

[[find]]
=== find

find(container:tinymce.ui.Control):tinymce.ui.Collection

Returns a tinymce.ui.Collection with matches of the specified selector inside the specified container.

==== Parameters

* [.param-name]#container# link:{baseurl}/api/tinymce.ui/tinymce.ui.control.html[[.param-type]#(tinymce.ui.Control)#] - Container to look for items in.

[[return-value]]
==== Return value
anchor:returnvalue[historical anchor]

* link:{baseurl}/api/tinymce.ui/tinymce.ui.collection.html[[.return-type]#tinymce.ui.Collection#] - Collection with matched elements.

[[match]]
=== match

match(control:tinymce.ui.Control, selectors:Array):Boolean

Returns true/false if the selector matches the specified control.

==== Parameters

* [.param-name]#control# link:{baseurl}/api/tinymce.ui/tinymce.ui.control.html[[.param-type]#(tinymce.ui.Control)#] - Control to match against the selector.
* [.param-name]#selectors# [.param-type]#(Array)# - Optional array of selectors, mostly used internally.

==== Return value

* [.return-type]#Boolean# - true/false state if the control matches or not.
