:rootDir: ./../../
:partialsDir: {rootDir}partials/
= tinymce.dom.Selection

This class handles text and control selection it's an crossbrowser utility class. Consult the TinyMCE Wiki API for more details and examples on how to use this class.

[[examples]]
== Examples

[source,js]
----
// Getting the currently selected node for the active editor
alert(tinymce.activeEditor.selection.getNode().nodeName);
----

[[constructors]]
== Constructors

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#selection[Selection()] |Constructs a new selection instance. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|===

[[methods]]
== Methods

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#collapse[collapse()] |Collapse the selection to start or end of range. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#getbookmark[getBookmark()] |Returns a bookmark location for the current selection. This bookmark object can then be used to restore the selection after some content modification to the document. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#getcontent[getContent()] |Returns the selected contents using the DOM serializer passed in to this class. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#getend[getEnd()] |Returns the end element of a selection range. If the end is in a text node the parent element will be returned. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#getnode[getNode()] |Returns the currently selected element or the common ancestor element for both start and end of the selection. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#getrng[getRng()] |Returns the browsers internal range object. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#getsel[getSel()] |Returns the browsers internal selection object. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#getstart[getStart()] |Returns the start element of a selection range. If the start is in a text node the parent element will be returned. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#iscollapsed[isCollapsed()] |Returns true/false if the selection range is collapsed or not. Collapsed means if it's a caret or a larger selection. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#movetobookmark[moveToBookmark()] |Restores the selection to the specified bookmark. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#select[select()] |Selects the specified element. This will place the start and end of the selection range around the element. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#selectorchanged[selectorChanged()] |Executes callback when the current selection starts/stops matching the specified selector. The current state will be passed to the callback as it's first argument. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#setcontent[setContent()] |Sets the current selection to the specified content. If any contents is selected it will be replaced with the contents passed in to this function. If there is no selection the contents will be inserted where the caret is placed in the editor/page. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#setcursorlocation[setCursorLocation()] |Move the selection cursor range to the specified node and offset. If there is no node specified it will move it to the first suitable location within the body. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#setnode[setNode()] |Sets the current selection to the specified DOM element. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|link:#setrng[setRng()] |Changes the selection to the specified DOM range. |link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[tinymce.dom.Selection]
|===

== Constructors

[[selection]]
=== Selection

public constructor function Selection(dom:tinymce.dom.DOMUtils, win:Window, serializer:tinymce.dom.Serializer, editor:tinymce.Editor)

Constructs a new selection instance.

[[parameters]]
==== Parameters

* `+dom+` link:{rootDir}api/tinymce.dom/tinymce.dom.domutils.html[`+(tinymce.dom.DOMUtils)+`] - DOMUtils object reference.
* `+win+` `+(Window)+` - Window to bind the selection object to.
* `+serializer+` link:{rootDir}api/tinymce.dom/tinymce.dom.serializer.html[`+(tinymce.dom.Serializer)+`] - DOM serialization class to use for getContent.
* `+editor+` link:{rootDir}api/tinymce/tinymce.editor.html[`+(tinymce.Editor)+`] - Editor instance of the selection.

== Methods

[[collapse]]
=== collapse

collapse(toStart:Boolean)

Collapse the selection to start or end of range.

==== Parameters

* `+toStart+` `+(Boolean)+` - Optional boolean state if to collapse to end or not. Defaults to false.

[[getbookmark]]
=== getBookmark

getBookmark(type:Number, normalized:Boolean):Object

Returns a bookmark location for the current selection. This bookmark object can then be used to restore the selection after some content modification to the document.

[[examples-getbookmark]]
==== Examples

[source,js]
----
// Stores a bookmark of the current selection
var bm = tinymce.activeEditor.selection.getBookmark();

tinymce.activeEditor.setContent(tinymce.activeEditor.getContent() + 'Some new content');

// Restore the selection bookmark
tinymce.activeEditor.selection.moveToBookmark(bm);
----

==== Parameters

* `+type+` `+(Number)+` - Optional state if the bookmark should be simple or not. Default is complex.
* `+normalized+` `+(Boolean)+` - Optional state that enables you to get a position that it would be after normalization.

[[return-value]]
==== Return value
anchor:returnvalue[historical anchor]

* `+Object+` - Bookmark object, use moveToBookmark with this object to restore the selection.

[[getcontent]]
=== getContent

getContent(args:Object):String

Returns the selected contents using the DOM serializer passed in to this class.

==== Examples

[source,js]
----
// Alerts the currently selected contents
alert(tinymce.activeEditor.selection.getContent());

// Alerts the currently selected contents as plain text
alert(tinymce.activeEditor.selection.getContent({format: 'text'}));
----

==== Parameters

* `+args+` `+(Object)+` - Optional settings class with for example output format text or html.

==== Return value

* `+String+` - Selected contents in for example HTML format.

[[getend]]
=== getEnd

getEnd(real:Boolean):Element

Returns the end element of a selection range. If the end is in a text node the parent element will be returned.

==== Parameters

* `+real+` `+(Boolean)+` - Optional state to get the real parent when the selection is collapsed not the closest element.

==== Return value

* `+Element+` - End element of selection range.

[[getnode]]
=== getNode

getNode():Element

Returns the currently selected element or the common ancestor element for both start and end of the selection.

==== Examples

[source,js]
----
// Alerts the currently selected elements node name
alert(tinymce.activeEditor.selection.getNode().nodeName);
----

==== Return value

* `+Element+` - Currently selected element or common ancestor element.

[[getrng]]
=== getRng

getRng():Range

Returns the browsers internal range object.

==== Return value

* `+Range+` - Internal browser range object.

[[getsel]]
=== getSel

getSel():Selection

Returns the browsers internal selection object.

==== Return value

* `+Selection+` - Internal browser selection object.

[[getstart]]
=== getStart

getStart(real:Boolean):Element

Returns the start element of a selection range. If the start is in a text node the parent element will be returned.

==== Parameters

* `+real+` `+(Boolean)+` - Optional state to get the real parent when the selection is collapsed not the closest element.

==== Return value

* `+Element+` - Start element of selection range.

[[iscollapsed]]
=== isCollapsed

isCollapsed():Boolean

Returns true/false if the selection range is collapsed or not. Collapsed means if it's a caret or a larger selection.

==== Return value

* `+Boolean+` - true/false state if the selection range is collapsed or not. Collapsed means if it's a caret or a larger selection.

[[movetobookmark]]
=== moveToBookmark

moveToBookmark(bookmark:Object):Boolean

Restores the selection to the specified bookmark.

==== Examples

[source,js]
----
// Stores a bookmark of the current selection
var bm = tinymce.activeEditor.selection.getBookmark();

tinymce.activeEditor.setContent(tinymce.activeEditor.getContent() + 'Some new content');

// Restore the selection bookmark
tinymce.activeEditor.selection.moveToBookmark(bm);
----

==== Parameters

* `+bookmark+` `+(Object)+` - Bookmark to restore selection from.

==== Return value

* `+Boolean+` - true/false if it was successful or not.

[[select]]
=== select

select(node:Element, content:Boolean):Element

Selects the specified element. This will place the start and end of the selection range around the element.

==== Examples

[source,js]
----
// Select the first paragraph in the active editor
tinymce.activeEditor.selection.select(tinymce.activeEditor.dom.select('p')[0]);
----

==== Parameters

* `+node+` `+(Element)+` - HTML DOM element to select.
* `+content+` `+(Boolean)+` - Optional bool state if the contents should be selected or not on non IE browser.

==== Return value

* `+Element+` - Selected element the same element as the one that got passed in.

[[selectorchanged]]
=== selectorChanged

selectorChanged(selector:String, callback:function)

Executes callback when the current selection starts/stops matching the specified selector. The current state will be passed to the callback as it's first argument.

==== Parameters

* `+selector+` `+(String)+` - CSS selector to check for.
* `+callback+` `+(function)+` - Callback with state and args when the selector is matches or not.

[[setcontent]]
=== setContent

setContent(content:String, args:Object)

Sets the current selection to the specified content. If any contents is selected it will be replaced with the contents passed in to this function. If there is no selection the contents will be inserted where the caret is placed in the editor/page.

==== Examples

[source,js]
----
// Inserts some HTML contents at the current selection
tinymce.activeEditor.selection.setContent('<strong>Some contents</strong>');
----

==== Parameters

* `+content+` `+(String)+` - HTML contents to set could also be other formats depending on settings.
* `+args+` `+(Object)+` - Optional settings object with for example data format.

[[setcursorlocation]]
=== setCursorLocation

setCursorLocation(node:Node, offset:Number)

Move the selection cursor range to the specified node and offset. If there is no node specified it will move it to the first suitable location within the body.

==== Parameters

* `+node+` `+(Node)+` - Optional node to put the cursor in.
* `+offset+` `+(Number)+` - Optional offset from the start of the node to put the cursor at.

[[setnode]]
=== setNode

setNode(elm:Element):Element

Sets the current selection to the specified DOM element.

==== Examples

[source,js]
----
// Inserts a DOM node at current selection/caret location
tinymce.activeEditor.selection.setNode(tinymce.activeEditor.dom.create('img', {src: 'some.gif', title: 'some title'}));
----

==== Parameters

* `+elm+` `+(Element)+` - Element to set as the contents of the selection.

==== Return value

* `+Element+` - Returns the element that got passed in.

[[setrng]]
=== setRng

setRng(rng:Range, forward:Boolean)

Changes the selection to the specified DOM range.

==== Parameters

* `+rng+` `+(Range)+` - Range to select.
* `+forward+` `+(Boolean)+` - Optional boolean if the selection is forwards or backwards.
