= tinymce.dom.ScriptLoader

This class handles asynchronous/synchronous loading of JavaScript files it will execute callbacks when various items gets loaded. This class is useful to load external JavaScript files.

[[examples]]
== Examples

[source,js]
----
// Load a script from a specific URL using the global script loader
tinymce.ScriptLoader.load('somescript.js');

// Load a script using a unique instance of the script loader
var scriptLoader = new tinymce.dom.ScriptLoader();

scriptLoader.load('somescript.js');

// Load multiple scripts
var scriptLoader = new tinymce.dom.ScriptLoader();

scriptLoader.add('somescript1.js');
scriptLoader.add('somescript2.js');
scriptLoader.add('somescript3.js');

scriptLoader.loadQueue(function() {
   alert('All scripts are now loaded.');
});
----

[[methods]]
== Methods

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#add[add()] |Adds a specific script to the load queue of the script loader. |link:{rootDir}api/tinymce.dom/tinymce.dom.scriptloader.html[tinymce.dom.ScriptLoader]
|link:#isdone[isDone()] |Returns true/false if a script has been loaded or not. |link:{rootDir}api/tinymce.dom/tinymce.dom.scriptloader.html[tinymce.dom.ScriptLoader]
|link:#load[load()] |Loads a specific script directly without adding it to the load queue. |link:{rootDir}api/tinymce.dom/tinymce.dom.scriptloader.html[tinymce.dom.ScriptLoader]
|link:#loadqueue[loadQueue()] |Starts the loading of the queue. |link:{rootDir}api/tinymce.dom/tinymce.dom.scriptloader.html[tinymce.dom.ScriptLoader]
|link:#loadscripts[loadScripts()] |Loads the specified queue of files and executes the callback ones they are loaded. This method is generally not used outside this class but it might be useful in some scenarios. |link:{rootDir}api/tinymce.dom/tinymce.dom.scriptloader.html[tinymce.dom.ScriptLoader]
|link:#markdone[markDone()] |Marks a specific script to be loaded. This can be useful if a script got loaded outside the script loader or to skip it from loading some script. |link:{rootDir}api/tinymce.dom/tinymce.dom.scriptloader.html[tinymce.dom.ScriptLoader]
|===

== Methods

[[add]]
=== add

add(url:String, success:function, scope:Object, failure:function)

Adds a specific script to the load queue of the script loader.

[[parameters]]
==== Parameters

* `+url+` `+(String)+` - Absolute URL to script to add.
* `+success+` `+(function)+` - Optional success callback function to execute when the script loades successfully.
* `+scope+` `+(Object)+` - Optional scope to execute callback in.
* `+failure+` `+(function)+` - Optional failure callback function to execute when the script failed to load.

[[isdone]]
=== isDone

isDone(url:String):Boolean

Returns true/false if a script has been loaded or not.

==== Parameters

* `+url+` `+(String)+` - URL to check for.

[[return-value]]
==== Return value
anchor:returnvalue[historical anchor]

* `+Boolean+` - true/false if the URL is loaded.

[[load]]
=== load

load(url:String, callback:function, callback:function)

Loads a specific script directly without adding it to the load queue.

==== Parameters

* `+url+` `+(String)+` - Absolute URL to script to add.
* `+callback+` `+(function)+` - Optional success callback function when the script loaded successfully.
* `+callback+` `+(function)+` - Optional failure callback function when the script failed to load.

[[loadqueue]]
=== loadQueue

loadQueue(success:function, failure:function, scope:Object)

Starts the loading of the queue.

==== Parameters

* `+success+` `+(function)+` - Optional callback to execute when all queued items are loaded.
* `+failure+` `+(function)+` - Optional callback to execute when queued items failed to load.
* `+scope+` `+(Object)+` - Optional scope to execute the callback in.

[[loadscripts]]
=== loadScripts

loadScripts(scripts:Array, callback:function, scope:Object, callback:function)

Loads the specified queue of files and executes the callback ones they are loaded. This method is generally not used outside this class but it might be useful in some scenarios.

==== Parameters

* `+scripts+` `+(Array)+` - Array of queue items to load.
* `+callback+` `+(function)+` - Optional callback to execute when scripts is loaded successfully.
* `+scope+` `+(Object)+` - Optional scope to execute callback in.
* `+callback+` `+(function)+` - Optional callback to execute if scripts failed to load.

[[markdone]]
=== markDone

markDone(url:string)

Marks a specific script to be loaded. This can be useful if a script got loaded outside the script loader or to skip it from loading some script.

==== Parameters

* `+url+` `+(string)+` - Absolute URL to the script to mark as loaded.
