= tinymce.dom.BookmarkManager

This class handles selection bookmarks.

[[constructors]]
== Constructors

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#bookmarkmanager[BookmarkManager()] |Constructs a new BookmarkManager instance for a specific selection instance. |link:{rootDir}api/tinymce.dom/tinymce.dom.bookmarkmanager.html[tinymce.dom.BookmarkManager]
|===

[[methods]]
== Methods

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#getbookmark[getBookmark()] |Returns a bookmark location for the current selection. This bookmark object can then be used to restore the selection after some content modification to the document. |link:{rootDir}api/tinymce.dom/tinymce.dom.bookmarkmanager.html[tinymce.dom.BookmarkManager]
|link:#isbookmarknode[isBookmarkNode()] |Returns true/false if the specified node is a bookmark node or not. |link:{rootDir}api/tinymce.dom/tinymce.dom.bookmarkmanager.html[tinymce.dom.BookmarkManager]
|link:#movetobookmark[moveToBookmark()] |Restores the selection to the specified bookmark. |link:{rootDir}api/tinymce.dom/tinymce.dom.bookmarkmanager.html[tinymce.dom.BookmarkManager]
|===

== Constructors

[[bookmarkmanager]]
=== BookmarkManager

public constructor function BookmarkManager(selection:tinymce.dom.Selection)

Constructs a new BookmarkManager instance for a specific selection instance.

[[parameters]]
==== Parameters

* `+selection+` link:{rootDir}api/tinymce.dom/tinymce.dom.selection.html[`+(tinymce.dom.Selection)+`] - Selection instance to handle bookmarks for.

== Methods

[[getbookmark]]
=== getBookmark

getBookmark(type:Number, normalized:Boolean):Object

Returns a bookmark location for the current selection. This bookmark object can then be used to restore the selection after some content modification to the document.

[[examples]]
==== Examples

[source,js]
----
// Stores a bookmark of the current selection
var bm = tinymce.activeEditor.selection.getBookmark();

tinymce.activeEditor.setContent(tinymce.activeEditor.getContent() + 'Some new content');

// Restore the selection bookmark
tinymce.activeEditor.selection.moveToBookmark(bm);
----

==== Parameters

* `+type+` `+(Number)+` - Optional state if the bookmark should be simple or not. Default is complex.
* `+normalized+` `+(Boolean)+` - Optional state that enables you to get a position that it would be after normalization.

[[return-value]]
==== Return value
anchor:returnvalue[historical anchor]

* `+Object+` - Bookmark object, use moveToBookmark with this object to restore the selection.

[[isbookmarknode]]
=== isBookmarkNode

isBookmarkNode(node:DOMNode):Boolean

Returns true/false if the specified node is a bookmark node or not.

==== Parameters

* `+node+` `+(DOMNode)+` - DOM Node to check if it's a bookmark node or not.

==== Return value

* `+Boolean+` - true/false if the node is a bookmark node or not.

[[movetobookmark]]
=== moveToBookmark

moveToBookmark(bookmark:Object):Boolean

Restores the selection to the specified bookmark.

==== Examples

[source,js]
----
// Stores a bookmark of the current selection
var bm = tinymce.activeEditor.selection.getBookmark();

tinymce.activeEditor.setContent(tinymce.activeEditor.getContent() + 'Some new content');

// Restore the selection bookmark
tinymce.activeEditor.selection.moveToBookmark(bm);
----

==== Parameters

* `+bookmark+` `+(Object)+` - Bookmark to restore selection from.

==== Return value

* `+Boolean+` - true/false if it was successful or not.
