:rootDir: ./../../
:partialsDir: {rootDir}partials/
= tinymce.Shortcuts

Contains logic for handling keyboard shortcuts.

[[examples]]
== Examples

[source,js]
----
editor.shortcuts.add('ctrl+a', "description of the shortcut", function() {});
editor.shortcuts.add('meta+a', "description of the shortcut", function() {}); // "meta" maps to Command on Mac and Ctrl on PC
editor.shortcuts.add('ctrl+alt+a', "description of the shortcut", function() {});
editor.shortcuts.add('access+a', "description of the shortcut", function() {}); // "access" maps to ctrl+alt on Mac and shift+alt on PC
----

[[methods]]
== Methods

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#add[add()] |Adds a keyboard shortcut for some command or function. |link:{rootDir}api/tinymce/tinymce.shortcuts.html[tinymce.Shortcuts]
|link:#remove[remove()] |Remove a keyboard shortcut by pattern. |link:{rootDir}api/tinymce/tinymce.shortcuts.html[tinymce.Shortcuts]
|===

== Methods

[[add]]
=== add

add(pattern:String, desc:String, cmdFunc:String, scope:Object):Boolean

Adds a keyboard shortcut for some command or function.

[[parameters]]
==== Parameters

* `+pattern+` `+(String)+` - Shortcut pattern. Like for example: ctrl+alt+o.
* `+desc+` `+(String)+` - Text description for the command.
* `+cmdFunc+` `+(String)+` - Command name string or function to execute when the key is pressed.
* `+scope+` `+(Object)+` - Optional scope to execute the function in.

[[return-value]]
==== Return value
anchor:returnvalue[historical anchor]

* `+Boolean+` - true/false state if the shortcut was added or not.

[[remove]]
=== remove

remove(pattern:String):Boolean

Remove a keyboard shortcut by pattern.

==== Parameters

* `+pattern+` `+(String)+` - Shortcut pattern. Like for example: ctrl+alt+o.

==== Return value

* `+Boolean+` - true/false state if the shortcut was removed or not.
