= tinymce.EditorCommands

This class enables you to add custom editor commands and it contains overrides for native browser commands to address various bugs and issues.

[#methods .anchor]##

== link:#methods[Methods]

[cols=",,",options="header",]
|===
|name |summary |defined by
|link:#addcommands[addCommands()] |Adds commands to the command collection. |link:/docs-4x/api/tinymce/tinymce.editorcommands[tinymce.EditorCommands]
|link:#execcommand[execCommand()] |Executes the specified command. |link:/docs-4x/api/tinymce/tinymce.editorcommands[tinymce.EditorCommands]
|link:#querycommandstate[queryCommandState()] |Queries the current state for a command for example if the current selection is "bold". |link:/docs-4x/api/tinymce/tinymce.editorcommands[tinymce.EditorCommands]
|link:#querycommandsupported[queryCommandSupported()] |Returns true/false if the command is supported or not. |link:/docs-4x/api/tinymce/tinymce.editorcommands[tinymce.EditorCommands]
|link:#querycommandvalue[queryCommandValue()] |Queries the command value for example the current fontsize. |link:/docs-4x/api/tinymce/tinymce.editorcommands[tinymce.EditorCommands]
|===

== Methods

[#addcommands .anchor]##

=== link:#addcommands[addCommands]

addCommands(commandList:Object, type:String)

Adds commands to the command collection.

==== Parameters

* [.param-name]#commandList# [.param-type]#(Object)# - Name/value collection with commands to add, the names can also be comma separated.
* [.param-name]#type# [.param-type]#(String)# - Optional type to add, defaults to exec. Can be value or state as well.

[#execcommand .anchor]##

=== link:#execcommand[execCommand]

execCommand(command:String, ui:Boolean, value:Object, args:Object):Boolean

Executes the specified command.

==== Parameters

* [.param-name]#command# [.param-type]#(String)# - Command to execute.
* [.param-name]#ui# [.param-type]#(Boolean)# - Optional user interface state.
* [.param-name]#value# [.param-type]#(Object)# - Optional value for command.
* [.param-name]#args# [.param-type]#(Object)# - Optional extra arguments to the execCommand.

==== Return value

* [.return-type]#Boolean# - true/false if the command was found or not.

[#querycommandstate .anchor]##

=== link:#querycommandstate[queryCommandState]

queryCommandState(command:String):Boolean, Number

Queries the current state for a command for example if the current selection is "bold".

==== Parameters

* [.param-name]#command# [.param-type]#(String)# - Command to check the state of.

==== Return value

* [.return-type]#Boolean# - true/false if the selected contents is bold or not, -1 if it's not found.
* [.return-type]#Number# - true/false if the selected contents is bold or not, -1 if it's not found.

[#querycommandsupported .anchor]##

=== link:#querycommandsupported[queryCommandSupported]

queryCommandSupported(command:String):Boolean

Returns true/false if the command is supported or not.

==== Parameters

* [.param-name]#command# [.param-type]#(String)# - Command that we check support for.

==== Return value

* [.return-type]#Boolean# - true/false if the command is supported or not.

[#querycommandvalue .anchor]##

=== link:#querycommandvalue[queryCommandValue]

queryCommandValue(command:String):Object

Queries the command value for example the current fontsize.

==== Parameters

* [.param-name]#command# [.param-type]#(String)# - Command to check the value of.

==== Return value

* [.return-type]#Object# - Command value of false if it's not found.
