= Cloud Deployment of Editor & Plugins
:description: TinyMCE Cloud customers, you'll be up and running in less than 5 minutes.
:description_short: Learn how to set up the TinyMCE editor via our Cloud, or migrate from a Self-hosted environment.
:keywords: tinymce cloud script textarea apiKey

TinyMCE Cloud is the easiest way to integrate TinyMCE and upgrade to our premium plugins.

You may use TinyMCE Cloud without an API key as mentioned in the link:{{site.baseurl}}/general-configuration-guide[General Configuration] guide. However, to use our premium plugins or avoid the in-editor developer warning, you need to signup for an API key and update the script tag used to load the editor code into your application.

All TinyMCE Cloud accounts include a free, pre-configured cloud image proxy service. This is setup using the link:{{  site.baseurl }}/plugins/imagetools/[Image Tools] plugin.

== Integrating TinyMCE for the first time

=== Step 1: Embed the TinyMCE Cloud script tag into your webpage

To load TinyMCE for the very first time, you need to embed the TinyMCE editor code into your application. The code embedding is done by adding the following script tag into your app, or in the case of a web page the `<head>` of the page:

`js
<script src="{{ site.cdnurl }}?apiKey=your_API_key"></script>
`

=== Step 2: Load, customize and interact with TinyMCE

In addition to the advanced content creation solutions available in the Cloud offering, you have access to more than 40 open source plugins to enhance the editing experience. We have provided a range of link:{{ site.baseurl }}/demo/basic-example/[simple examples] and we encourage you to review our walkthrough documentation that will help you link:{{ site.baseurl }}/quick-start[get started with TinyMCE].

=== Step 3: Specifying purchased TinyMCE plugins and toolbar/menu items

Lastly, you just need to extend your TinyMCE configuration to include any of the additional, advanced plugins (and associated toolbar/menu items) you've purchased. You will find enablement guides here:

* link:{{ site.baseurl }}/plugins/powerpaste/[PowerPaste]
* link:{{ site.baseurl }}/plugins/tinymcespellchecker/[Spell Checker]

NOTE: `spellchecker_rpc_url` is *not* required when enabling this plugin via link:{{site.baseurl}}/cloud-deployment-guide[TinyMCE Cloud].

* link:{{ site.baseurl }}/plugins/imagetools/[Image Tools (with configured image proxy)]

____
Note:``imagetools_cors_hosts`` and `imagetools_proxy` are _not_ required to be configured when enabling this plugin via link:{{site.baseurl}}//cloud-deployment-guide[TinyMCE Cloud].
____

* link:{{ site.baseurl }}/plugins/a11ychecker/[Accessibility Checker]
* link:{{ site.baseurl }}/plugins/advcode/[Advanced Code Editor]
* link:{{ site.baseurl }}/plugins/mediaembed/[Enhanced Media Embed]
* link:{{ site.baseurl }}/plugins/linkchecker/[Link Checker]

NOTE: Please note that after purchasing a plugin, it may take up to 30 minutes for the plugin to become available with your editor. You may also need to clear your browser's cache.

=== Step 4: Forward proxy configuration

If your company network has a forward proxy that controls access to the internet, please ensure that the following URLs are accessible via this proxy.

* All URLs at which the editor is deployed.
* All URLs at which the plugins are deployed.
* \https://imageproxy.tinymce.com
* \https://hyperlinking.tinymce.com
* \https://spelling.tinymce.com

IMPORTANT: Please ensure that the `tiny-api-key` and `tinymce-api-key` headers are retained while requesting the list of URLs above.

=== Step 5: Specifying a translation

If you wish to use a language other than English (US), please https://www.tinymce.com/i18n[download a language pack] and then link:{{ site.baseurl }}/configure/localization/#language_url[specify its location] with the `language_url` configuration option.

== Migrating from a Self-hosted environment to TinyMCE Cloud

=== Step 1: Replace existing reference to tinymce.min.js

Migrating from a Self-hosted environment to the Cloud is a relatively straightforward process. Please remove your existing script tag that loads TinyMCE's JavaScript (typically a reference to `tinymce.min.js` either hosted in your application or available via one our legacy CDNs). Now, replace this script tag with the following:

`js
<script src="{{ site.cdnurl }}?apiKey=your_API_key"></script>
`

=== Step 2: Update custom plugin paths

If you have any custom created plugins (or if you've modified any of the existing plugins), in order for these plugins to continue operating with your Cloud deployment, you'll need to reference these plugins via link:{{ site.baseurl }}/configure/integration-and-setup/#external_plugins[external_plugins] rather than the regular link:{{ site.baseurl }}/general-configuration-guide/work-with-plugins/[plugins] configuration element.

=== Step 3: Specify purchased TinyMCE plugins and toolbar buttons

Now, you just need to extend your link:{{ site.baseurl }}/configure/[TinyMCE configuration] to include any additional plugins (and associated toolbar/menu items) you've purchased. You will find enablement guides here:

* link:{{ site.baseurl }}/plugins/powerpaste/[Powerpaste]
* link:{{ site.baseurl }}/plugins/tinymcespellchecker/[Spell Checker]

NOTE: `spellchecker_rpc_url` is *not* required when enabling this plugin via link:{{site.baseurl}}//cloud-deployment-guide[TinyMCE Cloud].

* link:{{ site.baseurl }}/plugins/imagetools/[Image Tools (with configured image proxy)]

____
Note:``imagetools_cors_hosts`` and `imagetools_proxy` are _not_ required to be configured when enabling this plugin via link:{{site.baseurl}}//cloud-deployment-guide[TinyMCE Cloud].
____

* link:{{ site.baseurl }}/plugins/a11ychecker/[Accessibility Checker]
* link:{{ site.baseurl }}/plugins/advcode/[Advanced Code Editor]
* link:{{ site.baseurl }}/plugins/mediaembed/[Enhanced Media Embed]
* link:{{ site.baseurl }}/plugins/linkchecker/[Link Checker]
