= Specify editor & plugin versions
:description: Specifying editor and plugin versions for Tiny Cloud deployments.
:description_short: Specifying editor and plugin versions for Tiny Cloud deployments.
:keywords: tinymce cloud script textarea apiKey

[#specifying-the-tinymce-editor-version-deployed-from-cloud]
== Specifying the TinyMCE editor version deployed from Cloud

Use the URL provided to specify the {{site.productname}} version when deploying via {{site.cloudname}}. Refer to the link:{{ site.baseurl }}/cloud-deployment-guide/editor-and-features[{{site.productname}} editor via the {{site.cloudname}}] for more information.

The following example is the default for loading {{site.productname}} {{site.productmajorversion}} via {{site.cloudname}}. Substitute 'no-api-key' with your api key in the examples below.

`js
<script src="{{ site.cdnurl }}" referrerpolicy="origin"></script>
`

This URL specifies the latest and quality assured release of {{site.productname}}.

[#selecting-specific-version-numbers]
=== Selecting specific version numbers

____
All {{site.cloudname}} channels are based on the {{site.enterpriseversion}} version. For information on the latest version of the {{site.cloudname}} stable channel, see: link:{{site.baseurl}}/release-notes/[{{site.productname}} Release Notes]. For a list of changes that *may* be present in the {{site.cloudname}} testing channel, see: link:{{site.baseurl}}/changelog/[{{site.productname}} Changelog].
____

Support for requesting specific versions of {{site.productname}} {{site.productmajorversion}} should work same as {{site.productname}} 4.  In the meantime, there are three release channels available, see the section below.

[#dev-testing-and-stable-releases]
=== dev, testing, and stable releases

Choose from `dev`, `testing`, or `stable` release channels to load the latest version of {{site.productname}} from {{site.cloudname}}.

These channels are updated automatically and provide the latest {{site.productname}} version that matches the criteria below.

[#dev-release-channel]
==== dev release channel

This channel deploys the absolute latest version of {{site.productname}} as documented in link:{{ site.baseurl }}/changelog/[{{site.productname}} changelog]. The current version of {{site.productname}} available through the `dev` channel https://cdn.tiny.cloud/1/no-api-key/tinymce/5-dev/version.txt[can be found here].

[#example]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5-dev/tinymce.min.js" referrerpolicy="origin"></script>
+`

[#testing-release-channel]
==== testing release channel

This channel deploys the current release candidate for the `stable` channel. The {{site.productname}} release candidate is undergoing quality assurance. The current version of {{site.productname}} available through the `testing` channel https://cdn.tiny.cloud/1/no-api-key/tinymce/5-testing/version.txt[can be found at here].

[#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5-testing/tinymce.min.js" referrerpolicy="origin"></script>
+`

[#stable-release-channel]
==== stable release channel

This channel deploys the latest release of {{site.productname}} that has passed our quality assurance process. The current version of {{site.productname}} available through the `/{{site.productmajorversion}}` stable channel can be found https://cdn.tiny.cloud/1/no-api-key/tinymce/5/version.txt[here]. The {{site.productname}} {{site.productmajorversion}} stable channel can be loaded from https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js[this url].

[#example-2]
===== Example

`js
<script src="{{ site.cdnurl }}" referrerpolicy="origin"></script>
`

[#specifying-the-version-of-featuresplugins-deployed-from-tiny-cloud]
== Specifying the version of features/plugins deployed from Tiny Cloud

Use the URL query parameters to specify the version of each premium plugin. This is used when deployment is through the link:{{ site.baseurl }}/cloud-deployment-guide/editor-and-features[{{site.productname}} editor and premium plugins via {{site.cloudname}}] or deploying link:{{ site.baseurl }}/cloud-deployment-guide/features-only[only premium plugins from {{site.cloudname}}].

[discrete#mentions]
==== Mentions

* link:{{ site.baseurl }}/plugins/mentions/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/mentions/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?mentions=2.0.0" referrerpolicy="origin"></script>
+`

[discrete#tiny-drive]
==== Tiny Drive

* link:{{ site.baseurl }}/plugins/drive/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/tinydrive/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?tinydrive=1.1.0" referrerpolicy="origin"></script>
+`

[discrete#comments-2-0]
==== Comments 2.0

* link:{{ site.baseurl }}/plugins/comments/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/tinycomments/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?tinycomments=2.0.0" referrerpolicy="origin"></script>
+`

[discrete#page-embed]
==== Page Embed

* link:{{ site.baseurl }}/plugins/pageembed/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/pageembed/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?pageembed=1.0.0" referrerpolicy="origin"></script>
+`

[discrete#permanent-pen]
==== Permanent Pen

* link:{{ site.baseurl }}/plugins/permanentpen/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/permanentpen/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?permanentpen=1.0.0" referrerpolicy="origin"></script>
+`

[discrete#format-painter]
==== Format Painter

* link:{{ site.baseurl }}/plugins/formatpainter/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/formatpainter/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?formatpainter=1.0.0" referrerpolicy="origin"></script>
+`

[discrete#powerpaste]
==== PowerPaste

* link:{{ site.baseurl }}/plugins/powerpaste[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/powerpaste/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?powerpaste=4.0.0" referrerpolicy="origin"></script>
+`

[discrete#spell-checker-pro]
==== Spell Checker Pro

* link:{{ site.baseurl }}/plugins/tinymcespellchecker[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/tinymcespellchecker/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?tinymcespellchecker=1.0.0" referrerpolicy="origin"></script>
+`

[discrete#accessibility-checker]
==== Accessibility Checker

* link:{{ site.baseurl }}/plugins/a11ychecker[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/a11ychecker/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?a11ychecker=2.0.0" referrerpolicy="origin"></script>
+`

[discrete#advanced-code-editor]
==== Advanced Code Editor

* link:{{ site.baseurl }}/plugins/advcode/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/advcode/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?advcode=2.0.0" referrerpolicy="origin"></script>
+`

[discrete#enhanced-media-embed]
==== Enhanced Media Embed

* link:{{ site.baseurl }}/plugins/mediaembed/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/mediaembed/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?mediaembed=2.0.0" referrerpolicy="origin"></script>
+`

[discrete#link-checker]
==== Link Checker

* link:{{ site.baseurl }}/plugins/linkchecker/[Developer documentation]
* http://cdn.tiny.cloud/1/no-api-key/tinymce-plugins/linkchecker/available-versions[Supported versions]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?linkchecker=2.0.0" referrerpolicy="origin"></script>
+`

[#specifying-a-self-hosted-deployment-of-featuresplugins]
== Specifying a self-hosted deployment of features/plugins

// Additional configuration is required when serving [only premium plugins from {{site.cloudname}}]({{ site.baseurl }}/cloud-deployment-guide/features-only) and from a self-hosted installation. URL query parameters and the special version name "SDK" can also be used in the configuration.

If you're deploying link:{{ site.baseurl }}/cloud-deployment-guide/features-only[only premium plugins from {{site.cloudname}}], you may want to have some features served from {{site.cloudname}} and some features served from your self-hosted installation. This is also possible with URL query parameters and the special version name "SDK".

The "SDK" version lets the {{site.productname}} Plugin Manager know that you're not using {{site.cloudname}} version of a particular plugin and that it shouldn't serve the plugin from {{site.cloudname}}. It also won't display any warning or error messages if you're not entitled to it.

[discrete#mentions-2]
==== Mentions

* link:{{ site.baseurl }}/plugins/mentions/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?mentions=sdk" referrerpolicy="origin"></script>
+`

[discrete#tiny-drive-2]
==== Tiny Drive

* link:{{ site.baseurl }}/plugins/drive/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?tinydrive=sdk" referrerpolicy="origin"></script>
+`

[discrete#comments-2-0-2]
==== Comments 2.0

* link:{{ site.baseurl }}/plugins/comments/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?tinycomments=sdk" referrerpolicy="origin"></script>
+`

[discrete#page-embed-2]
==== Page Embed

* link:{{ site.baseurl }}/plugins/pageembed/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?pageembed=sdk" referrerpolicy="origin"></script>
+`

[discrete#permanent-pen-2]
==== Permanent Pen

* link:{{ site.baseurl }}/plugins/permanentpen/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?permanentpen=sdk" referrerpolicy="origin"></script>
+`

[discrete#format-painter-2]
==== Format Painter

* link:{{ site.baseurl }}/plugins/formatpainter/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?formatpainter=sdk" referrerpolicy="origin"></script>
+`

[discrete#powerpaste-2]
==== PowerPaste

* link:{{ site.baseurl }}/plugins/powerpaste[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?powerpaste=sdk" referrerpolicy="origin"></script>
+`

[discrete#spell-checker-pro-2]
==== Spell Checker Pro

* link:{{ site.baseurl }}/plugins/tinymcespellchecker[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?tinymcespellchecker=sdk" referrerpolicy="origin"></script>
+`

[discrete#accessibility-checker-2]
==== Accessibility Checker

* link:{{ site.baseurl }}/plugins/a11ychecker[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?a11ychecker=sdk" referrerpolicy="origin"></script>
+`

[discrete#advanced-code-editor-2]
==== Advanced Code Editor

* link:{{ site.baseurl }}/plugins/advcode/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?advcode=sdk" referrerpolicy="origin"></script>
+`

[discrete#enhanced-media-embed-2]
==== Enhanced Media Embed

* link:{{ site.baseurl }}/plugins/mediaembed/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?mediaembed=sdk" referrerpolicy="origin"></script>
+`

[discrete#link-checker-2]
==== Link Checker

* link:{{ site.baseurl }}/plugins/linkchecker/[Developer documentation]

[discrete#example-2]
===== Example

`+js
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js?linkchecker=sdk" referrerpolicy="origin"></script>
+`

[#featuring-declared-editor-and-plugin-versions]
=== Featuring declared editor and plugin versions

Support for requesting specific versions of {{site.productname}} {{site.productmajorversion}} will work similar to {{site.productname}} 4.  Only the latest version is available via the {{site.cloudname}}.
