= Version Compatibility Reference
:description: Premium plugins compatibility with TinyMCE editor versions.
:description_short: Matrix of compatibility between TinyMCE editor versions and premium plugins.
:keywords: tinymce cloud script textarea apiKey

Some of our premium plugins are only compatible with specific versions of TinyMCE.

If you're deploying link:{baseurl}/cloud-deployment-guide/editor-and-features[both the TinyMCE editor and premium plugins via the Cloud], use the following matrix in conjunction with the optional parameters for specifying editor version and link:{baseurl}/cloud-deployment-guide/editor-plugin-version[plugin version] to ensure your editor and plugins are compatible.

If you're deploying link:{baseurl}/cloud-deployment-guide/features-only[premium plugins _only_ via the Cloud], you'll need to ensure you're either only loading plugins supported for your editor version, or that your editor is upgraded to the required release.

[cols=",^,^,^,,^,^,^,^"]
|===
|  | link:{baseurl}/plugins/powerpaste/[PowerPaste] | link:{baseurl}/plugins/tinymcespellchecker/[Spell Checker] | link:{baseurl}/plugins/a11ychecker/[Accessibility Checker] | Mentions | link:{baseurl}/plugins/advcode/[Advanced Code Editor] | MoxieManager +
(SDK ONLY) | link:{baseurl}/plugins/mediaembed/[Enhanced Media Embed] | link:{baseurl}/plugins/linkchecker/[Link Checker]

| 4.5.2
| Y
| Y
| Y
| Y
| Y
| Y
| Y
| Y

| 4.4.3
| Y
| Y
| Y
| Y
| Y
| Y
| N
| N

| 4.3.13
| Y
| Y
| Y
| Y
| Y
| Y
| N
| N

| 4.2.8
| Y
| N1
| N
| N
| N
| Y
| N
| N

| 4.1.10
| Y
| N
| N
| N
| N
| Y
| N
| N

| 4.0.28
| Y
| N
| N
| N
| N
| Y
| N
| N

| 3.5.8
| N
| N
| N
| N
| N
| Y
| N
| N

|
|
|
|
|
|
|
|
|
|===

_N1_ - For this combination of TinyMCE and Spellchecking, the link:{baseurl}/plugins/tinymcespellchecker/#spellchecker_dialog[spellchecker_dialog mode] is unavailable.
