[IMPORTANT]
====
The {pluginname} plugin **requires** JWT authentication when using the {companyname} Cloud service.

**Authentication Setup:**

. Create a JWT key in the Customer Portal
. Configure the `{plugincode}_token_provider` option to specify the endpoint for retrieving your JWT token

For more information on how to set up JWT authentication with {pluginname}, see examples: xref:{pluginfilename}-with-jwt-authentication-nodejs.adoc[{pluginname} with JWT authentication (Node.js)] or xref:{pluginfilename}-with-jwt-authentication-php.adoc[{pluginname} with JWT authentication (PHP)]

**Trial period behavior**

* **Trial Period:**
** With JWT: Full functionality, unlimited usage, no watermarks.
** Without JWT: Full functionality with watermarks.

* **After Trial:**
** With {pluginname} "add-on" + JWT: Full functionality (subscription-based).
** Without add-on: Plugin entitlements are `disabled` and functionality is no longer available.

Visit the link:https://www.tiny.cloud/auth/login/[account portal] to obtain your JWT key and test full functionality.
====