[[configuring-content-security-policy-csp-for-tinymce]]
== Configuring Content Security Policy (CSP) for TinyMCE

{productname} can be used with a https://content-security-policy.com/[CSP] header. When using a CSP, the following directives are *required* for {productname} to function:

[cols=",",options="header"]
|===
|Policy directives |Reason
|`+script-src 'self' *.tinymce.com *.tiny.cloud;+` |Scripts are sometimes loaded as script element with an src attribute.
|`+connect-src 'self' *.tinymce.com *.tiny.cloud blob:;+` |XMLHttpRequest is required by some services such as spellchecking and PowerPaste.
|`+img-src 'self' *.tinymce.com *.tiny.cloud data: blob:;+` |Images within the editor are sometimes base64 encoded, blob URLs, or proxied through the {cloudname} service.
|`+style-src 'self' 'unsafe-inline' *.tinymce.com *.tiny.cloud;+` |Styles are used for inline formatting (such as underline, font colors, etc.) and the positioning of user interface elements.
|`+font-src 'self' *.tinymce.com *.tiny.cloud;+` |Fonts are used for icons in the UI and is loaded from external files.
|===

[IMPORTANT]
====
There is a hardened approach to CSP, commonly known as _strict CSP_. A strict CSP:

1. uses a `+nonce+` for all `+<script>+` elements;

2. regenerates each `+nonce+` on every page load;

3. refactors inline event handlers such that they are added from a JavaScript block; and

4. does not allow the `+unsafe-inline+` value in any directive.

However, {productname} currently requires the `unsafe-inline` value in the `style-src` directive to present content other than plain-text.

As a consequence, running {productname} from within a strict CSP configuration is not currently supported.

Also, the required directives documented above prevent any content loading from external sources. To allow content from specific sources, add the source domains to the relevant directives. For example, to allow YouTube videos:

[source,html]
----
media-src 'self' *.youtube.com;
----

To allow content from any source, use the (*) wildcard. Allowing all sources (using *) negates the security policy for the source type. For example:

[source,html]
----
media-src *;
----

For information on Content Security Policies, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP[MDN Web Docs - Content Security Policy (CSP)].
====

When using the {cloudname}, use this CSP header:

[source,html]
----
<meta
  http-equiv="Content-Security-Policy"
  content="default-src 'none'; script-src 'self' *.tinymce.com *.tiny.cloud; connect-src 'self' *.tinymce.com *.tiny.cloud blob:; img-src 'self' *.tinymce.com *.tiny.cloud data: blob:; style-src 'self' 'unsafe-inline' *.tinymce.com *.tiny.cloud; font-src 'self' *.tinymce.com *.tiny.cloud;"
>
----

When self-hosting {productname} from a local domain, use this CSP header (excludes the *.tiny.cloud domain):

[source,html]
----
<meta
  http-equiv="Content-Security-Policy"
  content="default-src 'none'; script-src 'self'; connect-src 'self' blob:; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; font-src 'self';"
>
----
