ifeval::["{docname}" == "available-menu-items"]
[#{plugincode}plugin]
== {pluginname} plugin

The {pluginname} plugin provides the following menu items:

ifdef::altplugincode[]
include::partial$menu-item-ids/{altplugincode}-menu-items.adoc[]
endif::[]
ifndef::altplugincode[]
include::partial$menu-item-ids/{plugincode}-menu-items.adoc[]
endif::[]

ifeval::["{plugincode}" == "comments"]
For information on the {pluginname} plugin, see: xref:introduction_to_tiny_comments.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincode}" != "comments"]

ifeval::["{plugincategory}" == "premium"]
For information on the {pluginname} plugin, see: xref:{plugincategory}-{plugincode}.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincategory}" != "premium"]
For information on the {pluginname} plugin, see: xref:{plugincode}.adoc[Plugins - The {pluginname} plugin]
endif::[]

endif::[]

endif::[]
ifeval::["{docname}" != "available-menu-items"]
[[menuitems]]
== Menu items

The {pluginname} plugin provides the following menu items:

ifdef::altplugincode[]
include::partial$menu-item-ids/{altplugincode}-menu-items.adoc[]
endif::[]
ifndef::altplugincode[]
include::partial$menu-item-ids/{plugincode}-menu-items.adoc[]
endif::[]

include::partial$misc/menu-item-settings.adoc[]
endif::[]
