ifeval::["{docname}" == "available-toolbar-buttons"]
[#{plugincode}plugin]
== {pluginname} plugin

The {pluginname} plugin provides the following toolbar buttons:

ifdef::altplugincode[]
include::partial$toolbar-button-ids/{altplugincode}-toolbar-buttons.adoc[]
endif::[]
ifndef::altplugincode[]
include::partial$toolbar-button-ids/{plugincode}-toolbar-buttons.adoc[]
endif::[]

ifeval::["{plugincode}" == "comments"]
For information on the {pluginname} plugin, see: xref:introduction_to_tiny_comments.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincode}" != "comments"]
ifeval::["{plugincode}" == "powerpaste"]
For information on the {pluginname} plugin, see: xref:introduction-to-powerpaste.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincode}" != "powerpaste"]

ifeval::["{plugincode}" == "tinymcespellchecker"]
For information on the {pluginname} plugin, see: xref:introduction-to-tiny-spellchecker.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincode}" != "tinymcespellchecker"]

ifeval::["{plugincode}" == "toc"]
For information on the {pluginname} plugin, see: xref:tableofcontents.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincode}" != "toc"]

ifeval::["{plugincode}" == "imagetools"]
For information on the {pluginname} plugin, see: xref:editimage.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincode}" != "imagetools"]
ifeval::["{plugincode}" == "tinydrive"]
For information on the {pluginname} plugin, see: xref:tinydrive-introduction.adoc[Plugins - The {pluginname} plugin]
endif::[]

ifeval::["{plugincode}" != "tinydrive"]
For information on the {pluginname} plugin, see: xref:{plugincode}.adoc[Plugins - The {pluginname} plugin]
endif::[]

endif::[]
ifeval::["{docname}" != "available-toolbar-buttons"]
[[toolbarbuttons]]
== Toolbar buttons

The {pluginname} plugin provides the following toolbar buttons:

ifdef::altplugincode[]
include::partial$toolbar-button-ids/{altplugincode}-toolbar-buttons.adoc[]
endif::[]
ifndef::altplugincode[]
include::partial$toolbar-button-ids/{plugincode}-toolbar-buttons.adoc[]
endif::[]

include::partial$misc/toolbar-button-settings.adoc[]

endif::[]
