ifeval::["{extensionType}" != "Packs"]
:extensionType: plugin
endif::[]
ifeval::[{pluralExtensionType} == true]
:isAre: are
endif::[]
ifeval::[{pluralExtensionType} != true]
:isAre: is
endif::[]

ifeval::["{pluginname}" != "Tiny Drive"]
[[getting-started-with-productname-pluginname]]
== Getting started with {productname} {pluginname}
endif::[]
ifeval::["{pluginname}" == "Tiny Drive"]
[[getting-started-with-pluginname]]
== Getting started with {pluginname}
endif::[]


[[creating-a-sitecloudname-account]]
=== Creating a {cloudname} account

Try the *{pluginname} {extensionType}* and the {cloudname} with a free link:{accountsignup}/[{accountpage}]. New accounts receive a 30-day trial of the {companyname} link:{plugindirectory}[premium plugins], skins, and icon packs; with no credit card information or commitment required.


ifeval::["{pluginname}" != "Tiny Drive"]
[[get-productname-pluginname]]
=== Get {productname} {pluginname}
endif::[]
ifeval::["{pluginname}" == "Tiny Drive"]
[[get-pluginname]]
=== Get {pluginname}
endif::[]

ifeval::["{pluginminimumplan}" != "enterprise"]
The *{pluginname} {extensionType}* {isAre} included in the following {cloudname} plans:
endif::[]
ifeval::["{pluginminimumplan}" == "enterprise"]
The *{pluginname} {extensionType}* {isAre} included in link:{pricingpage}/[{enterpriseplan}].
endif::[]

ifeval::["{pluginminimumplan}" == "tierone"]
* The link:{pricingpage}/[{tieroneplan}].
* The link:{pricingpage}/[{tiertwoplan}].
* The link:{pricingpage}/[{tierthreeplan}].
endif::[]
ifeval::["{pluginminimumplan}" == "tiertwo"]
* The link:{pricingpage}/[{tiertwoplan}].
* The link:{pricingpage}/[{tierthreeplan}].
endif::[]
ifeval::["{pluginminimumplan}" == "tierthree"]
* The link:{pricingpage}/[{tierthreeplan}].
endif::[]
ifeval::["{pluginminimumplan}" != "enterprise"]
* link:{pricingpage}/[{enterpriseplan}].
endif::[]

ifeval::["{pluginminimumplan}" == "tiertwo"]
A 14-day free trial is also available for the {tiertwoplan} and the {tierthreeplan}.
endif::[]
ifeval::["{pluginminimumplan}" == "tierthree"]
A 14-day free trial is also available for the {tiertwoplan} and the {tierthreeplan}.
endif::[]
ifeval::["{pluginminimumplan}" == "enterprise"]
A 14-day free trial is available for the {tierthreeplan}.
endif::[]



