\{% if extensionType != 'Packs' %} :extensionType: plugin \{% endif %} \{% if pluralExtensionType == true %} :isAre: are \{% else %} :isAre: is \{% endif %}

[[getting-started-with--if-pluginname--tiny-drive-siteproductname-endif--pluginname]]
== Getting started with \{% if pluginname != 'Tiny Drive' %}\{\{site.productname}}\{% endif %} \{\{pluginname}}

[[creating-a-sitecloudname-account]]
=== Creating a \{\{site.cloudname}} account

Try the *\{\{pluginname}} \{\{extensionType}}* and the \{\{site.cloudname}} with a free link:{accountsignup}/[\{\{site.accountpage}}]. New accounts receive a 30-day trial of the \{\{site.companyname}} link:{plugindirectory}[premium plugins], skins, and icon packs; with no credit card information or commitment required.

[[get--if-pluginname--tiny-drive-siteproductname-endif--pluginname]]
=== Get \{% if pluginname != 'Tiny Drive' %}\{\{site.productname}}\{% endif %} \{\{pluginname}}

\{% if pluginminimumplan != 'enterprise' %} The *\{\{pluginname}} \{\{extensionType}}* \{\{isAre}} included in the following \{\{site.cloudname}} plans: \{% else %} The *\{\{pluginname}} \{\{extensionType}}* \{\{isAre}} included in link:{pricingpage}/[\{\{site.enterpriseplan}}]. \{% endif %}

\{% case pluginminimumplan %} \{% when 'tierone' %}- The link:{pricingpage}/[\{\{site.tieroneplan}}]. \{% when 'tierone' or 'tiertwo' %}- The link:{pricingpage}/[\{\{site.tiertwoplan}}]. \{% when 'tierone' or 'tiertwo' or 'tierthree' %}- The link:{pricingpage}/[\{\{site.tierthreeplan}}].

* link:{pricingpage}/[\{\{site.enterpriseplan}}]. \{% endcase %}

\{% if pluginminimumplan == 'tiertwo' or pluginminimumplan == 'tierthree' %} A 14-day free trial is also available for the \{\{site.tiertwoplan}} and the \{\{site.tierthreeplan}}. \{% elsif pluginminimumplan == 'tierthree' %} A 14-day free trial is available for the \{\{site.tierthreeplan}}. \{% endif %}
