== Convert URLs to relative, absolute, or absolute with domain

=== Relative URLs

This will convert all URLs within the same domain to relative URLs. The URLs will be relative from the link:#document_base_url[document_base_url].

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : true,
  document_base_url : 'http://www.site.com/path1/'
});
----

Example: `+http://www.example.com/path1/path2/file.htm+` >> `+path2/file.htm+`

==== Example: Relative URLs on links and images

\{% include live-demo.html id="url-conversion-relative-1" %}

==== Example: Relative URLs on links and images to a specific page

\{% include live-demo.html id="url-conversion-relative-2" %}

=== Absolute URLs

This will convert all relative URLs to absolute URLs. The URLs will be absolute based on the link:#document_base_url[document_base_url].

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : false,
  remove_script_host : true,
  document_base_url : 'http://www.site.com/path1/'
});
----

Example: `+path2/file.htm+` >> `+/path1/path2/file.htm+`

==== Example: Absolute URLs on links and images

\{% include live-demo.html id="url-conversion-absolute-1" %}

==== Example: Absolute URLs and including domain on links and images

\{% include live-demo.html id="url-conversion-absolute-2" %}

=== Domain absolute URLs

This will convert all relative URLs to absolute URLs. The URLs will be absolute based on the link:#document_base_url[document_base_url] with domain.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  relative_urls : false,
  remove_script_host : false,
  document_base_url : 'http://www.site.com/path1/'
});
----

Example: `+path2/file.htm+` >> `+http://www.example.com/path1/path2/file.htm+`
