[[using-the-community-language-packs]]
== Using the community language packs

ifeval::[{forModuleLoaders} == false]
NOTE: {companyname} recommends using the `+language_url+` for the community language packs, to avoid copying the language pack into the `+tinymce/langs+` folder every time you upgrade {productname}.
endif::[]

To change the user interface language using a community language pack:

. Download the language pack from link:{gettiny}/language-packages/[the {companyname} Community Language Packages download page].
ifeval::[{forModuleLoaders} == true]
. Unzip and import/require the language file.
endif::[]
ifeval::[{forModuleLoaders} == false]
. Unpack the language file into the `+tinymce/langs+` folder.
endif::[]
. Set the xref:ui-localization.adoc#language[`+language+`] option in your {productname} configuration to the language code, matching the filename on the language pack. For example: If the language pack has the filename `+sv_SE.js+`, then set `+language: 'sv_SE',+`
. Confirm that the language has been set successfully by loading {productname}.

NOTE: The language code set in the {productname} configuration must match the filename of the language file. If the language file is not found, {productname} will not load.

If a language you need is not available, you may wish to translate {productname} yourself. To contribute to translating {productname}, go to our https://crowdin.com/project/tinymce[Crowdin translation page] and sign up. Then request to join an existing team, or create a new team if your language are not listed.
