:rootDir: ../
:partialsDir: {rootDir}partials/
= Comments Demo
:controls: toolbar button
:description: Tiny Comments provides the ability to add comments to the content and collaborate with other users for content editing.
:keywords: comments commenting tinycomments
:title_nav: Comments

[[comments-10-demo]]
== Comments 1.0 Demo
anchor:comments10demo[historical anchor]

In this example, the features in Comments 1.0 are highlighted, including adding a comment, replying to a comment, and deleting a comment. For more information on the other Comments 1.0 configuration options, see the link:{rootDir}plugins/comments/comments_1.0.html[docs].

++++
<p data-height="600" data-theme-id="0" data-slug-hash="pOzxJw" data-default-tab="result" data-user="tinymce" class="codepen">
  See the Pen <a href="http://codepen.io/tinymce/pen/pOzxJw/">pOzxJw</a>
  by TinyMCE (<a href="http://codepen.io/tinymce">@tinymce</a>)
  on <a href="http://codepen.io">CodePen</a>.
</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
++++

[[comments-20-demo]]
== Comments 2.0 Demo
anchor:comments20demo[historical anchor]

In this example, the features in Comments 2.0 are highlighted, including adding a comment, replying to a comment, and deleting a comment. For more information on the other Comments 2.0 configuration options, see the link:{rootDir}plugins/comments/comments_2.0.html[docs].

++++
<p data-height="600" data-theme-id="0" data-slug-hash="ZwjzWj" data-default-tab="result" data-user="tinymce" class="codepen">
  See the Pen <a href="http://codepen.io/tinymce/pen/ZwjzWj/">ZwjzWj</a>
  by TinyMCE (<a href="http://codepen.io/tinymce">@tinymce</a>)
  on <a href="http://codepen.io">CodePen</a>.
</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
++++
