= Accessibility checking
:description: WCAG & Section 508 compliant accessibility checking.
:keywords: a11y accessibility

For most developers, accessibility has become critical to the usability of their solutions. {{site.productname}}`'s link:{{site.baseurl}}/plugins/premium/a11ychecker/[accessibility checker] (based on technology built by link:{{site.url}}[{{site.companyname}}]) makes checking for common accessibility issues incredibly easy for content creators by using an interface that steps them through each error, and in most cases also recommends a solution.

The check is achieved within the editor before the user posts their content and operates in a similar fashion to running a spell check in Word.

Before the introduction of this feature users would have to manually check for errors, requiring an advanced knowledge of accessibility and typically an understanding of HTML. Most people creating content with {{site.productname}} don't possess these skills and if they do fixing errors can be an incredibly time-consuming task.

{% assign pluginname = 'Accessibility Checker' %}
{% assign pluginminimumplan = 'tierthree' %}
{% assign plugindocspage = 'a11ychecker' %}
{% include misc/purchase-premium-plugins.md %}
