:rootDir: ../
:partialsDir: {rootDir}partials/
:imagesDir: {rootDir}images/
= Format Painter
:controls: toolbar button
:description: Quickly apply formats to multiple pieces of text.
:keywords: formats formatting edit formatpainter_removeformat formatpainter_tableformats formatpainter_blacklisted_formats format painter configuration
:title_nav: Format Painter

The Format Painter plugin allows a user to copy and paste formatting from one location to another, such as font style and size.

The format painter retains the formatting after application making it possible to apply the same formatting multiple times by using the `Ctrl+Alt+V` keyboard shortcut.

The ability to reuse existing formatting saves the user time and ensures consistency across the content.

[[getting-started]]
=== Getting started
anchor:gettingstarted[historical anchor]

[[creating-an-account]]
==== Creating an account
anchor:creatinganaccount[historical anchor]

To try out Format Painter and Tiny Cloud-delivered editor, the first step is to create a free https://www.tiny.cloud/download/[Tiny account].

[NOTE]
====
The free user account provisioned with a free 30-day trial of all Tiny https://apps.tiny.cloud/product-category/tiny-cloud-extensions/[premium plugins], with no credit card information or commitment required.
====

[[buy-tinymce-format-painter]]
=== Buy TinyMCE Format Painter
anchor:buytinymceformatpainter[historical anchor]

Start with the https://www.tiny.cloud/pricing/[pricing page]
// this [dedicated product page](https://about.tiny.cloud/products/formatpainter/)
to see all the flexible pricing options. OEM and enterprise customers should https://www.tiny.cloud/contact/[contact sales directly].

For more information on Format Painter refer to the full link:{baseurl}/plugins/formatpainter/[documentation].

There is also a demo provided to explore the Format Painter capabilities link:{baseurl}/demo/formatpainter/[here].
