:rootDir: ../
:partialsDir: {rootDir}partials/
= Paste from Word
:description: Upgrade the Microsoft Word copy-and-paste capabilities of TinyMCE.
:keywords: enterprise powerpaste power paste powerpaste_word_import powerpaste_html_import powerpaste_block_drop powerpaste_allow_local_images microsoft word excel

[[improve-your-productivity--writing-experience]]
== Improve your productivity & writing experience
anchor:improveyourproductivitywritingexperience[historical anchor]

link:{tinymceproductsfeatures}powerpaste/[TinyMCE PowerPaste] automatically cleans up content from Microsoft Word and other HTML sources to ensure clean, compliant content that matches the look and feel of your site or app.

TinyMCE PowerPaste is a Premium Plugin from TinyMCE. We have flexible purchase options: as a link:{tinymceproductsfeatures}powerpaste/[stand-alone plugin], to link:{pricingpage}[OEM and custom enterprise pricing].

[NOTE]
====
Customers: we have full documentation explaining how to install and configure TinyMCE PowerPaste. link:{rootDir}plugins/powerpaste.html[Go to the docs.]
====

[[example-use-cases]]
== Example use cases
anchor:exampleusecases[historical anchor]

[[content-from-microsoft-word]]
=== Content from Microsoft Word
anchor:contentfrommicrosoftword[historical anchor]

If you paste content from Microsoft Word into your app, you probably know the published page usually doesn't match the site's style. Fonts can be different, images missing and formatting not the same as their original document.

This can be time consuming for users to fix, and usually involves manually editing HTML. It can also increase support requests.

TinyMCE PowerPaste automatically "`cleans`" pasted content, fixing these issues. It can also automatically upload images to a server, helping you spend time on more productive tasks.

[[content-from-microsoft-excel]]
=== Content from Microsoft Excel
anchor:contentfrommicrosoftexcel[historical anchor]

TinyMCE PowerPaste also makes light work of pasting Excel content into your app, automatically creating HTML compliant tables in the process.

While developers are very familiar writing HTML tables, most content creators literally don't know where to start. And then there's the issue of manually entering their Excel data into the table. This isn't a fun experience either.

For users of both Word and Excel, PowerPaste will dramatically improve the content production experience you deliver to your clients.

[[content-from-the-internet]]
=== Content from the internet
anchor:contentfromtheinternet[historical anchor]

If you cut and paste content from the internet into your app -- which includes almost everyone -- PowerPaste also works its auto-magic.

Just as it cleans up rogue formatting from sources like Word, it does the same for internet content. Need to grab a quote from a website for your blog post? PowerPaste removes classes, minimizing the chance of unwanted CSS overriding your stylesheets.

It also does the same for images, automatically linking to the source image URL. Perfect content, every time.

[[buy-tinymce-powerpaste]]
== Buy TinyMCE PowerPaste
anchor:buytinymcepowerpaste[historical anchor]

Start with our link:{tinymceproductsfeatures}powerpaste/[dedicated product page] to see our flexible pricing options. OEM and enterprise customers should link:{contactpage}[contact sales directly]. Still not sure? Check out the demo below.

[[powerpaste-demo]]
== PowerPaste demo
anchor:powerpastedemo[historical anchor]

++++
<p data-height="600" data-theme-id="0" data-slug-hash="Jbaeyr" data-default-tab="result" data-user="tinymce" class="codepen">
  See the Pen <a href="http://codepen.io/tinymce/pen/Jbaeyr/">Jbaeyr</a>
  by TinyMCE (<a href="http://codepen.io/tinymce">@tinymce</a>)
  on <a href="http://codepen.io">CodePen</a>.
</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
++++
