:rootDir: ../
:partialsDir: {rootDir}partials/
= Drive
:description: Tiny Drive. A premium plugin to manage files & images.
:keywords: tinydrive .net php relative_urls
:title_nav: Drive

[[cloud-based-file-and-image-management-for-tinymce]]
=== Cloud-based File and Image Management for TinyMCE
anchor:cloud-basedfileandimagemanagementfortinymce[historical anchor]

Tiny Drive is a premium TinyMCE plugin for cloud-based asset management and storage solution. Tiny Drive is a solution for creating rich text by attaching and embedding images, videos, and other files in your document.

Drive presents a cloud-based asset management and storage solution that provides the ease of use of Google Drive without the server requirements of a self-hosted asset manager such as our own MoxieManager.

[[getting-started]]
=== Getting Started
anchor:gettingstarted[historical anchor]

[[creating-an-account]]
==== Creating an Account
anchor:creatinganaccount[historical anchor]

If you would like to try out Drive and our Cloud-delivered editor, the first step is to create a free https://www.tiny.cloud/download/[Tiny account].  When you create an account, you are assigned an API key, which is required for the implementation of Drive.

[NOTE]
====
The API key is also provisioned with a free 30-day trial of all of our https://apps.tiny.cloud/product-category/tiny-cloud-extensions/[premium plugins], with no credit card information or commitment required.
====

[[configuring-the-editor-for-drive]]
==== Configuring the Editor for Drive
anchor:configuringtheeditorfordrive[historical anchor]

Once you have the API key, or if you are a current Cloud user who already has an API key, then you have access to Drive.  In order to get the service up and running, you'll need to complete a few more steps. See our link:{rootDir}plugins/drive.html[documentation] for more information.

[NOTE]
====
We are launching the service with a complimentary 100MB of storage and up to 1 GB of bandwidth.
====

[[security--performance]]
=== Security & Performance
anchor:securityperformance[historical anchor]

We know security is a primary concern when it comes to cloud storage.  Drive uses an https://aws.amazon.com/s3/[Amazon Web Services S3] bucket, the same storage solution used by companies like Netflix, Thomson Reuters, and Zillow.  (You can read about Amazon's comprehensive security approach https://aws.amazon.com/security/[here].)

As your assets are passed back and forth between your TinyMCE editor instance and the S3 bucket, Drive uses both your API key and a https://jwt.io/introduction/[JSON Web Token] (JWT) to authenticate each data transaction.  Each Drive user will need to create their own JWT, and we walk you through the whole process link:{rootDir}configure/jwt-authentication.html[here].

And to make sure your assets are delivered as fast as possible, we utilize the https://aws.amazon.com/cloudfront/[CloudFront CDN], which is Amazon's global content delivery network, known for its low latency and high data transfer speeds.

For more information on Drive see our full link:{rootDir}plugins/drive.html[documentation].

We also have a demo for you to explore the Drive capabilities link:{rootDir}demo/drive.html[here].
