:rootDir: ../
:partialsDir: {rootDir}partials/
= Comments
:description: Tiny Comments. A premium plugin to add comments and collaborate for content editing.
:keywords: enterprise pricing comment commenting

TinyMCE editor now has a highly desirable functionality, *Comments*.

The Comments plugin provides the user an ability to start or join a conversation by adding comments to the content within the TinyMCE editor.

Users can now add comments to their text from within their TinyMCE editor for collaboration, review, and providing feedback.

Currently, there are two versions of Comments compatible with TinyMCE v4:

* link:{rootDir}plugins/comments/comments_1.0.html[Comments 1.0]
* link:{rootDir}plugins/comments/comments_2.0.html[Comments 2.0]

[[collaborate-on-your-projects-within-your-content]]
=== Collaborate on your projects within your content
anchor:collaborateonyourprojectswithinyourcontent[historical anchor]

Comments offers the following primary functionality:

* A *user interface* to collaborate on content by creating and replying to comments.
* A way to control the delete operation on a comment or a comment thread if you want to remove it from your content.

[[primary-comments-functions]]
=== Primary Comments Functions
anchor:primarycommentsfunctions[historical anchor]

The Tiny Comments plugin allows the user to perform the following functions:

* Create a comment
* Reply to a comment
* Delete a comment/comment thread
* Lookup a comment
* Store a comment (Comments 1.0)
* Edit a comment (Comments 2.0)

[[buy-comments]]
=== Buy Comments
anchor:buycomments[historical anchor]

Start with our link:{tinymceproductsfeatures}comments/[dedicated product page] to see our flexible pricing options. Enterprise customers should link:{contactpage}[contact sales directly].

[[comments-demo]]
=== Comments demo
anchor:commentsdemo[historical anchor]

Still not sure? Check out the demos below.

* xref:demo/comments.adoc#comments10demo.html[Comments 1.0 demo]
* xref:demo/comments.adoc#comments20demo.html[Comments 2.0 demo]

NOTE: For more information on installing and configuring Tiny Comments, please visit the link:{rootDir}plugins/comments/index.html[documentation].
