:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Create an icon pack for TinyMCE
:description: How to make your own icon pack.
:description_short: Introducing icon pack creation.
:keywords: create creator skin icon
:title_nav: Create an icon pack

TinyMCE 5 introduced icon packs for customizing the editor icons.

[[prerequisites]]
=== Prerequisites

This guide assumes:

* Familiarity with the command line and running commands.
* https://nodejs.org/en/[NodeJS] and https://www.npmjs.com[NPM] are already installed.
* Optional: https://git-scm.com/[`git`] is already installed.

[[how-icons-work-in-tinymce]]
== How icons work in TinyMCE

A {productname} icon pack is a `.js` file containing strings of https://developer.mozilla.org/en-US/docs/Web/SVG[SVG's]. An icon pack can be used: to include one or more custom icons; or to replace some or all of the default {productname} icons.

An icon pack only requires the custom icons to be included; the default {productname} icons are used as a fallback for icons missing from the custom icon pack.

[NOTE]
====
Don't forget to explore our ready-to-use Premium Icon Packs such as 'Material' icons, and a smaller version of our default icons at link:{productpages}/skins-and-icon-packs/[Tiny Skins and Icon Packs].
====

[[creating-a-tinymce-icon-pack]]
== Creating a TinyMCE icon pack

To create a custom icon pack:

* <<downloadandsetuptheiconpacktemplate,Download and setup the icon pack template>>
* <<addthesvgfiles,Add the SVG files>>
* <<buildtheiconpack,Build the icon pack>>

[[download-and-setup-the-icon-pack-template]]
=== Download and setup the icon pack template

To use the {productname} icon pack template project:

. Download the https://github.com/tinymce/oxide-icon-pack-template[{productname} Oxide Icon Pack Template] by either:
 ** Downloading the `.zip` file from the https://github.com/tinymce/oxide-icon-pack-template[Oxide Icon Pack Template GitHub page] and extract the contents.
 ** From a terminal or command prompt, use git to clone the GitHub repository, such as:
+
[source,sh]
----
$ git clone https://github.com/tinymce/oxide-icon-pack-template.git
----
. Open a terminal or command prompt, navigate to the `oxide-icon-pack-template` directory.
. Install the project dependencies by executing:
+
[source,js]
----
$ npm install
----

. When prompted, enter a name for the icon pack. The icon pack name should only contain:
 ** Numbers.
 ** Letters.
 ** Hyphens ( `-` ).
 ** Underscores ( `_` ).

The icon pack name will be used with the link:{rootDir}configure/editor-appearance.html#icons[icons] option to apply the icons in {productname}.

[[add-the-svg-files]]
=== Add the SVG files

Each SVG files placed in `/src/svg` will be converted to an icon. The file names of the SVG files are used to set the icon identifier used by {productname}.

For example: `bold.svg` will have the identifier `bold`. Such as:

[source,js]
----
tinymce.init({
  selector: '#tiny_custom_button',
  toolbar: 'myButton',
  icons: 'my_icon_pack',
  setup: function (editor) {
    editor.ui.registry.addButton('myButton', {
      icon: 'bold',    // the 'bold' icon  created from 'bold.svg'
      onAction: function (_) {
        editor.insertContent('&nbsp;<strong>It\'s my icon button!</strong>&nbsp;');
      }
    });
  }
});
----

For a list of the icon identifiers, see: link:{rootDir}advanced/editor-icon-identifiers.html[Editor icon identifiers].

{productname} does not resize the SVGs provided, relying on the size defined in the SVG. This allows icons of different sizes to be used in the editor. The Toolbar button sizes are independent of the icon sizes. To change button sizes, a link:{rootDir}advanced/creating-a-skin.html[custom skin] is required.

NOTE: Input SVGs must be shapes, not strokes. SVG files containing strokes will not render correctly. If the input files contain strokes, use a graphics program to convert the strokes into shapes.

[[build-the-icon-pack]]
=== Build the icon pack

To build the icon pack using Gulp:

. Open a terminal or command prompt and navigate to the root directory of the icon pack (such as: `oxide-icon-pack-template/`).
. Build the icon pack by executing the `npx gulp` command:
+
[source,js]
----
$ npx gulp
----
 A `dist/` directory containing the icon pack will be created.

. Using a web browser, open `dist/html/icons.html` to preview the icons.

[[troubleshooting-information-for-building-icon-packs]]
==== Troubleshooting information for building icon packs

The SVG files are optimized during the build process with https://github.com/svg/svgo[SVGO]. The optimization can result in distorted graphics due to rounding errors. The graphics may be fixed by providing new SVGO options. To change the SVGO options used:

. Using a text editor, open `gulpfile.js`.
. Add the `svgo` option to the `iconPackager` function, such as:
+
[source,js]
----
iconPackager({
  name: 'my-icon-pack',
  svgo: { floatPrecision: 3 } //Increase the rounding precision
})
----
All user defined options, including SVGO options, will merge with the default options. For information on SVGO options, see: https://github.com/svg/svgo[SVGO on GitHub].

[[deploying-an-icon-pack]]
== Deploying an icon pack

An icon pack can be served either:

* <<deploytheiconpackwithtinymce,With {productname}>>
* <<deploytheiconpackandtinymceseparately,Separate from {productname}>>

[[deploy-the-icon-pack-with-tinymce]]
=== Deploy the icon pack with TinyMCE

:customIconPack: true
include::{partialsDir}configuration/icons.adoc[]

[[deploy-the-icon-pack-and-tinymce-separately]]
=== Deploy the icon pack and TinyMCE separately

include::{partialsDir}configuration/icons_url.adoc[]
:customIconPack: false
