:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= TinyMCE plugin Yeoman generator
:description: How to use the Yeoman generator to bootstrap a new TinyMCE plugin using ES2015/Babel or TypeScript.
:description_short: How to use the Yeoman generator to bootstrap a new TinyMCE plugin
:keywords: webpack yeoman generator plugin tinymce
:title_nav: Yeoman generator

The {productname} Plugin Generator is designed to make it quick and easy to get started creating plugins to extend and enhance your rich-text editing experience.

[[install-the-generator]]
== Install the generator

The plugin generator is built with the project scaffolding tool http://yeoman.io/[Yeoman]. To get started install both `yo` (the yeoman command) and the generator with the following command:

[source,sh]
----
npm install --global yo generator-tinymce
----

Wait for the install to finish.

[[run-the-generator]]
== Run the generator

Start the generator with the following command:

[source,sh]
----
yo tinymce
----

You will then be guided through these questions:

. *Plugin name?* +
The name of the plugin.
. *How do you want to write your plugin?* +
With what technology do you want to write your plugin? ES2015 transpiled with Babel, Typescript or the module system used internally by {companyname} called Bolt.
. *Use yarn instead of npm?* +
Use `yarn` instead of `npm` for a speedier install.
. *Skip git repo initialization?* +
Here you can skip the creation of a new repository for the plugin.
. *What's your name?* +
For license.
. *Your email? (optional)* +
For license.
. *Your website? (optional)* +
For license
. *Which license do you want to use?* +
Choose the license for the plugin.

Yeoman installs the needed dependencies, and the project is bootstrapped and ready. `cd` into the plugin directory and run the following command to start the auto-reloading development server:

[source,sh]
----
npm start
----

[[create-distribution-ready-build]]
== Create distribution ready build

Run the following command as root once you have completed development of the plugin:

[source,sh]
----
npm run build
----

A `dist` directory will be created with a directory named the same as your plugin containing three files:

* `plugin.js` - unminified plugin bundle
* `plugin.min.js` - minified and uglified plugin bundle
* `LICENSE` - the text file containing your license
