= Localize TinyMCE
:description: Localize TinyMCE with global language capabilities.
:keywords: internationalization localization languages
:title_nav: Localization

{{site.productname}} makes your project accessible to the world through its simple localization framework.

This section demonstrates how to change {{site.productname}}'s user interface to the user's language preference. These settings change the language in the toolbar, menu items, buttons, and tooltips.

NOTE: Language settings can be controlled in these configuration options: link:{{ site.baseurl }}/configure/localization/#directionality[directionality], link:{{ site.baseurl }}/configure/localization/#language[language] and  link:{{ site.baseurl }}/configure/localization/#language_url[language_url]. There is also a link:{{site.baseurl}}/plugins/opensource/directionality/[Directionality plugin] that adds a toolbar button to control `ltr-rtl` behavior.

== Step 1

Go to the link:{{site.gettiny}}/language-packages/[language download page] to review a list of language packs available for {{site.productname}}.

Click the download link on the far right of the table for a single language. Check the box beside each language and then click the download button at the bottom of the table for multiple languages.

IMPORTANT: The {{site.productname}} community translation project provides the language packs on our language download page.

== Step 2

Unpack the language `js` file(s) into the `path/to/tinymce/langs/` folder.

IMPORTANT: The language settings will not work unless the language pack is placed in `langs/` directory. The link:{{ site.baseurl }}/configure/localization/#language_url[language_url] configuration option is another method to enable additional language settings.

== Step 3

Set the language option in {{site.productname}}'s configuration to the language code in the list on link:{{ site.baseurl }}/configure/localization/#language[this page].

== Step 4

Load {{site.productname}} to confirm that the language is set correctly.

== A working example

The following code snippet sets {{site.productname}}'s language to Chinese and the text directionality from right to left.

link:{{site.gettiny}}/language-packages/[Download the Chinese language] pack to test this functionality. Install a _local instance_ of {{site.productname}} from the link:{{site.gettiny}}[downloads page]. Follow the link:{{ site.baseurl }}/general-configuration-guide/advanced-install/#self-hostedinstall[self-hosted install instructions].

[,html]
----
<!DOCTYPE html>
<html>
<head>
  <script src="js/tinymce.min.js"></script>
  <script type="text/javascript">
  tinymce.init({
    selector: 'textarea',
    language: 'zh_CN',
    directionality: 'rtl'
  });
  </script>
</head>

<body>
  <form method="post">
    <textarea>你好，世界!</textarea>
  </form>
</body>
</html>
----

{% assign_page next_page = "/general-configuration-guide/system-requirements/index.html" %}
{% include next-step.html next=next_page %}
