:rootDir: ../
:partialsDir: {rootDir}partials/
= 08. Check Spelling
:description: Take spell checking to your users.
:keywords: spell checker spelling browser_spellcheck gecko_spellcheck

Nobody likes content with spelling errors. Our team at TinyMCE is motivated to help your users create error-free content. Which is why we have several options to help you bring spell checking capabilities to your users.

[[browser-based-spell-checking]]
== Browser-based spell checking
anchor:browser-basedspellchecking[historical anchor]

The first and easiest to implement option is to utilize the browser's native spell check functionality by assigning the xref:configure/spelling.adoc#browser_spellcheck[`browser_spellcheck`] configuration option the value of `true`. Depending on the right click / context behavior you want, you _may_ need to enable the link:{rootDir}plugins/contextmenu.html[`contextmenu`] plugin.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  browser_spellcheck: true,
  contextmenu: false
});
----

[[php-spellchecker-component]]
== PHP Spellchecker component
anchor:phpspellcheckercomponent[historical anchor]

You can also use TinyMCE's PHP Spellchecker component, which you can link:{rootdir}attachments/tinymce_spellchecker_php_4.0.zip[download here]. To view the complete changelog history, view this link:{rootdir}_attachments/php_spelling_changelog.txt[txt] file. The TinyMCE's PHP Spellchecker component requires a little more work than the browser-based option, being a server-side script.

This plugin enables you to use *Enchant* or *PSpell* on the backend of your server to spell check contents within the TinyMCE editor.

[[installation-steps-for-the-default-enchant-engine]]
===== Installation steps for the default Enchant engine
anchor:installationstepsforthedefaultenchantengine[historical anchor]

. Make sure you enable *Enchant* in your PHP.
. Download the *TinyMCE Spellchecker* for PHP package. link:{rootdir}attachments/tinymce_spellchecker_php_4.0.zip[(Direct download)].
. Unpack the package in the your``/path/to/tinymce/plugins/spellchecker`` directory.
. Configure TinyMCE to use the spell checker by enabling the `spellchecker` plugin.
. Configure the `spellchecker_rpc_url` to `'spellchecker.php'`.
. Download word lists and place them in the `/dicts` directory for example "sv_SE.dic, sv_SE.aff".

[[example]]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'spellchecker',
  toolbar: 'spellchecker',
  spellchecker_rpc_url: 'spellchecker.php'
});
----

Please see the link:{rootDir}plugins/spellchecker.html[Spell Checker Plugin] for advanced configuration options.

[[tinymce-spellchecker-pro-plugin]]
== TinyMCE Spellchecker Pro plugin
anchor:tinymcespellcheckerproplugin[historical anchor]

For developers requiring a robust enterprise-grade spell check as-you-type functionality, you need the link:{rootDir}plugins/tinymcespellchecker.html[Spell Checker Pro plugin]. Spell Checker Pro requires both a client-side plugin to be configured and a server-side component to be installed and configured.

Full documentation can be found in the TinyMCE Enterprise link:{rootDir}enterprise/check-spelling/index.html[documentation for Spelling]. Learn more about link:{pricingpage}[TinyMCE Enterprise here].
