= TinyMCE distraction-free editing mode
:description: Mode that renders a lightweight UI for inline editing.
:keywords: Mode inlite distraction-free
:title_nav: Distraction-free editing mode

The *Distraction-free* mode renders the editor in inline mode without the menu bar or toolbar. Most of the editor functionality is accessed using: keyboard shortcuts, contextual menus, contextual toolbars, and toolbar functions provided by the `quickbars` plugin.

include::partial$misc/notonmobile.adoc[]

== Enabling distraction-free mode

To enable a basic distraction-free editor, use the following configuration.

[source, js]
----
tinymce.init({
    selector: 'div.tinymce',
    plugins: [ 'quickbars' ],
    toolbar: false,
    menubar: false,
    inline: true
});
----

The demonstration editor below is a distraction-free editor with some customizations.

liveDemo::editor-dfree[]

== Related configuration options

For information on:

* Configuring a Quick Toolbar; including `quicklink`, `quickimage`, and `quicktable`; see: link:{baseurl}/plugins/opensource/quickbars/[Quick Toolbar plugin].
* Configuring a contextual toolbar, see: link:{baseurl}/ui-components/contexttoolbar/[Context Toolbar].
* Configuring a contextual menu, see: link:{baseurl}/ui-components/contextmenu/[Context Menu].
* Disabling the {productname} menubar, see: link:{baseurl}/configure/editor-appearance/#menubar[Menubar].
* The `inline` setting, see: link:{baseurl}/configure/editor-appearance/#inline[inline].

{% assign_page next_page = "/general-configuration-guide/multiple-editors/index.html" %}
{% include next-step.html next=next_page %}
