:rootDir: ./../../
:partialsDir: {rootDir}partials/
= document_base_url

This option specifies the base URL for all relative URLs in the document. The default value is the directory of the current document. If a value is provided, it must specify a directory (not a document) and must end with a "/". This option also interacts with the xref:reference/configuration/relative_urls.adoc[relative_urls], xref:reference/configuration/remove_script_host.adoc[remove_script_host], and xref:reference/configuration/convert_urls.adoc[convert_urls] options to determine whether TinyMCE returns relative or absolute URLs. The FAQ contains a thorough link:/extras/TinyMCE_FAQ/[description] and an https://www.tiny.cloud/docs/demo/full-featured/[example page] of working with relative/absolute URLs.

Changed in 3.0: This may affect how other paths are interpreted, such as calls to tinyMCE.windowManager.open, so you may want to use absolute paths. The following configuration settings also appear to be affected by the document_base_url setting:

* xref:reference/configuration/content_css.adoc[content_css]
* xref:reference/configuration/external_link_list_url.adoc[external_link_list_url]
* xref:reference/configuration/external_image_list_url.adoc[external_image_list_url]

[[example-of-usage-of-the-document_base_url-option]]
== Example of usage of the document_base_url option:
anchor:exampleofusageofthedocument_base_urloption[historical anchor]

[source,js]
----
tinyMCE.init({
  document_base_url : "http://www.site.com/path1/"
});
----
