:rootDir: ./../../
:partialsDir: {rootDir}partials/
= entity_encoding

This option controls how entities/characters get processed by TinyMCE. The value can be set as shown in Encoding Types below.

The base entities `<` `>` `&` `'` and `"` will always be entity encoded into their named equivalents. Though `'` and `"` will only be encoded within attribute values and `<` `>` will only be encoded within text nodes. This is correct according too the HTML and XML specs.

[[encoding-types]]
== Encoding Types
anchor:encodingtypes[historical anchor]

|===
| Name | Summary

| named
| Characters will be converted into named entities based on the xref:reference/configuration/entities.adoc[entities] option. For example, a non-breaking space could be encoded as &nbsp;.

| numeric
| Characters will be converted into numeric entities. For example, a non-breaking space would be encoded as &#160;.

| raw
| All characters will be stored in non-entity form except these XML default entities: & < > &quot;
|===

[[example-of-usage-of-the-entity_encoding-option]]
== Example of usage of the entity_encoding option:
anchor:exampleofusageoftheentity_encodingoption[historical anchor]

`+js
tinyMCE.init({
  ...
  entity_encoding : "raw"
});
+`
