:rootDir: ./../../
:partialsDir: {rootDir}partials/
= extended_valid_elements

This option is very similar to xref:reference/configuration/valid_elements.adoc[valid_elements]. The only difference between this option and xref:reference/configuration/valid_elements.adoc[valid_elements] is that this one gets added to the existing rule set. This can be very useful if the existing rule set is fine but you want to add some specific elements that also should be valid.

When adding a new attribute by specifying an existing element rule (e.g. img), the entire rule for that element is over-ridden so be sure to include all valid attributes not just the one you wish to add. See xref:reference/configuration/valid_elements.adoc[valid_elements] for default rules.

[[example-of-usage-of-the-extended_valid_elements-option]]
== Example of usage of the extended_valid_elements option:
anchor:exampleofusageoftheextended_valid_elementsoption[historical anchor]

The below example replaces the current img rule (including the global element rules)

[source,js]
----
tinyMCE.init({
  ...
  extended_valid_elements : "img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name]"
});
----

Also see xref:reference/configuration/valid_elements.adoc[valid_elements] and xref:reference/configuration/invalid_elements.adoc[invalid_elements] for more configuration options.
