:rootDir: ./../../
:partialsDir: {rootDir}partials/
= theme_advanced_buttons_1_n_add

This option should contain a comma separated list of button/control names to add to the end of the specified toolbar row. The number 1-n is the row number to add the buttons/controls to. Below is a list of built-in controls, plugins may include other controls names that can be inserted but these are documented in the individual plugins. This option can only be used when theme is set to advanced and when the theme_advanced_layout_manager option is set to the default value of "SimpleLayout".

A complete reference of all built in buttons and controls can be found in the button/control reference page.

[[example-of-usage-of-the-theme_advanced_buttons1-n_add-option]]
== Example of usage of the `theme_advanced_buttons<1-n>_add option`: 
anchor:exampleofusageofthetheme_advanced_buttons1-n_addoption[historical anchor]

```js
tinyMCE.init({
  ...
  theme_advanced_buttons1_add : "separator,insertdate,inserttime,preview,zoom,separator,forecolor,backcolor"
  theme_advanced_buttons2_add : "bullist,numlist,separator,outdent,indent,separator,undo,redo,separator,link,unlink,anchor,image,cleanup,help,code"
  theme_advanced_buttons3_add : "hr,removeformat,visualaid,separator,sub,sup,separator,charmap"
});

```

[[common-mistakes]]
== Common Mistakes 
anchor:commonmistakes[historical anchor]

You can only use `theme_advanced_buttons<1-n>_add` once per n where n is a whole number starting with 1 with step 1. Multiple instances of the same n will overwrite each other. The following incorrect code will result in row 1 containing insertdate, inserttime, hr, and removeformat. Bullist and numlist will be overwritten.

```js
tinyMCE.init({
  ...
  theme_advanced_buttons1 : "insertdate,inserttime",
  theme_advanced_buttons1_add : "bullist,numlist",
  theme_advanced_buttons1_add : "hr,removeformat",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        ...
});

```
