:rootDir:
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Migrating from Froala to TinyMCE
:description: Upgrading your rich text editor from Froala Editor v3 to TinyMCE 5.
:keywords: migration considerations premigration pre-migration froala
:title_nav: Migrating from Froala

This page covers the basic steps for migrating from Froala Editor 3 to {productname} {productmajorversion}.
Procedures and links to our documentation have been included to assist with your migration to {productname}.

*Covered in this section:*

* link:{rootDir}migration-from-froala.html#migratingabasicfroalaconfigurationtotinymce[Migrating a Basic Froala Configuration to {productname}]
* link:{rootDir}migration-from-froala.html#updatingthelistofplugins[Updating the list of Plugins]
* link:{rootDir}migration-from-froala.html#migratingacustomtoolbarlayout[Migrating a Custom Toolbar Layout]
* link:{rootDir}migration-from-froala.html#configuringinlinemode[Configuring Inline Mode]
* link:{rootDir}migration-from-froala.html#migratingcustombuttons[Migrating Custom Buttons]
* link:{rootDir}migration-from-froala/#migratingcustomdrop-downtoolbarbuttons[Migrating Custom Drop-down Toolbar Buttons]

[[migrating-a-basic-froala-configuration-to-tinymce]]
== Migrating a Basic Froala Configuration to TinyMCE

To migrate from a basic Froala 3 configuration to a basic {productname} {productmajorversion} configuration, you need to:

. Replace the Froala links and source scripts with a {productname} source script.
. Replace the Froala editor variable assignment with the `tinymce.init` function.

[[replace-froala-links-and-source-script-with-a-tinymce-source-script]]
=== Replace Froala links and source script with a TinyMCE source script

. Remove the Froala links and source script, located in the `<head>` of the target HTML page.
For example:
+
[source,html]
----
<link href='/path/to/froala-editor/base/directory/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
<script type='text/javascript' src='/path/to/froala-editor/base/directory/js/froala_editor.pkgd.min.js'></script>
<link href='/path/to/froala-editor/base/directory/css/froala_style.min.css' rel='stylesheet' type='text/css' />
----

. Insert a {productname} source script into the `<head>` of the page.
 ** For {cloudname} deployments:
+
[source,html,subs="+attributes"]
----
<script src='{cdnurl}' referrerpolicy='origin'></script>
----
+
Replace `your-api-key` with your link:{accountpageurl}[{cloudname} API key].

 ** For Self-hosted {productname} deployments:
+
[source,html]
----
<script src='/path/to/tinymce/base/directory/tinymce.min.js'></script>
----
+
Replace `/path/to/tinymce/base/directory` with the relative path of the `tinymce/` directory containing `tinymce.min.js`.

For information on {productname} deployment types, see: link:{rootDir}general-configuration-guide/advanced-install.html[Installing {productname}].

[[replace-the-froala-editor-variable-assignment-with-the-tinymce-init-function]]
=== Replace the Froala editor variable assignment with the tinymce.init function

To insert an editor in the body of the page for a `<textarea>` element such as:

[source,html]
----
<form method='post'>
  <textarea id='myeditor'>Enter your comment here!</textarea>
</form>
----

. Remove the Froala editor variable assignment script.
+
[source,html]
----
<script>
  var editor = new FroalaEditor('textarea#myeditor')
</script>
----

. Add a `tinymce.init` function.
+
[source,html]
----
<script>
  tinymce.init({ selector: '#myeditor' });
</script>
----

For information on configuring the `selector` setting, see: link:{rootDir}general-configuration-guide/basic-setup.html[Basic Setup].

[[examples-basic-configuration]]
=== Examples: Basic Configuration

The following examples show an initial Froala configuration and the migrated {productname} configuration.

[[froala-3-a-basic-configuration]]
==== Froala 3 - A Basic Configuration

[source,html]
----
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <link href='/path/to/froala-editor/base/directory/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='/path/to/froala-editor/base/directory/js/froala_editor.pkgd.min.js'></script>
    <link href='/path/to/froala-editor/base/directory/css/froala_style.min.css' rel='stylesheet' type='text/css' />
  </head>
  <body>
    <form method='post'>
      <textarea id='basic_froala'>Hello, World! I'm a froala editor!</textarea>
    </form>
    <script>
      var editor = new FroalaEditor('textarea#basic_froala')
    </script>
  </body>
</html>
----

[[tinymce-5-a-basic-configuration]]
==== TinyMCE 5 - A Basic Configuration

[source,html]
----
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <script src='https://cdn.tiny.cloud/1/my-api-key/tinymce/5/tinymce.min.js' referrerpolicy='origin'></script>
  </head>
  <body>
    <form method='post'>
      <textarea id='tiny_basic'>Hello, World! I'm a tiny editor!</textarea>
    </form>
    <script>
      tinymce.init({ selector: 'textarea#tiny_basic' });
    </script>
  </body>
</html>
----

[[additional-information]]
=== Additional Information

For information on:

* Getting started with {productname}, see: link:{rootDir}quick-start[{productname} Quick Start].
* Installing {productname}, see: link:{rootDir}general-configuration-guide/advanced-install.html[Installing {productname}].

[[updating-the-list-of-plugins]]
== Updating the list of Plugins

Some _Froala core functionality_ is implemented by link:{rootDir}plugins.html[plugins for {productname}]; and some _Froala plugin-provided functionality_ is {productname} core functionality.

For Example:

* Froala includes ordered lists as part of the core functionality, but the `lists` plugin provides ordered lists for {productname}.
* Adding a font size option in Froala requires a plugin, but `fontsize` is core functionality for {productname}.

To include a plugin for a {productname} editor, add a `plugins` option and provide a link:{rootDir}configure/integration-and-setup.html#plugins[space-delimited list of the plugins to include], as shown below. You should delete any Froala sourcing scripts and Froala links from the page.

[[examples-enabling-plugins]]
=== Examples: Enabling Plugins

The following examples show how plugins are included or enabled in the Froala and {productname} editors.

[[froala-3-enabling-plugins]]
==== Froala 3 - Enabling Plugins

[source,html]
----
<head>
  <meta charset='utf-8'>
  <link href='/path/to/froala-editor/base/directory/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
  <script type='text/javascript' src='/path/to/froala-editor/base/directory/js/froala_editor.pkgd.min.js'></script>
  <link href='/path/to/froala-editor/base/directory/css/froala_style.min.css' rel='stylesheet' type='text/css' />
  <!-- Examples of Froala Plugin scripts -->
  <!-- Colors plugin -->
  <script type='text/javascript' src='/path/to/froala-editor/base/directory/js/plugins/colors.min.js'></script>
  <link href='/path/to/froala-editor/base/directory/css/plugins/colors.min.css' rel='stylesheet' type='text/css' />
  <!-- Emoticons plugin -->
  <script type='text/javascript' src='/path/to/froala-editor/base/directory/js/plugins/emoticons.min.js'></script>
  <link href='../css/plugins/emoticons.min.css' rel='stylesheet' type='text/css' />
  <!-- Font Family plugin -->
  <script type='text/javascript' src='/path/to/froala-editor/base/directory/js/plugins/font_family.min.js'></script>
  <!-- Font Size plugin -->
  <script type='text/javascript' src='/path/to/froala-editor/base/directory/js/plugins/font_size.min.js'></script>
  <!-- Help plugin -->
  <script type='text/javascript' src='/path/to/froala-editor/base/directory/js/plugins/help.min.js'></script>
  <link href='/path/to/froala-editor/base/directory/css/plugins/help.min.css ' rel='stylesheet' type='text/css' />
</head>
----

[[tinymce-5-enabling-plugins]]
==== TinyMCE 5 - Enabling Plugins

[source,html]
----
<script>
  tinymce.init({
    selector: '#tiny_editor',
    plugins: 'emoticons wordcount help code lists'
  });
</script>
----

[[additional-information-on-plugins]]
=== Additional Information on Plugins

* For information on enabling plugins for {productname}, see: link:{rootDir}configure/integration-and-setup.html#plugins[Integration and setup options: plugins].
* For a list of {productname} plugins, see: link:{rootDir}plugins.html[Add plugins to {productname}].

[[migrating-a-custom-toolbar-layout]]
== Migrating a Custom Toolbar Layout

To migrate a Custom Toolbar Layout from Froala to {productname}:

* Change the `toolbarButtons` option to `toolbar`.
* Update the toolbar item listing.
* Update the `plugin` option as required.

[[change-the-option-to]]
=== Change the `toolbarButtons` option to `toolbar`

Rename the Froala option `toolbarButtons` to `toolbar`.

[[update-the-toolbar-item-listing]]
=== Update the toolbar item listing

Froala and {productname} use different formats for listing toolbar items.

Froala accepts the list of toolbar buttons as a two-dimensional array of strings, with each array defining a group of toolbar items. For example:

[source,js]
----
toolbarButtons: [['undo', 'redo'], ['paragraphFormat'], ['bold', 'italic'],
['alignLeft', 'alignCenter', 'alignRight', 'alignJustify'],
['formatOL', 'formatUL'], ['indent', 'outdent']]
----

{productname} accepts a space-delimited string with horizontal bars (` | `) for grouping items.
For example:

[source,js]
----
toolbar: 'undo redo | formatselect | bold italic
| alignleft aligncenter alignright alignjustify
| numlist bullist | outdent indent'
----

Replace the names of toolbar items with the {productname} names. For example:

|===
| Toolbar Button | Froala | {productname}

| Format/Style Selector
| `paragraphFormat`
| `formatselect`

| Ordered list
| `formatOl`
| `numlist`

| Unordered list
| `formatUL`
| `bullist`
|===

[[update-the-option-as-required]]
=== Update the `plugin` option as required

The list of plugins may need updating, as indicated in link:{rootDir}migration-from-froala.html#updatingthelistofplugins[Updating the list of Plugins]. For example, the {productname} toolbar items; `numlist` and `bullist`, require the `lists` plugin.

For a list of toolbar items with the required plugins, see: link:{rootDir}advanced/editor-control-identifiers.html#toolbarcontrols[Editor control identifiers: Toolbar controls].

[[examples-custom-toolbar-layouts]]
=== Examples: Custom Toolbar Layouts

The following examples show a custom toolbar layout in Froala and the same layout migrated to {productname}.

[[froala-3-creating-a-custom-toolbar-layout]]
==== Froala 3 - Creating a Custom Toolbar Layout

[source,html]
----
<h2>Froala Custom Toolbar</h2>
  <form method='post'>
    <textarea id=froala_custom_toolbar>Hello, World! I'm a froala editor!</textarea>
  </form>
<script>
  var editor = new FroalaEditor('textarea#froala_custom_toolbar', {
    paragraphFormatSelection: true ,
    toolbarButtons: [['undo', 'redo'], ['paragraphFormat'], ['bold', 'italic'],
    ['alignLeft', 'alignCenter', 'alignRight', 'alignJustify'],
    ['formatOL', 'formatUL'], ['indent', 'outdent']]
  })
</script>
----

[[tinymce-5-creating-a-custom-toolbar-layout]]
==== TinyMCE 5 - Creating a Custom Toolbar Layout

[source,html,subs="+attributes"]
----
<h2>{productname} Custom Toolbar</h2>
  <form method='post'>
    <textarea id='tiny_custom_toolbar'>Hello, World! I'm a tiny editor!</textarea>
  </form>
<script>
  tinymce.init({
    selector: '#tiny_custom_toolbar',
    plugins: 'lists',
    toolbar: 'undo redo | formatselect | bold italic
      | alignleft aligncenter alignright alignjustify
      | numlist bullist | outdent indent',
  });
</script>
----

[[additional-information-on-customizing-toolbars]]
=== Additional Information on Customizing Toolbars

* For information on customizing the {productname} Toolbar, see: link:{rootDir}configure/editor-appearance.html#toolbar[User interface options: Toolbar].
* For a list of toolbar items, see: link:{rootDir}advanced/editor-control-identifiers.html#toolbarcontrols[Editor control identifiers: Toolbar controls].

[[configuring-inline-mode]]
== Configuring Inline Mode

When migrating from Froala to {productname}, the `toolbarInline` option changes to `inline`. Some additional settings you should consider include:

* link:{rootDir}plugins/quickbars.html[The Quick Toolbar plugin].
* link:{rootDir}ui-components/contexttoolbar.html[Context Toolbars].
* link:{rootDir}ui-components/contextmenu.html[Context Menus].
* link:{rootDir}configure/editor-appearance.html#menubar[Disabling the {productname} menubar].

[[examples-enabling-inline-mode]]
=== Examples: Enabling Inline Mode

The following examples show Froala and {productname} configured for inline mode.

[[froala-3-configuring-inline-mode]]
==== Froala 3 - Configuring Inline Mode

[source,html]
----
<h3>Froala Inline Mode</h3>
  <form method='post'>
    <div id=froala_custom_inline_toolbar>Hello, World! I'm a froala editor!</div>
  </form>
<script>
  var editor = new FroalaEditor('div#froala_custom_inline_toolbar', {
    toolbarInline: true,
    charCounterCount: false
  })
</script>
----

[[tinymce-5-configuring-inline-mode]]
==== TinyMCE 5 - Configuring Inline Mode

[source,html,subs="+attributes"]
----
<h3>{productname} Inline Mode</h3>
  <form method='post'>
    <div id='tiny_custom_inline_toolbar'>Hello, World! I'm a tiny editor!</div>
  </form>
<script>
  tinymce.init({
    selector: '#tiny_custom_inline_toolbar',
    inline: true
  });
</script>
----

[[additional-information-for-inline-mode]]
=== Additional Information for Inline Mode

For information on:

* The inline editing mode, see: link:{rootDir}general-configuration-guide/use-tinymce-inline.html[Setup inline editing mode].
* Configuring a Quick Toolbar, see: link:{rootDir}plugins/quickbars.html[Quick Toolbar plugin].
* Configuring a contextual toolbar, see: link:{rootDir}ui-components/contexttoolbar.html[Context Toolbar].
* Configuring a contextual menu, see: link:{rootDir}ui-components/contextmenu.html[Context Menu].
* Disabling the {productname} menubar, see: link:{rootDir}configure/editor-appearance.html#menubar[User interface options: Menubar].
* The {productname} distraction-free editing mode, see: link:{rootDir}general-configuration-guide/use-tinymce-distraction-free.html[{productname} distraction-free editing mode].

[[migrating-custom-buttons]]
== Migrating Custom Buttons

The {productname} `addButton` option is used in place of the Froala `RegisterCommand` option.

For information on getting started with the `addButton` option, see: link:{rootDir}ui-components/toolbarbuttons.html#howtocreatecustomtoolbarbuttons[Toolbar buttons].

[[examples-custom-toolbar-buttons]]
=== Examples: Custom Toolbar Buttons

The following examples show a Froala editor and a {productname} editor with a basic configuration and two custom toolbar buttons.

[[froala-3-creating-a-custom-toolbar-button]]
==== Froala 3 - Creating a Custom Toolbar Button

[source,html]
----
<h2>Froala Custom Button</h2>
  <form method='post'>
    <textarea id=froala_custom_button>Hello, World! I'm a froala editor!</textarea>
  </form>
<script>
  FroalaEditor.DefineIcon('mybutton1', {NAME: 'star', SVG_KEY: 'star'});
  FroalaEditor.RegisterCommand('mybutton1', {
    title: 'My Button',
    focus: true,
    undo: true,
    refreshAfterCallback: true,
    callback: function () {
      this.html.insert('&nbsp;<strong>It\'s my button!</strong>&nbsp;');
    }
  });

  FroalaEditor.RegisterCommand('My&#160;Button', {
    title: 'My Button',
    focus: true,
    undo: true,
    refreshAfterCallback: true,
    callback: function () {
      this.html.insert('&nbsp;<strong>It\'s my other button!</strong>&nbsp;');
    }
  });

  var editor = new FroalaEditor('textarea#froala_custom_button',{
    toolbarButtons: [['mybutton1'],['My&#160;Button']]
  })
</script>
----

[[tinymce-5-creating-a-custom-toolbar-button]]
==== TinyMCE 5 - Creating a Custom Toolbar Button

[source,html,subs="+attributes"]
----
<h2>{productname} Custom Button</h2>
  <form method='post'>
    <textarea id='tiny_custom_button'>Hello, World! I'm a tiny editor!</textarea>
  </form>
<script>
  tinymce.init({
    selector: '#tiny_custom_button',
    toolbar: 'myButton1 | myButton2',
    setup: function (editor) {
      editor.ui.registry.addButton('myButton1', {
        icon: 'user',
        onAction: function (_) {
          editor.insertContent('&nbsp;<strong>It\'s my icon button!</strong>&nbsp;');
        }
      });

      editor.ui.registry.addButton('myButton2', {
        text: 'My Button',
        onAction: function (_) {
          editor.insertContent('&nbsp;<strong>It\'s my text button!</strong>&nbsp;');
        }
      });
    }
  });
</script>
----

[[additional-information-on-custom-toolbar-buttons]]
=== Additional Information on Custom Toolbar Buttons

* For an overview on creating custom toolbar buttons, see: link:{rootDir}ui-components/toolbarbuttons.html#howtocreatecustomtoolbarbuttons[Toolbar buttons].
* For information on the available types of toolbar buttons and examples of custom toolbar buttons, see: link:{rootDir}ui-components/typesoftoolbarbuttons.html[Types of toolbar buttons].

[[migrating-custom-drop-down-toolbar-buttons]]
== Migrating Custom Drop-down Toolbar Buttons

The {productname} `addMenuButton` option is used in place of the Froala `RegisterCommand` `type: dropdown` option.

For information on getting started with the `addMenuButton` option, see: link:{rootDir}ui-components/toolbarbuttons.html#howtocreatecustomtoolbarbuttons[Toolbar buttons] and link:{rootDir}ui-components/typesoftoolbarbuttons.html#menubutton[Types of toolbar buttons: Menu button].

[[examples-custom-drop-down-buttons]]
=== Examples: Custom Drop-down Buttons

The following examples show a Froala editor and a {productname} editor with a basic configuration and a custom drop-down toolbar button.

[[froala-3-creating-a-custom-drop-down-button]]
==== Froala 3 - Creating a Custom Drop-down Button

[source,html]
----
<h2>Froala Custom Drop-down Button</h2>
  <form method='post'>
    <textarea id='froala_custom_button_menu'>Hello, World! I'm a froala editor!</textarea>
  </form>
<script>
  var option_values = {
    'Opt1': '<strong>You clicked menu item 1!</strong>',
    'Opt2': '<em>You clicked menu item 2!</em>'
  };
  FroalaEditor.DefineIcon('mybuttonmenu', {NAME: 'plus', SVG_KEY: 'add'});
  FroalaEditor.RegisterCommand('mybuttonmenu', {
    title: 'My Other Button Menu',
    type: 'dropdown',
    focus: false,
    undo: false,
    refreshAfterCallback: true,
    options: {
      'Opt1': 'Menu item 1',
      'Opt2': 'Menu item 2'
    },
    callback: function (cmd, val) {
      this.html.insert(option_values[val]);
    }
  });
  var editor = new FroalaEditor('textarea#froala_custom_button_menu', {
    toolbarButtons: [['mybuttonmenu']]
  })
</script>
----

[[tinymce-5-creating-a-custom-drop-down-button]]
==== TinyMCE 5 - Creating a Custom Drop-down Button

[source,html,subs="+attributes"]
----
<h2>{productname} Custom Drop-down Button</h2>
  <form method='post'>
    <textarea id='tiny_custom_button_menu'>Hello, World! I'm a tiny editor!</textarea>
  </form>
<script>
  tinymce.init({
    selector: '#tiny_custom_button_menu',
    toolbar: 'my_button',

    setup: function (editor) {
      editor.ui.registry.addMenuButton('my_button', {
        text: 'My button menu',
        icon: 'gamma',
        fetch: function (callback) {
          var items = [
            {
              type: 'menuitem',
              text: 'Menu item 1',
              onAction: function () {
                editor.insertContent('&nbsp;<strong>You clicked menu item 1!</strong>');
              }
            },
            {
              type: 'menuitem',
              text: 'Menu item 2',
              icon: 'user',
              onAction: function () {
                editor.insertContent('&nbsp;<em>You clicked menu item 2!</em>');
              }
            }
          ];
          callback(items);
        }
      });
    }
  });
</script>
----

[[additional-information-on-drop-down-buttons]]
=== Additional Information on Drop-down Buttons

For information on creating drop-down buttons, see: link:{rootDir}ui-components/typesoftoolbarbuttons.html#menubutton[Types of toolbar buttons: Menu button].
