:rootDir:
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Quick start
:description: Get an instance of TinyMCE 5 up and running using the Tiny Cloud.
:description_short: Setup a basic TinyMCE 5 editor using the Tiny Cloud.
:keywords: tinymce script textarea
:title_nav: Quick start

{productname} {productmajorversion} is a powerful and flexible rich text editor that can be embedded in web applications. This quick start covers how to add a {productname} editor to a web page using the {cloudname}.

[[step-1-include-the-tinymce-script]]
== Step 1: Include the TinyMCE script

Include the following line of code in the `<head>` of a HTML page.

[source,html,subs="+attributes"]
----
<script src="{cdnurl}" referrerpolicy="origin"></script>
----

[[step-2-initialize-tinymce-as-part-of-a-web-form]]
== Step 2: Initialize TinyMCE as part of a web form

Initialize {productname} {productmajorversion} on any element (or elements) on the web page by passing an object containing a `selector` value to `tinymce.init()`. The `selector` value can be any valid https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors[CSS selector].

For example: To replace `<textarea id="mytextarea">` with a {productname} {productmajorversion} editor instance, pass the selector `'#mytextarea'` to `tinymce.init()`.

For example:

[source,html,subs="+attributes"]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="{cdnurl}" referrerpolicy="origin"></script>

    <script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>

  </head>

  <body>
  <h1>{productname} Quick Start Guide</h1>
    <form method="post">
      <textarea id="mytextarea">Hello, World!</textarea>
    </form>
  </body>
</html>
----

Adding this content to a HTML file and opening it in a web browser will load a TinyMCE editor, such as:

codepen::default[]

[[step-3-add-your-api-key]]
== Step 3: Add your API key

To remove the notice:

image:icons/warning.svg[warning icon]*This domain is not registered with {cloudname}. Please see the quick start guide or create an account.*

Replace `no-api-key` in the source script (`+<script src=...+`) with a {cloudname} API key, which is created when signing up to the link:{accountsignup}[{cloudname}].

Signing up for a {cloudname} API key will also provide a trial of the link:{rootDir}enterprise.html[Premium Plugins].

[[step-4-save-the-content-with-a-form-post]]
== Step 4: Save the content with a form POST

Process the content with a form handler.

When the `<form>` is submitted, {productname} {productmajorversion} will `POST` the content in the same way as a normal HTML `<textarea>`, including the HTML elements and inline CSS of the editor content. The host's form handler can process the submitted content in the same way as content from a regular `<textarea>`.

[[next-steps]]
== Next Steps

For information on:

* Customizing {productname}, see: link:{rootDir}general-configuration-guide/basic-setup.html[Basic Setup].
* The three editor modes:
 ** link:{rootDir}general-configuration-guide/use-tinymce-classic.html[{productname} classic editing mode].
 ** link:{rootDir}general-configuration-guide/use-tinymce-inline.html[{productname} inline editing mode].
 ** link:{rootDir}general-configuration-guide/use-tinymce-distraction-free.html[{productname} distraction-free editing mode].
* Adding {productname} plugins, see: link:{rootDir}general-configuration-guide/work-with-plugins.html[Work with plugins to extend TinyMCE].
* Localizing the {productname} editor, see: link:{rootDir}general-configuration-guide/localize-your-language.html[Localize {productname}].
* Self-hosting {productname}, see: link:{rootDir}general-configuration-guide/advanced-install.html[Installing {productname}].
