:rootDir: ../
:partialsDir: {rootDir}partials/
= React Integration
:description: React TinyMCE component.
:keywords: integration integrate react reactjs create-react-app
:title_nav: React

Integration with React is easily done with our https://github.com/tinymce/tinymce-react[@tinymce/tinymce-react] package. This how-to shows you how to setup a project using https://facebook.github.io/react/[react], xref:demo/basic-example.adoc[tinymce] and https://github.com/facebookincubator/create-react-app[Create React App].

[[installing-create-react-app]]
== 1. Installing `create-react-app`
anchor:1installingcreate-react-app[historical anchor]

We will use the https://github.com/facebookincubator/create-react-app[Create React App] to quickly and easily get our project up and running.

Simply run the following.

----
$ npm install -g create-react-app
----

[[create-a-new-project]]
== 2. Create a new project
anchor:2createanewproject[historical anchor]

Use `create-react-app` to create a new project named `tinymce-react-demo`.

----
$ create-react-app tinymce-react-demo
----
When all of the installs have finished, cd into the directory.

----
$ cd tinymce-react-demo
----

[[setup-react-tinymce]]
== 3. Setup `react-tinymce`
anchor:3setupreact-tinymce[historical anchor]

Install the npm package and save it to your `package.json` with `--save`.

----
$ npm install --save @tinymce/tinymce-react
----

[[loading-tinymce]]
=== 3.1 Loading TinyMCE
anchor:31loadingtinymce[historical anchor]

[[auto-loading-from-tinymce-cloud]]
==== Auto-loading from TinyMCE Cloud
anchor:auto-loadingfromtinymcecloud[historical anchor]

`@tinymce/tinymce-react` requires `tinymce` to be globally available to work, but to make it as easy as possible it will automatically load xref:cloud-deployment-guide/editor-and-features.adoc[TinyMCE Cloud] if it can't find TinyMCE available when the component is mounting. To get rid of the `+This domain is not registered...+` warning, sign up for the cloud and enter the api key like this:

[source,js]
----
<Editor apiKey='YOUR_API_KEY' init={{ /* your other settings */ }} />
----

You can also define what cloud channel you want to use out these three
* `stable` *Default*. The most stable and well-tested version that has passed the Tiny quality assurance process.
* `testing` This channel will deploy the current candidate for release to the `stable` channel.
* `dev` The cutting edge version of TinyMCE updated daily for the daring users.

So using the `dev` channel would look like this:

[source,js]
----
<Editor apiKey='YOUR_API_KEY' cloudChannel='dev' init={{ /* your other settings */ }} />
----

For more info on the different channels see the xref:cloud-deployment-guide/editor-and-features/editor-plugin-version.adoc#devtestingandstablereleases[documentation].

[[loading-tinymce-by-yourself]]
==== Loading TinyMCE by yourself
anchor:loadingtinymcebyyourself[historical anchor]

To opt out of using TinyMCE cloud, you have to make TinyMCE globally available yourself. This can be done either by hosting the `tinymce.min.js` file by yourself and adding a script tag to your HTML or, if you are using a module loader, installing TinyMCE with npm. For info on how to get TinyMCE working with module loaders check out xref:advanced/usage-with-module-loaders.adoc[this page in the documentation].

[source,html,subs=+attributes]
----
<script src="{cdnurl}"></script>
----

[[replace-the-appjs-file]]
== 4. Replace the App.js file
anchor:4replacetheappjsfile[historical anchor]

Open up the provided `App.js` file located in the `src` directory and replace its content with the code below.

[source,js]
----
import React from 'react';
import { Editor } from '@tinymce/tinymce-react';

class App extends React.Component {
  handleEditorChange = (e) => {
    console.log('Content was updated:', e.target.getContent());
  }

render() {
    return (
      <Editor
        initialValue="<p>This is the initial content of the editor</p>"
        init={{
          plugins: 'link image code',
          toolbar: 'undo redo | bold italic | alignleft aligncenter alignright | code'
        }}
        onChange={this.handleEditorChange}
      />
    );
  }
}

export default App;
----

[[start-the-development-server]]
== 5. Start the development server
anchor:5startthedevelopmentserver[historical anchor]

Start up the development server provided with `create-react-app`.

----
$ npm start
----

[[keep-on-hacking]]
== 6. Keep on hacking
anchor:6keeponhacking[historical anchor]

This was just a simple guide on how to get started. For more complex configuration information, see the  React documentation.
