= WordPress integration
:keywords: integration integrate wordpress advanced
:title_nav: WordPress

{{site.thirdPartyInteg}}

== Default Visual Editor in Wordpress

To use {{site.productname}} in WordPress, TinyMCE Advanced is a great option.

== PowerPaste for WordPress

link:{{site.plugindirectory}}powerpaste[{{site.productname}} PowerPaste for WordPress] is a premium plugin from the makers of {{site.productname}} that brings the PowerPaste features to WordPress. It automatically fixes Word formatting, creates tables from Excel, and links & embed images with content pasted from the web.

== TinyMCE Advanced

https://wordpress.org/plugins/tinymce-advanced/[TinyMCE Advanced] is a WordPress plugin built by https://profiles.wordpress.org/azaozz/[Andrew Ozz] that will let you add, remove, and arrange the buttons that are shown on the Visual Editor toolbar. It includes 15 plugins for {{site.productname}} that are automatically enabled or disabled depending on what buttons are chosen.

*Some of the features added by this plugin*

* Support for creating and editing tables
* More options when inserting lists
* Search and Replace in the editor
* Ability to set Font Family and Font Size

With this plugin, you will also be able to enable the {{site.productname}} menu. It is a convenient way to access a lot of features that are not used frequently.
