:rootDir: ../
:partialsDir: {rootDir}partials/
= WordPress Integration
:description: WordPress powers 25% of the web and TinyMCE is proud to be the default editor.
:keywords: integration integrate wordpress advanced
:title_nav: WordPress

[[default-visual-editor-in-wordpress]]
== Default Visual Editor in Wordpress
anchor:defaultvisualeditorinwordpress[historical anchor]

A slimmed down version of TinyMCE is the default "Visual Editor" in WordPress. If you want to use a version of TinyMCE closer to the full-featured Self-hosted release, TinyMCE Advanced is a great option.

[[powerpaste-for-wordpress]]
== PowerPaste for WordPress
anchor:powerpasteforwordpress[historical anchor]

https://apps.tiny.cloud/products/powerpaste/[TinyMCE PowerPaste for WordPress] is a premium plugin from the makers of TinyMCE that brings the PowerPaste features to WordPress. It automatically fixes Word formatting, creates tables from Excel, and links & embed images with content pasted from the web.

[[tinymce-advanced]]
== TinyMCE Advanced
anchor:tinymceadvanced[historical anchor]

https://wordpress.org/plugins/tinymce-advanced/[TinyMCE Advanced] is a WordPress plugin built by https://profiles.wordpress.org/azaozz/[Andrew Ozz] that will let you add, remove, and arrange the buttons that are shown on the Visual Editor toolbar. It includes 15 plugins for TinyMCE that are automatically enabled or disabled depending on what buttons are chosen.

*Some of the features added by this plugin*

* Support for creating and editing tables
* More options when inserting lists
* Search and Replace in the editor
* Ability to set Font Family and Font Size

With this plugin, you will also be able to enable the TinyMCE menu. It is a convenient way to access a lot of features that are not used frequently.

[[a-note-about-integrations]]
==== A note about integrations
anchor:anoteaboutintegrations[historical anchor]

NOTE:  We are pleased to reference third-party integrations/code to help you build great products with TinyMCE. If you have queries about this integration, please contact the developer directly.
