This section describes issues that users of {productname} 5.1 may encounter, as well as possible workarounds for these issues.

*Outline*

* <<autocompleterandkeypresseventissuesonandroid,Autocompleter and keypress event issues on Android>>
* <<textpatternspluginlimitedfunctionalityonandroiddevices,Text Patterns plugin: Limited functionality on Android devices>>
* <<spellcheckerpropluginunexpectedbehavioronandroiddevices,Spell Checker Pro plugin: Unexpected behavior on Android devices>>
* <<uielementsmayrenderbehindthekeyboardonios12devices,UI elements may render behind the keyboard on iOS 12 devices>>
* <<uiissuewithsidebarsonmobile,UI issue with sidebars on mobile>>
* <<findandreplacemovingoutofviewinios,Find and replace moving out of view in iOS>>
* <<inlinetoolbarplacementissuesonmobiledevices,Inline toolbar placement issues on mobile devices>>
* <<touchselectionhandleissueonios,Touch selection handle issue on iOS>>
* <<textselectioncontexttoolbarissueonandroiddevices,Text selection context toolbar issue on Android devices>>
* <<formatpainterlimitedfunctionalityoniosdevices,FormatPainter: Limited functionality on iOS devices>>

[[autocompleter-and-keypress-event-issues-on-android]]
=== Autocompleter and keypress event issues on Android

[[issue]]
==== Issue

NOTE: This issue affects the following plugins:
* link:{rootDir}plugins/mentions.html[Mentions].
* link:{rootDir}plugins/emoticons.html[Emoticons].
* link:{rootDir}plugins/charmap.html[Character Map].

Plugins relying on the link:{rootDir}ui-components/autocompleter.html[autocompleter API] or keypress events do not work on Android. Android intercepts content and processes content prior to insertion into the editor.

[[workaround]]
==== Workaround

The only known workaround for the autocompleter at the moment is to press space and then press backspace to trigger the autocompleter to activate.

[[text-patterns-plugin-limited-functionality-on-android-devices]]
=== Text Patterns plugin: Limited functionality on Android devices

[[issue-2]]
==== Issue

The text pattern plugin will not apply inline patterns if the text pattern is immediately followed by a space on Android devices. The Text Patterns plugin relies on keypress events, which do not work on Android. Android intercepts content and processes content prior to insertion into the editor.

[[workaround-2]]
==== Workaround

Press _Enter_ or _Return_ immediately after entering the text pattern.

[[spell-checker-pro-plugin-unexpected-behavior-on-android-devices]]
=== Spell Checker Pro plugin: Unexpected behavior on Android devices

[[issue-2]]
==== Issue

When selecting a correction, the original word will be duplicated and inserted at the selection point. Such as `Anddddroid` might be replaced with `Anddd Andddroid droid`.

[[workaround-2]]
==== Workaround

No known workaround at the time of release.

[[ui-elements-may-render-behind-the-keyboard-on-ios-12-devices]]
=== UI elements may render behind the keyboard on iOS 12 devices

[[issue-2]]
==== Issue

UI elements may be rendered behind the keyboard on iOS 12 devices. This includes, but is not limited to:

* Dialogs.
* Context menus.
* Context toolbars.

This is due to a limitation of Safari on iOS 12. The silver theme relies on the `VisualViewport` API to determine the area of the page is visible on the device. Unfortunately the `VisualViewport` API is an experimental feature in iOS 12.

[[workaround-2]]
==== Workaround

To workaround this issue, users can either:

* Upgrade to iOS 13 or later
* Turn on the experimental feature by going to:

*Settings* > *Safari* > *Advanced* > *Experimental Features* > *Visual Viewport API*.

[[ui-issue-with-sidebars-on-mobile]]
=== UI issue with sidebars on mobile

[[issue-2]]
==== Issue

NOTE: This issue affects the link:{rootDir}plugins/comments.html[Comments plugin].

When opening sidebars on small screens (such as mobile phones), the sidebar may occupy most or all of the text area of the editor.

[[workaround-2]]
==== Workaround

For the comments plugin, the comments sidebar can be collapsed using the `showcomments` toolbar button (image:icons/comment.svg[comment.svg]).

For other plugins with sidebars, {companyname} recommends ensuring the sidebar's toolbar button is accessible on the toolbar.

[[find-and-replace-moving-out-of-view-in-ios]]
=== Find and replace moving out of view in iOS

[[issue-2]]
==== Issue

The Find and replace dialog moves outside the screen view on iOS when finding a match off-screen.

[[workaround-2]]
==== Workaround

No known workaround at the time of release.

[[inline-toolbar-placement-issues-on-mobile-devices]]
=== Inline toolbar placement issues on mobile devices

[[issue-2]]
==== Issue

On mobile devices, the inline toolbar can intermittently display in the wrong location when the keyboard is open or when scrolling.

[[workaround-2]]
==== Workaround

No known workaround at the time of release.

[[touch-selection-handle-issue-on-ios]]
=== Touch selection handle issue on iOS

[[issue-2]]
==== Issue

The iOS touch selection handles (lollipops) sometimes remain on screen after the selection changes, resulting in misplaced or multiple selections.

[[workaround-2]]
==== Workaround

This may be an iOS bug, and the is no known workaround at the time of release. To remove the duplicate or multiple selections, restart the Safari app.

[[text-selection-context-toolbar-issue-on-android-devices]]
=== Text selection context toolbar issue on Android devices

[[issue-2]]
==== Issue

TinyMCE text selection context toolbars do not appear on Android.

[[workaround-2]]
==== Workaround

No known workaround at the time of release.

[[format-painter-plugin-limited-functionality-on-ios-devices]]
=== Format Painter plugin: Limited functionality on iOS devices

[[issue-2]]
==== Issue

Unable to apply formats using a collapsed selection on iOS due to iOS selection placement.

[[workaround-2]]
==== Workaround

No known workaround at the time of release.
