The Release Notes provide high-level coverage of the improvements and additions that have been implemented in TinyMCE 5.0 and document known problems in this release, as well as notable bug fixes, deprecated functionality, and other details.

TinyMCE 5.0 has an ARIA https://www.w3.org/WAI/standards-guidelines/wcag/[WCAG 2.1 standards] compliant user interface to make the user interface controls and dynamic content more accessible. In TinyMCE 5.0, more complex controls or dialogs can be written in the new API style while keeping the more straightforward methods of adding buttons and windows.

[[get-tinymce-5-0]]
=== Get TinyMCE 5.0

Include this line of code in the <head> of the HTML page and link to the tinymce.min.js source file. Substitute 'no-api-key' with your api key.

[source,html,subs="+attributes"]
----
<script src="{cdnurl}" referrerpolicy="origin"></script>
----

Signing up for a free API key provides entitlements to all our free plugins. This includes advanced functionality such as the link:{rootDir}plugins/imagetools.html[Image tools] plugin, which requires a cloud image proxy server to already be configured. Premium plugins can be purchased at any time once the API key has been set up.

Refer to the link:{rootDir}quick-start[Quick start] docs for more information.

[[upgrade]]
=== Upgrade

Developers can upgrade their TinyMCE 4.x instances to TinyMCE 5.0 with little or no fuss. For instructions on how to migrate, refer to the link:{rootDir}migration-from-4x.html[Migration guide].

NOTE:  An instance of TinyMCE with heavy customizations could take longer to upgrade. Please contact https://support.tiny.cloud[Customer Support] if encountering issues with the upgrade.

Try out TinyMCE 5.0 demo to explore the new UI.

[[tinymce-5-0-demo]]
=== TinyMCE 5.0 demo

codepen::full-featured[height=750]
