= User interface options
:description: Configure the editor's appearance, including menu and toolbar controls.
:description_short:
:title_nav: User interface options

{% include configuration/block_formats.md %}

{% include configuration/branding.md %}

{% include configuration/contextmenu.md %}

{% include configuration/contextmenu_avoid_overlap.md %}

{% include configuration/contextmenu_never_use_native.md %}

{% include configuration/custom_ui_selector.md %}

{% include configuration/draggable_modal.md %}

{% include configuration/elementpath.md %}

{% include configuration/event_root.md %}

{% include configuration/fixed_toolbar_container.md %}

{% include configuration/fixed_toolbar_container_target.md %}

{% include configuration/font_formats.md %}

{% include configuration/fontsize_formats.md %}

{% include configuration/height.md %}

{% include configuration/icons.md %}

{% include configuration/icons_url.md %}

{% include configuration/inline.md %}

{% include configuration/lineheight_formats.md %}

{% include configuration/max_height.md %}

{% include configuration/max_width.md %}

{% include configuration/menu.md %}

{% include configuration/menubar.md %}

{% include configuration/min_height.md %}

{% include configuration/min_width.md %}

{% include configuration/mobile.md %}

{% include configuration/placeholder.md %}

{% include configuration/preview_styles.md %}

{% include configuration/removed_menuitems.md %}

{% include configuration/resize.md %}

{% include configuration/skin.md %}

{% include configuration/skin_url.md %}

{% include configuration/statusbar.md %}

{% include configuration/style_formats.md %}

{% include configuration/style_formats_autohide.md %}

{% include configuration/style_formats_merge.md %}

{% include configuration/theme.md %}

{% include configuration/theme_url.md %}

{% include configuration/toolbar.md %}

{% include configuration/toolbar_n.md %}

{% include configuration/toolbar_mode.md %}

{% include configuration/toolbar_groups.md %}

{% include configuration/toolbar_location.md %}

{% include configuration/toolbar_persist.md %}

{% include configuration/toolbar_sticky.md %}

{% include configuration/toolbar_sticky_offset.md %}

{% include configuration/width.md %}
