:rootDir: ../
:partialsDir: {rootDir}partials/
:imagesDir: {rootDir}images/
= Drive plugin
:description: Cloud-based file and image management for TinyMCE.
:keywords: tinydrive storage media tiny drive
:title_nav: Drive

The Tiny Drive plugin adds the functionality to upload and manage files and images to the cloud. This plugin is only available in https://www.tiny.cloud/download/[Tiny Cloud] and requires you to register for an API key.

To enable this functionality, add `tinydrive` to the list of plugins in the `tinymce.init` call. You also need to authenticate the user using a link:{baseurl}/configure/jwt-authentication/[JSON Web Token] (JWT).

Once you enable Drive it integrates as the default file picker for the Image, Link, and Media dialogs and as the default upload handler for local images being pasted or inserted into the document.

[[example]]
=== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  plugins: 'tinydrive'
});
----

[[options]]
== Options

These settings are necessary to make Drive work:

[[tinydrive_token_provider]]
=== `tinydrive_token_provider`

This setting could take one of the following two forms:

* A URL to a page that takes an HTTP JSON POST request and produces a JSON structure with a valid JWT. It uses a POST request to avoid caching by browsers and proxies.
* A function that provides the same token through a callback. This allows you to make your own HTTP request in any format you like. The provider function is a function that has a success and failure callback where the success takes an object with a token property containing the JWT, and the failure callback takes a string to present as an error message if the token could not be produced.

You can read more about how to create these tokens in the link:{baseurl}/configure/jwt-authentication/[JWT authentication] guide.

*Type:* `String` or `Function`

*Required:* yes

[[example-using-a-jwt-provider-url]]
==== Example Using a JWT Provider URL
anchor:exampleusingajwtproviderurl[historical anchor]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'tinydrive',
  tinydrive_token_provider: '/jwt'
});
----

[[example-using-a-jwt-provider-callback]]
==== Example Using a JWT Provider Callback
anchor:exampleusingajwtprovidercallback[historical anchor]

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "tinydrive",
  tinydrive_token_provider: function (success, failure) {
     success({ token: 'jwt-token' });
     // failure('Could not create a jwt token')
  }
});
----

[[tinydrive_upload_path]]
=== `tinydrive_upload_path`

This setting enables you to change the default upload path for files that get uploaded when pasted into the editor, uploaded directly through the Image dialog, or when you drag-and-drop images into the editor. It will produce a date-based structure within this path like this `+/uploads/{year}{month}{day}+`. This is to avoid having thousands of files in the same directory.

*Type:* `String`

*Default Value:* `"/uploads"`

[[example]]
==== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "tinydrive",
  tinydrive_upload_path: '/some/other/path'
});
----

[[tinydrive_max_image_dimension]]
=== `tinydrive_max_image_dimension`

This setting enables you to constrain the width/height of uploaded images. When this is enabled any images with a higher width or height than the specified amount would be proportionally resized down to the specified max dimension.

*Type:* `Number`

==== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "tinydrive",
  tinydrive_max_image_dimension: 1024
});
----

[[insert-file-toolbar-button]]
== Insert File toolbar button
anchor:insertfiletoolbarbutton[historical anchor]

Drive will automatically integrate into the Image, Link, and Media dialogs as a file picker. You can also configure it to insert files directly into your content using the `insertfile` button. To enable this button, add it to your toolbar editor setting.

The Insert File toolbar button will insert images as `img` elements or other files as links to that file.

[[example-of-toolbar-button]]
=== Example of toolbar button
anchor:exampleoftoolbarbutton[historical anchor]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'tinydrive',
  toolbar: 'insertfile'
});
----

[[insert-file-menu-item]]
== Insert File menu item
anchor:insertfilemenuitem[historical anchor]

Drive will automatically integrate into the Image, Link, and Media dialogs as a file picker. You can also configure it to insert files directly into your content using the `insertfile` menu item. To enable this menu item, add it to your menus editor setting or the insert_button_items setting.

The Insert File menu item will insert images as `img` elements or other files as links to that file.

[[example-of-menu-item]]
=== Example of menu item
anchor:exampleofmenuitem[historical anchor]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'tinydrive',
  toolbar: 'insert',
  menu: {
    insert: { title: 'Insert', items: 'insertfile' }
  },
  insert_button_items: 'insertfile'
});
----

[[restrictions-and-quotas]]
== Restrictions and Quotas
anchor:restrictionsandquotas[historical anchor]

Drive has restrictions on what files can be uploaded and how large these files can be:

* The maximum file size is 100MB
* Allowed image extensions: gif, jpeg, jpg, png, tif, tiff, bmp
* Allowed document extensions: doc, xls, ppt, pps, docx, xlsx, pptx, pdf, rtf, txt, keynote, pages, numbers
* Allowed audio extensions: wav, wave, mp3, ogg, ogv, oga, ogx, ogm, spx, opus
* Allowed video extensions: mp4, m4v, ogv, webm, mov
* Allowed archive extensions: zip
* The Copy operation is limited to single files due to technical reasons.

Your storage and bandwidth quota varies based upon the https://www.tiny.cloud/pricing/[Tiny Cloud Plan] you are subscribed to.

[[upload-files-url]]
== Upload Files URL
anchor:uploadfilesurl[historical anchor]

All files are uploaded to a central storage with a CDN endpoint that means that we are hosting your files and they are publicly available in read-only mode for anyone that has access to the URL of that file.
The URL format for each file is `+https://drive.tiny.cloud/1/{your-api-key}/{uuid}+` and gets generated when a file is uploaded.
If you move or rename a file, it will still have the same unique URL, so the restructuring of your files using Drive won't affect where they are being used. However, deleting a file will mark the URL as being unused, and the URL will not continue to work.

[[user-specific-root]]
== User specific root
anchor:userspecificroot[historical anchor]

It's common that you want to be able to have user specific paths so that each user within your system gets it's own directory. This can be done by setting the `+https://claims.tiny.cloud/drive/root+` custom jwt claim to a path within your tiny drive account. This path will automatically be constructured when the user is accessing drive using a jwt key with that claim. The user only be able to see and manage files within that root.
