:rootDir: ../
:partialsDir: {rootDir}partials/
:imagesDir: {rootDir}images/
= Link Checker Plugin
:description: Validate links, as you type.
:keywords: url urls link linkchecker_service_url linkchecker_content_css
:title_nav: Link Checker

The `linkchecker` does what it says &ndash; validates URLs, as you type them. URLs considered invalid will be highlighted with red and will have a dedicated context menu with options to either edit the link, try and open it in a separate tab, remove the link, or ignore it.

[NOTE]
====
Please note that Link Checker is a *premium* plugin and relies on a server-side service, which is included as a part of a https://www.tinymce.com/pricing/[premium TinyMCE plugin] subscription.
====

[[cloud-instructions]]
== Cloud Instructions
anchor:cloudinstructions[historical anchor]

If you are using link:{baseurl}/cloud-deployment-guide/editor-and-features/[TinyMCE Cloud], simply add `"linkchecker"` to your plugins list, and the service will be automatically configured.

[[example]]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "linkchecker"
});
----

[[self-hosted-instructions]]
== Self-hosted Instructions
anchor:self-hostedinstructions[historical anchor]

Customers using a Self-hosted environment will need to provide a URL to their deployment of the link checking service via the `linkchecker_service_url` parameter

===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "linkchecker",
  linkchecker_service_url: "http://mydomain.com/linkchecker"
});
----

[[options]]
== Options

Link Checker has the following settings.

[[linkchecker_content_css]]
=== `linkchecker_content_css`

After a link is checked for validity, a result of the validation is added to it via `data-mce-linkchecker-status` attribute. There are three possible outcomes of the validation: `valid`, `invalid` and `unknown`. Link Checker visually reflects `invalid` outcome by injecting the following CSS styles into the editor:

[source,css]
----
a[data-mce-linkchecker-status="invalid"] {
    outline-color: rgba(231, 76, 60, 0.25);
    background-color: rgba(231, 76, 60, 0.25)
}

a[data-mce-linkchecker-focus="true"] {
    outline: 1px solid rgba(231, 76, 60, 0.75)
}
----

`data-mce-linkchecker-focus` attribute is set to _true_ every time a dedicated context menu is shown on a link. This only happens for `invalid` links.

It is possible to replace or extend those styles, by providing a URL to custom stylesheet via `linkchecker_content_css` option.

[[linkchecker_service_url]]
=== `linkchecker_service_url`

A URL of the server-side link validation service. This is required option, without it plugin will fail to operate and will throw a corresponding warning on the screen.

*Type:* `String`

===== Example

[source,js]
----
tinymce.init({
    selector: "textarea",
    plugins: "linkchecker",
    linkchecker_service_url: "http://mydomain.com/linkchecker"
});
----
