:rootDir: ../
:partialsDir: {rootDir}partials/
= PowerPaste Plugin
:keywords: enterprise powerpaste power paste powerpaste_word_import powerpaste_html_import powerpaste_block_drop powerpaste_allow_local_images microsoft word excel
:title_nav: PowerPaste

The TinyMCE *PowerPaste* plugin automatically cleans up content from Microsoft Word/Excel and HTML sources to ensure clean, compliant content that matches the look and feel of the site.

NOTE: Due to limitations in Excel online (part of Office Live) PowerPaste does not support pasting from Excel online.  If you paste content using Excel in Office Live you will get a plain text representation of the content.

[[usage]]
== Usage

The *PowerPaste* plugin activates automatically when users paste content into the editor. For basic usage, users are not required to take any action. Simply copy and paste content normally using keyboard shortcuts, the browser's "Paste" menu item (including from the context menu), or the TinyMCE "Paste" toolbar button.

To paste clipboard content as plain text, users can click the "Paste As Text" toolbar button and then paste the content normally. The TinyMCE *PowerPaste* plugin will convert the HTML on the clipboard into plain text.

If you configure *PowerPaste* to allow local images (see the `powerpaste_allow_local_images` setting below), then images copied from Microsoft Word and other sources will appear in TinyMCE as Base64 encoded images. You can have TinyMCE automatically upload Base64 encoded images for reverting back to a standard image as documented on the following page:

\{rootDir}advanced/handle-async-image-uploads/

NOTE: PowerPaste (when configured to allow local images) will import images from pasted Microsoft Word/Excel content.  When doing this, *PowerPaste* extracts Base64 encoded images from the clipboard.  Images larger than approximately 8.5MB may fail to import based on technical limitations of web browsers.

[[cloud-installation]]
== Cloud Installation
anchor:cloudinstallation[historical anchor]

To enable the TinyMCE *PowerPaste* plugin with link:{rootDir}cloud-deployment-guide/editor-and-features.html[TinyMCE Cloud]:

. If you are currently using the `paste` plugin provided with TinyMCE, disable it by removing it from the `plugins` list.
. Add `powerpaste` to the `plugins` list.

Example TinyMCE configuration:

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "powerpaste"
});
----

[[self-hosted-installation]]
== Self-hosted Installation
anchor:self-hostedinstallation[historical anchor]

To enable the TinyMCE *PowerPaste* plugin:

. If you are currently using the `paste` plugin provided with TinyMCE, disable it by removing it from the `plugins` list.
. Copy the entire `powerpaste` folder (found in the ZIP that you downloaded) into the `plugins` directory of your TinyMCE installation. This is typically `/tinymce/plugins`.
. Add `powerpaste` to the `plugins` list in  your TinyMCE configuration.

See the example TinyMCE configuration above.

[[using-the-powerpaste-plugin-with-module-loaders]]
== Using the PowerPaste Plugin with Module Loaders
anchor:usingthepowerpastepluginwithmoduleloaders[historical anchor]

To enable the *PowerPaste* plugin when using a link:{rootDir}advanced/usage-with-module-loaders.html[module loader], follow these instructions:

. Make the PowerPaste plugin folder available over http.
. Add the path to the PowerPaste plugin folder to the xref:configure/integration-and-setup.adoc#external_plugins[external plugins] option in `tinymce.init()`.

Example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  external_plugins: {
    'powerpaste': 'http://www.server.com/application/external_plugins/powerpaste/plugin.js'
  }
});
----

[[configuration-options]]
== Configuration Options
anchor:configurationoptions[historical anchor]

[[powerpaste_word_import]]
=== powerpaste_word_import

This setting controls how content being pasted from Microsoft Word is filtered. The supported values are:

* `clean` - Preserve the structure of the content such as headings, tables and lists but remove inline styles and classes. This results in simple content that uses the site's CSS stylesheet while retaining the semantic structure from the original document.
* `merge` - Preserve the inline formatting and structure of the original document. Invalid and proprietary styles, tags and attributes are still removed ensuring that the HTML is valid while more closely matching the original document formatting.
* `prompt` (Default) - Prompt the user to choose between the clean and merge options after attempting to paste word content.

NOTE: When using the Windows operating system, copying and pasting content from Word 2013 (or later) in "Protected View" will result in plain, unformatted text. This is due to how Protected View interacts with the clipboard.

[[powerpaste_html_import]]
=== powerpaste_html_import

This setting controls how content being pasted from sources other than Microsoft Word is filtered. Note that this includes content copied from TinyMCE itself. The supported values are:

* `clean` - (Default) - Preserve the structure of the content such as headings, tables, and lists but remove inline styles and classes. This results in simple content that uses the site's CSS stylesheet while retaining the semantic structure from the original document.
* `merge` Preserve the inline formatting and structure of the original document. Invalid and proprietary styles, tags and attributes are still removed ensuring that the HTML is valid while more closely matching the original document formatting.
* `prompt` - Prompt the user to choose between the clean and merge options after attempting to paste HTML content.

[[powerpaste_block_drop]]
=== powerpaste_block_drop

Due to browser limitations, it is not possible to filter content that is dragged and dropped into the editor. When powerpaste_block_drop is set to true the plugin will disable drag and dropping content into the editor. This prevents the unfiltered content from being introduced. Copy and paste is still enabled.

The default is `false`.

[[powerpaste_allow_local_images]]
=== powerpaste_allow_local_images

When set to true Base 64 encoded images using a data URI in the copied content will not be removed after pasting.

The default is `true`.

NOTE: If you configure_ *_PowerPaste_* _to allow local images you can have TinyMCE automatically upload Base64 encoded images for conversion back to a standard image as documented on the following page: \{rootDir}advanced/handle-async-image-uploads

[[example]]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "powerpaste",
  powerpaste_word_import: "clean",
  powerpaste_html_import: "merge"
});
----

[[toolbar-buttons]]
== Toolbar Buttons
anchor:toolbarbuttons[historical anchor]

[[pastetext]]
==== pastetext

This button allows you to toggle paste as plain text mode on/off. When in plain text mode all rich formatted contents gets converted into plain text.

Example TinyMCE Configuration:

[source,js]
----
tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  toolbar: "pastetext"
});
----

[[menu-items]]
== Menu Items
anchor:menuitems[historical anchor]

==== pastetext

This menu item allows you to toggle paste as plain text mode on/off. When in plain text mode all rich formatted contents gets converted into plain text.

Example TinyMCE Configuration:

[source,js]
----
tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  menu: {
	edit: {title: "edit", items: "pastetext"}
  }
});
----

[[advanced-config-options]]
== Advanced Config Options
anchor:advancedconfigoptions[historical anchor]

[[post-filter-callback]]
=== Post filter callback
anchor:postfiltercallback[historical anchor]

Developers can add customer filtering after *PowerPaste* filters are run using the post filter callback. This can be added as an init option or at runtime by adding the event listener.

[[using-the-init-option]]
===== Using the init option
anchor:usingtheinitoption[historical anchor]

[source,js]
----
tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  paste_postprocess: function(editor, fragment) {
	// Fragment is a DocumentFragment node containing the DOM structure of the pasted content,
	// after it has been filtered by the PowerPaste plugin.
  var textnode = document.createTextNode("Added Text");
  // Modify the fragment via the argument - do not return a value!
  fragment.node.appendChild(textnode);
  }
});
----

[[using-an-event-listener]]
===== Using an event listener
anchor:usinganeventlistener[historical anchor]

[source,js]
----
tinymce.get('editorID').('PastePostProcess', function(fragment) {
  // Fragment is a DocumentFragment node containing the DOM structure of the pasted content,
  // after it has been filtered by the PowerPaste plugin.
});
----

[[buy-tinymce-powerpaste]]
== Buy TinyMCE PowerPaste
anchor:buytinymcepowerpaste[historical anchor]

Start with our link:{tinymceproductsfeatures}powerpaste/[dedicated product page] to see our flexible pricing options. OEM and enterprise customers should link:{pricingpage}[contact sales directly].
