:rootDir: ./../
:partialsDir: {rootDir}partials/
= Implement TinyMCE in Ruby on Rails

In your RubyOnRails application you can just invoke TinyMCE xref:Installation.adoc[in the standard way], in the layout file, or just for the views in which you want to use TinyMCE. A good place for TinyMCE files may be `public/javascripts/tiny_mce` directory, but you are free to choose any other location.

The plugins listed below will just make this task even easier.

The most crucial thing to keep in mind is to include the TinyMCE javascript library before the scriptaculous library in your layout or view (see http://wiki.script.aculo.us/scriptaculous/show/tinymce[the scriptaculous wiki]). The best order seems to be:

. prototype.js
. tiny_mce.js
. scriptaculous.js
. tinyMCE.init({ ...options... })

[[tiny_mce-plugin]]
== tiny_mce plugin
anchor:tiny_mceplugin[historical anchor]

To integrate TinyMCE into a Ruby on Rails application, there is a http://github.com/kete/tiny_mce[tiny_mce] plugin originally created by Blake Watters, and maintained by KieranP. This plugin makes TinyMCE available to all textareas for the controllers and actions you choose. For an installation guide, see the README documentation of the plugin at http://github.com/kete/tiny_mce[\http://github.com/kete/tiny_mce] (hosted on Github). It includes full installation, upgrade, and configuration documentation that should get you started. If you have any questions or problems, please file a ticket at http://kete.lighthouseapp.com/projects/14744-tiny_mce/tickets[\http://kete.lighthouseapp.com/projects/14744-tiny_mce/tickets] and someone will help ASAP.

[[links]]
== Links

* http://github.com/kete/tiny_mce[Github hosting]
* http://kete.lighthouseapp.com/projects/14744-tiny_mce/tickets[Ticketing Support System]

[[tinymce_hammer-plugin]]
== tinymce_hammer plugin
anchor:tinymce_hammerplugin[historical anchor]

http://tinymcehammer.lanalot.com/[tinymce_hammer] is a Ruby on Rails plugin (requires Rails 2.3+) that provides

* Easy, simple installation and usage, provides form helpers and form builder methods
* Fast, provides a single combined javascript for loading TinyMCE javascript
* Flexible, provide lazy loading support

== Links

* http://tinymcehammer.lanalot.com/[Project Website (tutorials, downloads, etc)]
* http://github.com/trevorrowe/tinymce_hammer[Github hosting]
* http://groups.google.com/group/tinymce_hammer/topics[Mailing list]

[[see-also]]
== See also:
anchor:seealso[historical anchor]

* http://webonrails.com/2008/08/08/configuring-tinymce-spellchecker-with-rails-application/[Configure tinyMCE Spellcheck with rails app]
* Integrating TinyMCE with the http://www.ajaxscaffold.com/[ajaxscaffold generator], see http://blog.katipo.co.nz/?p=24[blog.katipo.co.nz] (possibly outdated)
* Although TinyMCE does some HTML sanitizing, it's not advisable to rely on that because it can be easily circumvented (remember, it's just a client-side script). Better use something like technoweenie's http://svn.techno-weenie.net/projects/plugins/white_list/[white_list plugin]. (possibly outdated)
* http://www.gusto.com/mike/blog/post202[spellchecking] (http://archive.tinymce.com/forum/viewtopic.php?id=5060[forum thread]) (Outdated)
* http://garbageburrito.com/home/tinymce_gzip_compressor_ruby_on_rails_plugin[GZip compressor] (http://archive.tinymce.com/forum/viewtopic.php?id=4765[forum thread]) (Outdated)
* http://dev.rubyonrails.org/ticket/5263[integration with scriptaculous's InPlaceEdit] (http://archive.tinymce.com/forum/viewtopic.php?id=3702[forum thread]) (Outdated)
