= TinyMCE 5.2.2
:description: Release notes for TinyMCE 5.2.2
:keywords: releasenotes bugfixes
:title_nav: TinyMCE 5.2.2

== Overview

{productname} 5.2.2 was released for {enterpriseversion} and {cloudname} on Thursday, April 30^th^, 2020.  It includes {productname} 5.2.2 and additional changes to premium plugins. These release notes provide an overview of the changes for {productname} 5.2.2, including:

* xref:generalbugfixes[General bug fixes]
* xref:securityfixes[Security fixes]
* xref:accompanyingpremiumpluginchanges[Accompanying Premium Plugin changes]
* xref:upgradingtothelatestversionoftinymce5[Upgrading to the latest version of TinyMCE 5]

include::partial$misc/releasenotes_for_stable.adoc[]

[[generalbugfixes]]
== General bug fixes

{productname} 5.2.2 provides fixes for the following bugs:

* Fixed an issue where anchors could not be inserted on empty lines.
* Fixed text decorations (underline, strikethrough) not consistently inheriting the text color.
* Fixed `format` menu alignment buttons inconsistently applying to images.
* Fixed the floating toolbar drawer height collapsing when the editor is rendered in modal dialogs or floating containers.

[[securityfixes]]
== Security fixes

{productname} 5.2.2 provides fixes for the following security issues:

* Fixed `media` embed content not processing safely in some cases.

[[accompanyingpremiumpluginchanges]]
== Accompanying Premium Plugin changes

The following premium plugins updates were released alongside {productname} 5.2.2.

=== PowerPaste 5.2.3

The {productname} 5.2.2 release includes an accompanying release of the *PowerPaste* premium plugin.

*PowerPaste* 5.2.3 provides a security fix to prevent arbitrary JavaScript from being executed on paste when using specifically crafted content. Replication case provided by Michał Bentkowski.

=== SpellChecker Pro 2.0.1

The {productname} 5.2.2 release includes an accompanying release of the *SpellChecker Pro* premium plugin.

*SpellChecker Pro* 2.0.1 provides a fixes for:

* The context menu being incorrectly positioned on a scrolled page in TinyMCE 4.
* An unhandled exception thrown when enabling spellchecking in inline mode for TinyMCE 4.

:enterprise: true

include::partial$install/upgrading-info.adoc[]

:enterprise: false
