= TinyMCE 5.0.3
:keywords: releasenotes newfeatures deleted technologypreview bugfixes knownissues
:title_nav: TinyMCE 5.0.3

== Overview

{productname} 5.0.3 was released for {enterpriseversion} and {cloudname} on Thursday, March 28^th^, 2019. It includes {productname} 5.0.3 and additional changes to premium plugins. The Release Notes provide high-level coverage of the improvements and additions that have been implemented in TinyMCE 5.0.3 and document known problems in this release, as well as notable bug fixes, deprecated functionality, and other details.

TinyMCE 5.0.3 release adds improvements to the TinyMCE editor to improve the overall user experience.

== New features

=== Case Change

TinyMCE 5.0.3 introduces the *Case Change* plugin that allows changing the case of text in block selection to uppercase, lowercase, or title case.

Currently, there are three types of formats available:

image::icons/change-case.svg[Case Change]

* *lowercase* - The *lowercase* option changes all the selected characters to lowercase.
* *UPPERCASE* - The *UPPERCASE* option changes all the selected characters to uppercase.
* *Title Case* - The *Title Case* option changes anything other than articles, coordinating conjunctions, or short prepositions to capital letters. The default rule set for *Title Case* is based on https://titlecaseconverter.com/rules/#WP[Wikipedia Title Case].

To try out *Case Change* start with this link:{plugindirectory}case-change[dedicated product page] to see all the flexible pricing options.

For more information on *Case Change* refer to the full xref:plugins/premium/casechange.adoc[documentation].

There is also a demo provided to explore the *Case Change* capabilities xref:demo/casechange.adoc[here].

=== TinyMCE for Swing integration

Users can easily configure the TinyMCE editor in Swing through the *TinyMCE for Swing* integration. TinyMCE for Swing is an integration of the TinyMCE web-based rich text editor into the Java Swing UI toolkit. A Java API is provided, allowing a developer to configure, instantiate and interact with TinyMCE as a Swing component.

==== Buy TinyMCE for Swing integration

To start using TinyMCE for Swing as your new rich text editor, the first step is to obtain a copy of the *Integration*.

Contact link:{contactpage}[customer support] to discuss pricing options for a customized TinyMCE for Swing integration for your specific use case.

For more information on *TinyMCE for Swing* refer to the full xref:integrations/swing.adoc[documentation].

Refer to this https://github.com/tinymce/tinymce-swing-codesamples[GitHub repo] for examples on how to use TinyMCE for Swing.

== Updates and enhancements

The new TinyMCE 5.0.3 editor comes with significant changes to the previous versions. Improved solutions have been introduced for unnecessary and obsolete configuration options. A comprehensive list of the updates and fixed issues is available in the xref:changelog.adoc#version503march192019[Changelog].
