= TinyMCE 5.7.1
:description: Release notes for TinyMCE 5.7.1
:keywords: releasenotes bugfixes
:title_nav: TinyMCE 5.7.1

== Overview

{productname} 5.7.1 was released for {enterpriseversion} and {cloudname} on Wednesday, March 24^th^, 2021. It includes {productname} 5.7.1 and additional changes to premium plugins. These release notes provide an overview of the changes for {productname} 5.7.1, including:

* xref:accompanyingpremiumpluginchanges[Accompanying Premium Plugin changes]
* xref:generalbugfixes[General bug fixes]
* xref:securityfixes[Security fixes]
* xref:upgradingtothelatestversionoftinymce5[Upgrading to the latest version of TinyMCE 5]

include::partial$misc/releasenotes_for_stable.adoc[]

[[accompanyingpremiumpluginchanges]]
== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} 5.7.1.

=== PowerPaste 5.4.2

The {productname} 5.7.1 release includes an accompanying release of the *PowerPaste* premium plugin.

*PowerPaste* 5.4.2 provides the following bug fixes:

* Fixed a security issue where dragging and dropping content wasn't correctly sanitized in some cases.

For information on the PowerPaste plugin, see: xref:plugins/premium/powerpaste.adoc[PowerPaste plugin].

[[generalbugfixes]]
== General bug fixes

{productname} 5.7.1 provides fixes for the following bugs:

* Fixed the `help` dialog incorrectly linking to the changelog of TinyMCE 4 instead of TinyMCE 5.
* Fixed a bug where error messages were displayed incorrectly in the image dialog.
* Fixed a bug where context menu items with names that contained uppercase characters were not displayed.
* Fixed context menu items lacking support for the `disabled` and `shortcut` properties.
* Fixed a regression where the width and height were incorrectly set when embedding content using the `media` dialog.

[[securityfixes]]
== Security fixes

{productname} 5.7.1 provides fixes for the following security issues.

Fixed an issue where URLs were not correctly filtered in some cases.

*PowerPaste* 5.4.2 fixes a security issue where dragging and dropping content wasn't correctly sanitized in some cases. Tiny Technologies would like to thank Maurice Dauer for discovering this vulnerability.

:enterprise: true

include::partial$install/upgrading-info.adoc[]

:enterprise: false
