= TinyMCE 5.1.4
:description: Release notes for TinyMCE 5.1.4
:keywords: releasenotes bugfixes
:title_nav: TinyMCE 5.1.4

== Overview

{productname} 5.1.4 was released for {enterpriseversion} and {cloudname} on Wednesday, December 18^th^, 2019. These release notes provide an overview of the changes for {productname} 5.1.4, including:

* xref:generalbugfixes[General bug fixes]
* xref:securityfixes[Security fixes]

include::partial$misc/releasenotes_for_stable.adoc[]

[[generalbugfixes]]
== General bug fixes

{productname} 5.1.4 provides fixes for the following bugs:

* The dialog contents disappearing when clicking a checkbox for right-to-left languages.
* The `legacyoutput` plugin registering legacy formats after editor initialization, causing legacy content to be stripped on the initial load.
* The search and replace plugin not cycling through results when searching using special characters.

[[securityfixes]]
== Security fixes

{productname} 5.1.4 provides fixes for the following security issues:

* The `visualchars` plugin converting HTML-like text to DOM elements in certain cases.
* The Paste plugin not sanitizing content in some cases.
* HTML comments incorrectly being parsed in certain cases.

:enterprise: true

include::partial$install/upgrading-info.adoc[]

:enterprise: false
