= TinyMCE 5.10.7
:description: Release notes for TinyMCE 5.10.7
:keywords: releasenotes bugfixes
:title_nav: TinyMCE 5.10.7

== Overview

{productname} 5.10.7 was released for {enterpriseversion} and {cloudname} on Wednesday, December 7^th^, 2022. It includes {productname} 5.10.7. These release notes provide an overview of the changes for {productname} 5.10.7, including:

* xref:securityfixes[Security fixes]
* xref:upgradingtothelatestversionoftinymce5[Upgrading to the latest version of TinyMCE 5]

include::partial$misc/releasenotes_for_stable.adoc[]

== Security fixes

{productname} 5.10.7 provides a fix for the following security issue:

=== A cross-site scripting (XSS) vulnerability was found in TinyMCE alerts

It was discovered that HTML being inserted into the DOM for presentation in TinyMCE alert and confirm dialogs was not being sanitized.

As a consequence, plugins that used the alert or confirm dialogs could be used to insert aribtrary JavaScript that would execute when an alert presented in the TinyMCE UI for the current user.

As of TinyMCE 5.10.7, HTML being provided to the DOM for presentation in TinyMCE alert and confirm dialogs is now sanitized before being added.

This sanitizing closes the XSS vulnerability.

CVE: [CVE-2022-23494](https://www.cve.org/CVERecord?id=CVE-2022-23494).

NOTE: Tiny Technologies would like to thank [P4rkJW](https://p4rkjw.com/) for discovering this vulnerability.

:enterprise: true

include::partial$install/upgrading-info.adoc[]

:enterprise: false