= Java Spring
:description: Java Spring
:keywords: tinydrive java spring
:title_nav: Java Spring

[#tiny-drive-java-spring-starter-project]
== Tiny Drive Java Spring Starter Project

This project will help you get started with {{site.cloudfilemanager}} and allow you to play around with its features.

[#requirements]
=== Requirements

Before you start your journey with {{site.cloudfilemanager}}, it will go a lot smoother if you have done these steps:
1. Login/register to link:{{site.accountpageurl}}/[{{site.accountpage}}]
2. Get a link:{{site.accountpageurl}}/key-manager/[{{site.cloudname}} API Key]
3. Get a link:{{site.accountpageurl}}/jwt/[JWT Key]

Store the keys temporarily somewhere as you will need to copy & paste them later.

[#prerequisites]
=== Prerequisites

Java 10+ and Gradle 4+

[#procedure]
=== Procedure

These are the steps needed to get this project running on your machine:

[#1-clone-this-repo-to-your-local-machine-using]
==== 1. Clone this repo to your local machine using

`
$ git clone git@github.com:tinymce/tinydrive-java-spring-starter.git
`

[#2-change-the-in]
==== 2. Change the `apiKey` in `tinydrive-java-spring-startersrc/main/resources/application.yml`

You get the api key from the `API Key Manager` {{site.accountpage}} page at \http://tiny.cloud.

[#3-create-a-file-containing-your-generated-private-rsa-key]
==== 3. Create a `tinydrive-java-spring-starter/src/main/resources/private.key` file containing your generated private RSA key

You get the private RSA key from the `JWT Key Manager` {{site.accountpage}} page at \http://tiny.cloud.

[#4-go-to-the-directory-and-install-npm-packages-and-then-start-the-dev-server]
==== 4. Go to the directory and install npm packages and then start the dev server

`
$ cd tinydrive-java-spring-starter
$ gradle bootRun
`

[#5-open-the-example-project-at-httplocalhost3000]
==== 5. Open the example project at \http://localhost:3000

[#implementing-with-your-system]
=== Implementing with your system

If your specific use case has not been covered by any of the sample link:{{site.baseurl}}/tinydrive/libraries/[starter projects], some customizations might be required to be applied to implement {{site.cloudfilemanager}} in the specific system. The link:{{site.baseurl}}/tinydrive/jwt-authentication/[JSON Web Token] authentication solution would have to be tied to the login authentication of your system. This usually means integrating the JWT authentication to the existing session authentication so that users automatically login to {{site.cloudfilemanager}} and your system.

[#additional-resources]
==== Additional resources

Go through the following additional resources to figure out how to configure {{site.cloudfilemanager}} with your system.

* We recommend reading up and trying to understand how link:{{site.baseurl}}/tinydrive/jwt-authentication/[JWT authentication] works. In order to implement {{site.cloudfilemanager}} you need prior knowledge of JWT in detail, including how they can be used for user authentication and session management in a web application. There will be some coding involved on both the client-side and the server-side to configure JWT as per the instructions in this section.
* link:{{site.baseurl}}/tinydrive/libraries/[Starter projects]
* link:{{site.baseurl}}/tinydrive/configuration/[Configuration Options]
* link:{{site.baseurl}}/tinydrive/integrations/[Integrations]

[#need-help]
== Need help?

We are striving to make {{site.cloudfilemanager}} as useful and as simple as possible. For support related issues such as problems with JWT authentication and implementing {{site.cloudfilemanager}}, check our link:{{site.baseurl}}/tinydrive/get-help/[help page] or please contact link:{{site.supporturl}}[{{site.supportname}}].
