= tinymce.html.Styles
:navtitle: tinymce.html.Styles
:description: This class is used to parse CSS styles it also compresses styles to reduce the output size.
:keywords: parse, serialize
:moxie-type: api

This class is used to parse CSS styles it also compresses styles to reduce the output size.

[[examples]]
== Examples
[source, javascript]
----
const Styles = tinymce.html.Styles({
  url_converter: (url) => {
    return url;
  }
});

styles = Styles.parse('border: 1px solid red');
styles.color = 'red';

console.log(tinymce.html.Styles().serialize(styles));
----

[[summary]]
== Summary

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#parse[parse()]|Parses the specified style value into an object collection. This parser will also
merge and remove any redundant items that browsers might have added. It will also convert non hex
colors to hex values. Urls inside the styles will also be converted to absolute/relative based on settings.|`xref:apis/tinymce.html.styles.adoc[Styles]`
|xref:#serialize[serialize()]|Serializes the specified style object into a string.|`xref:apis/tinymce.html.styles.adoc[Styles]`
|===

[[methods]]
== Methods

[[parse]]
=== parse()
[source, javascript]
----
parse(css: String): Object
----
Parses the specified style value into an object collection. This parser will also
merge and remove any redundant items that browsers might have added. It will also convert non hex
colors to hex values. Urls inside the styles will also be converted to absolute/relative based on settings.

==== Parameters

* `css (String)` - Style value to parse for example: border:1px solid red;.

==== Return value

* `Object` - Object representation of that style like {border: '1px solid red'}

'''

[[serialize]]
=== serialize()
[source, javascript]
----
serialize(styles: Object, elementName: String): String
----
Serializes the specified style object into a string.

==== Parameters

* `styles (Object)` - Object to serialize as string for example: {border: '1px solid red'}
* `elementName (String)` - Optional element name, if specified only the styles that matches the schema will be serialized.

==== Return value

* `String` - String representation of the style object for example: border: 1px solid red.

'''
