= tinymce.html.DomParser
:navtitle: tinymce.html.DomParser
:description: This class parses HTML code into a DOM like structure of nodes it will remove redundant whitespace and make sure that the node tree is valid according to the specified schema. So for example: &lt;p&gt;a&lt;p&gt;b&lt;/p&gt;c&lt;/p&gt; will become &lt;p&gt;a&lt;/p&gt;&lt;p&gt;b&lt;/p&gt;&lt;p&gt;c&lt;/p&gt;
:keywords: addAttributeFilter, addNodeFilter, filterNode, parse
:moxie-type: api

This class parses HTML code into a DOM like structure of nodes it will remove redundant whitespace and make sure that the node tree is valid according to the specified schema. So for example: <p>a<p>b</p>c</p> will become <p>a</p><p>b</p><p>c</p>

[[examples]]
== Examples
[source, javascript]
----
var parser = new tinymce.html.DomParser({validate: true}, schema);
var rootNode = parser.parse('<h1>content</h1>');
----

[[summary]]
== Summary

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#addAttributeFilter[addAttributeFilter()]|Adds a attribute filter function to the parser, the parser will collect nodes that has the specified attributes
and then execute the callback once it has finished parsing the document.|`xref:apis/tinymce.html.domparser.adoc[DomParser]`
|xref:#addNodeFilter[addNodeFilter()]|Adds a node filter function to the parser, the parser will collect the specified nodes by name
and then execute the callback once it has finished parsing the document.|`xref:apis/tinymce.html.domparser.adoc[DomParser]`
|xref:#filterNode[filterNode()]|Runs the specified node though the element and attributes filters.|`xref:apis/tinymce.html.domparser.adoc[DomParser]`
|xref:#parse[parse()]|Parses the specified HTML string into a DOM like node tree and returns the result.|`xref:apis/tinymce.html.domparser.adoc[DomParser]`
|===

[[methods]]
== Methods

[[addAttributeFilter]]
=== addAttributeFilter()
[source, javascript]
----
addAttributeFilter(name: String, callback: function)
----
Adds a attribute filter function to the parser, the parser will collect nodes that has the specified attributes
and then execute the callback once it has finished parsing the document.

==== Examples
[source, javascript]
----
parser.addAttributeFilter('src,href', function(nodes, name) {
 for (var i = 0; i < nodes.length; i++) {
  console.log(nodes[i].name);
 }
});
----

==== Parameters

* `name (String)` - Comma separated list of nodes to collect.
* `callback (function)` - Callback function to execute once it has collected nodes.

'''

[[addNodeFilter]]
=== addNodeFilter()
[source, javascript]
----
addNodeFilter(callback: function)
----
Adds a node filter function to the parser, the parser will collect the specified nodes by name
and then execute the callback once it has finished parsing the document.

==== Examples
[source, javascript]
----
parser.addNodeFilter('p,h1', function(nodes, name) {
 for (var i = 0; i < nodes.length; i++) {
  console.log(nodes[i].name);
 }
});
----

==== Parameters

* `callback (function)` - Callback function to execute once it has collected nodes.

'''

[[filterNode]]
=== filterNode()
[source, javascript]
----
filterNode(node: tinymce.html.Node): tinymce.html.Node
----
Runs the specified node though the element and attributes filters.

==== Parameters

* `node (xref:apis/tinymce.html.node.adoc[Node])` - the node to run filters on.

==== Return value

* `xref:apis/tinymce.html.node.adoc[Node]` - The passed in node.

'''

[[parse]]
=== parse()
[source, javascript]
----
parse(html: String, args: Object): tinymce.html.Node
----
Parses the specified HTML string into a DOM like node tree and returns the result.

==== Examples
[source, javascript]
----
var rootNode = new DomParser({...}).parse('<b>text</b>');
----

==== Parameters

* `html (String)` - Html string to sax parse.
* `args (Object)` - Optional args object that gets passed to all filter functions.

==== Return value

* `xref:apis/tinymce.html.node.adoc[Node]` - Root node containing the tree.

'''
