= tinymce.dom.Serializer
:navtitle: tinymce.dom.Serializer
:description: This class is used to serialize DOM trees into a string. Consult the TinyMCE API Documentation for more details and examples on how to use this class.
:keywords: addAttributeFilter, addNodeFilter, addRules, addTempAttr, getTempAttrs, schema, serialize, setRules
:moxie-type: api

This class is used to serialize DOM trees into a string. Consult the TinyMCE API Documentation for more details and examples on how to use this class.

[[summary]]
== Summary

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#addAttributeFilter[addAttributeFilter()]|Adds a attribute filter function to the parser used by the serializer, the parser will
collect nodes that has the specified attributes
and then execute the callback once it has finished parsing the document.|`xref:apis/tinymce.dom.serializer.adoc[Serializer]`
|xref:#addNodeFilter[addNodeFilter()]|Adds a node filter function to the parser used by the serializer, the parser will collect the specified nodes by name
and then execute the callback once it has finished parsing the document.|`xref:apis/tinymce.dom.serializer.adoc[Serializer]`
|xref:#addRules[addRules()]|Adds valid elements rules to the serializers schema instance this enables you to specify things
like what elements should be outputted and what attributes specific elements might have.
Consult the TinyMCE Documentation for more details on this format.|`xref:apis/tinymce.dom.serializer.adoc[Serializer]`
|xref:#addTempAttr[addTempAttr()]|Adds a temporary internal attribute these attributes will get removed on undo and
when getting contents out of the editor.|`xref:apis/tinymce.dom.serializer.adoc[Serializer]`
|xref:#getTempAttrs[getTempAttrs()]|Returns an array of all added temp attrs names.|`xref:apis/tinymce.dom.serializer.adoc[Serializer]`
|xref:#serialize[serialize()]|Serializes the specified browser DOM node into a HTML string.|`xref:apis/tinymce.dom.serializer.adoc[Serializer]`
|xref:#setRules[setRules()]|Sets the valid elements rules to the serializers schema instance this enables you to specify things
like what elements should be outputted and what attributes specific elements might have.
Consult the TinyMCE Documentation for more details on this format.|`xref:apis/tinymce.dom.serializer.adoc[Serializer]`
|===

[[methods]]
== Methods

[[addAttributeFilter]]
=== addAttributeFilter()
[source, javascript]
----
addAttributeFilter(callback: function)
----
Adds a attribute filter function to the parser used by the serializer, the parser will
collect nodes that has the specified attributes
and then execute the callback once it has finished parsing the document.

==== Examples
[source, javascript]
----
parser.addAttributeFilter('src,href', function(nodes, name) {
 for (var i = 0; i < nodes.length; i++) {
  console.log(nodes[i].name);
 }
});
----

==== Parameters

* `callback (function)` - Callback function to execute once it has collected nodes.

'''

[[addNodeFilter]]
=== addNodeFilter()
[source, javascript]
----
addNodeFilter(callback: function)
----
Adds a node filter function to the parser used by the serializer, the parser will collect the specified nodes by name
and then execute the callback once it has finished parsing the document.

==== Examples
[source, javascript]
----
parser.addNodeFilter('p,h1', function(nodes, name) {
 for (var i = 0; i < nodes.length; i++) {
  console.log(nodes[i].name);
 }
});
----

==== Parameters

* `callback (function)` - Callback function to execute once it has collected nodes.

'''

[[addRules]]
=== addRules()
[source, javascript]
----
addRules(rules: String)
----
Adds valid elements rules to the serializers schema instance this enables you to specify things
like what elements should be outputted and what attributes specific elements might have.
Consult the TinyMCE Documentation for more details on this format.

==== Parameters

* `rules (String)` - Valid elements rules string to add to schema.

'''

[[addTempAttr]]
=== addTempAttr()
[source, javascript]
----
addTempAttr(name: String)
----
Adds a temporary internal attribute these attributes will get removed on undo and
when getting contents out of the editor.

==== Parameters

* `name (String)` - string

'''

[[getTempAttrs]]
=== getTempAttrs()
[source, javascript]
----
getTempAttrs(): String[]
----
Returns an array of all added temp attrs names.

==== Return value

* `String[]` - Array with attribute names.

'''

[[serialize]]
=== serialize()
[source, javascript]
----
serialize(node: DOMNode, args: Object)
----
Serializes the specified browser DOM node into a HTML string.

==== Parameters

* `node (DOMNode)` - DOM node to serialize.
* `args (Object)` - Arguments option that gets passed to event handlers.

'''

[[setRules]]
=== setRules()
[source, javascript]
----
setRules(rules: String)
----
Sets the valid elements rules to the serializers schema instance this enables you to specify things
like what elements should be outputted and what attributes specific elements might have.
Consult the TinyMCE Documentation for more details on this format.

==== Parameters

* `rules (String)` - Valid elements rules string.

'''
