= tinymce.Env
:navtitle: tinymce.Env
:description: This class contains various environment constants like browser versions etc. Normally you don&#x27;t want to sniff specific browser versions but sometimes you have to when it&#x27;s impossible to feature detect. So use this with care.
:keywords: android, browser.current, browser.isChrome, browser.isEdge, browser.isFirefox, browser.isIE, browser.isOpera, browser.isSafari, browser.version, caretAfter, ceFalse, contentEditable, desktop, deviceType.isDesktop, deviceType.isPhone, deviceType.isTablet, deviceType.isTouch, deviceType.isWebView, deviceType.isiPad, deviceType.isiPhone, documentMode, experimentalShadowDom, fileApi, gecko, iOS, ie, mac, opera, os.current, os.isAndroid, os.isChromeOS, os.isFreeBSD, os.isLinux, os.isOSX, os.isSolaris, os.isWindows, os.isiOS, os.version, range, transparentSrc, webKit
:moxie-type: api

This class contains various environment constants like browser versions etc. Normally you don't want to sniff specific browser versions but sometimes you have to when it's impossible to feature detect. So use this with care.

[[summary]]
== Summary

[[properties]]
=== Properties
[cols="2,1,4,1",options="header"]
|===
|Name|Type|Summary|Defined by
|android|`Boolean`|Constant that is `true` if the operating system is android.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `os.isAndroid()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|browser.current|`String`|Returns the current browser name.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|browser.version|`Object`|Returns the current browser major and minor version.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|caretAfter|`Boolean`|Returns `true`/`false` if the browser can or can't place the caret after a inline block like an image.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - All supported browsers now support placing carets after inline blocks.|`xref:apis/tinymce.env.adoc[Env]`
|ceFalse|`Boolean`|Constant that is `true` if the browser supports `contentEditable=false` regions.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - All supported browsers now support `contentEditable=false` regions.|`xref:apis/tinymce.env.adoc[Env]`
|contentEditable|`Boolean`|Constant that is `true` if the browser supports editing.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - All supported browsers now support content editable elements.|`xref:apis/tinymce.env.adoc[Env]`
|desktop|`Boolean`|__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `deviceType.isDesktop()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|documentMode|`Number`|Returns the IE document mode. For non IE browsers, this will fake IE 10 document mode.|`xref:apis/tinymce.env.adoc[Env]`
|experimentalShadowDom|`Boolean`|__Deprecated in TinyMCE 5.5 and has been marked for removal in TinyMCE 6.0__ - if you need the original target of an event, please use `event.composedPath()`.|`xref:apis/tinymce.env.adoc[Env]`
|fileApi|`Boolean`|Constant that is `true` if the browser has a modern file API.


__Deprecated in TinyMCE 5.10 and has been marked for removal in TinyMCE 6.0__ - All supported browsers now support modern file APIs.|`xref:apis/tinymce.env.adoc[Env]`
|gecko|`Boolean`|Constant that is `true` if the browser is Gecko.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `browser.isFirefox()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|iOS|`Boolean`|Constant that is `true` if the operating system is iOS.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `os.isiOS()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|ie|`Number`|Constant that is greater than zero if the browser is IE.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `browser.version.major` and `browser.isIE()` or `browser.isEdge()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|mac|`Boolean`|Constant that is `true` if the operating system is Mac OS.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `os.isOSX()` or `os.isiOS()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|opera|`Boolean`|Constant that is `true` if the browser is Opera.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `browser.isOpera()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|os.current|`String`|Returns the current operating system name.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|os.version|`Object`|Returns the current operating system major and minor version.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|range|`Boolean`|Constant that is `true` if the browser supports native DOM Ranges. IE 9{plus}.


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - All supported browsers now support native DOM ranges.|`xref:apis/tinymce.env.adoc[Env]`
|transparentSrc|`Boolean`|Transparent image data url.|`xref:apis/tinymce.env.adoc[Env]`
|webKit|`Boolean`|Constant that is `true` if the browser is WebKit (Safari/Chrome).


__Deprecated in TinyMCE 5.1 and has been marked for removal in TinyMCE 6.0__ - Use `browser.isSafari()` or `browser.isChrome()` instead.|`xref:apis/tinymce.env.adoc[Env]`
|===

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#browser.isChrome[browser.isChrome()]|Returns `true` if the user's browser is Google Chrome.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#browser.isEdge[browser.isEdge()]|Returns `true` if the user's browser is Microsoft Edge.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#browser.isFirefox[browser.isFirefox()]|Returns `true` if the user's browser is Firefox.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#browser.isIE[browser.isIE()]|Returns `true` if the user's browser is Microsoft Internet Explorer.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#browser.isOpera[browser.isOpera()]|Returns `true` if the user's browser is Opera.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#browser.isSafari[browser.isSafari()]|Returns `true` if the user's browser is Safari.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#deviceType.isDesktop[deviceType.isDesktop()]|Returns `true` if the user's device is a desktop device.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#deviceType.isPhone[deviceType.isPhone()]|Returns `true` if the user's device is a phone.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#deviceType.isTablet[deviceType.isTablet()]|Returns `true` if the user's device is a tablet.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#deviceType.isTouch[deviceType.isTouch()]|Returns `true` if the user's device is a touch device.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#deviceType.isWebView[deviceType.isWebView()]|Returns `true` if the user's device is a WebView device.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#deviceType.isiPad[deviceType.isiPad()]|Returns `true` if the user's device is an iPad.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#deviceType.isiPhone[deviceType.isiPhone()]|Returns `true` if the user's device is an iPhone.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isAndroid[os.isAndroid()]|Returns `true` if the user's operating system is Android.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isChromeOS[os.isChromeOS()]|Returns `true` if the user's operating system is ChromeOS.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isFreeBSD[os.isFreeBSD()]|Returns `true` if the user's operating system is FreeBSD.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isLinux[os.isLinux()]|Returns `true` if the user's operating system is Linux.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isOSX[os.isOSX()]|Returns `true` if the user's operating system is Mac OS X.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isSolaris[os.isSolaris()]|Returns `true` if the user's operating system is Solaris.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isWindows[os.isWindows()]|Returns `true` if the user's operating system is Microsoft Windows.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|xref:#os.isiOS[os.isiOS()]|Returns `true` if the user's operating system is iOS.


__Added in TinyMCE 5.1__|`xref:apis/tinymce.env.adoc[Env]`
|===

[[methods]]
== Methods

[[browser.isChrome]]
=== browser.isChrome()
[source, javascript]
----
browser.isChrome(): Boolean
----
Returns `true` if the user's browser is Google Chrome.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's browser is Google Chrome.

'''

[[browser.isEdge]]
=== browser.isEdge()
[source, javascript]
----
browser.isEdge(): Boolean
----
Returns `true` if the user's browser is Microsoft Edge.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's browser is Microsoft Edge.

'''

[[browser.isFirefox]]
=== browser.isFirefox()
[source, javascript]
----
browser.isFirefox(): Boolean
----
Returns `true` if the user's browser is Firefox.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's browser is Firefox.

'''

[[browser.isIE]]
=== browser.isIE()
[source, javascript]
----
browser.isIE(): Boolean
----
Returns `true` if the user's browser is Microsoft Internet Explorer.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's browser is Microsoft Internet Explorer.

'''

[[browser.isOpera]]
=== browser.isOpera()
[source, javascript]
----
browser.isOpera(): Boolean
----
Returns `true` if the user's browser is Opera.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's browser is Opera.

'''

[[browser.isSafari]]
=== browser.isSafari()
[source, javascript]
----
browser.isSafari(): Boolean
----
Returns `true` if the user's browser is Safari.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's browser is Safari.

'''

[[deviceType.isDesktop]]
=== deviceType.isDesktop()
[source, javascript]
----
deviceType.isDesktop(): Boolean
----
Returns `true` if the user's device is a desktop device.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's device is a desktop device.

'''

[[deviceType.isPhone]]
=== deviceType.isPhone()
[source, javascript]
----
deviceType.isPhone(): Boolean
----
Returns `true` if the user's device is a phone.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's device is a phone.

'''

[[deviceType.isTablet]]
=== deviceType.isTablet()
[source, javascript]
----
deviceType.isTablet(): Boolean
----
Returns `true` if the user's device is a tablet.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's device is a tablet.

'''

[[deviceType.isTouch]]
=== deviceType.isTouch()
[source, javascript]
----
deviceType.isTouch(): Boolean
----
Returns `true` if the user's device is a touch device.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's device is a touch device.

'''

[[deviceType.isWebView]]
=== deviceType.isWebView()
[source, javascript]
----
deviceType.isWebView(): Boolean
----
Returns `true` if the user's device is a WebView device.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's device is a WebView device.

'''

[[deviceType.isiPad]]
=== deviceType.isiPad()
[source, javascript]
----
deviceType.isiPad(): Boolean
----
Returns `true` if the user's device is an iPad.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's device is an iPad.

'''

[[deviceType.isiPhone]]
=== deviceType.isiPhone()
[source, javascript]
----
deviceType.isiPhone(): Boolean
----
Returns `true` if the user's device is an iPhone.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's device is an iPhone.

'''

[[os.isAndroid]]
=== os.isAndroid()
[source, javascript]
----
os.isAndroid(): Boolean
----
Returns `true` if the user's operating system is Android.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is Android.

'''

[[os.isChromeOS]]
=== os.isChromeOS()
[source, javascript]
----
os.isChromeOS(): Boolean
----
Returns `true` if the user's operating system is ChromeOS.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is ChromeOS.

'''

[[os.isFreeBSD]]
=== os.isFreeBSD()
[source, javascript]
----
os.isFreeBSD(): Boolean
----
Returns `true` if the user's operating system is FreeBSD.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is FreeBSD.

'''

[[os.isLinux]]
=== os.isLinux()
[source, javascript]
----
os.isLinux(): Boolean
----
Returns `true` if the user's operating system is Linux.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is Linux.

'''

[[os.isOSX]]
=== os.isOSX()
[source, javascript]
----
os.isOSX(): Boolean
----
Returns `true` if the user's operating system is Mac OS X.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is Mac OS X.

'''

[[os.isSolaris]]
=== os.isSolaris()
[source, javascript]
----
os.isSolaris(): Boolean
----
Returns `true` if the user's operating system is Solaris.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is Solaris.

'''

[[os.isWindows]]
=== os.isWindows()
[source, javascript]
----
os.isWindows(): Boolean
----
Returns `true` if the user's operating system is Microsoft Windows.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is Microsoft Windows.

'''

[[os.isiOS]]
=== os.isiOS()
[source, javascript]
----
os.isiOS(): Boolean
----
Returns `true` if the user's operating system is iOS.


__Added in TinyMCE 5.1__

==== Return value

* `Boolean` - Returns `true` if the user's operating system is iOS.

'''
