= tinymce.util.Tools
:navtitle: tinymce.util.Tools
:description: This class contains various utlity functions. These are also exposed directly on the tinymce namespace.
:keywords: each, explode, grep, hasOwnProperty, inArray, is, isArray, makeMap, map, resolve, toArray, trim, walk
:moxie-type: api

This class contains various utlity functions. These are also exposed directly on the tinymce namespace.

[[summary]]
== Summary

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#each[each()]|Performs an iteration of all items in a collection such as an object or array. This method will execute the
callback function for each item in the collection, if the callback returns false the iteration will terminate.
The callback has the following format: `cb(value, key_or_index)`.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#explode[explode()]|Splits a string but removes the whitespace before and after each value.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#grep[grep()]|Filters out items from the input array by calling the specified function for each item.
If the function returns false the item will be excluded if it returns true it will be included.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#hasOwnProperty[hasOwnProperty()]|JavaScript does not protect hasOwnProperty method, so it is possible to overwrite it. This is
an object independent version.
Checks if the input object `obj` has the property `prop`.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#inArray[inArray()]|Returns an index of the item or -1 if item is not present in the array.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#is[is()]|Checks if a object is of a specific type for example an array.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#isArray[isArray()]|Returns true/false if the object is an array or not.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#makeMap[makeMap()]|Makes a name/object map out of an array with names.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#map[map()]|Creates a new array by the return value of each iteration function call. This enables you to convert
one array list into another.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#resolve[resolve()]|Resolves a string and returns the object from a specific structure.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#toArray[toArray()]|Converts the specified object into a real JavaScript array.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#trim[trim()]|Removes whitespace from the beginning and end of a string.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|xref:#walk[walk()]|Executed the specified function for each item in a object tree.|`xref:apis/tinymce.util.tools.adoc[Tools]`
|===

[[methods]]
== Methods

[[each]]
=== each()
[source, javascript]
----
each(o: Object, cb: Function, s: Object)
----
Performs an iteration of all items in a collection such as an object or array. This method will execute the
callback function for each item in the collection, if the callback returns false the iteration will terminate.
The callback has the following format: `cb(value, key_or_index)`.

==== Examples
[source, javascript]
----
// Iterate an array
tinymce.each([ 1,2,3 ], (v, i) => {
  console.debug("Value: " + v + ", Index: " + i);
});

// Iterate an object
tinymce.each({ a: 1, b: 2, c: 3 }, (v, k) => {
  console.debug("Value: " + v + ", Key: " + k);
});
----

==== Parameters

* `o (Object)` - Collection to iterate.
* `cb (Function)` - Callback function to execute for each item.
* `s (Object)` - Optional scope to execute the callback in.

'''

[[explode]]
=== explode()
[source, javascript]
----
explode(s: String, d: String)
----
Splits a string but removes the whitespace before and after each value.

==== Examples
[source, javascript]
----
// Split a string into an array with a,b,c
const arr = tinymce.explode('a, b,   c');
----

==== Parameters

* `s (String)` - String to split.
* `d (String)` - Delimiter to split by.

'''

[[grep]]
=== grep()
[source, javascript]
----
grep(a: Array, f: Function): Array
----
Filters out items from the input array by calling the specified function for each item.
If the function returns false the item will be excluded if it returns true it will be included.

==== Examples
[source, javascript]
----
// Filter out some items, this will return an array with 4 and 5
const items = tinymce.grep([ 1,2,3,4,5 ], (v) => v > 3);
----

==== Parameters

* `a (Array)` - Array of items to loop though.
* `f (Function)` - Function to call for each item. Include/exclude depends on it's return value.

==== Return value

* `Array` - New array with values imported and filtered based in input.

'''

[[hasOwnProperty]]
=== hasOwnProperty()
[source, javascript]
----
hasOwnProperty(obj: Object, prop: String): Boolean
----
JavaScript does not protect hasOwnProperty method, so it is possible to overwrite it. This is
an object independent version.
Checks if the input object `obj` has the property `prop`.

==== Parameters

* `obj (Object)` - Object to check if the property exists.
* `prop (String)` - Name of a property on the object.

==== Return value

* `Boolean` - true if the object has the specified property.

'''

[[inArray]]
=== inArray()
[source, javascript]
----
inArray(item: any, arr: Array): Number
----
Returns an index of the item or -1 if item is not present in the array.

==== Parameters

* `item (any)` - Item to search for.
* `arr (Array)` - Array to search in.

==== Return value

* `Number` - index of the item or -1 if item was not found.

'''

[[is]]
=== is()
[source, javascript]
----
is(obj: Object, type: String): Boolean
----
Checks if a object is of a specific type for example an array.

==== Parameters

* `obj (Object)` - Object to check type of.
* `type (String)` - Optional type to check for.

==== Return value

* `Boolean` - true/false if the object is of the specified type.

'''

[[isArray]]
=== isArray()
[source, javascript]
----
isArray(obj: Object): Boolean
----
Returns true/false if the object is an array or not.

==== Parameters

* `obj (Object)` - Object to check.

==== Return value

* `Boolean` - true/false state if the object is an array or not.

'''

[[makeMap]]
=== makeMap()
[source, javascript]
----
makeMap(items: Array | String, delim: String, map: Object): Object
----
Makes a name/object map out of an array with names.

==== Parameters

* `items (Array | String)` - Items to make map out of.
* `delim (String)` - Optional delimiter to split string by.
* `map (Object)` - Optional map to add items to.

==== Return value

* `Object` - Name/value map of items.

'''

[[map]]
=== map()
[source, javascript]
----
map(array: Array, callback: Function): Array
----
Creates a new array by the return value of each iteration function call. This enables you to convert
one array list into another.

==== Parameters

* `array (Array)` - Array of items to iterate.
* `callback (Function)` - Function to call for each item. It's return value will be the new value.

==== Return value

* `Array` - Array with new values based on function return values.

'''

[[resolve]]
=== resolve()
[source, javascript]
----
resolve(n: String, o: Object): Object
----
Resolves a string and returns the object from a specific structure.

==== Examples
[source, javascript]
----
// Resolve a path into an object reference
const obj = tinymce.resolve('a.b.c.d');
----

==== Parameters

* `n (String)` - Path to resolve for example a.b.c.d.
* `o (Object)` - Optional object to search though, defaults to window.

==== Return value

* `Object` - Last object in path or null if it couldn't be resolved.

'''

[[toArray]]
=== toArray()
[source, javascript]
----
toArray(obj: Object): Array
----
Converts the specified object into a real JavaScript array.

==== Parameters

* `obj (Object)` - Object to convert into array.

==== Return value

* `Array` - Array object based in input.

'''

[[trim]]
=== trim()
[source, javascript]
----
trim(s: String): String
----
Removes whitespace from the beginning and end of a string.

==== Parameters

* `s (String)` - String to remove whitespace from.

==== Return value

* `String` - New string with removed whitespace.

'''

[[walk]]
=== walk()
[source, javascript]
----
walk(o: Object, f: Function, n: String, s: String)
----
Executed the specified function for each item in a object tree.

==== Parameters

* `o (Object)` - Object tree to walk though.
* `f (Function)` - Function to call for each item.
* `n (String)` - Optional name of collection inside the objects to walk for example childNodes.
* `s (String)` - Optional scope to execute the function in.

'''
