= tinymce.util.Delay
:navtitle: tinymce.util.Delay
:description: Utility class for working with delayed actions like setTimeout.
:keywords: setEditorInterval, setEditorTimeout
:moxie-type: api

Utility class for working with delayed actions like setTimeout.

[[summary]]
== Summary

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#setEditorInterval[setEditorInterval()]|Sets an interval timer that's similar to native browser link:https://developer.mozilla.org/en-US/docs/Web/API/setInterval[setInterval]
API, except that it checks if the editor instance is still alive when the callback gets executed.|`xref:apis/tinymce.util.delay.adoc[Delay]`
|xref:#setEditorTimeout[setEditorTimeout()]|Sets a timeout that's similar to the native browser link:https://developer.mozilla.org/en-US/docs/Web/API/setTimeout[setTimeout]
API, except that it checks if the editor instance is still alive when the callback gets executed.|`xref:apis/tinymce.util.delay.adoc[Delay]`
|===

[[methods]]
== Methods

[[setEditorInterval]]
=== setEditorInterval()
[source, javascript]
----
setEditorInterval(callback: Function, time: Number): Number
----
Sets an interval timer that's similar to native browser link:https://developer.mozilla.org/en-US/docs/Web/API/setInterval[setInterval]
API, except that it checks if the editor instance is still alive when the callback gets executed.

==== Parameters

* `callback (Function)` - Callback to execute when interval time runs out.
* `time (Number)` - Optional time to wait before the callback is executed, defaults to 0.

==== Return value

* `Number` - Timeout id number.

'''

[[setEditorTimeout]]
=== setEditorTimeout()
[source, javascript]
----
setEditorTimeout(editor: tinymce.Editor, callback: Function, time: Number): Number
----
Sets a timeout that's similar to the native browser link:https://developer.mozilla.org/en-US/docs/Web/API/setTimeout[setTimeout]
API, except that it checks if the editor instance is still alive when the callback gets executed.

==== Parameters

* `editor (xref:apis/tinymce.editor.adoc[Editor])` - Editor instance to check the removed state on.
* `callback (Function)` - Callback to execute when timer runs out.
* `time (Number)` - Optional time to wait before the callback is executed, defaults to 0.

==== Return value

* `Number` - Timeout id number.

'''
