= tinymce.util.ImageUploader
:navtitle: tinymce.util.ImageUploader
:description: This class handles uploading images to a back-end server.
:keywords: upload
:moxie-type: api

This class handles uploading images to a back-end server.

**Added in TinyMCE 5.7.**

[[summary]]
== Summary

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#upload[upload()]|Uploads images to the configured image upload URL (`images_upload_url`) or passes the images to the defined image upload handler function (`images_upload_handler`).|`xref:apis/tinymce.util.imageuploader.adoc[ImageUploader]`
|===

[[methods]]
== Methods

[[upload]]
=== upload()
[source, javascript]
----
upload(blobInfos: Array, showNotification: boolean)
----
Uploads images to the configured image upload URL (`images_upload_url`) or passes the images to the defined image upload handler function (`images_upload_handler`).

==== Parameters

* `blobInfos (Array)` - A BlobInfo array containing the image data to upload. A BlobInfo can be created by calling `editor.editorUpload.blobCache.create()`.
* `showNotification (boolean)` - (Optional) When set to true, a notification with a progress bar will be shown during image uploads.

'''
