= tinymce.WindowManager
:navtitle: tinymce.WindowManager
:description: This class handles the creation of native windows and dialogs. This class can be extended to provide for example inline dialogs.
:keywords: alert, close, confirm, open, openUrl
:moxie-type: api

This class handles the creation of native windows and dialogs. This class can be extended to provide for example inline dialogs.

[[examples]]
== Examples
[source, javascript]
----
// Opens a new dialog with the file.htm file and the size 320x240
tinymce.activeEditor.windowManager.openUrl({
  title: 'Custom Dialog',
  url: 'file.htm',
  width: 320,
  height: 240
});

// Displays an alert box using the active editor’s window manager instance
tinymce.activeEditor.windowManager.alert('Hello world!');

// Displays a confirm box. An alert message will display depending on what is chosen in the confirm box.
tinymce.activeEditor.windowManager.confirm('Do you want to do something?', (state) => {
  const message = state ? 'Ok' : 'Cancel';
  tinymce.activeEditor.windowManager.alert(message);
});
----

[[summary]]
== Summary

[[methods-summary]]
=== Methods
[cols="2,5,1",options="header"]
|===
|Name|Summary|Defined by
|xref:#alert[alert()]|Creates an alert dialog. Do not use the blocking behavior of this
native version. Use the callback method instead; then it can be extended.|`xref:apis/tinymce.windowmanager.adoc[WindowManager]`
|xref:#close[close()]|Closes the top most window.|`xref:apis/tinymce.windowmanager.adoc[WindowManager]`
|xref:#confirm[confirm()]|Creates an alert dialog. Do not use the blocking behavior of this
native version. Use the callback method instead; then it can be extended.|`xref:apis/tinymce.windowmanager.adoc[WindowManager]`
|xref:#open[open()]|Opens a new window.|`xref:apis/tinymce.windowmanager.adoc[WindowManager]`
|xref:#openUrl[openUrl()]|Opens a new window for the specified url.|`xref:apis/tinymce.windowmanager.adoc[WindowManager]`
|===

[[methods]]
== Methods

[[alert]]
=== alert()
[source, javascript]
----
alert(message: String, callback: Function, scope: Object)
----
Creates an alert dialog. Do not use the blocking behavior of this
native version. Use the callback method instead; then it can be extended.

==== Examples
[source, javascript]
----
// Displays an alert box using the active editors window manager instance
tinymce.activeEditor.windowManager.alert('Hello world!');
----

==== Parameters

* `message (String)` - Text to display in the new alert dialog.
* `callback (Function)` - (Optional) Callback function to be executed after the user has selected ok.
* `scope (Object)` - (Optional) Scope to execute the callback in.

'''

[[close]]
=== close()
[source, javascript]
----
close()
----
Closes the top most window.

'''

[[confirm]]
=== confirm()
[source, javascript]
----
confirm(message: String, callback: Function, scope: Object)
----
Creates an alert dialog. Do not use the blocking behavior of this
native version. Use the callback method instead; then it can be extended.

==== Examples
[source, javascript]
----
// Displays a confirm box and an alert message will be displayed depending on what you choose in the confirm
tinymce.activeEditor.windowManager.confirm('Do you want to do something?', (state) => {
  const message = state ? 'Ok' : 'Cancel';
  tinymce.activeEditor.windowManager.alert(message);
});
----

==== Parameters

* `message (String)` - Text to display in the new confirm dialog.
* `callback (Function)` - (Optional) Callback function to be executed after the user has selected ok or cancel.
* `scope (Object)` - (Optional) Scope to execute the callback in.

'''

[[open]]
=== open()
[source, javascript]
----
open(config: Object, params: Object): WindowManager.DialogInstanceApi
----
Opens a new window.

==== Parameters

* `config (Object)` - For information on the available options, see: link:https://www.tiny.cloud/docs/tinymce/6/dialog-configuration/#options[Dialog - Configuration options].
* `params (Object)` - (Optional) For information on the available options, see: link:https://www.tiny.cloud/docs/tinymce/6/dialog-configuration/#configuration-parameters[Dialog - Configuration parameters].

==== Return value

* `WindowManager.DialogInstanceApi` - A new dialog instance.

'''

[[openUrl]]
=== openUrl()
[source, javascript]
----
openUrl(config: Object): WindowManager.UrlDialogInstanceApi
----
Opens a new window for the specified url.

==== Parameters

* `config (Object)` - For information on the available options, see: link:https://www.tiny.cloud/docs/tinymce/6/urldialog/#configuration[URL dialog - Configuration].

==== Return value

* `WindowManager.UrlDialogInstanceApi` - A new URL dialog instance.

'''
