:modulesDir: ../
:partialsDir: {modulesDir}partials/
:imagesDir: {modulesDir}images/
include::{modulesDir}_attributes.adoc[]
= Cloud deployment of plugins Only
:description: Connect to Tiny Cloud within a hybrid deployment.
:description_short: Learn how to setup TinyMCE Plugins via the Tiny Cloud.
:keywords: tinymce cloud script textarea apiKey hybrid

A hybrid deployment of {cloudname} allows the loading of premium plugins in a self-hosted environment. Download and install the link:{gettiny}[{productname} Community edition] to get started.

Sign up for a free API key provides entitlements to premium link:{modulesDir}/plugins/imagetools/[Image Tools] plugin. A {cloudname} image proxy server must already be configured. Premium plugins can be purchased at any time once the API key has been set up.

[#step-1-insert-the-custom-script-tag-into-the-webpage]
== Step 1: Insert the custom script tag into the webpage

Add the following script in the webpage once the script tag to load {productname} has been specified. Be sure to substitute 'no-api-key' with your api key.

[source,js]
----
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js" referrerpolicy="origin"></script>
----

[#step-2-specify-purchased-tinymce-plugins-and-toolbar-buttons]
== Step 2: Specify purchased TinyMCE plugins and toolbar buttons

Extend the link:{modulesDir}/configure/[{productname} configuration] to include any additional purchased plugins and associated toolbar and menu items. Refer to the following enablement guides for more information:

* link:{modulesDir}/plugins/mentions/[Mentions]
* link:{modulesDir}/plugins/drive/[{cloudfilemanager}]
* link:{modulesDir}/plugins/comments/[Comments 2.0]
* link:{modulesDir}/plugins/pageembed/[Page Embed]
* link:{modulesDir}/plugins/permanentpen/[Permanent Pen]
* link:{modulesDir}/plugins/formatpainter/[Format Painter]
* link:{modulesDir}/plugins/powerpaste/[PowerPaste]
* link:{modulesDir}/plugins/tinymcespellchecker/[Spell Checker Pro]

NOTE: `spellchecker_rpc_url` is *not* required when enabling this plugin via link:{modulesDir}/cloud-deployment-guide/[{cloudname}].

* link:{modulesDir}/plugins/imagetools/[Image Tools (with configured image proxy)]

NOTE: Configuration of the `imagetools_cors_hosts` and `imagetools_proxy` properties occurrs automatically.

* link:{modulesDir}/plugins/moxiemanager/[Moxie Manager]
* link:{modulesDir}/plugins/a11ychecker/[Accessibility Checker]
* link:{modulesDir}/plugins/advcode/[Advanced Code Editor]
* link:{modulesDir}/plugins/mediaembed/[Enhanced Media Embed]
* link:{modulesDir}/plugins/linkchecker/[Link Checker]

NOTE: It may take up to 30 minutes for the purchased plugin to be available to {productname}. Clear the browser's cache.

The following is a complete example:

The example below has the following:

* The {cloudname} `API key` has the value _TEST_API_KEY_.
* The {cloudname} has the link:{modulesDir}/plugins/tinymcespellchecker/[Spell Checker Pro] plugin enabled.

[source,js]
----
<html>
   <head>
      <script src="https://your_server/tinymce.min.js"></script>
      <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/plugins.min.js" referrerpolicy="origin"></script>
   </head>
   <body>
      <textarea><p>test textarea</p></textarea>
      <script>
         tinymce.init({
            selector: 'textarea',
            height: 500,
            plugins: [
               'advlist autolink lists link image charmap print preview hr anchor pagebreak',
               'tinymcespellchecker']
         });
      </script>
   </body>
<html>
----

[#step-3-forward-proxy-configuration]
== Step 3: Forward proxy configuration

Ensure that the following URLs are accessible via this proxy if the network has a forward proxy that controls access to the internet.

* All URLs where the editor is deployed.
* All URLs where the plugins are deployed.
* \https://imageproxy.tiny.cloud
* \https://hyperlinking.tiny.cloud
* \https://spelling.tiny.cloud

Ensure the `tiny-api-key` and `tinymce-api-key` headers are retained while requesting the list of above URLs.
