:rootDir: ../
:partialsDir: {rootDir}partials/
= Migrate from 3.x
:description: Everything you need to start migrating from 3.x to 4 and beyond.
:description_short: Everything you need to start migrating from 3.x to 4 and beyond.
:keywords: migrate migration 3x themes event handling new removed
:title_nav: Migrate from 3.x

* <<filestructure,File structure>>
* <<removedplugins,Removed plugins>>
* <<newplugins,New plugins>>
* <<removedthemes,Removed themes>>
* <<newthemes,New themes>>
* <<eventhandling,Event handling>>
* <<userinterface,User interface>>
* <<controlstates,Control states>>
* <<dialogswindows,Dialogs/Windows>>
* <<html5output,HTML5 output>>
* <<usingthecompat3xplugin,Using the compat3x plugin>>

[[file-structure]]
== File structure
anchor:filestructure[historical anchor]

The file structure was changed in the 4.0 release to more closely match other JavaScript projects. All minified files are suffixed with `.min.js` and `editor_plugin` and `editor_theme` was replaced with `plugin` and `theme`.

----
/tiny_mce/tiny_mce.js -> /tinymce/tinymce.min.js
/tiny_mce/tiny_mce_src.js -> /tinymce/tinymce.js
/tiny_mce/plugins/<plugin>/editor_plugin.js -> /tinymce/plugins/<plugin>/plugin.min.js
/tiny_mce/plugins/<plugin>/editor_plugin_src.js -> /tinymce/plugins/<plugin>/plugin.js
/tiny_mce/theme/<plugin>/editor_template.js -> /tinymce/plugins/<plugin>/theme.min.js
/tiny_mce/theme/<plugin>/editor_template_src.js -> /tinymce/plugins/<plugin>/theme.js
----

[[removed-plugins]]
== Removed plugins
anchor:removedplugins[historical anchor]

These plugins where removed in 4.0: http://archive.tinymce.com/wiki.php/Plugin3x:advhr[advhr], http://archive.tinymce.com/wiki.php/Plugin3x:advimage[advimage], http://archive.tinymce.com/wiki.php/Plugin3x:advlink[advlink], http://archive.tinymce.com/wiki.php/Plugin3x:iespell[iespell], http://archive.tinymce.com/wiki.php/Plugin3x:inlinepopups[inlinepopups], http://archive.tinymce.com/wiki.php/Plugin3x:style[style], http://archive.tinymce.com/wiki.php/Plugin3x:emotions[emotions] and http://archive.tinymce.com/wiki.php/Plugin3x:xhtmlxtras[xhtmlxtras].

[[new-plugins]]
== New plugins
anchor:newplugins[historical anchor]

These are the new plugins in 4.0: link:{rootDir}plugins/anchor.html[anchor], link:{rootDir}plugins/charmap.html[charmap], link:{rootDir}plugins/compat3x.html[compat3x], link:{rootDir}plugins/hr.html[hr], link:{rootDir}plugins/image.html[image], link:{rootDir}plugins/link.html[link], link:{rootDir}plugins/emoticons.html[emoticons], link:{rootDir}plugins/code.html[code] and link:{rootDir}plugins/textcolor.html[textcolor].

[[removed-themes]]
== Removed themes
anchor:removedthemes[historical anchor]

The "simple" and "advanced" themes were removed in 4.0.

[[new-themes]]
== New themes
anchor:newthemes[historical anchor]

The new "modern" theme was introduced in 4.0. More themes will be added in the future.

[[event-handling]]
== Event handling
anchor:eventhandling[historical anchor]

TinyMCE 4.0 has a new way of binding events. Instead of the old dispatcher method, it uses the more common "on" and "off" like for example jQuery. It also allows you to bind multiple events and cancel events using the more common preventDefault and stopPropagation. Check the link:{rootDir}api/tinymce/tinymce.editor.html[API documentation] for a full list of events.

[source,js]
----
// Old event
editor.onInit(editor, args) {
    // Custom logic
});

// New event
editor.on('init', function(args) {
    // Custom logic
});
----

[[user-interface]]
== User interface
anchor:userinterface[historical anchor]

The user interface logic has been changed entirely in 4.0. Though the more straightforward methods of adding buttons and windows are the same, more complex controls or dialogs needs to be written in the new API style.

[[control-states]]
== Control states
anchor:controlstates[historical anchor]

Each control in TinyMCE 4 is supposed to be a self-contained unit. This enables controls to be created at multiple locations in the UI. So the old controlManager with fixed names has been removed.

[source,js]
----
// This is how control states used to function in the 3.x UI API
editor.onNodeChange.add(function(editor, controlManager, node) {
    controlManager.setActive('SomeButton', node.nodeName == 'A');
});
----

[source,js]
----
// In TinyMCE 4 you can use the simpler stateSelector setting
editor.addButton('SomeButton', {
    text: 'My button',
    stateSelector: 'a'
});

// Or you can use custom logic using the "nodechange" event
editor.addButton('SomeButton', {
    text: 'My button',
    onPostRender: function() {
        var ctrl = this;

     ed.on('NodeChange', function(e) {
         ctrl.active(e.element.nodeName == 'A');
     });
 } });
----

[[dialogswindows]]
== Dialogs/Windows

In TinyMCE 3.x all dialogs where HTML files loaded in iframes or separate windows. In 4.x all windows are DIV elements placed onto the same page as the editor. You can however still load pages into iframe based windows.

[source,js]
----
// Open URL based window
editor.windowManager.open({
    title: 'My dialog',
    width: 500,
    height: 400,
    url: 'somepage.html'
}, {
    someArg: 'someValue'
});
----

Here are some examples on how to extract parameters passed to windows and closing windows inside your "somepage.html" code.

[source,js]
----
// Get someArg value inside iframe dialog
var someArg = top.tinymce.activeEditor.windowManager.getParams().someArg;

// Close the top most window
top.tinymce.activeEditor.windowManager.close();
----

[[html5-output]]
== HTML5 output
anchor:html5output[historical anchor]

TinyMCE produces HTML5 loose output as of 4.0. This means it can handle all new HTML5 elements and also allow the deprecated HTML4 attributes and elements. If you want to use html4 or html5-strict output check the link:{rootDir}configure/content-filtering/#schema[schema] option for details.

[[using-the-compat3x-plugin]]
== Using the compat3x plugin
anchor:usingthecompat3xplugin[historical anchor]

As a last resort one can use the link:{rootDir}plugins/compat3x.html[compat3x plugin] it mimics parts of the 3.x API contains a few files removed from 4.x. We only recommend this as a last resort, and it won't work for all plugins. But most plugins should work right out of the box we tested it with some of our old 3.x plugins.
