[[content_langs]]
== `+content_langs+`

include::partial$configuration/content_langs_base.adoc[]

*Type:* `+Array+`

=== Example: using `+content_langs+` to change spelling dictionaries

The Spell Checker plugin will use the `+code+` property to determine which dictionary to use on the content, unless the `+customCode+` property is available. The language tag specified by `+customCode+` overrides the spelling dictionary, to allow for non-standard languages such as the medical dictionaries provided with Spell Checker. For all languages, ensure that:

* The `+code+` property is valid language tag, according to https://www.ietf.org/rfc/bcp/bcp47.txt[Tags for Identifying Languages (BCP47)]
* Either the `+code+` property is one of the xref:introduction-to-tiny-spellchecker.adoc#spellchecker_languages[Supported Languages] or the `+customCode+` override property is defined.
* The `+customCode+` property is one of the xref:introduction-to-tiny-spellchecker.adoc#spellchecker_languages[Supported Languages] if it is defined.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',
  toolbar: 'language',
  plugins: 'tinymcespellchecker',
  content_langs: [
    { title: 'Afrikaans (South Africa)', code: 'af-ZA', customCode: 'af-ZA' },
    { title: 'English (Australia)', code: 'en-AU' },
    { title: 'English (Canada)', code: 'en-CA' },
    { title: 'English (United Kingdom)', code: 'en-GB' },
    { title: 'English (United States)', code: 'en-US' },
    { title: 'Medical English (US)', code: 'en-US', customCode: 'en-US-medical' },
    { title: 'Medical English (UK)', code: 'en-GB', customCode: 'en-GB-medical' },
    { title: 'Danish', code: 'da' },
    { title: 'Dutch', code: 'nl-NL' },
    { title: 'Finnish', code: 'fi' },
    { title: 'French', code: 'fr' },
    { title: 'German', code: 'de-DE' },
    { title: 'Hungarian', code: 'hu' },
    { title: 'Italian', code: 'it-IT' },
    { title: 'Maori (New Zealand)', code: 'mi-NZ' },
    { title: 'Norwegian Bokmål', code: 'nb-NO' },
    { title: 'Norwegian Nynorsk', code: 'nn' },
    { title: 'Polish', code: 'pl' },
    { title: 'Portuguese (Brazil)', code: 'pt-BR' },
    { title: 'Portuguese (Portugal)', code: 'pt-PT' },
    { title: 'Spanish', code: 'es' },
    { title: 'Swedish', code: 'sv-SE' },
    { title: 'Swedish (Finland)', code: 'sv-FI' }
  ],
});
----