:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Case Change
:controls: toolbar button, menu item
:description: Change the case of text.
:keywords: case capitalization capitalize lowercase uppercase
:title_nav: Case Change

[[overview]]
== Overview

The *Case Change* plugin is a time saving and handy extension that allows changing the case of text in block selection to uppercase, lowercase, or title case.

[[types-of-formats]]
== Types of Formats

Currently, there are three types of formats available:

[[lowercase]]
=== lowercase

The *lowercase* option changes all the selected characters to lowercase.

[[uppercase]]
=== UPPERCASE

The *UPPERCASE* option changes all the selected characters to uppercase.

[[title-case]]
=== Title Case

The *Title Case* option changes anything other than articles, coordinating conjunctions, or short prepositions to capital letters. The default rule set for *Title Case* is based on https://titlecaseconverter.com/rules/#WP[Wikipedia Title Case].

The *Title Case* can be used for the following editor elements:

* Menu options and pushbuttons
* Field, checkbox, and radio button labels
* Frame, screen, and dialog box titles
* Tab descriptions
* All hierarchy nodes and folder names (IMG, roles, etc)
* Possible entries, options in drop-down lists
* Column and row headers
* Titles of reports and lists
* All technical short descriptions (names of programs, function groups, transactions, CUA statuses, and so on)

[[try-our-case-change-demo]]
== Try our Case Change demo

codepen::casechange[]

:pluginname: Case Change
:pluginminimumplan: tiertwo
:plugindocspage: casechange
include::{partialsDir}misc/purchase-premium-plugins.adoc[]
