:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Get TinyMCE bugs fixed
:description: TinyMCE Enterprise customers get priority fixes of bugs.
:keywords: enterprise bug bugs patch patches
:title_nav: Get bugs fixed

{productname} is an open source project that relies on the community, to report and fix bugs. You can do this through our https://github.com/tinymce/tinymce[Github project].

The team behind {productname} invests a lot of time in fixing community-reported bugs - particularly high priority issues. Just check out our link:{rootDir}changelog.html[changelog] and I am sure you will agree!

However, we cannot fix all of the issues that are reported. With 5 million downloads a year we have to triage what impacts the most people.

If your company needs specific issues fixed on a timeline, we suggest you sign up for a {accountpage} to receive priority support. Again, we cannot guarantee that we can fix all bugs, but this is the way to ensure your issues are at the top of the queue.
