:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Cloud-based file management
:description: Tiny Drive - a premium plugin to manage files & images.
:keywords: tinydrive .net php relative_urls
:title_nav: Cloud-based file management

{cloudfilemanager} is a premium {productname} plugin for cloud-based asset management and storage solution. {cloudfilemanager} is a solution for creating rich text by attaching and embedding images, videos, and other files in your document.

{cloudfilemanager} presents a cloud-based asset management and storage solution that provides the ease of use of Google Drive without the server requirements of a self-hosted asset manager such as our own MoxieManager.

[[configuring-the-editor-for-tiny-drive]]
=== Configuring the editor for Tiny Drive

Once you have the API key, or if you are a current {cloudname} user who already has an API key, then you have access to {cloudfilemanager}. In order to get the service up and running, you'll need to complete a few more steps. See our link:{rootDir}tinydrive.html[documentation] for more information.

[NOTE]
====
We are launching the service with a complimentary 100MB of storage and up to 1 GB of bandwidth.
====

[[security-performance]]
=== Security & performance

We know security is a primary concern when it comes to cloud storage.  {cloudfilemanager} uses an https://aws.amazon.com/s3/[Amazon Web Services S3] bucket, the same storage solution used by companies like Netflix, Thomson Reuters, and Zillow.  (You can read about Amazon's comprehensive security approach https://aws.amazon.com/security/[here].)

As your assets are passed back and forth between your {productname} editor instance and the S3 bucket, {cloudfilemanager} uses both your API key and a https://jwt.io/introduction/[JSON Web Token] (JWT) to authenticate each data transaction.  Each {cloudfilemanager} user will need to create their own JWT, and we walk you through the whole process link:{rootDir}tinydrive/jwt-authentication.html[here].

And to make sure your assets are delivered as fast as possible, we utilize the https://aws.amazon.com/cloudfront/[CloudFront CDN], which is Amazon's global content delivery network, known for its low latency and high data transfer speeds.

[[try-our-tiny-drive-plugin-demo]]
=== Try our Tiny Drive plugin demo

codepen::drive-demo[]

:pluginname: Tiny Drive
:pluginminimumplan: tierone
:plugindocspage: ../tinydrive
include::{partialsDir}misc/purchase-premium-plugins.adoc[]
