tinymce.init({
  selector: 'textarea#spellchecker',
  plugins: 'code tinymcespellchecker link',
  toolbar: 'spellchecker language spellcheckdialog',
  height: 500,
  spellchecker_language: 'en_US',
  content_langs: [
    { title: 'Afrikaans (South Africa)', code: 'af_ZA', customCode: 'af_ZA' },
    { title: 'English (Australia)', code: 'en_AU' },
    { title: 'English (Canada)', code: 'en_CA' },
    { title: 'English (United Kingdom)', code: 'en_GB' },
    { title: 'English (United States)', code: 'en_US' },
    { title: 'Medical English (US)', code: 'en_US', customCode: 'en_US-medical' },
    { title: 'Medical English (UK)', code: 'en_GB', customCode: 'en_GB-medical' },
    { title: 'Danish', code: 'da' },
    { title: 'Dutch', code: 'nl_NL' },
    { title: 'Finnish', code: 'fi' },
    { title: 'French', code: 'fr' },
    { title: 'German', code: 'de_DE' },
    { title: 'Hungarian', code: 'hu' },
    { title: 'Italian', code: 'it_IT' },
    { title: 'Maori (New Zealand)', code: 'mi_NZ' },
    { title: 'Norwegian Bokmål', code: 'nb_NO' },
    { title: 'Norwegian Nynorsk', code: 'nn' },
    { title: 'Polish', code: 'pl' },
    { title: 'Portuguese (Brazil)', code: 'pt_BR' },
    { title: 'Portuguese (Portugal)', code: 'pt_PT' },
    { title: 'Spanish', code: 'es' },
    { title: 'Swedish', code: 'sv_SE' },
    { title: 'Swedish (Finland)', code: 'sv_FI' }
  ],
  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:16px }'
});
