= Inlite theme
:description: Theme that renders a light weight UI for inline editing.
:keywords: theme inlite
:title_nav: Inlite

The `inlite` theme is responsible for rendering the editor lightweight inline mode. The current default theme is called link:{{ site.baseurl }}/themes/modern/[modern] this is an optional more lightweight distraction-free UI for the editor.

===== Example:

`js
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true
});
`

=== Theme specific controls

==== quicklink

Lets you quickly insert/edit links inline.

===== Example:

`js
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true,
    selection_toolbar: 'bold italic | quicklink h2 h3 blockquote'
});
`

==== quickimage

Lets you quickly insert images from the local machine into the editor. These can then be automatically uploaded if you configure link:{{ site.baseurl }}/advanced/handle-async-image-uploads/[image uploading].

===== Example:

`js
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true,
    insert_toolbar: 'quickimage quicktable'
});
`

==== quicktable

Lets you quickly insert a table 2x2 with 100% width.

===== Example:

`js
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true,
    insert_toolbar: 'quickimage quicktable'
});
`

=== Related configuration options

* link:{{ site.baseurl }}/configure/editor-appearance/#insert_toolbar[insert_toolbar]
* link:{{ site.baseurl }}/configure/editor-appearance/#selection_toolbar[selection_toolbar]
* link:{{ site.baseurl }}/configure/editor-appearance/#inline[inline]
* link:{{ site.baseurl }}/configure/editor-appearance/#skin[skin]
* link:{{ site.baseurl }}/configure/editor-appearance/#theme[theme]
