:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Tiny Drive plugin
:description: Cloud-based file and image management for TinyMCE.
:keywords: tinydrive storage media tiny drive
:title_nav: Drive

NOTE: This plugin is only available for link:{pricingpage}[{cloudname} users].

The link:{rootDir}tinydrive/introduction.html[{cloudfilemanager}] plugin adds the functionality to upload and manage files and images to the cloud. This plugin is only available in link:{accountsignup}[{cloudname}] and requires you to register for an API key.

To enable this functionality, add `tinydrive` to the list of plugins in the `tinymce.init` call. You also need to authenticate the user using a link:{rootDir}tinydrive/jwt-authentication[JSON Web Token] (JWT).

Once you enable {cloudfilemanager} it integrates as the default file picker for the Image, Link, and Media dialogs and as the default upload handler for local images being pasted or inserted into the document.

[[live-example]]
== Live example

codepen::drive[]

[[example]]
=== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  plugins: 'tinydrive',
  tinydrive_token_provider: 'URL_TO_YOUR_TOKEN_PROVIDER'
});
----

[[configuration]]
=== Configuration

You can read more about the various configuration options for {cloudfilemanager} in the dedicated link:{rootDir}tinydrive/configuration.html[configuration page].
