:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= PowerPaste plugin
:keywords: enterprise powerpaste power paste paste_as_text powerpaste_word_import powerpaste_html_import powerpaste_block_drop powerpaste_allow_local_images microsoft word excel
:title_nav: PowerPaste
:plugin: powerpaste
:pluginname: PowerPaste

{premiumplugin}

The {productname} *PowerPaste* plugin automatically cleans up content from Microsoft Word/Excel and HTML sources to ensure clean, compliant content that matches the look and feel of the site.

[NOTE]
====
Due to limitations in Excel online (part of Office Live) PowerPaste does not support pasting from Excel online.  If you paste content using Excel in Office Live you will get a plain text representation of the content.
====

[[usage]]
== Usage

The *PowerPaste* plugin activates automatically when users paste content into the editor. For basic usage, users are not required to take any action. Simply copy and paste content normally using keyboard shortcuts, the browser's "Paste" menu item (including from the context menu), or the {productname} "Paste" toolbar button.

To paste clipboard content as plain text, users can click the "Paste As Text" toolbar button or menu item, then paste the content normally. The {productname} *PowerPaste* plugin will convert the HTML on the clipboard into plain text.

If you configure *PowerPaste* to allow local images (see the <<powerpaste_allow_local_images,`powerpaste_allow_local_images`>> setting below), then images copied from Microsoft Word and other sources will appear in {productname} as Base64 encoded images. You can have {productname} automatically upload Base64 encoded images for reverting back to a standard image as described in the link:{rootDir}advanced/handle-async-image-uploads.html[image upload documentation].

[NOTE]
====
PowerPaste (when configured to allow local images) will import images from pasted Microsoft Word/Excel content.  When doing this, *PowerPaste* extracts Base64 encoded images from the clipboard.  Images larger than approximately 8.5MB may fail to import based on technical limitations of web browsers.
====

[[cloud-installation]]
== Cloud Installation

To enable the {productname} *PowerPaste* plugin with link:{rootDir}cloud-deployment-guide/editor-and-features.html[{cloudname}]:

. If you are currently using the `paste` plugin provided with {productname}, disable it by removing it from the `plugins` list.
. Add `powerpaste` to the `plugins` list.

Example {productname} configuration:

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "powerpaste"
});
----

[[self-hosted-installation]]
== Self-hosted Installation

To enable the {productname} *PowerPaste* plugin:

. If you are currently using the `paste` plugin provided with {productname}, disable it by removing it from the `plugins` list.
. Add `powerpaste` to the `plugins` list in  your {productname} configuration.

See the example {productname} configuration above.

[[using-the-powerpaste-plugin-with-module-loaders]]
== Using the PowerPaste Plugin with Module Loaders

To enable the *PowerPaste* plugin when using a link:{rootDir}advanced/usage-with-module-loaders.html[module loader], follow these instructions:

. Make the PowerPaste plugin folder available over http.
. Add the path to the PowerPaste plugin folder to the link:{rootDir}configure/integration-and-setup.html#external_plugins[external plugins] option in `tinymce.init()`.

Example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  external_plugins: {
    'powerpaste': 'http://www.server.com/application/external_plugins/powerpaste/plugin.js'
  }
});
----

[[configuration-options]]
== Configuration Options

[[paste_as_text]]
=== paste_as_text

This option controls the default state of the *Paste as text* menu item, which is added by the `powerpaste` plugin under the `Edit` menu drop-down.

The supported values are `true` and `false`. The default is `false`.

[discrete#example-paste_as_text]
===== Example: paste_as_text

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "powerpaste",
  menubar: "edit",
  toolbar: "pastetext",
  paste_as_text: true
});
----

include::{partialsDir}configuration/paste-merge-formats.adoc[]

[[powerpaste_word_import]]
=== powerpaste_word_import

This setting controls how content pasted from Microsoft Word is filtered.

*Default value:* `prompt`

The supported values are:

* `clean` - Preserve the structure of the content such as headings, tables and lists but remove inline styles and classes. This results in simple content that uses the site's CSS stylesheet while retaining the semantic structure from the original document.
* `merge` - Preserve the inline formatting and structure of the original document. Invalid and proprietary styles, tags and attributes are still removed ensuring that the HTML is valid while more closely matching the original document formatting.
* `prompt` - Prompt the user to choose between the clean and merge options after attempting to paste word content.

[NOTE]
====
When using the Windows operating system, copying and pasting content from Word 2013 (or later) in "Protected View" will result in plain, unformatted text. This is due to how Protected View interacts with the clipboard.
====

[[powerpaste_html_import]]
=== powerpaste_html_import

This setting controls how content pasted from sources other than Microsoft Word is filtered. Note that this includes content copied from {productname} itself.

*Default value:* `clean`

The supported values are:

* `clean` - Preserve the structure of the content such as headings, tables, and lists but remove inline styles and classes. This results in simple content that uses the site's CSS stylesheet while retaining the semantic structure from the original document.
* `merge` Preserve the inline formatting and structure of the original document. Invalid and proprietary styles, tags and attributes are still removed ensuring that the HTML is valid while more closely matching the original document formatting.
* `prompt` - Prompt the user to choose between the clean and merge options after attempting to paste HTML content.

[[powerpaste_allow_local_images]]
=== powerpaste_allow_local_images

When set to `true`, Base64 encoded images using a data URI in the copied content will not be removed after pasting.

*Default value:* `true`

*Possible values:*  `true`, `false`

[NOTE]
====
If you configure *_PowerPaste_* to allow local images, you can have {productname} automatically upload Base64 encoded images for conversion back to a standard image as described on the link:{rootDir}advanced/handle-async-image-uploads.html[image upload documentation].
====

include::{partialsDir}configuration/paste-block-drop.adoc[]

[[powerpaste_clean_filtered_inline_elements]]
=== powerpaste_clean_filtered_inline_elements

This setting allows for configuration of PowerPaste's *"clean"* paste filters for inline elements. These filters are run when `powerpaste_word_import` or `powerpaste_html_import` are set to `"clean"`; or when a user clicks the *"Remove formatting"* button on the paste prompt dialog.

The list of inline elements that should be removed on paste can be specified by setting `powerpaste_clean_filtered_inline_elements` to a comma-separated string of inline element tag names.

*Possible values:*  A comma-separated string.

[discrete#example-powerpaste_clean_filtered_inline_elements]
===== Example: powerpaste_clean_filtered_inline_elements

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "powerpaste",
  powerpaste_word_import: "clean", // optional
  powerpaste_html_import: "clean", // optional
  powerpaste_clean_filtered_inline_elements: "strong, em, b, i, u, strike, sup, sub, font"
});
----

[[powerpaste_keep_unsupported_src]]
=== powerpaste_keep_unsupported_src

Due to browser limitations, PowerPaste is not able to support all image types supported by Word and Excel. When `powerpaste_keep_unsupported_src` is set to `true`, PowerPaste will store the original `src` of unsupported images in a `data-image-src` attribute on the pasted image element. This enables developers to add further image support via post-processing.

For example, browsers do not allow PowerPaste to access the file system. If your application has access to the file system, setting `powerpaste_keep_unsupported_src` to `true` may allow you to replace unsupported images during post-processing using the original file paths.

*Default value:* `false`

*Possible values:* `true`, `false`

[discrete#example-powerpaste_keep_unsupported_src]
===== Example: powerpaste_keep_unsupported_src

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "powerpaste",
  powerpaste_keep_unsupported_src: true
});
----

include::{partialsDir}configuration/smart-paste.adoc[]

[[toolbar-buttons]]
== Toolbar Buttons

[discrete#pastetext]
==== pastetext

This button allows you to toggle paste as plain text mode on and off. When in plain text mode, all rich content is converted into plain text.

Example {productname} Configuration:

[source,js]
----
tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  toolbar: "pastetext"
});
----

[[menu-items]]
== Menu Items

[discrete#pastetext-2]
==== pastetext

This menu item allows you to toggle paste as plain text mode on and off. When in plain text mode, all rich content is converted into plain text.

Example {productname} Configuration:

[source,js]
----
tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  menu: {
	edit: {title: "edit", items: "pastetext"}
  }
});
----

[[advanced-config-options]]
== Advanced Config Options

[[pre-filtering-and-post-filtering-callbacks]]
=== Pre-filtering and post-filtering callbacks

Developers can add custom filtering before and after *PowerPaste*'s filters are run using the pre-filtering and post-filtering callbacks. These can be added as init options or at runtime using event listeners.

NOTE: These callbacks are also triggered by the core Paste plugin, but when triggered by PowerPaste they are passed more data.

[[configuration-options-2]]
==== Configuration Options

[[paste_preprocess]]
===== paste_preprocess

This setting allows you to run custom filtering on the content from the clipboard before it is run through PowerPaste's filters. The callback is passed two arguments: the PowerPaste plugin instance and an object containing event data. This object contains:

* Standard paste event data.
* `content` - A string containing the content to be pasted.
* `mode` - A string indicating whether PowerPaste is in `clean`, `merge`, or `auto` mode.
* `source` - A string indicating which kind of filtering PowerPaste will run based on the source of the content. This will return `html`, `msoffice`, `googledocs`, `image`, `imagedrop`, `plaintext`, `text`, or `invalid`.

NOTE: The `imagedrop` `source` was added in {productname} 5.3.

NOTE: The mode 'auto' is used when the content source does not have formatting to "clean" or "merge". For example, when pasting an image with no text or markup content.

Example {productname} configuration:

[source,js]
----
const yourCustomFilter = function(content) {
  // Implement your custom filtering and return the filtered content
  return content;
};

tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  paste_preprocess: function (pluginApi, data) {
    console.log(data.content, data.mode, data.source);
    // Apply custom filtering by mutating data.content
    // For example:
    const content = data.content;
    const newContent = yourCustomFilter(content);
    data.content = newContent;
  }
});
----

[[paste_postprocess]]
===== paste_postprocess

This setting allows you to run custom filtering on the pasted content after it is run through PowerPaste's filters. The callback is passed two arguments: the PowerPaste plugin instance and an object containing event data. This object contains:

* Standard paste event data.
* `node` - A DOM node containing the DOM structure of the filtered paste content.
* `mode` - A string indicating whether PowerPaste is in `clean`, `merge`, or `auto` mode.
* `source` - A string indicating which kind of filtering PowerPaste will run based on the source of the content. This will return `html`, `msoffice`, `googledocs`, `image`, `imagedrop`, `plaintext`, `text`, or `invalid`.

NOTE: The `imagedrop` `source` was added in {productname} 5.3.

NOTE: The mode 'auto' is used when the content source does not have formatting to "clean" or "merge". For example, when pasting an image with no text or markup content.

Example {productname} configuration:

[source,js]
----
tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  paste_postprocess: function (pluginApi, data) {
    console.log(data.node, data.mode, data.source);
    // Apply custom filtering by mutating data.node
    const additionalNode = document.createElement('div');
    additionalNode.innerHTML = '<p>This will go before the pasted content.</p>';
    data.node.insertBefore(additionalNode, data.node.firstElementChild);
  }
});
----

[[event-listeners]]
==== Event Listeners

Custom paste filtering can also be configured at runtime using event listeners.

* `PastePreProcess` is equivalent to `paste_preprocess`
* `PastePostProcess` is equivalent to `paste_postprocess`

The event listeners are passed the same data objects as their equivalent configuration options. The event listener callbacks can be configured or changed at any time as long as you have a reference to the Editor API.

Example {productname} configuration:

[source,js]
----
const yourCustomFilter = function(content) {
  // Implement your custom filtering and return the filtered content
  return content;
};

tinymce.init({
  selector: "textarea",
  plugins: "powerpaste",
  setup: function(editor) {
    editor.on('PastePreProcess', function(data) {
      console.log(data.content, data.mode, data.source);
      // Apply custom filtering by mutating data.content
      const content = data.content;
      const newContent = yourCustomFilter(content);
      data.content = newContent;
    });

    editor.on('PastePostProcess', function(data) {
      console.log(data.node, data.mode, data.source);
      // Apply custom filtering by mutating data.node
      // For example:
      const additionalNode = document.createElement('div');
      additionalNode.innerHTML = '<p>This will go before the pasted content.</p>';
      data.node.insertBefore(additionalNode, data.node.firstElementChild);
    });
  }
});
----

[[commands]]
== Commands

The PowerPaste plugin provides the following JavaScript command.

include::{partialsDir}commands/powerpaste-cmds.adoc[]
