:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Table plugin
:controls: toolbar button, menu item
:description: Table editing features.
:keywords: row cell column table_appearance_options table_clone_elements table_grid table_tab_navigation table_default_attributes table_default_styles table_class_list table_cell_class_list table_row_class_list table_advtab table_cell_advtab table_row_advtab
:title_nav: Table

The `table` plugin adds table management functionality to {productname}. It also adds a new menubar item `Table` with various options in its dropdown including `Insert table` and options to modify cells, rows and columns, and a toolbar button with the same functionality.

*Type:* `String`

[[example]]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table tabledelete | tableprops tablerowprops tablecellprops | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol"
});
----

[[config-options]]
== Config Options

These settings affect the execution of the `table` plugin and let you modify the default styles and attributes for tables, preset class lists, and table behavior.

[[table_toolbar]]
=== `table_toolbar`

This option allows you to specify the toolbar buttons shown on the contextual toolbar for tables. Provide a space-separated list of toolbar buttons in the order they should be shown. To create groups on the toolbar, use the `|` pipe character to add a separator between toolbar buttons.

To disable the table toolbar, set the value to an empty string.

*Type:* `String`

*Default Value:* `'tableprops tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol'`

*Possible Values:* Any toolbar button. For a list of predefined toolbar buttons, see: link:{rootDir}advanced/editor-control-identifiers.html#toolbarcontrols[Editor control identifiers - Toolbar controls].

[discrete#example-default-table_toolbar-configuration]
===== Example: Default table_toolbar configuration

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_toolbar: "tableprops tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol"
});
----

[discrete#example-disable-the-table-toolbar]
===== Example: Disable the table toolbar

To disable or remove the contextual table toolbar, set `table_toolbar` to an empty string.

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_toolbar: ""
});
----

[[table_appearance_options]]
=== `table_appearance_options`

This option allows you to disable some of the options available to a user when inserting or editing a table. When set to `false` the following fields will not appear: Cell spacing, Cell padding, Border and Caption.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:*  `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_appearance_options: false
});
----

[[table_clone_elements]]
=== `table_clone_elements`

This option enables you to specify which elements should be cloned as empty children when inserting rows/columns to a table. By default it will clone these "``strong`` `em` `b` `i` `span` `font` `h1` `h2` `h3` `h4` `h5` `h6` `p` ``div``" into new cells.

*Type:* `String`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_clone_elements: "strong em a"
});
----

[[table_grid]]
=== `table_grid`

This option allows you to disable the grid-like table picker in the Table menu. The grid feature (which is enabled by default) consists of a dragable matrix that a user can interact with to automatically create a table of x-rows by x-columns based upon their input.

However, if `table_grid` is set to `false` the table picker will be replaced by a menu item that opens a dialog that users can use to insert a table. This dialog allows users to set various parameters such as the number of columns and rows, width, height, cell spacing and padding, border width, alignment, and whether to display a caption. There are also advanced style options available if `table_advtab` is set to `true`.

NOTE: To configure the Table menu to include both the table picker and the table dialog menu items, set `table_grid` to `true` and configure link:{rootDir}configure/editor-appearance.html#menu[`menu`] to include both the `inserttable` and `inserttabledialog` menu items.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:*  `true`, `false`

{differs_for_mobile}

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_grid: false
});
----

[[table_tab_navigation]]
=== `table_tab_navigation`

This option enables you to disable the default tab between table cells feature. By default, when a user presses tab the cursor will move between cells within the table. By setting the `table_tab_navigation` value to `false` the cursor will tab between browser elements (such as the URL bar or form fields, etc).

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:* `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_tab_navigation: false
});
----

[[table_default_attributes]]
=== `table_default_attributes`

This option enables you to specify default attributes for inserted tables.

*Type:* `Object`

*Default Value:* `{ border: '1' }`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_default_attributes: {
    border: '1'
  }
});
----

[[table_default_styles]]
=== `table_default_styles`

This option enables you to specify the default styles for inserted tables.

*Type:* `Object`

*Default Value:* `{ 'border-collapse': 'collapse', 'width': '100%' }`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_default_styles: {
    width: '50%'
  }
});
----

[[table_responsive_width]]
=== `table_responsive_width`

This option enables you to force pixels or percentage sizes for tables. Setting this to true will force resizing by percentages and setting this to false
will force pixel resizing. The default is to automatically detect what the table size is and just use that unit for resizing.

*Type:* `Boolean`

*Default Value:* `none`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_responsive_width: false
});
----

[[table_class_list]]
=== `table_class_list`

This option enables you to specify a list of classes to present in the table options dialog box. This is useful if you want users to assign predefined classes to table elements.

*Type:* `Array`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_class_list: [
    {title: 'None', value: ''},
    {title: 'Dog', value: 'dog'},
    {title: 'Cat', value: 'cat'}
  ]
});
----

[[table_cell_class_list]]
=== `table_cell_class_list`

This option enables you to specify a list of classes to present in the table cell options dialog box. This is useful if you want users to assign predefined classes to table cells.

*Type:* `Array`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_cell_class_list: [
    {title: 'None', value: ''},
    {title: 'Dog', value: 'dog'},
    {title: 'Cat', value: 'cat'}
  ]
});
----

[[table_row_class_list]]
=== `table_row_class_list`

This option enables you to specify a list of classes to present in the table row options dialog. This is useful if you want users to assign predefined classes to table rows.

*Type:* `Array`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_row_class_list: [
    {title: 'None', value: ''},
    {title: 'Dog', value: 'dog'},
    {title: 'Cat', value: 'cat'}
  ]
});
----

[[table_advtab]]
=== `table_advtab`

This option makes it possible to disable the advanced tab in the table dialog box. The advanced tab allows a user to input `style`, `border color` and `background color` values.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:* `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_advtab: false
});
----

[[table_cell_advtab]]
=== `table_cell_advtab`

This option makes it possible to disable the advanced tab in the table cell dialog box. The advanced tab allows a user to input `style`, `border color` and `background color` values.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:* `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_cell_advtab: false
});
----

[[table_row_advtab]]
=== `table_row_advtab`

This option makes it possible to disable the advanced tab in the table row dialog box. The advanced tab allows a user to input `style`, `border color` and `background color` values.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:* `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_row_advtab: false
});
----

[[table_resize_bars]]
=== `table_resize_bars`

This option makes it possible to disable the ability to resize table columns and rows by dragging the border between two columns or rows.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:* `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_resize_bars: false
});
----

[[table_style_by_css]]
=== `table_style_by_css`

This option enables you to force Table Properties dialog to use HTML5/CSS3 standards for setting cell spacing and cellpadding. By default, these are added as attributes to the table element. By setting this to true, cell spacing is applied to the table element as a `border-spacing` style and cell padding is applied to all `td` elements as a `padding` style

*Type:* `Boolean`

*Default Value:* `false`

*Possible Values:* `true`, `false`

[discrete#example-2]
===== Example

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  menubar: "table",
  toolbar: "table",
  table_style_by_css: false
});
----

== Examples of various table setups

Here are some examples of configuration for common setups.

[[no-default-attributes-or-styles-on-tables]]
==== No default attributes or styles on tables

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_default_attributes: {},
  table_default_styles: {}
});
----

[[pixel-based-resizing]]
==== Pixel based resizing

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_default_attributes: {},
  table_default_styles: {},
  table_responsive_width: false
});
----

[[percentage_based_resizing]]
==== Percentage based resizing

[source,js]
----
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_default_attributes: {
    'border': '1'
  },
  table_default_styles: {
    'border-collapse': 'collapse',
    'width': '100%'
  },
  table_responsive_width: true
});
----

NOTE: The advanced tabs of the table, row, and cell properties dialogs use the `colorpicker` to allow for border and background colors to be applied. See docs to use and configure a custom link:{rootDir}plugins/colorpicker.html[colorpicker].

[[api]]
== API

|===
| Name | Arguments | Description

| insertTable
| columns: number, rows: number
| Insert a table with the given number of columns and rows at the current cursor location

| getClipboardRows
|
| Returns the data for any rows cut or copied using `mceTableCutRow` or `mceTableCopyRow`

| setClipboardRows
| rows: HTMLElement[]
| Set the data to be used by `mceTablePasteRowBefore` or `mceTablePasteRowAfter` for pasting rows into a table
|===

[[example-2]]
==== Example

[source,js]
----
tinymce.activeEditor.plugins.table.insertTable(2, 3);
----

[[events]]
== Events

|===
| Name | Description

| newrow
| Fired when a row is created

| newcell
| Fired when a cell is created

| ObjectResizeStart
| Fired when a resize action is started on a table, row, column or cell using the resize bars

| ObjectResized
| Fired when a resize action is finished on a table, row, column or cell using the resize bars
|===

[[commands]]
== Commands

The Table plugin provides the following JavaScript commands.

include::{partialsDir}commands/table-cmds.adoc[]
