This section describes issues that users of {productname} 5.1 may encounter, as well as possible workarounds for these issues.

*Outline*

* xref:autocompleterandkeypresseventissuesonandroid[Autocompleter and keypress event issues on Android]
* xref:textpatternspluginlimitedfunctionalityonandroiddevices[Text Patterns plugin: Limited functionality on Android devices]
* xref:spellcheckerpropluginunexpectedbehavioronandroiddevices[Spell Checker Pro plugin: Unexpected behavior on Android devices]
* xref:uielementsmayrenderbehindthekeyboardonios12devices[UI elements may render behind the keyboard on iOS 12 devices]
* xref:uiissuewithsidebarsonmobile[UI issue with sidebars on mobile]
* xref:findandreplacemovingoutofviewinios[Find and replace moving out of view in iOS]
* xref:inlinetoolbarplacementissuesonmobiledevices[Inline toolbar placement issues on mobile devices]
* xref:touchselectionhandleissueonios[Touch selection handle issue on iOS]
* xref:textselectioncontexttoolbarissueonandroiddevices[Text selection context toolbar issue on Android devices]
* xref:formatpainterlimitedfunctionalityoniosdevices[FormatPainter: Limited functionality on iOS devices]

[[autocompleterandkeypresseventissuesonandroid]]
=== Autocompleter and keypress event issues on Android

==== Issue

[NOTE]
====
This issue affects the following plugins:

* xref:plugins/premium/mentions.adoc[Mentions].
* xref:plugins/opensource/emoticons.adoc[Emoticons].
* xref:plugins/opensource/charmap.adoc[Character Map].
====

Plugins relying on the xref:ui-components/autocompleter.adoc[autocompleter API] or keypress events do not work on Android. Android intercepts content and processes content prior to insertion into the editor.

==== Workaround

The only known workaround for the autocompleter at the moment is to press space and then press backspace to trigger the autocompleter to activate.

[[textpatternspluginlimitedfunctionalityonandroiddevices]]
=== Text Patterns plugin: Limited functionality on Android devices

==== Issue

The text pattern plugin will not apply inline patterns if the text pattern is immediately followed by a space on Android devices. The Text Patterns plugin relies on keypress events, which do not work on Android. Android intercepts content and processes content prior to insertion into the editor.

==== Workaround

Press _Enter_ or _Return_ immediately after entering the text pattern.

[[spellcheckerpropluginunexpectedbehavioronandroiddevices]]
=== Spell Checker Pro plugin: Unexpected behavior on Android devices

==== Issue

When selecting a correction, the original word will be duplicated and inserted at the selection point. Such as `Anddddroid` might be replaced with `Anddd Andddroid droid`.

==== Workaround

No known workaround at the time of release.

[[uielementsmayrenderbehindthekeyboardonios12devices]]
=== UI elements may render behind the keyboard on iOS 12 devices

==== Issue

UI elements may be rendered behind the keyboard on iOS 12 devices. This includes, but is not limited to:

* Dialogs.
* Context menus.
* Context toolbars.

This is due to a limitation of Safari on iOS 12. The silver theme relies on the `VisualViewport` API to determine the area of the page is visible on the device. Unfortunately the `VisualViewport` API is an experimental feature in iOS 12.

==== Workaround

To workaround this issue, users can either:

* Upgrade to iOS 13 or later
* Turn on the experimental feature by going to:

*Settings* > *Safari* > *Advanced* > *Experimental Features* > *Visual Viewport API*.

[[uiissuewithsidebarsonmobile]]
=== UI issue with sidebars on mobile

==== Issue

NOTE: This issue affects the xref:plugins/premium/comments/index.adoc[Comments plugin].

When opening sidebars on small screens (such as mobile phones), the sidebar may occupy most or all of the text area of the editor.

==== Workaround

For the comments plugin, the comments sidebar can be collapsed using the `showcomments` toolbar button (image:icons/comment.svg[comment.svg]).

For other plugins with sidebars, {companyname} recommends ensuring the sidebar's toolbar button is accessible on the toolbar.

[[findandreplacemovingoutofviewinios]]
=== Find and replace moving out of view in iOS

==== Issue

The Find and replace dialog moves outside the screen view on iOS when finding a match off-screen.

==== Workaround

No known workaround at the time of release.

[[inlinetoolbarplacementissuesonmobiledevices]]
=== Inline toolbar placement issues on mobile devices

==== Issue

On mobile devices, the inline toolbar can intermittently display in the wrong location when the keyboard is open or when scrolling.

==== Workaround

No known workaround at the time of release.

[[touchselectionhandleissueonios]]
=== Touch selection handle issue on iOS

==== Issue

The iOS touch selection handles (lollipops) sometimes remain on screen after the selection changes, resulting in misplaced or multiple selections.

==== Workaround

This may be an iOS bug, and the is no known workaround at the time of release. To remove the duplicate or multiple selections, restart the Safari app.

[[textselectioncontexttoolbarissueonandroiddevices]]
=== Text selection context toolbar issue on Android devices

==== Issue

TinyMCE text selection context toolbars do not appear on Android.

==== Workaround

No known workaround at the time of release.

[[formatpainterlimitedfunctionalityoniosdevices]]
=== Format Painter plugin: Limited functionality on iOS devices

==== Issue

Unable to apply formats using a collapsed selection on iOS due to iOS selection placement.

==== Workaround

No known workaround at the time of release.
