[[plugins]]
= Plugins

This section documents the improvements, changes, and removals made to {productname} 6.0 Plugins.

It also documents the the plugin loading change introduced in {productname} 6.0.

* xref:plugin-loading-format-change[Plugin loading format change]
* xref:new-and-improved-plugins[New and improved Plugins]
* xref:changed-apis[Changed APIs]
* xref:removed-or-deprecated-plugins[Removed or deprecated Plugins]

// tag::plugins[]
[[plugin-loading-format-change]]
== Plugin loading format change

{productname} 6.0 allows plugin loading in any of three formats:

. An array of strings:
+
`plugins: [ 'advlist', 'lists', 'image', 'help', 'wordcount' ]`
+
. A space-separated string:
+
`plugins: 'advlist lists image help wordcount'`
+
. A comma-separated string, with or without spaces:
+
`plugins: 'advlist,lists,image,help,wordcount'` +
`plugins: 'advlist, lists, image, help, wordcount'`

Previously, one other format was allowed: arrays of space-separated strings. This format is no longer accepted in {productname} 6.0.

[[new-and-improved-plugins]]
== New and improved plugins

[[new-and-improved-plugins-editimage]]
=== Enhanced Image Editing

_Enhanced Image Editing_, a link:{plugindirectory}#productivity[Premium plugin], replaces the now-deprecated and removed _ImageTools_ plugin. The `imagetools` plugin is no longer part of the Core open source editor.

// need to explain relationship between Enhanced Image Editing and `editimage`.

The following `editimage` options replace the old `imagetools` options:

* `imagetools_cors_hosts` is now `editimage_cors_hosts`.
* `imagetools_credentials_hosts` is now `editimage_credentials_hosts`.
* `imagetools_fetch_image` is now `editimage_fetch_image`.
* `imagetools_proxy` is now `editimage_proxy`.
* `imagetools_toolbar` is now `editimage_toolbar`.

`editimage` also offers a new option: `editimage_proxy_service_url`. This option has been added as a new recommended method when using xref:introduction-to-premium-selfhosted-services.adoc[Tiny services].


[[new-and-improved-plugins-emoticons]]
=== Emoticons

The `emoticon` plugin now uses the more accurate word, _Emoji_, in its toolbar, menu item and dialog.

In previous versions, the word presented in these parts of the plugin’s user-interface was _Emoticon_.

NOTE: The plugin, itself, is still called Emoticons. And the plugin description and the plugin’s configuration and Help dialogs still reflect this.


[[new-and-improved-plugins-table-of-contents]]
=== Table of Contents

There are no end-user facing changes between the previous `toc` plugin and the `tableofcontents` plugin.

NOTE: The `tableofcontents` plugin is no longer part of the Core open source editor. Table of Contents is now a link:{plugindirectory}#productivity[Premium plugin].

=== Hindi, Malay, and Vietnamese translations added to Premium Plugins

The following Premium Plugins now present in Hindi, Malay, and Vietnamese:

* Accessibility Checker
* Advanced Tables
* Comments
* Enhanced Image Editing
* Export
* PowerPaste
* Real-time Collaboration (RTC)
* Spell Checker Pro
* Table of Contents

[[changed-plugins]]
== Changed plugins

[[changed-plugins-autoresize]]
=== Autoresize

Previously, the `autoresize` plugin offered an `autoresize_on_init` option.

This setting does not do anything meaningful, and had been previously deprecated.

As of {productname} 6.0, `autoresize_on_init` has been removed from the `autoresize` plugin.

[[changed-plugins-media]]
=== Media

In {productname} 5.x, the `media` plugin used https://tiny.cloud/docs/api/tinymce.html/tinymce.html.saxparser/[`SaxParser`] to validate elements for parsing.

As of {productname} 6.0, `SaxParser` is no longer used. Another {productname} public API — `DomParser` — is used instead.

As a consequence the `iframe`, `video`, `audio`, and `object` elements are no longer marked as _special_. Instead their contents are simply validated against the {productname} schema.

NOTE: The {productname} public API, `DomParser` uses, in turn, the same-named browser parsing API: https://developer.mozilla.org/en-US/docs/Web/API/DOMParser[`DomParser`].

Also, the `media` plugin’s `media_scripts` option was deprecated in {productname} 5.10.

// Based on the code it looks like `media_scripts` was meant to be a way to provide an allowed list of <script>s that could be used to embed media. However, somewhere along the lines it broke and no longer works.

As of the release of {productname} 6.0, this option has been removed completely.

[[changed-plugins-noneditable]]
=== Noneditable

The `noneditable` plugin is no longer a plugin. It is now a Core part of {productname} 6.0.

In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

All references to `noneditable` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[[changed-plugins-paste]]
=== Paste

The `paste` plugin’s functionality is now a Core part of {productname} 6.0.

In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

All references to `paste` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

The `paste_data_images` option now defaults to `true`. When `paste` was a plugin, this option was, by default, set to `false`, which prevented images being pasted from the local machine.

The `mceInsertClipboardContent` argument, `content`, has been renamed. It is now `html`.

The new name is a more accurate reflection of what sort of data the argument passes.


[[changed-plugins-print]]
=== Print

`print` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

All references to `print` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[[changed-plugins-table]]
=== Table

The `table` plugin’s functionality is, as of {productname} 6.0, entirely focussed on the user interface (UI) for creating and editing tables.

The code that generates tables is now a Core part of {productname} 6.0.

This, now core feature of {productname} 6.0, also includes the following fixes, changes, and improvements.

* If the selected cells in the `tfoot` section of a table were header elements (ie were `th` elements), pressing the `table` row header toolbar button (which invokes the `mceTableRowType` command) returned the row as a header row.
+
This was incorrect: the section takes precedence and cells in the `tfoot` section of a table should be declared as a footer row.
+
In {productname} 6.0, selecting cells in the `tfoot` section of a table and pressing the row header toolbar button returns the row as a footer row, as expected.

* `mceInsertTableDialog` is the new command for invoking an _Insert Table_ dialog box.
+
The previous command, `mceInsertTable`, no longer works to invoke an _Insert Table_ dialog box: use the `mceInsertTableDialog` command instead.
+
The `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user-input.

* The default values for the `table_style_by_css` and the `table_use_colgroups` options have both been changed.
+
Previously, these options defaulted to `false`. As of {productname} 6.0, both options now default to `true`.
+
This is in line with modern web practice.

* The `table_responsive_width` option was previously deprecated and superseded by `table_sizing_mode`.
+
In {productname} 6.0, the `table_responsive_width` option has been removed.

[[removed-or-deprecated-plugins]]
== Removed or deprecated plugins

[[removed-or-deprecated-plugins-bbcode]]
=== BBCode

As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"], the `bbcode` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[[removed-or-deprecated-plugins-color-picker]]
=== Color Picker

Color Picker’s functionality has been a built in part of {productname} since version 5.

Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"], the empty `colorpicker` plugin has been removed.

[[removed-or-deprecated-plugins-context-menu]]
=== Context Menu

Context Menu’s functionality has been a built in part of {productname} since version 5.

Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"], the empty `contextmenu` plugin has been removed.

[[removed-or-deprecated-plugins-full-page]]
=== Full Page

As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"], the `fullpage` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[[removed-or-deprecated-plugins-hr]]
=== HR

The `hr` (horizontal rule) functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

All references to `hr` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[[removed-or-deprecated-plugins-imagetools]]
=== ImageTools

The `imagetools` plugin is no longer part of the Free {productname} editor. _Image Tools_ is now _Enhanced Image Editing_, a link:{plugindirectory}#productivity[Premium plugin].

[[removed-or-deprecated-plugins-legacy-output]]
=== Legacy Output

As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"], the `legacyoutput` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

[[removed-or-deprecated-plugins-paste]]
=== Paste

The `paste` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

Because the functionality was unmaintainable, `paste` no longer supports input from Microsoft Word.

There is an open https://github.com/tinymce/tinymce/discussions/7487[request for maintainers] should someone in the community be interested in taking over maintenance of this particular functionality as a separate plugin.

If a community-maintained version of the `paste` plugin becomes available, we will link to it from the xref:migration-from-5x.adoc#plugins-paste[_Migration Guide_].

NOTE: The Premium plugin, xref:introduction-to-powerpaste.adoc[`PowerPaste`], is available. It provides the capability to accept data from Microsoft Word and Microsoft Excel, and clean-up the received data before pasting it into place.

[[removed-or-deprecated-plugins-print]]
=== Print

`print` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

All references to `print` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.

[[removed-or-deprecated-plugins-spellchecker]]
=== Spell Checker

As per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"], the `spellchecker` plugin has been removed. It is no longer part of {productname} 6.0.

The link:{plugindirectory}#productivity[Premium plugin], xref:introduction-to-tiny-spellchecker.adoc[Spell Checker Pro], which offers equivalent functionality and more, is available.

[[removed-or-deprecated-plugins-tabfocus]]
=== Tab Focus

The `tabfocus` plugin has been removed. It is no longer part of {productname} 6.0. And it is not otherwise available.

The `tabfocus_elements` option, which relied on the `tabfocus` plugin, no longer functions.

As well, the `tab_focus` option was previously deprecated by `tabfocus_elements`. With this release, the `tab_focus` option has been removed completely.

As per standard web practice, the `tabindex` attribute should be used instead of the `tabfocus` plugin or any of the `tabfocus` plugin’s options.

As per that standard web practice, the `tabindex` attribute is copied from the target element to the iframe.

[[removed-or-deprecated-plugins-table-of-contents]]
=== Table of Contents

The `toc` plugin is no longer part of the Core open source editor. _Table of Contents_ is now a link:{plugindirectory}#productivity[Premium plugin].

[[removed-or-deprecated-plugins-text-color]]
=== Text color

Text color’s functionality has been a built in part of {productname} since version 5.

Consequently, and as per the previous https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/[{productname} 5 announcement, window="_blank"], the empty `textcolor` plugin has now been removed.

[[removed-or-deprecated-plugins-text-pattern]]
=== Text Pattern

The `textpattern` functionality is no longer a plugin. It is now a Core part of {productname} 6.0.

In {productname} 6.0, there is no setting or specifying this functionality in the `plugins` option.

All references to `textpattern` should be removed from your plugin configuration. Leaving references to removed plugins in a plugin configuration will cause console errors documenting the plugin failing to load.


// end::plugins[]
