[[commands-and-queries]]
= Commands and queries

This section documents the improvements and changes made to {productname} 6.0 commands and queries.

It also documents the {productname} 6.0 commands that have been removed.

* xref:new-and-improved-commands-and-queries[New and improved commands and queries]
* xref:changed-commands-and-queries[Changed commands and queries]
* xref:removed-or-deprecated-commands-and-queries[Removed or deprecated commands and queries]

// tag::commands-and-queries[]
[[new-and-improved-commands-and-queries]]
== New and improved commands and queries


[[mce-autocompleter-close-and-mce-autocompleter-reload]]
=== `mceAutocompleterClose` and `mceAutocompleterReload`

As part of moving core autocompleter feature from the default `silver` theme to the {productname} core, two new commands are now available: `mceAutocompleterClose` and `mceAutocompleterReload`.

[[mce-insert-table-dialog]]
=== mceInsertTableDialog

`mceInsertTableDialog` is the new command for invoking an _Insert Table_ dialog.

The previous command, `mceInsertTable`, no longer works to invoke an _Insert Table_ dialog: use the `mceInsertTableDialog` command instead.

The `mceInsertTable` command is still the command for inserting a table with specified properties directly and without asking for user input.


[[changed-commands-and-queries]]
== Changed commands and queries


[[editor]]
=== Editor commands

The Editor commands APIs no longer fallback to executing the browsers native command functionality.

As well, the Editor query command APIs now return `false` or an empty string on removed {productname} editors.


[[mce-add-editor-and-mce-toggle-editor]]
=== `mceAddEditor` and `mceToggleEditor`

Previously, `mceAddEditor` and `mceToggleEditor` used the `editorManager.settings` values to set the `id` and UI and UX options for a new {productname} editor instance.

`editorManager.settings` is not used at all in {productname} 6 and has been removed.

Instead, the `mceAddEditor` and `mceToggleEditor` commands use `id` and `options` values from an object passed when the command is run.


[[removed-or-deprecated-commands-and-queries]]
== Removed or deprecated commands and queries


[[exec-command]]
=== `execCommand`

The `execCommand` handler function has been removed from the `plugin` and `theme` interfaces.


[[mce-insert-raw-html]]
=== `mceInsertRawHTML`

The `mceInsertRawHTML` command has been removed.

// end::commands-and-queries[]
