[[options]]
= Options

This section documents the changes made to {productname} 6.0 Options.

It also documents the {productname} 6.0 Option that has been removed.

* xref:changed-options[Changed Options]
* xref:removed-or-deprecated-apis[Removed or deprecated Options]

// tag::options[]
[[changed-options]]
== Changed options


[[changed-options-element-format]]
=== `element_format`

Previously, `element_format` had no explicit default value. It’s implicit value, however, was `'xhtml'`.

In {productname} 6.0, `element_format` now has an explicit default value: `'html'`.


[[changed-options-image-upload-handler]]
=== `image_upload_handler`

Previously the `images_upload_handler` option passed `success` or `failure` callbacks to report the status of an image upload.

In {productname} 6, `images_upload_handler` reports upload results by returning a `Promise`.


[[changed-options-link-default-protocol]]
=== link_default_protocol

The `link_default_protocol` option sets the link protocol used by links added or edited using the _link_ dialog.

It now defaults to `'https'`. Previously it defaulted to `'http'`.

NOTE: The `link_default_protocol` value is only applied to an edited or inserted link if the protocol is not explicitly specified.

[[changed-options-plugins-option]]
=== `plugins` option

Previously, the list of configured plugins could be retrieved by calling `editor.getParam('plugins')` and returned the configured plugins as a string.

As of {productname} 6, the list of configured plugins is retrieved by calling `editor.options.get('plugins')` and now returns the configured plugins as an array.



[[removed-or-deprecated-options]]
== Removed or deprecated options


[[removed-or-deprecated-options-textpattern]]
=== TextPattern

The `textpattern_patterns` option is no longer an option. It has been renamed to `text_patterns` and is now a Core part of {productname} 6.0.

All references to `textpattern_patterns` should be changed to `text_patterns`.

Also, text patterns are now on by default: `text_patterns: false` turns the functionality off.

// end::options[]
