[[a11ychecker_filter_issue]]
== `+a11ychecker_filter_issue+`

The `+a11ychecker_filter_issue+` option allows Accessibility Checker issues to be removed from the Accessibility Checker report using a callback function. This option is a flexible alternative to the `+a11ychecker_ignored_rules+` option. This option can remove issues from the results shown in the dialog and the `+getReport+` API.

The callback function will be passed xref:a11ychecker.adoc#issue[`issue` objects] generated by the xref:a11ychecker.adoc#getreport[`+getReport()+` API]. To remove an issue from the Accessibility Checker report the callback needs to return `+false+` for that particular issue.

*Type:* `+Function+`

*Default value:*
[source,js]
----
(issue) => true;
----

=== Example: using `+a11ychecker_filter_issue+` to filter out the Accessibility Checker T1 rule

The callback function in the following example will return `false` if the issue `id` value is `'T1'`, filtering `'T1'` issues from the Accessibility Checker report.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'a11ychecker',
  toolbar: 'a11ycheck',
  a11ychecker_filter_issue: (issue) => {
    return issue.id !== 'T1';
  }
});
----

=== Example: using `+a11ychecker_filter_issue+` to filter out all Accessibility Checker table rules and rules less than `+'error'+` level

The callback function in the following example will only return `+false+` if the issue `+element+` is a `+'table'+` and the `+'severity'+` level is not `+'error'+`, filtering all low-severity and `+table+` element-related issues from the Accessibility Checker report.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'a11ychecker',
  toolbar: 'a11ycheck',
  a11ychecker_filter_issue: (issue) => {
	  return !(issue.element.nodeName.toLowerCase() === 'table' || issue.severity !== 'error');
  }
});
----

=== Example: using `+a11ychecker_filter_issue+` to filter images with empty alternative text from the Accessibility Checker I1 rule

The callback function in the following example will only return `false` for any issues with `'I1'` as the `+'id'+` image elements with an empty `+'alt+'` attribute, otherwise the issue won’t be filtered out. This implementation can be useful as allowing images to have empty alternative text can be another method of applying the `+role="presentation"+` attribute to mark an image as `+decorative+`.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'a11ychecker',
  toolbar: 'a11ycheck',
  a11ychecker_filter_issue: (issue) => {
    const element = issue.element;
    const isImageAndI1Issue = issue.id === 'I1' && element.nodeName.toLowerCase() === 'img';
    const hasEmptyAltAttribute = element.hasAttribute('alt') && element.alt === '';
    return !(isImageAndI1Issue && hasEmptyAltAttribute);
  }
});
----
