[[a11y_advanced_options]]
== `+a11y_advanced_options+`

This option affects the functionality of:

* The Accessibility Checker plugin (`+a11ychecker+`).
* The Image plugin (`+image+`).

Setting `+a11y_advanced_options+` to `+true+`:

* Adds the *Image is decorative* option to the _Insert/Edit Image_ dialog, allowing users to specify that an image is decorative and does not require alternative text for accessibility purposes.
* Adds the *Image is decorative* option to the _Accessibility Checker error_ dialog for images without alternative text or the `+role="presentation"+` attribute.

[IMPORTANT]
====
When `+a11y_advanced_options+` is set to `+true+`, xref:a11ychecker.adoc#a11ychecker_allow_decorative_images[`+a11ychecker_allow_decorative_images+`] will default to `+true+`.
====

*Type:* `+Boolean+`

*Default value:* `+false+`

*Possible values:* `+true+`, `+false+`

=== Example: using `+a11y_advanced_options+`

ifeval::["{includedSection}" == "imagePlugin"]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'image',
  toolbar: 'image',
  a11y_advanced_options: true
});
----

endif::[]
ifeval::["{includedSection}" == "a11yPlugin"]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'a11ychecker',
  toolbar: 'a11ycheck',
  a11y_advanced_options: true
});
----

endif::[]
ifndef::includedSection[]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'a11ychecker image',
  toolbar: 'a11ycheck image',
  a11y_advanced_options: true
});
----

endif::[]
