[[a11y_advanced_options]]
== `+a11y_advanced_options+`

This option affects the functionality of:

* The xref:a11ychecker.adoc[Accessibility Checker] plugin (`+a11ychecker+`).
* The xref:image.adoc[Image] plugin (`+image+`).
* The xref:uploadcare.adoc[Image Optimizer Powered by Uploadcare] plugin (`+uploadcare+`).

Setting `+a11y_advanced_options+` to `+true+`:

* Adds the *Image is decorative* option to the _Insert/Edit Image_ dialog, allowing users to specify that an image is decorative and does not require alternative text for accessibility purposes.
* Adds the *Decorative image* button to Image Optimizer's _Alt text_ context toolbar, allowing users to specify that an image is decorative and does not require alternative text for accessibility purposes.
* Adds the *Image is decorative* option to the _Accessibility Checker error_ dialog for images without alternative text or the `+role="presentation"+` attribute.

[IMPORTANT]
====
If `xref:a11ychecker.adoc#a11ychecker_allow_decorative_images[a11ychecker_allow_decorative_images]` is not explicitly set, the value defined in `+a11y_advanced_options+` will be used.
====

*Type:* `+Boolean+`

*Default value:* `+false+`

*Possible values:* `+true+`, `+false+`

=== Example: using `+a11y_advanced_options+`

ifeval::["{includedSection}" == "uploadcarePlugin"]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'uploadcare',
  toolbar: 'uploadcare',
  uploadcare_public_key: '<your-public-key>',
  a11y_advanced_options: true,
});
----

endif::[]
ifeval::["{includedSection}" == "imagePlugin"]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'image',
  toolbar: 'image',
  a11y_advanced_options: true,
});
----

endif::[]
ifeval::["{includedSection}" == "a11yPlugin"]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'a11ychecker',
  toolbar: 'a11ycheck',
  a11y_advanced_options: true,
});
----

endif::[]
ifndef::includedSection[]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'a11ychecker image',
  toolbar: 'a11ycheck image',
  a11y_advanced_options: true,
});
----

endif::[]
