[[advtemplate_templates]]
== `advtemplate_templates`

This option lets you specify a static list of predefined templates that can be inserted using the _Templates_ dialog. It is for scenarios where the provided template list is unchangeable. In this use-case, there is no need to set up a persistent template store and provide a more complex plugin configuration.

*Type:* `+Array+` of `+Objects+`

The template list assigned to the `advtemplate_templates` option must adhere to the following requirements:

. Each item must have a non-empty `title` value.
. Each template item is required to include a non-empty `content` value.
. Each category item is required to include a `items` sublist, which can be empty.
. Category items must not contain nested subcategories.

*Default value:* `+undefined+`

=== Example: using `advtemplate_templates`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'advtemplate',
  toolbar: 'inserttemplate',
  advtemplate_templates: [
    {
      title: 'Template 1',
      content: 'Template 1 content'
    },
    {
      title: 'Category 2',
      items: [
        {
          title: 'Template 2.1',
          content: 'Template 2.1 content'
        },
        {
          title: 'Template 2.2',
          content: 'Template 2.2 content'
        }
      ]
    }
  ],
});
----