[[ai_shortcuts]]
== `ai_shortcuts`

The `+ai_shortcuts+` option controls the list of {pluginname} shortcuts available in the `+AI Shortcuts+` toolbar button and menu item.

This option can be configured with an array to present a customised set of {pluginname} shortcuts.

As well, it can be set to a `+Boolean+` value to control the use of the default list of {pluginname} shortcuts.

When not specified, or set to `+true+`, the {pluginname} shortcuts toolbar button and menu item present and display the default set of shortcuts included with the {pluginname}.

When set to `+[]+` (an empty array), or `+false+`, the {pluginname} shortcuts toolbar button and menu item do not present in the {productname} instance.

When configured with an instance-specific object array, the {pluginname} shortcuts toolbar button and menu item present, and display the configured shortcuts when activated.

*Type:* `+Array+` of `+Objects+`, or `+Boolean+`

*Default value:* 
[source, js]
----
[
  { title: 'Summarize content', prompt: 'Provide the key points and concepts in this content in a succinct summary.' },
  { title: 'Improve writing', prompt: 'Rewrite this content with no spelling mistakes, proper grammar, and with more descriptive language, using best writing practices without losing the original meaning.' },
  { title: 'Simplify language', prompt: 'Rewrite this content with simplified language and reduce the complexity of the writing, so that the content is easier to understand.' },
  { title: 'Expand upon', prompt: 'Expand upon this content with descriptive language and more detailed explanations, to make the writing easier to understand and increase the length of the content.' },
  { title: 'Trim content', prompt: 'Remove any repetitive, redundant, or non-essential writing in this content without changing the meaning or losing any key information.' },
  { title: 'Change tone', subprompts: [
    { title: 'Professional', prompt: 'Rewrite this content using polished, formal, and respectful language to convey professional expertise and competence.' },
    { title: 'Casual', prompt: 'Rewrite this content with casual, informal language to convey a casual conversation with a real person.' },
    { title: 'Direct', prompt: 'Rewrite this content with direct language using only the essential information.' },
    { title: 'Confident', prompt: 'Rewrite this content using compelling, optimistic language to convey confidence in the writing.' },
    { title: 'Friendly', prompt: 'Rewrite this content using friendly, comforting language, to convey understanding and empathy.' },
  ] },
  { title: 'Change style', subprompts: [
    { title: 'Business', prompt: 'Rewrite this content as a business professional with formal language.' },
    { title: 'Legal', prompt: 'Rewrite this content as a legal professional using valid legal terminology.' },
    { title: 'Journalism', prompt: 'Rewrite this content as a journalist using engaging language to convey the importance of the information.' },
    { title: 'Medical', prompt: 'Rewrite this content as a medical professional using valid medical terminology.' },
    { title: 'Poetic', prompt: 'Rewrite this content as a poem using poetic techniques without losing the original meaning.' },
  ] },
]
----

[NOTE]
.Translations and changes
====
The default {pluginname} shortcuts are only available in English. They have not been translated into any other languages, and switching {productname} to a language other than English does not change the default {pluginname} shortcuts.

Also, the default {pluginname} shortcuts are subject to change. If you prefer to keep these shortcuts, include them within your integration.
====

=== Example: using `ai_shortcuts` to present a customised set of {pluginname} shortcuts

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  plugins: 'ai',
  toolbar: 'aidialog aishortcuts',
  ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
  ai_shortcuts: [
    { title: 'Screenplay', prompt: 'Convert this to screenplay format.' },
    { title: 'Stage play', prompt: 'Convert this to stage play format.' },
    { title: 'Classical', subprompts: 
      [
        { title: 'Dialogue', prompt: 'Convert this to a Socratic dialogue.' },
        { title: 'Homeric', prompt: 'Convert this to a Classical Epic.' }
      ]
    },
    { title: 'Celtic', subprompts:
      [
        { title: 'Bardic', prompt: 'Convert this to Bardic verse.' },
        { title: 'Filí', prompt: 'Convert this to Filí-an verse.' }
      ]
    },
  ]
});
----

=== Example: disabling `ai_shortcuts`

To disable the {pluginname} shortcuts menu and toolbar options, set `ai_shortcuts` to `false` (or to `+[]+`, an empty array).

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  ai_shortcuts: false
});
----

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  ai_shortcuts: []
});
----

=== Valid Shortcuts

Valid shortcut objects contain the following fields.

`+title+`:: A string which is displayed in the `+aishortcuts+` toolbar button and menu item. This will indicate which shortcut is used, or which category of shortcuts are in this menu.

And either

`+prompt+`:: A string containing the query which is given to the `+ai_request+` function when the shortcut is used.

or

`+subprompts+`:: An array containing more valid shortcut objects. This allows shortcuts to be grouped into categories within the {pluginname} shortcuts toolbar button and menu item.