[[ai_shortcuts]]
== `ai_shortcuts`

The `+ai_shortcuts+` option controls whether or not the AI Assistant shortcuts menu and toolbar option presents.

As well, it can be configured with an array to present a customised set of AI Assistant shortcuts.

When set to `+true+`, the AI Assistant shortcuts menu and toolbar item present and display the default set of shortcuts included with the AI Assistant.

When set to `+false+`, the AI Assistant shortcuts menu and toolbar item do not present in the {productname} instance.

When configured with an instance-specific object array, the AI Assistant shortcuts menu and toolbar item present, and display the configured shortcuts when activated.

Setting `+ai_shortcuts+` to an empty array — `+[]+` — is also possible. It is functionally equivalent to setting the option to `+false+`.

*Type:* either `+true+`, or `+false+` *or* an `+array+`

*Default value:* `+true+`

[NOTE]
.Setting `ai_shortcuts` to other values
====
If `ai_shortcuts` is set to a value other than

- `+false+`;
- `+[]+` (an empty array); or
- a custom array

the AI Assistant treats the value as `+true+`.
====

=== The default set of shortcuts presented when `ai_shortcuts` is set to `+true+`.

[source,js]
----
[
  { title: 'Summarize', prompt: 'Briefly summarize this.' },
  { title: 'Explain', prompt: 'Give a short explanation of this.' },
  { title: 'Improve grammar', prompt: 'Correct grammar.' },
  { title: 'Improve writing', prompt: 'Enhance this text.' },
  { title: 'Simplify language', prompt: 'Simplify this.' },
  { title: 'Make longer', prompt: 'Expand this.' },
  { title: 'Make shorter', prompt: 'Condense this.' },
  { title: 'Change tone', subprompts: [
    { title: 'Descriptive', prompt: 'Make this descriptive.' },
    { title: 'Formal', prompt: 'Make this formal.' },
    { title: 'Casual', prompt: 'Make this casual.' },
    { title: 'Humour', prompt: 'Add humour to this.' },
    { title: 'Inspirational', prompt: 'Inspire reader with this.' },
    { title: 'Persuasive', prompt: 'Make this persuasive.' },
  ] },
  { title: 'Change style', subprompts: [
    { title: 'Business', prompt: 'Make this business-like.' },
    { title: 'Legal', prompt: 'Legal style this.' },
    { title: 'Journalism', prompt: 'Journalistic style this.' },
    { title: 'Medical', prompt: 'Medical style this.' },
    { title: 'Poetic', prompt: 'Make this poetic.' },
  ] },
]
----

=== Example: using `ai_shortcuts` to present a customised set of AI Assistant shortcuts

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  ai_shortcuts: '[
  { title: 'Classical', subprompts: 
    [
    { title: 'Dialogue', prompt: 'Convert this to a Socratic dialogue.' },
    { title: 'Homeric', prompt: 'Convert this to a Classical Epic.' },
    ]
  },
  { title: 'Celtic', subprompts:
    [
    { title: 'Bardic', prompt: 'Convert this to Bardic verse.' },
    { title: 'Filí', prompt: 'Convert this to Filí-an verse.' },
    ]
  },
]'
});
----

=== Example: disabling `ai_shortcuts`

To disable the AI Assistant shortcuts meny and toolbar options, set `ai_shortcuts` to `false` (or to `+[]+`, an empty array).

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  ai_shortcuts: false,
});
----
