[[autoresize_bottom_margin]]
== `+autoresize_bottom_margin+`

This option allows you to specify the size of the `+padding+` at the bottom of the editor's `+body+` set on initialization.

*Type:* `+Number+`

=== Example: using `+autoresize_bottom_margin+`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'autoresize',
  autoresize_bottom_margin: 50
});
----

As of version 6.4.1, {productname} checks for the {productname} resize function entering a loop.

If the function is detected as doing so, the document’s `+margin-bottom+` value is set to 0, instead of whatever value is assigned to `autoresize_bottom_margin`.

This prevents an xref:6.4.1-release-notes.adoc#infinite-resize[infinite resizing bug from presenting].

To prevent the resize function from even entering this loop, `+autoresize_bottom_margin+` must be set to a value less than any `+margin-bottom+` value set for the document.

Alternatively, if `+margin-bottom+` is set by a CSS declaration, set `+autoresize_bottom_margin+` to `0`.

=== Example: setting `+autoresize_bottom_margin+` to zero because `+margin-bottom+` is set elsewhere

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'autoresize',
  autoresize_bottom_margin: 0
});
----
