[[tinycomments-access]]
== `tinycomments_access`

*Type:* `+String+`

*Possible values:* `'comment'`

This option sets the editor to the readonly mode, while still allowing comments to be made. 

[IMPORTANT]
====
* When `tinycomments_access` is set to `comment`, the editor will automatically switch to xref:editor-important-options.adoc#readonly[Readonly Mode].
====

=== `tinycomments_access` _is set to `'comment'` and `readonly` set to `true`_

When `tinycomments_access` is set to `comment`, the editor will be in xref:editor-important-options.adoc#readonly[Readonly mode], but the comments will be in a **comment-only** mode. This means that users can add and delete comments, but they cannot edit the editor content.

[cols="1,1,2", options="header"]
|===
|Editor Readonly |Tinycomments_access |Result
|true |comment |The editor is read-only, but users can add or delete new comments.
|false |comment |The editor is read-only, but users can add or delete new comments.
|===

.Example
[source,javascript]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'tinycomments',
  toolbar: 'addcomment showcomments',
  readony: true, // set the editor to read-only mode
  tinycomments_access: 'comment' 
});
----

liveDemo::comments-ui-mode[]

=== `tinycomments_access` _is not configured and `readonly` set to `true`_

When `tinycomments_access` is not configured, the editor will remain in read-only mode, and the comments will be in read-only mode. This means that users cannot edit the content or add comments.

[cols="1,1,2", options="header"]
|===
|Editor Readonly |Tinycomments_access |Result
|true |not specified |readonly editor, readonly comments
|false |not specified |Default behavior, full editing rights to the comments and editor
|===

.Example
[source,javascript]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'tinycomments',
  toolbar: 'addcomment showcomments',
  readony: true, // set the editor to read-only mode
});
----

liveDemo::comments-readonly-mode[]