[[custom_elements]]
== `+custom_elements+`

This option enables you to specify non-HTML elements for the editor.

This way you can handle non-HTML elements inside an HTML editor. You can prefix the element names with a `+~+` if you want the element to behave as a `+span+` element and not a `+div+` element.

*Type:* `+String+` or `+Object+`

=== Simple string format

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  extended_valid_elements: 'mycustomblock[id],mycustominline',
  custom_elements: 'mycustomblock,~mycustominline' // Notice the ~ prefix to force a span element for the element
});
----

=== Record format

The `custom_elements` option and the `addCustomElements` API support a record structure. The key is the element name, and the value is a specification object with the following properties:

`+extends+` (string)::
  The element name from which the new element inherits its default properties. Using `extends` also adds the new element as a valid child wherever the extended element is valid. For example, `extends: "div"` makes the custom element block-level and allows it wherever `div` is allowed.

`+attributes+` (array of strings)::
  List of attribute names or the preset `@global`. Each string is either an attribute name or the preset `@global`, which expands to the schema's global attributes (see <<attribute-preset-global>>). For example: `["@global", "data-type", "data-id"]`.

`+children+` (array of strings)::
  List of valid child element names or presets. Each string is either an element name or one of the presets `@blocks`, `@phrasing`, or `@flow`. See <<html4>>, <<html5>>, and <<html5-strict>> for the exact element sets per schema.

`+padEmpty+` (boolean)::
  Defaults to `false`. When `true`, the element is padded with content (for example, a non-breaking space) when saved so that it always has some content. Use for elements that must not be empty.

`+componentUrl+` (string)::
  URL of the web component script to load into the editor. Use when the custom element is a web component that requires its script to render.

[[attribute-preset-global]]
=== Attribute preset: `@global`

The `@global` preset in the `attributes` array expands to the schema's global attributes. The exact set depends on the schema type:

[[html4]]
=== HTML Element Sets: `html4`

[cols="1,3",options="header"]
|===
| Type | Expected
| @blocks | address, blockquote, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, menu, ol, p, pre, table, ul, center, dir, isindex, noframes
| @phrasing | a, abbr, b, bdo, br, button, cite, code, del, dfn, em, embed, i, iframe, img, input, ins, kbd, label, map, noscript, object, q, s, samp, script, select, small, span, strong, sub, sup, textarea, u, var, #text, #comment, acronym, applet, basefont, big, font, strike, tt
| @flow | Same as @blocks + @phrasing
| @global (attributes) | id, accesskey, class, dir, lang, style, tabindex, title, role, xml:lang
|===

[[html5]]
=== HTML Element Sets: `html5`

[cols="1,3",options="header"]
|===
| Type | Expected
| @blocks | address, blockquote, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, menu, ol, p, pre, table, ul, article, aside, details, dialog, figure, main, header, footer, hgroup, section, nav, a, ins, del, canvas, map, center, dir, isindex, noframes
| @phrasing | a, abbr, b, bdo, br, button, cite, code, del, dfn, em, embed, i, iframe, img, input, ins, kbd, label, map, noscript, object, q, s, samp, script, select, small, span, strong, sub, sup, textarea, u, var, #text, #comment, audio, canvas, command, data, datalist, mark, meter, output, picture, progress, time, wbr, video, ruby, bdi, keygen, svg, acronym, applet, basefont, big, font, strike, tt
| @flow | Same as @blocks + @phrasing
| @global (attributes) | id, accesskey, class, dir, lang, style, tabindex, title, role, contenteditable, contextmenu, draggable, dropzone, hidden, spellcheck, translate, itemprop, itemscope, itemtype, xml:lang
|===

[[html5-strict]]
=== HTML Element Sets: `html5-strict`

[cols="1,3",options="header"]
|===
| Type | Expected
| @blocks | address, blockquote, div, dl, fieldset, form, h1, h2, h3, h4, h5, h6, hr, menu, ol, p, pre, table, ul, article, aside, details, dialog, figure, main, header, footer, hgroup, section, nav, a, ins, del, canvas, map
| @phrasing | a, abbr, b, bdo, br, button, cite, code, del, dfn, em, embed, i, iframe, img, input, ins, kbd, label, map, noscript, object, q, s, samp, script, select, small, span, strong, sub, sup, textarea, u, var, #text, #comment, audio, canvas, command, data, datalist, mark, meter, output, picture, progress, time, wbr, video, ruby, bdi, keygen, svg
| @flow | Same as @blocks + @phrasing
| @global (attributes) | id, accesskey, class, dir, lang, style, tabindex, title, role, contenteditable, contextmenu, draggable, dropzone, hidden, spellcheck, translate, itemprop, itemscope, itemtype
|===

=== Example using `+custom_elements+` with presets such as `@blocks`, `@phrasing`, and `@flow`

[source, js]
----
tinymce.init({
  selector: "textarea",
  // Add custom elements using the custom_elements option
  custom_elements: {
    // Custom element 'foo-bar' extends 'div' with attributes 'attr1' and 'attr2'
    "foo-bar": {
      extends: "div",
      attributes: ["attr1", "attr2"],
    },
    // Custom element 'foo-baz' extends 'span' allowing children '@phrasing' and 'foo-child'
    "foo-baz": {
      extends: "span",
      children: ["@phrasing", "foo-child"],
    },
    // Custom element 'foo-child' has no specific configuration
    "foo-child": {},
  },
  // You can also use the addCustomElements API to add custom elements
  setup: (editor) => {
    editor.on("preinit", () => {
      editor.schema.addCustomElements({
        // Custom element 'hey-bar' extends 'div' with attributes 'attr1' and 'attr2' as well as all global attributes
        "hey-bar": {
          extends: "div",
          attributes: ["@global", "attr1", "attr2"],
        },
        // Custom element 'hey-baz' extends 'span' allowing children 'hey-child' as well as all phrasing content
        "hey-baz": {
          extends: "span",
          children: ["@phrasing", "hey-child"],
        },
        // Custom element 'hey-child' has no specific configuration
        "hey-child": {},
      });
    });
  },
});
----

[[example-using-custom_elements-with-block-level-and-inline-level-components]]
=== Example using `+custom_elements+` with `padEmpty` and `componentUrl`

[source, js]
----
tinymce.init({
  selector: "textarea",
  custom_elements: {
    // Custom element that is padded when empty
    "my-empty-padded": {
      extends: "div",
      padEmpty: true,
    },
    // Block-level custom element (behaves like a div) with web component
    "my-custom-block": {
      extends: "div",
      attributes: ["@global", "data-type", "data-id"],
      children: ["@flow"],
      componentUrl: "/path/to/block-component.js"
    },
    // Inline-level custom element (behaves like a span) with web component
    "my-custom-inline": {
      extends: "span",
      attributes: ["@global", "data-value"],
      children: ["@phrasing"],
      componentUrl: "/path/to/inline-component.js"
    }
  }
});
----
