[[details_serialized_state]]
== `details_serialized_state`

This option sets the state of Accordion sections when content in a {productname} instance is saved.

When set to `+collapsed+`, all Accordions are set to closed on content save.

When set to `+expanded+`, all Accordions are set to open on content save.

When set to `+inherited+`, Accordions preserve their individual state on content save.

The default value for this option is `+inherited+`.

*Type:* `+String+`

*Possible values:* `+inherited+`, `+collapsed+`, `+expanded+`

*Default value:* `+inherited+`

=== Example: using `details_serialized_state` to close all Accordions on content save

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  details_serialized_state: 'collapsed',
});
----

=== Example: using `details_serialized_state` to save pre-configured `<details>` content in new {productname} documents as closed

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'preview', // added to this example for UX demonstration purposes; see the NOTE below
  newdocument_content: '<details><summary>Accordion summary...</summary><p>Accordion body...</p></details>',
  details_initial_state: 'expanded',
  details_serialized_state: 'collapsed',
});
----

[NOTE]
====
The option does not require the xref:accordion.adoc[Accordion] plugin be loaded to come into effect.

In the above example, when menu:File[New document] is selected, the xref:content-behavior-options#newdocument_content[`newdocument_content`] option puts a `<details>` element into the new editor instance.

The `details_initial_state` option causes that element to present as open while the `details_serialized_state` sets the saved content state to closed.

This example also demonstrates a potential UX issue with, in effect, setting `details_initial_state` and `details_serialied_state` at odds. Choosing menu:File[New document] results in a new editor instance containing an Accordion element presented open, as set by `details_initial_state`.

Choosing menu:File[Preview] shows this same newly-created document with a _closed_ Accordion element, as set by `details_serialized_state`.

The difference is expected, given the option values. It may, nonetheless, be experienced as a UX inconsistency for some end-users.
====
