[[persistent]]
=== `persistent`

include::partial$misc/admon-requires-6.6v.adoc[]

The `+persistent+` property, when set to `+true+`, allows an inline dialog to stay open when the dialog no longer has focus.

If an end-user gives another part of the {productname} editor focus (for example, the document editor, or a menu), the inline dialog will stay open.

The property has a default value of `+false+`.

NOTE: if an inline dialog is open and focus is switched away from the {productname} editor entirely (by, for example, the end-user switching focus to an available host-browser UI element), an open inline dialog will remain open regardless of the `+persistent+` property’s value. This was the behavior prior to this property being available and continues to be the behavior.

*Type:* `+String+`

*Possible values:* `+true+`, `+false+`

*Default value:* `false`

=== Example: using `persistent`

// This should be a working configuration. Please test.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  persistent: 'bottom'  // Demonstration fiddle for sample code: <https://fiddle.tiny.cloud/DBiaab>
});
----
