[[align]]
== `align`

////
Add optional align property to labels to control text alignment

Right-text alignment would help align the disclaimer label to the right of the dialog:
////

////
What does the option do? Why/when use it?
What is the values you can use and what do they do?
Is there any risks? (But explain them without saying the word `risk` or similar. Use warnings if needed.) For longer, complicated 'risks' and issues, use the limitations section.
////

*Type:* `+String+`

*Possible values:* `'+start+'`, `'+center+'`, `+end+`

*Default value:* `+start+`

=== Example: using `align` to set a dialog caption as end-aligned

NOTE: End-aligned is right-aligned when a left-to-right language is the display language. Equivalently, end-aligned is left-aligned when a right-to-left language is the display language.

[source,js]
----
tinymce.activeEditor.windowManager.open({
  title: 'Dialog Title', // The dialog's title - displayed in the dialog header
  body: {
    type: 'panel', // The root body type - a Panel or TabPanel
    items: [ 
        {
          type: 'label', // component type
          label: 'Caption', // text for the group label
          align: `end`,
          items: [
            {
              type: 'htmlpanel', // an HTML panel component
              html: 'Panel content goes here.'
            }
          ] 
        }
    ]
  },
  buttons: [ // A list of footer buttons
    {
      type: 'submit',
      text: 'OK'
    }
  ]
});
----

// Remove if not applicable
=== Limitation of the `align` option

The `align` option has the following limitations.

<List the things we can't or wont fix, as well as complicated complications and risks>
