[[exportword-service-url]]
== `exportword_service_url`

The {pluginname} uses the HTML to DOCX converter service to generate the Word files.

The {pluginname} feature is currently only available exclusively for `on-premise` setups, requiring a self-hosted HTML to DOCX converter service and the `exportword_service_url` option to be properly configured. If you require access to this feature, please link:https://www.tiny.cloud/contact/[contact us]. Refer to our xref:individual-import-from-word-and-export-to-word-on-premises.adoc[on-premises documentation] for detailed instructions on deploying the {pluginname} service server-side component using Docker.

[TIP]
Update the `exportword_service_url` configuration in your {productname} setup to point to your host. For instance, if your host is `mycustomhost.com`, the URL will be `https://mycustomhost.com/v1/convert`.

*Type:* `+String+`

=== Example: using `exportword_service_url`

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'exportword',
  toolbar: 'exportword',
  exportword_service_url: '<service_URL>'
});
----

[[exportword-converter-options]]
== `exportword_converter_options`

The `exportword_converter_options` option, is used to specify and configure various options related to the process of converting and exporting content from the editor to `.docx` Word file.

*Type:* `+Object+`

*Default value:* `{}`

=== Example: using `exportword_converter_options`

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'exportword',
  toolbar: 'exportword',
  exportword_service_url: '<service_URL>',
  exportword_converter_options: {
    header: [
      {
        html: '<h1>First page header.</h1>', //example
        css: 'h1 { font-size: 30px; }', //example
      }
    ],
  },
});
----

[NOTE]
To use this option, the Export to Word plugin requires the `exportword_service_url` option to be configured.

> For comprehensive details regarding the `exportword_converter_options`, please refer to the https://exportdocx.converter.tiny.cloud/docs#section/Export-to-Word[API documentation^] available for the {pluginname} Premium plugin.

[[exportword-converter-style]]
== `exportword_converter_style`

The `exportword_converter_style` option allow for customization of the styles applied to the exported Word document, providing flexibility in controlling its appearance.

*Type:* `+String+`

*Default value:* `''`

=== Example: using `exportword_converter_style`

[source,js]
----
tinymce.init({
  selector: 'textarea.tinymce',
  plugins: 'exportword',
  toolbar: 'exportword',
  exportword_service_url: '<service_URL>', // required
  exportword_converter_options: { // required to support "exportword_converter_style"
    header: [
      {
        html: '<h1>First page header.</h1>', //example
        css: 'h1 { font-size: 30px; }', //example
      }
    ],
  },
  exportword_converter_style: 'p { color: cyan !important }'
});
----