[[external_plugins]]
== `+external_plugins+`

This option allows a URL based location of plugins to be provided that are outside of the normal {productname} plugins directory.

{productname} will attempt to load these as per regular plugins when starting up. This option is useful when loading {productname} from a CDN or when the {productname} directory is separate from custom plugins.

This value should be set as a JavaScript object that contains a property for each {productname} plugin to be loaded. This property should be named after the plugin and should have a value that contains the location that the plugin that will be loaded from.

The URLs provided can be:

* *Absolute URLs*: Including the protocol, such as `+https://www.example.com/plugin.min.js+`.
* *Relative to the root directory of the web-server*: Including the leading "`+/+`" to indicate that it is relative to the web-server root, such as `+/plugin.min.js+`.
* *Relative to the {productname} `+base_url+`*: A relative path without the leading "`+/+`", such as `+../../myplugins/plugin.min.js+`. By default, the `+base_url+` is the directory containing {productname} javascript file (such as `+tinymce.min.js+`). For information on the `+base_url+` option, see: xref:editor-important-options.adoc#base_url[Integration and setup options - `+base_url+`].

*Type:* `+Object+`

*Default value:* `+undefined+`

=== Example: using `+external_plugins+`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  external_plugins: {
    'testing': 'http://www.testing.com/plugin.min.js',
    'maths': 'http://www.maths.com/plugin.min.js'
  }
});
----
