[[external_plugins]]
== `+external_plugins+`

This option allows plugins to be loaded from outside the default {productname} plugins directory. {productname} will attempt to load these plugins as usual when starting up, provided the required files exist.

This can be useful when:

* Using custom plugins.
* Loading {productname} from a CDN but not the plugins.
* Loading premium plugins from the tinymce-premium NPM package, without bundling or file stacking.
* Loading plugins from any location separate to the core {productname} files.

This option takes an object which contains `+key-value+` pairs of plugin names and the location their JavaScript file should be loaded from as a URL.

The URLs provided can be:

* *Absolute URLs*: Including the protocol, such as `+https://www.example.com/plugin.min.js+`.
* *Relative to the root directory of the web-server*: Including the leading "`+/+`" to indicate that it is relative to the web-server root, such as `+/plugin.min.js+`.
* *Relative to the {productname} `+base_url+`*: A relative path without the leading "`+/+`", such as `+../../myplugins/plugin.min.js+`. By default, the `+base_url+` is the directory containing {productname} javascript file (such as `+tinymce.min.js+`). For information on the `+base_url+` option, see: xref:editor-important-options.adoc#base_url[Integration and setup options - `+base_url+`].

*Type:* `+Object+`

=== Example: using `+external_plugins+`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  external_plugins: {
    'customplugin': 'https://cdn.example.com/customplugin/plugin.min.js',
    'advcode': '/<path_to_tinymce-premium>/plugins/advcode/plugin.min.js'
  },
  plugins: 'customplugin advcode',
  // ... other configuration
});
----

include::partial$configuration/external_plugins-premium-npm.adoc[]

[NOTE]
====
For more information on URL formats and path resolution, see the xref:editor-important-options.adoc#base_url[`+base_url+` option].
====
