[[fullscreen_native]]
== `+fullscreen_native+`

ifeval::["{plugincode}" != "fullscreen"]
NOTE: The `+fullscreen_native+` option requires the Fullscreen plugin.
endif::[]

The `+fullscreen_native+` option allows the editor to use the browser full screen mode, rather than only filling the https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts#What_is_a_viewport[browser window] when full screen mode is enabled. This functionality is the same as full screen mode for online videos.

*Type:* `+Boolean+`

*Possible values:* `+true+`, `+false+`

*Default value:* `+false+`

=== Example: using `+fullscreen_native+`

To use the browser-native full screen mode for the {productname} editor, set `+fullscreen_native+` to `+true+`. For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'fullscreen',
  toolbar: 'fullscreen',
  fullscreen_native: true
});
----

=== Limitations of the `+fullscreen_native+` option

The `+fullscreen_native+` option has the following limitations. When `+fullscreen_native+` is enabled:

* The Escape keyboard key (Esc) will exit full screen mode. Default editor behavior of the Esc key will be overridden by browser and the Esc key will exit full screen mode instead of closing dialogs, menus, or moving focus from the editor UI to the editor content. This may lead to accessibility issues.
* For Firefox users, the full screen keyboard shortcut (Command+Shift+F or Ctrl+Shift+F) cannot be used to repeatedly toggle the browser-native full screen mode on and off without interacting with the editor between on toggles. If the user does not interact with the editor between off and on toggles, the plugin will fall-back to filling the browser window.
* If the editor is initialized inside an iframe element, full screen mode will only fill the iframe on Firefox.
