== quickbars_image_toolbar

The *quickbars_image_toolbar* option configures the Quick Image toolbar provided by the link:quickbars.html[quickbars plugin]. To change the buttons on the Quick Image toolbar, provide a space-separated string of link:/interface/toolbars/available-toolbar-buttons/[toolbar button names]. The Quick Image toolbar is intended for image-related buttons, but any link:/interface/toolbars/available-toolbar-buttons/[{productname} toolbar buttons] or link:/how-to-guides/creating-custom-ui-components/toolbar-buttons/custom-toolbarbuttons/[custom toolbar buttons] are allowed.

To disable the Quick Image toolbar, set `+quickbars_image_toolbar+` to `+false+`.

Type : `+String+` or `+false+`

Defaults : `+'alignleft aligncenter alignright'+`

=== Example: Customizing the Quick Image toolbar

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars image imagetools',
  quickbars_image_toolbar: 'alignleft aligncenter alignright | rotateleft rotateright | imageoptions'
});
----

=== Example: Disabling the Quick Image toolbar

To disable the Quick Image toolbar, set `+quickbars_image_toolbar+` to `+false+`.

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars',
  quickbars_image_toolbar: false
});
----
