ifeval::["{plugincode}" == "export"]
[[export_cors_hosts]]
== `+export_cors_hosts+`
endif::[]
ifeval::["{plugincode}" != "export"]
[[imagetools_cors_hosts]]
== `+imagetools_cors_hosts+`
endif::[]

The {pluginname} plugin cannot work with images from another domains due to security measures imposed by browsers on so called cross-origin HTTP requests. To overcome these constraints, Cross-Origin Resource Sharing (CORS) must be explicitly enabled on the specified domain(s) (for more information check https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS[HTTP access control]).

An array of supported domains for the images (with CORS enabled on them) can be supplied to {productname} via the `{plugincode}_cors_hosts` option.

NOTE: Each string in the array _must_ be in the format of `+mydomain.com+`. Do not include protocols (`+http://, https://+`) or any trailing slashes in your domains.

NOTE: `{plugincode}_cors_hosts` is *not* required when enabling this plugin via xref:editor-and-features.adoc[{cloudname}].

Type: `+String[]+`

Default Value: `+[]+`

=== Example: `{plugincode}_cors_hosts`

[source,js,subs="attributes+"]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: '{plugincode}',
  plugins: 'image {plugincode}',
  {plugincode}_cors_hosts: [ 'mydomain.com', 'otherdomain.com' ]
});
----
