[[quickbars_image_toolbar]]
== `+quickbars_image_toolbar+`

The *quickbars_image_toolbar* option configures the Quick Image toolbar provided by the xref:quickbars.adoc[quickbars plugin]. To change the buttons on the Quick Image toolbar, provide a space-separated string of xref:available-toolbar-buttons.adoc[toolbar button names]. The Quick Image toolbar is intended for image-related buttons, but any xref:available-toolbar-buttons.adoc[{productname} toolbar buttons] or xref:custom-toolbarbuttons.adoc[custom toolbar buttons] are allowed.

To disable the Quick Image toolbar, set `+quickbars_image_toolbar+` to `+false+`.

*Type:* `+String+` or `+false+`

*Default value:* `+'alignleft aligncenter alignright'+`

=== Example: customizing the Quick Image toolbar

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'quickbars image editimage',
  quickbars_image_toolbar: 'alignleft aligncenter alignright | rotateleft rotateright | imageoptions'
});
----

=== Example: disabling the Quick Image toolbar

To disable the Quick Image toolbar, set `+quickbars_image_toolbar+` to `+false+`.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'quickbars',
  quickbars_image_toolbar: false
});
----
