== quickbars_insert_toolbar

The *quickbars_insert_toolbar* option configures the Quick Insert toolbar provided by the link:{baseurl}/plugins-ref/opensource/quickbars/[quickbars plugin]. To change the buttons on the Quick Insert toolbar, provide a space-separated string of [toolbar button names](\{\{ site.baseurl }}/interface/toolbars/available-toolbar-buttons/). The Quick Insert toolbar is intended for buttons related to inserting content, but any [\{\{site.productname}} toolbar buttons](\{\{ site.baseurl }}/interface/toolbars/available-toolbar-buttons/) or [custom toolbar buttons](\{\{ site.baseurl }}/how-to-guides/creating-custom-ui-components/toolbar-buttons/custom-toolbarbuttons/) are allowed.

To disable the Quick Insert toolbar, set `+quickbars_insert_toolbar+` to `+false+`.

Type : `+String+`

Defaults : `+'quickimage quicktable'+`

=== Example: Customizing the Quick Insert toolbar

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars pagebreak',
  quickbars_insert_toolbar: 'quickimage quicktable | hr pagebreak'
});
----

=== Example: Disabling the Quick Insert toolbar

To disable the Quick Insert toolbar, set `+quickbars_insert_toolbar+` to `+false+`.

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars',
  quickbars_insert_toolbar: false
});
----
