[[quickbars_insert_toolbar]]
== `+quickbars_insert_toolbar+`

The *quickbars_insert_toolbar* option configures the Quick Insert toolbar provided by the xref:quickbars.adoc[quickbars plugin]. To change the buttons on the Quick Insert toolbar, provide a space-separated string of xref:available-toolbar-buttons.adoc[toolbar button names]. The Quick Insert toolbar is intended for buttons related to inserting content, but any xref:available-toolbar-buttons.adoc[{productname} toolbar buttons] or xref:custom-toolbarbuttons.adoc[custom toolbar buttons] are allowed.

To disable the Quick Insert toolbar, set `+quickbars_insert_toolbar+` to `+false+`.

*Type:* `+String+`

*Default value:* `+'quickimage quicktable'+`

=== Example: customizing the Quick Insert toolbar

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'quickbars pagebreak',
  quickbars_insert_toolbar: 'quickimage quicktable | hr pagebreak'
});
----

=== Example: disabling the Quick Insert toolbar

To disable the Quick Insert toolbar, set `+quickbars_insert_toolbar+` to `+false+`.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'quickbars',
  quickbars_insert_toolbar: false
});
----
