[[invalid_elements]]
== `+invalid_elements+`

This option instructs the editor to remove specific elements when {productname} executes a cleanup. This option should contain a comma-separated list of element names to exclude from the content.

*Type:* `+String+`

=== Example: using `+invalid_elements+`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  invalid_elements: 'strong,em'
});
----

CAUTION: This option does not accept attributes in the list, only elements.

IMPORTANT: The `+invalid_elements+` option takes precedence over element rules with exact names in the xref:content-filtering.adoc#valid_elements[`+valid_elements+`] and xref:content-filtering.adoc#extended_valid_elements[`+extended_valid_elements+`] options. It has no effect on elements that match a wildcard rule, such as `+*[*]+`, `+*[class]+`, or `+h?+`, in either option.

Also see xref:content-filtering.adoc#valid_elements[valid_elements] and xref:content-filtering.adoc#extended_valid_elements[extended_valid_elements] for more configuration options.
