[[mentions_item_type]]
== `+mentions_item_type+`

This option sets which user interface item type to use when displaying the list of users.

* The `+name+` item will only display the user's name.
* The `+profile+` item will display the user's name and can display an optional image and description.

For information on the properties required for the user object provided to xref:mentions.adoc#mentions_fetch[`+mentions_fetch+`], see: xref:user-properties[User properties].

*Type:* `+String+`

*Possible values:* `+'name'+`, `+'profile'+`

*Default value:* `+'name'+`

.Example: using `+mentions_item_type+`

[source,js]
----
tinymce.init({
  selector: 'textarea',
  plugins: 'mentions',
  mentions_item_type: 'name'
});
----

[[user-properties]]
=== User properties

The following table describes the properties available for user objects provided to the xref:mentions.adoc#mentions_fetch[`+mentions_fetch+` callback]. Properties may be required, optional, or not available; depending on the xref:mentions_item_type[`+mentions_item_type+`] and xref:mentions_select[`+mentions_select+`] options.

[cols="1,1,1,1,4",options="header"]
|===
| Name        | Value      | `+name+`      | `+profile+` | Description
| id          | `+String+` | required      | required    | Used to identify the user mention in different callbacks
| name        | `+String+` | required      | required    | Name to display and highlight matches
| image       | `+String+` | not available | optional    | Image source for user avatar
| description | `+String+` | not available | optional    | Description to display
|===
