[[object_resizing]]
== object_resizing

This options allows you to turn on/off the resizing handles on images, tables or media objects. This option is enabled by default and allows you to resize table and images. You can also specify a CSS3 selector of what you want to enable resizing on.

[[disable-all-resizing-of-imagestables]]
=== Disable all resizing of images/tables 
anchor:disableallresizingofimagestables[historical anchor]

*Type:* `Boolean`, `String`

*Default Value:* `true`

*Possible Values:* `true`, `false`, `img`

[discrete]
[[example]]
===== Example

`js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  object_resizing : false
});
`

[[enable-resizing-on-images-only]]
=== Enable resizing on images only 
anchor:enableresizingonimagesonly[historical anchor]

*Type:* `Boolean`, `String`

*Default Value:* `true`

*Possible Values:* `true`, `false`, `img`

[discrete]
===== Example

`js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  object_resizing : 'img'
});
`
