[[resize]]
== `+resize+`

This option allows the resize handle to be disabled or to set the resize handler to resize both horizontally and vertically. The option can be `+true+`, `+false+` or the string `+'both'+`. `+false+` disables resizing, `+true+` enables vertical resizing only, `+'both'+` makes it possible to resize in both directions horizontal and vertical.

When resizing is enabled, the editor can be resized by either:

* Clicking and dragging the resize handle in the bottom right-hand corner of the editor.
* Focusing the resize handle, and using the arrow keys. The *Up Arrow* and *Left Arrow* keys will make the editor smaller, and the *Down Arrow* and *Right Arrow* keys will make the editor larger.

*Type:* `+Boolean+` or `+String+`

*Possible values:* `+true+`, `+false+`, or `+'both'+`

*Default value:* `+true+` for desktop, `+false+` for mobile

include::partial$misc/admon-different-default-for-mobile.adoc[]

=== Example: disabling editor resizing

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  resize: false
});
----

=== Example: enabling vertical and horizontal editor resizing

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  resize: 'both'
});
----
