[[rtc_user_details_provider]]
== `+rtc_user_details_provider+`

By default, a user's unique ID (`+userId+`, the `+sub+` field from their xref:rtc-jwt-authentication.adoc#required-jwt-claims-for-real-time-collaboration[JWT]) will be displayed as the username in remote caret tooltips.

To display a descriptive name on the caret, the `+userId+` needs to be resolved into user details that include the user's display name (`+fullName+`). This resolution is done on each client to avoid sending any personal information through the RTC server.

Only the `+fullName+` is required, but the whole object will be stored within the RTC caret information for use with the xref:rtc-options-optional#rtc_client_connected[`+rtc_client_connected+`] and xref:rtc_client_disconnected[`+rtc_client_disconnected+`] callbacks to avoid duplicate lookup queries. The user details are also passed to the `+RtcClientConnected+` and `+RtcClientDisconnected+` events.

This provider function is called once for each connecting client. Clients that reconnect may trigger a new call to the provider function rather than using cached data.

ifeval::["{plugincode}" != "rtc"]
Required plugin : xref:rtc-introduction.adoc[Real-Time Collaboration (`+rtc+`)]
endif::[]

Type : `+Function+` (Returns a https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise])

Input parameters :
[cols=",,",options="header",]
|===
|Field |Type |Description
|`+userId+` | `+string+` | User ID to resolve into user details.
|===

Return data :
[cols=",,",options="header",]
|===
|Field |Type |Description
|`+fullName+` | `+string+` | The full display name of user. For example: `+"John Doe"+`.
|any custom field | `+any+` | Extra user data for use in the xref:rtc-options-optional.adoc#rtc_client_connected[`+rtc_client_connected+` API].
|===

=== Example of providing static user details

[source,js]
----
tinymce.init({
  selector: 'textarea', // change this value according to your HTML
  plugins: 'rtc',
  rtc_document_id: 'unique-document-id',
  rtc_encryption_provider: () => Promise.resolve({ key: 'a secret key' }),
  rtc_token_provider: () => Promise.resolve({ token: 'signed-JWT-token' }),
  rtc_user_details_provider: ({ userId }) => Promise.resolve({ fullName: "John Doe" })
});
----

=== Example of providing user details from your server

[source,js]
----
tinymce.init({
  selector: 'textarea', // change this value according to your HTML
  plugins: 'rtc',
  rtc_document_id: 'unique-document-id',
  rtc_encryption_provider: () => Promise.resolve({ key: 'a secret key' }),
  rtc_token_provider: () => Promise.resolve({ token: 'signed-JWT-token' }),
  rtc_user_details_provider: ({ userId }) =>
    fetch('/getUserDetails', {
      method: 'POST',
      credentials: 'include',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ userId })
    })
    .then((response) => response.json())
    .then(({ fullnamefromserver })) => ({ fullName: fullnamefromserver })
    .catch((error) => console.log('Failed to retrieve user details\n' + error))
});
----
