[[rtc_token_provider]]
== `+rtc_token_provider+`

The RTC plugin and the RTC service uses https://jwt.io/introduction/[JSON Web Tokens (JWT)] to authenticate the user. The user's token should include:

* A unique user ID (`+sub+`).
* A relative expiration time (`+exp+`).

The `+rtc_token_provider+` function will be called one or more times to refresh the token before it expires. For production usage, {companyname} recommends a token provider with a dynamic request that produces a new JWT token with an updated `+exp+` claim.

For information on generating and serving JWTs for {productname} RTC, see: xref:rtc-jwt-authentication.adoc[Real-Time Collaboration (RTC) JWT Authentication Setup].

ifeval::["{plugincode}" != "rtc"]
Required plugin : xref:rtc-introduction.adoc[Real-Time Collaboration (`+rtc+`)]
endif::[]

Type : `+Function+` (Returns a https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise])

Input parameters :
[cols=",,",options="header",]
|===
|Field |Type |Description
|`+documentId+` |`+string+` | The document ID from the xref:rtc-options-required.adoc#rtc_document_id[`+rtc_document_id+`] option.
|===

Return data :
[cols=",,",options="header",]
|===
|Field |Type |Description
|`+token+` |`+string+` | A generated JWT token. This token should be signed with a private key as described in xref:rtc-jwt-authentication.adoc#jwt-endpoint-requirements[JWT authentication].
|===

=== Required JWT claims

[cols=",^,",options="header",]
|===
|Field |Type |Description
|`+sub+` |`+string+` |The unique user ID (If `+sub+` is the same for two clients, the server will trust them as if they are the same user).
|`+exp+` |`+integer+` |A timestamp indicating the token expiry date and time.
|===

=== Example: Using `+rtc_token_provider+`

This example shows the minimum required configuration for the Real-Time Collaboration plugin, including the `+rtc_token_provider+` option.

[source,js]
----
tinymce.init({
  selector: 'textarea#rtc-example',
  plugins: 'rtc',
  rtc_document_id: 'unique-document-id',
  rtc_encryption_provider: () => Promise.resolve({ key: 'a secret key' }),
  rtc_token_provider: ({ documentId }) =>
    fetch('/getJwtToken', {
      method: 'POST',
      credentials: 'include',
      body: JSON.stringify({ documentId }),
    })
    .then((response) => response.json())
    .then(({ jwt })) => ({ token: jwt })
    .catch((error) => console.log('Failed to return a JWT\n' + error))
});
----
