== quickbars_selection_toolbar

The *quickbars_selection_toolbar* option configures the Quick Selection toolbar provided by the link:quickbars.html[quickbars plugin]. To change the buttons on the Quick Selection toolbar, provide a space-separated string of link:/interface/toolbars/available-toolbar-buttons/[toolbar button names]. The Quick Selection toolbar is intended for buttons related to formatting content, but any link:/interface/toolbars/available-toolbar-buttons/[{productname} toolbar buttons] or link:/how-to-guides/creating-custom-ui-components/toolbar-buttons/custom-toolbarbuttons/[custom toolbar buttons] are allowed.

To disable the Quick Selection toolbar, set `+quickbars_selection_toolbar+` to `+false+`.

Type : `+String+`

Defaults : `+'bold italic | quicklink h2 h3 blockquote'+`

=== Example: Customizing the Quick Selection toolbar

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars',
  quickbars_selection_toolbar: 'bold italic | formatselect | quicklink blockquote'
});
----

=== Example: Disabling the Quick Selection toolbar

To disable the Quick Selection toolbar, set `+quickbars_selection_toolbar+` to `+false+`.

[source,js]
----
tinymce.init({
  selector: 'div.tinymce',
  plugins: 'quickbars',
  quickbars_selection_toolbar: false
});
----
