[[selector]]
== selector

This option allows you to specify a CSS selector for the areas that TinyMCE should make editable.

When using this option in TinyMCE's regular editing mode, the element will be replaced with an `iframe` that TinyMCE will perform all operations within.

[[replace-all-textarea-elements-on-the-page]]
=== Replace all textarea elements on the page
anchor:replacealltextareaelementsonthepage[historical anchor]

*Type:* `String`

[[example]]
===== Example

[source,js]
----
tinymce.init({
  selector: 'textarea'  // change this value according to your HTML
});
----

[[replace-a-textarea-element-with-id-editable]]
=== Replace a textarea element with id 'editable'
anchor:replaceatextareaelementwithideditable[historical anchor]

*Type:* `String`

===== Example

[source,js]
----
tinymce.init({
    selector: 'textarea#editable'
});
----

When using this option in TinyMCE's inline editing mode, the selector can be used on any block element and will edit the content in place instead of replacing the element with an `iframe`.

[[inline-editing-mode-on-a-div-element-with-id-editable]]
=== Inline editing mode on a div element with id 'editable'
anchor:inlineeditingmodeonadivelementwithideditable[historical anchor]

*Type:* `String`

===== Example

[source,js]
----
tinymce.init({
    selector: 'div#editable',
    inline: true
});
----

For more information on the differences between regular and inline editing modes please see this page link:{rootDir}general-configuration-guide/use-tinymce-inline.html[here].
