[[suggestededits_uid]]
== `suggestededits_uid`

The `{plugincode}_uid` is a _required_ option that takes as input a unique string to identify the current user. This is used to attribute changes made by the user.  

*Type:* `+String+`

=== Example: using `{plugincode}_uid`

// Add a working and tested configuration.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_uid: 'unique-identifier' // replace this with a unique string to identify the user 
});
----

[[suggestededits_model]]
== `suggestededits_model`

The `{plugincode}_model` option sets the initial model of the document to begin tracking changes. It takes as input an object representing the document. If no value is set, the plugin will generate the model by default. 

//*Type:* xref:#trackeddocument[TrackedDocument] `+Object+`

=== Example: using `{plugincode}_model`

// Add a working and tested configuration.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_uid: 'unique-identifier', // replace this with a unique string to identify the user 
  suggestededits_model: {
    version: 1, 
    maxId: 0, 
    contents: [
      {
        type: 'p',
        children: [
          { text: 'Hello, World!' }
        ]
      }
    ]
  }
});
----

[[suggestededits_access]]
== `suggestededits_access`

To configure a user's permission to edit the document and review changes, the `{plugincode}_access` option can be set alongside the editor mode.  

*Type:* `+String+`

*Possible Values*: `'full'`, `'suggest'`, `'read'`, `'none'` 

*Default Value*: `'full'`

The possible values set the access level of the review permissions as follows: 

[cols="20%,80%"]
|===
|Value | Review Permission

|`+'full'+`
|Access to the {pluginname} view, with permission to accept, reject, or add suggestions to changes.  

|`+'suggest'+`
|Access to the {pluginname} view, with permission to add suggestions to changes. 

|`+'read'+`
|Readonly access to the {pluginname} view.

|`+'none'+`
|No access to the {pluginname} view.
|===

[NOTE]
The `{plugincode}_access` option can be used in combination with the editor's read-only mode to restrict a user’s editing permission. 

.Example
[source,javascript]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_uid: 'unique-identifier', // replace this with a unique string to identify the user 
  suggestededits_access: 'full' //change this value to set permission to the Suggested Edits view 
  readonly: false //set to true to restrict a user's editing permission
});
----

liveDemo::suggestededits-access[]

[[suggestededits_css_url]]
== `suggestededits_css_url`

The `{plugincode}_css_url` option sets the location where a CSS file containing change annotations in the {pluginname} view should be loaded from. To override the default CSS classes, use this option alongside `{plugincode}_diff_classes`. 

*Type:* `+String+`

*Default value:* `'${pluginUrl}/css/{plugincode}.css'`

=== Example: using `{plugincode}_css_url`

// Add a working and tested configuration.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  suggestededits_css_url: './suggestededits.css'
});
----

[[suggestededits_diff_classes]]
== `suggestededits_diff_classes`

The `{plugincode}_diff_classes` option configures the CSS classes applied to the change annotations in the {pluginname} view. This is useful to set custom styles and must be used in combination with the `{plugincode}_css_url` option. 

[NOTE]
The CSS class names must exist in the xref:{plugincode}_css_url[`+suggestededits_css_url+`].

*Type:* `+Object+`

*Default value:* `addition`, `removal`, `modification`

Below are the default CSS classes: 

[source,js]
----
{
  addition: 'tox-suggestededits__annotation--added',
  removal: 'tox-suggestededits__annotation--removed',
  modification: 'tox-suggestededits__annotation--modified'
}
----

=== Example: using `{plugincode}_diff_classes`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_css_url: './suggestededits.css',
  suggestededits_diff_classes: {
    addition: 'added',
    removal: 'removed',
    modification: 'modified'
  }
});
----
