[[suggestededits_content]]
== `suggestededits_content`
The `{plugincode}_content` option determines where the initial content of the document is loaded from. With this option, you can set the content to be loaded from either the editor or the model, allowing you to control the source of truth for the document.

When set to `'html'`, the editor loads the initial content from the HTML in the textarea or the `content` property. In this case, if a model is provided, it will need to match the content in the editor for the plugin to work correctly

When set to `'model'`, the editor loads the initial content from the `{plugincode}_model` option. In this case, the content in the editor will be overwritten with the content from the model. This would allow you to only require the model for document tracking, though it is still recommended to save the content in the editor externally.

In either case, if a model is not provided, the plugin will generate a new model from the current content of the editor, whether it is empty or not.

*Type:* `+String+`

*Possible Values*: `'html'`, `'model'` 

*Default value:* `'html'`

=== Example: using `{plugincode}_content`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  user_id: 'unique-identifier', // Replace this with a unique string to identify the user
  fetch_users, // Function to fetch users for the user lookup API
  suggestededits_model, // Load the saved model into the editor
  suggestededits_content: 'model' // Only set this if you want to load the initial content from the model
});
----
