[[suggestededits_access]]
== `suggestededits_access`

To configure a user's permission to edit the document and review changes, the `{plugincode}_access` option can be set alongside the editor mode.

*Type:* `+String+`

*Possible Values*: `'full'`, `'feedback'`, `'read'`, `'none'`

*Default Value*: `'full'`

The possible values set the access level of the review permissions as follows:

[cols="20%,80%"]
|===
|Value | Review Permission

|`+'full'+`
|Access to the {pluginname} view, with permission to accept or reject suggestions.  

|`+'feedback'+`
|Access to the {pluginname} view, with permission to add feedback to suggestions.

|`+'read'+`
|Read-only access to the {pluginname} view.

|`+'none'+`
|No access to the {pluginname} view.
|===

=== Example: `suggestededits_access: 'feedback'`
[source,javascript]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_access: 'feedback', // Change this value to set the Suggested Edits view permissions
  readonly: false // Set to true to restrict a user's editing permission
});
----

liveDemo::suggestededits-access-feedback[]

=== Example: `suggestededits_access: 'read'`
[source,javascript]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'suggestededits',
  toolbar: 'suggestededits',
  suggestededits_access: 'feedback', // Change this value to set the Suggested Edits view permissions
  readonly: false // Set to true to restrict a user's editing permission
});
----
liveDemo::suggestededits-access-read[]