[[table_background_color_map]]
== `+table_background_color_map+`

This option is used to specify the default values for the table cell background color picker, which can be opened with the `+tablecellbackgroundcolor+` toolbar button or menu item. If no values are defined, the toolbar button and menu item will use the values or default values of the xref:user-formatting-options.adoc#color_map[`+color_map+` option]. This option does not modify the background color picker in the table dialogs. This option accepts Hex, RGB and HSL color values.

The xref:user-formatting-options.adoc#custom_colors[custom color picker] is not available for the `+tablecellbackgroundcolor+` toolbar button or menu item.

*Type:* `+Array+`

*Default value:* See xref:user-formatting-options.adoc#color_map[`+color_map+` option]

=== Example: using `+table_background_color_map+`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'table',
  toolbar: 'table',
  table_background_color_map: [
    { title: 'Red', value: 'FF0000' },
    { title: 'White', value: 'FFFFFF' },
    { title: 'Yellow', value: 'F1C40F' }
  ]
});
----
