[[tableofcontents_orderedlist]]
== `+tableofcontents_orderedlist+`

By default, Tables of Contents are rendered as unordered lists.

The `+tableofcontents_orderedlist+` option allows Tables of Contents to be rendered as an ordered list.

When the `+tableofcontents_orderedlist+` option is set to `+true+`, Tables of Contents are rendered as numeric ordered lists.

To customise the type of ordered list, add the `+xref:tableofcontents_orderedlist_type[tableofcontents_orderedlist_type]+` option to the configuration.

*Type:* `+Boolean+`

*Default value:* `+'false'+`

*Possible values:* `+'true'+`, `+'false'+`

=== Example: using `+tableofcontents_orderedlist+` to switch from an unordered to an ordered list

[source, js]
----
tinymce.init({
  selector: "textarea", // change this value according to your HTML
  plugins: "tableofcontents",
  toolbar: "tableofcontents",
  tableofcontents_orderedlist: true,
});
----

[NOTE]
====
If the `tableofcontents_orderedlist: true` option is set and no `tableofcontents_orderedlist_type` option is set, the **Table of Contents** plugin defaults to using a numeric ordered list.

This is equivalent to setting `tableofcontents_orderedlist_type: '1'`.
====
