== `+table_border_color_map+`

This option is used to specify the default values for the table cell border color picker, which can be opened with the `+tablecellbordercolor+` toolbar button or menu item. If no values are defined, the toolbar button and menu item will use the values or default values of the link:{{site.baseurl}}/content/user-formatting-options/#color_map[`+color_map+` option]. This option does not modify the border color picker in the table dialogs. This option accepts Hex, RGB and HSL color values.

The link:{{site.baseurl}}/content/user-formatting-options/#custom_colors[custom color picker] is not available for the `+tablecellbordercolor+` toolbar button or menu item.

Type : `+Array+`

Default Value : See link:{{site.baseurl}}/content/user-formatting-options/#color_map[`+color_map+` option]

=== Example: Using `+table_border_color_map+`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'table',
  menubar: 'table',
  toolbar: 'table',
  table_border_color_map: [
    {title: 'Red', value: 'FF0000'},
    {title: 'White', value: 'FFFFFF'},
    {title: 'Yellow', value: 'F1C40F'}
  ]
});
----
