[[toolbar_groups]]
== `+toolbar_groups+`

The `+toolbar_groups+` option creates toolbar buttons that display collections of other toolbar buttons as pop-up toolbars. The style of toolbar shown is based on the current xref:toolbar-configuration-options.adoc#toolbar_mode[toolbar mode]. For example, if `+toolbar_mode+` is set to `+floating+`, the toolbar group pop-ups will appear in a floating shelf.

[NOTE]
====
The `+toolbar_groups+` feature is _only_ supported when using the `+floating+` toolbar mode. If the `+toolbar_groups+` option is used with other toolbar modes, the toolbar group buttons will not be displayed and a warning message will be printed in the console.
====

This option accepts an object, mapping button names to their respective group configurations. Multiple toolbar groups can be defined within this object. For details on configuring toolbar groups, refer to xref:custom-group-toolbar-button.adoc[Creating custom Group toolbar buttons].

*Type:* `+Object+`

.Example: using `+toolbar_groups+`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'formatting | alignleft aligncenter alignright',
  toolbar_groups: {
    formatting: {
      icon: 'bold',
      tooltip: 'Formatting',
      items: 'bold italic underline | superscript subscript'
    }
  }
});
----
