[[toolbar]]
== toolbar

This option allows you to specify the xref:advanced/editor-control-identifiers.adoc#toolbarcontrols[buttons] and the order that they will appear on TinyMCE's toolbar.

[[grouping-toolbar-controls]]
=== Grouping toolbar controls
anchor:groupingtoolbarcontrols[historical anchor]

To specify the controls that should appear on TinyMCE's toolbar, the `toolbar` option should be provided with a space separated list of xref:advanced/editor-control-identifiers.adoc#toolbarcontrols[toolbar controls]. To create groups within this list, please add `|` pipe characters between the groups of controls that you would like to create.

*Type:* `String`

[[example-grouped-toolbar]]
=== Example grouped toolbar
anchor:examplegroupedtoolbar[historical anchor]

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'undo redo | styleselect | bold italic | link image'
});
----

[[disabling-the-toolbar]]
=== Disabling the toolbar
anchor:disablingthetoolbar[historical anchor]

To disable the toolbar, the toolbar option should be provided a boolean value of `false`.

*Type:* `Boolean`

*Default Value:* `true`

*Possible Values:* `true`, `false`

=== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
    toolbar: false
});
----

[[using-multiple-toolbars]]
=== Using multiple toolbars
anchor:usingmultipletoolbars[historical anchor]

To specify multiple toolbars, the toolbar option should be provided with an array of space separated strings.

*Type:* `Array`

=== Example

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: [
    'undo redo | styleselect | bold italic | link image',
    'alignleft aligncenter alignright'
  ]
});
----

Alternatively, you may specify multiple toolbars through the use of the <<toolbarn,toolbar(n)>> option.
