[[trackchanges_model]]
== `trackchanges_model`

The `trackchanges_model` option sets the initial model of the document to be begin tracking changes. It takes as input an object representing the document. If no value is set, the plugin will generate the model by default. 

//*Type:* xref:#trackeddocument[TrackedDocument] `+Object+`

=== Example: using `trackchanges_model`

// Add a working and tested configuration.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'trackchanges',
  toolbar: 'trackchanges',
  trackchanges_model: {
    version: 1, 
    maxId: 0, 
    contents: [
      {
        type: 'p',
        children: [
          { text: 'Hello, World!' }
        ]
      }
    ]
  }
});
----

[[trackchanges_uid]]
== `trackchanges_uid`

The `trackchanges_uid` is a _required_ option that takes as input a unique string to identify the current user. This is used to attribute changes made by the user.  

*Type:* `+String+`

=== Example: using `trackchanges_uid`

// Add a working and tested configuration.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  plugins: 'trackchanges',
  toolbar: 'trackchanges',
  trackchanges_uid: 'unique-identifier' // replace this with a unique string to identify the user 
});
----

[[trackchanges_css_url]]
== `trackchanges_css_url`

The `trackchanges_css_url` option sets the location where a CSS file containing change annotations in the {pluginname} view should be loaded from. To override the default CSS classes, use this option alongside `trackchanges_diff_classes`. 

*Type:* `+String+`

*Default value:* `'${pluginUrl}/css/trackchanges.css'`

=== Example: using `trackchanges_css_url`

// Add a working and tested configuration.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // Change this value according to your HTML
  trackchanges_css_url: './trackchanges.css'
});
----

[[trackchanges_diff_classes]]
== `trackchanges_diff_classes`

The `trackchanges_diff_classes` option configures the CSS classes applied to the change annotations in the {pluginname} view. This is useful to set custom styles and must be used in combination with the `trackchanges_css_url` option. 

[NOTE]
The CSS class names must exist in the xref:trackchanges_css_url[`+trackchanges_css_url+`].

*Type:* `+Object+`

*Default value:* `addition`, `removal`, `modification`

Below are the default CSS classes: 

[source,js]
----
{
  addition: 'tox-trackchanges__annotation--added',
  removal: 'tox-trackchanges__annotation--removed',
  modification: 'tox-trackchanges__annotation--modified'
}
----

=== Example: using `trackchanges_diff_classes`

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'trackchanges',
  toolbar: 'trackchanges',
  trackchanges_css_url: './trackchanges.css',
  trackchanges_diff_classes: {
    addition: 'added',
    removal: 'removed',
    modification: 'modified'
  }
});
----
