[[step-1-include-the-tinymce-script]]
=== Step 1: Include the TinyMCE script

Include this line of code in the `<head>` of your HTML page:

[source,html,subs="+attributes"]
----
<script src="{cdnurl}" referrerpolicy="origin"></script>
----

[[step-2-initialize-tinymce-as-part-of-a-web-form]]
=== Step 2: Initialize TinyMCE as part of a web form

With the script included, initialize {productname} on any element (or elements) in your web page.

Since {productname} lets you identify replaceable elements via a CSS selector, all you need do is pass an object that contains a `selector` to `tinymce.init()`.

In this example, let's replace `<textarea id='mytextarea'>` with a {productname} editor instance by passing the selector `'#mytextarea'` to `tinymce.init()`.

[source,html,subs="+attributes"]
----
<!DOCTYPE html>
<html>
<head>
  <script src="{cdnurl}" referrerpolicy="origin"></script>
  <script type="text/javascript">
  tinymce.init({
    selector: '#mytextarea'
  });
  </script>
</head>

<body>
<h1>{productname} Quick Start Guide</h1>
  <form method="post">
    <textarea id="mytextarea">Hello, World!</textarea>
  </form>
</body>
</html>
----

[[step-3-saving-content-with-a-form-post]]
=== Step 3: Saving content with a form POST

When the `<form>` is submitted the {productname} editor mimics the behavior of a normal HTML `<textarea>` during the `post`. In your form handler you can process the content submitted as if it had come from a regular `<textarea>`.

[[additional-information-about-using-tinymce-cloud]]
=== Additional information about using TinyMCE Cloud

There are a few things you need to consider when using {cloudname}. If you wish to use any local plugins (like http://www.moxiemanager.com[MoxieManager] for example) you need to load them using the new link:{rootDir}configure/integration-and-setup.html#external_plugins[`external_plugins`] option.

Also, if you wish to use a custom language, you need to enter the location of the language file into the new link:{rootDir}configure/localization.html#language_url[`language_url`] option.

You may also want to select a specific version of the editor from {cloudname} and you should head on over to link:{rootDir}cloud-deployment-guide/editor-plugin-version[Specify editor & plugin versions] for details on that.

[NOTE]
====
If you have decided to use {cloudname}, please move on to the next step link:../work-with-plugins/[working with plugins] where you'll start customizing {productname}. If you'd like to learn about other install options please keep reading.
====
