= Checking links as-you-type
:description: Check for valid hyperlinks inside the editor
:keywords: enterprise pricing video youtube vimeo mp3 mp4 mov movie clip film link linkchecking linkchecker mediaembed media
:title_nav: Hyperlink checking

The link:{{ site.baseurl }}/plugins/linkchecker/[Link Checker plugin] provides a link checking service right within the {{site.productname}} editor.

Think of Link Checker as "spell-checking for URLs". But instead of checking spelling, it will let you know if a URL in the editor is valid, invalid or questionable. This is a huge time-saver for anyone who creates content -- no more having to double-check URLs, especially in imported content. Not to mention the benefit of no longer frustrating readers with broken hyperlinks.

Your have two deployment options. One is super easy with {{site.cloudname}}, the other is to go the more traditional Self-hosted route, requiring an additional link:{{ site.baseurl }}/enterprise/server/[server-side component] to be installed and configured.

[#link-checker-self-hosted-setup]
== Link Checker self-hosted setup

Once you have the server-side component installed, additional configuration to your `application.conf` file is required. (Don't forget to restart the Java application server after updating the configuration.)

For information on configuring the server-side component, see: link:{{ site.baseurl }}/enterprise/server/[Configure server-side components].

You will also find more Self-hosted setup information on the link:{{ site.baseurl }}/plugins/linkchecker/[Link Checker plugin page].

[#link-checker-cloud-setup]
== Link Checker cloud setup

link:{{ site.baseurl }}/cloud-deployment-guide/editor-and-features/[{{site.cloudname}}] makes setting up Link Checker a breeze. Simply include the `linkchecker` parameter in your `tinymce.init` and have the {{site.cloudname}} services do the work for you.

{% assign pluginname = 'Link Checker' %}
{% assign pluginminimumplan = 'tierthree' %}
{% assign plugindocspage = 'linkchecker' %}
{% include misc/purchase-premium-plugins.md %}
