= Moxie Manager
:description: MoxieManager. A premium plugin to manage files & images.
:keywords: moxiemanager .net php relative_urls

== File and Image Management Using Moxie Manager

{% include pardot-px-moxiemanager.html %}

MoxieManager is a premium TinyMCE plugin and server system that enables users to insert files located externally to the editor (e.g. on their client desktop) into their document.

MoxieManager is an application separate from TinyMCE that includes .NET or PHP server components. Being built by the team behind TinyMCE it has tight integration with the editor via a toolbar control. It is designed to work with TinyMCE configuration settings such as `relative_urls`.

MoxieManager is a paid addition to TinyMCE. It is included in https://www.tinymce.com/pricing/[TinyMCE subscriptions].

Full documentation on MoxieManager, including how to http://www.moxiemanager.com/documentation/index.php/TinyMCE_Integration[integrate with TinyMCE], can be http://www.moxiemanager.com/documentation/[found] on the MoxieManager website.

We also have a demo for you to explore the Tiny Drive capabilities link:{{site.baseurl}}/demo/moxie-manager/[here].
