:rootDir: ../
:partialsDir: {rootDir}partials/
:imagesDir: {rootDir}images/
include::{rootDir}_attributes.adoc[]
= Paste from Word
:description: Upgrade the Microsoft Word copy-and-paste capabilities of TinyMCE.
:keywords: enterprise powerpaste power paste powerpaste_word_import powerpaste_html_import powerpaste_block_drop powerpaste_allow_local_images microsoft word excel

== Improve your productivity & writing experience

https://about.tiny.cloud/products/powerpaste/[TinyMCE PowerPaste] automatically cleans up content from Microsoft Word and other HTML sources to ensure clean, compliant content that matches the look and feel of your site or app.

TinyMCE PowerPaste is a Premium Plugin from TinyMCE. We have flexible purchase options: as a https://about.tiny.cloud/products/powerpaste/[stand-alone plugin], to https://www.tinymce.com/pricing/[OEM and custom enterprise pricing].

____
Customers: we have full documentation explaining how to install and configure TinyMCE PowerPaste. link:{baseurl}/plugins/powerpaste/[Go to the docs.]
____

== Example use cases

==== Content from Microsoft Word

If you paste content from Microsoft Word into your app, you probably know the published page usually doesn't match the site's style. Fonts can be different, images missing and formatting not the same as their original document.

This can be time consuming for users to fix, and usually involves manually editing HTML. It can also increase support requests.

TinyMCE PowerPaste automatically "`cleans`" pasted content, fixing these issues. It can also automatically upload images to a server, helping you spend time on more productive tasks.

==== Content from Microsoft Excel

TinyMCE PowerPaste also makes light work of pasting Excel content into your app, automatically creating HTML compliant tables in the process.

While developers are very familiar writing HTML tables, most content creators literally don't know where to start. And then there's the issue of manually entering their Excel data into the table. This isn't a fun experience either.

For users of both Word and Excel, PowerPaste will dramatically improve the content production experience you deliver to your clients.

==== Content from the internet

If you cut and paste content from the internet into your app -- which includes almost everyone -- PowerPaste also works its auto-magic.

Just as it cleans up rogue formatting from sources like Word, it does the same for internet content. Need to grab a quote from a website for your blog post? PowerPaste removes classes, minimizing the chance of unwanted CSS overriding your stylesheets.

It also does the same for images, automatically linking to the source image URL. Perfect content, every time.

=== Buy TinyMCE PowerPaste

Start with our https://about.tiny.cloud/products/powerpaste/[dedicated product page] to see our flexible pricing options. OEM and enterprise customers should https://www.tiny.cloud/contact/[contact sales directly]. Still not sure? Check out the demo below.

== PowerPaste demo

++++
<p data-height="600" data-theme-id="0" data-slug-hash="Jbaeyr" data-default-tab="result" data-user="tinymce" class="codepen">
  See the Pen <a href="http://codepen.io/tinymce/pen/Jbaeyr/">Jbaeyr</a>
  by TinyMCE (<a href="http://codepen.io/tinymce">@tinymce</a>)
  on <a href="http://codepen.io">CodePen</a>.
</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
++++
