= Cloud-based file management
:description: Tiny Drive - a premium plugin to manage files & images.
:keywords: tinydrive .net php relative_urls
:title_nav: Cloud-based file management

{{site.cloudfilemanager}} is a premium {{site.productname}} plugin for cloud-based asset management and storage solution. {{site.cloudfilemanager}} is a solution for creating rich text by attaching and embedding images, videos, and other files in your document.

{{site.cloudfilemanager}} presents a cloud-based asset management and storage solution that provides the ease of use of Google Drive without the server requirements of a self-hosted asset manager such as our own MoxieManager.

[#configuring-the-editor-for-tiny-drive]
=== Configuring the editor for Tiny Drive

Once you have the API key, or if you are a current {{site.cloudname}} user who already has an API key, then you have access to {{site.cloudfilemanager}}. In order to get the service up and running, you'll need to complete a few more steps. See our link:{{site.baseurl}}/tinydrive/[documentation] for more information.

____
We are launching the service with a complimentary 100MB of storage and up to 1 GB of bandwidth.
____

[#security-performance]
=== Security & performance

We know security is a primary concern when it comes to cloud storage.  {{site.cloudfilemanager}} uses an https://aws.amazon.com/s3/[Amazon Web Services S3] bucket, the same storage solution used by companies like Netflix, Thomson Reuters, and Zillow.  (You can read about Amazon's comprehensive security approach https://aws.amazon.com/security/[here].)

As your assets are passed back and forth between your {{site.productname}} editor instance and the S3 bucket, {{site.cloudfilemanager}} uses both your API key and a https://jwt.io/introduction/[JSON Web Token] (JWT) to authenticate each data transaction.  Each {{site.cloudfilemanager}} user will need to create their own JWT, and we walk you through the whole process link:{{site.baseurl}}/tinydrive/jwt-authentication/[here].

And to make sure your assets are delivered as fast as possible, we utilize the https://aws.amazon.com/cloudfront/[CloudFront CDN], which is Amazon's global content delivery network, known for its low latency and high data transfer speeds.

[#try-our-tiny-drive-plugin-demo]
=== Try our Tiny Drive plugin demo

{% include codepen.html id="drive-demo" %}

{% assign pluginname = 'Tiny Drive' %}
{% assign pluginminimumplan = 'tierone' %}
{% assign plugindocspage = '../tinydrive' %}
{% include misc/purchase-premium-plugins.md %}
