= Link plugin
:controls: toolbar button, menu item
:description: Add hyperlinks to content.
:keywords: url urls insert edit default_link_target link_assume_external_targets link_class_list link_list target_list rel_list link_title
:title_nav: Link

:pluginname: Link
:plugincode: link

The *link* plugin allows a user to link external resources such as website URLs, to selected text in their document.

It adds two toolbar buttons called `link` and `unlink` and three menu items called `link`, `unlink` and `openlink`. The toolbar button and menu item called `link` are included in {productname}'s default configuration. The `link` menu item can be found in the `Insert` menu.

The *link* plugin also includes a context menu and context toolbar. The context toolbar can be configured using the xref:link_context_toolbar[`link_context_toolbar`] and xref:link_quicklink[`link_quicklink`] options documented below.

== Basic setup

[source, js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'link',
  menubar: 'insert',
  toolbar: 'link'
});
----

== Options

These settings affect the execution of the `link` plugin. Predefined links, targets, and more can be specified here.

include::partial$configuration/default_link_target.adoc[]

include::partial$configuration/link_assume_external_targets.adoc[]

include::partial$configuration/link_class_list.adoc[]

include::partial$configuration/link_context_toolbar.adoc[]

include::partial$configuration/link_default_protocol.adoc[]

include::partial$configuration/link_list.adoc[]

include::partial$configuration/link_title.adoc[]

include::partial$configuration/link_quicklink.adoc[]

include::partial$configuration/rel_list.adoc[]

include::partial$configuration/target_list.adoc[]

include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]

include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The Link plugin provides the following JavaScript command.

include::partial$commands/link-cmds.adoc[]
