:rootDir: ../
:partialsDir: {rootDir}partials/
= Cloud Deployment of Plugins Only
:description: TinyMCE Cloud customers, you'll be up and running in less than 5 minutes.
:description_short: Learn how to setup TinyMCE Plugins via our Cloud.
:keywords: tinymce cloud script textarea apiKey

If you're already comfortable hosting and maintaining link:{downloadspage}[TinyMCE Community edition], or you're running a web application where you have no control over the TinyMCE instance, you're still able to load our premium TinyMCE plugins from TinyMCE Cloud. Think of this as a hybrid deployment.

Signing up for a free API key entitles you to the premium link:{rootDir}plugins/imagetools.html[Image Tools] plugin, with a provided cloud image proxy server already configured. You can purchase our Premium Plugins at any time once your API key is set up.

[[step-1-embed-your-custom-script-tag-into-your-webpage]]
== Step 1: Embed your custom script tag into your webpage
anchor:step1embedyourcustomscripttagintoyourwebpage[historical anchor]

Within your webpage, after you've specified your script tag to load the TinyMCE editor code, you'll then need to add the following new script:

[source,js]
----
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/4/plugins.min.js"></script>
----

[[step-2-specify-purchased-tinymce-plugins-and-toolbar-buttons]]
== Step 2: Specify purchased TinyMCE plugins and toolbar buttons
anchor:step2specifypurchasedtinymcepluginsandtoolbarbuttons[historical anchor]

Now you just need to extend your link:{rootDir}configure/index.html[TinyMCE configuration] to include any additional plugins (and associated toolbar/menu items) you've purchased. You will find enablement guides here:

* link:{rootDir}plugins/powerpaste.html[Powerpaste]
* link:{rootDir}plugins/tinymcespellchecker.html[Spell Checker]

NOTE: `spellchecker_rpc_url` is *not* required when enabling this plugin via link:{rootDir}cloud-deployment-guide/index.html[TinyMCE Cloud]

* link:{rootDir}plugins/imagetools.html[Image Tools (with configured image proxy)]

NOTE: We will configure the `imagetools_cors_hosts` and `imagetools_proxy` properties for you automatically.

* link:{rootDir}plugins/a11ychecker.html[Accessibility Checker]
* link:{rootDir}plugins/advcode.html[Advanced Code Editor]
* link:{rootDir}plugins/mediaembed.html[Enhanced Media Embed]
* link:{rootDir}plugins/linkchecker.html[Link Checker]

NOTE: Please note that after purchasing a plugin, it may take up to 30 minutes for the plugin to become available with your editor. You may also need to clear your browser's cache.

Here is a complete example, whereby:

* The account `API key` has the value _TEST_API_KEY_.
* The account has the link:{rootDir}plugins/tinymcespellchecker.html[Spell Checker] plugin enable.

[source,js]
----
<html>
   <head>
      <script src="https://your_server/tinymce.min.js"></script>
      <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/4/plugins.min.js"></script>
   </head>
   <body>
      <textarea><p>test textarea</p></textarea>
      <script>
         tinymce.init({
            selector: 'textarea',
            height: 500,
            theme: 'modern',
            plugins: [
               'advlist autolink lists link image charmap print preview hr anchor pagebreak',
               'tinymcespellchecker']
         });
      </script>
   </body>
<html>
----

[[step-3-forward-proxy-configuration]]
== Step 3: Forward proxy configuration
anchor:step3forwardproxyconfiguration[historical anchor]

If your company network has a forward proxy that controls access to the internet, please ensure that the following URLs are accessible via this proxy.

* All URLs at which the editor is deployed.
* All URLs at which the plugins are deployed.
* \https://imageproxy.tinymce.com
* \https://hyperlinking.tinymce.com
* \https://spelling.tinymce.com

Also, please ensure that the `tiny-api-key` and `tinymce-api-key` headers are retained while requesting the list of URLs above.
