Specifies the {productname} license key. Required for self-hosted deployments of {productname}. This property is **not required** for cloud-only deployments using the {cloudname} as your cloud subscription automatically includes the commercial license. For more information, see: xref:license-key.adoc[License Key].

*Type:* `+String+`

*Default value:* `+undefined+`

*Possible values:*
* `undefined` - Use this when loading from {cloudname} with an API key
* `'gpl'` - For open source projects using GPL license
* `'T8LK:...'` - For commercial {productname} installations (must use this prefix for version 8+)
* `'GPL+T8LK:'` - For open source projects that require premium features while maintaining GPL compliance.

[NOTE]
====
In hybrid deployments (using both cloud and self-hosted features):

* You can provide both an API key and a license key
* The editor will use cloud services when available
* It will automatically fall back to the local license key if cloud services are not contactable
====
