:rootDir: ../../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= Containerized service deployments
:description: Server-side components for premium plugins using Dockerfiles
:experimental:
:keywords: enterprise tinymcespellchecker spell check checker pro imagetools server

The {enterpriseversion} server-side components can be deployed on Docker orchestration applications such as https://kubernetes.io/[Kubernetes], https://docs.docker.com/engine/swarm/[Docker Swarm], or https://www.openshift.com/[OpenShift]. {companyname} provides packages containing pre-configured https://docs.docker.com/engine/reference/builder/[`Dockerfiles`] for building and deploying the {enterpriseversion} server-side components using Docker.

*Outline*

* <<containerizedservicesforself-hostedenterprisedeployments,Containerized services for Self-hosted Enterprise deployments>>
* <<containerizedservicesforindividuallylicensedpremiumplugins,Containerized services for individually licensed premium plugins>>

[[containerized-services-for-self-hosted-enterprise-deployments]]
== Containerized services for Self-hosted Enterprise deployments

The following sections assist with containerizing the {productname} services for users with licenses to the Self-hosted {productname} Enterprise bundles:

* The *Self-hosted Essential* bundle.
* The *Self-hosted Professional* bundle.
* The *Self-hosted Premium* bundle.

[[prerequisites]]
=== Prerequisites

* The https://docs.docker.com/engine/docker-overview/[Docker Engine] is installed and running.
* The user has Administrative or Root user access.
* The user is either:
 ** Using a Linux, Unix or macOS operating system.
 ** Using Windows and has access to unix command line tools using https://gitforwindows.org/[Git for Windows], https://www.cygwin.com/[Cygwin], or the https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux].

[[download-and-extract-the-tinymce-self-hosted-bundle]]
=== Download and extract the TinyMCE Self-hosted Bundle

. Go to menu:link:{accountpageurl}[{accountpage}][My Downloads] and download either:
 ** The *Self-hosted Essential* bundle.
 ** The *Self-hosted Professional* bundle.
 ** The *Self-hosted Premium* bundle.
. Open a command line and navigate to the directory containing the downloaded `.zip` file:
 ** `TinyMCE-Essential_latest.zip` for *Self-hosted Essential* users.
 ** `TinyMCE-Professional_latest.zip` for *Self-hosted Professional* users.
 ** `TinyMCE-Premium_latest.zip` for *Self-hosted Premium* users.

+
Windows Users should open a Bash command line as the Administrator User.
. Extract the contents of the `.zip` file, such as:
+
[source,sh]
----
unzip TinyMCE-Premium_latest.zip -d tinymce-selfhosted
----
+
The structure of the extracted files will be:
+
[source,sh]
----
tinymce-selfhosted/
├── tinymce/
└── tinymce-services/
    ├── ephox-hyperlinking-docker-starter-kit.zip
    ├── ephox-hyperlinking.war
    ├── ephox-image-proxy-docker-starter-kit.zip
    ├── ephox-image-proxy.war
    ├── ephox-spelling-docker-starter-kit.zip
    ├── ephox-spelling.war
    └── version.txt
----

. Navigate into the `tinymce-services` folder.
+
[source,sh]
----
cd tinymce-selfhosted/tinymce-services/
----

Proceed to setting up and deploying the containerized services:

* For the Enhanced Media Embed and Link Checker service, see: <<deploythetinymcehyperlinkingserver-sidecomponentusingdockerself-hostedenterprisebundles,Deploy the TinyMCE hyperlinking server-side component using Docker (self-hosted enterprise bundles)>>.
* For the Image Tools plugin service, see: <<deploythetinymceimageproxyserver-sidecomponentusingdockerself-hostedenterprisebundles,Deploy the TinyMCE image proxy server-side component using Docker (self-hosted enterprise bundles)>>.
* For the Spell Checker Pro service, see: <<deploythetinymcespellingserviceserver-sidecomponentusingdockerself-hostedenterprisebundles,Deploy the TinyMCE spelling service server-side component using Docker (self-hosted enterprise bundles)>>.

:shbundledockerfiles: true

include::{partialsDir}configuration/dockerized-hyperlinking-service.adoc[]

include::{partialsDir}configuration/dockerized-image-proxy.adoc[]

include::{partialsDir}configuration/dockerized-spelling-service.adoc[]

:shbundledockerfiles: false

[[containerized-services-for-individually-licensed-premium-plugins]]
== Containerized services for individually licensed premium plugins

The following sections assist with containerizing the {productname} services for users with licenses to self-hosted versions of:

* https://apps.tiny.cloud/products/enhanced-media-embed/[_Tiny Enhanced Media Embed_]
* https://apps.tiny.cloud/products/link-checker/[_Tiny Link Checker_]
* https://apps.tiny.cloud/products/spell-checker-pro/[_Tiny Spell Checker Pro_]

Select from the following:

* For the Tiny Enhanced Media Embed and Tiny Link Checker service, see: <<deploythetinymcehyperlinkingserver-sidecomponentusingdockerindividuallylicensed,Deploy the TinyMCE hyperlinking server-side component using Docker (individually licensed)>>.
* For the Tiny Spell Checker Pro service, see: <<deploythetinymcespellingserviceserver-sidecomponentusingdockerindividuallylicensed,Deploy the TinyMCE spelling service server-side component using Docker (individually licensed)>>.

include::{partialsDir}configuration/dockerized-hyperlinking-service.adoc[]

include::{partialsDir}configuration/dockerized-spelling-service.adoc[]
