:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= TinyMCE 5.0.1
:keywords: releasenotes newfeatures deleted technologypreview bugfixes knownissues
:title_nav: TinyMCE 5.0.1

[[overview]]
== Overview

The Release Notes provide high-level coverage of the improvements and additions that have been implemented in TinyMCE 5.0.1 and document known problems in this release, as well as notable bug fixes, deprecated functionality, and other details.

TinyMCE 5.0.1 release adds improvements to the TinyMCE editor to improve the overall user experience.

[[updates-and-enhancements]]
== Updates and enhancements

The new TinyMCE 5.0.1 editor comes with significant changes to the previous versions. Tiny has created a more configurable and modern editor. Improved solutions have been introduced for unnecessary and obsolete configuration options. A comprehensive list of the updates and fixed issues is available in the link:{rootDir}changelog.html#version501february212019[Changelog].
