:rootDir: ../
:partialsDir: {rootDir}partials/
include::{rootDir}_attributes.adoc[]
= TinyMCE 5.2.2
:description: Release notes for TinyMCE 5.2.2
:keywords: releasenotes bugfixes
:title_nav: TinyMCE 5.2.2

[[overview]]
== Overview

These release notes provide an overview of the changes for {productname} 5.2.2, including:

* <<generalbugfixes,General bug fixes>>
* <<securityfixes,Security fixes>>
* <<accompanyingpremiumpluginchanges,Accompanying Premium Plugin changes>>
* <<upgradingtothelatestversionoftinymce5,Upgrading to the latest version of TinyMCE 5>>

[NOTE]
====
This is the {cloudname} and {enterpriseversion} release notes. For information on the latest community version of {productname}, see: link:{rootDir}changelog.html[{productname} Changelog].
====

[[general-bug-fixes]]
== General bug fixes

{productname} 5.2.2 provides fixes for the following bugs:

* Fixed an issue where anchors could not be inserted on empty lines.
* Fixed text decorations (underline, strikethrough) not consistently inheriting the text color.
* Fixed `format` menu alignment buttons inconsistently applying to images.
* Fixed the floating toolbar drawer height collapsing when the editor is rendered in modal dialogs or floating containers.

[[security-fixes]]
== Security fixes

{productname} 5.2.2 provides fixes for the following security issues:

* Fixed `media` embed content not processing safely in some cases.

[[accompanying-premium-plugin-changes]]
== Accompanying Premium Plugin changes

The following premium plugins updates were released alongside {productname} 5.2.2.

[[powerpaste-5-2-3]]
=== PowerPaste 5.2.3

The {productname} 5.2.2 release includes an accompanying release of the *PowerPaste* premium plugin.

*PowerPaste* 5.2.3 provides a security fix to prevent arbitrary JavaScript from being executed on paste when using specifically crafted content. Replication case provided by Michał Bentkowski.

[[spellchecker-pro-2-0-1]]
=== SpellChecker Pro 2.0.1

The {productname} 5.2.2 release includes an accompanying release of the *SpellChecker Pro* premium plugin.

*SpellChecker Pro* 2.0.1 provides a fixes for:

* The context menu being incorrectly positioned on a scrolled page in TinyMCE 4.
* An unhandled exception thrown when enabling spellchecking in inline mode for TinyMCE 4.

:enterprise: true

include::{partialsDir}install/upgrading-info.adoc[]

:enterprise: false
