= TinyMCE vnumtxt
:description: Release notes for TinyMCE vnumtxt
:keywords: releasenotes bugfixes
:title_nav: TinyMCE vnumtxt

{% comment %}
Replace vnumtxt with the version number such as: X.Y.Z
Replace vnumcode with the version number without points, such as XYZ
The following "list" should be added to `data/nav.yml`
- url: "release-notesvnumcode"
  pages:
  - url: "#Overview"
  - url: "#New features"
  - url: "#Enhancements"
  - url: "#Functionality changes"
  - url: "#Accompanying Premium Plugin changes"
  - url: "#Accompanying Premium Skins and Icon Packs changes"
  - url: "#Accompanying Premium self-hosted server-side component changes"
  - url: "#General bug fixes"
  - url: "#Security fixes"
  - url: "#Deprecated features"
  - url: "#Known issues"
  - url: "#Upgrading to the latest version of TinyMCE 5"
{% endcomment %}

== Overview

{{site.productname}} vnumtxt was released for {{site.enterpriseversion}} and {{site.cloudname}} on <<`WEEKDAY`, `MMM` `D`^`st|nd|th`^, `YYYY`>>. It includes {{site.productname}} vnumtxt and additional changes to premium plugins. These release notes provide an overview of the changes for {{site.productname}} vnumtxt, including:

* <<newfeatures,New features>>
* <<enhancements,Enhancements>>
* <<functionalitychanges,Functionality changes>>
* <<accompanyingpremiumpluginchanges,Accompanying Premium Plugin changes>>
* <<accompanyingpremiumskinsandiconpackschanges,Accompanying Premium Skins and Icon Packs changes>>
* <<accompanyingpremiumself-hostedserver-sidecomponentchanges,Accompanying Premium self-hosted server-side component changes>>
* <<generalbugfixes,General bug fixes>>
* <<securityfixes,Security fixes>>
* <<deprecatedfeatures,Deprecated features>>
* <<knownissues,Known issues>>
* <<upgradingtothelatestversionoftinymce5,Upgrading to the latest version of TinyMCE 5>>

{{site.releasenotes_for_stable}}

== New features

The following new features were added for the {{site.productname}} vnumtxt release.

=== Feature name

=== Additional new features

{{site.productname}} vnumtxt introduces the following minor new features:

* changelog

== Enhancements

The following enhancements were made for the {{site.productname}} vnumtxt release.

=== Enhancement name

=== Additional enhancements

{{site.productname}} vnumtxt introduces the following minor enhancements:

* changelog

== Functionality changes

The following functionality changes were made for the {{site.productname}} vnumtxt release:

* changelog

== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {{site.productname}} vnumtxt.

=== Premium Plugin Name X.Y.Z

The {{site.productname}} vnumtxt release includes an accompanying release of the *<<Premium Plugin Name>>* premium plugin.

*<<Premium Plugin Name>>* X.Y.Z adds the following new features:

* {blank}+++<Description>++++++</Description>+++

*<<Premium Plugin Name>>* X.Y.Z introduces the following enhancements:

* {blank}+++<Description>++++++</Description>+++

*<<Premium Plugin Name>>* X.Y.Z provides the following bug fixes:

* {blank}+++<Description>++++++</Description>+++

For information on the <<Premium Plugin Name>> plugin, see: link:{{site.baseurl}}/plugins/<<Premium Plugin Name>>/[<<Premium Plugin Name>> plugin].

== Accompanying Premium Skins and Icon Packs changes

The {{site.productname}} vnumtxt release includes an accompanying release of the *Premium Skins and Icon Packs*.

=== Premium Skins and Icon Packs - New features

{% comment %}
Add description here.
{% endcomment %}

For information on using premium skins and icon packs, see: link:{{site.baseurl}}/enterprise/premium-skins-and-icon-packs/[Premium Skins and Icon Packs].

=== Premium Skins and Icon Packs - Bug fixes

The *Premium Skins and Icon Packs* release includes the following bug fixes:

{% comment %}
Add description here.
{% endcomment %}

For information on using premium skins and icon packs, see: link:{{site.baseurl}}/enterprise/premium-skins-and-icon-packs/[Premium Skins and Icon Packs].

== Accompanying Premium self-hosted server-side component changes

The {{site.productname}} vnumtxt release includes accompanying changes affecting the {{site.productname}} *self-hosted* services for the following plugins:

* The Enhanced Media Embed plugin (`mediaembed`)
* The Export plugin (`export`)
* The Image Tools plugin (`imagetools`)
* The Link Checker plugin (`linkchecker`)
* The Spell Checker Pro plugin (`tinymcespellchecker`)

The Java server-side components have been updated to the following versions:

* `ephox-spelling.war`: X.Y.Z
* `ephox-hyperlinking.war`: X.Y.Z
* `ephox-image-proxy.war`: X.Y.Z

This version requires Java 8 or higher. For information on the removal of Java 7 support, see: link:{{site.baseurl}}/release-notes/release-notes53/#removalofjava7support[Removal of Java 7 support for TinyMCE 5.3 and later].

For information on:

* The Spell Checker Pro plugin, see: link:{{site.baseurl}}/plugins/premium/tinymcespellchecker/[Spell Checker Pro plugin].
* The Link Checker plugin, see: link:{{site.baseurl}}/plugins/premium/linkchecker/[Link Checker plugin].
* The Image Tools plugin, see: link:{{site.baseurl}}/plugins/opensource/imagetools/[Image Tools plugin].
* The Enhanced Media Embed plugin, see: link:{{site.baseurl}}/plugins/premium/mediaembed/[Enhanced Media Embed plugin].
* Deploying the server-side components, see: link:{{site.baseurl}}/enterprise/server/[Server-side component installation].

=== Updating the self-hosted server-side components

The new versions of the server-side services provide updates for the Java-based server-side components. To deploy the updated version of the server-side components:

. Update your Java Application Server to the minimum required version:
 ** Eclipse Jetty 9.4 or later
 ** Apache Tomcat:
  *** 9 or later
  *** 8.5.12+
  *** 8.0.42+
  *** 7.0.76+
. Replace the existing server-side `.war` files with the `.war` files bundled with {{site.productname}} vnumtxt or later.

For information on:

* Deploying the server-side components, see: link:{{site.baseurl}}/enterprise/server/[Server-side component installation].
* Deploying the server-side components using Docker, see: link:{{site.baseurl}}/enterprise/server/dockerservices/[Containerized service deployments].

== General bug fixes

{{site.productname}} vnumtxt provides fixes for the following bugs:

* changelog

== Security fixes

{{site.productname}} vnumtxt provides fixes for the following security issues:

* changelog

== Deprecated features

The following features have been deprecated with the release of {{site.productname}} vnumtxt:

* <<,>>.

=== The...

== Known issues

This section describes issues that users of {{site.productname}} vnumtxt may encounter and possible workarounds for these issues.

* <<,>>

###

Issue:: This issue affects ....

Workaround:: There was no known workaround at the time of the release.

{% assign enterprise = true %}

{% include install/upgrading-info.md %}

{% assign enterprise = false %}
