= TinyMCE vnumtxt
:description: Release notes for TinyMCE vnumtxt
:keywords: releasenotes bugfixes
:title_nav: TinyMCE vnumtxt

////
Replace vnumtxt with the version number such as: X.Y.Z
Replace vnumcode with the version number without points, such as XYZ
The following "list" should be added to `data/nav.yml`
- url: "release-notesvnumcode"
  pages:
  - url: "#Overview"
  - url: "#New features"
  - url: "#Enhancements"
  - url: "#Functionality changes"
  - url: "#Accompanying Premium Plugin changes"
  - url: "#Accompanying Premium Skins and Icon Packs changes"
  - url: "#Accompanying Premium self-hosted server-side component changes"
  - url: "#General bug fixes"
  - url: "#Security fixes"
  - url: "#Deprecated features"
  - url: "#Known issues"
  - url: "#Upgrading to the latest version of TinyMCE 5"
////

== Overview

{productname} vnumtxt was released for {enterpriseversion} and {cloudname} on <<`WEEKDAY`, `MMM` `D`^`st|nd|th`^, `YYYY`>>. It includes {productname} vnumtxt and additional changes to premium plugins. These release notes provide an overview of the changes for {productname} vnumtxt, including:

* <<newfeatures,New features>>
* <<enhancements,Enhancements>>
* <<functionalitychanges,Functionality changes>>
* <<accompanying-premium-self-hosted-server-side-component-changes,Accompanying Premium Plugin changes>>
* <<accompanyingpremiumskinsandiconpackschanges,Accompanying Premium Skins and Icon Packs changes>>
* <<accompanying-premium-self-hosted-server-side-component-changes,Accompanying Premium self-hosted server-side component changes>>
* <<general-bug-fixes,General bug fixes>>
* <<security-fixes,Security fixes>>
* <<deprecatedfeatures,Deprecated features>>
* <<knownissues,Known issues>>
* <<upgrading-to-the-latest-version-of-tinymce-5,Upgrading to the latest version of TinyMCE 5>>

include::partial$misc/releasenotes_for_stable.adoc[]

== New features

The following new features were added for the {productname} vnumtxt release.

=== Feature name

=== Additional new features

{productname} vnumtxt introduces the following minor new features:

* changelog

== Enhancements

The following enhancements were made for the {productname} vnumtxt release.

=== Enhancement name

=== Additional enhancements

{productname} vnumtxt introduces the following minor enhancements:

* changelog

== Functionality changes

The following functionality changes were made for the {productname} vnumtxt release:

* changelog

== Accompanying Premium Plugin changes

The following premium plugin updates were released alongside {productname} vnumtxt.

=== Premium Plugin Name X.Y.Z

The {productname} vnumtxt release includes an accompanying release of the *<<Premium Plugin Name>>* premium plugin.

*<<Premium Plugin Name>>* X.Y.Z adds the following new features:

* {blank}+++<Description>++++++</Description>+++

*<<Premium Plugin Name>>* X.Y.Z introduces the following enhancements:

* {blank}+++<Description>++++++</Description>+++

*<<Premium Plugin Name>>* X.Y.Z provides the following bug fixes:

* {blank}+++<Description>++++++</Description>+++

For information on the <<Premium Plugin Name>> plugin, see: xref:plugins/<<Premium Plugin Name>>/[<<Premium Plugin Name>> plugin].

== Accompanying Premium Skins and Icon Packs changes

The {productname} vnumtxt release includes an accompanying release of the *Premium Skins and Icon Packs*.

=== Premium Skins and Icon Packs - New features

////
Add description here.
////

For information on using premium skins and icon packs, see: xref:enterprise/premium-skins-and-icon-packs/[Premium Skins and Icon Packs].

=== Premium Skins and Icon Packs - Bug fixes

The *Premium Skins and Icon Packs* release includes the following bug fixes:

////
Add description here.
////

For information on using premium skins and icon packs, see: xref:enterprise/premium-skins-and-icon-packs/[Premium Skins and Icon Packs].

[[accompanying-premium-self-hosted-server-side-component-changes]]
== Accompanying Premium self-hosted server-side component changes

The {productname} vnumtxt release includes accompanying changes affecting the {productname} *self-hosted* services for the following plugins:

* The Enhanced Media Embed plugin (`mediaembed`)
* The Export plugin (`export`)
* The Image Tools plugin (`imagetools`)
* The Link Checker plugin (`linkchecker`)
* The Spell Checker Pro plugin (`tinymcespellchecker`)

The Java server-side components have been updated to the following versions:

* `ephox-spelling.war`: X.Y.Z
* `ephox-hyperlinking.war`: X.Y.Z
* `ephox-image-proxy.war`: X.Y.Z

This version requires Java 8 or higher. For information on the removal of Java 7 support, see: xref:release-notes/release-notes53/#removalofjava7support[Removal of Java 7 support for TinyMCE 5.3 and later].

For information on:

* The Spell Checker Pro plugin, see: xref:plugins/premium/tinymcespellchecker/[Spell Checker Pro plugin].
* The Link Checker plugin, see: xref:plugins/premium/linkchecker/[Link Checker plugin].
* The Image Tools plugin, see: xref:plugins/opensource/imagetools/[Image Tools plugin].
* The Enhanced Media Embed plugin, see: xref:plugins/premium/mediaembed/[Enhanced Media Embed plugin].
* Deploying the server-side components, see: xref:enterprise/server/[Server-side component installation].

=== Updating the self-hosted server-side components

The new versions of the server-side services provide updates for the Java-based server-side components. To deploy the updated version of the server-side components:

. Update your Java Application Server to the minimum required version:
 ** Eclipse Jetty 9.4 or later
 ** Apache Tomcat:
  *** 9 or later
  *** 8.5.12+
  *** 8.0.42+
  *** 7.0.76+
. Replace the existing server-side `.war` files with the `.war` files bundled with {productname} vnumtxt or later.

For information on:

* Deploying the server-side components, see: xref:enterprise/server/[Server-side component installation].
* Deploying the server-side components using Docker, see: xref:enterprise/server/dockerservices/[Containerized service deployments].

== General bug fixes

{productname} vnumtxt provides fixes for the following bugs:

* changelog

== Security fixes

{productname} vnumtxt provides fixes for the following security issues:

* changelog

== Deprecated features

The following features have been deprecated with the release of {productname} vnumtxt:

* <<,>>.

=== The...

== Known issues

This section describes issues that users of {productname} vnumtxt may encounter and possible workarounds for these issues.

* <<,>>

=== ,

Issue:: This issue affects ....

Workaround:: There was no known workaround at the time of the release.

:enterprise: true

include::partial$install/upgrading-info.adoc[]

:enterprise: false
