== `<configuration_option>`

// Replace content in angled brackets (<>) and remove my comments before committing!!!

// Update or remove

What does the option do? Why/when use it?
What is the values you can use and what do they do?
Is there any risks? (But explain them without saying the word `risk` or similar. Use warnings if needed.) For longer, complicated 'risks' and issues, use the limitations section.

Type : String, Boolean, Number, Function, Object, Array, or Regexp

// Remove "Possible values" where there is not a discrete set of possible values
Possible Values : `'string1'`, `'string2'`, `false`

Default Value : `false`, `1`, `'string1'`

=== Example: Using `<configuration_option>`

// This should be a working configuration. Please test.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  <configuration_option>: 'bottom'
});
----

// Remove if not required. add additional examples as required.
=== Example: Disabling the <feature>

To disable the <feature>, set the `<configuration_option>` to `false`.
// This should be a working configuration. Please test.
[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  <configuration_option>: false
});
----

// Remove if not applicable
=== Limitation of the `<configuration_option>` option

The `<configuration_option>` option has the following limitations.

<List the things we can't or wont fix, as well as complicated complications and risks>
