== `<configuration_option>`

////
Replace content in angled brackets (<>) and remove my comments before committing!!!
////

What does the option do? Why/when use it?
What is the values you can use and what do they do?
Is there any risks? (But explain them without saying the word `risk` or similar. Use warnings if needed.) For longer, complicated 'risks' and issues, use the limitations section.

////
Is a plugin required? Update ELSE Remove
////

ifeval::[{plugincode} != "<plugincode>"]
Required plugin:: link/to/ppp/[<plugin name> (`<plugin_code>`)]
endif::[]

Type:: String, Boolean, Number, Function, Object, Array, or Regexp

////
Remove "Possible values" where there is not a discrete set of possible values
////

Possible values:: `'string1'`, `'string2'`, `false`

Default value:: `false` `10` `/^\w{6}/` `'str'`

[source, js]
----
{
  default: 'object'
}
----
[source, js]
----
[
  'array',
  'default',
  1
]
----
[source, js]
----
(editor) => {
  console.log(editor);
}
----

Input parameters::
+
[cols=",^,"]
|===
| Field | Type | Description

| `id`
| `string`
| The id description.
|===

Return data::
+
[cols=",^,^,"]
|===
| Field | Type | Required or optional | Description

| `data`
| `string`
| required
| The data description.
|===

=== Example: Using `<configuration_option>`

////
This should be a working configuration. Please test.
////
[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your html
  <configuration_option>: 'bottom'
});
----
////
Remove if not required. add additional examples as required.
////

=== Example: Disabling the <feature>

To disable the <feature>, set the `<configuration_option>` to `false`.

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  <configuration_option>: false
});
----

=== Limitation of the `<configuration_option>` option

The `<configuration_option>` option has the following limitations.

<List the things we can't or wont fix, as well as complicated complications and risks>