= <Plugin Name> plugin

:title_nav: <Plugin Name>
:description: <What does this plugin do? What is the benefit? (One sentence description)>.
:description_short: <Like description, but shorter (if possible)>.
:keywords: plugin <plugincode> etc.

// Replace content in angled brackets (<>) and remove my comments before committing!!!
// Official product name as a string. Can be used in content using the {pluginname} variable
:pluginname: <Plugin Name>
// The plugin identifier used to add the plugin to an editor using the `plugin` option. Provide as a string. Can be used in content using the {plugincode} variable
:plugincode: <plugincode>
:altplugincode: nil
:plugincategory: premium|opensource

include::partial$misc/admon_premium_plugin.adoc[]

// Add an introduction. What does the plugin do? Why would I use this plugin? Keep it concise.

== Interactive example

////
  No Lorem Ipsum! Add some content to test on, possibly just a description of how end-users use the feature?
  See the emoticons, advtable,and advcode demos for examples.
////

liveDemo::{plugincode}[]

== Basic setup

To add the {pluginname} plugin to the editor, add `{plugincode}` to the `plugins` option in the editor configuration.

For example:

[source,js]
----
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: '{{plugincode}}',
  toolbar: '<toolbar-button(s)>',
  an_essential_option: false
});
----

// Delete everything not require/relevant from this point on.

== Configuration options

The following configuration options affect the behavior of the {pluginname} plugin.

////
  There should be a template to help you create these configuration option/settings "chunks".
  Just include as per the below example.
////
include::partial$configuration/<setting-name-in-hyphen-case>.adoc[]

////
  Toolbar buttons content, uses the pluginname and plugincode variables.
  The toolbar buttons are the same as another plugin, assign the other plugin's identifier to `altplugincode`
  Don't forget to add this to available-toolbar-buttons.md
////
include::partial$misc/plugin-toolbar-button-id-boilerplate.adoc[]
////
  Menu items content, uses the pluginname and plugincode variables.
  The menu items are the same as another plugin, assign the other plugin's identifier to `altplugincode`
  Don't forget to add this to available-menu-items.md
////
include::partial$misc/plugin-menu-item-id-boilerplate.adoc[]

== Commands

The {pluginname} plugin provides the following {productname} commands.

include::partial$commands/{plugincode}-cmds.adoc[]

== Events

The {{pluginname}} plugin provides the following events.

include::partial$events/{plugincode}-events.adoc[]

== APIs

The {{pluginname}} plugin provides the following APIs.

include::partial$plugin-apis/{plugincode}-apis.adoc[]
