:rootDir: ../
:partialsDir: {rootDir}partials/
= Inlite theme
:description: Theme that renders a light weight UI for inline editing.
:keywords: theme inlite
:title_nav: Inlite

The `inlite` theme is responsible for rendering the editor lightweight inline mode. The current default theme is called link:{rootDir}themes/modern.html[modern] this is an optional more lightweight distraction-free UI for the editor.

[[example]]
===== Example:

[source,js]
----
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true
});
----

[[theme-specific-controls]]
=== Theme specific controls
anchor:themespecificcontrols[historical anchor]

[[quicklink]]
==== quicklink

Lets you quickly insert/edit links inline.

===== Example:

[source,js]
----
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true,
    selection_toolbar: 'bold italic | quicklink h2 h3 blockquote'
});
----

[[quickimage]]
==== quickimage

Lets you quickly insert images from the local machine into the editor. These can then be automatically uploaded if you configure link:{rootDir}advanced/handle-async-image-uploads.html[image uploading].

===== Example:

[source,js]
----
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true,
    insert_toolbar: 'quickimage quicktable'
});
----

[[quicktable]]
==== quicktable

Lets you quickly insert a table 2x2 with 100% width.

===== Example:

[source,js]
----
tinymce.init({
    selector: "div.tinymce",
    theme: "inlite",
    inline: true,
    insert_toolbar: 'quickimage quicktable'
});
----

[[related-configuration-options]]
=== Related configuration options
anchor:relatedconfigurationoptions[historical anchor]

* link:{rootDir}configure/editor-appearance/#insert_toolbar[insert_toolbar]
* link:{rootDir}configure/editor-appearance/#selection_toolbar[selection_toolbar]
* link:{rootDir}configure/editor-appearance/#inline[inline]
* link:{rootDir}configure/editor-appearance/#skin[skin]
* link:{rootDir}configure/editor-appearance/#theme[theme]
