[[tinymce-angular-technical-reference]]
== TinyMCE Angular technical reference

*Covered in this section:*

* <<installingthetinymceangularintegrationusingnpm,Installing the TinyMCE Angular integration using NPM>>
* <<configuringtheeditor,Configuring the editor>>
* <<usingthetinymceangularintegration,Using the TinyMCE Angular integration>>
 ** <<apikey,`apiKey`>>
 ** <<cloudchannel,`cloudChannel`>>
 ** <<disabled,`disabled`>>
 ** <<id,`id`>>
 ** <<init,`init`>>
 ** <<initialvalue,`initialValue`>>
 ** <<inline,`inline`>>
 ** <<outputformat,`outputFormat`>>
 ** <<plugins,`plugins`>>
 ** <<tagname,`tagName`>>
 ** <<toolbar,`toolbar`>>
* <<usingthengmodeldirective,Using the `ngModel` directive>>
* <<usingwithreactiveforms,Using with reactive forms>>
* <<eventbinding,Event binding>>

[[installing-the-tinymce-angular-integration-using-npm]]
=== Installing the TinyMCE Angular integration using NPM

To install the `tinymce-angular` package and save it to your `package.json`.

[source,sh]
----
$ npm install --save @tinymce/tinymce-angular
----

This package is for Angular 5+. For Angular 4, use `@tinymce/tinymce-angular-legacy`

[[using-the-tinymce-angular-integration]]
=== Using the TinyMCE Angular integration

. Import the `EditorModule` from the npm package using:
+
[source,js]
----
import { EditorModule } from '@tinymce/tinymce-angular';
----
+
Add the `EditorModule` to `+@NgModule({imports})+`:
+
[source,js]
----
// This might look different depending on how you have set up your app
// but the important part is the imports array
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    EditorModule // <- Important part
  ],
  providers: [],
  bootstrap: [AppComponent]
})
----

. Add the editor to the Angular application template, such as:
+
[source,html]
----
<editor apiKey="test" [init]="{plugins: 'link'}"></editor>
----

[[configuring-the-editor]]
=== Configuring the editor

The editor accepts the following properties:

[source,html,subs="+attributes"]
----
<editor
  apiKey="no-api-key"
  cloudChannel="{productmajorversion}"
  [disabled]="false"
  id=""
  [init]="{  }"
  initialValue=""
  [inline]="false"
  plugins=""
  tagName="div"
  toolbar=""
></editor>
----

None of the configuration properties are *required* for `tinymce-angular` to work. Specify a {cloudname} API key using `apiKey` to remove the `+This domain is not registered...+` warning message.

[[apikey]]
==== `apiKey`

{cloudname} API key. Required for deployments using the {cloudname} to provide the {productname} editor.

To register for a {cloudname} API key, visit the link:{accountsignup}[sign-up page].

*Default value:* `no-api-key`

*Type:* String

[[example]]
===== Example: `apiKey`

[source,html]
----
<editor
  apiKey="your-api-key"
></editor>
----

[[cloudchannel]]
==== `cloudChannel`

*Default value:* `{productmajorversion}`

*Possible values:*  `{productmajorversion}-stable`, `{productmajorversion}-testing`, `{productmajorversion}-dev`

Changes the {productname} build used for the editor to one of the following {cloudname} channels:

* `{productmajorversion}-stable` (*Default*): The current enterprise release of {productname}.
* `{productmajorversion}-testing`: The current release candidate for the next enterprise release of {productname}.
* `{productmajorversion}-dev`: The nightly-build version of {productname}.

Such as:

[source,html,subs="+attributes"]
----
<editor
  apiKey="your-api-key"
  cloudChannel="{productmajorversion}-dev"
></editor>
----
For information {productname} development channels, see: link:{rootDir}cloud-deployment-guide/editor-plugin-version.html#devtestingandstablereleases[Specifying the {productname} editor version deployed from Cloud - dev, testing, and stable releases].

[[disabled]]
==== `disabled`

The `disabled` property can dynamically switch the editor between a "disabled" (read-only) mode (`true`) and the standard editable mode (`false`).

*Default value:* `false`

*Possible values:*  `true`, `false`

[[example-2]]
===== Example: `disabled`

[source,html]
----
<editor
  [disabled]="true"
></editor>
----

[[id]]
==== `id`

An id for the editor. Used for retrieving the editor instance using the `tinymce.get('ID')` method. Defaults to an automatically generated https://tools.ietf.org/html/rfc4122[UUID].

*Default value:* Automatically generated https://tools.ietf.org/html/rfc4122[UUID].

*Type:* String

[[example-2]]
===== Example: `id`

[source,html]
----
<editor
  id="uuid"
></editor>
----

[[init]]
==== `init`

Object sent to the `tinymce.init` method used to initialize the editor.

For information on the {productname} selector (`tinymce.init`), see: link:{rootDir}general-configuration-guide/basic-setup.html[Basic setup].

*Default value:* `+{ }+`

*Type:* Object

[[example-2]]
===== Example: `init`

[source,html]
----
<editor
  [init]="{
    plugins: [
     'lists link image paste help wordcount'
    ],
    toolbar: 'undo redo | formatselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | help'
  }"
></editor>
----

[[initialvalue]]
==== `initialValue`

Initial content of the editor when the editor is initialized.

*Default value:* `' '`

*Type:* String

[[example-2]]
===== Example: `initialValue`

[source,html]
----
<editor
  initialValue="Once upon a time..."
></editor>
----

[[inline]]
==== `inline`

Used to set the editor to inline mode. Using `<editor [inline]="true"></editor>` is the same as setting `{inline: true}` in the {productname} selector (`tinymce.init`).

For information on inline mode, see: link:{rootDir}configure/editor-appearance.html#inline[User interface options - `inline`] and link:{rootDir}general-configuration-guide/use-tinymce-inline.html[Setup inline editing mode].

*Default value:* `false`

*Possible values:*  `true`, `false`

[[example-2]]
===== Example: `inline`

[source,html]
----
<editor
  [inline]="true"
></editor>
----

[[plugins]]
==== `plugins`

Used to include plugins for the editor. Using `<editor plugins="lists code"></editor>` is the same as setting `{plugins: 'lists code'}` in the {productname} selector (`tinymce.init`).

For information on adding plugins to {productname}, see: link:{rootDir}plugins.html[Add plugins to {productname}].

*Type:* String or Array

[[example-2]]
===== Example: `plugins`

[source,html]
----
<editor
  plugins="lists code"
></editor>
----

[[outputformat]]
==== `outputFormat`

Used to specify the format of the content emitted by the tinymce-angular component when used in conjunction with forms or plain data bindings.

*Type:* String

*Default value:* `html`

*Possible values:* `html`, `text`

[[example-2]]
===== Example: `outputFormat`

[source,html]
----
<editor
  outputFormat="text"
></editor>
----

[[tagName]]
==== `tagName`

Only valid when <<inline,`<editor [inline]="true"></editor>`>>. Used to define the HTML element for the editor in inline mode.

*Default value:* `div`

*Type:* String

[[example-2]]
===== Example: `tagName`

[source,html]
----
<editor
  [inline]="true"
  tagName="my-custom-tag"
></editor>
----

[[toolbar]]
==== `toolbar`

Used to set the toolbar for the editor. Using `<editor toolbar="bold italic"></editor>` is the same as setting `{toolbar: 'bold italic'}` in the {productname} selector (`tinymce.init`).

For information setting the toolbar for {productname}, see: link:{rootDir}configure/editor-appearance.html#toolbar[User interface options - toolbar].

*Possible values:*  See link:{rootDir}advanced/editor-control-identifiers.html[Editor control identifiers - Toolbar controls].

*Type:* String

[[example-2]]
===== Example: `toolbar`

[source,html]
----
<editor
  plugins="code"
  toolbar="bold italic underline code"
></editor>
----

[[using-the-directive]]
=== Using the `ngModel` directive

The `ngModel` directive can be added to use the editor in a form:

[source,html]
----
<editor [(ngModel)]="dataModel"></editor>
----

For information on using `NgModel`, see: https://angular.io/api/forms/NgModel[Angular documentation - NgModel].

[[using-with-reactive-forms]]
=== Using with reactive forms

To use {productname} Angular component with reactive forms:

. Include the `<editor>` configuration within the `formGroup`.
. Add the `formControlName` directive to the editor configuration. For example:
+
[source,html]
----
<editor [formControlName]="schema.key" [init]="{plugins: 'link'}"></editor>
----

For information on using reactive forms, see: https://angular.io/guide/reactive-forms[Angular documentation - Reactive Forms].

[[event-binding]]
=== Event binding

Functions can be bound to editor events, such as:

[source,html]
----
<editor (onSelectionChange)="handleEvent($event)"></editor>
----

When the handler is called (`handleEvent` in this example), it is called with an event containing two properties:

* `event` - The TinyMCE event object.
* `editor` - A reference to the editor.

The following events are available:

* `onActivate`
* `onAddUndo`
* `onBeforeAddUndo`
* `onBeforeExecCommand`
* `onBeforeGetContent`
* `onBeforeRenderUI`
* `onBeforeSetContent`
* `onBeforePaste`
* `onBlur`
* `onChange`
* `onClearUndos`
* `onClick`
* `onContextMenu`
* `onCopy`
* `onCut`
* `onDblclick`
* `onDeactivate`
* `onDirty`
* `onDrag`
* `onDragDrop`
* `onDragEnd`
* `onDragGesture`
* `onDragOver`
* `onDrop`
* `onExecCommand`
* `onFocus`
* `onFocusIn`
* `onFocusOut`
* `onGetContent`
* `onHide`
* `onInit`
* `onKeyDown`
* `onKeyPress`
* `onKeyUp`
* `onLoadContent`
* `onMouseDown`
* `onMouseEnter`
* `onMouseLeave`
* `onMouseMove`
* `onMouseOut`
* `onMouseOver`
* `onMouseUp`
* `onNodeChange`
* `onObjectResizeStart`
* `onObjectResized`
* `onObjectSelected`
* `onPaste`
* `onPostProcess`
* `onPostRender`
* `onPreProcess`
* `onProgressState`
* `onRedo`
* `onRemove`
* `onReset`
* `onSaveContent`
* `onSelectionChange`
* `onSetAttrib`
* `onSetContent`
* `onShow`
* `onSubmit`
* `onUndo`
* `onVisualAid`
