[[tinymce-vue-js-technical-reference]]
== TinyMCE Vue.js technical reference

*Covered in this section:*

* <<installingthetinymcevuejsintegrationusingnpm,Installing the TinyMCE Vue.js integration using NPM>>
* <<usingthetinymcevuejsintegration,Using the TinyMCE Vue.js integration>>
* <<configuringtheeditor,Configuring the editor>>
 ** <<api-key,`api-key`>>
 ** <<cloud-channel,`cloud-channel`>>
 ** <<disabled,`disabled`>>
 ** <<id,`id`>>
 ** <<init,`init`>>
 ** <<initial-value,`initial-value`>>
 ** <<inline,`inline`>>
 ** <<model-events,`model-events`>>
 ** <<output-format,`output-format`>>
 ** <<plugins,`plugins`>>
 ** <<tag-name,`tag-name`>>
 ** <<toolbar,`toolbar`>>
 ** <<tinymce-script-src,`tinymce-script-src`>>
* <<forminputbindingsv-model,Form Input Bindings: `v-model`>>
* <<eventbinding,Event binding>>

[[installing-the-tinymce-vue-js-integration-using-npm]]
=== Installing the TinyMCE Vue.js integration using NPM

To install the `tinymce-vue` package and save it to your `package.json`.

[source,sh]
----
$ npm install --save @tinymce/tinymce-vue
----

[[using-the-tinymce-vue-js-integration]]
=== Using the TinyMCE Vue.js integration

. Load the component.
 ** For bundle loader users (such as `webpack`, `rollup`, or `browserify`):
+
[source,js]
----
// es modules
import Editor from '@tinymce/tinymce-vue';
// commonjs require
// NOTE: default needed after require
var Editor = require('@tinymce/tinymce-vue').default;
----

 ** To load `tinymce-vue` in a HTML file:
+
[source,html]
----
<script src="/path/to/tinymce-vue.min.js"></script>
----
. Add the editor to the `components` property of the app:
+
[source,js]
----
// This might look different depending on how you have set up your app
// but the important part is the components property
var app = new Vue({
  el: '#app',
  data: { /* Your data */ },
  components: {
    'editor': Editor // <- Important part
  },
  methods: { /* Your methods */}
})
----

. Add the `<editor>` tag to the `template`
+
[source,html]
----
<editor api-key="API_KEY" :init="{plugins: 'wordcount'}" />
----

[[configuring-the-editor]]
=== Configuring the editor

The editor accepts the following properties:

[source,html,subs="+attributes"]
----
<editor
  api-key="your-api-key"
  cloud-channel="{productmajorversion}"
  :disabled=false
  id="uuid"
  :init="{  }"
  initial-value=""
  :inline=true
  model-events= ""
  plugins=""
  tag-name="div"
  toolbar=""
  value=""
/>
----

None of the configuration properties are *required* for `tinymce-vue` to work. Specify a {cloudname} API key using `api-key` to remove the `+This domain is not registered...+` warning message.

[[api-key]]
==== `api-key`

{cloudname} API key. Required for deployments using the {cloudname} to provide the {productname} editor.

To register for a {cloudname} API key, visit the link:{accountsignup}[sign-up page].

*Default value:* `no-api-key`

*Type:* String

[[example]]
===== Example: `api-key`

[source,html]
----
<editor
  api-key="your-api-key"
/>
----

[[cloud-channel]]
==== `cloud-channel`

*Default value:* `{productmajorversion}`

*Possible values:*  `{productmajorversion}-stable`, `{productmajorversion}-testing`, `{productmajorversion}-dev`

Changes the {productname} build used for the editor to one of the following {cloudname} channels:

* `{productmajorversion}`, `{productmajorversion}-stable` (*Default*): The current enterprise release of {productname}.
* `{productmajorversion}-testing`: The current release candidate for the next enterprise release of {productname}.
* `{productmajorversion}-dev`: The nightly-build version of {productname}.

Such as:

[source,html,subs="+attributes"]
----
<editor
  api-key="your-api-key"
  cloud-channel="{productmajorversion}-dev"
  :init="{ /* your other settings */ }"
/>
----

For information {productname} development channels, see: link:{rootDir}cloud-deployment-guide/editor-plugin-version.html#devtestingandstablereleases[Specifying the {productname} editor version deployed from Cloud - dev, testing, and stable releases].

[[disabled]]
==== `disabled`

The `disabled` property can dynamically switch the editor between a "disabled" (read-only) mode (`true`) and the standard editable mode (`false`).

*Default value:* `false`

*Possible values:*  `true`, `false`

[[example-2]]
===== Example: `disabled`

[source,html]
----
<editor
  :disabled=true
/>
----

[[id]]
==== `id`

An id for the editor. Used for retrieving the editor instance using the `tinymce.get('ID')` method. Defaults to an automatically generated https://tools.ietf.org/html/rfc4122[UUID].

*Default value:* Automatically generated https://tools.ietf.org/html/rfc4122[UUID].

*Type:* String

[[example-2]]
===== Example: `id`

[source,html]
----
<editor
  id="uuid"
/>
----

[[init]]
==== `init`

Object sent to the `tinymce.init` method used to initialize the editor.

For information on the {productname} selector (`tinymce.init`), see: link:{rootDir}general-configuration-guide/basic-setup.html[Basic setup].

*Default value:* `+"{ }"+`

*Type:* Object

[[example-2]]
===== Example: `init`

[source,html]
----
<editor
  :init="{
    plugins: [
     'lists link image paste help wordcount'
    ],
    toolbar: 'undo redo | formatselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | help'
  }"
/>
----

[[initial-value]]
==== `initial-value`

Initial content of the editor when the editor is initialized.

*Default value:* `" "`

*Type:* String

[[example-2]]
===== Example: `initial-value`

[source,html]
----
<editor
  initial-value="Once upon a time..."
/>
----

[[inline]]
==== `inline`

Used to set the editor to inline mode. Using `<editor :inline=true />` is the same as setting `{inline: true}` in the {productname} selector (`tinymce.init`).

For information on inline mode, see: link:{rootDir}configure/editor-appearance.html#inline[User interface options - `inline`] and link:{rootDir}general-configuration-guide/use-tinymce-inline.html[Setup inline editing mode].

*Default value:* `false`

*Possible values:*  `true`, `false`

[[example-2]]
===== Example: `inline`

[source,html]
----
<editor
  :inline=true
/>
----

[[model-events]]
==== `model-events`

Sets the trigger events for <<forminputbindingsv-model,v-model events>>.

For a list of available {productname} events, see: link:{rootDir}advanced/events.html#editorevents[Editor events].

*Default value:* `"change keyup undo redo"`.

*Type:* String

[[example-2]]
===== Example: `model-events`

[source,html]
----
<editor
  model-events="change keydown blur focus paste"
/>
----

[[output-format]]
==== `output-format`

Used to specify the format of the content emitted via the `input` event. This affects the format of the content used in conjunction with data binding.

*Type:* String

*Default value:* `html`

*Possible values:* `html`, `text`

[[example-2]]
===== Example: `output-format`

[source,html]
----
<editor
  output-format="text"
/>
----

[[plugins]]
==== `plugins`

Used to include plugins for the editor. Using `<editor plugins="lists code" />` is the same as setting `{plugins: 'lists code'}` in the {productname} selector (`tinymce.init`).

For information on adding plugins to {productname}, see: link:{rootDir}plugins.html[Add plugins to {productname}].

*Type:* String or Array

[[example-2]]
===== Example: `plugins`

[source,html]
----
<editor
  plugins="lists code"
/>
----

[[tag-name]]
==== `tag-name`

Only valid when <<inline,`<editor :inline=true />`>>. Used to define the HTML element for the editor in inline mode.

*Default value:* `div`

*Type:* String

[[example-2]]
===== Example: `tag-name`

[source,html]
----
<editor
  :inline=true
  tag-name="my-custom-tag"
/>
----

[[toolbar]]
==== `toolbar`

Used to set the toolbar for the editor. Using `<editor toolbar="bold italic" />` is the same as setting `{toolbar: 'bold italic'}` in the {productname} selector (`tinymce.init`).

For information setting the toolbar for {productname}, see: link:{rootDir}configure/editor-appearance.html#toolbar[User interface options - toolbar].

*Possible values:*  See link:{rootDir}advanced/editor-control-identifiers.html[Editor control identifiers - Toolbar controls].

*Type:* String

[[example-2]]
===== Example: `toolbar`

[source,html]
----
<editor
  plugins="code"
  toolbar="bold italic underline code"
/>
----

[[tinymce-script-src]]
==== `tinymce-script-src`

Use the `tinymce-script-src` prop to specify an external version of TinyMCE to lazy load.

*Type:* String

[[example-2]]
===== Example: `tinymce-script-src`

[source,html]
----
<editor
  tinymce-script-src="/path/to/tinymce.min.js"
/>
----

[[form-input-bindings]]
=== Form Input Bindings: `v-model`

The `v-model` directive can be used to create a two-way data binding. For example:

[source,html]
----
<editor v-model="content" />
----

For information on `v-model` and form input bindings, see: https://vuejs.org/v2/guide/forms.html[Vue.js documentation - Form Input Bindings].

[[event-binding]]
=== Event binding

Functions can be bound to editor events, such as:

[source,html]
----
<editor @onSelectionChange="handlerFunction" />
----

When the handler is called (*handlerFunction* in this example), it is called with two arguments:

* `event` - The TinyMCE event object.
* `editor` - A reference to the editor.

The following events are available:

* `onActivate`
* `onAddUndo`
* `onBeforeAddUndo`
* `onBeforeExecCommand`
* `onBeforeGetContent`
* `onBeforeRenderUI`
* `onBeforeSetContent`
* `onBeforePaste`
* `onBlur`
* `onChange`
* `onClearUndos`
* `onClick`
* `onContextMenu`
* `onCopy`
* `onCut`
* `onDblclick`
* `onDeactivate`
* `onDirty`
* `onDrag`
* `onDragDrop`
* `onDragEnd`
* `onDragGesture`
* `onDragOver`
* `onDrop`
* `onExecCommand`
* `onFocus`
* `onFocusIn`
* `onFocusOut`
* `onGetContent`
* `onHide`
* `onInit`
* `onKeyDown`
* `onKeyPress`
* `onKeyUp`
* `onLoadContent`
* `onMouseDown`
* `onMouseEnter`
* `onMouseLeave`
* `onMouseMove`
* `onMouseOut`
* `onMouseOver`
* `onMouseUp`
* `onNodeChange`
* `onObjectResizeStart`
* `onObjectResized`
* `onObjectSelected`
* `onPaste`
* `onPostProcess`
* `onPostRender`
* `onPreProcess`
* `onProgressState`
* `onRedo`
* `onRemove`
* `onReset`
* `onSaveContent`
* `onSelectionChange`
* `onSetAttrib`
* `onSetContent`
* `onShow`
* `onSubmit`
* `onUndo`
* `onVisualAid`
