= tinymce.html.DomParser

This class parses HTML code into a DOM like structure of nodes it will remove redundant whitespace and make sure that the node tree is valid according to the specified schema. So for example: <p>a<p>b</p>c</p> will become <p>a</p><p>b</p><p>c</p>

[[examples]]
== Examples

[source,js]
----
var parser = new tinymce.html.DomParser({validate: true}, schema);
var rootNode = parser.parse('<h1>content</h1>');
----

[[methods]]
== Methods

[cols="1,3,1",options="header",]
|===
|name |summary |defined by
|link:#addattributefilter[addAttributeFilter()] |Adds a attribute filter function to the parser, the parser will collect nodes that has the specified attributes and then execute the callback once it has finished parsing the document. |link:{baseurl}/api/tinymce.html/tinymce.html.domparser.html[tinymce.html.DomParser]
|link:#addnodefilter[addNodeFilter()] |Adds a node filter function to the parser, the parser will collect the specified nodes by name and then execute the callback once it has finished parsing the document. |link:{baseurl}/api/tinymce.html/tinymce.html.domparser.html[tinymce.html.DomParser]
|link:#filternode[filterNode()] |Runs the specified node though the element and attributes filters. |link:{baseurl}/api/tinymce.html/tinymce.html.domparser.html[tinymce.html.DomParser]
|link:#parse[parse()] |Parses the specified HTML string into a DOM like node tree and returns the result. |link:{baseurl}/api/tinymce.html/tinymce.html.domparser.html[tinymce.html.DomParser]
|===

== Methods

[[addattributefilter]]
=== addAttributeFilter

addAttributeFilter(callback:function)

Adds a attribute filter function to the parser, the parser will collect nodes that has the specified attributes and then execute the callback once it has finished parsing the document.

[[examples]]
==== Examples

[source,js]
----
parser.addAttributeFilter('src,href', function(nodes, name) {
 for (var i = 0; i < nodes.length; i++) {
  console.log(nodes[i].name);
 }
});
----

[[parameters]]
==== Parameters

* `+callback+` `+(function)+` - Callback function to execute once it has collected nodes.

[[addnodefilter]]
=== addNodeFilter

addNodeFilter(callback:function)

Adds a node filter function to the parser, the parser will collect the specified nodes by name and then execute the callback once it has finished parsing the document.

==== Examples

[source,js]
----
parser.addNodeFilter('p,h1', function(nodes, name) {
 for (var i = 0; i < nodes.length; i++) {
  console.log(nodes[i].name);
 }
});
----

==== Parameters

* `+callback+` `+(function)+` - Callback function to execute once it has collected nodes.

[[filternode]]
=== filterNode

filterNode(Node:tinymce.html.Node):tinymce.html.Node

Runs the specified node though the element and attributes filters.

==== Parameters

* `+Node+` link:{baseurl}/api/tinymce.html/tinymce.html.node.html[`+(tinymce.html.Node)+`] - the node to run filters on.

[[return-value]]
==== Return value
anchor:returnvalue[historical anchor]

* link:{baseurl}/api/tinymce.html/tinymce.html.node.html[`+tinymce.html.Node+`] - The passed in node.

[[parse]]
=== parse

parse(html:String, args:Object):tinymce.html.Node

Parses the specified HTML string into a DOM like node tree and returns the result.

==== Examples

[source,js]
----
var rootNode = new DomParser({...}).parse('<b>text</b>');
----

==== Parameters

* `+html+` `+(String)+` - Html string to sax parse.
* `+args+` `+(Object)+` - Optional args object that gets passed to all filter functions.

==== Return value

* link:{baseurl}/api/tinymce.html/tinymce.html.node.html[`+tinymce.html.Node+`] - Root node containing the tree.
