= tinymce.html.SaxParser

This class parses HTML code using pure JavaScript and executes various events for each item it finds. It will always execute the events in the right order for tag soup code like <b><p></b></p>. It will also remove elements and attributes that doesn't fit the schema if the validate setting is enabled.

== Examples

[source,prettyprint]
----
var parser = new tinymce.html.SaxParser({
    validate: true,

    comment: function(text) {
        console.log('Comment:', text);
    },

    cdata: function(text) {
        console.log('CDATA:', text);
    },

    text: function(text, raw) {
        console.log('Text:', text, 'Raw:', raw);
    },

    start: function(name, attrs, empty) {
        console.log('Start:', name, attrs, empty);
    },

    end: function(name) {
        console.log('End:', name);
    },

    pi: function(name, text) {
        console.log('PI:', name, text);
    },

    doctype: function(text) {
        console.log('DocType:', text);
    }
}, schema);
----

[#constructors .anchor]##

== link:#constructors[Constructors]

[cols=",,",options="header",]
|===
|name |summary |defined by
|link:#saxparser[SaxParser()] |Constructs a new SaxParser instance. |link:/docs-4x/api/tinymce.html/tinymce.html.saxparser[tinymce.html.SaxParser]
|===

[#methods .anchor]##

== link:#methods[Methods]

[cols=",,",options="header",]
|===
|name |summary |defined by
|link:#parse[parse()] |Parses the specified HTML string and executes the callbacks for each item it finds. |link:/docs-4x/api/tinymce.html/tinymce.html.saxparser[tinymce.html.SaxParser]
|===

== Constructors

[#saxparser .anchor]##

=== link:#saxparser[SaxParser]

public constructor function SaxParser(settings:Object, schema:tinymce.html.Schema)

Constructs a new SaxParser instance.

==== Parameters

* [.param-name]#settings# [.param-type]#(Object)# - Name/value collection of settings. comment, cdata, text, start and end are callbacks.
* [.param-name]#schema# link:/docs-4x/api/tinymce.html/tinymce.html.schema[[.param-type]#(tinymce.html.Schema)#] - HTML Schema class to use when parsing.

== Methods

[#parse .anchor]##

=== link:#parse[parse]

parse(html:String)

Parses the specified HTML string and executes the callbacks for each item it finds.

==== Examples

[source,prettyprint]
----
SaxParser({...}).parse('<b>text</b>');
----

==== Parameters

* [.param-name]#html# [.param-type]#(String)# - Html string to sax parse.
