= tinymce.html.Writer

This class is used to write HTML tags out it can be used with the Serializer or the SaxParser.

[[examples]]
== Examples

[source,prettyprint]
----
var writer = new tinymce.html.Writer({indent: true});
var parser = new tinymce.html.SaxParser(writer).parse('<p><br></p>');
console.log(writer.getContent());
----

[[methods]]
== Methods

[width="100%",cols="34%,33%,33%",options="header",]
|===
|name |summary |defined by
|link:#cdata[cdata()] |Writes a comment node such as . |link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|link:#doctype[doctype()] a|
Writes a doctype node such as

.

|link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|link:#end[end()] a|
Writes the a end element such as

.

|link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|link:#getcontent[getContent()] |Returns the contents that got serialized. |link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|link:#pi[pi()] a|
Writes a PI node such as

.

|link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|link:#reset[reset()] |Resets the internal buffer if one wants to reuse the writer. |link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|link:#start[start()] a|
Writes the a start element such as

.

|link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|link:#text[text()] |Writes a text node. |link:/docs-4x/api/tinymce.html/tinymce.html.writer[tinymce.html.Writer]
|===

== Methods

[[cdata]]
=== cdata

cdata(text:String)

Writes a comment node such as .

[[parameters]]
==== Parameters

* [.param-name]#text# [.param-type]#(String)# - String to write out inside the comment.

[[doctype]]
=== doctype

doctype(text:String)

Writes a doctype node such as

.

==== Parameters

* [.param-name]#text# [.param-type]#(String)# - String to write out inside the doctype.

[[end]]
=== end

end(name:String)

Writes the a end element such as

.

==== Parameters

* [.param-name]#name# [.param-type]#(String)# - Name of the element.

[[getcontent]]
=== getContent

getContent():String

Returns the contents that got serialized.

[[return-value]]
==== Return value 
anchor:returnvalue[historical anchor]

* [.return-type]#String# - HTML contents that got written down.

[[pi]]
=== pi

pi(name:String, text:String)

Writes a PI node such as .

==== Parameters

* [.param-name]#name# [.param-type]#(String)# - Name of the pi.
* [.param-name]#text# [.param-type]#(String)# - String to write out inside the pi.

[[reset]]
=== reset

reset()

Resets the internal buffer if one wants to reuse the writer.

[[start]]
=== start

start(name:String, attrs:Array, empty:Boolean)

Writes the a start element such as

.

==== Parameters

* [.param-name]#name# [.param-type]#(String)# - Name of the element.
* [.param-name]#attrs# [.param-type]#(Array)# - Optional attribute array or undefined if it hasn't any.
* [.param-name]#empty# [.param-type]#(Boolean)# - Optional empty state if the tag should end like +
.

[[text]]
=== text

text(text:String, raw:Boolean)

Writes a text node.

==== Parameters

* [.param-name]#text# [.param-type]#(String)# - String to write out.
* [.param-name]#raw# [.param-type]#(Boolean)# - Optional raw state if true the contents wont get encoded.
