== TinyMCE Angular technical reference

*Covered in this section:*

* xref:supportedangularversions[Supported Angular versions]
* xref:installingthetinymceangularintegrationusingnpm[Installing the TinyMCE Angular integration using NPM]
* xref:usingthetinymceangularintegration[Using the TinyMCE Angular integration]
* xref:configuringtheeditor[Configuring the editor]
 ** xref:apikey[`apiKey`]
 ** xref:cloudchannel[`cloudChannel`]
 ** xref:disabled[`disabled`]
 ** xref:id[`id`]
 ** xref:init[`init`]
 ** xref:initialvalue[`initialValue`]
 ** xref:inline[`inline`]
 ** xref:outputformat[`outputFormat`]
 ** xref:plugins[`plugins`]
 ** xref:tagname[`tagName`]
 ** xref:toolbar[`toolbar`]
* xref:usingthengmodeldirective[Using the `ngModel` directive]
 ** xref:modelevents[`modelEvents`]
* xref:usingwithreactiveforms[Using with reactive forms]
* xref:eventbinding[Event binding]
 ** xref:supportedbrowserevents[Supported browser events]
 ** xref:supportedtinymceevents[Supported TinyMCE events]
 ** xref:allowedevents[`allowedEvents`]
 ** xref:ignoreevents[`ignoreEvents`]

[[supportedangularversions]]
=== Supported Angular versions

The following table shows the supported versions of Angular and the required version of the `tinymce-angular` integration package.

[cols="^,^"]
|===
| Angular Version | `tinymce-angular` version

| 9+
| 4.x

| 5 to 8
| 3.x

| 4 or older
| Not Supported
|===

[[installingthetinymceangularintegrationusingnpm]]
=== Installing the TinyMCE Angular integration using NPM

To install the `tinymce-angular` package and save it to your `package.json`.

[source, sh]
----
$ npm install --save @tinymce/tinymce-angular
----

[[usingthetinymceangularintegration]]
=== Using the TinyMCE Angular integration

. Import the `EditorModule` from the npm package using:
+
[source, js]
----
import { EditorModule } from '@tinymce/tinymce-angular';
----
Add the `EditorModule` to `+@NgModule({imports})+`:
+
[source, js]
----
// This might look different depending on how you have set up your app
// but the important part is the imports array
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    EditorModule // <- Important part
  ],
  providers: [],
  bootstrap: [AppComponent]
})
----

. Add the editor to the Angular application template, such as:
+
[source, html]
----
<editor apiKey="test" [init]="{plugins: 'link'}"></editor>
----

[[configuringtheeditor]]
=== Configuring the editor

The editor accepts the following properties:

[source, html, subs="attributes+"]
----
<editor
  apiKey="no-api-key"
  cloudChannel="{productmajorversion}"
  [disabled]="false"
  id=""
  [init]="{  }"
  initialValue=""
  [inline]="false"
  plugins=""
  tagName="div"
  toolbar=""
></editor>
----

None of the configuration properties are *required* for `tinymce-angular` to work. Specify a {cloudname} API key using `apiKey` to remove the `+This domain is not registered...+` warning message.

[[apikey]]
==== `apiKey`

{cloudname} API key. Required for deployments using the {cloudname} to provide the {productname} editor.

include::partial$misc/get-an-api-key.adoc[]

*Default value:* `no-api-key`

*Type:* String

===== Example: Using `apiKey`

[source, html]
----
<editor
  apiKey="your-api-key">
</editor>
----

[[cloudchannel]]
==== `cloudChannel`

*Default value:* `{productmajorversion}`

*Possible values:*  `{productmajorversion}-stable`, `{productmajorversion}-testing`, `{productmajorversion}-dev`

Changes the {productname} build used for the editor to one of the following {cloudname} channels:

* `{productmajorversion}-stable` (*Default*): The current enterprise release of {productname}.
* `{productmajorversion}-testing`: The current release candidate for the next enterprise release of {productname}.
* `{productmajorversion}-dev`: The nightly-build version of {productname}.

Such as:

[source, html, subs="attributes+"]
----
<editor
  apiKey="your-api-key"
  cloudChannel="{productmajorversion}-dev">
</editor>
----
For information {productname} development channels, see: xref:cloud-deployment-guide/editor-plugin-version.adoc#55-testingand5-devreleasechannels[Specifying the {productname} editor version deployed from Cloud - dev, testing, and stable releases].

[[disabled]]
==== `disabled`

The `disabled` property can dynamically switch the editor between a "disabled" (read-only) mode (`true`) and the standard editable mode (`false`).

*Default value:* `false`

*Possible values:*  `true`, `false`

===== Example: Using `disabled`

[source, html]
----
<editor
  [disabled]="true"
></editor>
----

[[id]]
==== `id`

An id for the editor. Used for retrieving the editor instance using the `tinymce.get('ID')` method. Defaults to an automatically generated https://tools.ietf.org/html/rfc4122[UUID].

*Default value:* Automatically generated https://tools.ietf.org/html/rfc4122[UUID].

*Type:* String

===== Example: Using `id`

[source, html]
----
<editor
  id="uuid"
></editor>
----

[[init]]
==== `init`

Object sent to the `tinymce.init` method used to initialize the editor.

For information on the {productname} selector (`tinymce.init`), see: xref:general-configuration-guide/basic-setup.adoc[Basic setup].

*Default value:* pass:[{ }]

*Type:* Object

===== Example: Using `init`

[source, html]
----
<editor
  [init]="{
    plugins: [
      'lists link image paste help wordcount'
    ],
    toolbar: 'undo redo | formatselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | help'
  }"
></editor>
----

[[initialvalue]]
==== `initialValue`

Initial content of the editor when the editor is initialized.

*Default value:* `' '`

*Type:* String

===== Example: Using `initialValue`

[source, html]
----
<editor
  initialValue="Once upon a time...">
</editor>
----

[[inline]]
==== `inline`

Used to set the editor to inline mode. Using `<editor [inline]="true"></editor>` is the same as setting `{inline: true}` in the {productname} selector (`tinymce.init`).

For information on inline mode, see: xref:configure/editor-appearance.adoc#inline[User interface options - `inline`] and xref:general-configuration-guide/use-tinymce-inline.adoc[Setup inline editing mode].

*Default value:* `false`

*Possible values:*  `true`, `false`

===== Example: Using `inline`

[source, html]
----
<editor
  [inline]="true"
></editor>
----

[[plugins]]
==== `plugins`

Used to include plugins for the editor. Using `<editor plugins="lists code"></editor>` is the same as setting `{plugins: 'lists code'}` in the {productname} selector (`tinymce.init`).

For information on adding plugins to {productname}, see: xref:plugins/index.adoc[Add plugins to {productname}].

*Type:* String or Array

===== Example: Using `plugins`

[source, html]
----
<editor
  plugins="lists code">
</editor>
----

[[outputformat]]
==== `outputFormat`

Used to specify the format of the content emitted by the `tinymce-angular` component when used in conjunction with forms or plain data bindings.

*Type:* String

*Default value:* `html`

*Possible values:* `html`, `text`

===== Example: Using `outputFormat`

[source, html]
----
<editor
  outputFormat="text">
</editor>
----

[[tagname]]
==== `tagName`

Only valid when xref:inline[`+<editor [inline]="true"></editor>+`]. Used to define the HTML element for the editor in inline mode.

*Default value:* `div`

*Type:* String

===== Example: Using `tagName`

[source, html]
----
<editor
  [inline]="true"
  tagName="my-custom-tag"
></editor>
----

[[toolbar]]
==== `toolbar`

Used to set the toolbar for the editor. Using `<editor toolbar="bold italic"></editor>` is the same as setting `{toolbar: 'bold italic'}` in the {productname} selector (`tinymce.init`).

For information setting the toolbar for {productname}, see: xref:configure/editor-appearance.adoc#toolbar[User interface options - toolbar].

*Possible values:*  See xref:advanced/available-toolbar-buttons.adoc[Toolbar Buttons Available for {productname}].

*Type:* String

===== Example: Using `toolbar`

[source, html]
----
<editor
  plugins="code"
  toolbar="bold italic underline code"
></editor>
----

[[usingthengmodeldirective]]
=== Using the `ngModel` directive

The `ngModel` directive can be added to use the editor in a form:

[source, html]
----
<editor [(ngModel)]="dataModel"></editor>
----

For information on using `NgModel`, see: https://angular.io/api/forms/NgModel[Angular documentation - NgModel].

[[modelevents]]
==== `modelEvents`

NOTE: This property requires `tinymce-angular` 4.0.0 or newer

Used to specify the events that trigger the `NgModelChange` to emit.

*Default value:* `"change input undo redo"`.

*Possible value:* A space separated list of TinyMCE editor events.

*Type* String

===== Example: Using `modelEvents`

[source, html]
----
<editor
  modelEvents="change input nodechange undo redo"
></editor>
----

[[usingwithreactiveforms]]
=== Using with reactive forms

To use {productname} Angular component with reactive forms:

. Include the `<editor>` configuration within the `formGroup`.
. Add the `formControlName` directive to the editor configuration. For example:
+
[source, html]
----
<editor [formControlName]="schema.key" [init]="{plugins: 'link'}"></editor>
----

For information on using reactive forms, see: https://angular.io/guide/reactive-forms[Angular documentation - Reactive Forms].

[[eventbinding]]
=== Event binding

Functions can be bound to editor events, such as:

[source, html]
----
<editor (onSelectionChange)="handleEvent($event)"></editor>
----

When the handler is called (`handleEvent` in this example), it is called with an event containing two properties:

* `event` - The TinyMCE event object.
* `editor` - A reference to the editor.

The following events are available:

[[supportedbrowserevents]]
==== Supported browser events

* `onBeforePaste`
* `onBlur`
* `onClick`
* `onContextMenu`
* `onCopy`
* `onCut`
* `onDblclick`
* `onDrag`
* `onDragDrop`
* `onDragEnd`
* `onDragGesture`
* `onDragOver`
* `onDrop`
* `onFocus`
* `onFocusIn`
* `onFocusOut`
* `onKeyDown`
* `onKeyPress`
* `onKeyUp`
* `onMouseDown`
* `onMouseEnter`
* `onMouseLeave`
* `onMouseMove`
* `onMouseOut`
* `onMouseOver`
* `onMouseUp`
* `onPaste`
* `onSelectionChange`

[[supportedtinymceevents]]
==== Supported TinyMCE events

* `onActivate`
* `onAddUndo`
* `onBeforeAddUndo`
* `onBeforeExecCommand`
* `onBeforeGetContent`
* `onBeforeRenderUI`
* `onBeforeSetContent`
* `onChange`
* `onClearUndos`
* `onDeactivate`
* `onDirty`
* `onExecCommand`
* `onGetContent`
* `onHide`
* `onInit`
* `onInitNgModel`
* `onLoadContent`
* `onNodeChange`
* `onPostProcess`
* `onPostRender`
* `onPreInit`
* `onPreProcess`
* `onProgressState`
* `onRedo`
* `onRemove`
* `onReset`
* `onSaveContent`
* `onSetAttrib`
* `onObjectResizeStart`
* `onObjectResized`
* `onObjectSelected`
* `onSetContent`
* `onShow`
* `onSubmit`
* `onUndo`
* `onVisualAid`

By default, all the available events will trigger from the editor to the `tinymce-angular` component. To limit the events triggering in the component, use the `allowedEvents` and `ignoreEvents` properties.

[[allowedevents]]
==== `allowedEvents`

NOTE: This property requires `tinymce-angular` 4.2.0 or newer

Used to provide an allow-list of valid events to trigger from the editor to the `tinymce-angular` component. By default, the component will emit all the events listed in the xref:eventbinding[Event binding section].

*Possible values:* A comma separated list of events to allow.

*Type* String

===== Example: Using `allowedEvents`

[source, html]
----
<editor
  allowedEvents="onMouseDown,onKeyDown"
></editor>
----

[[ignoreevents]]
==== `ignoreEvents`

NOTE: This property requires `tinymce-angular` 4.2.0 or newer

Used to block a list of events from the `tinymce-angular` component.

*Possible values:* A comma separated list of events to ignore.

*Type* String

===== Example: Using `ignoreEvents`

[source, html]
----
<editor
  ignoreEvents="onMouseEnter,onMouseLeave,onMouseOut,onMouseMove"
></editor>
----
