:packageName: tinymce-angular

The steps below use standalone components. If using Angular Modules, see xref:angular-modules[Angular Modules].

== Prerequisites

This procedure requires https://nodejs.org/[Node.js (and NPM)].

== Procedure

. From a terminal or command prompt, install the link:https://angular.dev/tools/cli[Angular CLI Tool] globally.
+
[source,sh]
----
npm install -g @angular/cli
----

. Create a new Angular project named `+tinymce-angular-demo+` using default settings and without Git initialization.
+
[source,sh]
----
ng new --defaults --skip-git tinymce-angular-demo
----

. Move into the project directory and install `+tinymce-angular+`.
+
[source,sh]
----
cd tinymce-angular-demo && npm install @tinymce/tinymce-angular
----

ifeval::["{productSource}" == "package-manager"]

. Install the `+tinymce+`.
+
[source,sh]
----
npm install tinymce
----
+
endif::[]

. Update the root component `+src/app/app.component.ts+` to import and use the `EditorComponent`.
ifeval::["{productSource}" == "cloud"]
+
[source,ts,subs="attributes+"]
----
import { Component } from '@angular/core';
import { EditorComponent } from '@tinymce/tinymce-angular';

@Component({
  selector: 'app-root',
  imports: [EditorComponent],
  template: `
  <h1>{productname} {productmajorversion} Angular Demo</h1>
  <editor
    [init]="init"
    licenseKey="gpl"
    apiKey="no-api-key"
  />
  `
})
export class AppComponent {
  init: EditorComponent['init'] = {
    plugins: 'lists link image table code help wordcount'
  };
}
----
+
. Update the `+apiKey+` with your own link:{accountsignup}/[{cloudname} API key].
endif::[]
ifeval::["{productSource}" != "cloud"]

+
[source,ts,subs="attributes+"]
----
import { Component } from '@angular/core';
import { EditorComponent } from '@tinymce/tinymce-angular';

@Component({
  selector: 'app-root',
  imports: [EditorComponent],
  template: `
  <h1>{productname} {productmajorversion} Angular Demo</h1>
  <editor
    [init]="init"
    licenseKey="gpl"
  />
  `
})
export class AppComponent {
  init: EditorComponent['init'] = {
    plugins: 'lists link image table code help wordcount'
  };
}
----

endif::[]

ifeval::["{productSource}" == "zip"]
. Unzip the content of the `+tinymce/js+` folder from the link:{download-enterprise}[{productname} zip] into the `+src+` folder.
endif::[]

include::partial$integrations/angular-load-tinymce-independently.adoc[]

. Run the Angular a development server
+
[source,sh]
----
ng serve
----

include::partial$integrations/angular-other-resources.adoc[]