:packageName: tinymce-angular

The https://github.com/tinymce/tinymce-angular[Official {productname} Angular component] integrates {productname} into Angular projects. This procedure creates a https://angular.io/guide/setup-local[basic Angular application] containing a {productname} editor.

For examples of the {productname} Angular integration, visit https://tinymce.github.io/tinymce-angular/[the tinymce-angular storybook].

== Prerequisites

This procedure requires https://nodejs.org/[Node.js (and npm)].

== Procedure

. On a command line or command prompt, install the https://angular.io/cli[Angular CLI Tool] package.
+
[source,sh]
----
npm install -g @angular/cli
----
. Create a new Angular project named `+tinymce-angular-demo+`.
+
[source,sh]
----
ng new --defaults --skip-git tinymce-angular-demo
----
. Change into the newly created directory.
+
[source,sh]
----
cd tinymce-angular-demo
----
ifeval::["{productSource}" == "package-manager"]
. Install the `+tinymce+` and `+tinymce-angular+` packages and save them to your `+package.json+` with `+--save+`.
+
[source,sh]
----
npm install --save tinymce @tinymce/tinymce-angular
----

endif::[]
ifeval::["{productSource}" != "package-manager"]
. Install the `+tinymce-angular+` package and save it to your `+package.json+` with `+--save+`.
+
[source,sh]
----
npm install --save @tinymce/tinymce-angular
----
endif::[]
. Using a text editor, open `+/path/to/tinymce-angular-demo/src/app/app.module.ts+` and replace the contents with:
+
[source,ts]
----
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { EditorModule } from '@tinymce/tinymce-angular';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    EditorModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
----
. Using a text editor, open `+/path/to/tinymce-angular-demo/src/app/app.component.html+` and replace the contents with:
+
[source,tsx,subs="attributes+"]
----
<h1>{productname} {productmajorversion} Angular Demo</h1>
<editor
  [init]="{ plugins: 'lists link image table code help wordcount' }"
></editor>
----

ifeval::["{productSource}" == "cloud"]
. Include the `+apiKey+` option in the editor element and include your link:{accountsignup}/[{cloudname} API key]. Such as:
+
[source,tsx]
----
<editor apiKey="your-api-key" [init]={ /* your other settings */ } ></editor>
----
endif::[]
ifeval::["{productSource}" == "package-manager"]
. Using a text editor; open `+angular.json+` and add {productname} to the `+assets+` property.
+
[source,json]
----
"assets": [
  { "glob": "**/*", "input": "node_modules/tinymce", "output": "/tinymce/" }
]
----

. Load TinyMCE.
* To load TinyMCE when the editor is initialized (also known as lazy loading), add a dependency provider to the module using the `+TINYMCE_SCRIPT_SRC+` token.
+
[source,ts]
----
import { EditorModule, TINYMCE_SCRIPT_SRC } from '@tinymce/tinymce-angular';
/* ... */
@NgModule({
  /* ... */
  imports: [
    EditorModule
  ],
  providers: [
    { provide: TINYMCE_SCRIPT_SRC, useValue: 'tinymce/tinymce.min.js' }
  ]
})
----
* To load TinyMCE when the page or application is loaded:
.. Open `+angular.json+` and add {productname} to the _global scripts_ tag.
+
[source,json]
----
"scripts": [
  "node_modules/tinymce/tinymce.min.js"
]
----
.. Update the editor configuration to include the `+base_url+` and `+suffix+` options.
+
[source,html]
----
<editor [init]="{
  base_url: '/tinymce', // Root for resources
  suffix: '.min'        // Suffix to use when loading resources
}"></editor>
----
endif::[]
ifeval::["{productSource}" == "zip"]

. Add the `+tinymce+` global to the application by: Deploying {productname} independent of the Angular application, or bundling {productname} with the Angular application.
* Deploy {productname} independent of the Angular application
+
To use an independent deployment of {productname}, add a script to either the `+<head>+` or the end of the `+<body>+` of the HTML file, such as:
+
[source,html]
----
<script src="/path/to/tinymce.min.js"></script>
----
+
To use an independent deployment of {productname} with the create a Angular application, add the script to `+/path/to/tinymce-angular-demo/src/app/app.component.html+`.
+
* Bundling {productname} with the Angular application using a module loader (such as Webpack).
+
--
:depth: 2
include::partial$integrations/bundling-integration.adoc[]
--
endif::[]

. Test the application using the Angular development server.
+
* To start the development server, navigate to the `+tinymce-angular-demo+` directory and run:
+
[source,sh]
----
ng serve --open
----

* To stop the development server, select on the command line or command prompt and press _Ctrl+C_.

ifeval::["{productSource}" == "package-manager"]

[#bunding-{productname}-with-an-angular-application]
== Bundling {productname} with an Angular application

include::partial$integrations/bundling-integration.adoc[]
endif::[]

== Deploying the application to a HTTP server

The application will require further configuration before it can be deployed to a production environment. For information on configuring the application for deployment, see: https://angular.io/guide/build[Angular Docs - Building and serving Angular apps] or https://angular.io/guide/deployment[Angular Docs - Deployment].

To deploy the application to a local HTTP Server:

. Navigate to the `+tinymce-angular-demo+` directory and run:
+
[source,sh]
----
ng build
----
. Copy the contents of the `+tinymce-angular-demo/dist+` directory to the root directory of the web server.

The application has now been deployed on the web server.

NOTE: Additional configuration is required to deploy the application outside the web server root directory, such as +http://localhost:<port>/my_angular_application+.

== Next Steps

* For examples of the {productname} integration, see: https://tinymce.github.io/tinymce-angular/[the tinymce-angular storybook].
* For information on customizing:
** {productname} integration, see: xref:angular-ref.adoc[Angular framework Technical Reference].
** {productname}, see: xref:basic-setup.adoc[Basic setup].
** The Angular application, see: https://angular.io/docs[the Angular documentation].
