== TinyMCE Blazor integration quick start guides

The https://github.com/tinymce/tinymce-blazor[Official {productname} Blazor component] integrates {productname} into https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor[Blazor applications].
This procedure creates a basic Blazor application and adds a {productname} editor using the {productname} Blazor integration. The basic Blazor application is based on the following tutorial: https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/[Microsoft .NET Blazor Tutorial - Build your first Blazor app].

Select from the following guides:

* <<usingvisualstudio,Using Visual Studio>>
* <<usingacommandpromptorterminal,Using a command prompt or terminal>>

=== Using Visual Studio

==== Prerequisites

This procedure requires:

* https://docs.microsoft.com/en-us/visualstudio/windows/[Microsoft Visual Studio]
* https://docs.microsoft.com/en-us/dotnet/core/install/[Microsoft .NET]

==== Procedure

. On the Visual Studio toolbar, click the https://docs.microsoft.com/en-us/visualstudio/ide/create-new-project[*New Project* button].
. Select the *Blazor Server App* template.
. Use the NuGet package manager console to install the `TinyMCE.Blazor` package, such as:
+
`sh
 Install-Package TinyMCE.Blazor
`

include::partial$integrations/blazor-postinstall.adoc[]

. To test the application, run the application by pressing *Ctrl+F5*.

=== Using a command prompt or terminal

==== Prerequisites

This procedure requires:

* https://docs.microsoft.com/en-us/dotnet/core/install/[Microsoft .NET]

==== Procedure

. Create a new Blazor project:
+
`sh
 dotnet new blazorserver -o BlazorApp --no-https
`

. Change into the new application directory:
+
`sh
 cd BlazorApp
`

. Install the {productname} Blazor integration:
+
`sh
 dotnet add package TinyMCE.Blazor
`

include::partial$integrations/blazor-postinstall.adoc[]

. Test the application using the .NET development server.
 ** To start the development server, in the project's root directory, run:
+
`sh
  dotnet watch run
 `
+
This will start a local development server, accessible at \http://localhost:5000.

 ** To stop the development server, select on the command line or command prompt and press _Ctrl+C_.

=== Next Steps

For information on customizing the integration, see:

* link:{baseurl}/general-configuration-guide/basic-setup/[{productname} basic setup].
* link:{baseurl}/integrations/blazor/#tinymceblazorintegrationtechnicalreference[The {productname} Blazor integration technical reference].
