include::partial$misc/admon-third-party-integration.adoc[]

For information on adding {productname} to a Django project, try using the Python-based `+django-tinymce+` package. For information on setting up `+django-tinymce+`, see: https://django-tinymce.readthedocs.io/en/latest/index.html[the django-tinymce Documentation].

ifeval::["{productSource}" == "cloud"]
To load {productname} from the {cloudname}, update the project’s `+settings.py+` file:

* Set `+TINYMCE_JS_URL+` to the {cloudname} CDN.
* Ensure `+TINYMCE_COMPRESSOR+` is set to `+False+`.

For example:

[source,py,subs="attributes+"]
----
TINYMCE_JS_URL = '{cdnurl}'
TINYMCE_COMPRESSOR = False
----

endif::[]
ifeval::["{productSource}" != "cloud"]
To download {productname} and use it with the `+django-tinymce+` package:

. Get the package from link:{gettiny}/[{productname} Downloads].
. Unzip the package and move the `'path/to/{prodnamecode}/'` directory into the django project.
. Add a URL path to the `{prodnamecode}` directory.
. Add the relevant configuration setting:
* If you do not need the `+TINYMCE_COMPRESSOR+` (`+TINYMCE_COMPRESSOR = False+`), add `+TINYMCE_JS_URL+` to the project’s `+settings.py+` file pointing to `+tinymce/tinymce.min.js+`. Such as:
+
[source,py]
----
TINYMCE_JS_URL = os.path.join(MEDIA_URL, "path/to/tinymce/tinymce.min.js")
TINYMCE_COMPRESSOR = False
----
* If you do need the `+TINYMCE_COMPRESSOR+` (`+TINYMCE_COMPRESSOR = TRUE+`), add `+TINYMCE_JS_ROOT+` to the project’s `+settings.py+` file pointing to the `+tinymce/+` root directory. Such as:
+
[source,py]
----
TINYMCE_JS_ROOT = os.path.join(MEDIA_URL, "path/to/tinymce")
TINYMCE_COMPRESSOR = True
----
. Set `+license_key+` in `+TINYMCE_DEFAULT_CONFIG+` in the project’s `+settings.py+` file. `+TINYMCE_DEFAULT_CONFIG+` replaces the default `+django-tinymce+` configuration, so include any other options the editor needs. Such as:
+
[source,py]
----
TINYMCE_DEFAULT_CONFIG = {
    "license_key": "gpl",
    "height": 500,
    "menubar": False,
    "plugins": "advlist,autolink,lists,link,image,charmap,preview,anchor,"
    "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,"
    "help,wordcount",
    "toolbar": "undo redo | blocks | bold italic backcolor | alignleft aligncenter "
    "alignright alignjustify | bullist numlist outdent indent | removeformat | help",
}
----
+
NOTE: The `+"license_key": "gpl"+` value is for self-hosting {productname} under the GNU General Public License (GPL). To use a commercial license, or to include premium plugins, replace `+"gpl"+` with a valid license key. For details, see xref:license-key.adoc#setting-the-license[Setting the license].

endif::[]
