ifeval::["{productSource}" == "cloud"]
:scriptSource: {cdnurl}
:packageSource: {cloudname}
endif::[]
ifeval::["{productSource}" == "composer"]
:scriptSource: "{ asset('js/tinymce/tinymce.min.js') }"
:packageSource: https://packagist.org/packages/tinymce/tinymce[TinyMCE Composer package]
endif::[]
ifeval::["{productSource}" == "zip"]
:scriptSource: "{ asset('js/tinymce/tinymce.min.js') }"
:packageSource: TinyMCE .zip package
endif::[]

This guide assists with adding {productname} from the {packageSource} to pages or views in Laravel. The example Laravel project created in this procedure is based on the Laravel project documented in the Laravel Docs, under https://laravel.com/docs/8.x/installation#installation-via-composer[Installation Via Composer]. The guide will create two blades: one for the JavaScript and another for the editor placeholder, to reflect how {productname} should be used in production environments.

== Requirements

This procedure assumes the following prerequisites have been installed:

* https://www.php.net/[PHP]
* https://getcomposer.org/[Composer]
ifeval::["{productSource}" != "cloud"]
* https://nodejs.org/[Node.js]
endif::[]

== Procedure

. On a command line (or command prompt), create a new Laravel project named `my-example-app` by running the following command:
+
[source, sh]
----
composer create-project laravel/laravel my-example-app
----

. Change into the root directory of the Laravel application, such as:
+
[source, sh]
----
cd my-example-app
----
+
ifeval::["{productSource}" != "cloud"]
. Install the required Node.js components, including https://laravel.com/docs/8.x/mix[Laravel Mix]:
+
[source,sh]
----
npm install
----
endif::[]
ifeval::["{productSource}" == "composer"]
. Add {productname} to the project using Composer:
+
[source,sh]
----
composer require tinymce/tinymce
----

. Add a Laravel Mix task to copy {productname} to the public files when Mix is run, such as:
+
[source,js]
.`webpack.mix.js`
----
mix.copyDirectory('vendor/tinymce/tinymce', 'public/js/tinymce');
----
endif::[]
ifeval::["{productSource}" == "zip"]
. Download {productname}.
+
* For Self-hosted Enterprise customers, visit [{companyname} - Self-hosted releases]({download-community})
* For the self-hosted {productname} community edition, visit [{accountpage} - Downloads]({download-enterprise})

. Extract (or unzip) the downloaded {productname} `.zip` file into the `resources/js/` directory of the Laravel project, such as:
+
[source, sh]
----
unzip ../tinymce_latest.zip -d resources/js
----

. Add a Laravel Mix task to copy {productname} to the public files when Mix is run, such as:
+
[source,js]
.`webpack.mix.js`
----
mix.copyDirectory('resources/js/tinymce/js/tinymce', 'public/js/tinymce');
----
endif::[]

ifeval::["{productSource}" != "cloud"]
. Run Laravel Mix to copy {productname} to the `public/js/` directory:
+
[source,sh]
----
npx mix
----
endif::[]

. Create a new reusable https://laravel.com/docs/8.x/blade#components[component (`blade.php`)] for the {productname} configuration, such as:
+
[source,sh]
----
php artisan make:component Head/tinymceConfig
----
+
This will create the blade `resources/views/components/head/tinymce-config.blade.php`.

. Open the newly created `.blade.php` file in a text editor and replace the contents with:
** The {productname} source script.
** A {productname} configuration.
+
For example:
+
[source, html, subs="attributes+"]
.`resources/views/components/head/tinymce-config.blade.php`
----
<script src="{scriptSource}" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: 'textarea#myeditorinstance', // Replace this CSS selector to match the placeholder element for TinyMCE
    plugins: 'code table lists',
    toolbar: 'undo redo | formatselect| bold italic | alignleft aligncenter alignright | indent outdent | bullist numlist | code | table'
  });
</script>
----

ifeval::["{productSource}" == "cloud"]
. Replace `no-api-key` in the {productname} source script with your {cloudname} API Key.
-
include::partial$misc/get-an-api-key.adoc[]
endif::[]

. Create a second blade containing a placeholder HTML element for {productname}, such as:
+
[source, sh]
----
php artisan make:component Forms/tinymceEditor
----
+
This will create the blade `resources/views/components/forms/tinymce-editor.blade.php`.

. Open the newly created `.blade.php` file in a text editor and replace the contents with a placeholder, matching the CSS selector provided to the `selector` option in the editor configuration.
+
For example:
+
[source,html]
.`resources/views/components/forms/tinymce-editor.blade.php`
----
<form method="post">
  <textarea id="myeditorinstance">Hello, World!</textarea>
</form>
----

. Add the blade components on the pages or views where {productname} is needed. The configuration blade (`Head/tinymceConfig` in this example) can be added to the `<head>` or at the end of the `<body>` on the target page or view. The placeholder blade (`Forms/tinymceEditor`) should be added where {productname} is required on the page.
+
For example:
+
[source,html]
.`resources/views/welcome.blade.php`
----
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TinyMCE in Laravel</title>
    <!-- Insert the blade containing the TinyMCE configuration and source script -->
    <x-head.tinymce-config/>
  </head>
  <body>
    <h1>TinyMCE in Laravel</h1>
    <!-- Insert the blade containing the TinyMCE placeholder HTML element -->
    <x-forms.tinymce-editor/>
  </body>
</html>
----

. Start the Laravel development server to verify that {productname} loads on the page or view, such as running the following command and opening the page on the localhost.
+
[source, sh]
----
php artisan serve
----

include::partial$misc/quickstart-next-steps.adoc[]
