\{% if productSource == 'cloud' %} The {cloudname} can be used to integrate {productname} into Ruby on Rails projects. This procedure creates a https://guides.rubyonrails.org/getting_started.html[basic Ruby on Rails application] containing a {productname} editor.

include::partial$integrations/rails-basic-proj.adoc[]

[arabic, start=3]
. Add the following lines within the `+<head>+` element of `+app/views/layouts/application.html.erb+` to automatically include {productname} on pages using the `+application+` layout:
+
[source,html]
----
<script src="{cdnurl}" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: '.tinymce',
    plugins: 'lists link image table code help wordcount'
  });
</script>
----
. Create a `+<textarea>+` with the initial content `+Hello, World!+` for {productname} by adding the following lines to `+app/views/welcome/index.html.erb+`:
+
[source,html]
----
<%= text_area_tag :content, "Hello, World!", :class => "tinymce" %>
----
. On a command line, from the project's root directory, start the Ruby on Rails server.
+
[source,sh]
----
rails server
----

The page containing the {productname} will be accessible at `+http://localhost:<port>/+` (default: http://localhost:3000/).
\{% elsif productSource == 'zip' %} Self-hosted instances of {productname} can be integrated into Ruby on Rails projects. This procedure creates a https://guides.rubyonrails.org/getting_started.html[basic Ruby on Rails application] containing a {productname} editor.

include::partial$integrations/rails-basic-proj.adoc[]

[arabic, start=3]
. Add the following lines within the `+<head>+` element of `+app/views/layouts/application.html.erb+` to automatically include {productname} on pages using the `+application+` layout:
+
[source,html]
----
<script src="/path/to/tinymce.min.js"></script>
<script>
  tinymce.init({
    selector: '.tinymce',
    plugins: 'lists link image table code help wordcount'
  });
</script>
----
. Create a `+<textarea>+` with the initial content `+Hello, World!+` for {productname} by adding the following lines to `+app/views/welcome/index.html.erb+`:
+
[source,html]
----
<%= text_area_tag :content, "Hello, World!", :class => "tinymce" %>
----
. On a command line, from the project's root directory, start the Ruby on Rails server.
+
[source,sh]
----
rails server
----

The page containing the {productname} will be accessible at `+http://localhost:<port>/+` (default: http://localhost:3000/).

\{% else %}

include::partial$misc/admon_third_party_integration.adoc[]

Sam Pohlenz maintains the https://github.com/spohlenz/tinymce-rails[{productname} Ruby on Rails gem] for integrating {productname} into the Ruby on Rails asset pipeline. This procedure creates a https://guides.rubyonrails.org/getting_started.html[basic Ruby on Rails application] containing a {productname} editor based on our link:basic-example.html[Basic example].

include::partial$integrations/rails-basic-proj.adoc[]

[arabic]
. Using a text editor, open the project `+Gemfile+` and add the line:
+
[source,sh]
----
gem 'tinymce-rails'
----
+
Do not add this line within a `+group+` - `+end+` element.
. Install the `+tinymce-rails+` gem using `+bundle+`:
+
[source,sh]
----
bundle install
----
. Create a {productname} configuration file.
[arabic]
.. Create the `+config/tinymce.yml+` file:
+
[source,sh]
----
touch config/tinymce.yml
----
.. Add a {productname} configuration. The configuration must be in the https://yaml.org/spec/1.2/spec.html[YAML format], such as:
+
[source,yml]
----
height: 500
menubar: false
toolbar:
  - undo redo | formatselect | bold italic | alignleft aligncenter alignright | bullist numlist outdent indent | removeformat | help
plugins:
  - insertdatetime media
  - table paste code help wordcount
----
. Add the following lines within the `+<head>+` element of `+app/views/layouts/application.html.erb+` to automatically include {productname} on pages using the `+application+` layout:
+
[source,html]
----
<%= tinymce_assets %>
<script type="text/javascript" src="/assets/tinymce.js"></script>
----
. Create a `+<textarea>+` with the initial content `+Hello, World!+` for {productname} by adding the following lines to `+app/views/welcome/index.html.erb+`:
+
[source,html]
----
<%= text_area_tag :content, "Hello, World!", :class => "tinymce" %>
<%= tinymce %>
----
. On a command line, from the project's root directory, start the Ruby on Rails server.
+
[source,sh]
----
rails server
----

The page containing the {productname} will be accessible at `+http://localhost:<port>/+` (default: http://localhost:3000/).

For information on creating advanced configurations for the third-party TinyMCE Ruby on Rails integration, visit the project on GitHub: https://github.com/spohlenz/tinymce-rails[Rails Integration for TinyMCE].
\{% endif %}
