== TinyMCE React integration quick start guide

The https://github.com/tinymce/tinymce-react[Official {productname} React component] integrates {productname} into React projects.
This procedure creates a https://github.com/facebook/create-react-app[basic React application] containing a {productname} editor based on our xref:demo/basic-example.adoc[Basic example].

For examples of the {productname} integration, visit https://tinymce.github.io/tinymce-react/[the tinymce-react storybook].

=== Prerequisites

This procedure requires:

* https://nodejs.org/[Node.js (and npm)].
* Access to `tinymce.min.js` on either:
 ** xref:cloud-deployment-guide/editor-and-features.adoc[{cloudname}].
 ** {productname} Self-hosted. See:
  *** xref:general-configuration-guide/advanced-install.adoc#packagemanagerinstalloptions[Installing {productname} - Package Managers].
  *** xref:general-configuration-guide/advanced-install.adoc#self-hostedinstall[Installing {productname} - Self-Hosted Download / Install].

=== Procedure

. Use the https://github.com/facebook/create-react-app[Create React App] package to create a new React project named `tinymce-react-demo`.
+
[source, sh]
----
 $ npx create-react-app tinymce-react-demo
----

. Change to the newly created directory.
+
[source, sh]
----
 $ cd tinymce-react-demo
----

. Install the `tinymce-react` package and save it to your `package.json` with `--save`.
+
[source, sh]
----
 $ npm install --save @tinymce/tinymce-react
----

. Using a text editor, open `./src/App.js` and replace the contents with:
+
[source,jsx]
----
import React, { useRef } from 'react';
import { Editor } from '@tinymce/tinymce-react';

export default function App() {
  const editorRef = useRef(null);
  const log = () => {
    if (editorRef.current) {
      console.log(editorRef.current.getContent());
    }
  };
  return (
    <>
      <Editor
        onInit={(evt, editor) => editorRef.current = editor}
        initialValue="<p>This is the initial content of the editor.</p>"
        init={{
          height: 500,
          menubar: false,
          plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table paste code help wordcount'
          ],
          toolbar: 'undo redo | formatselect | ' +
          'bold italic backcolor | alignleft aligncenter ' +
          'alignright alignjustify | bullist numlist outdent indent | ' +
          'removeformat | help',
          content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
        }}
      />
      <button onClick={log}>Log editor content</button>
    </>
  );
}
----
+
This JavaScript file will create the class `App` containing a {productname} editor configured to replicate the example on the xref:demo/basic-example.adoc[Basic example page].

. Provide access to {productname} using either {cloudname} or by self-hosting {productname}.
 ** *{cloudname}*
+
Include the `apiKey` option in the editor element and include your link:{accountsignup}[{cloudname} API key].
+
Such as:
+
[source, jsx]
----
<Editor apiKey='your-api-key' init={{ /* your other settings */ }} />
----

 ** *{productname} Self-hosted*
+
{productname} can be self-hosted by: deploying {productname} independent of the React application, or bundling {productname} with the React application.

  *** *Deploy {productname} independent of the React application using `tinymceScriptSrc`*
+
To use an independent deployment of {productname}, add the `tinymceScriptSrc` prop to specify the path to the {productname} script, such as:
+
[source,jsx]
----
<Editor
  tinymceScriptSrc="/path/to/tinymce.min.js">
</Editor>
----
+
To use `tinymceScriptSrc` with the `create-react-app` project, put the {productname} distribution in `./public` folder
and reference the path to the `public` folder using the environment
variable `process.env.PUBLIC_URL`, such as:
+
[source,jsx]
----
<Editor tinymceScriptSrc={process.env.PUBLIC_URL + '/tinymce/tinymce.min.js'}></Editor>
----

*** Deploy {productname} independent of the React application with a script tag
+
An alternative method is to add a script to either the `<head>` or the end of the `<body>` of the HTML file, such as:
+
[source, html]
----
<script src="/path/to/tinymce.min.js"></script>
----
+
To use the independently sourced {productname} with create-react-app, add the script tag to `./public/index.html`.
+
Normally the tinymce distribution would be put in the `public` folder
and referenced using the URL `%PUBLIC_URL%/tinymce/tinymce.min.js`, such as:
+
[source, html]
----
<script src="%PUBLIC_URL%/tinymce/tinymce.min.js"></script>
----
+
For information on self-hosting {productname}, see: xref:general-configuration-guide/advanced-install.adoc[Installing {productname}].

*** *Bundling {productname} with the React application using a module loader*
+
{companyname} does not recommend bundling `tinymce` and `tinymce-react` with a module loader. Bundling these packages can be complex and error prone.
+
To bundle {productname} using a module loader (such as Webpack and Browserify), see: xref:advanced/usage-with-module-loaders/index.adoc[Usage with module loaders].
+
Example of bundling:
+
[source,js]
----
import { Editor } from '@tinymce/tinymce-react';

// TinyMCE so the global var exists
// eslint-disable-next-line no-unused-vars
import tinymce from 'tinymce/tinymce';

// Theme
import 'tinymce/themes/silver';
// Toolbar icons
import 'tinymce/icons/default';
// Editor styles
import 'tinymce/skins/ui/oxide/skin.min.css';

// importing the plugin js.
import 'tinymce/plugins/advlist';
import 'tinymce/plugins/autolink';
import 'tinymce/plugins/link';
import 'tinymce/plugins/image';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/charmap';
import 'tinymce/plugins/hr';
import 'tinymce/plugins/anchor';
import 'tinymce/plugins/searchreplace';
import 'tinymce/plugins/wordcount';
import 'tinymce/plugins/code';
import 'tinymce/plugins/fullscreen';
import 'tinymce/plugins/insertdatetime';
import 'tinymce/plugins/media';
import 'tinymce/plugins/nonbreaking';
import 'tinymce/plugins/table';
import 'tinymce/plugins/template';
import 'tinymce/plugins/help';

// Content styles, including inline UI like fake cursors
/* eslint import/no-webpack-loader-syntax: off */
import contentCss from '!!raw-loader!tinymce/skins/content/default/content.min.css';
import contentUiCss from '!!raw-loader!tinymce/skins/ui/oxide/content.min.css';

export default function TinyEditorComponent(props) {
  // note that skin and content_css is disabled to avoid the normal
  // loading process and is instead loaded as a string via content_style
  return (
    <Editor
      init={{
        skin: false,
        content_css: false,
        content_style: [contentCss, contentUiCss].join('\n'),
      }}
    />
  );
}
----

. Test the application using the Node.js development server.
 ** To start the development server, navigate to the `tinymce-react-demo` directory and run:
+
[source, sh]
----
npm run start
----

 ** To stop the development server, select on the command line or command prompt and press _Ctrl+C_.

=== Deploying the application to a HTTP server.

The application will require further configuration before it can be deployed to a production environment. For information on configuring the application for deployment, see: https://create-react-app.dev/docs/deployment[Create React App - Deployment].

To deploy the application to a local HTTP Server:

. Navigate to the `tinymce-react-demo` directory and run:
+
[source, sh]
----
 $ npm run build
----

. Copy the contents of the `tinymce-react-demo/build` directory to the root directory of the web server.

The application has now been deployed on the web server.

NOTE: Additional configuration is required to deploy the application outside the web server root directory, such as \http://localhost:<port>/my_react_application.

=== Next Steps

* For examples of the {productname} integration, see: https://tinymce.github.io/tinymce-react/[the tinymce-react storybook].
* For information on customizing:
 ** {productname}, see: xref:general-configuration-guide/basic-setup.adoc[Basic setup].
 ** The React application, see: https://create-react-app.dev/docs/getting-started[Create React App] or https://reactjs.org/docs/getting-started.html[the React documentation].
