The https://github.com/tinymce/tinymce-react[Official \{\{site.productname}} React component] integrates \{\{site.productname}} into React projects. This procedure creates a https://github.com/facebook/create-react-app[basic React application] containing a \{\{site.productname}} editor.

For examples of the \{\{site.productname}} integration, visit https://tinymce.github.io/tinymce-react/[the tinymce-react storybook].

== Prerequisites

This procedure requires https://nodejs.org/[Node.js (and npm)].

== Procedure

[arabic]
. Use the https://github.com/facebook/create-react-app[Create React App] package to create a new React project named `+tinymce-react-demo+`.
+
[source,sh]
----
npx create-react-app tinymce-react-demo
----
. Change to the newly created directory.
+
[source,sh]
----
cd tinymce-react-demo
----

\{% if productSource == "package-manager" %} 3. Install the `+tinymce+` and `+tinymce-react+` packages and save them to your `+package.json+` with `+--save+`.

....
```sh
npm install --save tinymce @tinymce/tinymce-react
```
....

\{% else %} 3. Install the `+tinymce-react+` package and save it to your `+package.json+` with `+--save+`.

....
```sh
npm install --save @tinymce/tinymce-react
```
....

\{% endif %}

[arabic, start=4]
. Using a text editor, open `+./src/App.js+` and replace the contents with:
+
[source,jsx]
----
import React, { useRef } from 'react';
import { Editor } from '@tinymce/tinymce-react';

export default function App() {
  const editorRef = useRef(null);
  const log = () => {
    if (editorRef.current) {
      console.log(editorRef.current.getContent());
    }
  };
  return (
    <>
      <Editor
        onInit={(evt, editor) => editorRef.current = editor}
        initialValue="<p>This is the initial content of the editor.</p>"
        init={% raw %}{{{% endraw %} plugins: 'lists link image table code help wordcount' {% raw %}}}{% endraw %}
      />
      <button onClick={log}>Log editor content</button>
    </>
  );
}
----
+
This JavaScript file will create a component "`+App+`" containing a \{\{site.productname}} editor configured with basic features. \{% if productSource == "cloud" %}
. Include the `+apiKey+` option in the editor element and include your link:{accountsignup}/[\{\{site.cloudname}} API key].
+
Such as:
+
[source,jsx]
----
<Editor apiKey='your-api-key' init={% raw %}{{{% endraw %} /* your other settings */ {% raw %}}}{% endraw %} />
----

\{% elsif productSource == "package-manager" %} 5. Bundle \{\{site.productname}} with the React application using a module loader (such as Webpack).

\{% include integrations/bundling-integration.md package='tinymce-react' depth='1' %} \{% else %} 5. \{\{site.productname}} can be self-hosted by either: <<deployingtinymceindependent, Deploying \{\{site.productname}} independent of the React application>>, or <<bundle, Bundling \{\{site.productname}} with the React application>>. * Deploying \{\{site.productname}} independent of the React application. To use a \{\{site.productname}} instance that has been deployed independent of the React application, use: <<usingthetinyscriptsrcprop, the `+tinymceScriptSrc+` prop>>, or <<usinganhtmlscripttag, an HTML `+<script>+` tag>>. * Using the `+tinymceScriptSrc+` prop:

....
        1. To use an independent deployment of {productname}, add the `tinymceScriptSrc` prop to specify the path to the {productname} script, such as:

            ```jsx
            <Editor tinymceScriptSrc="/path/to/tinymce.min.js" />
            ```

        1. To use `tinymceScriptSrc` with the `create-react-app` project, put the {productname} distribution in `./public` folder and reference the path to the `public` folder using the environment variable `process.env.PUBLIC_URL`, such as:

            ```jsx
            <Editor tinymceScriptSrc={process.env.PUBLIC_URL + '/tinymce/tinymce.min.js'}>
            ```

    <a id="usinganhtmlscripttag" class="anchor"></a>
    * Using an HTML `<script>` tag:

        1. Add a script to either the `<head>` or the end of the `<body>` of the HTML file, such as:

            ```html
            <script src="/path/to/tinymce.min.js"></script>
            ```

        1. To use the independently sourced {productname} with create-react-app, add the script tag to `./public/index.html`.

            Normally the `tinymce` distribution would be put in the `public` folder and referenced using the URL `%PUBLIC_URL%/tinymce/tinymce.min.js`, such as:

            ```html
            <script src="%PUBLIC_URL%/tinymce/tinymce.min.js"></script>
            ```

<a id="bundle" class="anchor"></a>
* Bundle {productname} with the React application using a module loader (such as Webpack).
....

\{% include integrations/bundling-integration.md package='tinymce-react' depth='2' %} \{% endif %} 6. Test the application using the Node.js development server. * To start the development server, navigate to the `+tinymce-react-demo+` directory and run:

....
    ```sh
    npm run start
    ```

* To stop the development server, select on the command line or command prompt and press _Ctrl+C_.
....

== Deploying the application to a HTTP server

The application will require further configuration before it can be deployed to a production environment. For information on configuring the application for deployment, see: https://create-react-app.dev/docs/deployment[Create React App - Deployment].

To deploy the application to a local HTTP Server:

[arabic]
. Navigate to the `+tinymce-react-demo+` directory and run:
+
[source,sh]
----
npm run build
----
. Copy the contents of the `+tinymce-react-demo/build+` directory to the root directory of the web server.

The application has now been deployed on the web server.

____
*Note:* Additional configuration is required to deploy the application outside the web server root directory, such as http://localhost:<port>/my_react_application.
____

== Next Steps

* For examples of the \{\{site.productname}} integration, see: https://tinymce.github.io/tinymce-react/[the tinymce-react storybook].
* For information on customizing:
** \{\{site.productname}} integration, see: link:{baseurl}/how-to-guides/environment-setup/react/react-ref/[React framework Technical Reference].
** \{\{site.productname}}, see: link:{baseurl}/how-to-guides/learn-the-basics/basic-setup/[Basic setup].
** The React application, see: https://create-react-app.dev/docs/getting-started[Create React App] or https://reactjs.org/docs/getting-started.html[the React documentation].
