The https://github.com/tinymce/tinymce-svelte[Official {productname} Svelte component] integrates {productname} into https://svelte.dev/[Svelte applications]. This procedure creates a basic Svelte application containing a {productname} editor.

For examples of the {productname} integration, visit https://tinymce.github.io/tinymce-svelte/[the tinymce-svelte storybook].

== Prerequisites

This procedure requires https://nodejs.org/[Node.js (and npm)].

== Procedure

. Use the https://github.com/vitejs/vite[Vite] package to create a new Svelte project named `+tinymce-svelte-demo+`, such as:
+
[source,sh]
----
npm create vite@5 tinymce-svelte-demo -- --template svelte
----
. Change to the newly created directory.
+
[source,sh]
----
cd tinymce-svelte-demo
----

ifeval::["{productSource}" == "package-manager"]

. Install the `+tinymce+` and the `+tinymce-svelte+` editor component, such as:
+
[source,sh,subs="attributes+"]
----
npm install tinymce@^{productmajorversion} @tinymce/tinymce-svelte
----

endif::[]
ifeval::["{productSource}" != "package-manager"]

. Install the `+tinymce-svelte+` editor component, such as:
+
[source,sh]
----
npm install @tinymce/tinymce-svelte
----

endif::[]
ifeval::["{productSource}" == "cloud"]

. Open `+src/App.svelte+` and replace the contents with:
+
[source,html,subs="+macros"]
----
<script>
import Editor from '@tinymce/tinymce-svelte';
let conf = {
  height: 500,
  menubar: false,
  plugins: [
    'advlist', 'autolink', 'lists', 'link', 'image', 'charmap',
    'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
    'insertdatetime', 'media', 'table', 'preview', 'help', 'wordcount'
  ],
  toolbar: 'undo redo | blocks | ' +
    'bold italic forecolor | alignleft aligncenter ' +
    'alignright alignjustify | bullist numlist outdent indent | ' +
    'removeformat | help',
}
</script>
<main>
  <h1>Hello Tiny</h1>
  <Editor
    apiKey='your-tiny-cloud-api-key'
    pass:a[channel='{productmajorversion}']
    value='<p>This is the initial content of the editor.</p>'
    {conf}
  />
</main>
----

endif::[]
ifeval::["{productSource}" == "package-manager"]

. Install the `+vite-plugin-static-copy+` development dependency, such as:
+
[source,sh]
----
npm install -D vite-plugin-static-copy
----
. Open `+vite.config.js+` and configure the `+vite-plugin-static-copy+` plugin to copy {productname} to the `+public/+` directory, such as:
+
[source,js]
----
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import { viteStaticCopy } from 'vite-plugin-static-copy'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    viteStaticCopy({
      targets: [
        { src: 'node_modules/tinymce/*', dest: 'tinymce' }
      ]
    }),
    svelte()
  ],
})
----
. Open `+src/App.svelte+` and replace the contents with:
+
[source,html]
----
<script>
import Editor from '@tinymce/tinymce-svelte';
let conf = {
  height: 500,
  menubar: false,
  plugins: [
    'advlist', 'autolink', 'lists', 'link', 'image', 'charmap',
    'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
    'insertdatetime', 'media', 'table', 'preview', 'help', 'wordcount'
  ],
  toolbar: 'undo redo | blocks | ' +
    'bold italic forecolor | alignleft aligncenter ' +
    'alignright alignjustify | bullist numlist outdent indent | ' +
    'removeformat | help',
}
</script>
<main>
  <h1>Hello Tiny</h1>
  <Editor
    licenseKey='your-license-key'
    scriptSrc='tinymce/tinymce.min.js'
    value='<p>This is the initial content of the editor.</p>'
    {conf}
  />
</main>
----

endif::[]
ifeval::["{productSource}" == "zip"]

. Open `+src/App.svelte+` and replace the contents with:
+
[source,html]
----
<script>
import Editor from '@tinymce/tinymce-svelte';
let conf = {
  height: 500,
  menubar: false,
  plugins: [
    'advlist', 'autolink', 'lists', 'link', 'image', 'charmap',
    'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
    'insertdatetime', 'media', 'table', 'preview', 'help', 'wordcount'
  ],
  toolbar: 'undo redo | blocks | ' +
    'bold italic forecolor | alignleft aligncenter ' +
    'alignright alignjustify | bullist numlist outdent indent | ' +
    'removeformat | help',
}
</script>
<main>
  <h1>Hello Tiny</h1>
  <Editor
    licenseKey='your-license-key'
    scriptSrc='/path/or/url/to/tinymce.min.js'
    value='<p>This is the initial content of the editor.</p>'
    {conf}
  />
</main>
----

endif::[]

. Test the application using the Node.js development server.
* To start the development server, in the project's root directory, run:
+
[source,sh]
----
npm run dev
----
+
* To stop the development server, select on the command line or command prompt and press _Ctrl+C_.

== Next Steps

* For examples of the {productname} integration, see: https://tinymce.github.io/tinymce-svelte/[the tinymce-svelte storybook].
* For information on customizing, see:
** xref:basic-setup.adoc[{productname} basic setup].
** xref:svelte-ref.adoc[The {productname} Svelte integration technical reference].
