:packageName: tinymce-vue

The link:https://github.com/tinymce/tinymce-vue[Official {productname} Vue.js component] integrates {productname} into Vue.js projects, providing a powerful WYSIWYG editor within the Vue ecosystem. This procedure creates a link:https://cli.vuejs.org/guide/creating-a-project.html#vue-create[basic Vue.js application] containing a {productname} editor.

Version 4 and later of the `+tinymce-vue+` package supports Vue.js 3.x, but does not support Vue.js 2.x. For Vue.js 2.x applications, use `+tinymce-vue+` version 3.

include::partial$integrations/bundling-integrations-not-recommended-message.adoc[]

== Prerequisites

This procedure requires:

* link:https://nodejs.org/en/download/[Node.js LTS] (recommended).
* link:https://cli.vuejs.org/[Vue CLI] (optional).

== Procedure

. Create a new Vue project named `tinymce-vue-demo` using the link:https://github.com/vuejs/create-vue[Create Vue Tool].
* From a command line or command prompt create a Vue.js 3.x project: `+tinymce-vue-demo+`.
+
[source,sh]
----
npm create vue@3
----
* If a Vue.js 2.x project is required, instead use:
+
[source,sh]
----
npm create vue@2
----
+
[NOTE]
As per the link:https://vuejs.org/about/faq.html#what-s-the-difference-between-vue-2-and-vue-3[Vue FAQ], _Vue 2 will reach End of Life by the end of 2023_.

+
* Follow the prompts and type `+tinymce-vue-demo+` as the project name.
. Change into the newly created directory.
+
[source,sh]
----
cd tinymce-vue-demo
----

ifeval::["{productSource}" == "package-manager"]
. Install the `+tinymce+` and `+tinymce-vue+` packages.

* For Vue.js 3.x users:
+
[source,sh]
----
npm install tinymce "@tinymce/tinymce-vue"
----

* For Vue.js 2.x users:
+
[source,sh]
----
npm install tinymce "@tinymce/tinymce-vue@^3"
----

include::partial$integrations/premium-plugins-install-step-link.adoc[]
endif::[]
ifeval::["{productSource}" != "package-manager"]

. Install the `+tinymce-vue+` package.
* For Vue.js 3.x users:
+
[source,sh]
----
npm install "@tinymce/tinymce-vue"
----
* For Vue.js 2.x users:
+
[source,sh]
----
npm install "@tinymce/tinymce-vue@^3"
----

endif::[]

. Using a text editor, open `+/path/to/tinymce-vue-demo/src/App.vue+`.
.. Add a {productname} configuration to the `+<template>+` using the `+<editor>+` tag.
.. Add `+import Editor from '@tinymce/tinymce-vue'+` to the start of the `+<script>+`.
+
ifeval::["{productSource}" == "cloud"]
.For example:
[source,jsx]
----
<script setup>
import Editor from '@tinymce/tinymce-vue'
</script>

<template>
  <main id="sample">
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
    <editor
      id="uuid"
      apiKey="no-api-key"
      :init="{
        plugins: 'advlist anchor autolink charmap code fullscreen help image insertdatetime link lists media preview searchreplace table visualblocks wordcount',
        toolbar: 'undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        height: 500,
      }"
    />
  </main>
</template>

<style scoped>
.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  #sample {
    display: flex;
    flex-direction: column;
    place-items: center;
    width: 1000px;
  }
}
</style>
----
. Include the `+api-key+` option in the editor element and include your link:{accountsignup}/[{cloudname} API key]. Such as:
+
[source,html]
----
<editor api-key='no-api-key' :init="{ /* your other settings */ }" />
----
endif::[]
ifeval::["{productSource}" == "package-manager"]
+
.For example:
[source,jsx]
----
<script setup>
import Editor from '@tinymce/tinymce-vue'
</script>

<template>
  <main id="sample">
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
    <editor
      id="uuid"
      licenseKey="gpl"
      :init="{
        plugins: 'advlist anchor autolink charmap code fullscreen help image insertdatetime link lists media preview searchreplace table visualblocks wordcount',
        toolbar: 'undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        height: 500,
      }"
    />
  </main>
</template>

<style scoped>
.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  #sample {
    display: flex;
    flex-direction: column;
    place-items: center;
    width: 1000px;
  }
}
</style>
----
+
. Bundle {productname} with the Vue.js application using a module loader (such as Webpack).
--
include::partial$integrations/bundling-integration.adoc[]
--
endif::[]
ifeval::["{productSource}" == "zip"]
+
.For example:
[source,jsx]
----
<script setup>
import Editor from '@tinymce/tinymce-vue'
</script>

<template>
  <main id="sample">
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
    <editor
      id="uuid"
      licenseKey="gpl"
      :init="{
        plugins: 'advlist anchor autolink charmap code fullscreen help image insertdatetime link lists media preview searchreplace table visualblocks wordcount',
        toolbar: 'undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        height: 500,
      }"
    />
  </main>
</template>

<style scoped>
.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  #sample {
    display: flex;
    flex-direction: column;
    place-items: center;
    width: 1000px;
  }
}
</style>
----
+
. {productname} can be self-hosted by either:
** xref:deploying-tinymce-independent[Deploying {productname} independent of the Vue.js application],
** xref:zip-install.adoc[{productname} .zip deployments].

[[deploying-tinymce-independent]]
== Deploying {productname} independent of the Vue.js application

Deploying {productname} independent of the Vue.js application. To use a {productname} instance that has been deployed independent of the Vue.js application, use an HTML `+<script>+` tag.

To use an independent deployment of {productname}, add a script to either the `<head>` or the end of the `<body>` of the HTML file, such as:

[source,html]
----
<script src="/path/to/tinymce.min.js"></script>
----

To use an independent deployment of {productname} with the example create a Vue.js application, add the `+<script>+` to `/path/to/tinymce-vue-demo/public/index.html`.
endif::[]

. Test the application using the Node.js development server.
* To start the development server, navigate to the `+tinymce-vue-demo+` directory and run:
+
[source,sh]
----
npm run dev
----

* To stop the development server, select on the command line or command prompt and press `+Ctrl+C+`.

== Deploying the application to a HTTP server

The application will require further configuration before it can be deployed to a production environment. For information on configuring the application for deployment, see: link:https://vuejs.org/v2/guide/deployment.html[Vue.js - Production Deployment].

== Next Steps

* For examples of the {productname} integration, see: link:https://tinymce.github.io/tinymce-vue/[the tinymce-vue storybook].
* For information on customizing:
** {productname} integration, see: xref:vue-ref.adoc[Vue.js framework Technical Reference].
** {productname}, see: xref:basic-setup.adoc[Basic setup].
** The Vue.js application, see: link:https://vuejs.org/v2/guide/[Vue.js Documentation].
