*Covered in this section:*

* xref:installing-the-tinymce-vuejs-integration-using-npm[Installing the TinyMCE Vue.js integration using NPM]
* xref:using-the-tinymce-vuejs-integration[Using the TinyMCE Vue.js integration]
* xref:configuring-the-editor[Configuring the editor]
** xref:api-key[`+api-key+`]
** xref:cloud-channel[`+cloud-channel+`]
** xref:disabled[`+disabled+`]
** xref:id[`+id+`]
** xref:init[`+init+`]
** xref:initial-value[`+initial-value+`]
** xref:inline[`+inline+`]
** xref:model-events[`+model-events+`]
** xref:output-format[`+output-format+`]
** xref:plugins[`+plugins+`]
** xref:tag-name[`+tag-name+`]
** xref:toolbar[`+toolbar+`]
** xref:tinymce-script-src[`+tinymce-script-src+`]
* xref:form-input-bindings-v-model[Form Input Bindings: `+v-model+`]
* xref:event-binding[Event binding]

[[installing-the-tinymce-vuejs-integration-using-npm]]
== Installing the TinyMCE Vue.js integration using NPM

To install the `+tinymce-vue+` package and save it to your `+package.json+`.

* For Vue.js 3.x users:
+
[source,sh]
----
npm install --save "@tinymce/tinymce-vue@^4"
----
* For Vue.js 2.x users:
+
[source,sh]
----
npm install --save "@tinymce/tinymce-vue@^3"
----

[[using-the-tinymce-vuejs-integration]]
== Using the TinyMCE Vue.js integration

. Load the component.
* For bundle loader users (such as `+webpack+`, `+rollup+`, or `+browserify+`):
+
[source,js]
----
// es modules
import Editor from '@tinymce/tinymce-vue';
// commonjs require
// NOTE: default needed after require
var Editor = require('@tinymce/tinymce-vue').default;
----
* To load `+tinymce-vue+` in an HTML file:
+
[source,html]
----
<script src="/path/to/tinymce-vue.min.js"></script>
----
. Add the editor to the `+components+` property of the app:
+
[source,js]
----
// This might look different depending on how you have set up your app
// but the important part is the components property
var app = new Vue({
  el: '#app',
  data: { /* Your data */ },
  components: {
    'editor': Editor // <- Important part
  },
  methods: { /* Your methods */}
})
----
. Add the `+<editor>+` tag to the `+template+`
+
[source,html]
----
<editor api-key="API_KEY" :init="{plugins: 'wordcount'}" />
----

[[configuring-the-editor]]
== Configuring the editor

The editor accepts the following properties:

[source,html,subs="attributes+"]
----
<editor
  api-key="your-api-key"
  cloud-channel="{productmajorversion}"
  :disabled=false
  id="uuid"
  :init= "{ }"
  initial-value=""
  :inline=true
  model-events= ""
  plugins=""
  tag-name="div"
  toolbar=""
  value=""
/>
----

None of the configuration properties are *required* for `+tinymce-vue+` to work. Specify a {cloudname} API key using `+api-key+` to remove the `+This domain is not registered...+` warning message.

[[api-key]]
=== `+api-key+`

{cloudname} API key. Required for deployments using the {cloudname} to provide the {productname} editor.

include::partial$misc/get-an-api-key.adoc[]

*Type:* `+String+`

*Default value:* `+'no-api-key'+`

==== Example: using `+api-key+`

[source,html]
----
<editor
  api-key="your-api-key"
/>
----

[[cloud-channel]]
=== `+cloud-channel+`

*Type:* `+String+`

*Default value:* `'{productmajorversion}'`

*Possible values:* `'{productmajorversion}'`, `'{productmajorversion}-testing'`, `'{productmajorversion}-dev'`, `'{productminorversion}'`

Changes the {productname} build used for the editor to one of the following {cloudname} channels:

* `{productmajorversion}` (*Default*): The current enterprise release of {productname}.
* `{productmajorversion}-testing`: The current release candidate for the next enterprise release of {productname}.
* `{productmajorversion}-dev`: The nightly-build version of {productname}.
* A version number such as `{productminorversion}`: The specific enterprise release version of {productname}.

Such as:

[source,html,subs="attributes+"]
----
<editor
  api-key="your-api-key"
  cloud-channel="{productmajorversion}-dev"
  :init="{ /* your other settings */ }"
/>
----

For information {productname} development channels, see: xref:editor-plugin-version.adoc#{productmajorversion}-{productmajorversion}-testing-and-{productmajorversion}-dev-release-channels[Specifying the {productname} editor version deployed from Cloud - dev, testing, and stable releases].

[[disabled]]
=== `+disabled+`

The `+disabled+` property can dynamically switch the editor between a "disabled" (read-only) mode (`+true+`) and the standard editable mode (`+false+`).

*Type:* `+Boolean+`

*Default value:* `+false+`

*Possible values:* `+true+`, `+false+`

==== Example: using `+disabled+`

[source,html]
----
<editor
  :disabled=true
/>
----

[[id]]
=== `+id+`

An id for the editor. Used for retrieving the editor instance using the `+tinymce.get('ID')+` method.

*Type:* `+String+`

*Default value:* Automatically generated https://tools.ietf.org/html/rfc4122[UUID]

==== Example: using `+id+`

[source,html]
----
<editor
  id="uuid"
/>
----

[[init]]
=== `+init+`

Object sent to the `+tinymce.init+` method used to initialize the editor.

For information on the {productname} selector (`+tinymce.init+`), see: xref:basic-setup.adoc[Basic setup].

*Type:* `+Object+`

*Default value:* `+'{ }'+`

==== Example: using `+init+`

[source,html]
----
<editor
  :init="{
    plugins: 'lists link image paste help wordcount',
    toolbar: 'undo redo | blocks | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | help'
  }"
/>
----

[[initial-value]]
=== `+initial-value+`

Initial content of the editor when the editor is initialized.

*Type:* `+String+`

*Default value:* `+' '+`

==== Example: using `+initial-value+`

[source,html]
----
<editor
  initial-value="Once upon a time..."
/>
----

[[inline]]
=== `+inline+`

Used to set the editor to inline mode. Using `+<editor :inline=true />+` is the same as setting `+{inline: true}+` in the {productname} selector (`+tinymce.init+`).

For information on inline mode, see: xref:inline-editor-options.adoc#inline[User interface options - `+inline+`] and xref:use-tinymce-inline.adoc[Setup inline editing mode].

*Type:* `+Boolean+`

*Default value:* `+false+`

*Possible values:* `+true+`, `+false+`

==== Example: using `+inline+`

[source,html]
----
<editor
  :inline=true
/>
----

[[model-events]]
=== `+model-events+`

Sets the trigger events for xref:form-input-bindings-v-model[v-model events].

For a list of available {productname} events, see: xref:events.adoc#editor-core-events[Available Events - Editor events].

*Type:* `+String+`

*Default value:* `+'change keyup undo redo'+`.

==== Example: using `+model-events+`

[source,html]
----
<editor
  model-events="change keydown blur focus paste"
/>
----

[[output-format]]
=== `+output-format+`

Used to specify the format of the content emitted via the `+input+` event. This affects the format of the content used in conjunction with data binding.

*Type:* `+String+`

*Default value:* `+'html'+`

*Possible values:* `+'html'+`, `+'text'+`

==== Example: using `+output-format+`

[source,html]
----
<editor
  output-format="text"
/>
----

[[plugins]]
=== `+plugins+`

Used to include plugins for the editor. Using `+<editor plugins="lists code" />+` is the same as setting `+{plugins: 'lists code'}+` in the {productname} selector (`+tinymce.init+`).

For information on adding plugins to {productname}, see: xref:work-with-plugins.adoc[Add plugins to {productname}].

*Type:* `+String+` or `+Array+`

==== Example: using `+plugins+`

[source,html]
----
<editor
  plugins="lists code"
/>
----

[[tag-name]]
=== `+tag-name+`

Only valid when xref:inline[`+<editor :inline=true />+`]. Used to define the HTML element for the editor in inline mode.

*Type:* `+String+`

*Default value:* `+'div'+`

==== Example: using `+tag-name+`

[source,html]
----
<editor
  :inline=true
  tag-name="my-custom-tag"
/>
----

[[toolbar]]
=== `+toolbar+`

Used to set the toolbar for the editor. Using `+<editor toolbar="bold italic" />+` is the same as setting `+{toolbar: 'bold italic'}+` in the {productname} selector (`+tinymce.init+`).

For information setting the toolbar for {productname}, see: xref:toolbar-configuration-options.adoc#toolbar[User interface options - toolbar].

*Type:* `+String+`

*Possible values:* See xref:available-toolbar-buttons.adoc[Toolbar Buttons Available for {productname}].

==== Example: using `+toolbar+`

[source,html]
----
<editor
  plugins="code"
  toolbar="bold italic underline code"
/>
----

[[tinymce-script-src]]
=== `+tinymce-script-src+`

Use the `+tinymce-script-src+` prop to specify an external version of TinyMCE to lazy load.

*Type:* `+String+`

==== Example: using `+tinymce-script-src+`

[source,html]
----
<editor
  tinymce-script-src="/path/to/tinymce.min.js"
/>
----

[[form-input-bindings-v-model]]
== Form Input Bindings: `+v-model+`

The `+v-model+` directive can be used to create a two-way data binding. For example:

[source,html]
----
<editor v-model="content" />
----

For information on `+v-model+` and form input bindings, see: https://vuejs.org/guide/essentials/forms.html[Vue.js documentation - Form Input Bindings].

[[event-binding]]
== Event binding

Functions can be bound to editor events, such as:

[source,html]
----
<editor @selectionChange="handlerFunction" />
----

For older versions of Vue (Vue 2) supported by v3.x, the syntax for event bindings are: `<editor v-on:selectionChange="handlerFunction">` or `<editor @onSelectionChange="handlerFunction">`.

When the handler is called (*handlerFunction* in this example), it is called with two arguments:

* `+event+` - The TinyMCE event object.
* `+editor+` - A reference to the editor.

The following events are available:

* `+activate+`
* `+addUndo+`
* `+beforeAddUndo+`
* `+beforeExecCommand+`
* `+beforeGetContent+`
* `+beforeRenderUI+`
* `+beforeSetContent+`
* `+beforePaste+`
* `+blur+`
* `+change+`
* `+clearUndos+`
* `+click+`
* `+contextMenu+`
* `+copy+`
* `+cut+`
* `+dblclick+`
* `+deactivate+`
* `+dirty+`
* `+drag+`
* `+dragDrop+`
* `+dragEnd+`
* `+dragGesture+`
* `+dragOver+`
* `+drop+`
* `+execCommand+`
* `+focus+`
* `+focusIn+`
* `+focusOut+`
* `+getContent+`
* `+hide+`
* `+init+`
* `+keyDown+`
* `+keyPress+`
* `+keyUp+`
* `+loadContent+`
* `+mouseDown+`
* `+mouseEnter+`
* `+mouseLeave+`
* `+mouseMove+`
* `+mouseOut+`
* `+mouseOver+`
* `+mouseUp+`
* `+nodeChange+`
* `+objectResizeStart+`
* `+objectResized+`
* `+objectSelected+`
* `+paste+`
* `+postProcess+`
* `+postRender+`
* `+preProcess+`
* `+progressState+`
* `+redo+`
* `+remove+`
* `+reset+`
* `+saveContent+`
* `+selectionChange+`
* `+setAttrib+`
* `+setContent+`
* `+show+`
* `+submit+`
* `+undo+`
* `+visualAid+`
