:packageName: tinymce-vue

The https://github.com/tinymce/tinymce-vue[Official {productname} Vue.js component] integrates {productname} into Vue.js projects. This procedure creates a https://cli.vuejs.org/guide/creating-a-project.html#vue-create[basic Vue.js application] containing a {productname} editor.

Version 4 and onwards of the `+tinymce-vue+` package supports Vue.js 3.x, but does not support Vue.js 2.x. For Vue.js 2.x applications, use `+tinymce-vue+` version 3.

[[tinymce-vuejs-integration-live-examples]]
== TinyMCE Vue.js integration live examples

For examples of the {productname} Vue.js 3.x integration:

. Clone the `+tinymce/tinymce-vue+` GitHub repository. For example:
+
[source,sh]
----
git clone https://github.com/tinymce/tinymce-vue.git
----
. Install the required packages using `+yarn+`. For example:
+
[source,sh]
----
yarn install
----
. To start the demo server, run:
+
[source,sh]
----
yarn demo
----

The `+tinymce-vue+` demo is now running. Visit: http://localhost:3001.

== Prerequisites

This procedure requires https://nodejs.org/[Node.js (and npm)].

== Procedure

. Create a new Vue project named `tinymce-vue-demo` using the [Create Vue Tool](https://github.com/vuejs/create-vue).
* From a command line or command prompt create a Vue.js 3.x project: `+tinymce-vue-demo+`.
+
[source,sh]
----
npm create vue@3
----
* If you need to support IE11, you can create a Vue.js 2.x project instead:
+
[source,sh]
----
npm create vue@2
----
* Follow the prompts and type `+tinymce-vue-demo+` as the project name.
. Change into the newly created directory.
+
[source,sh]
----
cd tinymce-vue-demo
----

ifeval::["{productSource}" == "package-manager"]
. Install the `+tinymce+` and `+tinymce-vue+` packages and save them to your `+package.json+` with `+--save+`.

* For Vue.js 3.x users:
+
[source,sh]
----
npm install --save tinymce "@tinymce/tinymce-vue@^5"
----

* For Vue.js 2.x users:
+
[source,sh]
----
npm install --save tinymce "@tinymce/tinymce-vue@^3"
----

endif::[]
ifeval::["{productSource}" != "package-manager"]

. Install the `+tinymce-vue+` package and save it to your `+package.json+` with `+--save+`.
* For Vue.js 3.x users:
+
[source,sh]
----
npm install --save "@tinymce/tinymce-vue@^5"
----
* For Vue.js 2.x users:
+
[source,sh]
----
npm install --save "@tinymce/tinymce-vue@^3"
----

endif::[]

. Using a text editor, open `+/path/to/tinymce-vue-demo/src/App.vue+`.
.. Add a {productname} configuration to the `+<template>+` using the `+<Editor>+` tag.
.. Add `+import Editor from '@tinymce/tinymce-vue'+` to the start of the `+<script>+`.
+
For example:
+
[source,jsx]
----
<script setup>
import Editor from '@tinymce/tinymce-vue'
</script>

<template>
  <main id="sample">
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
    <Editor
      api-key="no-api-key"
      :init="{
        plugins: 'lists link image table code help wordcount'
      }"
    />
  </main>
</template>

<style scoped>
.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  #sample {
    display: flex;
    flex-direction: column;
    place-items: center;
    width: 1000px;
  }
}
</style>
----

ifeval::["{productSource}" == "cloud"]
. Include the `+api-key+` option in the editor element and include your link:{accountsignup}/[{cloudname} API key].
+
Such as:
+
[source,html]
----
<Editor api-key='your-api-key' :init="{ /* your other settings */ }" />
----
endif::[]
ifeval::["{productSource}" == "package-manager"]
. Bundle {productname} with the Vue.js application using a module loader (such as Webpack).
+
--
:depth: 1
include::partial$integrations/bundling-integration.adoc[]
--
endif::[]
ifeval::["{productSource}" == "zip"]
. {productname} can be self-hosted by either: xref:deploying-tinymce-independent[Deploying {productname} independent of the Vue.js application], or xref:bundle[Bundling {productname} with the Vue.js application].

* [[deploying-tinymce-independent]] Deploying {productname} independent of the Vue.js application. To use a {productname} instance that has been deployed independent of the Vue.js application, use an HTML `+<script>+` tag.
+
To use an independent deployment of {productname}, add a script to either the `<head>` or the end of the `<body>` of the HTML file, such as:
+
[source,html]
----
<script src="/path/to/tinymce.min.js"></script>
----
+
To use an independent deployment of {productname} with the example create a Vue.js application, add the script to `/path/to/tinymce-vue-demo/public/index.html`.

* [[bundle]] Bundle {productname} with the Vue.js application using a module loader (such as Webpack).
+
--
:depth: 2
include::partial$integrations/bundling-integration.adoc[]
--
endif::[]

. Test the application using the Node.js development server.
* To start the development server, navigate to the `+tinymce-vue-demo+` directory and run:
+
[source,sh]
----
npm run dev
----

* To stop the development server, select on the command line or command prompt and press _Ctrl+C_.

== Deploying the application to a HTTP server

The application will require further configuration before it can be deployed to a production environment. For information on configuring the application for deployment, see: https://vuejs.org/v2/guide/deployment.html[Vue.js - Production Deployment].

== Next Steps

* For examples of the {productname} integration, see: https://tinymce.github.io/tinymce-vue/[the tinymce-vue storybook].
* For information on customizing:
** {productname} integration, see: xref:vue-ref.adoc[Vue.js framework Technical Reference].
** {productname}, see: xref:basic-setup.adoc[Basic setup].
** The Vue.js application, see: https://vuejs.org/v2/guide/[Vue.js Documentation].
