== Contents

\{% include module-loading/bundling-plugins-that-cant-bundle.md %}

* link:#premiumplugins[Premium plugins]
** link:#accessibilitycheckera11ychecker[Accessibility Checker (a11ychecker)]
** link:#advancedcodeadvcode[Advanced Code (advcode)]
** link:#advancedtablesadvtable[Advanced Tables (advtable)]
** link:#casechangecasechange[Case Change (casechange)]
** link:#checklistchecklist[Checklist (checklist)]
** link:#commentstinycomments[Comments (tinycomments)]
** link:#enhancedmediaembedmediaembed[Enhanced Media Embed (mediaembed)]
** link:#exportexport[Export (export)]
** link:#formatpainterformatpainter[Format Painter (formatpainter)]
** link:#linkcheckerlinkchecker[Link Checker (linkchecker)]
** link:#mentionsmentions[Mentions (mentions)]
** link:#pageembedpageembed[Page Embed (pageembed)]
** link:#permanentpenpermanentpen[Permanent Pen (permanentpen)]
** link:#powerpastepowerpaste[PowerPaste (powerpaste)]
** link:#spellcheckerprotinymcespellchecker[Spell Checker Pro (tinymcespellchecker)]
* link:#communityplugins[Community plugins]
** link:#advancedlistadvlist[Advanced List (advlist)]
** link:#anchoranchor[Anchor (anchor)]
** link:#autolinkautolink[Autolink (autolink)]
** link:#autoresizeautoresize[Autoresize (autoresize)]
** link:#autosaveautosave[Autosave (autosave)]
** link:#charactermapcharmap[Character Map (charmap)]
** link:#codecode[Code (code)]
** link:#codesamplecodesample[Code Sample (codesample)]
** link:#directionalitydirectionality[Directionality (directionality)]
** link:#emoticonsemoticons[Emoticons (emoticons)]
** link:#fullscreenfullscreen[Full Screen (fullscreen)]
** link:#helphelp[Help (help)]
** link:#imageimage[Image (image)]
** link:#imagetoolsimagetools[Image Tools (imagetools)]
** link:#importcssimportcss[Import CSS (importcss)]
** link:#insertdatetimeinsertdatetime[Insert Date/Time (insertdatetime)]
** link:#linklink[Link (link)]
** link:#listslists[Lists (lists)]
** link:#mediamedia[Media (media)]
** link:#nonbreakingspacenonbreaking[Nonbreaking Space (nonbreaking)]
** link:#pagebreakpagebreak[Page Break (pagebreak)]
** link:#pastepaste[Paste (paste)]
** link:#previewpreview[Preview (preview)]
** link:#quicktoolbarquickbars[Quick Toolbar (quickbars)]
** link:#savesave[Save (save)]
** link:#searchandreplacesearchreplace[Search and Replace (searchreplace)]
** link:#tabletable[Table (table)]
** link:#templatetemplate[Template (template)]
** link:#textpatterntextpattern[Text Pattern (textpattern)]
** link:#tableofcontentstoc[Table of Contents (toc)]
** link:#visualblockvisualblocks[Visual Block (visualblocks)]
** link:#visualcharactersvisualchars[Visual Characters (visualchars)]
** link:#wordcountwordcount[Word Count (wordcount)]

== Premium plugins

=== Accessibility Checker (`+a11ychecker+`)

\{% include module-loading/admon-bundling-plugin-langs.md %}

\{% include plugin_files/plugin-file-list-a11ychecker.md %}

=== Advanced Code (`+advcode+`)

\{% include plugin_files/plugin-file-list-advcode.md %}

=== Advanced Tables (`+advtable+`)

\{% include plugin_files/plugin-file-list-advtable.md %}

=== Case Change (`+casechange+`)

\{% include plugin_files/plugin-file-list-casechange.md %}

=== Checklist (`+checklist+`)

\{% include plugin_files/plugin-file-list-checklist.md %}

=== Comments (`+tinycomments+`)

\{% include module-loading/admon-bundling-plugin-langs.md %}

\{% include plugin_files/plugin-file-list-tinycomments.md %}

=== Enhanced Media Embed (`+mediaembed+`)

\{% include plugin_files/plugin-file-list-mediaembed.md %}

=== Export (`+export+`)

\{% include module-loading/admon-bundling-plugin-langs.md %}

\{% include plugin_files/plugin-file-list-export.md %}

=== Format Painter (`+formatpainter+`)

\{% include plugin_files/plugin-file-list-formatpainter.md %}

=== Link Checker (`+linkchecker+`)

\{% include plugin_files/plugin-file-list-linkchecker.md %}

=== Mentions (`+mentions+`)

\{% include plugin_files/plugin-file-list-mentions.md %}

=== Page Embed (`+pageembed+`)

\{% include plugin_files/plugin-file-list-pageembed.md %}

=== Permanent Pen (`+permanentpen+`)

\{% include plugin_files/plugin-file-list-permanentpen.md %}

=== PowerPaste (`+powerpaste+`)

\{% include module-loading/admon-bundling-plugin-langs.md %}

\{% include plugin_files/plugin-file-list-powerpaste.md %}

=== Spell Checker Pro (`+tinymcespellchecker+`)

\{% include module-loading/admon-bundling-plugin-langs.md %}

\{% include plugin_files/plugin-file-list-tinymcespellchecker.md %}

== Community plugins

=== Advanced List (`+advlist+`)

\{% include plugin_files/plugin-file-list-advlist.md %}

=== Anchor (`+anchor+`)

\{% include plugin_files/plugin-file-list-anchor.md %}

=== Autolink (`+autolink+`)

\{% include plugin_files/plugin-file-list-autolink.md %}

=== Autoresize (`+autoresize+`)

\{% include plugin_files/plugin-file-list-autoresize.md %}

=== Autosave (`+autosave+`)

\{% include plugin_files/plugin-file-list-autosave.md %}

=== Character Map (`+charmap+`)

\{% include plugin_files/plugin-file-list-charmap.md %}

=== Code (`+code+`)

\{% include plugin_files/plugin-file-list-code.md %}

=== Code Sample (`+codesample+`)

\{% include plugin_files/plugin-file-list-codesample.md %}

=== Directionality (`+directionality+`)

\{% include plugin_files/plugin-file-list-directionality.md %}

=== Emoticons (`+emoticons+`)

\{% include plugin_files/plugin-file-list-emoticons.md %}

=== Full Screen (`+fullscreen+`)

\{% include plugin_files/plugin-file-list-fullscreen.md %}

=== Help (`+help+`)

\{% include plugin_files/plugin-file-list-help.md %}

=== Image (`+image+`)

\{% include plugin_files/plugin-file-list-image.md %}

=== Image Tools (`+imagetools+`)

\{% include plugin_files/plugin-file-list-imagetools.md %}

=== Import CSS (`+importcss+`)

\{% include plugin_files/plugin-file-list-importcss.md %}

=== Insert Date/Time (`+insertdatetime+`)

\{% include plugin_files/plugin-file-list-insertdatetime.md %}

=== Link (`+link+`)

\{% include plugin_files/plugin-file-list-link.md %}

=== Lists (`+lists+`)

\{% include plugin_files/plugin-file-list-lists.md %}

=== Media (`+media+`)

\{% include plugin_files/plugin-file-list-media.md %}

=== Nonbreaking Space (`+nonbreaking+`)

\{% include plugin_files/plugin-file-list-nonbreaking.md %}

=== Page Break (`+pagebreak+`)

\{% include plugin_files/plugin-file-list-pagebreak.md %}

=== Paste (`+paste+`)

\{% include plugin_files/plugin-file-list-paste.md %}

=== Preview (`+preview+`)

\{% include plugin_files/plugin-file-list-preview.md %}

=== Quick Toolbar (`+quickbars+`)

\{% include plugin_files/plugin-file-list-quickbars.md %}

=== Save (`+save+`)

\{% include plugin_files/plugin-file-list-save.md %}

=== Search and Replace (`+searchreplace+`)

\{% include plugin_files/plugin-file-list-searchreplace.md %}

=== Table (`+table+`)

\{% include plugin_files/plugin-file-list-table.md %}

=== Template (`+template+`)

\{% include plugin_files/plugin-file-list-template.md %}

=== Text Pattern (`+textpattern+`)

\{% include plugin_files/plugin-file-list-textpattern.md %}

=== Table of Contents (`+toc+`)

\{% include plugin_files/plugin-file-list-toc.md %}

=== Visual Block (`+visualblocks+`)

\{% include plugin_files/plugin-file-list-visualblocks.md %}

=== Visual Characters (`+visualchars+`)

\{% include plugin_files/plugin-file-list-visualchars.md %}

=== Word Count (`+wordcount+`)

\{% include plugin_files/plugin-file-list-wordcount.md %}
