ifeval::["{productSource}" == "cloud"]
:sourcename: the {cloudname}
endif::[]

ifeval::["{productSource}" == "composer"]
:sourcename: the Composer package manager
endif::[]

ifeval::["{productSource}" == "npm"]
:sourcename: npm or Yarn
endif::[]

ifeval::["{productSource}" == "bower"]
:sourcename: Bower
endif::[]

ifeval::["{productSource}" == "nuget"]
:sourcename: Nuget
endif::[]

ifeval::["{productSource}" == "zip"]
:sourcename: a {productname} .zip package
endif::[]

ifeval::["{productSource}" == "cloud"]
:scriptsource: {cdnurl}
endif::[]

ifeval::["{productSource}" != "cloud"]
:scriptsource: /path/or/uri/to/tinymce.min.js
endif::[]

== Install {productname} using {sourcename}

{productname} {productmajorversion} is a powerful and flexible rich text editor that can be embedded in web applications. This quick start covers how to add a {productname} editor to a web page using {sourcename}.

ifeval::["{productSource}" == "composer"]

To add {productname} to a PHP project using Composer, run the following on a command line:

[source,sh]
----
composer require tinymce/tinymce
----

The location of the main {productname} script will be: `+vendor/tinymce/tinymce/tinymce.min.js+`. Ensure the `+tinymce+` directory containing the `+tinymce.min.js+` file is accessible for the target page or application by either:

* Using a webserver route, or
* Copying the `+tinymce+` directory to a public folder using a build tool.
endif::[]
ifeval::["{productSource}" == "npm"]

To add {productname} to a project:

* Using npm, run the following on a command line:
+
[source,sh,subs="attributes+"]
----
npm install tinymce@^{productmajorversion}
----
* Using Yarn, run the following on a command line:
+
[source,sh,subs="attributes+"]
----
yarn add tinymce@^{productmajorversion}
----

The location of the main {productname} script will be: `+node_modules/tinymce/tinymce.min.js+`. Ensure the `+tinymce+` directory containing the `+tinymce.min.js+` file is accessible for the target page or application by either:

* Using a webserver route, or
* Copying the `+tinymce+` directory to a public folder using a build tool such as Gulp or Webpack.
endif::[]
ifeval::["{productSource}" == "bower"]

To add {productname} to a Bower project, run the following on a command line:

[source,sh,subs="attributes+"]
----
bower install tinymce#^{productmajorversion}
----

The location of the main {productname} script will be: `+bower_components/tinymce/tinymce.min.js+`. Ensure the `+tinymce+` directory containing the `+tinymce.min.js+` file is accessible for the target page or application by either:

* Using a webserver route, or
* Copying the `+tinymce+` directory to a public folder using a build tool such as Gulp or Webpack.
endif::[]
ifeval::["{productSource}" == "nuget"]
To add {productname} to a .NET project, run the following on a command line:

* Using the NuGet package manager console, run the following:
+
[source,sh]
----
Install-Package {productname}
----

* Using the `+dotnet+` CLI, run the following:
+
[source,sh]
----
dotnet add package {productname}
----

Ensure the `+tinymce+` directory containing the `+tinymce.min.js+` file is accessible for the target page or application by either:

* Using a webserver route, or
* Copying the `+tinymce+` directory to a public folder using a build tool.
endif::[]
ifeval::["{productSource}" == "composer"]

To deploy {productname} from a .zip archive:

include::partial$integrations/download-tinymce-zip.adoc[]

. Unzip the archive into a public folder of your webserver, such as:
+
[source,sh]
----
unzip tinymce_latest.zip -d /path/to/webserver/public/
----
+
The location of the main {productname} script will be: `+/path/to/webserver/public/tinymce/js/tinymce/tinymce.min.js+`.

endif::[]

== Include the {productname} script

Include the following line of code in the `+<head>+` of an HTML page.

[source,html,subs="attributes+"]
----
<script src="{scriptsource}" referrerpolicy="origin"></script>
----

== Initialize {productname} as part of a web form

Initialize {productname} {productmajorversion} on any element (or elements) on the web page by passing an object containing a `+selector+` value to `+tinymce.init()+`. The `+selector+` value can be any valid https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors[CSS selector].

For example: To replace `+<textarea id="mytextarea">+` with a {productname} {productmajorversion} editor instance, pass the selector `+'#mytextarea'+` to `+tinymce.init()+`.

For example:

ifeval::["{productSource}" == "cloud"]
[source,html,subs="attributes+"]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="{scriptsource}" referrerpolicy="origin"></script>
    <script>
      tinymce.init({
        selector: '#mytextarea'
      });
    </script>
  </head>

  <body>
    <h1>{productname} Quick Start Guide</h1>
    <form method="post">
      <textarea id="mytextarea">Hello, World!</textarea>
    </form>
  </body>
</html>
----
endif::[]

ifeval::["{productSource}" != "cloud"]
[source,html,subs="attributes+"]
----
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="{scriptsource}" referrerpolicy="origin"></script>
    <script>
      tinymce.init({
        selector: '#mytextarea',
        license_key: 'gpl|<your-license-key>'
      });
    </script>
  </head>

  <body>
    <h1>{productname} Quick Start Guide</h1>
    <form method="post">
      <textarea id="mytextarea">Hello, World!</textarea>
    </form>
  </body>
</html>
----
endif::[]

Adding this content to an HTML file and opening it in a web browser will load a {productname} editor, such as:

liveDemo::default[]

ifeval::["{productSource}" == "cloud"]
== Add your API key

To remove the notice:

**This domain is not registered with {cloudname}. Please see the quick start guide or create an account.**

Replace `+no-api-key+` in the source script (`+<script src=...+`) with a {cloudname} API key, which is created when signing up to the link:{accountsignup}/[{cloudname}].

Signing up for a {cloudname} API key will also provide a trial of the xref:plugins.adoc#premium-plugins[Premium Plugins].
endif::[]

ifeval::["{productSource}" != "cloud"]
include::partial$misc/setting-the-license.adoc[]

For more information on licensing, see the xref:license-key.adoc[License Key] guide.
endif::[]

== Save the content from the editor

To retrieve content from the editor, either process the content with a form handler or use the xref:apis/tinymce.editor.adoc#getContent[getContent API].

If you use a form handler, once the `+<form>+` is submitted, {productname} {productmajorversion} will `+POST+` the content in the same way as a normal HTML `+<textarea>+`, including the HTML elements and inline CSS of the editor content. The host's form handler can process the submitted content in the same way as content from a regular `+<textarea>+`.

include::partial$misc/quickstart-next-steps.adoc[]
