[[step-1-include-the-tinymce-script]]
=== Step 1: Include the TinyMCE script
anchor:step1includethetinymcescript[historical anchor]

Include this line of code in the `<head>` of your HTML page:

[source,html]
----
<script src="{{ site.cdnurl }}"></script>
----

[[step-2-initialize-tinymce-as-part-of-a-web-form]]
=== Step 2: Initialize TinyMCE as part of a web form
anchor:step2initializetinymceaspartofawebform[historical anchor]

With the script included, initialize TinyMCE on any element (or elements) in your web page.

Since TinyMCE lets you identify replaceable elements via a CSS selector, all you need do is pass an object that contains a `selector` to `tinymce.init()`.

In this example, let's replace `<textarea id='mytextarea'>` with a TinyMCE editor instance by passing the selector `'#mytextarea'` to `tinymce.init()`.

[source,html]
----
<!DOCTYPE html>
<html>
<head>
  <script src="{{ site.cdnurl }}"></script>
  <script type="text/javascript">
  tinymce.init({
    selector: '#mytextarea'
  });
  </script>
</head>

<body>
<h1>TinyMCE Quick Start Guide</h1>
  <form method="post">
    <textarea id="mytextarea">Hello, World!</textarea>
  </form>
</body>
</html>
----

[[step-3-saving-content-with-a-form-post]]
=== Step 3: Saving content with a form POST
anchor:step3savingcontentwithaformpost[historical anchor]

When the `<form>` is submitted the TinyMCE editor mimics the behavior of a normal HTML `<textarea>` during the `post`. In your form handler you can process the content submitted as if it had come from a regular `<textarea>`.

[[additional-information-about-using-the-cdn]]
=== Additional information about using the CDN
anchor:additionalinformationaboutusingthecdn[historical anchor]

There are a few things you need to consider when using the CDN version. If you wish to use any local plugins (like http://www.moxiemanager.com[MoxieManager] for example) you need to load them using the new link:{{ site.baseurl }}/configure/integration-and-setup/#external_plugins[`external_plugins`] option.

Also, if you wish to use a custom language, you need to enter the location of the language file into the new link:{{ site.baseurl }}/configure/localization/#language_url[`language_url`] option.

For a list of versions supported by the CacheFly CDN, check this text document: http://tinymce.cachefly.net/index.txt[\http://tinymce.cachefly.net/index.txt]

While we're at it a big shout out to http://www.cachefly.com/[Cachefly] who sponsors the CDN hosting of TinyMCE. If you haven't tried CacheFly now is the perfect time. Use promo code `TINYMCE` to get exclusive pay-as-you-go pricing. They also have a risk-free 2TB 14-day trial with no credit card required. Sign up at http://www.cachefly.com/[www.cachefly.com].

____
If you have decided to use the CDN, move on to the next step xref:api/work-with-plugins.adoc[working with plugins], where you'll start customizing TinyMCE. If you'd like to learn about other install options please keep reading.
____
