[[step-1-download-the-jquery-package]]
=== Step 1: Download the jQuery package
anchor:step1downloadthejquerypackage[historical anchor]

We have a jQuery plugin http://archive.tinymce.com/download/custom_package.php[available here] if you'd rather install TinyMCE using this method.

NOTE: the above link will take you to the custom package download page. When building your jQuery package, select "TinyMCE core (jQuery) under the "Core Elements" section.

As with the <<sdkinstall,Self-hosted>> option, unzip the package and move the `'path/to/tinymce/'` directory into a web accessible location on your web server (for example, `localhost`).

[[step-2-installation]]
=== Step 2: Installation
anchor:step2installation[historical anchor]

Include this line of code in the `<head>` of your page:

[source,html]
----
<script src="/path/to/tinymce/tinymce.min.js"></script>
<script src="/path/to/tinymce/jquery.tinymce.min.js"></script>
----

[[step-2-initialize-tinymce-as-part-of-a-web-form]]
=== Step 2: Initialize TinyMCE as part of a web form
anchor:step2initializetinymceaspartofawebform[historical anchor]

With the script included, initialize TinyMCE on any element (or elements) in your web page.

Since TinyMCE lets you identify replaceable elements via a CSS3 selector all you need do is pass an object that contains a selector to `tinymce.init()`.

In this example, let's replace `<textarea id='mytextarea'>` with a TinyMCE editor instance by passing the selector `'#mytextarea'` to `tinymce.init()`.

[source,html]
----
<!DOCTYPE html>
<html>
<head>
  <script src="/path/to/tinymce/tinymce.min.js"></script>
  <script src="/path/to/tinymce/jquery.tinymce.min.js"></script>
  <script type="text/javascript">
  tinymce.init({
    selector: '#mytextarea'
  });
  </script>
</head>

<body>
  <h1>TinyMCE Getting Started Guide</h1>
  <form method="post">
    <textarea id="mytextarea"></textarea>
  </form>
</body>
</html>
----

[[step-3-saving-content-with-a-form-post]]
=== Step 3: Saving Content with a form POST
anchor:step3savingcontentwithaformpost[historical anchor]

When the `form` is submitted the TinyMCE editor mimics the behavior of a normal HTML `<textarea>` during a form `post`. No additional configuration is required.

[NOTE]
====
If you have decided the use the jQuery version, move on to the next step link:{baseurl}/general-configuration-guide/work-with-plugins/index.html[Work with Plugins], where you'll start customizing TinyMCE. If you'd like to learn about other install options please keep reading.
====
