[[step-1-download-the-self-hosted-package]]
=== Step 1: Download the Self-hosted package
anchor:step1downloadtheself-hostedpackage[historical anchor]

If you'd rather download and install the script manually, get the package from link:{downloadspage}[TinyMCE Downloads].

Unzip the package and move the `'path/to/tinymce/'` directory into a web accessible location on your web server (for example, `localhost`).

[[step-2-include-the-tinymce-script]]
=== Step 2: Include the TinyMCE script
anchor:step2includethetinymcescript[historical anchor]

Include this line of code in the `<head>` of your HTML page:

[source,html]
----
<script src="path/to/tinymce/js/tinymce.min.js"></script>
----

[[step-3-initialize-tinymce-as-part-of-a-web-form]]
=== Step 3: Initialize TinyMCE as part of a web form
anchor:step3initializetinymceaspartofawebform[historical anchor]

With the script included, initialize TinyMCE on any element (or elements) in your web page.

Since TinyMCE lets you identify replaceable elements via a CSS selector, all you need do is pass an object that contains a `selector` to `tinymce.init()`.

In this example, let's replace `<textarea id='mytextarea'>` with a TinyMCE editor instance by passing the selector `'#mytextarea'` to `tinymce.init()`.

[source,html]
----
<!DOCTYPE html>
<html>
<head>
  <script src="/path/to/tinymce/tinymce.min.js"></script>
  <script type="text/javascript">
  tinymce.init({
    selector: '#mytextarea'
  });
  </script>
</head>

<body>
<h1>TinyMCE Quick Start Guide</h1>
  <form method="post">
    <textarea id="mytextarea">Hello, World!</textarea>
  </form>
</body>
</html>
----

[[step-4-saving-content-with-a-form-post]]
=== Step 4: Saving content with a form POST
anchor:step4savingcontentwithaformpost[historical anchor]

When the `<form>` is submitted the TinyMCE editor mimics the behavior of a normal HTML `<textarea>` during the `post`. In your form handler you can process the content submitted as if it had come from a regular `<textarea>`.

[NOTE]
====
If you decided to use the Self-hosted package, move on to the next step link:{baseurl}/general-configuration-guide/work-with-plugins/index.html[working with plugins], where you'll start customizing TinyMCE. If you'd like to learn about other install options please keep reading.
====
