== Upgrading to the latest version of TinyMCE 5

The procedure for upgrading to the latest version of {productname} {productmajorversion} depends on the deployment type.

* <<upgradingtinycloud,Upgrading Tiny Cloud>>.{% if enterprise != true %}
* <<#upgradingtinymceself-hostedusingapackagemanager,Upgrading TinyMCE Self-hosted using a package manager>>.{% endif %}
* <<upgradingtinymceself-hostedmanually,Upgrading TinyMCE Self-hosted manually>>.

=== Upgrading Tiny Cloud

{cloudname} provides the latest enterprise version of {productname}. For information on configuring {cloudname}, see: link:{baseurl}/cloud-deployment-guide/[the Cloud deployment guide].

{% if enterprise != true %}

=== Upgrading TinyMCE Self-hosted using a package manager

Select from the following package managers.

* <<yarn,Yarn>>
* <<npm,npm>>
* <<composer,Composer>>
* <<nuget,NuGet>>
* <<bower,Bower>>

==== Yarn

To upgrade to {productname} {productminorversion} using Yarn, run:
[source, sh]
----
$ yarn upgrade {prodnamecode}
----

==== npm

To upgrade to {productname} {productminorversion} using npm, run:
[source, sh]
----
$ npm install {prodnamecode}@latest --save
----

==== Composer

To upgrade to {productname} {productminorversion} using Composer, run:
[source, sh]
----
$ composer require tinymce/tinymce
----

==== NuGet

To upgrade to {productname} {productminorversion} using NuGet, run:
[source, sh]
----
$ Install-Package {productname}
----

==== Bower

To upgrade to {productname} {productminorversion} using Bower, run:
[source, sh]
----
$ bower install {prodnamecode}#{productminorversion} --save
----

{% endif %}

=== Upgrading TinyMCE Self-hosted manually

To upgrade to {productname} {productminorversion} using a manually downloaded package:

. Backup the `{prodnamecode}/` directory so any customizations can be restored after the upgrade.
+
Customizations for {productname} are typically stored in the following directories:
+
[source, sh]
----
 tinymce/
 ├── icons/
 ├── langs/
 ├── plugins/
 ├── skins/
 │   ├── content/
 │   └── ui/
 └── themes/
----

. Download the latest version of {productname}.
 ** For the {productname} Community Version, download `{prodnamecode}_<VERSION>.zip` from link:{gettiny}/self-hosted/[Get {productname} - Self-hosted releases], where _`<VERSION>`_ is the latest version of {productname}.
 ** For the {productname} Enterprise Version, download the *{productname} Enterprise Bundle* from link:{accountpageurl}/downloads/[{accountpage} > Downloads]. The downloaded file will be named `enterprise_latest.zip`.
. Extract the downloaded `.zip` file to a temporary location.
. (If required) Install the latest language packs from link:{gettiny}/language-packages/[Get {productname} - Language Packages].
. Copy customizations to the new `{prodnamecode}/` directory. Ensure that _only custom changes_ are added the new `{prodnamecode}/` directory, such as:
 ** Custom icons packs
 ** Custom plugins
 ** Custom skins
 ** Custom themes
. Delete the existing `{prodnamecode}/` directory and replace with the new `{prodnamecode}/`.

____
NOTE: To simplify the upgrade process to future versions of {productname}:

. Host the {productname} customizations outside of the `{prodnamecode}/` directory.
. Update your {productname} configuration as required:
 ** Set the location of content CSS customizations using link:{baseurl}/configure/content-appearance/#content_css[`content_css`].
 ** Set the location of custom plugins using link:{baseurl}/configure/integration-and-setup/#external_plugins[`external_plugins`].
 ** Set the location of custom icon packages using link:{baseurl}/configure/editor-appearance/#icons_url[`icons_url`] instead of `icons`.
 ** Set the location of custom localization packages using link:{baseurl}/configure/localization/#language_url[`language_url`] instead of `language`.
 ** Set the location of custom skin packages using link:{baseurl}/configure/editor-appearance/#skin_url[`skin_url`] instead of `skin`.
 ** Set the location of custom themes using link:{baseurl}/configure/editor-appearance/#theme_url[`theme_url`] instead of `theme`.
____
