== Upgrading to the latest version of {productname} {productmajorversion}

The procedure for upgrading to the latest version of {productname} {productmajorversion} depends on the deployment type.

* xref:upgrading-tiny-cloud[Upgrading Tiny Cloud].
ifeval::[{enterprise} != true]
* xref:upgrading-tinymce-self-hosted-using-a-package-manager[Upgrading TinyMCE Self-hosted using a package manager].
endif::[]
* xref:upgrading-tinymce-self-hosted-manually[Upgrading TinyMCE Self-hosted manually].

[[upgrading-tiny-cloud]]
=== Upgrading Tiny Cloud

{cloudname} provides the latest enterprise version of {productname}. For information on configuring {cloudname}, see: xref:editor-and-features.adoc[the Cloud deployment guide].

ifeval::[{enterprise} != true]

[[upgrading-tinymce-self-hosted-using-a-package-manager]]
=== Upgrading TinyMCE Self-hosted using a package manager

Select from the following package managers.

* xref:yarn[Yarn]
* xref:npm[npm]
* xref:composer[Composer]
* xref:nuget[NuGet]
* xref:bower[Bower]

[[yarn]]
==== Yarn

To upgrade to {productname} {productminorversion} using Yarn, run:

[source,sh,subs="attributes+"]
----
yarn upgrade {prodnamecode}
----

[[npm]]
==== npm

To upgrade to {productname} {productminorversion} using npm, run:

[source,sh,subs="attributes+"]
----
npm install {prodnamecode}@latest --save
----

[[composer]]
==== Composer

To upgrade to {productname} {productminorversion} using Composer, run:

[source,sh]
----
composer require tinymce/tinymce
----

[[nuget]]
==== NuGet

To upgrade to {productname} {productminorversion} using NuGet, run:

[source,sh,subs="attributes+"]
----
Install-Package {productname}
----

[[bower]]
==== Bower

To upgrade to {productname} {productminorversion} using Bower, run:

[source,sh,subs="attributes+"]
----
bower install {prodnamecode}#{productminorversion} --save
----

endif::[]

[[upgrading-tinymce-self-hosted-manually]]
=== Upgrading TinyMCE Self-hosted manually

To upgrade to {productname} {productminorversion} using a manually downloaded package:

. Backup the `{prodnamecode}/` directory so any customizations can be restored after the upgrade.
+
Customizations for {productname} are typically stored in the following directories:
+
[source,sh]
----
tinymce/
├── icons/
├── langs/
├── models/
├── plugins/
├── skins/
│   ├── content/
│   └── ui/
└── themes/
----
. Download the latest version of {productname}.
* For the {productname} Community Version, download `{prodnamecode}_<VERSION>.zip` from link:{gettiny}/self-hosted/[Get {productname} - Self-hosted releases], where `_<VERSION>_` is the latest version of {productname}.
* For the {productname} Enterprise Version, download the *{productname} Enterprise Bundle* from link:{accountpageurl}/downloads/[{accountpage} > Downloads]. The downloaded file will be named `+enterprise_latest.zip+`.
. Extract the downloaded `+.zip+` file to a temporary location.
. (If required) Install the latest language packs from link:{gettiny}/language-packages/[Get {productname} - Language Packages].
. Copy customizations to the new `{prodnamecode}/` directory. Ensure that _only custom changes_ are added the new `{prodnamecode}/` directory, such as:
* Custom icons packs
* Custom plugins
* Custom skins
* Custom themes
. Delete the existing `{prodnamecode}/` directory and replace with the new `{prodnamecode}/`.

[NOTE]
====
To simplify the upgrade process to future versions of {productname}:

. Host the {productname} customizations outside of the `{prodnamecode}/` directory.
. Update your {productname} configuration as required:
* Set the location of content CSS customizations using xref:add-css-options.adoc#content_css[`+content_css+`].
* Set the location of custom plugins using xref:editor-important-options.adoc#external_plugins[`+external_plugins+`].
* Set the location of custom icon packages using xref:editor-icons.adoc#icons_url[`+icons_url+`] instead of `+icons+`.
* Set the location of custom localization packages using xref:ui-localization.adoc#language_url[`+language_url+`] instead of `+language+`.
* Set the location of custom skin packages using xref:editor-skin.adoc#skin_url[`+skin_url+`] instead of `+skin+`.
* Set the location of custom themes using xref:editor-theme.adoc#theme_url[`+theme_url+`] instead of `+theme+`.
====
