:rootDir: ./../
:partialsDir: {rootDir}partials/
= .NET

TinyMCE Compressor gzips all javascript files in TinyMCE to a single streamable file. This makes the overall download size 75% smaller and reduces the number of requests to the web server. The initialization time for TinyMCE will also be reduced dramatically by using this script.

[[installation]]
== Installation

Here is a step by step list on how to install the GZip compressor.

. Download TinyMCE Compressor .NET from the https://www.tiny.cloud/docs/advanced/using-the-gzip-compressors/[download page].
. Copy the `tiny_mce_gzip.js` and `tiny_mce_gzip.aspx` to the tiny_mce directory. The same directory that contains the `tiny_mce.js` file.
. Remove the current script tag. +++<script type="text/javascript" src="tinymce/jscripts/tiny_mce/tiny_mce.js">++++++</script>+++
. Add the new new GZip script +++<script type="text/javascript" src="tinymce/jscripts/tiny_mce/tiny_mce_gzip.js">++++++</script>+++.
. Add the new GZip initialization call that will tell the compressor what to include in the output. This should be the sum of all and themes, plugins contained on page.

[[example-of-initialization]]
== Example of initialization
anchor:exampleofinitialization[historical anchor]

The example below will pack both themes and all plugins into one file/steam. Remove the things you don't need or add you custom plugins to the settings below. Remember that the tinyMCE_GZ.init call must be placed in it's own script tag.

[source,html]
----
<script type="text/javascript" src="tinymce/jscripts/tiny_mce/tiny_mce_gzip.js"></script>
<script type="text/javascript">
tinyMCE_GZ.init({
  plugins : 'style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras',
  themes : 'simple,advanced',
  languages : 'en',
  disk_cache : true,
  debug : false
});
</script>
<script type="text/javascript">
tinyMCE.init({
  .. your normal init ..
});
</script>
----

[[troubleshooting]]
== Troubleshooting

* The GZip compressor can fail to load if the server has odd settings or is missing the required support for it to function. To see compilation errors or other problems we suggest that you use HTTP debugging tools like http://www.fiddlertool.com/fiddler/[Fiddler] or http://www.getfirebug.com/[Firebug] you can also point you browser directly to the GZip file.
* Consult the changelog of this script and make sure that you use the latest version of TinyMCE. These two parts are pretty much tied together so there is no guarantee that it will work with older versions of TinyMCE.
* Visit the https://community.tiny.cloud[TinyMCE Community forum] for help with the TinyMCE Gzip Compressor.
* To remove a plugin, remember to remove it both from tinyMCE_GZ.init and TinyMCE.init.
* To add a plugin, remember to add it both to the tinyMCE_GZ.init and the tinyMCE.init calls.

[[license-notice]]
== License notice
anchor:licensenotice[historical anchor]

This library is under LGPL license but it uses a GPL:ed third party library for the gzip compression. This third party library can be used in commercial applications. Review the"ICSharpCode.SharpZipLib_Readme.rtf" for details.
