= Other/third-party compressors

The TinyMCE compressor is a backend for reducing the overall download and initialization time for TinyMCE it consists of a JavaScript loader that requests a php/aspx/jsp/cfm page that compresses the specified resources using GZip. This method makes the overall download 75% smaller and the number of requests will also be reduced. The overall initialization time for TinyMCE will be reduced dramatically if you use this script for loading TinyMCE.

[[what-is-gzip]]
== What is GZip? 
anchor:whatisgzip[historical anchor]

gzip is short for GNU zip, a GNU free software file compression program. It was created by Jean-loup Gailly and Mark Adler. Version 0.1 was first publicly released on October 31, 1992. Version 1.0 followed in February 1993. The HTTP1.1 protocol allows for clients to optionally request the compression of content from the server.

[[third-party-compressors]]
== Third-party Compressors 
anchor:third-partycompressors[historical anchor]

There are also other compressors maintained by third-party developers:

* http://code.google.com/p/django-tinymce/[Django]
* http://hacks.traveljury.com/perl_compressor/[Perl]
* http://tinymcehammer.lanalot.com/[Ruby On Rails]
* http://garbageburrito.com/home/tinymce_gzip_compressor_ruby_on_rails_plugin[Ruby]
* http://code.google.com/p/tinymce-python-compressor/[Python (CGI)]
