////
Replace vnumtxt with the version number such as: X.Y.Z
////

= TinyMCE vnumtxt: Core changes
:navtitle: Core changes
:description: The core changes for TinyMCE vnumtxt
:keywords: releasenotes, bugfixes, defaults

== Contents

* xref:fixes[Fixes]
* xref:new-features[New features]
* xref:enhancements[Enhancements]
* xref:functionality-changes[Functionality changes]

[[fixes]]
== Fixes

{productname} 6.0.2 provides fixes for the following bugs:

* changelog

[[new-features]]
== New features

The following new features were added for the {productname} vnumtxt release.

=== Feature name

=== Additional new features

{productname} vnumtxt introduces the following minor new features:

* changelog

[[enhancements]]
== Enhancements

The following enhancements were made for the {productname} vnumtxt release.

=== Enhancement name

=== Additional enhancements

{productname} vnumtxt introduces the following minor enhancements:

* changelog

[[functionality-changes]]
== Functionality changes

The following functionality changes were made for the {productname} vnumtxt release:

* changelog
