[[troubleshooting-context-toolbar-and-context-form-conflicts]]
== Troubleshooting context toolbar and context form conflicts [[contexttoolbarpriority]][[contextformpriority]]

There are situations where custom context toolbars or custom context forms may conflict with:

* Context toolbars or context forms provided by the editor,
* Context toolbars or context forms provided by the link:{rootDir}plugins/quickbars.html[Quick Toolbars (`quickbars`) plugin],
* Other custom context toolbars or custom context forms.

ifeval::[{productmajorversion} < 6]
How these conflicts are resolved depends on the {productname} version.

* For {productname} 5.3 or newer, see: <<determiningthedisplaypriorityofcontexttoolbarsandcontextforms,Determining the display priority of context toolbars and context forms>>.
* For {productname} 5.0, 5.1, or 5.2; see: <<determiningthedisplaypriorityofcontexttoolbarsandcontextformslegacybehavior,Determining the display priority of context toolbars and context forms (Legacy behavior)>>.
endif::[]

[[determining-the-display-priority-of-context-toolbars-and-context-forms]]
=== Determining the display priority of context toolbars and context forms

There are three settings that determine the priority of context toolbars and context forms: `scope`, `predicate`, and `position`.

* `scope` - Sets the context toolbar or form as either: specific to certain types of content (`node`), or a general (global) toolbar or form (`editor`).
* `predicate` - A function for determining if the context menu or form applies to the current selection or cursor position. This function should return a boolean value.
* `position` - Sets where the context toolbar or form is rendered, relative to the current context (`selection`, `node`, or `line`).

Generally:

* Context _forms_ are prioritized over context _toolbars_.
* Context _forms_ with `scope: 'node'` are prioritized over `scope: 'editor'`.
* Only one context _form_ can be shown for a selection or cursor position, they cannot be concatenated to another context _form_ or a context _toolbar_.
* Context _toolbars_ with `position: 'selection'` are prioritized over `position: 'node'`, and `position: 'line'` is given the lowest priority.
* The editor concatenates context _toolbars_ when there is more than one context _toolbar_ to display with:
 ** A matching predicate,
 ** The same `scope` and `position` values.

+
Concatenated toolbars may contain duplicate toolbar items.
* If no matching context toolbars or context forms are found for the selection or cursor position, then editor will recursively search for matches on the parent node of the current node, until it reaches the root node of the editor content.

[[description-of-how-context-toolbars-and-context-forms-are-prioritized]]
==== Description of how context toolbars and context forms are prioritized

The following description can be used for troubleshooting the behavior of context toolbars and context forms.

The editor will determine which context toolbars or context form will be shown using following process:

. Find all *context forms* with both:
 ** `scope: 'node'`
 ** A predicate matching the current selection or cursor position.

+
If there are any matching *context forms*, the first one found will be displayed in the editor and the process will end.
. Find all *context forms* with both:
 ** `scope: 'editor'`
 ** A predicate matching the current selection or cursor position.

+
If there are any matching *context forms*, the first one found will be displayed in the editor and the process will end.
. Find all *context toolbars* with both:
 ** Any `scope`
 ** A predicate matching the current selection or cursor position.

+
If there are any matching *context toolbars*, the editor will prioritize the context toolbars based on the `position` value.
 ** All context toolbars with `position: 'selection'` or `position: 'node'` will be concatenated, the concatenated toolbar will be displayed, and the process will end.
 ** Otherwise, all context toolbars with `position: line` will be concatenated, the concatenated toolbar will be displayed, and the process will end.
. Find all *context forms* with both:
 ** Any `scope`
 ** A predicate matching the *parent node* of the current node, selection, or cursor position.

+
If there are any *context forms* found, the first one found will be displayed in the editor and the process will end.
. Find all *context toolbars* with both:
 ** Any `scope`
 ** A predicate matching the *parent node* of the current node, selection, or cursor position.

+
If there are any matching *context toolbars*, the editor will prioritize the context toolbars based on the `position` value.
 ** If there are context toolbars with `position: 'selection'`, they will be concatenated, the concatenated toolbar will be displayed, and the process will end.
 ** If there are context toolbars with `position: 'node'`, they will be concatenated, the concatenated toolbar will be displayed, and the process will end.
 ** Otherwise, all context toolbars with `position: line` will be concatenated, the concatenated toolbar will be displayed, and the process will end.
. Repeat step 4 and 5 for each successive parent node in the DOM for context toolbars and context forms with `scope: node` until either:
 ** A matching context form or context toolbars are found and displayed,
 ** The root node of the editor is reached.

ifeval::[{productmajorversion} < 6]
[[determining-the-display-priority-of-contexttoolbars-and-contextforms-legacy-behavior]]
=== Determining the display priority of context toolbars and context forms (Legacy behavior)

There are two settings that determine determine the priority: `predicate` and `scope`. The priority system mirrors the old link:{url}/docs-4x/themes/inlite/#quicklink[inlite] theme from TinyMCE 4. The `predicate` is a function that takes in the current context position and returns a boolean. The `scope` is either `node` or `editor`. The whole priority process works as follows:

. The current cursor position is stored to use as the first current context position.
. For this current context position, each predicate with `scope: node` in the registered ContextForm is called. Currently, the order they are checked-in cannot be specified. The first predicate that passes will `win` and that ContextForm will be shown.
. If no predicates (`scope: node`) match the current context position, then all of the `scope: editor` predicates are tried. The first one that matches the editor context wins.
. If no `scope: editor` predicates match, then the new context position is calculated by going up the tree one level to the parent node. All `scope: node` predicates are then checked again. As soon as one matches, it _wins_ and that ContextForm is shown. If nothing matches, it goes up the tree and tries again.

NOTE: Only `scope: node` predicates are checked at this stage. The `scope: editor` predicate is only checked once and that check only happens in (2).

CAUTION: Since the order in which the ContextForms and ContextToolbars are checked is not specified, try not to have their predicates overlap.

endif::[]
